import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.LineBundleFrame
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.SheafOfModulesIsLineBundle
import MiyaokaMori.AlgebraicGeometry.Modules.FramePowIsFrame
import MiyaokaMori.AlgebraicGeometry.Modules.NonvanishingLocusTensorSection
import MiyaokaMori.AlgebraicGeometry.Modules.Stalk.ModulesTensorStalk
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.LineBundleNonvanishingLocus
import MiyaokaMori.AlgebraicGeometry.Modules.Dual.ModulesDualEv
import MiyaokaMori.AlgebraicGeometry.Modules.Dual.LineBundleDualEvalIso
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.Stacks01cmTensorHom
import MiyaokaMori.AlgebraicGeometry.Modules.Dual.DualSheafOld
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.TensorSectionsBilinear
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.ModuleSheafFrameIso
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.FrameLocus
import MiyaokaMori.Paper.S3PositiveLine.Realization.ProjectivizationOfNowhereZeroTuple
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.Stacks01ct

/-! # Frame lemmas for the jet chart trivialization

Frame lemmas needed by `JetChartTrivialization` (§3 of the paper: "a frame ε of L on V identifies
C̃_(κ)(L)|_V with Spec(O(V)[t]/(t^{κ+1}))"):

* `LineBundle.Frame.isFrame`: the section of a `LineBundle.Frame` (a section generating every stalk) is a
  frame in the sense of `Modules.IsFrame` (`r ↦ r • ε|_W` bijective on every `W ≤ V`);
* `Modules.IsFrame.tensorSections`: the tensor of two frames is a frame of the (monoidal) tensor product;
* `Modules.IsFrame.exists_dual_pairing_one_dualEv`: a frame `ε` of a line bundle `L` on `V` has a dual frame
  `δ ∈ Γ(V, L^∨)` (`L^∨ = Modules.dual L`) with `⟨δ, ε⟩ = 1`, the pairing being `Modules.dualEv L`
  (the `dual` spelling of `internalHomEval L O_X`; `dual L = internalHom L O_X` is a definitional equality whose
  check is expensive, so it is crossed exactly once, by the `subst` recipe of `ModulesDualEv`);
* `Modules.IsFrame.dual_of_pairing_eq_one`: a section `δ` of `L^∨` with `⟨δ, ε⟩ = 1` (pairing `Modules.dualEv L`)
  for a frame `ε` of the line bundle `L` is a frame of `L^∨`.

Sources: Stacks 01CR (invertible sheaves are locally generated by one section), 01CY (a nowhere-vanishing
section of a line bundle is a frame), 01CB (stalk of a tensor product), 01CT (`𝓗om(L, O) ⊗ L ≅ O`).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency false

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

open scoped CategoryTheory.MonoidalCategory

namespace AlgebraicGeometry.Scheme.Modules

variable {X : AlgebraicGeometry.Scheme.{u}}

/-- **A section of a line bundle generating every stalk is a frame** (Stacks 01CR/01CY). If
`span {e_y} = ⊤` in `M_y` for every `y ∈ W`, then `e_y ∉ 𝔪_y M_y`: otherwise `e_y = a • e_y` with
`a ∈ 𝔪_y`, so `(1 - a) • e_y = 0` with `1 - a` a unit, so `e_y = 0` and `M_y = span {0} = 0`; but a
local frame `e'` of the line bundle near `y` has `e'_y ∉ 𝔪_y M_y` (`IsFrame.germ_notMem_maximalIdeal_smul`),
contradicting `M_y = 0`. Then `IsFrame.of_forall_germ_notMem`. -/
theorem IsFrame.of_forall_span_germ_eq_top (M : X.Modules) [M.IsLineBundle] {W : X.Opens} (e : Γ(M, W))
    (h : ∀ (y : X) (hy : y ∈ W),
      Submodule.span (X.presheaf.stalk y) ({M.presheaf.germ W y hy e} : Set (M.presheaf.stalk y)) = ⊤) :
    IsFrame M W e := by
  refine IsFrame.of_forall_germ_notMem M e ?_
  intro y hy hmem
  have hspan := h y hy
  rw [← hspan] at hmem
  obtain ⟨a, ha, hae⟩ := (Submodule.mem_smul_span_singleton (M := M.presheaf.stalk y)).mp hmem
  have hu : IsUnit (1 - a) :=
    IsLocalRing.isUnit_one_sub_self_of_mem_nonunits a ((IsLocalRing.mem_maximalIdeal a).mp ha)
  have hz : (1 - a) • (M.presheaf.germ W y hy e : M.presheaf.stalk y) = (1 - a) • (0 : M.presheaf.stalk y) := by
    rw [sub_smul, one_smul, hae, sub_self, smul_zero]
  have hey : (M.presheaf.germ W y hy e : M.presheaf.stalk y) = 0 := hu.smul_left_cancel.mp hz
  have htop : (⊤ : Submodule (X.presheaf.stalk y) (M.presheaf.stalk y)) = ⊥ := by
    rw [← hspan, hey, Submodule.span_zero_singleton]
  obtain ⟨W', -, hyW', e', he'⟩ := exists_frame_le M hy
  apply he'.germ_notMem_maximalIdeal_smul hyW'
  have h0 : (M.presheaf.germ W' y hyW' e' : M.presheaf.stalk y) = 0 :=
    (Submodule.eq_bot_iff _).mp htop _ Submodule.mem_top
  rw [h0]
  exact Submodule.zero_mem _

/-- **The tensor of two frames is a frame** (Stacks 01CB): if `a` is a frame of the line bundle `A` and
`b` a frame of the line bundle `B` on `W`, then `a ⊗ b = tensorSections A B W a b` is a frame of `A ⊗ B`
on `W`. Proof: `A ⊗ B` is a line bundle; at `y ∈ W`, `(A ⊗ B)_y ≅ A_y ⊗ B_y ≅ 𝒪_y ⊗ 𝒪_y ≅ 𝒪_y`
(`tensorStalkEquiv`, `IsFrame.stalkEquiv`) sends the germ of `a ⊗ b` to `1 ∉ 𝔪_y`, so the germ is not in
`𝔪_y (A ⊗ B)_y`; conclude with `IsFrame.of_forall_germ_notMem`. -/
theorem IsFrame.tensorSections {A B : X.Modules} [A.IsLineBundle] [B.IsLineBundle] {W : X.Opens}
    {a : Γ(A, W)} {b : Γ(B, W)} (ha : IsFrame A W a) (hb : IsFrame B W b) :
    IsFrame (CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules) A B) W
      (AlgebraicGeometry.Scheme.Modules.tensorSections A B W a b) := by
  haveI : (CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules) A B).IsLineBundle :=
    IsLineBundle.of_iso (AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj A B)
  refine IsFrame.of_forall_germ_notMem _ _ ?_
  intro y hy hmem
  let Θ : (CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules) A B).presheaf.stalk y
      ≃ₗ[X.presheaf.stalk y] X.presheaf.stalk y :=
    tensorStalkEquiv A B y ≪≫ₗ
      TensorProduct.congr (ha.stalkEquiv hy).symm (hb.stalkEquiv hy).symm ≪≫ₗ
      TensorProduct.lid (X.presheaf.stalk y) (X.presheaf.stalk y)
  rw [mem_maximalIdeal_smul_top_iff_of_linearEquiv Θ] at hmem
  have h1 : (ha.stalkEquiv hy).symm (A.presheaf.germ W y hy a) = 1 := by
    rw [LinearEquiv.symm_apply_eq, IsFrame.stalkEquiv_apply, one_smul]
  have h2 : (hb.stalkEquiv hy).symm (B.presheaf.germ W y hy b) = 1 := by
    rw [LinearEquiv.symm_apply_eq, IsFrame.stalkEquiv_apply, one_smul]
  have hΘ : Θ ((CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules) A B).presheaf.germ W y hy
      (AlgebraicGeometry.Scheme.Modules.tensorSections A B W a b)) = 1 := by
    have s1 := tensorStalkEquiv_germ_tensorSections A B y W hy a b
    show TensorProduct.lid (X.presheaf.stalk y) (X.presheaf.stalk y)
      (TensorProduct.congr (ha.stalkEquiv hy).symm (hb.stalkEquiv hy).symm
        (tensorStalkEquiv A B y ((CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules) A B).presheaf.germ
          W y hy (AlgebraicGeometry.Scheme.Modules.tensorSections A B W a b)))) = 1
    rw [s1, TensorProduct.congr_tmul, h1, h2, TensorProduct.lid_tmul, one_smul]
  rw [hΘ] at hmem
  exact (Ideal.ne_top_iff_one _).mp (IsLocalRing.maximalIdeal.isMaximal _).ne_top hmem

/-- **Dual frame with pairing `1`** (Stacks 01CT), `dual` spelling. Generalize `dual L` to `D` with
`hD : D = internalHom L O_X` (`Modules.dual_eq_internalHom`) and the pairing to `ev` with
`HEq ev (internalHomEval L O_X)` (`Modules.dualEv_heq`); after `subst` everything is in the `internalHom`
spelling, where `δ := hf.dualFrameSheaf` (the sheafification of the local functional `x ↦ coord_ε(x)`) pairs
with `ε` to `coord_ε(ε) = 1` (`internalHomEval_tensorSections_unit`, `IsFrame.localHomEval_dualFrameLocal`). -/
theorem IsFrame.exists_dual_pairing_one_dualEv {L : X.Modules} {V : X.Opens} {e : Γ(L, V)} (hf : IsFrame L V e) :
    ∃ δ : Γ(AlgebraicGeometry.Scheme.Modules.dual L, V),
      (AlgebraicGeometry.Scheme.Modules.dualEv L).app V
        (AlgebraicGeometry.Scheme.Modules.tensorSections (AlgebraicGeometry.Scheme.Modules.dual L) L V δ e) =
          (1 : Γ(X, V)) := by
  have key : ∀ (D : X.Modules) (hD : D = AlgebraicGeometry.Scheme.Modules.internalHom L (SheafOfModules.unit X.ringCatSheaf))
      (ev : CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules) D L ⟶ SheafOfModules.unit X.ringCatSheaf)
      (hev : HEq ev (AlgebraicGeometry.Scheme.Modules.internalHomEval L (SheafOfModules.unit X.ringCatSheaf))),
      ∃ δ : Γ(D, V), ev.app V (AlgebraicGeometry.Scheme.Modules.tensorSections D L V δ e) = (1 : Γ(X, V)) := by
    intro D hD ev hev
    subst hD
    have hev2 := eq_of_heq hev
    subst hev2
    have h2 := AlgebraicGeometry.Scheme.Modules.internalHomEval_tensorSections_unit L
      (SheafOfModules.unit X.ringCatSheaf) V hf.dualFrameLocal e
    have h3 := hf.localHomEval_dualFrameLocal (1 : Γ(X, V))
    rw [one_smul] at h3
    exact ⟨hf.dualFrameSheaf, h2.trans h3⟩
  exact key (AlgebraicGeometry.Scheme.Modules.dual L) (AlgebraicGeometry.Scheme.Modules.dual_eq_internalHom L)
    (AlgebraicGeometry.Scheme.Modules.dualEv L) (AlgebraicGeometry.Scheme.Modules.dualEv_heq L)

/-- **A section of `L^∨` pairing to `1` with a section of `L` is a frame of `L^∨`** (Stacks 01CT). Near
`y ∈ V` take a frame `ψ` of the line bundle `L^∨` on `W ≤ V` (`exists_frame_le`) and write `δ|_W = c • ψ`;
restricting `⟨δ, ε⟩ = 1` to `W` and using bilinearity gives `c · ⟨ψ, ε|_W⟩ = 1`, so `c` is a unit and
`δ|_W` is a frame (`IsFrame.of_isUnit_coord`); frames glue (`IsFrame.of_iSup`). -/
theorem IsFrame.dual_of_pairing_eq_one {L : X.Modules} [L.IsLineBundle] {V : X.Opens} {e : Γ(L, V)}
    {δ : Γ(AlgebraicGeometry.Scheme.Modules.dual L, V)}
    (h : (AlgebraicGeometry.Scheme.Modules.dualEv L).app V
      (AlgebraicGeometry.Scheme.Modules.tensorSections (AlgebraicGeometry.Scheme.Modules.dual L) L V δ e) =
        (1 : Γ(X, V))) :
    IsFrame (AlgebraicGeometry.Scheme.Modules.dual L) V δ := by
  have key : ∀ y : X, y ∈ V → ∃ W : X.Opens, ∃ hW : W ≤ V, y ∈ W ∧
      IsFrame (AlgebraicGeometry.Scheme.Modules.dual L) W ((AlgebraicGeometry.Scheme.Modules.dual L).res hW δ) := by
    intro y hy
    obtain ⟨W, hWV, hyW, ψ, hψ⟩ := exists_frame_le (AlgebraicGeometry.Scheme.Modules.dual L) hy
    refine ⟨W, hWV, hyW, ?_⟩
    apply hψ.of_isUnit_coord
    have hδ : (AlgebraicGeometry.Scheme.Modules.dual L).res hWV δ =
        hψ.coord le_rfl ((AlgebraicGeometry.Scheme.Modules.dual L).res hWV δ) • ψ := by
      have h1 := hψ.coord_smul_frame le_rfl ((AlgebraicGeometry.Scheme.Modules.dual L).res hWV δ)
      rw [res_self] at h1
      exact h1.symm
    have h1 : (AlgebraicGeometry.Scheme.Modules.dualEv L).app W
        (AlgebraicGeometry.Scheme.Modules.tensorSections (AlgebraicGeometry.Scheme.Modules.dual L) L W
          ((AlgebraicGeometry.Scheme.Modules.dual L).res hWV δ) (L.res hWV e)) = (1 : Γ(X, W)) := by
      have h2 := congrArg
        (@AlgebraicGeometry.Scheme.Modules.res X (SheafOfModules.unit X.ringCatSheaf) W V hWV) h
      rw [← Hom.app_res (AlgebraicGeometry.Scheme.Modules.dualEv L) hWV] at h2
      have h3 : (CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules)
            (AlgebraicGeometry.Scheme.Modules.dual L) L).res hWV
          (AlgebraicGeometry.Scheme.Modules.tensorSections (AlgebraicGeometry.Scheme.Modules.dual L) L V δ e) =
          AlgebraicGeometry.Scheme.Modules.tensorSections (AlgebraicGeometry.Scheme.Modules.dual L) L W
            ((AlgebraicGeometry.Scheme.Modules.dual L).res hWV δ) (L.res hWV e) :=
        tensorSections_restrict (AlgebraicGeometry.Scheme.Modules.dual L) L (homOfLE hWV) δ e
      rw [h3] at h2
      refine h2.trans ?_
      exact map_one (X.presheaf.map (homOfLE hWV).op).hom
    rw [hδ, tensorSections_smul_left (AlgebraicGeometry.Scheme.Modules.dual L) L W _ ψ (L.res hWV e) _ rfl,
      Hom.app_smul] at h1
    exact isUnit_iff_exists.mpr ⟨_, h1, (mul_comm _ _).trans h1⟩
  choose W hWV hyW hfr using key
  refine IsFrame.of_iSup (fun y : V => W y.1 y.2) (fun y => hWV y.1 y.2) ?_ (fun y => hfr y.1 y.2)
  intro y hy
  exact Opens.mem_iSup.mpr ⟨⟨y, hy⟩, hyW y hy⟩

end AlgebraicGeometry.Scheme.Modules

/-- **The section of a `LineBundle.Frame` is a frame** in the sense of `Modules.IsFrame`: its `generates`
field says `span {ε_y} = L_y` at every `y ∈ V` (`IsFrame.of_forall_span_germ_eq_top`). -/
theorem LineBundle.Frame.isFrame {k : Type u} [Field k] {X : Variety k} {L : LineBundle X}
    {V : X.toScheme.Opens} (ε : LineBundle.Frame L V) :
    AlgebraicGeometry.Scheme.Modules.IsFrame L.toModules V ε.section_ :=
  AlgebraicGeometry.Scheme.Modules.IsFrame.of_forall_span_germ_eq_top L.toModules ε.section_ ε.generates

end
