import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.ModulesTensorMonoidalIso
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.ModulesTensorSectionsCoherence
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.TensorSectionsBilinear
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.GradedQuasicoherentAlgebra
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.QcSectionsBasicOpenLocalization
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.SheafOfModulesMonoidal

/-! # The graded section ring of a graded quasi-coherent algebra

The graded section ring `A(U) = ⊕_m Γ(U, S_m)` of a graded quasi-coherent algebra on an open `U`
(multiplication from `S.mul`); restriction gives graded ring homomorphisms `A(U′) → A(U)`, the unit gives
`Γ(U, O) → A(U)_0`. For affine `U ⊆ U′`, the irrelevant ideal of `A(U)` is generated by the image of that of
`A(U′)` (the hypothesis of `Proj.map`); the proof uses only elementwise facts about localization at
principal opens (`QcSectionsBasicOpenLocalization`) and "principal opens cover ⟺ generate the unit
ideal" on affine opens.

Reference: the `𝒜(U)` of Stacks 01NN; §2 of the paper.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false
set_option backward.defeqAttrib.useBackward true

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

open scoped CategoryTheory.MonoidalCategory DirectSum TensorProduct


/-! ## Bilinearity of the section pairing (`tensorSections` is `Γ(X, U)`-linear in each variable)

`tensorSections A B U a b` is by definition the value of `tensorSectionsHom A B` on the pure tensor `a ⊗ₜ b`
(`Modules.tensorSectionsHom_app`, `rfl`), and `tensorSectionsHom A B` is `Γ(X, U)`-linear on each open, so
bilinearity comes from `add_tmul` / `tmul_add` / `zero_tmul` / `tmul_zero` / `smul_tmul'` of `TensorProduct`. -/

namespace AlgebraicGeometry.Scheme.Modules

variable {X : AlgebraicGeometry.Scheme.{u}}

theorem tensorSections_zero_left (A B : X.Modules) (U : X.Opens)
    (b : B.val.obj (Opposite.op U)) :
    AlgebraicGeometry.Scheme.Modules.tensorSections A B U 0 b = 0 := by
  rw [← tensorSectionsHom_app A B U 0 b, TensorProduct.zero_tmul]
  exact map_zero _

theorem tensorSections_zero_right (A B : X.Modules) (U : X.Opens)
    (a : A.val.obj (Opposite.op U)) :
    AlgebraicGeometry.Scheme.Modules.tensorSections A B U a 0 = 0 := by
  rw [← tensorSectionsHom_app A B U a 0, TensorProduct.tmul_zero]
  exact map_zero _

end AlgebraicGeometry.Scheme.Modules

/-- The sections `Γ(U, S_m)` of the `m`-th graded piece on `U` (an additive group). -/

abbrev AlgebraicGeometry.Scheme.GradedQCAlgebra.sectionsPiece {X : AlgebraicGeometry.Scheme.{u}}
    (S : X.GradedQCAlgebra) (U : X.Opens) (m : ℕ) : Type u :=
  (S.part m).val.obj (Opposite.op U)

/-! ## Graded multiplication and unit on sections (the morphism-level axioms of `GradedQCAlgebra` are first
evaluated pointwise in named lemmas, then used to fill the fields of `DirectSum.GCommRing`, to avoid referring
to instances not yet built) -/

namespace AlgebraicGeometry.Scheme.GradedQCAlgebra

variable {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra) (U : X.Opens)

/-- The graded multiplication of sections: `S.mul m n` on the section pairing. -/
def sectionsGMul {m n : ℕ} (a : S.sectionsPiece U m) (b : S.sectionsPiece U n) :
    S.sectionsPiece U (m + n) :=
  (S.mul m n).app U
    (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part m) (S.part n) U a b)

/-- The graded unit of sections: `S.one` sends `1 ∈ Γ(X, U)` into the `0`-th piece. -/
def sectionsGOne : S.sectionsPiece U 0 :=
  S.one.app U (1 : Γ(X, U))

/-- Transport along an equality of pieces: for `m = n`, the value of `eqToHom` on a section gives the same
`GradedMonoid` element as the original section. -/
theorem mk_eqToHom_app {m n : ℕ} (e : m = n) (x : S.sectionsPiece U m) :
    (GradedMonoid.mk n ((CategoryTheory.eqToHom (congrArg S.part e)).app U x) :
        GradedMonoid (S.sectionsPiece U)) = GradedMonoid.mk m x := by
  subst e
  rfl

theorem sectionsGMul_zero_right {m n : ℕ} (a : S.sectionsPiece U m) :
    S.sectionsGMul U a (0 : S.sectionsPiece U n) = 0 := by
  show (S.mul m n).app U
    (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part m) (S.part n) U a 0) = 0
  rw [AlgebraicGeometry.Scheme.Modules.tensorSections_zero_right]
  exact map_zero _

theorem sectionsGMul_zero_left {m n : ℕ} (b : S.sectionsPiece U n) :
    S.sectionsGMul U (0 : S.sectionsPiece U m) b = 0 := by
  show (S.mul m n).app U
    (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part m) (S.part n) U 0 b) = 0
  rw [AlgebraicGeometry.Scheme.Modules.tensorSections_zero_left]
  exact map_zero _

theorem sectionsGMul_add_right {m n : ℕ} (a : S.sectionsPiece U m)
    (b b' : S.sectionsPiece U n) :
    S.sectionsGMul U a (b + b') = S.sectionsGMul U a b + S.sectionsGMul U a b' := by
  show (S.mul m n).app U
    (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part m) (S.part n) U a (b + b')) = _
  rw [AlgebraicGeometry.Scheme.Modules.tensorSections_add_right]
  exact map_add _ _ _

theorem sectionsGMul_add_left {m n : ℕ} (a a' : S.sectionsPiece U m)
    (b : S.sectionsPiece U n) :
    S.sectionsGMul U (a + a') b = S.sectionsGMul U a b + S.sectionsGMul U a' b := by
  show (S.mul m n).app U
    (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part m) (S.part n) U (a + a') b) = _
  rw [AlgebraicGeometry.Scheme.Modules.tensorSections_add_left]
  exact map_add _ _ _

/-- The axiom `S.one_mul` pointwise: `S.one.app U r * a = r • a` (transported to the `0 + m` piece). -/
theorem sectionsGOne_app_sectionsGMul {m : ℕ} (r : Γ(X, U)) (a : S.sectionsPiece U m) :
    S.sectionsGMul U (S.one.app U r) a =
      (CategoryTheory.eqToHom (congrArg S.part (Nat.zero_add m).symm)).app U
        (@HSMul.hSMul Γ(X, U) Γ(S.part m, U) Γ(S.part m, U) _ r a) := by
  have h := congrArg
    (fun (φ : CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules)
        (𝟙_ X.Modules) (S.part m) ⟶ S.part (0 + m)) =>
      φ.app U (AlgebraicGeometry.Scheme.Modules.tensorSections
        (𝟙_ X.Modules) (S.part m) U r a))
    (S.one_mul m)
  have hT := AlgebraicGeometry.Scheme.Modules.tensorHom_tensorSections
    S.one (𝟙 (S.part m)) U r a
  rw [CategoryTheory.MonoidalCategory.tensorHom_id] at hT
  have hL := AlgebraicGeometry.Scheme.Modules.leftUnitor_app_tensorSections (S.part m) U r a
  have hR : ((S.one ▷ S.part m) ≫ S.mul 0 m).app U
      (AlgebraicGeometry.Scheme.Modules.tensorSections (𝟙_ X.Modules) (S.part m) U r a)
      = S.sectionsGMul U (S.one.app U r) a := by
    show (S.mul 0 m).app U ((S.one ▷ S.part m).val.app (Opposite.op U)
      (AlgebraicGeometry.Scheme.Modules.tensorSections (𝟙_ X.Modules) (S.part m) U r a)) = _
    rw [hT]; rfl
  refine hR.symm.trans (h.trans ?_)
  show (CategoryTheory.eqToHom (congrArg S.part (Nat.zero_add m).symm)).app U
      ((λ_ (S.part m)).hom.app U
        (AlgebraicGeometry.Scheme.Modules.tensorSections (𝟙_ X.Modules) (S.part m) U r a)) = _
  rw [hL]

/-- The left unit law (in `GradedMonoid` form). -/
theorem sectionsGOne_mul_mk {m : ℕ} (a : S.sectionsPiece U m) :
    (GradedMonoid.mk (0 + m) (S.sectionsGMul U (S.sectionsGOne U) a) :
        GradedMonoid (S.sectionsPiece U)) = GradedMonoid.mk m a := by
  have h1 : S.sectionsGMul U (S.sectionsGOne U) a
      = (CategoryTheory.eqToHom (congrArg S.part (Nat.zero_add m).symm)).app U a := by
    refine (S.sectionsGOne_app_sectionsGMul U 1 a).trans ?_
    exact congrArg _ (one_smul Γ(X, U) (show Γ(S.part m, U) from a))
  rw [h1]
  exact S.mk_eqToHom_app U (Nat.zero_add m).symm a

/-- The axiom `S.mul_comm` pointwise. -/
theorem sectionsGMul_comm_app {m n : ℕ} (a : S.sectionsPiece U m) (b : S.sectionsPiece U n) :
    S.sectionsGMul U b a =
      (CategoryTheory.eqToHom (congrArg S.part (Nat.add_comm m n))).app U
        (S.sectionsGMul U a b) := by
  have h := congrArg
    (fun (φ : CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules)
        (S.part m) (S.part n) ⟶ S.part (n + m)) =>
      φ.app U (AlgebraicGeometry.Scheme.Modules.tensorSections
        (S.part m) (S.part n) U a b))
    (S.mul_comm m n)
  have hb := AlgebraicGeometry.Scheme.Modules.braiding_app_tensorSections
    (S.part m) (S.part n) U a b
  have hLHS : ((β_ (S.part m) (S.part n)).hom ≫ S.mul n m).app U
      (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part m) (S.part n) U a b)
      = S.sectionsGMul U b a := by
    show (S.mul n m).app U ((β_ (S.part m) (S.part n)).hom.app U
      (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part m) (S.part n) U a b)) = _
    rw [hb]; rfl
  exact hLHS.symm.trans h

/-- Commutativity (in `GradedMonoid` form). -/
theorem sectionsGMul_mk_comm {m n : ℕ} (a : S.sectionsPiece U m) (b : S.sectionsPiece U n) :
    (GradedMonoid.mk (m + n) (S.sectionsGMul U a b) : GradedMonoid (S.sectionsPiece U))
      = GradedMonoid.mk (n + m) (S.sectionsGMul U b a) := by
  rw [S.sectionsGMul_comm_app U a b]
  exact (S.mk_eqToHom_app U (Nat.add_comm m n) (S.sectionsGMul U a b)).symm

/-- The right unit law (in `GradedMonoid` form): commutativity + left unit law. -/
theorem sectionsGMul_one_mk {m : ℕ} (a : S.sectionsPiece U m) :
    (GradedMonoid.mk (m + 0) (S.sectionsGMul U a (S.sectionsGOne U)) :
        GradedMonoid (S.sectionsPiece U)) = GradedMonoid.mk m a :=
  (S.sectionsGMul_mk_comm U a (S.sectionsGOne U)).trans (S.sectionsGOne_mul_mk U a)

/-- The axiom `S.mul_assoc` pointwise. -/
theorem sectionsGMul_assoc_app {m n p : ℕ} (a : S.sectionsPiece U m) (b : S.sectionsPiece U n)
    (c : S.sectionsPiece U p) :
    S.sectionsGMul U a (S.sectionsGMul U b c) =
      (CategoryTheory.eqToHom (congrArg S.part (Nat.add_assoc m n p))).app U
        (S.sectionsGMul U (S.sectionsGMul U a b) c) := by
  have h := congrArg
    (fun (φ : CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules)
        (CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules) (S.part m) (S.part n))
        (S.part p) ⟶ S.part (m + (n + p))) =>
      φ.app U (AlgebraicGeometry.Scheme.Modules.tensorSections
        (CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules) (S.part m) (S.part n))
        (S.part p) U
        (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part m) (S.part n) U a b) c))
    (S.mul_assoc m n p)
  have hTR := AlgebraicGeometry.Scheme.Modules.tensorHom_tensorSections
    (S.mul m n) (𝟙 (S.part p)) U
    (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part m) (S.part n) U a b) c
  rw [CategoryTheory.MonoidalCategory.tensorHom_id] at hTR
  have hTL := AlgebraicGeometry.Scheme.Modules.tensorHom_tensorSections
    (𝟙 (S.part m)) (S.mul n p) U a
    (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part n) (S.part p) U b c)
  rw [CategoryTheory.MonoidalCategory.id_tensorHom] at hTL
  have ha := AlgebraicGeometry.Scheme.Modules.associator_app_tensorSections
    (S.part m) (S.part n) (S.part p) U a b c
  have hL : ((α_ (S.part m) (S.part n) (S.part p)).hom ≫
        (S.part m ◁ S.mul n p) ≫ S.mul m (n + p)).app U
      (AlgebraicGeometry.Scheme.Modules.tensorSections
        (CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules) (S.part m) (S.part n))
        (S.part p) U
        (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part m) (S.part n) U a b) c)
      = S.sectionsGMul U a (S.sectionsGMul U b c) := by
    show (S.mul m (n + p)).app U ((S.part m ◁ S.mul n p).val.app (Opposite.op U)
      ((α_ (S.part m) (S.part n) (S.part p)).hom.val.app (Opposite.op U) _)) = _
    rw [show (α_ (S.part m) (S.part n) (S.part p)).hom.val.app (Opposite.op U) _ = _ from ha,
      hTL]
    rfl
  have hR : ((S.mul m n ▷ S.part p) ≫ S.mul (m + n) p ≫
        CategoryTheory.eqToHom (congrArg S.part (Nat.add_assoc m n p))).app U
      (AlgebraicGeometry.Scheme.Modules.tensorSections
        (CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules) (S.part m) (S.part n))
        (S.part p) U
        (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part m) (S.part n) U a b) c)
      = (CategoryTheory.eqToHom (congrArg S.part (Nat.add_assoc m n p))).app U
        (S.sectionsGMul U (S.sectionsGMul U a b) c) := by
    show (CategoryTheory.eqToHom (congrArg S.part (Nat.add_assoc m n p))).app U
      ((S.mul (m + n) p).app U ((S.mul m n ▷ S.part p).val.app (Opposite.op U) _)) = _
    rw [hTR]
    rfl
  exact hL.symm.trans (h.trans hR)

/-- Associativity (in `GradedMonoid` form). -/
theorem sectionsGMul_mk_assoc {m n p : ℕ} (a : S.sectionsPiece U m) (b : S.sectionsPiece U n)
    (c : S.sectionsPiece U p) :
    (GradedMonoid.mk (m + n + p) (S.sectionsGMul U (S.sectionsGMul U a b) c) :
        GradedMonoid (S.sectionsPiece U))
      = GradedMonoid.mk (m + (n + p)) (S.sectionsGMul U a (S.sectionsGMul U b c)) := by
  rw [S.sectionsGMul_assoc_app U a b c]
  exact (S.mk_eqToHom_app U (Nat.add_assoc m n p) _).symm

/-- `S.one` preserves multiplication on `U` (in `GradedMonoid` form): `S.one` is `O_X`-linear. -/
theorem sectionsGOne_app_mul (r s : Γ(X, U)) :
    (GradedMonoid.mk 0 (S.one.app U (r * s)) : GradedMonoid (S.sectionsPiece U))
      = GradedMonoid.mk (0 + 0) (S.sectionsGMul U (S.one.app U r) (S.one.app U s)) := by
  have h1 : S.sectionsGMul U (S.one.app U r) (S.one.app U s)
      = (CategoryTheory.eqToHom (congrArg S.part (Nat.zero_add 0).symm)).app U
          (S.one.app U (r * s)) := by
    refine (S.sectionsGOne_app_sectionsGMul U r (S.one.app U s)).trans ?_
    exact congrArg _ (AlgebraicGeometry.Scheme.Modules.Hom.app_smul S.one r
      (s : Γ(𝟙_ X.Modules, U))).symm
  rw [h1]
  exact (S.mk_eqToHom_app U (Nat.zero_add 0).symm (S.one.app U (r * s))).symm

/-- `GOne` / `GMul` are local instances of this file only: `sectionsGCommRing` absorbs them, and downstream
obtains them through the projections `GCommRing → … → GOne`, so these two broad instance heads need not enter
global instance search. -/
noncomputable local instance sectionsGOneInst : GradedMonoid.GOne (S.sectionsPiece U) where
  one := S.sectionsGOne U

noncomputable local instance sectionsGMulInst : GradedMonoid.GMul (S.sectionsPiece U) where
  mul {_ _} a b := S.sectionsGMul U a b

/-- The graded multiplication `Γ(U, S_m) × Γ(U, S_n) → Γ(U, S_{m+n})`; the image of the unit `S.one` on `U` sits in
the `0`-th piece; the images of `ℕ`, `ℤ` are `n • 1`. Associativity, commutativity and distributivity come from
the pointwise forms of the `GradedQCAlgebra` axioms above. -/
noncomputable instance sectionsGCommRing : DirectSum.GCommRing (S.sectionsPiece U) where
  natCast n := n • S.sectionsGOne U
  intCast n := n • S.sectionsGOne U
  mul_zero a := S.sectionsGMul_zero_right U a
  zero_mul b := S.sectionsGMul_zero_left U b
  mul_add a b c := S.sectionsGMul_add_right U a b c
  add_mul a b c := S.sectionsGMul_add_left U a b c
  one_mul a := S.sectionsGOne_mul_mk U a.snd
  mul_one a := S.sectionsGMul_one_mk U a.snd
  mul_assoc a b c := S.sectionsGMul_mk_assoc U a.snd b.snd c.snd
  natCast_zero := zero_nsmul _
  natCast_succ n := succ_nsmul _ n
  intCast_ofNat n := natCast_zsmul _ n
  intCast_negSucc_ofNat n := negSucc_zsmul _ n
  mul_comm a b := S.sectionsGMul_mk_comm U a.snd b.snd


end AlgebraicGeometry.Scheme.GradedQCAlgebra

/-- `⊕_m Γ(S.part m, U)` with its `CommRing` structure (Mathlib `DirectSum.commRing`, from the `GCommRing` above). -/
noncomputable def AlgebraicGeometry.Scheme.GradedQCAlgebra.sectionsRing {X : AlgebraicGeometry.Scheme.{u}}
    (S : X.GradedQCAlgebra) (U : X.Opens) : Type u :=
  ⨁ m, S.sectionsPiece U m

noncomputable instance {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra) (U : X.Opens) :
    CommRing (S.sectionsRing U) :=
  inferInstanceAs (CommRing (⨁ m, S.sectionsPiece U m))

/-- The `m`-th graded piece is the image of `DirectSum.of m`. -/

def AlgebraicGeometry.Scheme.GradedQCAlgebra.sectionsGrading {X : AlgebraicGeometry.Scheme.{u}}
    (S : X.GradedQCAlgebra) (U : X.Opens) : ℕ → AddSubgroup (S.sectionsRing U) :=
  fun m => (DirectSum.of (S.sectionsPiece U) m).range

/-! ### Graded ring structure, restriction homomorphisms, unit (named lemmas first; the instances only assemble) -/

namespace AlgebraicGeometry.Scheme.GradedQCAlgebra

variable {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra)

theorem sectionsGrading_one_mem (U : X.Opens) :
    (1 : S.sectionsRing U) ∈ S.sectionsGrading U 0 :=
  ⟨GradedMonoid.GOne.one, rfl⟩

theorem sectionsGrading_mul_mem (U : X.Opens) ⦃i j : ℕ⦄ {gi gj : S.sectionsRing U}
    (hi : gi ∈ S.sectionsGrading U i) (hj : gj ∈ S.sectionsGrading U j) :
    gi * gj ∈ S.sectionsGrading U (i + j) := by
  obtain ⟨a, rfl⟩ := hi
  obtain ⟨b, rfl⟩ := hj
  exact ⟨GradedMonoid.GMul.mul a b, (DirectSum.of_mul_of a b).symm⟩

/-- The decomposition map: componentwise, view `x_m` as an element of the image of `DirectSum.of m`. -/
noncomputable def sectionsDecompose (U : X.Opens) :
    S.sectionsRing U →+ ⨁ m, (S.sectionsGrading U m) :=
  DirectSum.map (fun m => (DirectSum.of (S.sectionsPiece U) m).rangeRestrict)

theorem sectionsDecompose_left_inv (U : X.Opens) :
    Function.LeftInverse (DirectSum.coeAddMonoidHom (S.sectionsGrading U))
      (S.sectionsDecompose U) := by
  have key : (DirectSum.coeAddMonoidHom (S.sectionsGrading U)).comp (S.sectionsDecompose U)
      = AddMonoidHom.id (S.sectionsRing U) := by
    refine DirectSum.addHom_ext ?_
    intro i a
    show DirectSum.coeAddMonoidHom (S.sectionsGrading U)
      (DirectSum.map (fun m => (DirectSum.of (S.sectionsPiece U) m).rangeRestrict)
        (DirectSum.of (S.sectionsPiece U) i a)) = _
    rw [DirectSum.map_of]
    exact DirectSum.coeAddMonoidHom_of (S.sectionsGrading U) i _
  intro x
  exact DFunLike.congr_fun key x

theorem sectionsDecompose_right_inv (U : X.Opens) :
    Function.RightInverse (DirectSum.coeAddMonoidHom (S.sectionsGrading U))
      (S.sectionsDecompose U) := by
  have key : (S.sectionsDecompose U).comp (DirectSum.coeAddMonoidHom (S.sectionsGrading U))
      = AddMonoidHom.id (⨁ m, (S.sectionsGrading U m)) := by
    refine DirectSum.addHom_ext ?_
    intro i y
    obtain ⟨v, hv⟩ := y.2
    show DirectSum.map (fun m => (DirectSum.of (S.sectionsPiece U) m).rangeRestrict)
      (DirectSum.coeAddMonoidHom (S.sectionsGrading U)
        (DirectSum.of (fun m => (S.sectionsGrading U m)) i y)) = _
    rw [DirectSum.coeAddMonoidHom_of, ← hv, DirectSum.map_of]
    exact congrArg (DirectSum.of (fun m => (S.sectionsGrading U m)) i) (Subtype.ext hv)
  intro y
  exact DFunLike.congr_fun key y

/-- The restriction map on the `m`-th piece. -/
noncomputable def sectionsRestrictPiece {U U' : X.Opens} (h : U ≤ U') (m : ℕ) :
    S.sectionsPiece U' m →+ S.sectionsPiece U m :=
  ((S.part m).val.map (CategoryTheory.homOfLE h).op).hom.toAddMonoidHom

/-- Restriction preserves the unit (naturality of `S.one` + restriction of the structure sheaf preserves `1`). -/
theorem sectionsGOne_restrict {U U' : X.Opens} (h : U ≤ U') :
    S.sectionsRestrictPiece h 0 (S.sectionsGOne U') = S.sectionsGOne U := by
  have hn := _root_.PresheafOfModules.naturality_apply S.one.val
    (CategoryTheory.homOfLE h).op (1 : X.ringCatSheaf.obj.obj (Opposite.op U'))
  have h1 : ((𝟙_ X.Modules).val.map (CategoryTheory.homOfLE h).op)
      (1 : X.ringCatSheaf.obj.obj (Opposite.op U')) =
      (1 : X.ringCatSheaf.obj.obj (Opposite.op U)) := by
    change (X.presheaf.map (CategoryTheory.homOfLE h).op).hom 1 = 1
    exact map_one _
  rw [h1] at hn
  exact hn.symm

/-- Restriction preserves the graded multiplication (naturality of `S.mul` + compatibility of the section pairing
with restriction). -/
theorem sectionsGMul_restrict {U U' : X.Opens} (h : U ≤ U') {m n : ℕ}
    (a : S.sectionsPiece U' m) (b : S.sectionsPiece U' n) :
    S.sectionsRestrictPiece h (m + n) (S.sectionsGMul U' a b)
      = S.sectionsGMul U (S.sectionsRestrictPiece h m a) (S.sectionsRestrictPiece h n b) := by
  show ((S.part (m + n)).val.map (CategoryTheory.homOfLE h).op)
      ((S.mul m n).val.app (Opposite.op U')
        (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part m) (S.part n) U' a b))
    = (S.mul m n).val.app (Opposite.op U)
        (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part m) (S.part n) U
          (((S.part m).val.map (CategoryTheory.homOfLE h).op) a)
          (((S.part n).val.map (CategoryTheory.homOfLE h).op) b))
  rw [← AlgebraicGeometry.Scheme.Modules.tensorSections_restrict (S.part m) (S.part n)
    (CategoryTheory.homOfLE h) a b]
  exact (_root_.PresheafOfModules.naturality_apply (S.mul m n).val
    (CategoryTheory.homOfLE h).op _).symm

/-- Restriction as a ring homomorphism (piecewise restriction, preserving `1` and multiplication). -/
noncomputable def sectionsRestrictRingHom {U U' : X.Opens} (h : U ≤ U') :
    S.sectionsRing U' →+* S.sectionsRing U :=
  DirectSum.toSemiring
    (fun m => (DirectSum.of (S.sectionsPiece U) m).comp (S.sectionsRestrictPiece h m))
    (by
      show DirectSum.of (S.sectionsPiece U) 0
        (S.sectionsRestrictPiece h 0 (S.sectionsGOne U')) = 1
      rw [S.sectionsGOne_restrict h]
      rfl)
    (fun {i j} a b => by
      show DirectSum.of (S.sectionsPiece U) (i + j)
        (S.sectionsRestrictPiece h (i + j) (S.sectionsGMul U' a b)) = _
      rw [S.sectionsGMul_restrict h a b]
      exact (DirectSum.of_mul_of _ _).symm)

theorem sectionsRestrictRingHom_of {U U' : X.Opens} (h : U ≤ U') (m : ℕ)
    (a : S.sectionsPiece U' m) :
    S.sectionsRestrictRingHom h (DirectSum.of (S.sectionsPiece U') m a)
      = DirectSum.of (S.sectionsPiece U) m (S.sectionsRestrictPiece h m a) :=
  DirectSum.toSemiring_of _ _ _ m a

end AlgebraicGeometry.Scheme.GradedQCAlgebra

/-- The decomposition `x ↦ (x_m)_m`: componentwise the range restriction of `of_m` (`DirectSum.map`); the left and
right inverse laws come from the universal property of the direct sum. -/

noncomputable instance {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra) (U : X.Opens) :
    GradedRing (S.sectionsGrading U) where
  one_mem := S.sectionsGrading_one_mem U
  mul_mem := S.sectionsGrading_mul_mem U
  decompose' := S.sectionsDecompose U
  left_inv := S.sectionsDecompose_left_inv U
  right_inv := S.sectionsDecompose_right_inv U

/-- Restriction for `U ≤ U′`: piecewise the restriction maps of the `S_m`; a graded ring homomorphism. -/

noncomputable def AlgebraicGeometry.Scheme.GradedQCAlgebra.sectionsRestrict {X : AlgebraicGeometry.Scheme.{u}}
    (S : X.GradedQCAlgebra) {U U' : X.Opens} (h : U ≤ U') :
    S.sectionsGrading U' →+*ᵍ S.sectionsGrading U where
  toRingHom := S.sectionsRestrictRingHom h
  map_mem := by
    rintro i x ⟨a, rfl⟩
    exact ⟨S.sectionsRestrictPiece h i a, (S.sectionsRestrictRingHom_of h i a).symm⟩

/-- The unit `Γ(X, U) → A(U)_0`: `r ↦ r · 1_U` (the value of `S.one` on `U`, placed in the `0`-th piece). -/

noncomputable def AlgebraicGeometry.Scheme.GradedQCAlgebra.sectionsUnit {X : AlgebraicGeometry.Scheme.{u}}
    (S : X.GradedQCAlgebra) (U : X.Opens) : Γ(X, U) →+* S.sectionsGrading U 0 where
  toFun r := ⟨DirectSum.of (S.sectionsPiece U) 0 (S.one.app U r), ⟨_, rfl⟩⟩
  map_one' := rfl
  map_mul' r s := Subtype.ext (by
    show DirectSum.of (S.sectionsPiece U) 0 (S.one.app U (r * s))
      = DirectSum.of (S.sectionsPiece U) 0 (S.one.app U r) *
        DirectSum.of (S.sectionsPiece U) 0 (S.one.app U s)
    rw [DirectSum.of_mul_of]
    exact DirectSum.of_eq_of_gradedMonoid_eq (S.sectionsGOne_app_mul U r s))
  map_zero' := Subtype.ext (by
    show DirectSum.of (S.sectionsPiece U) 0 (S.one.app U 0) = 0
    rw [map_zero, map_zero])
  map_add' r s := Subtype.ext (by
    show DirectSum.of (S.sectionsPiece U) 0 (S.one.app U (r + s))
      = DirectSum.of (S.sectionsPiece U) 0 (S.one.app U r) +
        DirectSum.of (S.sectionsPiece U) 0 (S.one.app U s)
    rw [map_add, map_add])

/-- `r • 1_U = S.one.app U r` (`O_X`-linearity of `S.one`). -/
theorem AlgebraicGeometry.Scheme.GradedQCAlgebra.smul_sectionsGOne {X : AlgebraicGeometry.Scheme.{u}}
    (S : X.GradedQCAlgebra) (U : X.Opens) (r : Γ(X, U)) :
    @HSMul.hSMul Γ(X, U) Γ(S.part 0, U) Γ(S.part 0, U) _ r (S.sectionsGOne U)
      = S.one.app U r := by
  refine (AlgebraicGeometry.Scheme.Modules.Hom.app_smul S.one r
    (show Γ(𝟙_ X.Modules, U) from (1 : Γ(X, U)))).symm.trans ?_
  refine congrArg (fun x => S.one.app U x) ?_
  show r * (1 : Γ(X, U)) = r
  exact mul_one r

/-- The `0`-th component of `sectionsUnit U r` is `r • 1_U`. -/
theorem AlgebraicGeometry.Scheme.GradedQCAlgebra.sectionsUnit_apply {X : AlgebraicGeometry.Scheme.{u}}
    (S : X.GradedQCAlgebra) (U : X.Opens) (r : Γ(X, U)) :
    (S.sectionsUnit U r : S.sectionsRing U) =
      DirectSum.of (S.sectionsPiece U) 0
        (@HSMul.hSMul Γ(X, U) Γ(S.part 0, U) Γ(S.part 0, U) _ r (S.sectionsGOne U)) :=
  congrArg (DirectSum.of (S.sectionsPiece U) 0) (S.smul_sectionsGOne U r).symm

/-! ## The irrelevant ideal condition

The proof uses only the two elementwise facts "quasi-coherent sheaves on affine opens commute with
localization at principal opens" (`Modules.exists_pow_smul_eq_map_basicOpen` /
`exists_pow_smul_eq_zero_of_map_basicOpen_eq_zero`, `QcSectionsBasicOpenLocalization.lean`); it needs
neither the base change `A(U) ≅ A(U′) ⊗ R` nor `QcPullbackAffineSections`. Three auxiliary lemmas follow:
multiplication by the unit piece is the scalar action; restriction of pieces is compatible with the scalar
action; restriction of pieces is functorial. -/

namespace AlgebraicGeometry.Scheme.GradedQCAlgebra

variable {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra)

/-- `(sectionsUnit U r) * of m a = of m (r • a)`: multiplying the `m`-th piece by the unit piece is the scalar
action of `Γ(X, U)` (the pointwise form `sectionsGOne_app_sectionsGMul` of `S.one_mul`). -/
theorem sectionsUnit_mul_of (U : X.Opens) (r : Γ(X, U)) {m : ℕ} (a : S.sectionsPiece U m) :
    @HMul.hMul (S.sectionsRing U) (S.sectionsRing U) (S.sectionsRing U) _
        (S.sectionsUnit U r) (DirectSum.of (S.sectionsPiece U) m a)
      = DirectSum.of (S.sectionsPiece U) m
          (@HSMul.hSMul Γ(X, U) Γ(S.part m, U) Γ(S.part m, U) _ r a) := by
  show DirectSum.of (S.sectionsPiece U) 0 (S.one.app U r) * DirectSum.of (S.sectionsPiece U) m a
    = DirectSum.of (S.sectionsPiece U) m
        (@HSMul.hSMul Γ(X, U) Γ(S.part m, U) Γ(S.part m, U) _ r a)
  rw [DirectSum.of_mul_of]
  refine DirectSum.of_eq_of_gradedMonoid_eq ?_
  show (GradedMonoid.mk (0 + m) (S.sectionsGMul U (S.one.app U r) a) :
      GradedMonoid (S.sectionsPiece U)) = GradedMonoid.mk m _
  rw [S.sectionsGOne_app_sectionsGMul U r a]
  exact S.mk_eqToHom_app U (Nat.zero_add m).symm _

/-- Restriction of the graded pieces is compatible with the scalar action (`PresheafOfModules.map_smul`). -/
theorem sectionsRestrictPiece_smul {U U' : X.Opens} (h : U ≤ U') (m : ℕ) (r : Γ(X, U'))
    (a : S.sectionsPiece U' m) :
    S.sectionsRestrictPiece h m
        (@HSMul.hSMul Γ(X, U') Γ(S.part m, U') Γ(S.part m, U') _ r a)
      = @HSMul.hSMul Γ(X, U) Γ(S.part m, U) Γ(S.part m, U) _
          ((X.presheaf.map (CategoryTheory.homOfLE h).op) r) (S.sectionsRestrictPiece h m a) :=
  _root_.PresheafOfModules.map_smul (S.part m).val (CategoryTheory.homOfLE h).op r a

/-- Functoriality of the restriction of pieces: for `U ≤ V ≤ W`, restricting to `V` and then to `U` equals
restricting directly to `U`. -/
theorem sectionsRestrictPiece_trans {U V W : X.Opens} (hUV : U ≤ V) (hVW : V ≤ W) (m : ℕ)
    (a : S.sectionsPiece W m) :
    S.sectionsRestrictPiece hUV m (S.sectionsRestrictPiece hVW m a)
      = S.sectionsRestrictPiece (hUV.trans hVW) m a := by
  have h1 : CategoryTheory.homOfLE (hUV.trans hVW)
      = CategoryTheory.homOfLE hUV ≫ CategoryTheory.homOfLE hVW := Subsingleton.elim _ _
  show ((S.part m).val.map (CategoryTheory.homOfLE hUV).op).hom
      (((S.part m).val.map (CategoryTheory.homOfLE hVW).op).hom a)
    = ((S.part m).val.map (CategoryTheory.homOfLE (hUV.trans hVW)).op).hom a
  exact ((_root_.PresheafOfModules.congr_map_apply _ (congrArg Quiver.Hom.op h1) _).trans
    (_root_.PresheafOfModules.map_comp_apply _ _ _ _)).symm

end AlgebraicGeometry.Scheme.GradedQCAlgebra

/-- **The irrelevant ideal condition (for `Proj.map`)**: for affine `U ⊆ U′`, the irrelevant ideal of `A(U)` is
contained in the ideal generated by the image of the irrelevant ideal of `A(U′)`.

Reference: Stacks 01I8 (quasi-coherent sheaves on affine opens commute with localization at principal
opens); used for the hypothesis of `Proj.map` in Stacks 01NQ.

**Proof** (using only localization at principal opens, no base change): by `HomogeneousIdeal.irrelevant_le` it
suffices to show `x ∈ I` for `d > 0` and `x = of_d a` (`a ∈ Γ(U, S_d)`), where
`I := (irrelevant A(U′)).map (sectionsRestrict h)`. Let `K ⊆ Γ(X, U)` be the set of `r` with `of_d (r • a) ∈ I`;
it is an ideal (`add_smul`, `mul_smul` and `sectionsUnit_mul_of`: `of_d (c • y) = unit(c) · of_d y`). For a
point `p` of `U`, since `U′` is affine (`IsAffineOpen.exists_basicOpen_le`) choose `f ∈ Γ(X, U′)` with
`p ∈ D(f) ⊆ U`; let `g := f|_U`, so `D(g) = U ⊓ D(f) = D(f)` (`Scheme.basicOpen_res`). `S_d` is quasi-coherent, so
surjectivity of localization on `U′` for `f` gives `n` and `t ∈ Γ(U′, S_d)` with `t|_{D(f)} = f^n • a|_{D(f)}`.
Then `c := g^n • a − t|_U ∈ Γ(U, S_d)` restricts to `0` on `D(f) = D(g)` (compatibility of restriction with the
scalar action, functoriality of restriction); the kernel of localization on `U` for `g` gives `N` with
`g^N • c = 0`, i.e. `g^{N+n} • a = g^N • t|_U`. Now `of_d (g^N • t|_U) = unit(g^N) · sectionsRestrict h (of_d t)`
and `of_d t ∈ irrelevant A(U′)` (`d > 0`), so `g^{N+n} ∈ K`, i.e. `g ∈ rad K`. Hence `U ⊆ ⋃_{g ∈ rad K} D(g)`, and
since `U` is affine (`IsAffineOpen.self_le_iSup_basicOpen_iff`) we get `span (rad K) = rad K = ⊤`, so `K = ⊤`
(`Ideal.radical_eq_top`), `1 ∈ K`, i.e. `of_d a = of_d (1 • a) ∈ I`.

**Edge cases**: for `U = ∅`, `Γ(X, U)` is the zero ring and `1 = 0 ∈ K` holds directly (no call to
`exists_basicOpen_le` needed); if some piece of `S` is `0`, its elements are all `0`. -/
theorem AlgebraicGeometry.Scheme.GradedQCAlgebra.sectionsRestrict_irrelevant {X : AlgebraicGeometry.Scheme.{u}}
    (S : X.GradedQCAlgebra) {U U' : X.Opens} (hU : AlgebraicGeometry.IsAffineOpen U)
    (hU' : AlgebraicGeometry.IsAffineOpen U') (h : U ≤ U') :
    HomogeneousIdeal.irrelevant (S.sectionsGrading U) ≤
      (HomogeneousIdeal.irrelevant (S.sectionsGrading U')).map (S.sectionsRestrict h) := by
  rw [HomogeneousIdeal.irrelevant_le]
  intro d hd x hx
  have : (S.part d).IsQuasicoherent := S.quasicoherent d
  obtain ⟨a, rfl⟩ : ∃ a : S.sectionsPiece U d, DirectSum.of (S.sectionsPiece U) d a = x := hx
  set I : Ideal (S.sectionsRing U) :=
    Ideal.map (S.sectionsRestrict h : S.sectionsRing U' →+* S.sectionsRing U)
      (HomogeneousIdeal.irrelevant (S.sectionsGrading U')).toIdeal with hI
  show DirectSum.of (S.sectionsPiece U) d a ∈ I
  -- K := {r ∈ Γ(X, U) | of_d (r • a) ∈ I}
  let K : Ideal Γ(X, U) :=
    { carrier := {r | DirectSum.of (S.sectionsPiece U) d
        (@HSMul.hSMul Γ(X, U) Γ(S.part d, U) Γ(S.part d, U) _ r a) ∈ I}
      add_mem' := by
        intro r s hr hs
        show DirectSum.of (S.sectionsPiece U) d
          (@HSMul.hSMul Γ(X, U) Γ(S.part d, U) Γ(S.part d, U) _ (r + s) a) ∈ I
        rw [add_smul, map_add]
        exact I.add_mem hr hs
      zero_mem' := by
        show DirectSum.of (S.sectionsPiece U) d
          (@HSMul.hSMul Γ(X, U) Γ(S.part d, U) Γ(S.part d, U) _ 0 a) ∈ I
        rw [zero_smul, map_zero]
        exact I.zero_mem
      smul_mem' := by
        intro c r hr
        show DirectSum.of (S.sectionsPiece U) d
          (@HSMul.hSMul Γ(X, U) Γ(S.part d, U) Γ(S.part d, U) _ (c * r) a) ∈ I
        rw [mul_smul, ← S.sectionsUnit_mul_of U c]
        exact I.mul_mem_left _ hr }
  -- every point of U lies in some D(g) with g ∈ rad K
  have key : ∀ p ∈ U, ∃ g : Γ(X, U), g ∈ K.radical ∧ p ∈ X.basicOpen g := by
    intro p hp
    obtain ⟨f, hfU, hpf⟩ := hU'.exists_basicOpen_le ⟨p, hp⟩ (h hp)
    set g : Γ(X, U) := (X.presheaf.map (CategoryTheory.homOfLE h).op) f with hg
    have hDg : X.basicOpen g = X.basicOpen f := by
      rw [hg, AlgebraicGeometry.Scheme.basicOpen_res]
      exact inf_eq_right.mpr hfU
    refine ⟨g, ?_, hDg ▸ hpf⟩
    have hDf : X.basicOpen f ≤ U := hfU
    obtain ⟨n, t, ht⟩ := AlgebraicGeometry.Scheme.Modules.exists_pow_smul_eq_map_basicOpen
      (S.part d) hU' f (S.sectionsRestrictPiece hDf d a)
    set c : S.sectionsPiece U d :=
      @HSub.hSub Γ(S.part d, U) Γ(S.part d, U) Γ(S.part d, U) _
        (@HSMul.hSMul Γ(X, U) Γ(S.part d, U) Γ(S.part d, U) _ (g ^ n) a)
        (S.sectionsRestrictPiece h d t) with hc_def
    -- c restricts to 0 on D(f)
    have hcf : S.sectionsRestrictPiece hDf d c = 0 := by
      rw [hc_def, map_sub, S.sectionsRestrictPiece_smul hDf d, S.sectionsRestrictPiece_trans hDf h d t,
        sub_eq_zero, hg, ← map_pow]
      have e : ((X.presheaf.map (CategoryTheory.homOfLE hDf).op)
          ((X.presheaf.map (CategoryTheory.homOfLE h).op) (f ^ n)))
          = (X.presheaf.map (CategoryTheory.homOfLE (X.basicOpen_le f)).op) (f ^ n) := by
        have h1 : CategoryTheory.homOfLE (X.basicOpen_le f)
            = CategoryTheory.homOfLE hDf ≫ CategoryTheory.homOfLE h := Subsingleton.elim _ _
        rw [h1, CategoryTheory.op_comp, X.presheaf.map_comp]
        rfl
      rw [e, map_pow]
      exact ht.symm
    -- hence c restricts to 0 on D(g) = D(f)
    have hcg : (S.part d).presheaf.map (CategoryTheory.homOfLE (X.basicOpen_le g)).op c = 0 := by
      show S.sectionsRestrictPiece (X.basicOpen_le g) d c = 0
      rw [← S.sectionsRestrictPiece_trans hDg.le hDf d c, hcf, map_zero]
    obtain ⟨N, hN⟩ := AlgebraicGeometry.Scheme.Modules.exists_pow_smul_eq_zero_of_map_basicOpen_eq_zero
      (S.part d) hU g c hcg
    refine ⟨N + n, ?_⟩
    show DirectSum.of (S.sectionsPiece U) d
      (@HSMul.hSMul Γ(X, U) Γ(S.part d, U) Γ(S.part d, U) _ (g ^ (N + n)) a) ∈ I
    have hEq : @HSMul.hSMul Γ(X, U) Γ(S.part d, U) Γ(S.part d, U) _ (g ^ (N + n)) a
        = @HSMul.hSMul Γ(X, U) Γ(S.part d, U) Γ(S.part d, U) _ (g ^ N)
            (S.sectionsRestrictPiece h d t) := by
      rw [hc_def, smul_sub, sub_eq_zero, smul_smul, ← pow_add] at hN
      exact hN
    rw [hEq, ← S.sectionsUnit_mul_of U (g ^ N)]
    refine I.mul_mem_left _ ?_
    rw [← S.sectionsRestrictRingHom_of h d t]
    exact Ideal.mem_map_of_mem _ (HomogeneousIdeal.mem_irrelevant_of_mem _ hd ⟨t, rfl⟩)
  -- rad K = ⊤, so K = ⊤
  have hK : K = ⊤ := by
    rw [← Ideal.radical_eq_top, ← Ideal.span_eq K.radical, ← hU.self_le_iSup_basicOpen_iff]
    intro p hp
    obtain ⟨g, hgK, hpg⟩ := key p hp
    exact TopologicalSpace.Opens.mem_iSup.mpr ⟨⟨g, hgK⟩, hpg⟩
  have h1 : (1 : Γ(X, U)) ∈ K := hK ▸ Submodule.mem_top
  have h1' : DirectSum.of (S.sectionsPiece U) d
      (@HSMul.hSMul Γ(X, U) Γ(S.part d, U) Γ(S.part d, U) _ (1 : Γ(X, U)) a) ∈ I := h1
  rwa [one_smul] at h1'

end
