import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.Basic.CoproductSectionsLocallyFinite
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.GradedAlgebraTotalProjection
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.QcAlgebraSectionsRing
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.GradedQcAlgebraSectionsToQcAlgebra
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.GradedAlgebraTotalComponent
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.GeneratedInDegreeOneSections
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.SymGradedAlgebraGeneratedInDegreeOne
import MiyaokaMori.AlgebraicGeometry.Modules.SymGenTotalLinearMap

/-! # The section ring of the symmetric algebra sheaf is generated in degree one

**Surjectivity half of `symGradedAlgebra_sectionsRing_isSymmetricAlgebra`.** For `W` quasi-coherent on a
scheme `X` and `U ⊆ X` an affine open, the `Γ(X, U)`-algebra map `Sym_{Γ(X,U)} Γ(U, W) → A(U) := Γ(U, Sym W)`
induced by the degree-one inclusion `symGenTotalLinearMap W U` (`SymGradedAlgebraSectionsIsSymmetricAlgebra.lean`)
is surjective: `A(U)` is generated as a `Γ(X, U)`-algebra by the degree-one sections
(`symGradedAlgebra_lift_symGenTotalLinearMap_surjective`).

Ingredients:
* `exists_finset_sum_eq_of_isColimit_of_isCompact`: sections of a coproduct of sheaves of modules over a
  quasi-compact open are finite sums of images of the pieces (the open-`U` version of
  `CoproductSectionsLocallyFinite.lean`; Stacks 01AI, "`Γ(U, −)` commutes with direct sums for
  `U` quasi-compact");
* `GradedQCAlgebra.sectionsToTotalRingHom_surjective`: hence `⨁_m Γ(U, S_m) → Γ(U, ∐_m S_m)` is surjective for
  `U` quasi-compact (the ring homomorphism of `GradedQcAlgebraSectionsToQcAlgebra.lean`
  for the inclusions `totalIncl`);
* `GeneratedInDegreeOne.sectionsGrading_mem_closure` (`GeneratedInDegreeOneSections.lean`, Stacks 01N0 on
  sections) with `symGradedAlgebra_generatedInDegreeOne`: positive-degree sections lie in the subring generated by
  `range (sectionsUnitHom U) ∪ A(U)_1`;
* `symPowπ_zero_isIso`, `symPowπ_one_isIso`, `symGen_isIso`: `O_X → Sym^0 W` and `W → Sym^1 W` are isomorphisms
  (no transposition to quotient by), so degree `0` is `Γ(X, U)` and degree `1` is `Γ(U, W)`.

The companion module `TotalSpaceSectionsRingEquivMvPolynomialSymSectionsInjective.lean` states the injectivity
half and assembles `IsSymmetricAlgebra`. Source: Bourbaki Algebra III §6, Stacks 01CG/01N0.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry CategoryTheory.MonoidalCategory

noncomputable section

namespace AlgebraicGeometry.Scheme.Modules

variable {X : AlgebraicGeometry.Scheme.{u}}

/-- **Sections of a coproduct over a quasi-compact open are finite sums** (Stacks 01AI type statement,
"Γ(U, −) commutes with direct sums for `U` quasi-compact"): the open-`U` version of
`exists_finset_sum_eq_of_isColimit` (`CoproductSectionsLocallyFinite.lean`).
For a colimit cocone `c` of a discrete diagram with "projections" `p q : c.pt ⟶ F_q` (`ι_m ≫ p q = 0` for
`m ≠ q`, `ι_q ≫ p q = 𝟙`), a section `t` of `c.pt` over a quasi-compact open `U` has only finitely many
nonzero components `(p q) t`, and `t = Σ_q ι_q ((p q) t)` over any finite set containing them.

Proof: cover `U` by the opens `V x` of `exists_locally_finite_sum_of_isColimit`
(`t|_{V x} = Σ_{m ∈ s x} ι_m (z x m)`), take a finite subcover (`IsCompact.elim_nhds_subcover'`) and
`Fs := ⋃ s x`; on `V x`, `(p q)(t|_{V x}) = if q ∈ s x then z x q else 0` by the orthogonality relations, so
both claims hold after restriction to every `V x`; conclude by separatedness (`TopCat.Sheaf.eq_of_locally_eq'`). -/
theorem exists_finset_sum_eq_of_isColimit_of_isCompact {ι : Type}
    {F : Discrete ι ⥤ X.Modules} {c : Cocone F} (hc : IsColimit c)
    (p : ∀ q : ι, c.pt ⟶ F.obj ⟨q⟩)
    (hp0 : ∀ m q, m ≠ q → c.ι.app ⟨m⟩ ≫ p q = 0)
    (hp1 : ∀ m, c.ι.app ⟨m⟩ ≫ p m = 𝟙 _)
    (U : X.Opens) (hU : IsCompact (U : Set X))
    (t : (c.pt.val.obj (op U) : Type u)) :
    ∃ Fs : Finset ι, (∀ q, q ∉ Fs → ((p q).val.app (op U)).hom t = 0) ∧
      ∑ q ∈ Fs, ((c.ι.app ⟨q⟩).val.app (op U)).hom (((p q).val.app (op U)).hom t) = t := by
  classical
  have hloc : ∀ x : (U : Set X), ∃ (V : X.Opens) (hVU : V ≤ U), (x : X) ∈ V ∧
      ∃ (s : Finset ι) (z : ∀ i, ((F.obj ⟨i⟩).val.obj (op V) : Type u)),
        c.pt.val.map (homOfLE hVU).op t = ∑ i ∈ s, ((c.ι.app ⟨i⟩).val.app (op V)).hom (z i) :=
    fun x => exists_locally_finite_sum_of_isColimit hc U t x.1 x.2
  choose V hVU hxV s z hz using hloc
  obtain ⟨T, hT⟩ := hU.elim_nhds_subcover' (fun x hx => ((V ⟨x, hx⟩ : X.Opens) : Set X))
    (fun x hx => (V ⟨x, hx⟩).isOpen.mem_nhds (hxV ⟨x, hx⟩))
  -- separatedness on the finite cover
  have hsep : ∀ (M : X.Modules) (a b : (M.val.obj (op U) : Type u)),
      (∀ x ∈ T, M.val.map (homOfLE (hVU x)).op a = M.val.map (homOfLE (hVU x)).op b) → a = b := by
    intro M a b h
    let Sh : TopCat.Sheaf AddCommGrpCat.{u} X := ⟨M.val.presheaf, M.isSheaf⟩
    refine Sh.eq_of_locally_eq' (fun x : T => V x.1) U (fun x => homOfLE (hVU x.1)) ?_ a b
      (fun x => h x.1 x.2)
    intro y hy
    have hy' := hT hy
    rw [Set.mem_iUnion₂] at hy'
    obtain ⟨x, hx, hyx⟩ := hy'
    exact Opens.mem_iSup.mpr ⟨⟨x, hx⟩, hyx⟩
  -- components of the restrictions
  have hcompo : ∀ (x : (U : Set X)) (q : ι),
      ((p q).val.app (op (V x))).hom (c.pt.val.map (homOfLE (hVU x)).op t) =
        if q ∈ s x then z x q else 0 := by
    intro x q
    have hterm : ∀ m ∈ s x,
        ((p q).val.app (op (V x))).hom (((c.ι.app ⟨m⟩).val.app (op (V x))).hom (z x m)) =
          if m = q then (if q ∈ s x then z x q else 0) else 0 := by
      intro m hm
      have h5 : ((p q).val.app (op (V x))).hom (((c.ι.app ⟨m⟩).val.app (op (V x))).hom (z x m)) =
          (((c.ι.app ⟨m⟩ ≫ p q).val.app (op (V x))).hom (z x m)) := rfl
      by_cases hmq : m = q
      · subst hmq
        refine h5.trans ?_
        refine (congrArg (fun g : F.obj ⟨m⟩ ⟶ F.obj ⟨m⟩ => (g.val.app (op (V x))).hom (z x m))
          (hp1 m)).trans ?_
        rw [if_pos rfl, if_pos hm]
        rfl
      · refine h5.trans ?_
        refine (congrArg (fun g : F.obj ⟨m⟩ ⟶ F.obj ⟨q⟩ => (g.val.app (op (V x))).hom (z x m))
          (hp0 m q hmq)).trans ?_
        rw [if_neg hmq]
        rfl
    refine (congrArg (((p q).val.app (op (V x))).hom) (hz x)).trans ?_
    refine (map_sum ((p q).val.app (op (V x))).hom
      (fun i => ((c.ι.app ⟨i⟩).val.app (op (V x))).hom (z x i)) (s x)).trans ?_
    refine (Finset.sum_congr rfl hterm).trans ?_
    refine (Finset.sum_ite_eq' (s x) q (fun _ => if q ∈ s x then z x q else 0)).trans ?_
    by_cases hq : q ∈ s x
    · rw [if_pos hq]
    · rw [if_neg hq, if_neg hq]
  refine ⟨T.biUnion s, ?_, ?_⟩
  · intro q hq
    refine hsep (F.obj ⟨q⟩) _ 0 fun x hx => ?_
    have hqx : q ∉ s x := fun h => hq (Finset.mem_biUnion.mpr ⟨x, hx, h⟩)
    have hn : (F.obj ⟨q⟩).val.map (homOfLE (hVU x)).op (((p q).val.app (op U)).hom t) =
        ((p q).val.app (op (V x))).hom (c.pt.val.map (homOfLE (hVU x)).op t) :=
      (_root_.PresheafOfModules.naturality_apply (p q).val (homOfLE (hVU x)).op t).symm
    refine (hn.trans ((hcompo x q).trans (if_neg hqx))).trans ?_
    exact (map_zero _).symm
  · refine hsep c.pt _ t fun x hx => ?_
    have hsub : s x ⊆ T.biUnion s := fun q hq => Finset.mem_biUnion.mpr ⟨x, hx, hq⟩
    have hterm : ∀ q ∈ T.biUnion s,
        c.pt.val.map (homOfLE (hVU x)).op
            (((c.ι.app ⟨q⟩).val.app (op U)).hom (((p q).val.app (op U)).hom t)) =
          if q ∈ s x then ((c.ι.app ⟨q⟩).val.app (op (V x))).hom (z x q) else 0 := by
      intro q _
      have hn1 : c.pt.val.map (homOfLE (hVU x)).op
            (((c.ι.app ⟨q⟩).val.app (op U)).hom (((p q).val.app (op U)).hom t)) =
          ((c.ι.app ⟨q⟩).val.app (op (V x))).hom
            ((F.obj ⟨q⟩).val.map (homOfLE (hVU x)).op (((p q).val.app (op U)).hom t)) :=
        (_root_.PresheafOfModules.naturality_apply (c.ι.app ⟨q⟩).val (homOfLE (hVU x)).op
          (((p q).val.app (op U)).hom t)).symm
      have hn2 : (F.obj ⟨q⟩).val.map (homOfLE (hVU x)).op (((p q).val.app (op U)).hom t) =
          ((p q).val.app (op (V x))).hom (c.pt.val.map (homOfLE (hVU x)).op t) :=
        (_root_.PresheafOfModules.naturality_apply (p q).val (homOfLE (hVU x)).op t).symm
      refine hn1.trans ((congrArg _ (hn2.trans (hcompo x q))).trans ?_)
      by_cases hq : q ∈ s x
      · rw [if_pos hq, if_pos hq]
      · rw [if_neg hq, if_neg hq]
        exact map_zero _
    refine (map_sum (c.pt.val.map (homOfLE (hVU x)).op).hom _ _).trans ?_
    refine (Finset.sum_congr rfl hterm).trans ?_
    refine (Finset.sum_ite_mem (T.biUnion s) (s x) _).trans ?_
    rw [Finset.inter_eq_right.mpr hsub]
    exact (hz x).symm

end AlgebraicGeometry.Scheme.Modules

namespace AlgebraicGeometry.Scheme.GradedQCAlgebra

variable {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra)

/-- `ι_m ≫ totalProj q = 0` for `m ≠ q`. -/

theorem totalIncl_totalProj_of_ne_sss {m q : ℕ} (hmq : m ≠ q) : S.totalIncl m ≫ S.totalProj q = 0 :=
  (Sigma.ι_desc (fun m => if h : m = q then CategoryTheory.eqToHom (congrArg S.part h) else 0) m).trans
    (dif_neg hmq)

/-- **Sections of `S.total` over a quasi-compact open are finite sums of graded pieces**:
`a = Σ_{q ∈ Fs} ι_q (π_q a)` with `π_q a = 0` outside `Fs` (`exists_finset_sum_eq_of_isColimit_of_isCompact`
applied to the coproduct `∐ S.part` with the projections `totalProj`). -/
theorem total_sections_exists_finset_sum (U : X.Opens) (hU : IsCompact (U : Set X))
    (a : S.total.sectionsRing U) :
    ∃ Fs : Finset ℕ, (∀ q, q ∉ Fs → (S.totalProj q).app U a = 0) ∧
      ∑ q ∈ Fs, (S.totalIncl q).app U ((S.totalProj q).app U a) = a := by
  have hc : IsColimit (colimit.cocone (Discrete.functor S.part)) := colimit.isColimit _
  have hp0 : ∀ m q : ℕ, m ≠ q →
      (colimit.cocone (Discrete.functor S.part)).ι.app ⟨m⟩ ≫ S.totalProj q = 0 :=
    fun m q hmq => S.totalIncl_totalProj_of_ne_sss hmq
  have hp1 : ∀ m : ℕ, (colimit.cocone (Discrete.functor S.part)).ι.app ⟨m⟩ ≫ S.totalProj m = 𝟙 _ :=
    fun m => S.totalIncl_totalProj m
  exact AlgebraicGeometry.Scheme.Modules.exists_finset_sum_eq_of_isColimit_of_isCompact hc
    S.totalProj hp0 hp1 U hU a

/-- The graded pieces sit in `S.total` compatibly with the unit (definitional). -/
theorem one_comp_totalIncl : S.one ≫ S.totalIncl 0 = S.total.one := rfl

/-- The graded pieces sit in `S.total` compatibly with the multiplication (`total_mul_component`). -/
theorem mul_comp_totalIncl (m n : ℕ) :
    S.mul m n ≫ S.totalIncl (m + n) = (S.totalIncl m ⊗ₘ S.totalIncl n) ≫ S.total.mul :=
  (S.total_mul_component m n).symm

/-- The ring homomorphism `⨁_m Γ(U, S_m) →+* Γ(U, ∐_m S_m)` induced by the inclusions `totalIncl`. -/
noncomputable def sectionsToTotalRingHom (U : X.Opens) : S.sectionsRing U →+* S.total.sectionsRing U :=
  S.sectionsToRingHom S.total S.totalIncl S.one_comp_totalIncl S.mul_comp_totalIncl U

theorem sectionsToTotalRingHom_of (U : X.Opens) (m : ℕ) (a : S.sectionsPiece U m) :
    S.sectionsToTotalRingHom U (DirectSum.of (S.sectionsPiece U) m a) = (S.totalIncl m).app U a :=
  S.sectionsToRingHom_of S.total S.totalIncl S.one_comp_totalIncl S.mul_comp_totalIncl U m a

theorem sectionsToTotalRingHom_sectionsUnitHom (U : X.Opens) (r : Γ(X, U)) :
    S.sectionsToTotalRingHom U (S.sectionsUnitHom U r) = S.total.sectionsUnit U r := by
  refine (S.sectionsToTotalRingHom_of U 0 (S.one.app U r)).trans ?_
  rfl

/-- **`⨁_m Γ(U, S_m) → Γ(U, ∐_m S_m)` is surjective for `U` quasi-compact**
(`total_sections_exists_finset_sum`). -/
theorem sectionsToTotalRingHom_surjective (U : X.Opens) (hU : IsCompact (U : Set X)) :
    Function.Surjective (S.sectionsToTotalRingHom U) := by
  intro a
  obtain ⟨Fs, -, hsum⟩ := S.total_sections_exists_finset_sum U hU a
  refine ⟨∑ q ∈ Fs, S.ofPiece U q ((S.totalProj q).app U a), ?_⟩
  rw [map_sum (S.sectionsToTotalRingHom U)]
  refine Eq.trans (Finset.sum_congr rfl fun q _ => S.sectionsToTotalRingHom_of U q _) hsum

end AlgebraicGeometry.Scheme.GradedQCAlgebra

namespace AlgebraicGeometry.Scheme.Modules

variable {X : AlgebraicGeometry.Scheme.{u}}

/-- The quotient map `𝟙_ = W^{⊗0} → Sym^0 W` is an isomorphism (no transpositions to quotient by). -/
theorem symPowπ_zero_isIso (W : X.Modules) : IsIso (symPowπ W 0) := by
  let inv := symPowDesc W 0 (𝟙 _) (fun i => i.elim0)
  have h₁ : symPowπ W 0 ≫ inv = 𝟙 _ := by
    dsimp only [inv]
    rw [symPowπ_desc]
  have h₂ : inv ≫ symPowπ W 0 = 𝟙 _ := by
    apply (cancel_epi (symPowπ W 0)).1
    rw [← Category.assoc, h₁, Category.id_comp, Category.comp_id]
  exact ⟨inv, h₁, h₂⟩

/-- The quotient map `W^{⊗1} → Sym^1 W` is an isomorphism (the only "transposition" is the identity). -/
theorem symPowπ_one_isIso (W : X.Modules) : IsIso (symPowπ W 1) := by
  have htr : ∀ i : Fin 1, monoidalPowTransp W 1 i = 𝟙 _ := fun i => by
    rw [Fin.fin_one_eq_zero i]; rfl
  let inv := symPowDesc W 1 (𝟙 _) (fun i => by rw [htr i, Category.id_comp])
  have h₁ : symPowπ W 1 ≫ inv = 𝟙 _ := by
    dsimp only [inv]
    rw [symPowπ_desc]
  have h₂ : inv ≫ symPowπ W 1 = 𝟙 _ := by
    apply (cancel_epi (symPowπ W 1)).1
    rw [← Category.assoc, h₁, Category.id_comp, Category.comp_id]
  exact ⟨inv, h₁, h₂⟩

/-- For quasi-coherent `W`, `symGradedAlgebra W` is the branch `symGradedAlgebraOfQC W _`. -/
theorem symGradedAlgebra_eq_ofQC_sss (W : X.Modules) (hq : W.IsQuasicoherent) :
    symGradedAlgebra W = symGradedAlgebraOfQC W hq := by
  delta symGradedAlgebra
  exact dif_pos hq

/-- For quasi-coherent `W` the unit `O_X → Sym^0 W` of `symGradedAlgebra W` is an isomorphism. -/
theorem symGradedAlgebra_one_isIso_ofQC (W : X.Modules) [hq : W.IsQuasicoherent] :
    IsIso (symGradedAlgebra W).one := by
  rw [symGradedAlgebra_eq_ofQC_sss W hq]
  exact symPowπ_zero_isIso W

/-- For quasi-coherent `W` the generator inclusion `symGen W : W → Sym^1 W` is an isomorphism. -/
theorem symGen_isIso (W : X.Modules) [hq : W.IsQuasicoherent] : IsIso (symGen W) := by
  have h1 := symPowπ_one_isIso W
  unfold symGen
  rw [dif_pos hq]
  exact IsIso.comp_isIso' inferInstance (IsIso.comp_isIso' h1 inferInstance)

/-- **Surjectivity half of `IsSymmetricAlgebra`**: for `W` quasi-coherent and `U` affine, the algebra map
`Sym_{Γ(X,U)} Γ(U, W) → A(U) = Γ(U, Sym W)` induced by the degree-one inclusion `symGenTotalLinearMap` is
surjective, i.e. `A(U)` is generated as a `Γ(X, U)`-algebra by the degree-one sections.

Proof. `A(U)` receives the ring homomorphism `ψ : ⨁_m Γ(U, Sym^m W) → A(U)` (`sectionsToTotalRingHom`), which
is surjective because `U` is quasi-compact (`sectionsToTotalRingHom_surjective`). Every element of the graded
section ring lies in the subring generated by `range (sectionsUnitHom U) ∪ A(U)_1`: in degree `0` because
`S.one : O_X → Sym^0 W` is an isomorphism (`symGradedAlgebra_one_isIso_ofQC`), in positive degrees by
`GeneratedInDegreeOne.sectionsGrading_mem_closure` (`Sym W` is generated in degree one,
`symGradedAlgebra_generatedInDegreeOne`; Stacks 01N0 on sections over an affine open). `ψ` sends
`sectionsUnitHom U r` to `algebraMap r` and a degree-one section `b = symGen n` to `symGenTotalLinearMap n =
lift (ι n)` (`symGen` is an isomorphism, `symGen_isIso`), so the image of the generating set lies in the range
of `lift`, hence so does everything. -/
theorem symGradedAlgebra_lift_symGenTotalLinearMap_surjective (W : X.Modules) [hq : W.IsQuasicoherent]
    (U : X.affineOpens) :
    letI := ((symGradedAlgebra W).total.sectionsUnit U.1).toAlgebra
    Function.Surjective (SymmetricAlgebra.lift (symGenTotalLinearMap W U.1)) := by
  letI := ((symGradedAlgebra W).total.sectionsUnit U.1).toAlgebra
  let T : Subring ((symGradedAlgebra W).total.sectionsRing U.1) :=
    (SymmetricAlgebra.lift (symGenTotalLinearMap W U.1)).range.toSubring
  -- 1. every element of the graded section ring lies in the closure of `range unit ∪ A(U)_1`
  have hone : IsIso (symGradedAlgebra W).one := symGradedAlgebra_one_isIso_ofQC W
  have hgen : ∀ x : (symGradedAlgebra W).sectionsRing U.1, x ∈ Subring.closure
      (Set.range ((symGradedAlgebra W).sectionsUnitHom U.1) ∪
        ((symGradedAlgebra W).sectionsGrading U.1 1 : Set ((symGradedAlgebra W).sectionsRing U.1))) := by
    intro x
    refine DirectSum.induction_on (β := (symGradedAlgebra W).sectionsPiece U.1)
      (motive := fun x => x ∈ Subring.closure
        (Set.range ((symGradedAlgebra W).sectionsUnitHom U.1) ∪
          ((symGradedAlgebra W).sectionsGrading U.1 1 : Set ((symGradedAlgebra W).sectionsRing U.1))))
      x ?_ ?_ ?_
    · exact Subring.zero_mem _
    · rintro (_ | m) a
      · -- degree `0`: `a = S.one.app U r`, so `of 0 a = sectionsUnitHom U r`
        obtain ⟨r, hr⟩ := (ConcreteCategory.bijective_of_isIso ((symGradedAlgebra W).one.app U.1)).2 a
        refine Subring.subset_closure (Or.inl ⟨r, ?_⟩)
        show DirectSum.of ((symGradedAlgebra W).sectionsPiece U.1) 0 ((symGradedAlgebra W).one.app U.1 r) =
          DirectSum.of ((symGradedAlgebra W).sectionsPiece U.1) 0 a
        rw [hr]
      · exact GradedQCAlgebra.GeneratedInDegreeOne.sectionsGrading_mem_closure
          (symGradedAlgebra_generatedInDegreeOne W) U.2 (Nat.succ_pos m) ⟨a, rfl⟩
    · intro x y hx hy
      exact Subring.add_mem _ hx hy
  -- 2. the image of the generating set under `ψ` lies in `T`
  have himg : ((symGradedAlgebra W).sectionsToTotalRingHom U.1) ''
      (Set.range ((symGradedAlgebra W).sectionsUnitHom U.1) ∪
        ((symGradedAlgebra W).sectionsGrading U.1 1 : Set ((symGradedAlgebra W).sectionsRing U.1))) ⊆ T := by
    rintro _ ⟨x, hx, rfl⟩
    rcases hx with ⟨r, rfl⟩ | ⟨b, rfl⟩
    · rw [(symGradedAlgebra W).sectionsToTotalRingHom_sectionsUnitHom]
      exact Subalgebra.algebraMap_mem (SymmetricAlgebra.lift (symGenTotalLinearMap W U.1)).range r
    · rw [(symGradedAlgebra W).sectionsToTotalRingHom_of]
      have hsg := symGen_isIso W
      obtain ⟨n, hn⟩ := (ConcreteCategory.bijective_of_isIso ((symGen W).app U.1)).2 b
      refine ⟨SymmetricAlgebra.ι _ _ n, ?_⟩
      show SymmetricAlgebra.lift (symGenTotalLinearMap W U.1) (SymmetricAlgebra.ι _ _ n) = _
      rw [SymmetricAlgebra.lift_ι_apply, symGenTotalLinearMap_apply, Hom.comp_app]
      show ((symGradedAlgebra W).totalIncl 1).app U.1 ((symGen W).app U.1 n) = _
      rw [hn]
  -- 3. conclude
  intro a
  obtain ⟨x, rfl⟩ := (symGradedAlgebra W).sectionsToTotalRingHom_surjective U.1 U.2.isCompact a
  exact Subring.closure_le.mpr himg
    (Subring.mem_closure_image_of ((symGradedAlgebra W).sectionsToTotalRingHom U.1) (hgen x))

end AlgebraicGeometry.Scheme.Modules

end
