import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.OfGradedQCAlgebra
import MiyaokaMori.RingTheory.GradedRing.WeightedSymGrading
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.WeightedSymAlgebra
import MiyaokaMori.AlgebraicGeometry.Proj.WeightedProj.WeightedSymGenerator
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.WeightedSymSectionsRingEquivSymEval

/-! # The section ring of the weighted symmetric algebra sheaf on an affine open

On an **affine** open `U`, the section ring `⨁_m Γ(U, S_m)` of the sheaf-theoretic
`weightedSymAlgebra V` (`S_m = ⨁_{d ∈ D_m} ⊗_q Sym^{d_q}(V_q^∨)`) is the algebraic weighted symmetric
algebra `Sym_{Γ(U)}(⨁_q Γ(U, V_q^∨))` of `WeightedSymGrading.lean`, with the `m`-th graded piece going to `WeightedSym.piece w m`
(`w q = q + 1`) and the structure map going to `algebraMap`.

Sources: Stacks 01CG (Sym^n of a quasi-coherent module is the sheafification of `U ↦ Sym^n Γ(U, F)`;
on an affine `U` with `F` quasi-coherent this is `Γ(U, Sym^n F) = Sym^n Γ(U, F)`, Stacks 01I8 applied to
the qc module `Sym^n F`, cf. Stacks 01OB), Stacks 01I8 (sections of a tensor product of qc modules over
an affine open: `Γ(U, F ⊗ G) = Γ(U, F) ⊗_{Γ(U)} Γ(U, G)`), `Γ(U, ⨁) = ⨁ Γ(U, -)` for finite biproducts
(Γ(U, -) is additive). §2 of the paper (`S` is locally a finitely generated weighted polynomial algebra).

## Structure

The isomorphism is **not** built piece by piece; it is the inverse of the canonical `Γ(U)`-algebra map
given by the universal property of the symmetric algebra (Bourbaki Algebra III §6 no. 1):

* `sectionsAlgebra`: the `Γ(U)`-algebra structure on the section ring via `sectionsUnitHom` (local instance);
* `genSections`: `Γ(U, V_q^∨) → ⨁_m Γ(U, S_m)`, `w ↦ of (q+1) ((genIncl V q).app U w)` — sections of the
  generator inclusion `V_q^∨ → S_{q+1}` of `WeightedSymGenerator.lean`; it is `Γ(U)`-linear;
* `symLiftHom : Sym_{Γ(U)}(⨁_q Γ(U, V_q^∨)) →+* ⨁_m Γ(U, S_m)`: `SymmetricAlgebra.lift` of the direct sum
  of the `genSections`. It sends `algebraMap` to `sectionsUnitHom` (`symLiftHom_algebraMap`) and
  `WeightedSym.piece w m` into `sectionsGrading m` (`symLiftHom_mem_sectionsGrading`, by the induction
  principle `WeightedSym.piece_le_of_gen`).
* `symLiftHom_bijective` — `symLiftHom` is bijective when `U` is affine (this is where Stacks 01CG / 01I8 enter).
  Assembled from `WeightedSymSectionsRingEquivSymPure.lean`: surjectivity from
  `closure_sectionsUnitHom_genIncl_eq_top` (the section ring is generated by `Γ(U)` and the `genSections`), injectivity
  from a left inverse `exists_addMonoidHom_sectionsRing` together with `span_monomials_eq_top` (ordered monomials span
  `Sym`). The affine inputs are `span_range_weightedTensorPure_eq_top` and
  `exists_linearMap_weightedTensorPure` there (consequences of the bijectivity of `tensorSectionsHom` and the
  coequalizer description of `Sym^e` on affine opens).
* From injectivity alone: `symLiftHom a ∈ sectionsGrading m ↔ a ∈ piece w m`
  (`symLiftHom_mem_sectionsGrading_iff`, by comparing the two `DirectSum.decompose`).
* The target theorem takes `e := (RingEquiv.ofBijective symLiftHom _).symm`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory Opposite DirectSum
open scoped AlgebraicGeometry

noncomputable section

namespace AlgebraicGeometry.Scheme.weightedSymAlgebra

variable {X : AlgebraicGeometry.Scheme.{u}} {r : ℕ} (V : Fin r → X.Modules)
  [∀ q, (V q).IsLocallyFree] [∀ q, (V q).IsFiniteType] (U : X.Opens)

/-- The section modules of the generators `V_q^∨` (the `W q` of `WeightedSymGrading`). -/
abbrev genSectionsModule : Fin r → Type u := fun q => Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U)

/-- The weights `w q = q + 1`. -/
abbrev weight : Fin r → ℕ := fun q => (q : ℕ) + 1

/-- The `Γ(U)`-algebra structure on the section ring `⨁_m Γ(U, S_m)` given by the structure map
`sectionsUnitHom`. **Local instance only** (registered with `attribute [local instance]` below):
`sectionsRing` is a `def`, so no other `Algebra Γ(X, U)` instance is visible on it. -/
@[instance_reducible] def sectionsAlgebra :
    Algebra Γ(X, U) ((AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsRing U) :=
  ((AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsUnitHom U).toAlgebra

attribute [local instance] sectionsAlgebra

theorem smul_def' (c : Γ(X, U)) (z : (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsRing U) :
    c • z = (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsUnitHom U c * z := rfl

theorem algebraMap_eq (c : Γ(X, U)) :
    algebraMap Γ(X, U) ((AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsRing U) c =
      (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsUnitHom U c := rfl

/-- Sections of the generator inclusion `V_q^∨ → S_{q+1}` (`weightedSymAlgebra.genIncl`), placed in
degree `q + 1` of the section ring. -/
def genSections (q : Fin r) (w : Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U)) :
    (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsRing U :=
  (AlgebraicGeometry.Scheme.weightedSymAlgebra V).ofPiece U ((q : ℕ) + 1)
    ((AlgebraicGeometry.Scheme.weightedSymAlgebra.genIncl V q).app U w)

theorem genSections_mem_sectionsGrading (q : Fin r)
    (w : Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U)) :
    genSections V U q w ∈
      (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading U ((q : ℕ) + 1) :=
  ⟨_, rfl⟩

theorem genSections_add (q : Fin r) (w w' : Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U)) :
    genSections V U q (w + w') = genSections V U q w + genSections V U q w' := by
  unfold genSections
  rw [map_add]
  exact map_add (DirectSum.of ((AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsPiece U)
    ((q : ℕ) + 1)) _ _

theorem genSections_smul (q : Fin r) (c : Γ(X, U))
    (w : Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U)) :
    genSections V U q (c • w) = c • genSections V U q w := by
  rw [smul_def']
  unfold genSections
  rw [AlgebraicGeometry.Scheme.Modules.Hom.app_smul]
  exact ((AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsUnitHom_mul_ofPiece U c _).symm

/-- `genSections` as a `Γ(U)`-linear map. -/
def genLinear (q : Fin r) :
    Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U) →ₗ[Γ(X, U)]
      (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsRing U where
  toFun := genSections V U q
  map_add' := genSections_add V U q
  map_smul' := genSections_smul V U q

/-- The generator map `⨁_q Γ(U, V_q^∨) → ⨁_m Γ(U, S_m)`. -/
def genDirectSum :
    (⨁ q, Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U)) →ₗ[Γ(X, U)]
      (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsRing U :=
  DirectSum.toModule Γ(X, U) (Fin r) _ (genLinear V U)

/-- **The canonical algebra map** `Sym_{Γ(U)}(⨁_q Γ(U, V_q^∨)) → ⨁_m Γ(U, S_m)`
(universal property of the symmetric algebra). -/
def symLift :
    SymmetricAlgebra Γ(X, U) (⨁ q, Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U)) →ₐ[Γ(X, U)]
      (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsRing U :=
  SymmetricAlgebra.lift (genDirectSum V U)

/-- `symLift` as a ring homomorphism (its type does not mention the local algebra instance). -/
def symLiftHom :
    SymmetricAlgebra Γ(X, U) (⨁ q, Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U)) →+*
      (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsRing U :=
  (symLift V U).toRingHom

theorem symLiftHom_apply
    (a : SymmetricAlgebra Γ(X, U) (⨁ q, Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U))) :
    symLiftHom V U a = symLift V U a := rfl

theorem symLiftHom_algebraMap (c : Γ(X, U)) :
    symLiftHom V U (algebraMap Γ(X, U) _ c) =
      (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsUnitHom U c :=
  (symLift V U).commutes c

theorem symLiftHom_gen (q : Fin r) (w : Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U)) :
    symLiftHom V U (WeightedSym.gen Γ(X, U) (genSectionsModule V U) q w) = genSections V U q w := by
  rw [symLiftHom_apply]
  show SymmetricAlgebra.lift (genDirectSum V U)
    (SymmetricAlgebra.ι Γ(X, U) _ (DirectSum.lof Γ(X, U) (Fin r) (genSectionsModule V U) q w)) = _
  rw [SymmetricAlgebra.lift_ι_apply]
  exact DirectSum.toModule_lof (R := Γ(X, U)) (M := genSectionsModule V U) (φ := genLinear V U) q w

theorem symLiftHom_smul (c : Γ(X, U))
    (a : SymmetricAlgebra Γ(X, U) (⨁ q, Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U))) :
    symLiftHom V U (c • a) =
      (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsUnitHom U c * symLiftHom V U a := by
  rw [Algebra.smul_def, map_mul, symLiftHom_algebraMap]

/-- **Weighted pieces go to graded pieces**: `symLiftHom (piece w m) ⊆ sectionsGrading m`
(induction principle `WeightedSym.piece_le_of_gen`: `1 ∈ grading 0`, `grading i * grading j ⊆ grading (i+j)`,
`genSections q ∈ grading (q+1)`). -/
theorem symLiftHom_mem_sectionsGrading {m : ℕ}
    {a : SymmetricAlgebra Γ(X, U) (⨁ q, Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U))}
    (ha : a ∈ WeightedSym.piece Γ(X, U) (genSectionsModule V U) (weight (r := r)) m) :
    symLiftHom V U a ∈ (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading U m := by
  let Q : ℕ → Submodule Γ(X, U)
      (SymmetricAlgebra Γ(X, U) (⨁ q, Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U))) := fun k =>
    { carrier := {b | symLiftHom V U b ∈ (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading U k}
      add_mem' := fun {x y} hx hy => by
        show symLiftHom V U (x + y) ∈ (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading U k
        rw [map_add]
        exact add_mem hx hy
      zero_mem' := by
        show symLiftHom V U 0 ∈ (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading U k
        rw [map_zero]
        exact zero_mem _
      smul_mem' := fun c x hx => by
        show symLiftHom V U (c • x) ∈ (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading U k
        rw [symLiftHom_smul]
        have h0 : (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsUnitHom U c ∈
            (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading U 0 :=
          ((AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsUnit U c).2
        have := (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading_mul_mem U h0 hx
        rwa [Nat.zero_add] at this }
  have h1 : (1 : SymmetricAlgebra Γ(X, U) (⨁ q, Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U))) ∈ Q 0 := by
    show symLiftHom V U 1 ∈ (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading U 0
    rw [map_one]
    exact (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading_one_mem U
  have hmul : ∀ i j, Q i * Q j ≤ Q (i + j) := fun i j => by
    refine Submodule.mul_le.mpr fun x hx y hy => ?_
    show symLiftHom V U (x * y) ∈ (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading U (i + j)
    rw [map_mul]
    exact (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading_mul_mem U hx hy
  have hgen : ∀ q, WeightedSym.genSpan Γ(X, U) (genSectionsModule V U) q ≤ Q (weight q) := by
    rintro q _ ⟨w, rfl⟩
    show symLiftHom V U (WeightedSym.gen Γ(X, U) (genSectionsModule V U) q w) ∈
      (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading U ((q : ℕ) + 1)
    rw [symLiftHom_gen]
    exact genSections_mem_sectionsGrading V U q w
  exact WeightedSym.piece_le_of_gen h1 hmul hgen m ha

/-- The ordered monomial `∏_q ∏_i gen q (w q i)` of `Sym_{Γ(U)}(⨁_q Γ(U, V_q^∨))` attached to a multidegree `d` and a
family `w q : Fin (d q) → Γ(U, V_q^∨)`. -/
def monomial (p : Σ d : Fin r → ℕ, ∀ q, Fin (d q) → genSectionsModule V U q) :
    SymmetricAlgebra (X.presheaf.obj (Opposite.op U)) (⨁ q, genSectionsModule V U q) :=
  ∏ q, ∏ i, WeightedSym.gen (X.presheaf.obj (Opposite.op U)) (genSectionsModule V U) q (p.2 q i)

omit [∀ q, (V q).IsLocallyFree] [∀ q, (V q).IsFiniteType] in
theorem monomial_mul (p p' : Σ d : Fin r → ℕ, ∀ q, Fin (d q) → genSectionsModule V U q) :
    monomial V U p * monomial V U p' = monomial V U ⟨p.1 + p'.1, fun q => Fin.append (p.2 q) (p'.2 q)⟩ := by
  unfold monomial
  rw [← Finset.prod_mul_distrib]
  refine Fintype.prod_congr _ _ fun q => ?_
  refine Eq.trans ?_ (Fin.prod_univ_add (fun i : Fin (p.1 q + p'.1 q) =>
    WeightedSym.gen (X.presheaf.obj (Opposite.op U)) (genSectionsModule V U) q (Fin.append (p.2 q) (p'.2 q) i))).symm
  congr 1
  · exact Fintype.prod_congr _ _ fun i => by rw [Fin.append_left]
  · exact Fintype.prod_congr _ _ fun i => by rw [Fin.append_right]

omit [∀ q, (V q).IsLocallyFree] [∀ q, (V q).IsFiniteType] in
theorem monomial_zero : monomial V U ⟨0, fun _ => Fin.elim0⟩ = 1 := by
  unfold monomial
  exact Fintype.prod_eq_one _ fun q => Fintype.prod_eq_one _ fun i => (show Fin 0 from i).elim0

omit [∀ q, (V q).IsLocallyFree] [∀ q, (V q).IsFiniteType] in
/-- The one-factor monomial of `gen q y`. -/
theorem monomial_single (q : Fin r) (y : genSectionsModule V U q) :
    monomial V U ⟨fun q' => if q' = q then 1 else 0, fun q' i => if h : q' = q then
        cast (congrArg (genSectionsModule V U) h.symm) y else (Fin.cast (if_neg h) i).elim0⟩ =
      WeightedSym.gen (X.presheaf.obj (Opposite.op U)) (genSectionsModule V U) q y := by
  unfold monomial
  rw [Finset.prod_eq_single q]
  · have h1 : ∀ i : Fin (if q = q then 1 else 0),
        (if h : q = q then cast (congrArg (genSectionsModule V U) h.symm) y
          else (Fin.cast (if_neg h) i).elim0) = y := fun i => by
      rw [dif_pos rfl]
      exact cast_eq _ y
    rw [Fintype.prod_congr _ _ fun i => congrArg _ (h1 i), Finset.prod_const, Finset.card_univ,
      Fintype.card_fin, if_pos rfl, pow_one]
  · intro q' _ hq'
    exact Fintype.prod_eq_one _ fun i => (Fin.cast (if_neg hq') i).elim0
  · intro h
    exact absurd (Finset.mem_univ q) h

/-- **Ordered monomials span the weighted symmetric algebra**: the `Γ(U)`-span of the `monomial V U p` is all of
`Sym_{Γ(U)}(⨁_q Γ(U, V_q^∨))`. Proof by `SymmetricAlgebra.induction`: `algebraMap c = c • 1` and `1` is the empty
monomial (`monomial_zero`); `ι x = Σ_q gen q (x q)` (`DirectSum.sum_univ_of`) and `gen q y` is a one-factor monomial
(`monomial_single`); the span is closed under multiplication (`monomial_mul`). -/
theorem span_monomials_eq_top : Submodule.span (X.presheaf.obj (Opposite.op U)) (Set.range (monomial V U)) = ⊤ := by
  have hmono : ∀ p, monomial V U p ∈ Submodule.span (X.presheaf.obj (Opposite.op U)) (Set.range (monomial V U)) :=
    fun p => Submodule.subset_span ⟨p, rfl⟩
  have hmul : Submodule.span (X.presheaf.obj (Opposite.op U)) (Set.range (monomial V U)) *
      Submodule.span (X.presheaf.obj (Opposite.op U)) (Set.range (monomial V U)) ≤ Submodule.span (X.presheaf.obj (Opposite.op U)) (Set.range (monomial V U)) := by
    rw [Submodule.span_mul_span]
    refine Submodule.span_le.mpr ?_
    rintro _ ⟨_, ⟨p, rfl⟩, _, ⟨p', rfl⟩, rfl⟩
    show monomial V U p * monomial V U p' ∈ Submodule.span (X.presheaf.obj (Opposite.op U)) (Set.range (monomial V U))
    rw [monomial_mul]
    exact hmono _
  refine Submodule.eq_top_iff'.mpr fun a => ?_
  induction a using SymmetricAlgebra.induction with
  | algebraMap c =>
    rw [Algebra.algebraMap_eq_smul_one]
    refine Submodule.smul_mem _ c ?_
    have h := hmono ⟨0, fun _ => Fin.elim0⟩
    rw [monomial_zero] at h
    exact h
  | ι x =>
    rw [← DirectSum.sum_univ_of x, map_sum]
    refine Submodule.sum_mem _ fun q _ => ?_
    have h := hmono ⟨fun q' => if q' = q then 1 else 0, fun q' i => if h : q' = q then
      cast (congrArg (genSectionsModule V U) h.symm) (x q) else (Fin.cast (if_neg h) i).elim0⟩
    rw [monomial_single] at h
    exact h
  | mul a b ha hb => exact hmul (Submodule.mul_mem_mul ha hb)
  | add a b ha hb => exact Submodule.add_mem _ ha hb

/-- **Bijectivity of the canonical map on an affine open** — the content of Stacks 01CG / 01I8 in this
encoding. Notation: `S := weightedSymAlgebra V`, `W_q := Γ(U, V_q^∨)`, `R := Γ(U)`,
`A := Sym_R(⨁_q W_q)`, `φ := symLiftHom V U : A → ⨁_m Γ(U, S_m)`.

Proof, assembled from `WeightedSymSectionsRingEquivSymPure.lean`:
* **Surjectivity.** The range of `φ` is a subring containing `range sectionsUnitHom` (`symLiftHom_algebraMap`) and every
  `genSections q x = ofPiece (q+1) (genIncl_q x)` (`symLiftHom_gen`); on an affine `U` these generate the whole section ring
  (`weightedSymAlgebra.closure_sectionsUnitHom_genIncl_eq_top`: every section of `S_m = ⨁_{d ∈ D_m} T_d` is a sum of
  `Γ(U)`-combinations of pure sections of the `T_d` — `span_range_weightedTensorPure_eq_top`, Stacks 01I8/01CG — and a pure
  section is a product of generators, `ofPiece_ι_weightedTensorPure`).
* **Injectivity.** `weightedSymAlgebra.exists_addMonoidHom_sectionsRing` gives an additive, `Γ(U)`-linear
  `ψ : ⨁_m Γ(U, S_m) → A` with `ψ (∏_q ∏_i genSections q (w q i)) = ∏_q ∏_i gen q (w q i)` (built from linear maps out of
  `Γ(U, T_d)` prescribed on pure sections, `exists_linearMap_weightedTensorPure`, Stacks 01I8/01CG). Then `ψ ∘ φ` is
  `Γ(U)`-linear and is the identity on the ordered monomials `∏_q ∏_i gen q (w q i)`, which span `A`
  (`span_monomials_eq_top`); hence `ψ ∘ φ = id` and `φ` is injective.

The affine inputs are `span_range_weightedTensorPure_eq_top` and `exists_linearMap_weightedTensorPure` of
`WeightedSymSectionsRingEquivSymPure.lean` (both consequences of the bijectivity of `tensorSectionsHom` and the
coequalizer description of `Sym^e` on affine opens).

Edge cases: `r = 0` (`A = R`, section ring `= Γ(U, 𝟙_) = R` in degree 0, `0` elsewhere; `φ = sectionsUnitHom`, bijective
by `part 0 = T_0 = 𝟙_` and `part m = 0` for `m > 0` since `D_m = ∅`); `U = ⊥` (both sides the zero ring); `V_q = 0`
(`W_q = 0`, `Sym^e 0 = 0` for `e > 0`, consistent on both sides). -/
theorem symLiftHom_bijective {U : X.Opens} (hU : AlgebraicGeometry.IsAffineOpen U) :
    Function.Bijective (symLiftHom V U) := by
  constructor
  · obtain ⟨ψ, hψ_smul, hψ_mono⟩ := exists_addMonoidHom_sectionsRing V hU
      (C := SymmetricAlgebra Γ(X, U) (⨁ q, Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U)))
      (fun q => WeightedSym.gen Γ(X, U) (genSectionsModule V U) q)
    have key : ∀ a, ψ (symLiftHom V U a) = a := by
      intro a
      have ha : a ∈ Submodule.span (X.presheaf.obj (Opposite.op U)) (Set.range (monomial V U)) := by
        rw [span_monomials_eq_top]
        trivial
      refine Submodule.span_induction ?_ ?_ ?_ ?_ ha
      · rintro _ ⟨⟨d, w⟩, rfl⟩
        have h1 : ∀ q, symLiftHom V U (∏ i, WeightedSym.gen (X.presheaf.obj (Opposite.op U))
            (genSectionsModule V U) q (w q i)) = ∏ i, genSections V U q (w q i) := fun q => by
          rw [map_prod]
          exact Fintype.prod_congr _ _ fun i => symLiftHom_gen V U q (w q i)
        have h2 : symLiftHom V U (monomial V U ⟨d, w⟩) = ∏ q, ∏ i, genSections V U q (w q i) := by
          unfold monomial
          rw [map_prod]
          exact Fintype.prod_congr _ _ h1
        rw [h2]
        exact hψ_mono d w
      · rw [map_zero, map_zero]
      · intro x y _ _ hx hy
        rw [map_add, map_add, hx, hy]
      · intro c x _ hx
        rw [symLiftHom_smul, hψ_smul, hx]
    exact fun a b hab => by rw [← key a, hab, key b]
  · have hle : Subring.closure (Set.range ((AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsUnitHom U) ∪
        ⋃ q : Fin r, Set.range (fun x : Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U) =>
          (AlgebraicGeometry.Scheme.weightedSymAlgebra V).ofPiece U ((q : ℕ) + 1) ((genIncl V q).app U x))) ≤
        (symLiftHom V U).range := by
      refine Subring.closure_le.mpr (Set.union_subset ?_ ?_)
      · rintro _ ⟨c, rfl⟩
        exact ⟨algebraMap Γ(X, U) _ c, symLiftHom_algebraMap V U c⟩
      · intro z hz
        obtain ⟨q, hq⟩ := Set.mem_iUnion.mp hz
        obtain ⟨x, rfl⟩ := hq
        exact ⟨WeightedSym.gen Γ(X, U) (genSectionsModule V U) q x, symLiftHom_gen V U q x⟩
    rw [closure_sectionsUnitHom_genIncl_eq_top V hU] at hle
    exact fun z => hle trivial

/-- The decompositions of `φ a` (in `sectionsGrading`) and of `a` (in `piece w`) match componentwise. -/
theorem decompose_symLiftHom
    (a : SymmetricAlgebra Γ(X, U) (⨁ q, Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U))) (k : ℕ) :
    ((DirectSum.decompose ((AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading U)
        (symLiftHom V U a) k : (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading U k) :
        (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsRing U) =
      symLiftHom V U
        (DirectSum.decompose (WeightedSym.piece Γ(X, U) (genSectionsModule V U) (weight (r := r))) a k :
          SymmetricAlgebra Γ(X, U) (⨁ q, Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U))) := by
  refine DirectSum.Decomposition.inductionOn
    (ℳ := WeightedSym.piece Γ(X, U) (genSectionsModule V U) (weight (r := r))) ?_ ?_ ?_ a
  · rw [map_zero, DirectSum.decompose_zero, DirectSum.decompose_zero, DirectSum.zero_apply,
      DirectSum.zero_apply, ZeroMemClass.coe_zero, ZeroMemClass.coe_zero, map_zero]
  · intro j x
    have hx : (x : SymmetricAlgebra Γ(X, U) (⨁ q, Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U))) ∈
        WeightedSym.piece Γ(X, U) (genSectionsModule V U) (weight (r := r)) j := x.2
    by_cases hjk : j = k
    · subst hjk
      rw [DirectSum.decompose_of_mem_same _ hx,
        DirectSum.decompose_of_mem_same _ (symLiftHom_mem_sectionsGrading V U hx)]
    · rw [DirectSum.decompose_of_mem_ne _ hx hjk,
        DirectSum.decompose_of_mem_ne _ (symLiftHom_mem_sectionsGrading V U hx) hjk, map_zero]
  · intro x y hx hy
    rw [map_add, DirectSum.decompose_add, DirectSum.decompose_add, DirectSum.add_apply,
      DirectSum.add_apply, AddSubgroup.coe_add, Submodule.coe_add, map_add, hx, hy]

/-- **Graded pieces correspond** (needs only injectivity of `φ`): `φ a ∈ sectionsGrading m ↔ a ∈ piece w m`. -/
theorem symLiftHom_mem_sectionsGrading_iff (hinj : Function.Injective (symLiftHom V U)) (m : ℕ)
    (a : SymmetricAlgebra Γ(X, U) (⨁ q, Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U))) :
    symLiftHom V U a ∈ (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading U m ↔
      a ∈ WeightedSym.piece Γ(X, U) (genSectionsModule V U) (weight (r := r)) m := by
  refine ⟨fun h => ?_, symLiftHom_mem_sectionsGrading V U⟩
  set ℳ := WeightedSym.piece Γ(X, U) (genSectionsModule V U) (weight (r := r)) with hℳ
  have hzero : ∀ k, k ≠ m → DirectSum.decompose ℳ a k = 0 := by
    intro k hk
    apply Subtype.ext
    apply hinj
    rw [ZeroMemClass.coe_zero, map_zero, ← decompose_symLiftHom,
      DirectSum.decompose_of_mem_ne _ h (Ne.symm hk)]
  have hdec : DirectSum.decompose ℳ a = DirectSum.of (fun k => ℳ k) m (DirectSum.decompose ℳ a m) := by
    refine DirectSum.ext fun k => ?_
    by_cases hk : k = m
    · subst hk
      rw [DirectSum.of_eq_same]
    · rw [DirectSum.of_eq_of_ne m k _ hk, hzero k hk]
  have ha : a = (DirectSum.decompose ℳ a m : _) := by
    conv_lhs => rw [← (DirectSum.decompose ℳ).symm_apply_apply a, hdec, DirectSum.decompose_symm_of]
  rw [ha]
  exact (DirectSum.decompose ℳ a m).2

end AlgebraicGeometry.Scheme.weightedSymAlgebra

/-- **Section ring of the old weighted Sym on an affine open = algebraic weighted Sym.**

Notation: `S := weightedSymAlgebra V`, `W_q := Γ(U, V_q^∨)` (a `Γ(U)`-module), `w q := q + 1`,
`A := Sym_{Γ(U)}(⨁_q W_q)` with the weighted grading `WeightedSym.piece w`.

Proof: `e` is the inverse of the canonical algebra map `φ := symLiftHom V U : A → ⨁_m Γ(U, S_m)`
(universal property of `Sym`, generators sent to the sections of `genIncl V q : V_q^∨ → S_{q+1}`), which is
bijective on affine `U` (`symLiftHom_bijective`; Stacks 01CG / 01I8, through
`WeightedSymSectionsRingEquivSymPure.lean`). The grading
statement is `symLiftHom_mem_sectionsGrading_iff` (from injectivity of `φ`: `φ (piece w m) ⊆ sectionsGrading m` by
`WeightedSym.piece_le_of_gen`, and the two `DirectSum.decompose` match componentwise); the unit statement is
`symLiftHom_algebraMap` (`φ` is a `Γ(U)`-algebra map for the algebra structure given by `sectionsUnitHom`).

Edge cases: `r = 0` (both sides `Γ(U)` in degree 0, `0` elsewhere),
`U = ⊥` (both sides the zero ring), `ρ = 0` (the rank does not occur in this statement).

Relation to the paper (§2: `S = ⊕_m S_m`, `S_m` locally free with local basis the weight-`m` monomials in
coordinates of weights `1, …, k`; `S` is locally a finitely generated weighted polynomial algebra): on every affine
open `U`, the section ring of `weightedSymAlgebra V` (`V_q^∨` in weight `q + 1`) is `Sym_{Γ(U)}(⊕_q Γ(U, V_q^∨))`
with `Γ(U, S_m)` corresponding to the weighted-degree-`m` polynomials in the generators
(`WeightedSym.piece (q ↦ q + 1) m`) and `sectionsUnitHom` to `algebraMap` — the Stacks 01CG / 01I8 content, which
holds on every affine open, not only on trivializing ones. The user `weightedSym_locally_weighted_polynomial`
consumes the three components (`e`; the grading equivalence in the direction
`a ∈ sectionsGrading m ↔ e a ∈ piece w m`; the unit equation) as the `equiv` / `equiv_grading` / `equiv_unit` fields
of a `WeightedPolynomialAtlas`, composed with `WeightedSym.equivMvPolynomial` on a trivializing chart. -/
theorem AlgebraicGeometry.Scheme.weightedSymAlgebra.exists_sectionsRing_equiv_symmetricAlgebra
    {X : AlgebraicGeometry.Scheme.{u}} {r : ℕ} (V : Fin r → X.Modules)
    [∀ q, (V q).IsLocallyFree] [∀ q, (V q).IsFiniteType] (U : X.AffineZariskiSite) :
    ∃ e : (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsRing U.toOpens ≃+*
        SymmetricAlgebra Γ(X, U.toOpens)
          (⨁ q, Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U.toOpens)),
      (∀ (m : ℕ) (a : (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsRing U.toOpens),
        a ∈ (AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsGrading U.toOpens m ↔
          e a ∈ WeightedSym.piece Γ(X, U.toOpens)
            (fun q : Fin r => Γ(AlgebraicGeometry.Scheme.Modules.dual (V q), U.toOpens))
            (fun q : Fin r => (q : ℕ) + 1) m) ∧
      (∀ s : Γ(X, U.toOpens),
        e ((AlgebraicGeometry.Scheme.weightedSymAlgebra V).sectionsUnitHom U.toOpens s) =
          algebraMap Γ(X, U.toOpens) _ s) := by
  open AlgebraicGeometry.Scheme.weightedSymAlgebra in
  have hbij := symLiftHom_bijective V U.2
  let e0 := RingEquiv.ofBijective (symLiftHom V U.toOpens) hbij
  refine ⟨e0.symm, fun m a => ?_, fun s => ?_⟩
  · obtain ⟨b, rfl⟩ : ∃ b, e0 b = a := hbij.2 a
    rw [e0.symm_apply_apply]
    exact symLiftHom_mem_sectionsGrading_iff V U.toOpens hbij.1 m b
  · apply e0.injective
    rw [e0.apply_symm_apply]
    exact (symLiftHom_algebraMap V U.toOpens s).symm

end
