import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.OfGradedQCAlgebra
import MiyaokaMori.AlgebraicGeometry.Modules.Basic.BiproductSections
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.TensorSectionsBilinear
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.ModulesTensorSectionsCoherence
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.WeightedSymAlgebra
import MiyaokaMori.AlgebraicGeometry.Proj.WeightedProj.WeightedSymGenerator
import MiyaokaMori.AlgebraicGeometry.Modules.TotalSpace.TotalSpaceSectionConstructions

/-! # Pure sections of the weighted symmetric algebra sheaf

Sheaf-side toolkit for the bijectivity statement `symLiftHom_bijective` of
`WeightedSymSectionsRingEquivSym.lean`. Notation: `S := weightedSymAlgebra V`,
`F q := V_q^∨`, `T_d := weightedSymTensor r F d = ⊗_q Sym^{d q}(F q)`, `R := Γ(X, U)`.

* `GradedQCAlgebra.gradedPure S g e v`: the section `g v_0 ⋯ g v_{e-1}` of `S.part e` (iterated `S.mul` with the
  degree-one map `g : V ⟶ S.part 1`); in the section ring it is the product of the `ofPiece 1 (g v_i)`
  (`ofPiece_gradedPure`).
* `weightedTensorPure U r F d w`: the **pure section** `⊗_q (w_{q,0} ⋯ w_{q,d q - 1})` of `T_d`, recursive in `r`
  along `weightedSymTensor` (`tensorSections` of the `Sym^{d 0}(F 0)`-factor and the tail).
* `weightedSymTensorMul_app_weightedTensorPure`: `mulTerm a b (pure a wa ⊗ pure b wb) = pure (a+b) (append)`;
  `weightedSymTensorGen_app`: the generator inclusion of `WeightedSymGenerator.lean` on a section is the pure section
  with one factor; `weightedSymTensorOne_app_one`: the unit is the empty pure section.
* `weightedTensorPure_eq_prod`: any multiplicative, unital evaluation `Φ` of the graded layer `(T_d)_d` into a
  commutative monoid sends a pure section to the product of its one-factor pure sections.
* `weightedSymAlgebra.ofPiece_ι_weightedTensorPure`: in the section ring `⨁_m Γ(U, S_m)`,
  `ι_d (pure d w) = ∏_q ∏_i genIncl_q (w q i)`.
* Two statements that use the affine hypothesis (Stacks 01I8 / 01CG through the bijectivity of
  `tensorSectionsHom` and the coequalizer description of `Sym^e` on affine opens):
  `span_range_weightedTensorPure_eq_top` (pure sections span
  `Γ(U, T_d)`) and `exists_linearMap_weightedTensorPure` (a linear map out of `Γ(U, T_d)` may be prescribed on pure
  sections by a multilinear expression). From them: `weightedSymAlgebra.closure_sectionsUnitHom_genIncl_eq_top`
  (the section ring is generated by `Γ(U)` and the generators) and `weightedSymAlgebra.exists_addMonoidHom_sectionsRing`
  (the left inverse of `symLiftHom`).

Sources: Stacks 01CG, 01I8; Bourbaki Algebra III §6; §2 of the paper (the weighted symmetric algebra).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits CategoryTheory.MonoidalCategory Opposite
open scoped AlgebraicGeometry

noncomputable section

namespace AlgebraicGeometry.Scheme

variable {X : AlgebraicGeometry.Scheme.{u}} (U : X.Opens)

/-! ## Sections of morphisms: small toolkit -/

namespace Modules

/-- `tensorSections` with every section typed as `Γ(·, U)`, syntactically uniform with `Hom.app`
(`tensorSections` itself types its arguments as `·.val.obj (op U)`; the two spellings are definitionally equal but
`rw` does not see through them). -/
def tsec (A B : X.Modules) (U : X.Opens) (a : Γ(A, U)) (b : Γ(B, U)) : Γ(A ⊗ B, U) :=
  tensorSections A B U a b

/-- The section `1 ∈ Γ(U) = Γ(U, 𝟙_)` of the tensor unit, typed as a section of `𝟙_ X.Modules`. -/
def unitSec (U : X.Opens) : Γ(𝟙_ X.Modules, U) := (1 : Γ(X, U))

theorem comp_app_apply_sec {A B C : X.Modules} (f : A ⟶ B) (g : B ⟶ C) (x : Γ(A, U)) :
    (f ≫ g).app U x = g.app U (f.app U x) := by
  rw [AlgebraicGeometry.Scheme.Modules.Hom.comp_app, ConcreteCategory.comp_apply]

theorem iso_inv_app_eq {A B : X.Modules} (f : A ≅ B) {x : Γ(A, U)} {y : Γ(B, U)}
    (h : f.hom.app U x = y) : f.inv.app U y = x := by
  subst h
  have := congrArg (fun k : A ⟶ A => k.app U x) f.hom_inv_id
  exact this

/-- `eqToHom` between (definitionally) equal objects acts as the identity on sections. -/
theorem eqToHom_app_self {A : X.Modules} (h : A = A) (x : Γ(A, U)) : (eqToHom h).app U x = x := by
  rw [eqToHom_refl]
  rfl

theorem tensorHom_app_tsec {A B A' B' : X.Modules} (φ : A ⟶ A') (ψ : B ⟶ B') (a : Γ(A, U)) (b : Γ(B, U)) :
    (φ ⊗ₘ ψ).app U (tsec A B U a b) = tsec A' B' U (φ.app U a) (ψ.app U b) :=
  tensorHom_tensorSections φ ψ U a b

theorem whiskerLeft_app_tsec (A : X.Modules) {B B' : X.Modules} (f : B ⟶ B') (a : Γ(A, U)) (b : Γ(B, U)) :
    (A ◁ f).app U (tsec A B U a b) = tsec A B' U a (f.app U b) := by
  rw [← MonoidalCategory.id_tensorHom]
  exact tensorHom_tensorSections (𝟙 A) f U a b

theorem whiskerRight_app_tsec {A A' : X.Modules} (f : A ⟶ A') (B : X.Modules) (a : Γ(A, U)) (b : Γ(B, U)) :
    (f ▷ B).app U (tsec A B U a b) = tsec A' B U (f.app U a) b := by
  rw [← MonoidalCategory.tensorHom_id]
  exact tensorHom_tensorSections f (𝟙 B) U a b

theorem associator_app_tsec (A B C : X.Modules) (a : Γ(A, U)) (b : Γ(B, U)) (c : Γ(C, U)) :
    (α_ A B C).hom.app U (tsec (A ⊗ B) C U (tsec A B U a b) c) = tsec A (B ⊗ C) U a (tsec B C U b c) :=
  associator_app_tensorSections A B C U a b c

theorem associator_inv_app_tsec (A B C : X.Modules) (a : Γ(A, U)) (b : Γ(B, U)) (c : Γ(C, U)) :
    (α_ A B C).inv.app U (tsec A (B ⊗ C) U a (tsec B C U b c)) = tsec (A ⊗ B) C U (tsec A B U a b) c :=
  iso_inv_app_eq U (α_ A B C) (associator_app_tsec U A B C a b c)

theorem braiding_app_tsec (A B : X.Modules) (a : Γ(A, U)) (b : Γ(B, U)) :
    (β_ A B).hom.app U (tsec A B U a b) = tsec B A U b a :=
  braiding_app_tensorSections A B U a b

theorem leftUnitor_app_tsec (A : X.Modules) (r : Γ(X, U)) (a : Γ(A, U)) :
    (λ_ A).hom.app U (tsec (𝟙_ X.Modules) A U r a) = r • a :=
  leftUnitor_app_tensorSections A U r a

theorem rightUnitor_app_tsec (A : X.Modules) (a : Γ(A, U)) (r : Γ(X, U)) :
    (ρ_ A).hom.app U (tsec A (𝟙_ X.Modules) U a r) = r • a :=
  rightUnitor_app_tensorSections A U a r

theorem leftUnitor_app_tsec_unitSec (A : X.Modules) (a : Γ(A, U)) :
    (λ_ A).hom.app U (tsec (𝟙_ X.Modules) A U (unitSec U) a) = a :=
  (leftUnitor_app_tensorSections A U 1 a).trans (one_smul _ a)

theorem rightUnitor_app_tsec_unitSec (A : X.Modules) (a : Γ(A, U)) :
    (ρ_ A).hom.app U (tsec A (𝟙_ X.Modules) U a (unitSec U)) = a :=
  (rightUnitor_app_tensorSections A U a 1).trans (one_smul _ a)

theorem leftUnitor_inv_app (A : X.Modules) (a : Γ(A, U)) :
    (λ_ A).inv.app U a = tsec (𝟙_ X.Modules) A U (unitSec U) a :=
  iso_inv_app_eq U (λ_ A) (leftUnitor_app_tsec_unitSec U A a)

theorem rightUnitor_inv_app (A : X.Modules) (a : Γ(A, U)) :
    (ρ_ A).inv.app U a = tsec A (𝟙_ X.Modules) U a (unitSec U) :=
  iso_inv_app_eq U (ρ_ A) (rightUnitor_app_tsec_unitSec U A a)

theorem tsec_smul_left (A B : X.Modules) (r : Γ(X, U)) (a : Γ(A, U)) (b : Γ(B, U)) :
    tsec A B U (r • a) b = r • tsec A B U a b :=
  tensorSections_smul_left A B U r a b _ rfl

theorem tsec_smul_right (A B : X.Modules) (r : Γ(X, U)) (a : Γ(A, U)) (b : Γ(B, U)) :
    tsec A B U a (r • b) = r • tsec A B U a b :=
  tensorSections_smul_right A B U r a b _ rfl

theorem tsec_add_left (A B : X.Modules) (a a' : Γ(A, U)) (b : Γ(B, U)) :
    tsec A B U (a + a') b = tsec A B U a b + tsec A B U a' b :=
  tensorSections_add_left A B U a a' b

theorem tsec_add_right (A B : X.Modules) (a : Γ(A, U)) (b b' : Γ(B, U)) :
    tsec A B U a (b + b') = tsec A B U a b + tsec A B U a b' :=
  tensorSections_add_right A B U a b b'

/-- `tensorμ` (the middle-four interchange) on pure sections. -/
theorem tensorμ_app_tsec (X₁ X₂ Y₁ Y₂ : X.Modules) (x₁ : Γ(X₁, U)) (x₂ : Γ(X₂, U))
    (y₁ : Γ(Y₁, U)) (y₂ : Γ(Y₂, U)) :
    (tensorμ X₁ X₂ Y₁ Y₂).app U (tsec (X₁ ⊗ X₂) (Y₁ ⊗ Y₂) U (tsec X₁ X₂ U x₁ x₂) (tsec Y₁ Y₂ U y₁ y₂)) =
      tsec (X₁ ⊗ Y₁) (X₂ ⊗ Y₂) U (tsec X₁ Y₁ U x₁ y₁) (tsec X₂ Y₂ U x₂ y₂) := by
  unfold tensorμ
  rw [comp_app_apply_sec, comp_app_apply_sec, comp_app_apply_sec, comp_app_apply_sec, associator_app_tsec,
    whiskerLeft_app_tsec, associator_inv_app_tsec, whiskerLeft_app_tsec, whiskerRight_app_tsec,
    braiding_app_tsec, whiskerLeft_app_tsec, associator_app_tsec, associator_inv_app_tsec]

end Modules

/-! ## Pure sections of a graded piece -/

namespace GradedQCAlgebra

/-- The section `g v_0 ⋯ g v_{e-1}` of `S.part e`: iterated multiplication `S.mul e 1` of the images of the
`v_i` under the degree-one map `g` (`e = 0`: the unit `S.one 1`). -/
def gradedPure (S : X.GradedQCAlgebra) {V : X.Modules} (g : V ⟶ S.part 1) :
    (e : ℕ) → (Fin e → Γ(V, U)) → Γ(S.part e, U)
  | 0, _ => S.one.app U (AlgebraicGeometry.Scheme.Modules.unitSec U)
  | e + 1, v => (S.mul e 1).app U (AlgebraicGeometry.Scheme.Modules.tsec (S.part e) (S.part 1) U
      (gradedPure S g e (Fin.init v)) (g.app U (v (Fin.last e))))

theorem gradedPure_zero (S : X.GradedQCAlgebra) {V : X.Modules} (g : V ⟶ S.part 1) (v : Fin 0 → Γ(V, U)) :
    S.gradedPure U g 0 v = S.one.app U (AlgebraicGeometry.Scheme.Modules.unitSec U) := rfl

theorem gradedPure_succ (S : X.GradedQCAlgebra) {V : X.Modules} (g : V ⟶ S.part 1) (e : ℕ)
    (v : Fin (e + 1) → Γ(V, U)) :
    S.gradedPure U g (e + 1) v = (S.mul e 1).app U (AlgebraicGeometry.Scheme.Modules.tsec
      (S.part e) (S.part 1) U (S.gradedPure U g e (Fin.init v)) (g.app U (v (Fin.last e)))) := rfl

/-- `ofPiece (m + n) (S.mul m n (a ⊗ b)) = ofPiece m a * ofPiece n b` in the section ring. -/
theorem ofPiece_mul_app_tsec (S : X.GradedQCAlgebra) {m n : ℕ} (a : Γ(S.part m, U))
    (b : Γ(S.part n, U)) :
    S.ofPiece U (m + n) ((S.mul m n).app U
        (AlgebraicGeometry.Scheme.Modules.tsec (S.part m) (S.part n) U a b)) =
      S.ofPiece U m a * S.ofPiece U n b :=
  (DirectSum.of_mul_of (A := S.sectionsPiece U) a b).symm

theorem ofPiece_one_app_one (S : X.GradedQCAlgebra) :
    S.ofPiece U 0 (S.one.app U (AlgebraicGeometry.Scheme.Modules.unitSec U)) = 1 :=
  (DirectSum.one_def (A := S.sectionsPiece U)).symm

theorem ofPiece_eqToHom_app (S : X.GradedQCAlgebra) {m n : ℕ} (h : m = n) (x : Γ(S.part m, U)) :
    S.ofPiece U n ((eqToHom (congrArg S.part h)).app U x) = S.ofPiece U m x := by
  subst h
  rw [eqToHom_refl]
  rfl

/-- In the section ring, `gradedPure e v` is the product of the degree-one sections `g v_i`. -/
theorem ofPiece_gradedPure (S : X.GradedQCAlgebra) {V : X.Modules} (g : V ⟶ S.part 1) (e : ℕ)
    (v : Fin e → Γ(V, U)) :
    S.ofPiece U e (S.gradedPure U g e v) = ∏ i, S.ofPiece U 1 (g.app U (v i)) := by
  induction e with
  | zero => rw [gradedPure_zero, ofPiece_one_app_one, Fin.prod_univ_zero]
  | succ e ih =>
    rw [gradedPure_succ]
    rw [ofPiece_mul_app_tsec, ih, Fin.prod_univ_castSucc]
    rfl

/-- Multiplication of pure sections of the graded pieces: concatenation of the factors. -/
theorem mul_app_gradedPure (S : X.GradedQCAlgebra) {V : X.Modules} (g : V ⟶ S.part 1) (m n : ℕ)
    (v : Fin m → Γ(V, U)) (v' : Fin n → Γ(V, U)) :
    (S.mul m n).app U (AlgebraicGeometry.Scheme.Modules.tsec (S.part m) (S.part n) U
        (S.gradedPure U g m v) (S.gradedPure U g n v')) =
      S.gradedPure U g (m + n) (Fin.append v v') := by
  apply S.ofPiece_injective U (m + n)
  rw [ofPiece_mul_app_tsec, ofPiece_gradedPure, ofPiece_gradedPure, ofPiece_gradedPure,
    Fin.prod_univ_add]
  congr 1
  · exact Fintype.prod_congr _ _ fun i => by rw [Fin.append_left]
  · exact Fintype.prod_congr _ _ fun i => by rw [Fin.append_right]

/-- The unit times a section of `S.part m` (on sections of `S.one_mul`). -/
theorem mul_app_one_tsec (S : X.GradedQCAlgebra) (m : ℕ) (b : Γ(S.part m, U)) :
    (S.mul 0 m).app U (AlgebraicGeometry.Scheme.Modules.tsec (S.part 0) (S.part m) U
        (S.one.app U (AlgebraicGeometry.Scheme.Modules.unitSec U)) b) =
      (eqToHom (congrArg S.part (Nat.zero_add m).symm)).app U b := by
  have h := congrArg (fun k : 𝟙_ X.Modules ⊗ S.part m ⟶ S.part (0 + m) =>
    k.app U (AlgebraicGeometry.Scheme.Modules.tsec (𝟙_ X.Modules) (S.part m) U
      (AlgebraicGeometry.Scheme.Modules.unitSec U) b)) (S.one_mul m)
  simp only at h
  rw [Modules.comp_app_apply_sec, Modules.comp_app_apply_sec, Modules.whiskerRight_app_tsec,
    Modules.leftUnitor_app_tsec_unitSec] at h
  exact h

/-- A degree-one section, viewed in `S.part e` for `e = 1`, is the one-factor pure section. -/
theorem eqToHom_app_eq_gradedPure_one (S : X.GradedQCAlgebra) {V : X.Modules} (g : V ⟶ S.part 1)
    {e : ℕ} (he : e = 1) (x : Γ(V, U)) (w : Fin e → Γ(V, U)) (hw : ∀ i, w i = x) :
    (eqToHom (congrArg S.part he.symm)).app U (g.app U x) = S.gradedPure U g e w := by
  subst he
  rw [eqToHom_refl, Modules.Hom.id_app, gradedPure_succ, gradedPure_zero, hw, mul_app_one_tsec]
  exact (Modules.eqToHom_app_self U _ _).symm

/-- The unit section, viewed in `S.part e` for `e = 0`, is the empty pure section. -/
theorem eqToHom_app_eq_gradedPure_zero (S : X.GradedQCAlgebra) {V : X.Modules} (g : V ⟶ S.part 1)
    {e : ℕ} (he : e = 0) (w : Fin e → Γ(V, U)) :
    (eqToHom (congrArg S.part he.symm)).app U (S.one.app U (AlgebraicGeometry.Scheme.Modules.unitSec U)) = S.gradedPure U g e w := by
  subst he
  rw [eqToHom_refl]
  rfl

end GradedQCAlgebra

/-! ## Pure sections of the weighted tensor layer -/

/-- Identity map re-typing a section of `Sym^{d 0}(F 0) ⊗ T_{tail d}` as a section of `T_d` at the `r + 1` layer
(`weightedSymTensor.eq_2`); the two types are definitionally equal but syntactically different, and keeping the
retyping explicit keeps every statement below well-typed at reducible transparency (`rw`-safe). -/
def weightedTensorUp (r : ℕ) (F : Fin (r + 1) → X.Modules) (d : Fin (r + 1) → ℕ)
    (x : Γ((AlgebraicGeometry.Scheme.Modules.symGradedAlgebra (F 0)).part (d 0) ⊗
      AlgebraicGeometry.Scheme.weightedSymTensor r (Fin.tail F) (Fin.tail d), U)) :
    Γ(AlgebraicGeometry.Scheme.weightedSymTensor (r + 1) F d, U) := x

/-- The retyping `weightedTensorUp` for multidegrees `Fin.cons 0 d'` with empty first block, with the domain
spelled through `Sym^0(F 0) ⊗ T_{d'}` (again definitionally equal, syntactically different). -/
def weightedTensorUp₀ (r : ℕ) (F : Fin (r + 1) → X.Modules) (d' : Fin r → ℕ)
    (x : Γ((AlgebraicGeometry.Scheme.Modules.symGradedAlgebra (F 0)).part 0 ⊗
      AlgebraicGeometry.Scheme.weightedSymTensor r (Fin.tail F) d', U)) :
    Γ(AlgebraicGeometry.Scheme.weightedSymTensor (r + 1) F (Fin.cons (0 : ℕ) d'), U) := x

/-- **Pure sections** of `⊗_q Sym^{d q}(F q)`: `⊗_q (w_{q,0} ⋯ w_{q, d q - 1})`, recursive in `r` along
`weightedSymTensor` (the `Sym^{d 0}(F 0)`-factor is `gradedPure` for `symGen (F 0)`, the tail is the pure section of
the tail; `r = 0`: the section `1` of `𝟙_ = O_X`). -/
def weightedTensorPure : (r : ℕ) → (F : Fin r → X.Modules) → (d : Fin r → ℕ) →
    (∀ q, Fin (d q) → Γ(F q, U)) → Γ(AlgebraicGeometry.Scheme.weightedSymTensor r F d, U)
  | 0, _, _, _ => AlgebraicGeometry.Scheme.Modules.unitSec U
  | r + 1, F, d, w => weightedTensorUp U r F d (AlgebraicGeometry.Scheme.Modules.tsec _ _ U
      ((AlgebraicGeometry.Scheme.Modules.symGradedAlgebra (F 0)).gradedPure U
        (AlgebraicGeometry.Scheme.Modules.symGen (F 0)) (d 0) (w 0))
      (weightedTensorPure r (Fin.tail F) (Fin.tail d) (fun q => w q.succ)))

theorem weightedTensorPure_zero (F : Fin 0 → X.Modules) (d : Fin 0 → ℕ) (w : ∀ q, Fin (d q) → Γ(F q, U)) :
    weightedTensorPure U 0 F d w = AlgebraicGeometry.Scheme.Modules.unitSec U := rfl

theorem weightedTensorPure_succ (r : ℕ) (F : Fin (r + 1) → X.Modules) (d : Fin (r + 1) → ℕ)
    (w : ∀ q, Fin (d q) → Γ(F q, U)) :
    weightedTensorPure U (r + 1) F d w = weightedTensorUp U r F d (AlgebraicGeometry.Scheme.Modules.tsec _ _ U
      ((AlgebraicGeometry.Scheme.Modules.symGradedAlgebra (F 0)).gradedPure U
        (AlgebraicGeometry.Scheme.Modules.symGen (F 0)) (d 0) (w 0))
      (weightedTensorPure U r (Fin.tail F) (Fin.tail d) (fun q => w q.succ))) := rfl

/-- Transport of sections along an equality of multidegrees. -/
def weightedTensorCast (r : ℕ) (F : Fin r → X.Modules) {d d' : Fin r → ℕ} (h : d = d')
    (x : Γ(AlgebraicGeometry.Scheme.weightedSymTensor r F d, U)) :
    Γ(AlgebraicGeometry.Scheme.weightedSymTensor r F d', U) :=
  (eqToHom (congrArg (AlgebraicGeometry.Scheme.weightedSymTensor r F) h)).app U x

theorem weightedTensorCast_rfl (r : ℕ) (F : Fin r → X.Modules) {d : Fin r → ℕ}
    (x : Γ(AlgebraicGeometry.Scheme.weightedSymTensor r F d, U)) :
    weightedTensorCast U r F rfl x = x := by
  unfold weightedTensorCast
  rw [eqToHom_refl]
  rfl

/-- Pure sections are compatible with transport: if `d = d'` and the families agree along `Fin.cast`, the pure
sections agree. -/
theorem weightedTensorCast_weightedTensorPure (r : ℕ) (F : Fin r → X.Modules) {d d' : Fin r → ℕ} (h : d = d')
    (w : ∀ q, Fin (d q) → Γ(F q, U)) (w' : ∀ q, Fin (d' q) → Γ(F q, U))
    (hw : ∀ q i, w q i = w' q (Fin.cast (congrFun h q) i)) :
    weightedTensorCast U r F h (weightedTensorPure U r F d w) = weightedTensorPure U r F d' w' := by
  subst h
  rw [weightedTensorCast_rfl]
  congr 1
  funext q i
  exact hw q i

/-- **The unit is the empty pure section**: `weightedSymTensorOne r F` applied to `1 ∈ Γ(U)`. -/
theorem weightedSymTensorOne_app_one : ∀ (r : ℕ) (F : Fin r → X.Modules)
    (w : ∀ q, Fin ((0 : Fin r → ℕ) q) → Γ(F q, U)),
    (AlgebraicGeometry.Scheme.weightedSymTensorOne r F).app U (AlgebraicGeometry.Scheme.Modules.unitSec U) =
      weightedTensorPure U r F 0 w
  | 0, _, _ => rfl
  | r + 1, F, w =>
    (congrArg (fun k => k.app U (AlgebraicGeometry.Scheme.Modules.unitSec U))
      (AlgebraicGeometry.Scheme.weightedSymTensorOne.eq_2 r F)).trans <|
    (Modules.comp_app_apply_sec U _ _ _).trans <|
    (congrArg _ (Modules.leftUnitor_inv_app U _ _)).trans <|
    (Modules.tensorHom_app_tsec U _ _ _ _).trans <|
    congrArg (weightedTensorUp U r F 0)
      (congrArg₂ _ rfl (weightedSymTensorOne_app_one r (Fin.tail F) (fun q => w q.succ)))

/-- **Multiplication of pure sections** (`mulTerm` on sections): the factorwise multiplication
`weightedSymTensorMul r F a b : T_a ⊗ T_b ⟶ T_{a+b}` sends `pure a wa ⊗ pure b wb` to the pure section of the
concatenated families. -/
theorem weightedSymTensorMul_app_weightedTensorPure : ∀ (r : ℕ) (F : Fin r → X.Modules) (a b : Fin r → ℕ)
    (wa : ∀ q, Fin (a q) → Γ(F q, U)) (wb : ∀ q, Fin (b q) → Γ(F q, U)),
    (AlgebraicGeometry.Scheme.weightedSymTensorMul r F a b).app U
        (AlgebraicGeometry.Scheme.Modules.tsec _ _ U (weightedTensorPure U r F a wa)
          (weightedTensorPure U r F b wb)) =
      weightedTensorPure U r F (a + b) (fun q => Fin.append (wa q) (wb q))
  | 0, _, _, _, _, _ => Modules.leftUnitor_app_tsec_unitSec U (𝟙_ X.Modules) (Modules.unitSec U)
  | r + 1, F, a, b, wa, wb => by
    refine (congrArg (fun k => k.app U (AlgebraicGeometry.Scheme.Modules.tsec _ _ U
        (weightedTensorPure U (r + 1) F a wa) (weightedTensorPure U (r + 1) F b wb)))
      (AlgebraicGeometry.Scheme.weightedSymTensorMul.eq_2 r F a b)).trans ?_
    refine (Modules.comp_app_apply_sec U _ _ _).trans ?_
    rw [weightedTensorPure_succ, weightedTensorPure_succ]
    refine (congrArg _ (Modules.tensorμ_app_tsec U _ _ _ _
      ((AlgebraicGeometry.Scheme.Modules.symGradedAlgebra (F 0)).gradedPure U
        (AlgebraicGeometry.Scheme.Modules.symGen (F 0)) (a 0) (wa 0))
      (weightedTensorPure U r (Fin.tail F) (Fin.tail a) (fun q => wa q.succ))
      ((AlgebraicGeometry.Scheme.Modules.symGradedAlgebra (F 0)).gradedPure U
        (AlgebraicGeometry.Scheme.Modules.symGen (F 0)) (b 0) (wb 0))
      (weightedTensorPure U r (Fin.tail F) (Fin.tail b) (fun q => wb q.succ)))).trans ?_
    refine (Modules.tensorHom_app_tsec U _ _ _ _).trans ?_
    exact congrArg (weightedTensorUp U r F (a + b))
      (congrArg₂ _ (GradedQCAlgebra.mul_app_gradedPure U _ _ (a 0) (b 0) (wa 0) (wb 0))
        (weightedSymTensorMul_app_weightedTensorPure r (Fin.tail F) (Fin.tail a) (Fin.tail b) _ _))

/-- **The generator inclusion on sections** (`weightedSymTensorGen` of `WeightedSymGenerator.lean`): the image of
`x ∈ Γ(U, F j)` is the pure section of multidegree `δ_j` with the single factor `x`. -/
theorem weightedSymTensorGen_app : ∀ (r : ℕ) (F : Fin r → X.Modules) (j : Fin r) (e : Fin r → ℕ)
    (he : ∀ q, e q = if q = j then 1 else 0) (x : Γ(F j, U)) (w : ∀ q, Fin (e q) → Γ(F q, U))
    (hw : ∀ i, w j i = x),
    (AlgebraicGeometry.Scheme.weightedSymTensorGen r F j e he).app U x = weightedTensorPure U r F e w
  | 0, _, j, _, _, _, _, _ => j.elim0
  | r + 1, F, ⟨0, h0⟩, e, he, x, w, hw => by
    have he0 : e 0 = 1 := by
      rw [he 0, if_pos]
      exact Fin.ext rfl
    refine (congrArg (fun k => k.app U x)
      (AlgebraicGeometry.Scheme.weightedSymTensorGen.eq_2 r F h0 e he)).trans ?_
    refine (Modules.comp_app_apply_sec U _ _ _).trans ?_
    refine (Modules.comp_app_apply_sec U _ _ _).trans ?_
    refine (congrArg _ (congrArg _ (Modules.eqToHom_app_self U _ x))).trans ?_
    refine (congrArg _ (Modules.rightUnitor_inv_app U _ x)).trans ?_
    refine (Modules.tensorHom_app_tsec U _ _ _ _).trans ?_
    refine congrArg (weightedTensorUp U r F e) (congrArg₂ _ ?_ ?_)
    · exact (Modules.comp_app_apply_sec U _ _ _).trans
        (GradedQCAlgebra.eqToHom_app_eq_gradedPure_one U _ _ he0 x (w 0) hw)
    · have hetail : (0 : Fin r → ℕ) = Fin.tail e := by
        funext q
        show 0 = e q.succ
        rw [he q.succ, if_neg]
        intro h
        exact absurd (congrArg Fin.val h) (by simp)
      refine (Modules.comp_app_apply_sec U _ _ _).trans ?_
      refine (congrArg _ (weightedSymTensorOne_app_one U r (Fin.tail F) (fun _ => Fin.elim0))).trans ?_
      exact weightedTensorCast_weightedTensorPure U r (Fin.tail F) hetail (fun _ => Fin.elim0)
        (fun q => w q.succ) (fun q i => (show Fin 0 from i).elim0)
  | r + 1, F, ⟨j + 1, hj⟩, e, he, x, w, hw => by
    have he0 : e 0 = 0 := by
      rw [he 0, if_neg]
      intro h
      exact absurd (congrArg Fin.val h) (by simp)
    refine (congrArg (fun k => k.app U x)
      (AlgebraicGeometry.Scheme.weightedSymTensorGen.eq_3 r F j hj e he)).trans ?_
    refine (Modules.comp_app_apply_sec U _ _ _).trans ?_
    refine (congrArg _ (Modules.leftUnitor_inv_app U _ x)).trans ?_
    refine (Modules.tensorHom_app_tsec U _ _ _ _).trans ?_
    refine congrArg (weightedTensorUp U r F e) (congrArg₂ _ ?_ ?_)
    · exact (Modules.comp_app_apply_sec U _ _ _).trans
        (GradedQCAlgebra.eqToHom_app_eq_gradedPure_zero U _ _ he0 (w 0))
    · exact weightedSymTensorGen_app r (Fin.tail F) ⟨j, by omega⟩ (Fin.tail e) _ x (fun q => w q.succ) hw


end AlgebraicGeometry.Scheme

end
