import MiyaokaMori.Paper.S2WeightedJets.Charts.JetLocalGradedRingEquiv
import MiyaokaMori.Paper.S2WeightedJets.Jets.JetGradedAlgebraSectionsBridge

/-! # The local weighted chart of the jet graded algebra

**Statement.** On an affine open `U ⊆ C` on which the cone tangent bundle `E = s^*T_{Z/C}` is
trivial (of rank `n+1`), and provided `s` lands in an open `Zx ⊆ Z` that is smooth of relative
dimension `n+1` over `C`, the sections ring of the jet graded algebra
`(jetGradedAlgebra Z s hs r).1` over `U` is isomorphic to the weighted polynomial ring
`Γ(C, U)[x_{i,q}]` (`i < n+1`, `q < r`, weight of `x_{i,q}` = `q+1`), the isomorphism identifying the
`m`-th grading piece with the weighted-homogeneous polynomials of weight `m` and the structure map
with the constant polynomials `MvPolynomial.C`.

**Source.** §2.2 of the paper: choose an affine open `U` on which `E` is trivial; relative
étale coordinates give `J_k^s|_U ≃ 𝔸_U^{(n+1)k}` (eq. (2.5)); the coefficients
`x_{α,i,q}` have order and weight `q`; `𝒮_k = ⊕ (𝒮_k)_m` with `(𝒮_k)_m` the weight-`m` homogeneous
functions; `𝒵^×` is smooth over `C` of relative dimension `n+1`
(eq. (2.1)). See also Demailly, *Holomorphic Morse inequalities and the
Green–Griffiths–Lang conjecture* (0.3).

**The smoothness hypothesis is necessary.** Without it the statement is false: take
`Z = C ×_k Spec k[x,y]/(y² − x³)` (affine over `C`) with `s` the
zero section `x = y = 0` (a closed immersion) and `r = 2`. The relative tangent sheaf
`T_{Z/C} = (Ω_{Z/C})^∨` pulled back along `s` is `𝒪_C ⊗_A Der_k(A)` with `A = k[x,y]/(y² − x³)`, and
`Der_k(A) ≅ k[t]` (`x = t², y = t³`; generated by `2x∂_x + 3y∂_y` and `2y∂_x + 3x²∂_y`) needs two
generators at the cusp, so `E = s^*T_{Z/C} ≅ 𝒪_C²` is free of rank `2 = n+1` with `n = 1` and `htriv`
holds on every affine `U`. But the based `2`-jets `t ↦ (a₁t + a₂t², b₁t + b₂t²)` must satisfy
`y² − x³ ≡ b₁²t² ≡ 0 (mod t³)`, so `J_2^s|_U = Spec Γ(C,U)[a₁,a₂,b₁,b₂]/(b₁²)`, whose function ring has
the nonzero nilpotent `b₁` (of weight 1, hence visible in `Γ(U, ker φ_1)` with `b₁·b₁ = 0` there), while
`MvPolynomial _ Γ(C,U)` is reduced. The paper avoids this because based jets land in the smooth locus
`𝒵^×`, exactly the hypotheses `(Zx) (hsZx) [SmoothOfRelativeDimension (n+1) (Zx.ι ≫ Z.hom)]`
that `jet_local_coordinates` and `jetLocalGradedRingEquiv` carry.

**Route.**
1. `jetGradedAlgebra_sections_equiv_jetGradedAffineAlgebra`:
   the sections ring `⨁_m Γ(U, ker φ_m)` is isomorphic to the sections ring
   `J_r(B_U, ε_U) = (jetGradedAffineAlgebra Z s hs r)(U)`, matching gradings and structure maps.
2. `jetLocalGradedRingEquiv`: the latter sections ring
   over `U` is the weighted polynomial ring over `Γ(U.toScheme, ⊤)`, gradings and units matching.
3. Transport the coefficient ring along `U.topIso : Γ(U.toScheme, ⊤) ≅ Γ(C, U)` with
   `MvPolynomial.mapEquiv`; `IsWeightedHomogeneous` is preserved by `MvPolynomial.map` along an
   injective ring homomorphism (`MvPolynomial.coeff_map`), and `map (C a) = C (f a)` (`MvPolynomial.map_C`).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- `MvPolynomial.map` along an injective ring homomorphism preserves and reflects weighted
homogeneity (coefficientwise: `MvPolynomial.coeff_map`). -/
private theorem isWeightedHomogeneous_map_iff_aux {σ R S M : Type*} [CommSemiring R] [CommSemiring S]
    [AddCommMonoid M] (f : R →+* S) (hf : Function.Injective f) (w : σ → M)
    (p : MvPolynomial σ R) (m : M) :
    (MvPolynomial.map f p).IsWeightedHomogeneous w m ↔ p.IsWeightedHomogeneous w m := by
  unfold MvPolynomial.IsWeightedHomogeneous
  constructor
  · intro h d hd
    refine h ?_
    rw [MvPolynomial.coeff_map]
    exact fun h0 => hd (hf (h0.trans (map_zero f).symm))
  · intro h d hd
    refine h ?_
    intro h0
    apply hd
    rw [MvPolynomial.coeff_map, h0, map_zero]

/-- **Local weighted chart of the jet graded algebra** (with the smoothness
hypotheses of the paper). See the module docstring for the source, the counterexample to the
unhypothesised version, and the route. Assembled from
`jetGradedAlgebra_sections_equiv_jetGradedAffineAlgebra` and `jetLocalGradedRingEquiv`. -/
theorem jetGradedAlgebra_localWeightedChart_of_smooth
    {k : Type u} [Field k] {C : SmoothProjectiveCurve k}
    (Z : CategoryTheory.Over C.toScheme) [AlgebraicGeometry.IsAffineHom Z.hom]
    (s : C.toScheme ⟶ Z.left)
    (hs : s ≫ Z.hom = CategoryTheory.CategoryStruct.id C.toScheme)
    [AlgebraicGeometry.IsClosedImmersion s]
    (Zx : Z.left.Opens) (hsZx : ∀ c, s.base c ∈ Zx) (n : ℕ)
    [AlgebraicGeometry.SmoothOfRelativeDimension (n + 1) (Zx.ι ≫ Z.hom)]
    (r : ℕ) (U : C.toScheme.affineOpens)
    (htriv : Nonempty ((AlgebraicGeometry.Scheme.Modules.pullback U.1.ι).obj
      (coneTangentBundle Z.hom s hs) ≅
        SheafOfModules.free (R := U.1.toScheme.ringCatSheaf)
          (ULift.{u} (Fin (n + 1))))) :
    ∃ e : ((jetGradedAlgebra (k := k) Z s hs r).1).toGradedAffineAlgebra.toAffineAlgebra.sections
          (AlgebraicGeometry.Scheme.affineSite U) ≃+*
        MvPolynomial (ULift.{u} (Fin (n + 1) × Fin r)) Γ(C.toScheme, U.1),
      (∀ (m : ℕ)
          (a : ((jetGradedAlgebra (k := k) Z s hs r).1).toGradedAffineAlgebra.toAffineAlgebra.sections
            (AlgebraicGeometry.Scheme.affineSite U)),
        a ∈ ((jetGradedAlgebra (k := k) Z s hs r).1).toGradedAffineAlgebra.grading
              (AlgebraicGeometry.Scheme.affineSite U) m ↔
          (e a).IsWeightedHomogeneous
            (fun iq : ULift.{u} (Fin (n + 1) × Fin r) ↦ (iq.down.2 : ℕ) + 1) m) ∧
      (∀ a : Γ(C.toScheme, U.1),
        e (((jetGradedAlgebra (k := k) Z s hs r).1).toGradedAffineAlgebra.toAffineAlgebra.unitHom
          (AlgebraicGeometry.Scheme.affineSite U) a) = MvPolynomial.C a) := by
  obtain ⟨e₁, he₁g, he₁u⟩ :=
    jetGradedAlgebra_sections_equiv_jetGradedAffineAlgebra (k := k) Z s hs r
      (AlgebraicGeometry.Scheme.affineSite U)
  obtain ⟨e₂, he₂g, he₂u⟩ := jetLocalGradedRingEquiv Z s hs Zx hsZx n r U htriv
  let ρ : Γ(U.1.toScheme, ⊤) ≃+* Γ(C.toScheme, U.1) := U.1.topIso.commRingCatIsoToRingEquiv
  let e₃ : MvPolynomial (ULift.{u} (Fin (n + 1) × Fin r)) Γ(U.1.toScheme, ⊤) ≃+*
      MvPolynomial (ULift.{u} (Fin (n + 1) × Fin r)) Γ(C.toScheme, U.1) :=
    MvPolynomial.mapEquiv (ULift.{u} (Fin (n + 1) × Fin r)) ρ
  refine ⟨(e₁.trans e₂).trans e₃, ?_, ?_⟩
  · intro m a
    rw [he₁g m a, he₂g m (e₁ a)]
    exact (isWeightedHomogeneous_map_iff_aux (ρ : Γ(U.1.toScheme, ⊤) →+* Γ(C.toScheme, U.1))
      ρ.injective _ (e₂ (e₁ a)) m).symm
  · intro a
    have hρ : U.1.topIso.hom.hom (U.1.topIso.inv.hom a) = a := by
      rw [← CommRingCat.comp_apply, Iso.inv_hom_id]
      rfl
    have h := he₂u (U.1.topIso.inv.hom a)
    rw [hρ] at h
    show e₃ (e₂ (e₁ _)) = _
    rw [he₁u a, h]
    show MvPolynomial.map (ρ : Γ(U.1.toScheme, ⊤) →+* Γ(C.toScheme, U.1))
      (MvPolynomial.C (U.1.topIso.inv.hom a)) = _
    rw [MvPolynomial.map_C]
    exact congrArg MvPolynomial.C hρ

end
