import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.FinitePresentationLocalData
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.QcSectionsBasicOpenLocalization
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.Stacks01pbAffineOpen
import MiyaokaMori.AlgebraicGeometry.Modules.Coherent.CoherentSheaf

/-! # Coherent modules on a locally Noetherian scheme are locally finitely presented

**Stacks 01XZ (part), in the concrete form `IsLocalPresentation`.** Let `X` be locally Noetherian and
`G` coherent (quasi-coherent of finite type). Then every point `x` has an affine open neighbourhood `U`
with a local presentation `(s, r)` of `G|_U` in the sense of `FinitePresentationLocalData.lean`:
`s : Fin n → G(U)` generate locally, `∑ᵢ r^j_i s_i = 0`, and the relations generate the relation sheaf
locally.

**Proof.** Take an affine open `U ∋ x`, `A := Γ(X, U)` (Noetherian, `IsLocallyNoetherian`),
`N := Γ(G, U)`, a finite `A`-module (`finite_sections_of_isFiniteType`, Stacks 01PB). Choose generators
`s_1, …, s_n` of `N` (`Module.Finite.exists_fin`); the kernel of `A^n → N`, `c ↦ ∑ c_i s_i`, is a
submodule of the Noetherian module `A^n`, hence finitely generated by `r^1, …, r^m ∈ A^n`
(`IsNoetherian.noetherian`, `Submodule.fg_iff_exists_fin_generating_family`). The three clauses:
* `relation`: `r^j ∈ ker`.
* `generates`: for `W ≤ U`, `t ∈ G(W)`, `y ∈ W`, choose a basic open `D(h) ∋ y`, `D(h) ≤ W`
  (`IsAffineOpen.exists_basicOpen_le`). By quasi-coherence `h^k t|_{D(h)}` lifts to `u ∈ N`
  (`exists_pow_smul_eq_map_basicOpen`), `u = ∑ a_i s_i`, and `h` is a unit on `D(h)`
  (`isUnit_res_basicOpen`), so `t|_{D(h)} = ∑ (h^{-k} a_i)|_{D(h)} s_i|_{D(h)}`.
* `relations_generate`: for `W ≤ U`, `c ∈ Γ(X, W)^n` with `∑ c_i s_i|_W = 0` and `y ∈ W`, choose
  `D(h) ∋ y`, `D(h) ≤ W`. Since `Γ(X, D(h)) = A_h` (`IsAffineOpen.isLocalization_basicOpen`), clear
  denominators: `h^k c_i|_{D(h)} = a_i|_{D(h)}` with `a_i ∈ A` (`IsLocalization.exist_integer_multiples`).
  Then `(∑ a_i s_i)|_{D(h)} = 0`, so `h^l ∑ a_i s_i = 0` in `N`
  (`exists_pow_smul_eq_zero_of_map_basicOpen_eq_zero`), i.e. `(h^l a_i)_i ∈ ker = span(r^j)`,
  `h^l a_i = ∑_j e_j r^j_i`, and `c_i|_{D(h)} = ∑_j (h^{-(k+l)} e_j)|_{D(h)} r^j_i|_{D(h)}`.

Source: Stacks 01XZ (`modules-lemma-coherent-Noetherian`), Stacks 01PB; proof written out as above. -/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

namespace MiyaokaMori.StalkHomSpread

open AlgebraicGeometry AlgebraicGeometry.Scheme.Modules

variable {X : AlgebraicGeometry.Scheme.{u}} (G : X.Modules) {U : X.Opens}

theorem presheaf_map_map_le {W V : X.Opens} (h₁ : W ≤ V) (h₂ : V ≤ U) (t : Γ(G, U)) :
    G.presheaf.map (homOfLE h₁).op (G.presheaf.map (homOfLE h₂).op t) =
      G.presheaf.map (homOfLE (h₁.trans h₂)).op t := by
  rw [← ConcreteCategory.comp_apply, ← Functor.map_comp]
  rfl

theorem ring_map_map_le {W V : X.Opens} (h₁ : W ≤ V) (h₂ : V ≤ U) (a : Γ(X, U)) :
    X.presheaf.map (homOfLE h₁).op (X.presheaf.map (homOfLE h₂).op a) =
      X.presheaf.map (homOfLE (h₁.trans h₂)).op a := by
  rw [← ConcreteCategory.comp_apply, ← Functor.map_comp]
  rfl

variable [G.IsQuasicoherent] (hU : AlgebraicGeometry.IsAffineOpen U)

include hU

/-- Global generators of `Γ(G, U)` (`U` affine, `G` quasi-coherent) generate `G|_U` locally. -/
theorem isLocalGenerators_of_span_eq_top {n : ℕ} (s : Fin n → Γ(G, U))
    (hs : Submodule.span Γ(X, U) (Set.range s) = ⊤) :
    AlgebraicGeometry.Scheme.Modules.IsLocalGenerators G U s := by
  intro W hW t y hyW
  obtain ⟨h, hhW, hyh⟩ := hU.exists_basicOpen_le (⟨y, hyW⟩ : W) (hW hyW)
  refine ⟨X.basicOpen h, hhW, hyh, ?_⟩
  set t' := G.presheaf.map (homOfLE hhW).op t with ht'
  obtain ⟨k, u, hu⟩ := AlgebraicGeometry.Scheme.Modules.exists_pow_smul_eq_map_basicOpen G hU h t'
  have hu' : u ∈ Submodule.span Γ(X, U) (Set.range s) := hs ▸ Submodule.mem_top
  obtain ⟨a, ha⟩ := (Submodule.mem_span_range_iff_exists_fun Γ(X, U)).mp hu'
  set hres := X.presheaf.map (homOfLE (X.basicOpen_le h)).op h with hhres
  have hunit : IsUnit hres := X.toRingedSpace.isUnit_res_basicOpen h
  set hinv : Γ(X, X.basicOpen h) := ↑hunit.unit⁻¹ with hhinv
  have hinvres1 : hinv * hres = 1 := hunit.val_inv_mul
  refine ⟨fun i => hinv ^ k * X.presheaf.map (homOfLE (X.basicOpen_le h)).op (a i), ?_⟩
  have key : hres ^ k • t' = ∑ i, X.presheaf.map (homOfLE (X.basicOpen_le h)).op (a i) •
      G.presheaf.map (homOfLE (X.basicOpen_le h)).op (s i) := by
    rw [← hu, ← ha, map_sum]
    simp only [AlgebraicGeometry.Scheme.Modules.map_smul]
  have hinvres : hinv ^ k * hres ^ k = 1 := by
    rw [← mul_pow, hinvres1, one_pow]
  calc t' = (hinv ^ k * hres ^ k) • t' := by rw [hinvres, one_smul]
    _ = hinv ^ k • (hres ^ k • t') := by rw [mul_smul]
    _ = _ := by
      rw [key, Finset.smul_sum]
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [smul_smul]

/-- Relations among global generators of `Γ(G, U)` that generate the kernel of `A^n → Γ(G, U)`
generate the relations of `G|_U` locally. -/
theorem relations_generate_of_span_eq_ker {n m : ℕ} (s : Fin n → Γ(G, U))
    (r : Fin m → Fin n → Γ(X, U))
    (hr : Submodule.span Γ(X, U) (Set.range r) =
      LinearMap.ker (Fintype.linearCombination Γ(X, U) s)) :
    ∀ (W : X.Opens) (hW : W ≤ U) (c : Fin n → Γ(X, W)),
      ∑ i, c i • G.presheaf.map (homOfLE hW).op (s i) = 0 → ∀ y ∈ W,
      ∃ (W' : X.Opens) (hW' : W' ≤ W), y ∈ W' ∧ ∃ d : Fin m → Γ(X, W'),
        ∀ i, X.presheaf.map (homOfLE hW').op (c i) =
          ∑ j, d j • X.presheaf.map (homOfLE (hW'.trans hW)).op (r j i) := by
  intro W hW c hc y hyW
  obtain ⟨h, hhW, hyh⟩ := hU.exists_basicOpen_le (⟨y, hyW⟩ : W) (hW hyW)
  refine ⟨X.basicOpen h, hhW, hyh, ?_⟩
  have := hU.isLocalization_basicOpen h
  set res := X.presheaf.map (homOfLE (X.basicOpen_le h)).op with hres_def
  have halg : ∀ z : Γ(X, U), algebraMap Γ(X, U) Γ(X, X.basicOpen h) z = res z := fun z => rfl
  obtain ⟨b, hb⟩ := IsLocalization.exist_integer_multiples (Submonoid.powers h) Finset.univ
    (fun i => X.presheaf.map (homOfLE hhW).op (c i))
  obtain ⟨k, hk⟩ := b.2
  choose a ha using fun i => RingHom.mem_rangeS.mp (hb i (Finset.mem_univ i))
  -- `ha i : algebraMap (a i) = (b : A) • c i|`
  have ha' : ∀ i, res (a i) = res h ^ k * X.presheaf.map (homOfLE hhW).op (c i) := by
    intro i
    rw [← halg, ha i, Algebra.smul_def, halg, ← hk, map_pow]
  -- `(∑ a_i s_i)|_{D(h)} = 0`
  have hzero : G.presheaf.map (homOfLE (X.basicOpen_le h)).op (∑ i, a i • s i) = 0 := by
    rw [map_sum]
    simp only [AlgebraicGeometry.Scheme.Modules.map_smul]
    have hc' := congrArg (G.presheaf.map (homOfLE hhW).op) hc
    rw [map_sum, map_zero] at hc'
    simp only [AlgebraicGeometry.Scheme.Modules.map_smul, presheaf_map_map_le] at hc'
    calc ∑ i, res (a i) • G.presheaf.map (homOfLE (X.basicOpen_le h)).op (s i)
        = res h ^ k • ∑ i, X.presheaf.map (homOfLE hhW).op (c i) •
            G.presheaf.map (homOfLE (hhW.trans hW)).op (s i) := by
          rw [Finset.smul_sum]
          refine Finset.sum_congr rfl fun i _ => ?_
          rw [ha' i, mul_smul]
      _ = 0 := by rw [hc', smul_zero]
  obtain ⟨l, hl⟩ :=
    AlgebraicGeometry.Scheme.Modules.exists_pow_smul_eq_zero_of_map_basicOpen_eq_zero G hU h _ hzero
  -- `(h^l a_i)_i ∈ ker = span (range r)`
  have hmem : (fun i => h ^ l * a i) ∈ Submodule.span Γ(X, U) (Set.range r) := by
    rw [hr, LinearMap.mem_ker, Fintype.linearCombination_apply]
    simp only [mul_smul]
    rw [← Finset.smul_sum]
    exact hl
  obtain ⟨e, he⟩ := (Submodule.mem_span_range_iff_exists_fun Γ(X, U)).mp hmem
  have he' : ∀ i, ∑ j, e j * r j i = h ^ l * a i := by
    intro i
    have := congrFun he i
    simpa [Finset.sum_apply, Pi.smul_apply, smul_eq_mul] using this
  have hunit : IsUnit (res h) := X.toRingedSpace.isUnit_res_basicOpen h
  set hinv : Γ(X, X.basicOpen h) := ↑hunit.unit⁻¹ with hhinv
  have hinvres1 : hinv * res h = 1 := hunit.val_inv_mul
  refine ⟨fun j => hinv ^ (k + l) * res (e j), fun i => ?_⟩
  have hinvres : hinv ^ (k + l) * res h ^ (k + l) = 1 := by
    rw [← mul_pow, hinvres1, one_pow]
  have step : res h ^ (k + l) * X.presheaf.map (homOfLE hhW).op (c i) =
      ∑ j, res (e j) * res (r j i) := by
    rw [pow_add, mul_comm (res h ^ k), mul_assoc, ← ha' i, ← map_pow, ← map_mul, ← he' i, map_sum]
    simp only [map_mul]
  calc X.presheaf.map (homOfLE hhW).op (c i)
      = (hinv ^ (k + l) * res h ^ (k + l)) * X.presheaf.map (homOfLE hhW).op (c i) := by
        rw [hinvres, one_mul]
    _ = hinv ^ (k + l) * ∑ j, res (e j) * res (r j i) := by rw [mul_assoc, step]
    _ = ∑ j, (hinv ^ (k + l) * res (e j)) • X.presheaf.map (homOfLE (hhW.trans hW)).op (r j i) := by
        rw [Finset.mul_sum]
        refine Finset.sum_congr rfl fun j _ => ?_
        rw [smul_eq_mul, mul_assoc]

omit hU in
/-- **Coherent modules on a locally Noetherian scheme are locally finitely presented** (Stacks 01XZ),
in the concrete form `IsLocalPresentation` of `FinitePresentationLocalData.lean`: every point has an
affine open neighbourhood `U` with a local presentation `(s, r)` of `G|_U`. -/
theorem exists_isLocalPresentation_of_isCoherent [AlgebraicGeometry.IsLocallyNoetherian X]
    (G : X.Modules) [hG : G.IsCoherent] (x : X) :
    ∃ (U : X.Opens) (_ : x ∈ U) (n m : ℕ) (s : Fin n → Γ(G, U)) (r : Fin m → Fin n → Γ(X, U)),
      AlgebraicGeometry.Scheme.Modules.IsLocalPresentation G U s r := by
  have := hG.quasicoherent
  have := hG.finiteType
  obtain ⟨⟨U, hU⟩, hxU⟩ : ∃ U : X.affineOpens, x ∈ (U : X.Opens) := by
    have : x ∈ (⊤ : X.Opens) := trivial
    rw [← AlgebraicGeometry.iSup_affineOpens_eq_top X] at this
    exact Opens.mem_iSup.mp this
  have hnoeth : IsNoetherianRing Γ(X, U) := IsLocallyNoetherian.component_noetherian ⟨U, hU⟩
  have hfin : Module.Finite Γ(X, U) Γ(G, U) :=
    AlgebraicGeometry.Scheme.Modules.finite_sections_of_isFiniteType G hU
  obtain ⟨n, s, hs⟩ := Module.Finite.exists_fin (R := Γ(X, U)) (M := Γ(G, U))
  have hker : (LinearMap.ker (Fintype.linearCombination Γ(X, U) s)).FG :=
    IsNoetherian.noetherian _
  obtain ⟨m, r, hr⟩ := Submodule.fg_iff_exists_fin_generating_family.mp hker
  refine ⟨U, hxU, n, m, s, r, ⟨isLocalGenerators_of_span_eq_top G hU s hs, fun j => ?_,
    relations_generate_of_span_eq_ker G hU s r hr⟩⟩
  have hj : r j ∈ LinearMap.ker (Fintype.linearCombination Γ(X, U) s) :=
    hr ▸ Submodule.subset_span ⟨j, rfl⟩
  rw [LinearMap.mem_ker, Fintype.linearCombination_apply] at hj
  exact hj

end MiyaokaMori.StalkHomSpread

end
