import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.Stalk.ModulesSupport
import MiyaokaMori.AlgebraicGeometry.Modules.Coherent.CoherentSheaf
import MiyaokaMori.AlgebraicGeometry.Modules.Coherent.CoherentFreeStalksLocallyFree
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.Stacks01pbAffineOpen

/-! # Generic points of the support of a coherent module

Generic points of the support of a coherent module, for Stacks 02OL.

`genericPoints F := {y ∈ Supp F | ∀ z ∈ Supp F, z ⤳ y → z = y}` (the minimal points of `Supp F` for
specialization = generic points of the irreducible components of the closed set `Supp F`).

* `germ_eq_zero_iff` / `exists_smul_germ_eq_germ` / `subsingleton_stalk_iff`: on an affine open `U`,
  the stalk of a quasi-coherent `F` at `z ∈ U` is the localization of `Γ(U, F)` at the prime of `z`
  (`isLocalizedModule_germ`, Stacks 01I8), spelled with basic opens: the germ of `m` at `z` is zero iff
  `u • m = 0` for some `u` with `z ∈ D(u)`, every stalk element is `germ m / unit`, and the stalk is
  zero iff all germs of sections over `U` vanish.
* `isClosed_support_of_isCoherent` (Stacks 01B4): `Supp F` is closed. Proof: if `F_x = 0`, take an
  affine `U ∋ x`; `Γ(U, F)` is finite (Stacks 01PB), each generator is killed by some `u_i ∉ p_x`,
  `u := ∏ u_i` kills `Γ(U, F)`, and every stalk at `z ∈ D(u)` is generated by germs of `Γ(U, F)` with
  `u` a unit there, so `F_z = 0` on the neighbourhood `D(u)` of `x`.
* `exists_mem_genericPoints_specializes`: every `x ∈ Supp F` is a specialization of a generic point.
  Proof (Stacks 004W/0052 in the closed sober subspace `Supp F`): by Zorn (`exists_preirreducible`)
  `{x}` lies in a maximal irreducible closed subset `T` of `Supp F`; `T` has a generic point `η`
  (closed subsets of quasi-sober spaces are quasi-sober); `η ⤳ x`; and `η` is minimal in `Supp F`
  since `z ⤳ η` forces `closure {z} ⊇ T`, hence `= T` by maximality, hence `z = η` (T0).
* `finite_genericPoints_inter`: on a locally Noetherian scheme, for `U` affine, `genericPoints F ∩ U`
  is finite. Proof: `S := U ∩ Supp F` is a Noetherian space (subspace of the Noetherian `U`), so it has
  finitely many irreducible components (Stacks 0052, `NoetherianSpace.finite_irreducibleComponents`);
  `y ↦ closure {y}` maps `genericPoints F ∩ U` injectively into them (maximality as above, injectivity
  by T0).

Source: Stacks 01B4, 004W, 0052, 01I8; used for Stacks 02OL.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000
set_option linter.style.haveILetI false

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace Topology
open scoped AlgebraicGeometry

noncomputable section

namespace AlgebraicGeometry.Scheme.Modules

variable {X : AlgebraicGeometry.Scheme.{u}}

/-- The generic points of the support: the points of `Supp F` that are minimal for specialization. -/
def genericPoints (F : X.Modules) : Set X :=
  {y | y ∈ F.support ∧ ∀ z ∈ F.support, z ⤳ y → z = y}

theorem genericPoints_subset_support (F : X.Modules) : F.genericPoints ⊆ F.support :=
  fun _ h => h.1

theorem eq_of_specializes_of_mem_genericPoints {F : X.Modules} {y z : X} (hy : y ∈ F.genericPoints)
    (hz : z ∈ F.support) (h : z ⤳ y) : z = y :=
  hy.2 z hz h

section Localization

/-- The germ of a section over an affine open is zero iff the section is killed by a function
`u` with `z ∈ D(u)` (the stalk is the localization of the sections at the prime of `z`). -/
theorem germ_eq_zero_iff (F : X.Modules) [F.IsQuasicoherent] {U : X.Opens}
    (hU : AlgebraicGeometry.IsAffineOpen U) {z : X} (hz : z ∈ U) (m : Γ(F, U)) :
    F.presheaf.germ U z hz m = 0 ↔ ∃ u : Γ(X, U), z ∈ X.basicOpen u ∧ u • m = 0 := by
  set p := hU.primeIdealOf ⟨z, hz⟩ with hp
  letI := X.presheaf.algebra_section_stalk ⟨z, hz⟩
  have hloc : IsLocalization.AtPrime (X.presheaf.stalk z) p.asIdeal :=
    hU.isLocalization_stalk ⟨z, hz⟩
  letI modA : Module Γ(X, U) (F.presheaf.stalk z) :=
    Module.compHom (F.presheaf.stalk z) (X.presheaf.germ U z hz).hom
  let g : Γ(F, U) →ₗ[Γ(X, U)] F.presheaf.stalk z :=
    { toFun := F.presheaf.germ U z hz
      map_add' := map_add _
      map_smul' := fun r m => CoherentFreeStalksAux.germ_smul' F hz r m }
  have hg : IsLocalizedModule p.asIdeal.primeCompl g :=
    CoherentFreeStalksAux.isLocalizedModule_germ F hU hz (fun _ _ => rfl) g (fun _ => rfl)
  have hmem : ∀ u : Γ(X, U), z ∈ X.basicOpen u ↔ u ∈ p.asIdeal.primeCompl := fun u =>
    (X.mem_basicOpen u z hz).trans
      (IsLocalization.AtPrime.isUnit_to_map_iff (X.presheaf.stalk z) p.asIdeal u)
  change g m = 0 ↔ _
  rw [IsLocalizedModule.eq_zero_iff p.asIdeal.primeCompl g]
  constructor
  · rintro ⟨⟨u, hu⟩, hum⟩
    exact ⟨u, (hmem u).mpr hu, hum⟩
  · rintro ⟨u, hzu, hum⟩
    exact ⟨⟨u, (hmem u).mp hzu⟩, hum⟩

/-- Every element of the stalk at `z ∈ U` (`U` affine) becomes the germ of a section over `U`
after multiplying by a unit `germ u`, `z ∈ D(u)`. -/
theorem exists_smul_germ_eq_germ (F : X.Modules) [F.IsQuasicoherent] {U : X.Opens}
    (hU : AlgebraicGeometry.IsAffineOpen U) {z : X} (hz : z ∈ U) (e : F.presheaf.stalk z) :
    ∃ (u : Γ(X, U)) (m : Γ(F, U)), z ∈ X.basicOpen u ∧
      X.presheaf.germ U z hz u • e = F.presheaf.germ U z hz m := by
  set p := hU.primeIdealOf ⟨z, hz⟩ with hp
  letI := X.presheaf.algebra_section_stalk ⟨z, hz⟩
  have hloc : IsLocalization.AtPrime (X.presheaf.stalk z) p.asIdeal :=
    hU.isLocalization_stalk ⟨z, hz⟩
  letI modA : Module Γ(X, U) (F.presheaf.stalk z) :=
    Module.compHom (F.presheaf.stalk z) (X.presheaf.germ U z hz).hom
  let g : Γ(F, U) →ₗ[Γ(X, U)] F.presheaf.stalk z :=
    { toFun := F.presheaf.germ U z hz
      map_add' := map_add _
      map_smul' := fun r m => CoherentFreeStalksAux.germ_smul' F hz r m }
  have hg : IsLocalizedModule p.asIdeal.primeCompl g :=
    CoherentFreeStalksAux.isLocalizedModule_germ F hU hz (fun _ _ => rfl) g (fun _ => rfl)
  have hmem : ∀ u : Γ(X, U), z ∈ X.basicOpen u ↔ u ∈ p.asIdeal.primeCompl := fun u =>
    (X.mem_basicOpen u z hz).trans
      (IsLocalization.AtPrime.isUnit_to_map_iff (X.presheaf.stalk z) p.asIdeal u)
  obtain ⟨⟨m, u⟩, hmu⟩ := IsLocalizedModule.mk'_surjective p.asIdeal.primeCompl g e
  refine ⟨u.1, m, (hmem u.1).mpr u.2, ?_⟩
  have h1 : (u.1 : Γ(X, U)) • e = g m := by
    rw [← hmu]
    exact IsLocalizedModule.mk'_cancel' g m u
  exact h1

/-- On an affine open `U ∋ z`, the stalk of a quasi-coherent module at `z` is zero iff the germs
at `z` of all sections over `U` vanish. -/
theorem subsingleton_stalk_iff (F : X.Modules) [F.IsQuasicoherent] {U : X.Opens}
    (hU : AlgebraicGeometry.IsAffineOpen U) {z : X} (hz : z ∈ U) :
    Subsingleton (F.presheaf.stalk z) ↔ ∀ m : Γ(F, U), F.presheaf.germ U z hz m = 0 := by
  constructor
  · intro h m
    exact Subsingleton.elim _ _
  · intro h
    refine subsingleton_of_forall_eq 0 fun e => ?_
    obtain ⟨u, m, hzu, hue⟩ := exists_smul_germ_eq_germ F hU hz e
    rw [h m] at hue
    have hunit : IsUnit (X.presheaf.germ U z hz u) := (X.mem_basicOpen u z hz).mp hzu
    have := congrArg (fun w => (↑hunit.unit⁻¹ : X.presheaf.stalk z) • w) hue
    simpa [smul_smul] using this

end Localization

/-- **Stacks 01B4**: the support of a coherent module is closed (see the module docstring). -/
theorem isClosed_support_of_isCoherent (F : X.Modules) [F.IsCoherent] : IsClosed F.support := by
  haveI : F.IsQuasicoherent := IsCoherent.quasicoherent
  haveI : F.IsFiniteType := IsCoherent.finiteType
  rw [← isOpen_compl_iff, isOpen_iff_forall_mem_open]
  intro x hx
  obtain ⟨U, hU, hxU, -⟩ := Opens.isBasis_iff_nbhd.mp X.isBasis_affineOpens
    (show x ∈ (⊤ : X.Opens) from trivial)
  have hU : AlgebraicGeometry.IsAffineOpen U := hU
  have hx0 : ∀ m : Γ(F, U), F.presheaf.germ U x hxU m = 0 := by
    rw [← subsingleton_stalk_iff F hU hxU]
    have : ¬ Nontrivial (F.presheaf.stalk x) := hx
    exact not_nontrivial_iff_subsingleton.mp this
  have hfin : Module.Finite Γ(X, U) Γ(F, U) := finite_sections_of_isFiniteType F hU
  obtain ⟨s, hs⟩ := hfin.fg_top
  -- choose, for each generator, a function `u` with `x ∈ D(u)` killing it
  have hchoice : ∀ m : Γ(F, U), ∃ u : Γ(X, U), x ∈ X.basicOpen u ∧ u • m = 0 := fun m =>
    (germ_eq_zero_iff F hU hxU m).mp (hx0 m)
  choose uf huf using hchoice
  classical
  let u : Γ(X, U) := ∏ m ∈ s, uf m
  have hxu : x ∈ X.basicOpen u := by
    have : ∀ m ∈ s, x ∈ X.basicOpen (uf m) := fun m _ => (huf m).1
    rw [X.mem_basicOpen u x hxU]
    have hprod : X.presheaf.germ U x hxU u = ∏ m ∈ s, X.presheaf.germ U x hxU (uf m) := by
      simp [u, map_prod]
    rw [hprod]
    exact IsUnit.prod_iff.mpr fun m hm => (X.mem_basicOpen (uf m) x hxU).mp (this m hm)
  have hkill : ∀ m : Γ(F, U), u • m = 0 := by
    intro m
    have hm : m ∈ Submodule.span Γ(X, U) (s : Set Γ(F, U)) := by rw [hs]; trivial
    refine Submodule.span_induction (p := fun m _ => u • m = 0) ?_ ?_ ?_ ?_ hm
    · intro m hm
      have hu : u = (∏ t ∈ s.erase m, uf t) * uf m := (Finset.prod_erase_mul s uf hm).symm
      rw [hu, mul_smul, (huf m).2, smul_zero]
    · simp
    · intro a b _ _ ha hb
      rw [smul_add, ha, hb, add_zero]
    · intro r a _ ha
      rw [smul_comm, ha, smul_zero]
  refine ⟨X.basicOpen u, ?_, (X.basicOpen u).2, hxu⟩
  intro z hz
  have hzU : z ∈ U := X.basicOpen_le u hz
  show ¬ Nontrivial (F.presheaf.stalk z)
  rw [not_nontrivial_iff_subsingleton, subsingleton_stalk_iff F hU hzU]
  intro m
  rw [germ_eq_zero_iff F hU hzU m]
  exact ⟨u, hz, hkill m⟩

/-- Every point of the support of a coherent module is a specialization of a generic point of the
support (see the module docstring). -/
theorem exists_mem_genericPoints_specializes (F : X.Modules) [F.IsCoherent] {x : X}
    (hx : x ∈ F.support) : ∃ y ∈ F.genericPoints, y ⤳ x := by
  have hcl : IsClosed F.support := isClosed_support_of_isCoherent F
  haveI : QuasiSober F.support := hcl.isClosedEmbedding_subtypeVal.quasiSober
  obtain ⟨T, hT, hxT, hmax⟩ :=
    exists_preirreducible ({⟨x, hx⟩} : Set F.support) isIrreducible_singleton.2
  have hTirr : IsIrreducible T := ⟨⟨⟨x, hx⟩, hxT (Set.mem_singleton _)⟩, hT⟩
  have hTcl : IsClosed T := by
    rw [← closure_eq_iff_isClosed]
    exact hmax _ hT.closure subset_closure
  obtain ⟨η, hη⟩ := QuasiSober.sober hTirr hTcl
  refine ⟨η.1, ⟨η.2, ?_⟩, ?_⟩
  · intro z hz hzη
    have h1 : (⟨z, hz⟩ : F.support) ⤳ η := IsInducing.subtypeVal.specializes_iff.mp hzη
    have h2 : closure {(⟨z, hz⟩ : F.support)} = T := by
      apply hmax _ isIrreducible_singleton.closure.2
      rw [← hη.def]
      exact closure_minimal (Set.singleton_subset_iff.mpr (specializes_iff_mem_closure.mp h1))
        isClosed_closure
    have h3 : IsGenericPoint (⟨z, hz⟩ : F.support) T := h2
    exact congrArg Subtype.val (h3.eq hη)
  · have : η ⤳ ⟨x, hx⟩ := hη.specializes (hxT rfl)
    exact this.map continuous_subtype_val

/-- On a locally Noetherian scheme, a coherent module has only finitely many generic points of
its support in any affine open (see the module docstring). -/
theorem finite_genericPoints_inter (F : X.Modules) [AlgebraicGeometry.IsLocallyNoetherian X]
    [F.IsCoherent] {U : X.Opens} (hU : AlgebraicGeometry.IsAffineOpen U) :
    (F.genericPoints ∩ (U : Set X)).Finite := by
  haveI : IsNoetherianRing Γ(X, U) := IsLocallyNoetherian.component_noetherian ⟨U, hU⟩
  haveI hNU : NoetherianSpace U := noetherianSpace_of_isAffineOpen U hU
  have hcl : IsClosed F.support := isClosed_support_of_isCoherent F
  -- the closed subspace `S := U ∩ Supp F` of `U`
  let S : Set X := (U : Set X) ∩ F.support
  haveI : NoetherianSpace S := by
    rw [noetherianSpace_set_iff]
    intro t ht
    exact (noetherianSpace_set_iff (U : Set X)).mp hNU t (ht.trans Set.inter_subset_left)
  haveI : QuasiSober (U : Set X) := U.isOpenEmbedding'.quasiSober
  haveI : QuasiSober S := QuasiSober.inter_of_isClosed_of_quasiSober_left (U : Set X) hcl
  -- the generic points, as points of `S`
  let G : Set S := {p | p.1 ∈ F.genericPoints}
  have hGimg : F.genericPoints ∩ (U : Set X) = Subtype.val '' G := by
    ext y
    constructor
    · rintro ⟨hy, hyU⟩
      exact ⟨⟨y, hyU, hy.1⟩, hy, rfl⟩
    · rintro ⟨⟨y, hyU, hyS⟩, hy, rfl⟩
      exact ⟨hy, hyU⟩
  rw [hGimg]
  refine Set.Finite.image _ ?_
  -- `p ↦ closure {p}` maps `G` injectively into the irreducible components of `S`
  let φ : S → Set S := fun p => closure {p}
  have hφ : ∀ p ∈ G, φ p ∈ irreducibleComponents S := by
    intro p hp
    refine ⟨isIrreducible_singleton.closure, ?_⟩
    intro T hT hpT
    have hTcl : IsIrreducible (closure T) := hT.closure
    obtain ⟨z, hz⟩ := QuasiSober.sober hTcl isClosed_closure
    have hzp : z ⤳ p := hz.specializes (subset_closure (hpT (subset_closure rfl)))
    have hzp' : z.1 ⤳ p.1 := hzp.map continuous_subtype_val
    have hzeq : z.1 = p.1 := hp.2 z.1 z.2.2 hzp'
    have hzeq' : z = p := Subtype.ext hzeq
    calc T ⊆ closure T := subset_closure
      _ = closure {z} := hz.def.symm
      _ = φ p := by rw [hzeq']
  refine Set.Finite.of_finite_image (f := φ) ?_ ?_
  · exact NoetherianSpace.finite_irreducibleComponents.subset (Set.image_subset_iff.mpr hφ)
  · intro p _ q _ hpq
    have h1 : IsGenericPoint p (closure {q}) := hpq
    exact h1.eq isGenericPoint_closure

end AlgebraicGeometry.Scheme.Modules

end
