import MiyaokaMori.Prelude
import MiyaokaMori.Paper.S2WeightedJets.Cone.PuncturedConeIsPuncturedLineBundleContract
import MiyaokaMori.Paper.S2WeightedJets.Cone.PuncturedConeIsPuncturedLineBundleContractInjectiveEvalIso
import MiyaokaMori.Paper.S2WeightedJets.Cone.PuncturedConeIsPuncturedLineBundleContractInjectiveTensorSections
import MiyaokaMori.AlgebraicGeometry.Proj.ProjectiveSpace.SerreTwistIsLineBundle
import MiyaokaMori.AlgebraicGeometry.Modules.Pullback.SectionPullbackNotZeroAt
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.ModuleSheafFrameIso
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.WeightedProjCoordinateFormula

/-! # A section of `L` is determined by its pairings with the homogeneous coordinates

A section of `L = pr₁^*A ⊗ pr₂^*O_X(−1)` is determined by its pairings with the homogeneous coordinates
`pr₂^*(e^*x_i)`: `⟨w, q_i⟩ = ⟨w', q_i⟩` for all `i` implies `w = w'`. This is the section version of
"`M ⊗ Q^∨ = 𝓗om(Q, M)`, and `Q` is generated by the `q_i`".

Source: eq. (2.1) of the paper; Stacks 01CT (the evaluation `L ⊗ L^∨ → O` of a line
bundle is an isomorphism).

Route:
* The pairing `contract : L ⊗ pr₂^*O_X(1) ⟶ pr₁^*A` is itself an **isomorphism** (`isIso_contract`): it is
  the composite of `tensorIsoTensorObj`, the associator, `id ◁ eval` and the right unitor, where `eval` is
  `pullbackTensorObjIso.inv ≫ pr₂^*(internalHomEval O_X(1) O_X) ≫ pullbackUnitIso.hom` and
  `internalHomEval O_X(1) O_X : 𝓗om(O_X(1), O_X) ⊗ O_X(1) ⟶ O_X` is an isomorphism
  (Stacks 01CT, `Stacks01ct_DualEval.isIso_internalHomEval_dual`). Hence `contractSections T w q`
  is (the component on `⊤` of an isomorphism applied to) `w ⊗ q`, and the hypothesis `⟨w, q_i⟩ = ⟨w', q_i⟩`
  becomes `w ⊗ q_i = w' ⊗ q_i` (`sectionTensor`).
* The homogeneous coordinates `q_i = T.hom^*pr₂^*e^*x_i` have no common zero (`exists_not_isZeroAt_coordinate`):
  `x_i` is a frame of `O_{P^N}(1)` on `D₊(x_i)` (`isFrame_homogeneousSection`), the germ of a frame does not lie
  in `𝔪·O(1)_p` (`IsFrame.germ_notMem_maximalIdeal_smul`), the `D₊(x_i)` cover `P^N`
  (`projectiveSpace_iSup_basicOpen_X`), and the three pullbacks along `e.emb`, `pr₂`, `T.hom` preserve
  "nonzero at a point" (`not_isZeroAt_sectionPullbackAlong`).
* The general lemma `eq_of_sectionTensor_eq_of_forall_exists_not_isZeroAt` (auxiliary module
  `…ContractInjectiveTensorSections`): for line bundles `L, N` and `q_i ∈ Γ(N)` without common zero,
  `w ⊗ q_i = w' ⊗ q_i` for all `i` implies `w = w'` (computed on stalks with frames, Stacks 01CB + 01CY).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

attribute [local instance] MvPolynomial.gradedAlgebra

noncomputable section

/-- The homogeneous coordinates `x_0, …, x_N ∈ Γ(P^N, O(1))` have no common zero: `p ∈ D₊(x_i)` for some `i`
(the `D₊(x_i)` cover `P^N`), and `x_i` is a frame of `O(1)` on `D₊(x_i)` (`isFrame_homogeneousSection`), whose
germ does not lie in `𝔪_p · O(1)_p` (`IsFrame.germ_notMem_maximalIdeal_smul`). The section over `D₊(x_i)` is
the restriction of the global one (`rfl`). -/
theorem exists_not_isZeroAt_projectiveSpaceCoordinate (k : Type u) [Field k] (N : ℕ)
    (p : ProjectiveSpace N k) :
    ∃ i : Fin (N + 1), ¬ IsZeroAt (projectiveSpaceCoordinate k N i) p := by
  have hp : p ∈ ⨆ i : Fin (N + 1),
      AlgebraicGeometry.Proj.basicOpen (AlgebraicGeometry.Proj.projectiveGrading k N) (MvPolynomial.X i) := by
    rw [projectiveSpace_iSup_basicOpen_X k N]; trivial
  obtain ⟨i, hi⟩ := Opens.mem_iSup.mp hp
  refine ⟨i, fun hz => ?_⟩
  have hfr : AlgebraicGeometry.Scheme.Modules.IsFrame (projectiveSpaceTwist k N 1)
      (AlgebraicGeometry.Proj.basicOpen (AlgebraicGeometry.Proj.projectiveGrading k N) (MvPolynomial.X i))
      ((projectiveSpaceTwist k N 1).presheaf.map (homOfLE le_top).op (projectiveSpaceCoordinate k N i)) :=
    MiyaokaMori.WeightedJets.ProjTwisting.isFrame_homogeneousSection (AlgebraicGeometry.Proj.projectiveGrading k N) 1
      (MvPolynomial.X i) (MvPolynomial.isHomogeneous_X k i) _ (fun x => x.2)
  apply hfr.germ_notMem_maximalIdeal_smul hi
  have hz' : (projectiveSpaceTwist k N 1).presheaf.germ ⊤ p trivial
      (projectiveSpaceCoordinate k N i) ∈
        (IsLocalRing.maximalIdeal ((ProjectiveSpace N k).presheaf.stalk p)) •
          (⊤ : Submodule ((ProjectiveSpace N k).presheaf.stalk p)
            ((projectiveSpaceTwist k N 1).stalk p)) := hz
  have hres : (projectiveSpaceTwist k N 1).presheaf.germ _ p hi
      ((projectiveSpaceTwist k N 1).presheaf.map (homOfLE le_top).op (projectiveSpaceCoordinate k N i)) =
        (projectiveSpaceTwist k N 1).presheaf.germ ⊤ p trivial
          (projectiveSpaceCoordinate k N i) := by
    have h1 := TopCat.Presheaf.germ_res_apply (projectiveSpaceTwist k N 1).presheaf (homOfLE le_top) p hi
      (projectiveSpaceCoordinate k N i)
    exact h1
  rw [hres]
  exact hz'

/-- The homogeneous coordinates `q_i = T.hom^*pr₂^*(e^*x_i) ∈ Γ(T, T.hom^*pr₂^*O_X(1))` have no common zero:
the `x_i` have no common zero (`exists_not_isZeroAt_projectiveSpaceCoordinate`), and pulling back along
`e.emb`, `pr₂`, `T.hom` preserves "nonzero at a point" (`not_isZeroAt_sectionPullbackAlong`). -/
theorem conePuncturedLineBundle.exists_not_isZeroAt_coordinate {k : Type u} [Field k]
    {C X : AlgebraicGeometry.Scheme.{u}} [C.Over (AlgebraicGeometry.Spec (CommRingCat.of k))]
    [X.Over (AlgebraicGeometry.Spec (CommRingCat.of k))] {N : ℕ}
    (e : ProjectiveEmbedding k X N)
    (T : CategoryTheory.Over (CategoryTheory.Limits.pullback (C ↘ AlgebraicGeometry.Spec (CommRingCat.of k))
      (X ↘ AlgebraicGeometry.Spec (CommRingCat.of k))))
    (t : T.left) :
    ∃ i : Fin (N + 1),
      ¬ IsZeroAt (sectionPullbackAlong T.hom (conePuncturedLineBundle.coordinate C e i)) t := by
  have h1 : (projectiveSpaceTwist k N 1).IsLineBundle := projectiveSpaceTwist_isLineBundle k N 1
  have h2 := ProjectiveEmbedding.oX_one_isLineBundle e
  obtain ⟨i, hi⟩ := exists_not_isZeroAt_projectiveSpaceCoordinate k N
    (e.emb.base ((CategoryTheory.Limits.pullback.snd (C ↘ AlgebraicGeometry.Spec (CommRingCat.of k))
      (X ↘ AlgebraicGeometry.Spec (CommRingCat.of k))).base (T.hom.base t)))
  refine ⟨i, ?_⟩
  apply not_isZeroAt_sectionPullbackAlong T.hom _ _ t
  apply not_isZeroAt_sectionPullbackAlong
    (CategoryTheory.Limits.pullback.snd (C ↘ AlgebraicGeometry.Spec (CommRingCat.of k))
      (X ↘ AlgebraicGeometry.Spec (CommRingCat.of k)))
    (e.oX 1)
  -- The inner term of `coordinate C e i` is `sectionPullbackAlong e.emb (projectiveSpaceCoordinate k N i)`.
  exact @not_isZeroAt_sectionPullbackAlong _ _ e.emb (projectiveSpaceTwist k N 1) h1 _ _ hi

/-- Injectivity of the pairing: for `T` over `C ×_k X` and `w, w' ∈ Γ(T, T.hom^*L)`, if
`⟨w, T.hom^*pr₂^*(e^*x_i)⟩ = ⟨w', …⟩` for every `i`, then `w = w'`.

Source: Stacks 01CT (the evaluation isomorphism of a line bundle) and 01NE ("`x_0, …, x_N` generate
`O_{P^N}(1)`"); eq. (2.1) of the paper.

Proof: write `M := T.hom^*pr₁^*A`, `Q := T.hom^*pr₂^*O_X(1)`, `D := T.hom^*pr₂^*O_X(−1)`, all line bundles,
with `T.hom^*L ≅ M ⊗ D`, and `q_i := T.hom^*pr₂^*(e^*x_i) ∈ Γ(T, Q)`.
1. `x_i` is a frame of `O(1)` on `D₊(x_i) ⊆ P^N` (`isFrame_homogeneousSection`), so `x_i` is nonzero at the
   points of `D₊(x_i)`; the `D₊(x_i)` cover `P^N`; pullback along the closed immersion `e.emb`, `pr₂` and
   `T.hom` preserves "nonzero at a point" (`not_isZeroAt_sectionPullbackAlong`), so for every `t ∈ T` some
   `q_i` is nonzero at `t` (`exists_not_isZeroAt_coordinate`).
2. `contract` is an isomorphism (`isIso_contract`: `contract = (id_M ⊗ ev)` composed with monoidal structure
   isomorphisms, `ev` the evaluation of a line bundle, Stacks 01CT `isIso_internalHomEval_dual`);
   `contractSections T w q` is the component on `⊤` of the isomorphism `T.hom^*contract` (a bijection)
   applied to `w ⊗ q` (transported through the isomorphisms `tensorIsoTensorObj`, `pullbackTensorObjIso`),
   so the hypothesis becomes `w ⊗ q_i = w' ⊗ q_i`.
3. The general lemma `eq_of_sectionTensor_eq_of_forall_exists_not_isZeroAt`: at `t` pick `q_i` nonzero at `t`,
   so `q_i` is a frame of `Q` near `t`; take a frame `ℓ` of `M ⊗ D`, write `w = a • ℓ`, `w' = a' • ℓ`; then
   `(w ⊗ q_i)_t = a_t • (ℓ ⊗ q_i)_t`, and `(M ⊗ D ⊗ Q)_t ≃ 𝒪_t` sends `(ℓ ⊗ q_i)_t` to `1`, so `a_t = a'_t`
   and `w_t = w'_t`.
4. This holds at every point, so `w = w'` by separatedness of the sheaf. -/
theorem conePuncturedLineBundle.contractSections_injective {k : Type u} [Field k]
    {C X : AlgebraicGeometry.Scheme.{u}} [C.Over (AlgebraicGeometry.Spec (CommRingCat.of k))]
    [X.Over (AlgebraicGeometry.Spec (CommRingCat.of k))] {N : ℕ}
    (e : ProjectiveEmbedding k X N) (A : C.Modules) [A.IsLineBundle]
    (T : CategoryTheory.Over (CategoryTheory.Limits.pullback (C ↘ AlgebraicGeometry.Spec (CommRingCat.of k))
      (X ↘ AlgebraicGeometry.Spec (CommRingCat.of k))))
    (w w' : (((AlgebraicGeometry.Scheme.Modules.pullback T.hom).obj (conePuncturedLineBundle e A)).val.obj
      (Opposite.op ⊤) : Type u))
    (h : ∀ i : Fin (N + 1),
      conePuncturedLineBundle.contractSections e A T w
          (sectionPullbackAlong T.hom (conePuncturedLineBundle.coordinate C e i)) =
        conePuncturedLineBundle.contractSections e A T w'
          (sectionPullbackAlong T.hom (conePuncturedLineBundle.coordinate C e i))) :
    w = w' := by
  have h2 := ProjectiveEmbedding.oX_one_isLineBundle e
  have hc : CategoryTheory.IsIso (conePuncturedLineBundle.contract e A) :=
    conePuncturedLineBundle.isIso_contract e A
  -- the hypothesis becomes `w ⊗ q_i = w' ⊗ q_i`
  have hten : ∀ i : Fin (N + 1),
      sectionTensor w (sectionPullbackAlong T.hom (conePuncturedLineBundle.coordinate C e i)) =
        sectionTensor w' (sectionPullbackAlong T.hom (conePuncturedLineBundle.coordinate C e i)) := by
    intro i
    have hi := h i
    unfold conePuncturedLineBundle.contractSections at hi
    have hb1 := AlgebraicGeometry.Scheme.Modules.Iso.app_bijective
      (CategoryTheory.asIso ((AlgebraicGeometry.Scheme.Modules.pullback T.hom).map
        (conePuncturedLineBundle.contract e A))) ⊤
    have hb2 := AlgebraicGeometry.Scheme.Modules.Iso.app_bijective
      (AlgebraicGeometry.Scheme.Modules.pullbackTensorObjIso T.hom (conePuncturedLineBundle e A)
        ((AlgebraicGeometry.Scheme.Modules.pullback
          (CategoryTheory.Limits.pullback.snd (C ↘ AlgebraicGeometry.Spec (CommRingCat.of k))
            (X ↘ AlgebraicGeometry.Spec (CommRingCat.of k)))).obj
          (e.oX 1))).symm ⊤
    have hb3 := AlgebraicGeometry.Scheme.Modules.Iso.app_bijective
      (AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj
        ((AlgebraicGeometry.Scheme.Modules.pullback T.hom).obj (conePuncturedLineBundle e A))
        ((AlgebraicGeometry.Scheme.Modules.pullback T.hom).obj
          ((AlgebraicGeometry.Scheme.Modules.pullback
            (CategoryTheory.Limits.pullback.snd (C ↘ AlgebraicGeometry.Spec (CommRingCat.of k))
              (X ↘ AlgebraicGeometry.Spec (CommRingCat.of k)))).obj
            (e.oX 1)))) ⊤
    exact hb3.1 (hb2.1 (hb1.1 hi))
  exact AlgebraicGeometry.Scheme.Modules.eq_of_sectionTensor_eq_of_forall_exists_not_isZeroAt _ _
    (fun i => sectionPullbackAlong T.hom (conePuncturedLineBundle.coordinate C e i))
    (conePuncturedLineBundle.exists_not_isZeroAt_coordinate e T) w w' hten

end
