import MiyaokaMori.Prelude
import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Functor
import Mathlib.AlgebraicGeometry.Morphisms.ClosedImmersion

/-! # `Proj.map` of a graded map surjective in positive degrees is a closed immersion

A graded ring homomorphism `f : 𝒜 →+*ᵍ ℬ` that is **surjective in every positive degree**
induces a closed immersion `Proj.map f : Proj ℬ → Proj 𝒜` (Stacks 01MZ / Hartshorne II Ex. 3.12(a):
`Proj (𝒜/I) → Proj 𝒜` is a closed immersion). Surjectivity in degree `0` is *not* required:
on the chart `D_+(s)`, `s ∈ 𝒜_d`, `d > 0`, the map `𝒜_{(s)} → ℬ_{(f s)}` is surjective because
`a / (f s)^n = (a · f s) / (f s)^{n+1}` and `a · f s` has positive degree.

Source: Stacks 01MZ (constructions-lemma-proj-closed-immersion-of-surjective-graded-map),
Mathlib `AlgebraicGeometry.Proj.awayι_comp_map` for the chart squares. Used by
`ProjToSpecProperOfGenerated.lean` (a Proj generated by finitely many degree-one elements over
the base is a closed subscheme of `P^N`), hence for Stacks 01WC.
-/

set_option autoImplicit false

universe u

open CategoryTheory CategoryTheory.Limits HomogeneousLocalization

noncomputable section

namespace AlgebraicGeometry.Proj

variable {A B σ τ : Type u} [CommRing A] [SetLike σ A] [AddSubgroupClass σ A]
  [CommRing B] [SetLike τ B] [AddSubgroupClass τ B]
  {𝒜 : ℕ → σ} {ℬ : ℕ → τ} [GradedRing 𝒜] [GradedRing ℬ]
  (f : 𝒜 →+*ᵍ ℬ)

/-- If `f` is surjective in every positive degree, then `𝒜_{(s)} → ℬ_{(f s)}` is surjective for every
homogeneous `s` of positive degree: `a / (f s)^n = (a · f s) / (f s)^{n+1}` and `a · f s = f x`. -/
theorem away_map_surjective (hsurj : ∀ n, 0 < n → ∀ y ∈ ℬ n, ∃ x ∈ 𝒜 n, f x = y)
    {d : ℕ} (hd : 0 < d) {s : A} (hs : s ∈ 𝒜 d) :
    Function.Surjective (Away.map f s) := by
  intro y
  obtain ⟨n, a, ha, rfl⟩ := Away.mk_surjective ℬ (f.map_mem hs) y
  have hmem : a * f s ∈ ℬ ((n + 1) • d) := by
    rw [succ_nsmul]
    exact SetLike.mul_mem_graded ha (f.map_mem hs)
  have hpos : 0 < (n + 1) • d := by
    rw [smul_eq_mul]
    exact Nat.mul_pos (Nat.succ_pos n) hd
  obtain ⟨x, hx, hxa⟩ := hsurj ((n + 1) • d) hpos (a * f s) hmem
  refine ⟨Away.mk 𝒜 hs (n + 1) x hx, ?_⟩
  rw [Away.map_mk]
  apply HomogeneousLocalization.val_injective
  rw [Away.val_mk, Away.val_mk, hxa, Localization.mk_eq_mk_iff]
  apply Localization.r_of_eq
  show f s ^ n * (a * f s) = f s ^ (n + 1) * a
  ring

/-- **Closed immersion criterion for `Proj.map`**: surjective in every positive degree ⇒ closed
immersion. Proof: closed immersions are Zariski-local on the target; on the affine cover
`Spec 𝒜_{(s)} → Proj 𝒜` (`s` homogeneous of positive degree) the pullback of `Proj.map f` is
`Spec (𝒜_{(s)} → ℬ_{(f s)})` (`awayι_comp_map`, `map_preimage_basicOpen`), which is a closed
immersion because the ring map is surjective (`away_map_surjective`). -/
theorem isClosedImmersion_map
    (hf : HomogeneousIdeal.irrelevant ℬ ≤ (HomogeneousIdeal.irrelevant 𝒜).map f)
    (hsurj : ∀ n, 0 < n → ∀ y ∈ ℬ n, ∃ x ∈ 𝒜 n, f x = y) :
    IsClosedImmersion (Proj.map f hf) := by
  apply IsZariskiLocalAtTarget.of_openCover (P := @IsClosedImmersion)
    (Proj.affineOpenCover 𝒜).openCover
  change ∀ s : (Σ i : ℕ+, 𝒜 i),
    IsClosedImmersion (pullback.snd (Proj.map f hf) (awayι 𝒜 s.2.1 s.2.2 s.1.2))
  rintro ⟨m, t, ht⟩
  -- the `IsOpenImmersion (awayι …)` instance is not found by unification through the `ℕ+` coercion
  have : IsOpenImmersion (awayι 𝒜 t ht m.pos) := by unfold awayι; infer_instance
  have : IsOpenImmersion (awayι ℬ (f t) (f.map_mem ht) m.pos) := by unfold awayι; infer_instance
  have hpb : IsPullback (Spec.map (CommRingCat.ofHom (Away.map f t)))
      (awayι ℬ (f t) (f.map_mem ht) m.pos) (awayι 𝒜 t ht m.pos) (Proj.map f hf) := by
    apply IsOpenImmersion.isPullback
    · exact awayι_comp_map f hf m.pos t ht
    · rw [opensRange_awayι, opensRange_awayι]
      rfl
  rw [← MorphismProperty.cancel_left_of_respectsIso (P := @IsClosedImmersion)
    hpb.flip.isoPullback.hom, hpb.flip.isoPullback_hom_snd]
  exact IsClosedImmersion.spec_of_surjective _ (away_map_surjective f hsurj m.pos ht)

end AlgebraicGeometry.Proj

end
