import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Cohomology.Cech.CechPullbackMap
import MiyaokaMori.AlgebraicGeometry.Modules.Pullback.PullbackSectionsNativeBaseChange
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.GradedQcAlgebraPullback
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.TensorSectionsBilinear
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.OfGradedQCAlgebra

/-! # The unit graded homomorphism of the base change of a relative Proj

Statement: for `g : S' ⟶ S`, a graded quasi-coherent algebra `𝒜` on `S`, opens `U ⊆ S`, `V ⊆ S'`
with `V ≤ g⁻¹U`, the **unit graded ring homomorphism**
`baseChangeUnitGraded g 𝒜 U V hV : 𝒜(U) →+*ᵍ (g^*𝒜)(V)`, `s ↦ (g^*s)|_V`, between the section rings
of the old encoding (`GradedQCAlgebra.sectionsRing`, `⊕_m Γ(U, 𝒜_m)`).
Piecewise it is `Modules.pullbackSectionsOn g (𝒜.part m) U V hV` (restriction to `V` of the
pullback–pushforward adjunction unit `η : 𝒜_m ⟶ g_* g^* 𝒜_m` evaluated on `U`).

This is the algebraic input of Stacks 01O3 (`RelativeProjBaseChangeComparison.lean`):
`Proj.map` of this graded hom is the local comparison map
`Proj((g^*𝒜)(V)) ⟶ Proj(𝒜(U))` (`RelativeProjBaseChangeLocal.lean`).

Proved here: the unit is compatible with the multiplication/unit of `𝒜.pullback g`
(`baseChangeUnitPiece_gOne`, `baseChangeUnitPiece_gMul`; via the three generic lemmas on
`Modules.pullbackSectionsOn` in the first section: naturality in the module, the unit `ε`, the
tensor `μ`), with restriction (`baseChangeUnitRingHom_restrict`) and with the structure maps
`Γ(S,U) → 𝒜(U)_0`, `Γ(S',V) → (g^*𝒜)(V)_0` along `g^♯` (`baseChangeUnitRingHom_sectionsUnitHom`).
Also proved (from Stacks 01I9, `isIso_transpose_pullbackSectionsNative`):
* `baseChangeUnitGraded_irrelevant_le`: for affine `U`, `V` the irrelevant ideal of `(g^*𝒜)(V)` is
  generated by the image of the irrelevant ideal of `𝒜(U)` (the `Proj.map` hypothesis of
  `baseChangeProjMap`, `RelativeProjBaseChangeLocal.lean`).

Source: Stacks 01O3 (constructions.tex, `lemma-relative-proj-base-change`), 01I9; the base change of
`P(O ⊕ L)` in Corollary 4.3 of the paper.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

namespace AlgebraicGeometry.Scheme.Modules

variable {S S' : AlgebraicGeometry.Scheme.{u}} (g : S' ⟶ S)

/-- Naturality of the section pullback in the module: for `φ : M ⟶ N`,
`(g^*φ)((g^*s)|_V) = (g^*(φ s))|_V` (adjunction unit naturality + naturality of `Hom.app`
with respect to restriction). -/
theorem pullback_map_app_pullbackSectionsOn {M N : S.Modules} (φ : M ⟶ N) (U : S.Opens)
    (V : S'.Opens) (hV : V ≤ g ⁻¹ᵁ U) (s : Γ(M, U)) :
    ((AlgebraicGeometry.Scheme.Modules.pullback g).map φ).app V
        (AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g M U V hV s) =
      AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g N U V hV (φ.app U s) := by
  rw [pullbackSectionsOn_apply, pullbackSectionsOn_apply]
  have h1 := ((AlgebraicGeometry.Scheme.Modules.pullback g).map φ).mapPresheaf.naturality_apply
    (homOfLE hV).op (pullbackUnitHom g M U s)
  have h2 := congrArg
    (fun ψ : M ⟶ (AlgebraicGeometry.Scheme.Modules.pushforward g).obj
      ((AlgebraicGeometry.Scheme.Modules.pullback g).obj N) => ψ.app U s)
    ((AlgebraicGeometry.Scheme.Modules.pullbackPushforwardAdjunction g).unit_naturality φ)
  simp only [AlgebraicGeometry.Scheme.Modules.Hom.comp_app,
    AlgebraicGeometry.Scheme.Modules.pushforward_map_app] at h2
  exact h1.trans (congrArg _ h2)

/-- The comparison `g^*O_S ⟶ O_{S'}` (`pullbackUnitIso.hom = pullbackObjUnitToUnit`) sends
`(g^*1)|_V` to `1`: its adjoint transpose is the structure map `g^♯`, which preserves `1`. -/
theorem pullbackUnitIso_hom_app_pullbackSectionsOn_one (U : S.Opens) (V : S'.Opens)
    (hV : V ≤ g ⁻¹ᵁ U) :
    (AlgebraicGeometry.Scheme.Modules.pullbackUnitIso g).hom.app V
      (AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g
        (CategoryTheory.MonoidalCategoryStruct.tensorUnit S.Modules) U V hV (1 : Γ(S, U))) =
      (1 : Γ(S', V)) := by
  have h1 := (AlgebraicGeometry.Scheme.Modules.pullbackUnitIso g).hom.mapPresheaf.naturality_apply
    (homOfLE hV).op
    (pullbackUnitHom g (CategoryTheory.MonoidalCategoryStruct.tensorUnit S.Modules) U (1 : Γ(S, U)))
  have h2 : (AlgebraicGeometry.Scheme.Modules.pullbackUnitIso g).hom.app (g ⁻¹ᵁ U)
      (pullbackUnitHom g (CategoryTheory.MonoidalCategoryStruct.tensorUnit S.Modules) U
        (1 : Γ(S, U))) = (1 : Γ(S', g ⁻¹ᵁ U)) := by
    have : (SheafOfModules.pushforward.{u} g.toRingCatSheafHom).IsRightAdjoint :=
      (AlgebraicGeometry.Scheme.Modules.pullbackPushforwardAdjunction g).isRightAdjoint
    have h3 := congrArg
      (fun ψ : CategoryTheory.MonoidalCategoryStruct.tensorUnit S.Modules ⟶
          (AlgebraicGeometry.Scheme.Modules.pushforward g).obj
            (CategoryTheory.MonoidalCategoryStruct.tensorUnit S'.Modules) => ψ.app U (1 : Γ(S, U)))
      ((CategoryTheory.Adjunction.homEquiv_unit
        (adj := AlgebraicGeometry.Scheme.Modules.pullbackPushforwardAdjunction g)
        (f := (AlgebraicGeometry.Scheme.Modules.pullbackUnitIso g).hom)).symm.trans
        (SheafOfModules.pullbackPushforwardAdjunction_homEquiv_pullbackObjUnitToUnit
          g.toRingCatSheafHom))
    simp only [AlgebraicGeometry.Scheme.Modules.Hom.comp_app] at h3
    refine h3.trans ?_
    exact map_one (g.toRingCatSheafHom.hom.app (op U)).hom
  refine h1.trans ((congrArg _ h2).trans ?_)
  show (S'.presheaf.map (homOfLE hV).op).hom 1 = 1
  exact map_one _

/-- `δ = pullbackTensorObjHom` sends `(g^*(a ⊗ b))|_V` to `(g^*a)|_V ⊗ (g^*b)|_V`. -/
theorem pullbackTensorObjHom_app_pullbackSectionsOn (M N : S.Modules) (U : S.Opens) (V : S'.Opens)
    (hV : V ≤ g ⁻¹ᵁ U) (a : Γ(M, U)) (b : Γ(N, U)) :
    (AlgebraicGeometry.Scheme.Modules.pullbackTensorObjHom g M N).app V
        (AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g
          (CategoryTheory.MonoidalCategoryStruct.tensorObj M N) U V hV
          (AlgebraicGeometry.Scheme.Modules.tensorSections M N U a b)) =
      AlgebraicGeometry.Scheme.Modules.tensorSections
        ((AlgebraicGeometry.Scheme.Modules.pullback g).obj M)
        ((AlgebraicGeometry.Scheme.Modules.pullback g).obj N) V
        (AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g M U V hV a)
        (AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g N U V hV b) := by
  -- naturality of δ with respect to restriction
  have h1 := (AlgebraicGeometry.Scheme.Modules.pullbackTensorObjHom g M N).mapPresheaf.naturality_apply
    (homOfLE hV).op
    (pullbackUnitHom g (CategoryTheory.MonoidalCategoryStruct.tensorObj M N) U
      (AlgebraicGeometry.Scheme.Modules.tensorSections M N U a b))
  -- δ on `g⁻¹U`: the adjoint transpose of δ on a tensor of sections
  have h2 : (AlgebraicGeometry.Scheme.Modules.pullbackTensorObjHom g M N).app (g ⁻¹ᵁ U)
      (pullbackUnitHom g (CategoryTheory.MonoidalCategoryStruct.tensorObj M N) U
        (AlgebraicGeometry.Scheme.Modules.tensorSections M N U a b)) =
      AlgebraicGeometry.Scheme.Modules.tensorSections
        ((AlgebraicGeometry.Scheme.Modules.pullback g).obj M)
        ((AlgebraicGeometry.Scheme.Modules.pullback g).obj N) (g ⁻¹ᵁ U)
        (pullbackUnitHom g M U a) (pullbackUnitHom g N U b) := by
    have h3 := AlgebraicGeometry.Scheme.Modules.homEquiv_pullbackTensorObjHom_tensorSections g M N U a b
    have h4 := congrArg
      (fun ψ : CategoryTheory.MonoidalCategoryStruct.tensorObj M N ⟶
          (AlgebraicGeometry.Scheme.Modules.pushforward g).obj
            (CategoryTheory.MonoidalCategoryStruct.tensorObj
              ((AlgebraicGeometry.Scheme.Modules.pullback g).obj M)
              ((AlgebraicGeometry.Scheme.Modules.pullback g).obj N)) =>
        ψ.app U (AlgebraicGeometry.Scheme.Modules.tensorSections M N U a b))
      (CategoryTheory.Adjunction.homEquiv_unit
        (adj := AlgebraicGeometry.Scheme.Modules.pullbackPushforwardAdjunction g)
        (f := AlgebraicGeometry.Scheme.Modules.pullbackTensorObjHom g M N))
    simp only [AlgebraicGeometry.Scheme.Modules.Hom.comp_app] at h4
    exact h4.symm.trans h3
  refine h1.trans ((congrArg _ h2).trans ?_)
  exact AlgebraicGeometry.Scheme.Modules.tensorSections_restrict _ _ (homOfLE hV) _ _

/-- `μ = δ⁻¹` sends `(g^*a)|_V ⊗ (g^*b)|_V` to `(g^*(a ⊗ b))|_V`. -/
theorem pullback_μ_app_tensorSections_pullbackSectionsOn (M N : S.Modules) (U : S.Opens)
    (V : S'.Opens) (hV : V ≤ g ⁻¹ᵁ U) (a : Γ(M, U)) (b : Γ(N, U)) :
    (CategoryTheory.Functor.LaxMonoidal.μ (AlgebraicGeometry.Scheme.Modules.pullback g) M N).app V
        (AlgebraicGeometry.Scheme.Modules.tensorSections
          ((AlgebraicGeometry.Scheme.Modules.pullback g).obj M)
          ((AlgebraicGeometry.Scheme.Modules.pullback g).obj N) V
          (AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g M U V hV a)
          (AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g N U V hV b)) =
      AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g
        (CategoryTheory.MonoidalCategoryStruct.tensorObj M N) U V hV
        (AlgebraicGeometry.Scheme.Modules.tensorSections M N U a b) := by
  have h := pullbackTensorObjHom_app_pullbackSectionsOn g M N U V hV a b
  have h4 := congrArg
    (fun ψ : (AlgebraicGeometry.Scheme.Modules.pullback g).obj
        (CategoryTheory.MonoidalCategoryStruct.tensorObj M N) ⟶
      (AlgebraicGeometry.Scheme.Modules.pullback g).obj
        (CategoryTheory.MonoidalCategoryStruct.tensorObj M N) => ψ.app V
      (AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g
        (CategoryTheory.MonoidalCategoryStruct.tensorObj M N) U V hV
        (AlgebraicGeometry.Scheme.Modules.tensorSections M N U a b)))
    (AlgebraicGeometry.Scheme.Modules.pullbackTensorObjIso g M N).hom_inv_id
  simp only [AlgebraicGeometry.Scheme.Modules.Hom.comp_app] at h4
  have h5 := congrArg
    (fun ψ : CategoryTheory.MonoidalCategoryStruct.tensorObj
        ((AlgebraicGeometry.Scheme.Modules.pullback g).obj M)
        ((AlgebraicGeometry.Scheme.Modules.pullback g).obj N) ⟶
      (AlgebraicGeometry.Scheme.Modules.pullback g).obj
        (CategoryTheory.MonoidalCategoryStruct.tensorObj M N) => ψ.app V
      (AlgebraicGeometry.Scheme.Modules.tensorSections
          ((AlgebraicGeometry.Scheme.Modules.pullback g).obj M)
          ((AlgebraicGeometry.Scheme.Modules.pullback g).obj N) V
          (AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g M U V hV a)
          (AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g N U V hV b)))
    (AlgebraicGeometry.Scheme.Modules.pullback_μ_eq g M N)
  refine h5.trans ((congrArg _ h.symm).trans ?_)
  exact h4

end AlgebraicGeometry.Scheme.Modules

namespace AlgebraicGeometry.Scheme.GradedQCAlgebra

variable {S S' : AlgebraicGeometry.Scheme.{u}} (g : S' ⟶ S) (𝒜 : S.GradedQCAlgebra)
  (U : S.Opens) (V : S'.Opens) (hV : V ≤ g ⁻¹ᵁ U)

/-- The `m`-th piece of the unit: `Γ(U, 𝒜_m) → Γ(V, g^*𝒜_m)`, `s ↦ (g^*s)|_V`
(`Modules.pullbackSectionsOn`: adjunction unit on `U`, then restriction from `g⁻¹U` to `V`). -/
def baseChangeUnitPiece (m : ℕ) : 𝒜.sectionsPiece U m →+ (𝒜.pullback g).sectionsPiece V m :=
  AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g (𝒜.part m) U V hV

/-- The unit sends the graded unit `1_U ∈ Γ(U, 𝒜_0)` to `1_V ∈ Γ(V, g^*𝒜_0)`.

Source: Stacks 01O3 / 01AG (the adjunction unit of `g^* ⊣ g_*` is a monoidal transformation).

Proof. By definition `(𝒜.pullback g).sectionsGOne V = ((𝒜.pullback g).one).app V 1` with
`(𝒜.pullback g).one = ε ≫ (g^*).map 𝒜.one`, where `ε = pullbackUnitIso.inv`
(`Modules.pullback_ε_eq`) and
`pullbackUnitIso.hom = SheafOfModules.pullbackObjUnitToUnit g` is the adjoint transpose of the
structure map `g^♯ : O_S ⟶ g_* O_{S'}`. Hence `pullbackUnitIso.hom.app (η_{O_S}(1)|_V) = g^♯(1) = 1`,
i.e. `ε.app V 1 = η_{O_S}(1)|_V`. By naturality of `η` in the module
(`Adjunction.unit_naturality` for `𝒜.one : O_S ⟶ 𝒜_0`), `((g^*).map 𝒜.one).app (η_{O_S}(1)) =
η_{𝒜_0}(𝒜.one.app U 1) = η_{𝒜_0}(sectionsGOne U)`; restricting from `g⁻¹U` to `V`
(`pullbackSectionsOn_apply`, naturality of `Hom.app` with respect to restriction) gives
`baseChangeUnitPiece 0 (sectionsGOne U) = sectionsGOne' V`. No missing library facts: all named
lemmas exist (`pullback_ε_eq`, `pullbackUnitIso`, `SheafOfModules.pullbackObjUnitToUnit`,
`PresheafOfModules.naturality_apply`). Proved (via `pullback_map_app_pullbackSectionsOn` and
`pullbackUnitIso_hom_app_pullbackSectionsOn_one`). -/
theorem baseChangeUnitPiece_gOne :
    baseChangeUnitPiece g 𝒜 U V hV 0 (𝒜.sectionsGOne U) = (𝒜.pullback g).sectionsGOne V := by
  -- ε on `1` is `(g^*1)|_V`
  have hε : (CategoryTheory.Functor.LaxMonoidal.ε (AlgebraicGeometry.Scheme.Modules.pullback g)).app V
        (1 : Γ(S', V)) =
      AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g
        (CategoryTheory.MonoidalCategoryStruct.tensorUnit S.Modules) U V hV (1 : Γ(S, U)) := by
    have h := AlgebraicGeometry.Scheme.Modules.pullbackUnitIso_hom_app_pullbackSectionsOn_one g U V hV
    have h4 := congrArg
      (fun ψ : (AlgebraicGeometry.Scheme.Modules.pullback g).obj
          (CategoryTheory.MonoidalCategoryStruct.tensorUnit S.Modules) ⟶
        (AlgebraicGeometry.Scheme.Modules.pullback g).obj
          (CategoryTheory.MonoidalCategoryStruct.tensorUnit S.Modules) => ψ.app V
        (AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g
          (CategoryTheory.MonoidalCategoryStruct.tensorUnit S.Modules) U V hV (1 : Γ(S, U))))
      (AlgebraicGeometry.Scheme.Modules.pullbackUnitIso g).hom_inv_id
    simp only [AlgebraicGeometry.Scheme.Modules.Hom.comp_app] at h4
    have h5 := congrArg
      (fun ψ : CategoryTheory.MonoidalCategoryStruct.tensorUnit S'.Modules ⟶
        (AlgebraicGeometry.Scheme.Modules.pullback g).obj
          (CategoryTheory.MonoidalCategoryStruct.tensorUnit S.Modules) => ψ.app V (1 : Γ(S', V)))
      (AlgebraicGeometry.Scheme.Modules.pullback_ε_eq g)
    refine h5.trans ((congrArg _ h.symm).trans ?_)
    exact h4
  -- `one` of the pullback algebra is `ε ≫ g^*(𝒜.one)`
  have hone : (𝒜.pullback g).sectionsGOne V =
      ((AlgebraicGeometry.Scheme.Modules.pullback g).map 𝒜.one).app V
        ((CategoryTheory.Functor.LaxMonoidal.ε (AlgebraicGeometry.Scheme.Modules.pullback g)).app V
          (1 : Γ(S', V))) := rfl
  refine Eq.trans ?_ hone.symm
  exact ((AlgebraicGeometry.Scheme.Modules.pullback_map_app_pullbackSectionsOn g 𝒜.one U V hV
    (1 : Γ(S, U))).symm.trans (congrArg _ hε.symm))

/-- The unit is multiplicative on graded pieces.

Source: Stacks 01O3 / 01AG (`g^*` is strong monoidal and the adjunction unit is monoidal).

Proof. `𝒜.sectionsGMul U a b = (𝒜.mul m n).app U (tensorSections a b)` and
`(𝒜.pullback g).sectionsGMul V a' b' = ((𝒜.pullback g).mul m n).app V (tensorSections a' b')` with
`(𝒜.pullback g).mul m n = μ ≫ (g^*).map (𝒜.mul m n)`, `μ = δ⁻¹` (`Modules.pullback_μ_eq`).
By `Modules.homEquiv_pullbackTensorObjHom_tensorSections` the
adjoint transpose of `δ` sends `tensorSections a b` to `tensorSections (η a) (η b)`, i.e.
`δ.app (g⁻¹U) (η_{𝒜_m ⊗ 𝒜_n}(a ⊗ b)) = η_{𝒜_m}(a) ⊗ η_{𝒜_n}(b)`; hence
`μ.app (g⁻¹U) (η a ⊗ η b) = η(a ⊗ b)`. Naturality of `η` for `𝒜.mul m n` gives
`((g^*).map (𝒜.mul m n)).app (g⁻¹U) (η(a ⊗ b)) = η((𝒜.mul m n).app U (a ⊗ b))`. Finally restrict
from `g⁻¹U` to `V`: `tensorSections` commutes with restriction (`tensorSections_restrict`) and so
does `Hom.app` (`PresheafOfModules.naturality_apply`). Proved (via
`pullback_map_app_pullbackSectionsOn` and `pullback_μ_app_tensorSections_pullbackSectionsOn`). -/
theorem baseChangeUnitPiece_gMul {m n : ℕ} (a : 𝒜.sectionsPiece U m) (b : 𝒜.sectionsPiece U n) :
    baseChangeUnitPiece g 𝒜 U V hV (m + n) (𝒜.sectionsGMul U a b) =
      (𝒜.pullback g).sectionsGMul V (baseChangeUnitPiece g 𝒜 U V hV m a)
        (baseChangeUnitPiece g 𝒜 U V hV n b) := by
  have hmul : (𝒜.pullback g).sectionsGMul V (baseChangeUnitPiece g 𝒜 U V hV m a)
        (baseChangeUnitPiece g 𝒜 U V hV n b) =
      ((AlgebraicGeometry.Scheme.Modules.pullback g).map (𝒜.mul m n)).app V
        ((CategoryTheory.Functor.LaxMonoidal.μ (AlgebraicGeometry.Scheme.Modules.pullback g)
          (𝒜.part m) (𝒜.part n)).app V
          (AlgebraicGeometry.Scheme.Modules.tensorSections
            ((AlgebraicGeometry.Scheme.Modules.pullback g).obj (𝒜.part m))
            ((AlgebraicGeometry.Scheme.Modules.pullback g).obj (𝒜.part n)) V
            (AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g (𝒜.part m) U V hV a)
            (AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn g (𝒜.part n) U V hV b))) := rfl
  refine Eq.trans ?_ hmul.symm
  refine Eq.trans ?_ (congrArg _
    (AlgebraicGeometry.Scheme.Modules.pullback_μ_app_tensorSections_pullbackSectionsOn g (𝒜.part m)
      (𝒜.part n) U V hV a b).symm)
  exact (AlgebraicGeometry.Scheme.Modules.pullback_map_app_pullbackSectionsOn g (𝒜.mul m n) U V hV
    (AlgebraicGeometry.Scheme.Modules.tensorSections (𝒜.part m) (𝒜.part n) U a b)).symm


/-- The unit as a ring homomorphism `𝒜(U) →+* (g^*𝒜)(V)` (piecewise, `DirectSum.toSemiring`). -/
def baseChangeUnitRingHom : 𝒜.sectionsRing U →+* (𝒜.pullback g).sectionsRing V :=
  DirectSum.toSemiring
    (fun m => (DirectSum.of ((𝒜.pullback g).sectionsPiece V) m).comp
      (baseChangeUnitPiece g 𝒜 U V hV m))
    (by
      show DirectSum.of ((𝒜.pullback g).sectionsPiece V) 0
        (baseChangeUnitPiece g 𝒜 U V hV 0 (𝒜.sectionsGOne U)) = 1
      rw [baseChangeUnitPiece_gOne]
      rfl)
    (fun {i j} a b => by
      show DirectSum.of ((𝒜.pullback g).sectionsPiece V) (i + j)
        (baseChangeUnitPiece g 𝒜 U V hV (i + j) (𝒜.sectionsGMul U a b)) = _
      rw [baseChangeUnitPiece_gMul]
      exact (DirectSum.of_mul_of _ _).symm)

theorem baseChangeUnitRingHom_of (m : ℕ) (a : 𝒜.sectionsPiece U m) :
    baseChangeUnitRingHom g 𝒜 U V hV (DirectSum.of (𝒜.sectionsPiece U) m a) =
      DirectSum.of ((𝒜.pullback g).sectionsPiece V) m (baseChangeUnitPiece g 𝒜 U V hV m a) :=
  DirectSum.toSemiring_of _ _ _ m a

/-- The unit as a graded ring homomorphism `𝒜(U) →+*ᵍ (g^*𝒜)(V)`. -/
def baseChangeUnitGraded : 𝒜.sectionsGrading U →+*ᵍ (𝒜.pullback g).sectionsGrading V where
  toRingHom := baseChangeUnitRingHom g 𝒜 U V hV
  map_mem := by
    rintro i x ⟨a, rfl⟩
    exact ⟨baseChangeUnitPiece g 𝒜 U V hV i a, (baseChangeUnitRingHom_of g 𝒜 U V hV i a).symm⟩

theorem baseChangeUnitGraded_apply (x : 𝒜.sectionsRing U) :
    baseChangeUnitGraded g 𝒜 U V hV x = baseChangeUnitRingHom g 𝒜 U V hV x := rfl

/-- The unit commutes with restriction: for `U' ≤ U`, `V' ≤ V`, `V' ≤ g⁻¹U'`,
`res_{V'} ∘ unit_{U,V} = unit_{U',V'} ∘ res_{U'}` (both sides are ring homs on the direct sum, so it
suffices to check on `of m a`, where it is `pullbackSectionsOn_restrict`). -/
theorem baseChangeUnitRingHom_restrict {U' : S.Opens} {V' : S'.Opens} (hU' : U' ≤ U)
    (hV'V : V' ≤ V) (hV' : V' ≤ g ⁻¹ᵁ U') (x : 𝒜.sectionsRing U) :
    (𝒜.pullback g).sectionsRestrictHom hV'V (baseChangeUnitRingHom g 𝒜 U V hV x) =
      baseChangeUnitRingHom g 𝒜 U' V' hV' (𝒜.sectionsRestrictHom hU' x) := by
  have key : ((𝒜.pullback g).sectionsRestrictHom hV'V).comp (baseChangeUnitRingHom g 𝒜 U V hV) =
      (baseChangeUnitRingHom g 𝒜 U' V' hV').comp (𝒜.sectionsRestrictHom hU') := by
    refine DirectSum.ringHom_ext fun m a => ?_
    show (𝒜.pullback g).sectionsRestrictRingHom hV'V
        (baseChangeUnitRingHom g 𝒜 U V hV (DirectSum.of (𝒜.sectionsPiece U) m a)) =
      baseChangeUnitRingHom g 𝒜 U' V' hV'
        (𝒜.sectionsRestrictRingHom hU' (DirectSum.of (𝒜.sectionsPiece U) m a))
    rw [baseChangeUnitRingHom_of, (𝒜.pullback g).sectionsRestrictRingHom_of,
      𝒜.sectionsRestrictRingHom_of, baseChangeUnitRingHom_of]
    refine congrArg _ ?_
    exact AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn_restrict g (𝒜.part m) hV hV' hU'
      hV'V a
  exact DFunLike.congr_fun key x

/-- The unit is compatible with the structure maps: `unit (r · 1_U) = g^♯(r)|_V · 1_V`.

Source: Stacks 01O3 (the base change square of the degree-0 parts).

Proof. `𝒜.sectionsUnitHom U r = of 0 (𝒜.one.app U r) = of 0 (r • 1_U)` (`smul_sectionsGOne`);
`baseChangeUnitRingHom_of` reduces to the piece `0`, where `pullbackSectionsOn` is semilinear
along `g.appLE U V hV` (`pullbackUnitHom_smul` + `Modules.map_smul`), so
`unit_0 (r • 1_U) = g^♯(r)|_V • unit_0 1_U = g^♯(r)|_V • 1_V` by `baseChangeUnitPiece_gOne`, and
`smul_sectionsGOne` for `𝒜.pullback g` turns this back into `sectionsUnitHom V (g^♯(r)|_V)`.
Depends on `baseChangeUnitPiece_gOne`. -/
theorem baseChangeUnitRingHom_sectionsUnitHom (r : Γ(S, U)) :
    baseChangeUnitRingHom g 𝒜 U V hV (𝒜.sectionsUnitHom U r) =
      (𝒜.pullback g).sectionsUnitHom V ((g.appLE U V hV).hom r) := by
  have h1 : 𝒜.sectionsUnitHom U r = DirectSum.of (𝒜.sectionsPiece U) 0 (𝒜.one.app U r) := rfl
  have h2 : (𝒜.pullback g).sectionsUnitHom V ((g.appLE U V hV).hom r) =
      DirectSum.of ((𝒜.pullback g).sectionsPiece V) 0
        ((𝒜.pullback g).one.app V ((g.appLE U V hV).hom r)) := rfl
  rw [h1, h2]
  exact (baseChangeUnitRingHom_of g 𝒜 U V hV 0 (𝒜.one.app U r)).trans (congrArg _ (by
    rw [← 𝒜.smul_sectionsGOne, ← (𝒜.pullback g).smul_sectionsGOne, ← baseChangeUnitPiece_gOne]
    exact AlgebraicGeometry.Scheme.Modules.pullbackSectionsOn_smul_native g (𝒜.part 0) U V hV r
      (𝒜.sectionsGOne U)))

/-- **Irrelevant ideal condition** (hypothesis of `Proj.map`): for affine `U`, `V`, the irrelevant
ideal of `(g^*𝒜)(V)` is contained in the ideal generated by the image of the irrelevant ideal of
`𝒜(U)` under the unit.

Source: Stacks 01I9 (`schemes-lemma-widetilde-pullback`, sections of the pullback of a
quasi-coherent module between affines), 01O3.

Proof. By `HomogeneousIdeal.irrelevant_le` it suffices to show that every homogeneous
`x ∈ (g^*𝒜)(V)_d`, `d > 0`, lies in the ideal generated by the image. Such `x` is `of d x'` with
`x' ∈ Γ(V, g^*𝒜_d)`. Since `𝒜_d` is quasi-coherent and `U`, `V` are affine with `V ≤ g⁻¹U`,
the canonical map `Γ(S',V) ⊗_{Γ(S,U)} Γ(U, 𝒜_d) → Γ(V, g^*𝒜_d)`, `t ⊗ s ↦ t • (g^*s)|_V`, is an
isomorphism (`Modules.isIso_transpose_pullbackSectionsNative`; only surjectivity is needed here). Hence
`x' = Σ_i t_i • (g^*s_i)|_V` with `s_i ∈ Γ(U, 𝒜_d)`. In the section ring, scalar multiplication by
`t_i` is multiplication by `(g^*𝒜).sectionsUnitHom V t_i` (`sectionsUnitHom_mul_ofPiece`),
and `of d ((g^*s_i)|_V) = unit (of d s_i)` by
`baseChangeUnitRingHom_of`, with `of d s_i ∈ 𝒜(U)_d ⊆ 𝒜(U)_+` (`d > 0`). So
`x = Σ_i sectionsUnitHom V t_i * unit (of d s_i) ∈ Ideal.map unit 𝒜(U)_+`.
Formally: `isIso_transpose_pullbackSectionsNative` gives surjectivity of the transpose
`Γ(S',V) ⊗ Γ(U,𝒜_d) → Γ(V, g^*𝒜_d)`; induction on the tensor (`TensorProduct.induction_on`), the
pure-tensor case being `t ⊗ s ↦ t • (g^*s)|_V` (`HomEquiv.fromExtendScalars`, definitional). -/
theorem baseChangeUnitGraded_irrelevant_le (hU : AlgebraicGeometry.IsAffineOpen U)
    (hVa : AlgebraicGeometry.IsAffineOpen V) :
    HomogeneousIdeal.irrelevant ((𝒜.pullback g).sectionsGrading V) ≤
      (HomogeneousIdeal.irrelevant (𝒜.sectionsGrading U)).map
        (baseChangeUnitGraded g 𝒜 U V hV) := by
  rw [HomogeneousIdeal.irrelevant_le]
  intro d hd x hx
  obtain ⟨x', rfl⟩ := hx
  -- the target ideal
  set I : Ideal ((𝒜.pullback g).sectionsRing V) :=
    Ideal.map (baseChangeUnitGraded g 𝒜 U V hV)
      (HomogeneousIdeal.irrelevant (𝒜.sectionsGrading U)).toIdeal with hI
  show DirectSum.of ((𝒜.pullback g).sectionsPiece V) d x' ∈ I
  -- Stacks 01I9: the transpose `Γ(S',V) ⊗ Γ(U,𝒜_d) → Γ(V, g^*𝒜_d)` is surjective
  have := 𝒜.quasicoherent d
  have := AlgebraicGeometry.Scheme.Modules.isIso_transpose_pullbackSectionsNative g (𝒜.part d)
    U hU V hVa hV
  set T := ((ModuleCat.extendRestrictScalarsAdj (g.appLE U V hV).hom).homEquiv _ _).symm
    (AlgebraicGeometry.Scheme.Modules.pullbackSectionsNative g (𝒜.part d) U V hV) with hT
  obtain ⟨z, rfl⟩ := (CategoryTheory.ConcreteCategory.bijective_of_isIso T).2 x'
  -- every element of the image lies in `I`: by induction on the tensor
  induction z using TensorProduct.induction_on with
  | zero =>
    have e0 : T.hom 0 = 0 := map_zero _
    have e0' : DirectSum.of ((𝒜.pullback g).sectionsPiece V) d (T.hom 0) = 0 := by
      rw [e0]; exact map_zero _
    show DirectSum.of ((𝒜.pullback g).sectionsPiece V) d (T.hom 0) ∈ I
    rw [e0']
    exact I.zero_mem
  | tmul t s =>
    obtain ⟨t', rfl⟩ : ∃ t' : ↑Γ(S', V), t' = t := ⟨t, rfl⟩
    show DirectSum.of ((𝒜.pullback g).sectionsPiece V) d
      (@HSMul.hSMul ↑Γ(S', V) ↑Γ((𝒜.pullback g).part d, V) ↑Γ((𝒜.pullback g).part d, V) _ t'
        (baseChangeUnitPiece g 𝒜 U V hV d s)) ∈ I
    have e2 : DirectSum.of ((𝒜.pullback g).sectionsPiece V) d
        (@HSMul.hSMul ↑Γ(S', V) ↑Γ((𝒜.pullback g).part d, V) ↑Γ((𝒜.pullback g).part d, V) _ t'
          (baseChangeUnitPiece g 𝒜 U V hV d s)) =
        (𝒜.pullback g).sectionsUnitHom V t' *
          (𝒜.pullback g).ofPiece V d (baseChangeUnitPiece g 𝒜 U V hV d s) :=
      ((𝒜.pullback g).sectionsUnitHom_mul_ofPiece V t' (baseChangeUnitPiece g 𝒜 U V hV d s)).symm
    rw [e2]
    have e4 : (𝒜.pullback g).ofPiece V d (baseChangeUnitPiece g 𝒜 U V hV d s) =
        baseChangeUnitGraded g 𝒜 U V hV (DirectSum.of (𝒜.sectionsPiece U) d s) :=
      (baseChangeUnitRingHom_of g 𝒜 U V hV d s).symm
    rw [e4]
    refine I.mul_mem_left _ (Ideal.mem_map_of_mem (baseChangeUnitGraded g 𝒜 U V hV) ?_)
    exact HomogeneousIdeal.mem_irrelevant_of_mem (𝒜.sectionsGrading U) hd ⟨s, rfl⟩
  | add a b ha hb =>
    have e3 : T.hom (a + b) = T.hom a + T.hom b := map_add _ a b
    have e3' : DirectSum.of ((𝒜.pullback g).sectionsPiece V) d (T.hom (a + b)) =
        DirectSum.of ((𝒜.pullback g).sectionsPiece V) d (T.hom a) +
          DirectSum.of ((𝒜.pullback g).sectionsPiece V) d (T.hom b) := by
      rw [e3]; exact map_add _ _ _
    show DirectSum.of ((𝒜.pullback g).sectionsPiece V) d (T.hom (a + b)) ∈ I
    rw [e3']
    exact I.add_mem ha hb

end AlgebraicGeometry.Scheme.GradedQCAlgebra

end
