import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.GeneratedInDegreeOne
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.GradedQuasicoherentAlgebra
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.VeroneseSubalgebra

/-! # Sufficiently divisible degrees

The predicate "`m` is sufficiently divisible": `m > 0` and the `m`-th Veronese subalgebra of `S` is
generated by its degree-one part. The paper takes `m` to be a positive multiple of `s_k w_k`
(Lemma 2.2) and uses `O(m)` only for such `m` (§2 of the paper).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

def AlgebraicGeometry.Scheme.GradedQCAlgebra.SufficientlyDivisible {X : AlgebraicGeometry.Scheme.{u}}
    (S : X.GradedQCAlgebra) (m : ℕ) : Prop :=
  0 < m ∧ (S.veronese m).GeneratedInDegreeOne

end
