import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.GeneratedInDegreeOne
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.GradedQuasicoherentAlgebra
import MiyaokaMori.Paper.S2WeightedJets.Ygg.JetWeightLcm
import MiyaokaMori.AlgebraicGeometry.Proj.WeightedProj.LocallyWeightedPolynomialAlgebra
import MiyaokaMori.AlgebraicGeometry.Modules.Basic.ModulesEpiOfOpenCover
import MiyaokaMori.Paper.S2WeightedJets.Ygg.MonomialSplitIntoWeightM
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.SufficientlyDivisible
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.VeroneseSubalgebra
import MiyaokaMori.AlgebraicGeometry.Proj.WeightedProj.WeightedPolynomialAtlasVeroneseGeneration
import MiyaokaMori.AlgebraicGeometry.Proj.WeightedProj.WeightedPolynomialQCAlgebra

/-! # Generation of the Veronese algebra

The Veronese algebra `⊕_ℓ S_{ℓm}` (with `m = s_k · w_k`) is generated by `S_m`.

Source: Lemma 2.2 of the paper.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

theorem veroneseDegree_pos {σ : Type u} [Fintype σ] [Nonempty σ] (k : ℕ) :
    0 < Fintype.card σ * jetWeight k := by
  apply Nat.mul_pos Fintype.card_pos
  rw [Nat.pos_iff_ne_zero, jetWeight, Finset.lcm_ne_zero_iff]
  intro q hq
  exact Nat.ne_of_gt (Finset.mem_Icc.mp hq).1

theorem dvd_veroneseDegree {σ : Type u} [Fintype σ] (k q : ℕ)
    (hq : q ∈ Finset.Icc 1 k) : q ∣ Fintype.card σ * jetWeight k := by
  apply dvd_mul_of_dvd_right
  exact Finset.dvd_lcm (s := Finset.Icc 1 k) (f := id) (b := q) hq

theorem veronese_generation {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra)
    {σ : Type u} [Fintype σ] [Nonempty σ] {k : ℕ} (w : σ → ℕ) (hw : ∀ i, w i ∈ Finset.Icc 1 k)
    (hS : S.IsLocallyWeightedPolynomial w (fun i => (Finset.mem_Icc.mp (hw i)).1)) :
    S.SufficientlyDivisible (Fintype.card σ * jetWeight k) := by
  refine ⟨veroneseDegree_pos k, ?_⟩
  obtain ⟨atlas⟩ := hS
  exact S.veronese_generatedInDegreeOne_of_atlas w hw atlas

end
