import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.OfGradedQCAlgebra
import MiyaokaMori.AlgebraicGeometry.Proj.WeightedProj.WeightedPolynomialAtlas
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.GeneratedInDegreeOne
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.VeroneseSubalgebra
import MiyaokaMori.AlgebraicGeometry.Proj.WeightedProj.WeightedPolynomialAtlasVeroneseGeneration

/-! # Veronese generation for a weighted polynomial atlas, given the splitting property

Statement: let the graded quasi-coherent algebra sheaf `S` have a weighted polynomial atlas with weights
`w : σ → ℕ`, let `m ∈ ℕ`, and assume the purely combinatorial "splitting property" `hsplit`: every monomial
exponent of weight `l·m` (`l ≥ 1`) is a sum of `l` exponents of weight `m`. Then the Veronese algebra
`S⁽ᵐ⁾ = ⊕_l S_{lm}` is generated by its degree-one part `S_m`, i.e. for every `l > 0` the map
`(S.veronese m).mulPowOne l : S_m^{⊗l} → S_{lm}` is an epimorphism in `X.Modules`.

This is the sheaf-theoretic core of the Veronese generation statement (`m = |σ| · lcm(1..k)`), with the
combinatorial part abstracted into a hypothesis: that statement is this lemma plus the splitting of monomials
into weight-`m` factors (after renumbering the variables via `Fintype.equivFin σ`); the version for an arbitrary
`m` divisible by `1..k` is this lemma plus the corresponding divisibility splitting.

Proof (the proof of the Claim in Lemma 2.2 of the paper):
1. **Local criterion.** `GeneratedInDegreeOne` is `∀ l > 0, Epi (mulPowOne l)`. The target `S_{lm}` is
   quasi-coherent, and `Modules.epi_of_surjective_sections_affine_cover` (surjective on sections over an affine
   cover ⇒ epi; internally `epi_iff_locally_surjective_sections` and the quasi-coherent localization
   `exists_pow_smul_eq_map_basicOpen`) reduces the problem to: on every chart `C = 𝒜.chart i`, the section map
   of `mulPowOne l` is surjective.
2. **Algebraic core on a chart** (`symm_mem_of_isWeightedHomogeneous_of_split`). For a weighted homogeneous
   polynomial `p` of weight `l·m` use `IsWeightedHomogeneous.induction_on`: `0` and sums are clear; a monomial
   `monomial d c` is written by `hsplit` as `C c * ∏_j monomial (f j) 1` (`monomial_sum_index`), each factor of
   weight `m`, whose preimage under `(𝒜.equiv i).symm` lies in the piece `1*m`
   (`WeightedPolynomialAtlas.symm_mem`), i.e. is of the form `ofPiece (1*m) (b j)`.
3. **Lifting to sections of the tensor power** (`exists_tensorPow_section_of_chart_of_split`). The image `P`
   (inside the sections ring `S.sectionsRing C`) is an additive subgroup; `exists_tensorPow_section_prod` and
   `sectionsUnitHom_mul_ofPiece` show that `P` contains all `unit c · ∏_j ofPiece (1*m) (b j)`; given
   `t ∈ Γ(C, S_{lm})`, `ofPiece t` is, via the chart isomorphism, a homogeneous polynomial of weight `l·m`,
   step 2 gives `ofPiece t ∈ P`, and injectivity of `ofPiece` gives a preimage of `t`.
4. The charts cover `X`, and step 1 gives the global epimorphism.

Neither `Fintype σ` nor `Nonempty σ` is needed.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

namespace AlgebraicGeometry.Scheme.GradedQCAlgebra

variable {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra)

/-- **Algebraic core (splitting-property version)**: let `P` be an additive subgroup of the sections ring
`S.sectionsRing C` of the chart `C = 𝒜.chart i` containing all `sectionsUnitHom c * ∏_{j<ℓ} ofPiece (1*m) (b j)`.
If `hsplit` holds, then every weighted homogeneous polynomial of weight `ℓ m` lands in `P` under
`(𝒜.equiv i).symm`.
Proof: by `IsWeightedHomogeneous.induction_on`: `0` and sums are clear; a monomial `monomial d c` is written by
`hsplit` as `C c * ∏_j monomial (f j) 1`, each factor of weight `m`, whose preimage lies in the piece `1*m`
(`WeightedPolynomialAtlas.symm_mem`), i.e. is of the form `ofPiece (1*m) (b j)`. -/
theorem symm_mem_of_isWeightedHomogeneous_of_split {σ : Type u} (w : σ → ℕ) (m : ℕ)
    (hsplit : ∀ (e : σ →₀ ℕ) (l : ℕ), 1 ≤ l → Finsupp.weight w e = l * m →
      ∃ f : Fin l → (σ →₀ ℕ), (∀ j, Finsupp.weight w (f j) = m) ∧ ∑ j, f j = e)
    (𝒜 : S.toGradedAffineAlgebra.WeightedPolynomialAtlas w) (i : 𝒜.I) (ℓ : ℕ) (hℓ : 1 ≤ ℓ)
    (P : AddSubgroup (S.sectionsRing (𝒜.chart i).toOpens))
    (hP : ∀ (c : Γ(X, (𝒜.chart i).toOpens))
      (b : Fin ℓ → S.sectionsPiece (𝒜.chart i).toOpens (1 * m)),
      S.sectionsUnitHom (𝒜.chart i).toOpens c *
        ∏ j, S.ofPiece (𝒜.chart i).toOpens (1 * m) (b j) ∈ P)
    (p : MvPolynomial σ Γ(X, (𝒜.chart i).toOpens))
    (hp : p.IsWeightedHomogeneous w (ℓ * m)) :
    (𝒜.equiv i).symm p ∈ P := by
  classical
  induction hp using MvPolynomial.IsWeightedHomogeneous.induction_on with
  | zero => rw [map_zero]; exact P.zero_mem
  | add p q _ _ ihp ihq => rw [map_add]; exact P.add_mem ihp ihq
  | monomial d c hd =>
    obtain ⟨f, hf, hsum⟩ := hsplit d ℓ hℓ hd
    rw [← hsum, MvPolynomial.monomial_sum_index, map_mul, map_prod, S.atlas_equiv_symm_C w 𝒜 i c]
    have hmem : ∀ j, (𝒜.equiv i).symm (MvPolynomial.monomial (f j) 1) ∈
        S.sectionsGrading (𝒜.chart i).toOpens (1 * m) :=
      fun j => 𝒜.symm_mem i (MvPolynomial.isWeightedHomogeneous_monomial w (f j) 1
        ((hf j).trans (Nat.one_mul _).symm))
    have hex : ∀ j, ∃ b : S.sectionsPiece (𝒜.chart i).toOpens (1 * m),
        S.ofPiece (𝒜.chart i).toOpens (1 * m) b =
          (𝒜.equiv i).symm (MvPolynomial.monomial (f j) 1) :=
      fun j => hmem j
    choose b hb using hex
    rw [show (∏ j, (𝒜.equiv i).symm (MvPolynomial.monomial (f j) 1)) =
        ∏ j, S.ofPiece (𝒜.chart i).toOpens (1 * m) (b j) from
      Finset.prod_congr rfl fun j _ => (hb j).symm]
    exact hP c b

/-- **Surjectivity on a chart (splitting-property version)**: for a chart `C = 𝒜.chart i` and `ℓ ≥ 1`, if
`hsplit` holds, the section map on `C` of `mulPowOne ℓ : (S^{(m)}_1)^{⊗ℓ} → S^{(m)}_ℓ` of the Veronese algebra
`S^{(m)}` is surjective.
Proof: the image `P` (inside the sections ring) is an additive subgroup; by `exists_tensorPow_section_prod` and
`sectionsUnitHom_mul_ofPiece`, `P` contains all `unit c · ∏ ofPiece (b j)`; `ofPiece t` lies in the piece `ℓ m`
and is, via the chart isomorphism, a homogeneous polynomial of weight `ℓ m`, so
`symm_mem_of_isWeightedHomogeneous_of_split` gives `ofPiece t ∈ P`; injectivity of `ofPiece` gives a preimage. -/
theorem exists_tensorPow_section_of_chart_of_split {σ : Type u} (w : σ → ℕ) (m : ℕ)
    (hsplit : ∀ (e : σ →₀ ℕ) (l : ℕ), 1 ≤ l → Finsupp.weight w e = l * m →
      ∃ f : Fin l → (σ →₀ ℕ), (∀ j, Finsupp.weight w (f j) = m) ∧ ∑ j, f j = e)
    (𝒜 : S.toGradedAffineAlgebra.WeightedPolynomialAtlas w) (i : 𝒜.I) (ℓ : ℕ) (hℓ : 1 ≤ ℓ)
    (t : Γ((S.veronese m).part ℓ, (𝒜.chart i).toOpens)) :
    ∃ y : Γ(AlgebraicGeometry.Scheme.Modules.tensorPow ((S.veronese m).part 1) ℓ,
        (𝒜.chart i).toOpens),
      ((S.veronese m).mulPowOne ℓ).app (𝒜.chart i).toOpens y = t := by
  classical
  let Φ : Γ(AlgebraicGeometry.Scheme.Modules.tensorPow
      ((S.veronese m).part 1) ℓ, (𝒜.chart i).toOpens) →
      S.sectionsRing (𝒜.chart i).toOpens :=
    fun y => S.ofPiece (𝒜.chart i).toOpens (ℓ * m)
      (((S.veronese m).mulPowOne ℓ).app (𝒜.chart i).toOpens y)
  let P : AddSubgroup (S.sectionsRing (𝒜.chart i).toOpens) :=
    { carrier := Set.range Φ
      zero_mem' := ⟨0, by
        show S.ofPiece (𝒜.chart i).toOpens (ℓ * m)
          (((S.veronese m).mulPowOne ℓ).app (𝒜.chart i).toOpens 0) = 0
        rw [map_zero]
        exact map_zero (DirectSum.of (S.sectionsPiece (𝒜.chart i).toOpens) (ℓ * m))⟩
      add_mem' := by
        rintro _ _ ⟨y₁, rfl⟩ ⟨y₂, rfl⟩
        refine ⟨y₁ + y₂, ?_⟩
        show S.ofPiece (𝒜.chart i).toOpens (ℓ * m)
          (((S.veronese m).mulPowOne ℓ).app (𝒜.chart i).toOpens (y₁ + y₂)) = _
        rw [map_add]
        exact map_add (DirectSum.of (S.sectionsPiece (𝒜.chart i).toOpens) (ℓ * m)) _ _
      neg_mem' := by
        rintro _ ⟨y, rfl⟩
        refine ⟨-y, ?_⟩
        show S.ofPiece (𝒜.chart i).toOpens (ℓ * m)
          (((S.veronese m).mulPowOne ℓ).app (𝒜.chart i).toOpens (-y)) = _
        rw [map_neg]
        exact map_neg (DirectSum.of (S.sectionsPiece (𝒜.chart i).toOpens) (ℓ * m)) _ }
  have hP : ∀ (c : Γ(X, (𝒜.chart i).toOpens))
      (b : Fin ℓ → S.sectionsPiece (𝒜.chart i).toOpens (1 * m)),
      S.sectionsUnitHom (𝒜.chart i).toOpens c *
        ∏ j, S.ofPiece (𝒜.chart i).toOpens (1 * m) (b j) ∈ P := by
    intro c b
    obtain ⟨y, hy⟩ := S.exists_tensorPow_section_prod m (𝒜.chart i).toOpens ℓ b
    refine ⟨c • y, ?_⟩
    show S.ofPiece (𝒜.chart i).toOpens (ℓ * m)
      (((S.veronese m).mulPowOne ℓ).app (𝒜.chart i).toOpens (c • y)) = _
    rw [← hy, AlgebraicGeometry.Scheme.Modules.Hom.app_smul]
    exact (S.sectionsUnitHom_mul_ofPiece (𝒜.chart i).toOpens c _).symm
  have ht : S.ofPiece (𝒜.chart i).toOpens (ℓ * m) t ∈
      S.sectionsGrading (𝒜.chart i).toOpens (ℓ * m) := ⟨t, rfl⟩
  have hhom : (𝒜.equiv i (S.ofPiece (𝒜.chart i).toOpens (ℓ * m) t)).IsWeightedHomogeneous w (ℓ * m) :=
    𝒜.equiv_isWeightedHomogeneous i ht
  obtain ⟨y, hy⟩ := S.symm_mem_of_isWeightedHomogeneous_of_split w m hsplit 𝒜 i ℓ hℓ P hP _ hhom
  refine ⟨y, S.ofPiece_injective (𝒜.chart i).toOpens (ℓ * m) ?_⟩
  exact hy.trans ((𝒜.equiv i).symm_apply_apply _)

end AlgebraicGeometry.Scheme.GradedQCAlgebra

/-- For a graded algebra sheaf with a weighted polynomial atlas satisfying the weight-`m` splitting property
`hsplit`, the `m`-th Veronese algebra is generated in degree one.
Proof: unfold `GeneratedInDegreeOne` for each `ℓ ≥ 1`; the target `S_{ℓm}` is quasi-coherent, and
`Modules.epi_of_surjective_sections_affine_cover` reduces to surjectivity on sections over the charts, which is
`exists_tensorPow_section_of_chart_of_split` (see the module docstring). -/
theorem AlgebraicGeometry.Scheme.GradedQCAlgebra.veronese_generatedInDegreeOne_of_atlas_of_split
    {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra)
    {σ : Type u} (w : σ → ℕ) (m : ℕ)
    (hsplit : ∀ (e : σ →₀ ℕ) (l : ℕ), 1 ≤ l → Finsupp.weight w e = l * m →
      ∃ f : Fin l → (σ →₀ ℕ), (∀ j, Finsupp.weight w (f j) = m) ∧ ∑ j, f j = e)
    (atlas : S.toGradedAffineAlgebra.WeightedPolynomialAtlas w) :
    (S.veronese m).GeneratedInDegreeOne := by
  intro ℓ hℓ
  have : ((S.veronese m).part ℓ).IsQuasicoherent := (S.veronese m).quasicoherent ℓ
  exact AlgebraicGeometry.Scheme.Modules.epi_of_surjective_sections_affine_cover _ atlas.chart
    atlas.covers
    (fun i t => S.exists_tensorPow_section_of_chart_of_split w m hsplit atlas i ℓ hℓ t)

end
