import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Cohomology.ExtendByZero.TopcatSheafOpenClosedFunctors
import MiyaokaMori.AlgebraicGeometry.Cohomology.Basic.Stacks02uzExactAux

/-! # Bookkeeping for Stacks 02UX (vanishing above a degree; jointly epimorphic families)

Generic facts used to assemble Stacks 02UX (reduction of `H^p(X, F) = 0` for all abelian sheaves `F` to
the sheaves `j_!ℤ_U`) from its leaves:
* the third two-out-of-three statement along the long exact `Ext` sequence of a short exact sequence
  (`H^n X₂ = 0` and `H^{n+1} X₁ = 0` imply `H^n X₃ = 0`; Mathlib `Abelian.Ext.covariant_sequence_exact₃`),
  complementing `subsingleton_H_X₁/X₂_of_shortExact` of `Stacks02uzExactAux.lean`;
* `HVanishAbove d F` (`H^p F = 0` for all `p > d`) and its stability under isomorphism, zero objects, and the
  three two-out-of-three moves;
* `IsJointlyEpi φ` for a family `φ i : X i ⟶ Y` (the categorical form of "`Y` is generated by the sections
  `φ i`", exactly the hypothesis `hgen` of `TopCat.Sheaf.exists_filtration_subsheaf_constant`, Stacks 0A38):
  an empty jointly epimorphic family forces `Y = 0`; and if `φ : Fin (n+1) → _` is jointly epimorphic then the
  quotient `Y / im(φ 0)` is generated by the images of `φ 1, …, φ n` (the dévissage step of Stacks 02UX);
* `extendByZeroConstant U = j_!ℤ_U` (`ℤ_U` the constant sheaf with value `ULift ℤ`) and `FinGenerated F`
  ("`F` is generated by finitely many sections over opens": a jointly epimorphic family
  `j_{a!}ℤ_{U_a} ⟶ F`, `a : Fin r`).

Source: Stacks 02UX (cohomology-lemma-vanishing-generated-one-section), second paragraph. -/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w w' u₁ v₁ u₂

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace

noncomputable section

namespace CategoryTheory.Sheaf

variable {C : Type u} [Category.{v} C] {J : GrothendieckTopology C}
  [HasSheafify J AddCommGrpCat.{w}] [HasExt.{w'} (Sheaf J AddCommGrpCat.{w})]

/-- For a short exact sequence `0 → X₁ → X₂ → X₃ → 0` of abelian sheaves, `H^{n₀} X₂ = 0` and
`H^{n₀+1} X₁ = 0` imply `H^{n₀} X₃ = 0` (exactness of `H^{n₀} X₂ → H^{n₀} X₃ → H^{n₀+1} X₁`). -/
theorem subsingleton_H_X₃_of_shortExact {S : ShortComplex (Sheaf J AddCommGrpCat.{w})}
    (hS : S.ShortExact) (n₀ n₁ : ℕ) (h : n₀ + 1 = n₁)
    [Subsingleton (H S.X₂ n₀)] [Subsingleton (H S.X₁ n₁)] : Subsingleton (H S.X₃ n₀) := by
  refine subsingleton_of_forall_eq 0 fun x => ?_
  obtain ⟨x₂, hx₂⟩ := Abelian.Ext.covariant_sequence_exact₃ _ hS x h (Subsingleton.elim _ _)
  rw [← hx₂, Subsingleton.elim x₂ 0]
  simp

/-- `H^p F = 0` for every `p > d`. -/
def HVanishAbove (d : ℕ) (F : Sheaf J AddCommGrpCat.{w}) : Prop :=
  ∀ p : ℕ, d < p → Subsingleton (H F p)

theorem hVanishAbove_of_iso {F G : Sheaf J AddCommGrpCat.{w}} (e : F ≅ G) (d : ℕ)
    (hF : HVanishAbove d F) : HVanishAbove d G := fun p hp =>
  haveI := hF p hp
  subsingleton_H_of_iso e p

theorem hVanishAbove_of_isZero {F : Sheaf J AddCommGrpCat.{w}} (hF : IsZero F) (d : ℕ) :
    HVanishAbove d F := fun p _ => subsingleton_H_of_isZero hF p

/-- Two-out-of-three, middle term. -/
theorem hVanishAbove_X₂_of_shortExact {S : ShortComplex (Sheaf J AddCommGrpCat.{w})}
    (hS : S.ShortExact) (d : ℕ) (h₁ : HVanishAbove d S.X₁) (h₃ : HVanishAbove d S.X₃) :
    HVanishAbove d S.X₂ := fun p hp =>
  haveI := h₁ p hp
  haveI := h₃ p hp
  subsingleton_H_X₂_of_shortExact hS p

/-- Two-out-of-three, right term (uses `H^{p+1} X₁ = 0`, available since `p + 1 > d`). -/
theorem hVanishAbove_X₃_of_shortExact {S : ShortComplex (Sheaf J AddCommGrpCat.{w})}
    (hS : S.ShortExact) (d : ℕ) (h₁ : HVanishAbove d S.X₁) (h₂ : HVanishAbove d S.X₂) :
    HVanishAbove d S.X₃ := fun p hp =>
  haveI := h₂ p hp
  haveI := h₁ (p + 1) (by omega)
  subsingleton_H_X₃_of_shortExact hS p (p + 1) rfl

end CategoryTheory.Sheaf

namespace CategoryTheory

variable {A : Type u₁} [Category.{v₁} A]

/-- A family `φ i : X i ⟶ Y` is jointly epimorphic: two morphisms out of `Y` agreeing after every `φ i`
are equal. (For `Y` a sheaf and `X i = j_!ℤ_{U_i}` this says "`Y` is generated by the sections `φ i`".) -/
def IsJointlyEpi {ι : Type u₂} {Y : A} {X : ι → A} (φ : ∀ i, X i ⟶ Y) : Prop :=
  ∀ {T : A} (g h : Y ⟶ T), (∀ i, φ i ≫ g = φ i ≫ h) → g = h

/-- A single epimorphism is a jointly epimorphic family (indexed by `Fin 1`). -/
theorem isJointlyEpi_of_epi {X Y : A} (f : X ⟶ Y) [Epi f] :
    IsJointlyEpi (fun _ : Fin 1 => f) := fun _ _ hgh => (cancel_epi f).mp (hgh 0)

/-- An empty jointly epimorphic family forces the target to be a zero object (`𝟙 Y = 0`). -/
theorem isZero_of_isJointlyEpi_of_isEmpty [HasZeroMorphisms A] {ι : Type u₂} [IsEmpty ι] {Y : A}
    {X : ι → A} (φ : ∀ i, X i ⟶ Y) (hφ : IsJointlyEpi φ) : IsZero Y := by
  rw [IsZero.iff_id_eq_zero]
  exact hφ _ _ fun i => (IsEmpty.false i).elim

/-- **Dévissage step** (Stacks 02UX, second paragraph): if `φ : Fin (n+1) → _` generates `Y`, then the
quotient `Y / im(φ 0)` (the cokernel of `image.ι (φ 0)`) is generated by the images of `φ 1, …, φ n`. -/
theorem isJointlyEpi_succ_comp_cokernelπ [Abelian A] {n : ℕ} {Y : A} {X : Fin (n + 1) → A}
    (φ : ∀ a, X a ⟶ Y) (hφ : IsJointlyEpi φ) :
    IsJointlyEpi (fun a : Fin n => φ a.succ ≫ cokernel.π (image.ι (φ 0))) := by
  intro T g h hgh
  have h0 : φ 0 ≫ cokernel.π (image.ι (φ 0)) = 0 := by
    calc φ 0 ≫ cokernel.π (image.ι (φ 0))
        = factorThruImage (φ 0) ≫ image.ι (φ 0) ≫ cokernel.π (image.ι (φ 0)) := by
          rw [← Category.assoc, image.fac]
      _ = 0 := by rw [cokernel.condition, comp_zero]
  have hall : ∀ a, φ a ≫ (cokernel.π (image.ι (φ 0)) ≫ g) =
      φ a ≫ (cokernel.π (image.ι (φ 0)) ≫ h) := by
    intro a
    refine Fin.cases ?_ (fun a => ?_) a
    · rw [← Category.assoc, ← Category.assoc, h0, zero_comp, zero_comp]
    · rw [← Category.assoc, hgh a, Category.assoc]
  exact (cancel_epi (cokernel.π (image.ι (φ 0)))).mp (hφ _ _ hall)

end CategoryTheory

namespace TopCat.Sheaf

variable {X : TopCat.{u}}

/-- `j_!ℤ_U`: the extension by zero of the constant sheaf `ℤ_U` (value `ULift ℤ`) on the open `U`. -/
abbrev extendByZeroConstant (U : Opens X) :
    CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u} :=
  TopCat.Sheaf.extendByZero U
    ((CategoryTheory.constantSheaf (Opens.grothendieckTopology U) AddCommGrpCat.{u}).obj
      (AddCommGrpCat.of (ULift ℤ)))

/-- `F` is generated by finitely many sections over opens: there is a jointly epimorphic family
`j_{a!}ℤ_{U_a} ⟶ F` indexed by `Fin r` (a morphism `j_!ℤ_U ⟶ F` is the same as a section of `F` over `U`,
by the adjunctions `j_! ⊣ j^{-1}` and `ℤ_U ⊣ Γ(U, −)`). This is the hypothesis `hgen` of Stacks 0A38
(`TopCat.Sheaf.exists_filtration_subsheaf_constant`). -/
def FinGenerated (F : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}) : Prop :=
  ∃ (r : ℕ) (U : Fin r → Opens X) (φ : ∀ a, extendByZeroConstant (U a) ⟶ F), CategoryTheory.IsJointlyEpi φ

end TopCat.Sheaf

end
