import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Varieties.Basic.ClosedSubvariety
import MiyaokaMori.AlgebraicGeometry.Chow.Cycles.CycleGroup
import MiyaokaMori.AlgebraicGeometry.Varieties.Basic.Variety
import MiyaokaMori.AlgebraicGeometry.Varieties.Basic.VarietyLocallyNoetherian
import MiyaokaMori.AlgebraicGeometry.Divisors.Weil.PrincipalDivisor
import MiyaokaMori.AlgebraicGeometry.Chow.RationalEquivalence.RationalEquivalenceX
import MiyaokaMori.AlgebraicGeometry.Varieties.Dimension.SchemeDimension
import MiyaokaMori.AlgebraicGeometry.Varieties.Dimension.VarietyDimension
import MiyaokaMori.AlgebraicGeometry.Varieties.Basic.VarietyQcqs
import MiyaokaMori.AlgebraicGeometry.Chow.Pushforward.ClosedImmersionPushforwardRatEquiv
import MiyaokaMori.AlgebraicGeometry.Chow.ChernClass.FirstChernCapFundamentalCycle

/-! # Rational equivalence on a variety: Fulton's generators

Rational equivalence of `i`-cycles: the subgroup of `Z_i(X)` generated by the principal divisors on all
`(i+1)`-dimensional closed subvarieties `W`, pushed forward to `X` (Fulton, Intersection Theory, §1.3).
Since the Chow group has one definition (`AlgebraicGeometry.ChowGroup X.toScheme i`, with the subgroup
`ratEquivZero` of Stacks 02RW), Fulton's description is kept as a **theorem**: every Fulton generator
`ι_W* div(r)` lies in `ratEquivZero X.toScheme i`
(`ClosedSubvariety.properPushforward_principalDivisor_mem_ratEquivZero`), so Fulton's subgroup is
contained in the 02RW subgroup.

Proof: `W` is an integral scheme of dimension `i+1`, whose generic point `η` has height `i+1`
(`height_genericPoint_of_dimension_pos`); the principal cycle `div(r) = W.carrier.principalCycle r` is a
02RW generator on `W` centred at `η` (`isRatEquivGen_principalCycle`); the pushforward along the closed
immersion `W.ι` sends 02RW generators to 02RW generators
(`isRatEquivGen_properPushforward_of_isClosedImmersion`); a single generator lies in `ratEquivZero`
(`single_mem_ratEquivZero`). `(principalDivisor W.toVariety r).val` and `W.carrier.principalCycle r` are
definitionally equal.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- A generator of rational equivalence in the sense of Fulton §1.3 (the pushforward along `W.ι` of a
principal divisor `div(r)` on an `(i+1)`-dimensional closed subvariety `W`) is rationally trivial in the
sense of Stacks 02RW: `ι_W* div(r) ∈ ratEquivZero X i`. This is all that is needed to relate Fulton's
definition to the 02RW definition. -/
theorem ClosedSubvariety.properPushforward_principalDivisor_mem_ratEquivZero {k : Type u} [Field k]
    {X : Variety k} {i : ℕ} (W : ClosedSubvariety X) (hW : W.dimension = i + 1)
    (r : W.carrier.functionFieldˣ) :
    AlgebraicGeometry.AlgebraicCycle.properPushforward W.ι (principalDivisor W.toVariety r).val
      ∈ AlgebraicGeometry.ratEquivZero X.toScheme i := by
  have hgen := AlgebraicGeometry.isRatEquivGen_principalCycle (X := W.carrier)
    (AlgebraicGeometry.height_genericPoint_of_dimension_pos (X := W.carrier) hW) r
  exact AlgebraicGeometry.single_mem_ratEquivZero
    (MiyaokaMori.ClosedImmersionPushforward.isRatEquivGen_properPushforward_of_isClosedImmersion
      W.ι i _ _ hgen)

/-- The same fact as a membership in the subgroup of `Z_i(X)` by which `ChowGroup X i` is the quotient, for
direct use after `QuotientAddGroup.eq_iff_sub_mem` (e.g. in `capDivisor_single`). -/
theorem ClosedSubvariety.properPushforward_principalDivisor_mem_addSubgroupOf {k : Type u} [Field k]
    {X : Variety k} {i : ℕ} (W : ClosedSubvariety X) (hW : W.dimension = i + 1)
    (r : W.carrier.functionFieldˣ)
    (hmem : AlgebraicGeometry.AlgebraicCycle.properPushforward W.ι (principalDivisor W.toVariety r).val ∈ CycleGroup X i) :
    (⟨AlgebraicGeometry.AlgebraicCycle.properPushforward W.ι (principalDivisor W.toVariety r).val, hmem⟩ : CycleGroup X i)
      ∈ (AlgebraicGeometry.ratEquivZero X.toScheme i).addSubgroupOf
          (AlgebraicGeometry.cycleSubgroup X.toScheme i) :=
  AddSubgroup.mem_addSubgroupOf.mpr
    (ClosedSubvariety.properPushforward_principalDivisor_mem_ratEquivZero W hW r)

end
