import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffectiveCartierCanonicalSection
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.LineBundleNonvanishingLocus
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffCartierLineBundle
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.FrameLocus

/-! # Comparison lemmas between the two encodings of effective Cartier divisors

Comparison lemmas between the `EffCartier` interface and the `EffectiveCartierDivisor` interface:
  * `isLineBundle_iff_old`: `Scheme.Modules.IsLineBundle` is equivalent to `SheafOfModules.IsLineBundle`
    (the two definitions coincide);
  * `effCartierOfOld` / `effCartierToOld`: `EffectiveCartierDivisor` and `EffCartier` correspond with the
    same ideal sheaf (`rfl`);
  * `dualSheafSectionsEquivOld`: `Γ(U, dualSheaf M) ≃ₗ Γ(U, Modules.dual M)`, and
    `canonicalSection_eq_one`: the canonical section equals `1_D`;
  * `lineBundleToFound`: a packaged line bundle on a variety as a packaged line bundle on its scheme;
  * `frameLocus_eq_nonvanishingLocus`: the frame locus of a section of a line bundle is its
    nonvanishing locus.
Note: when both interfaces are imported, the dot notation `M.IsLineBundle` (for `M : X.Modules`)
resolves to `Scheme.Modules.IsLineBundle`; this file writes full names throughout.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory Opposite TopologicalSpace AlgebraicGeometry

noncomputable section

namespace MiyaokaMori.Found.CartierBridge

variable {X : Scheme.{u}}

/-- The two line bundle classes are equivalent (their definitions coincide). -/
theorem isLineBundle_iff_old (M : X.Modules) :
    AlgebraicGeometry.Scheme.Modules.IsLineBundle M ↔ SheafOfModules.IsLineBundle M :=
  ⟨fun h ↦ ⟨h.1⟩, fun h ↦ ⟨h.1⟩⟩

theorem isLineBundle_of_old (M : X.Modules) [h : SheafOfModules.IsLineBundle M] :
    AlgebraicGeometry.Scheme.Modules.IsLineBundle M := (isLineBundle_iff_old M).mpr h

theorem old_of_isLineBundle (M : X.Modules) [h : AlgebraicGeometry.Scheme.Modules.IsLineBundle M] :
    SheafOfModules.IsLineBundle M := (isLineBundle_iff_old M).mp h

/-- The two inclusion-map components agree. -/
theorem idealIota_eq_old (I : X.IdealSheafData) (W : X.Opens) :
    AlgebraicGeometry.Scheme.EffCartier.idealIota I W =
      MiyaokaMori.EffectiveCartierCanonicalSection.iota I W := rfl

/-- An ideal sheaf that is a line bundle is locally generated by a nonzerodivisor. -/
theorem isInvertibleIdeal_of_old (D : EffectiveCartierDivisor X) :
    MiyaokaMori.Statement.IsInvertibleIdeal D.idealSheaf := by
  intro x
  have : SheafOfModules.IsLineBundle D.idealSheaf.toModules := D.isLineBundle
  obtain ⟨W, -, hxW, f, hf⟩ :=
    MiyaokaMori.EffectiveCartierCanonicalSection.exists_frame_le D.idealSheaf.toModules
      (U := ⊤) (p := x) trivial
  obtain ⟨_, ⟨W₁, hW₁, rfl⟩, hxW₁, hW₁W⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open hxW W.isOpen
  have hf₁ := hf.restrict hW₁W
  exact ⟨⟨W₁, hW₁⟩, hxW₁, _, fun r hr ↦ hf₁.regular r (by rwa [mul_comm]), hf₁.ideal_eq hW₁⟩

/-- An `EffectiveCartierDivisor` as an `EffCartier`. -/
def effCartierOfOld (D : EffectiveCartierDivisor X) : X.EffCartier :=
  ⟨D.idealSheaf, isInvertibleIdeal_of_old D⟩

@[simp] theorem effCartierOfOld_ideal (D : EffectiveCartierDivisor X) :
    (effCartierOfOld D).ideal = D.idealSheaf := rfl

/-- An `EffCartier` as an `EffectiveCartierDivisor`. Since `EffectiveCartierDivisor X` is an alias of
`X.EffCartier`, this is the identity; the name and type are kept for downstream users. -/
def effCartierToOld (D : X.EffCartier) : EffectiveCartierDivisor X := D

@[simp] theorem effCartierToOld_idealSheaf (D : X.EffCartier) :
    (effCartierToOld D).idealSheaf = D.ideal := rfl

@[simp] theorem effCartierOfOld_toOld (D : X.EffCartier) : effCartierOfOld (effCartierToOld D) = D :=
  AlgebraicGeometry.Scheme.EffCartier.ext rfl

/-- The two closed subschemes agree. -/
theorem toScheme_eq_old (D : EffectiveCartierDivisor X) :
    (effCartierOfOld D).toScheme = D.toScheme := rfl

/-- Sections of `dualSheaf M` are isomorphic to sections of the sheafified dual `Modules.dual M`. -/
def dualSheafSectionsEquivOld (M : X.Modules) (U : X.Opens) :
    Γ(AlgebraicGeometry.Scheme.Modules.dualSheaf M, U) ≃ₗ[Γ(X, U)]
      Γ(AlgebraicGeometry.Scheme.Modules.dual M, U) :=
  (AlgebraicGeometry.Scheme.Modules.dualSheafSections M U).trans
    (MiyaokaMori.ModuleDualSectionEquiv.sectionEquiv M U)

/-- The canonical section equals `1_D`: `O_X(D)` is `EffCartier.sheaf` (no sheafification), so the two
canonical sections coincide. -/
theorem canonicalSection_eq_one (D : EffectiveCartierDivisor X) :
    D.canonicalSection = (effCartierOfOld D).one := rfl

/-- A packaged line bundle on a variety as a packaged line bundle on the underlying scheme. -/
def lineBundleToFound {k : Type u} [Field k] {V : Variety k} (L : _root_.LineBundle V) :
    AlgebraicGeometry.Scheme.LineBundle V.toScheme :=
  @AlgebraicGeometry.Scheme.LineBundle.mk _ L.toModules
    ((isLineBundle_iff_old _).mpr (LineBundle.toModules_isLineBundle L))

/-- The frame locus of a global section `s` of a line bundle equals its nonvanishing locus `X_s`
(Stacks 01CY).
* `⊆`: if `s` is a frame on some `W ∋ x`, then the germ of `s` is not in `𝔪_x L_x`
  (`IsFrame.germ_notMem_maximalIdeal_smul`, Nakayama in one variable).
* `⊇`: take a frame `(W, e)` at `x` and let `f := coord_e(s|_W)`, so `s|_W = f • e` and
  `s_x = f_x • e_x`. If `f_x` were not a unit then `f_x ∈ 𝔪_x` and `s_x ∈ 𝔪_x L_x`, a contradiction;
  so `f_x` is a unit, i.e. `x ∈ X.basicOpen f`. On `V := X.basicOpen f` the restriction of `f` is a
  unit (`RingedSpace.isUnit_res_basicOpen`) and the coordinate of `s|_V` in the frame `e|_V` is `f|_V`
  (`coord_unique`), so `s|_V` is a frame by `IsFrame.of_isUnit_coord`, and `x ∈ frameLocus`. -/
theorem frameLocus_eq_nonvanishingLocus (L : X.Modules) [hL : SheafOfModules.IsLineBundle L]
    (s : Γ(L, ⊤)) :
    AlgebraicGeometry.Scheme.Modules.frameLocus L s =
      @AlgebraicGeometry.Scheme.Modules.nonvanishingLocus X L hL s := by
  have : AlgebraicGeometry.Scheme.Modules.IsLineBundle L := isLineBundle_of_old L
  apply TopologicalSpace.Opens.ext
  ext x
  constructor
  · -- if s is a frame at x, the germ of s is not in 𝔪_x L_x
    intro hx
    obtain ⟨W, hxW, hfr⟩ := AlgebraicGeometry.Scheme.Modules.mem_frameLocus.mp hx
    have h0 : L.presheaf.germ W x hxW (L.res le_top s) = L.presheaf.germ ⊤ x trivial s :=
      TopCat.Presheaf.germ_res_apply _ _ _ _ _
    have := AlgebraicGeometry.Scheme.Modules.IsFrame.germ_notMem_maximalIdeal_smul hfr hxW
    rwa [h0] at this
  · -- conversely, take a frame (W, e) at x with s|_W = f • e; the germ condition forces f_x to be a
    -- unit, so s is a frame on X.basicOpen f
    intro hx
    obtain ⟨W, hxW, e, hf⟩ := AlgebraicGeometry.Scheme.Modules.exists_frame L x
    set f : Γ(X, W) := hf.coord le_rfl (L.res le_top s) with hfdef
    have hse : L.res le_top s = f • e := by
      have h := hf.coord_smul_frame le_rfl (L.res le_top s)
      rw [AlgebraicGeometry.Scheme.Modules.res_self] at h
      exact h.symm
    have hgerm : L.presheaf.germ ⊤ x trivial s =
        X.presheaf.germ W x hxW f • L.presheaf.germ W x hxW e := by
      have h0 : L.presheaf.germ W x hxW (L.res le_top s) = L.presheaf.germ ⊤ x trivial s :=
        TopCat.Presheaf.germ_res_apply _ _ _ _ _
      rw [← h0, hse, AlgebraicGeometry.Scheme.Modules.germ_smul']
    -- f is a unit at x
    have hunit : IsUnit (X.presheaf.germ W x hxW f) := by
      by_contra hnu
      refine hx ?_
      have hmem : (X.presheaf.germ W x hxW f) •
          (show AlgebraicGeometry.Scheme.Modules.stalk L x from L.presheaf.germ W x hxW e) ∈
          (IsLocalRing.maximalIdeal (X.presheaf.stalk x)) •
            (⊤ : Submodule (X.presheaf.stalk x)
              (AlgebraicGeometry.Scheme.Modules.stalk L x)) :=
        Submodule.smul_mem_smul ((IsLocalRing.mem_maximalIdeal _).mpr hnu) Submodule.mem_top
      rw [hgerm]
      exact hmem
    -- on V = X.basicOpen f, f is a unit, so s|_V is a frame
    set V : X.Opens := X.basicOpen f with hVdef
    have hVW : V ≤ W := X.basicOpen_le f
    have hxV : x ∈ V := (X.mem_basicOpen f x hxW).mpr hunit
    have hfV := hf.restrict hVW
    have hresu : IsUnit (X.presheaf.map (homOfLE hVW).op f) :=
      X.toRingedSpace.isUnit_res_basicOpen f
    have hcoord : hfV.coord le_rfl (L.res hVW (L.res le_top s))
        = X.presheaf.map (homOfLE hVW).op f := by
      refine hfV.coord_unique le_rfl _ _ ?_
      rw [AlgebraicGeometry.Scheme.Modules.res_self, hse,
        AlgebraicGeometry.Scheme.Modules.res_smul]
    have hframe : AlgebraicGeometry.Scheme.Modules.IsFrame L V (L.res le_top s) := by
      have h := AlgebraicGeometry.Scheme.Modules.IsFrame.of_isUnit_coord hfV (by
        rw [hcoord]; exact hresu)
      rwa [AlgebraicGeometry.Scheme.Modules.res_res] at h
    exact AlgebraicGeometry.Scheme.Modules.mem_frameLocus.mpr ⟨V, hxV, hframe⟩

end MiyaokaMori.Found.CartierBridge

end
