import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.IdealSheaf.IdealSheafToModules
import MiyaokaMori.AlgebraicGeometry.Modules.Dual.DualSheaf
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.RegularSection
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.NonZeroDivisorRes

/-! # Effective Cartier divisors

An **effective Cartier divisor** `X.EffCartier` on a scheme `X` is a quasi-coherent ideal sheaf
(Mathlib's `IdealSheafData`) that is locally generated by a single nonzerodivisor
(`MiyaokaMori.Statement.IsInvertibleIdeal`; the local characterization of Stacks 01WQ, 01WS).
  * Type level: equality is equality of ideal sheaves (`EffCartier.ext`); the closed subscheme
    `D.toScheme` with its immersion `D.ι`; the zero divisor `0`; the pullback `D.comap f h` along a
    morphism (`h`: `f⁻¹I·O` is again invertible — the condition of Stacks 01WV; no fallback).
  * Interface: `D.Presentation` is a triple (line bundle `L`, section `s`, "the ideal sheaf of `D` is
    the zero ideal of `(L, s)`"). Theorems about `D` are stated for an arbitrary presentation.
  * The canonical presentation: `D.sheaf = O_X(D) := (I_D)^∨` (`dualSheaf`, without sheafification),
    `D.one = 1_D :=` the inclusion `I_D ↪ O_X` itself, and `dualPair D.one h x = iota x` is `rfl`.
Design: all computations (orders, lengths, Weil cycles, intersection numbers) need local equations,
so the local equation is put into the definition (a ring-theoretic condition, checkable on affine
opens), and the line bundle property of `I_D` and `O_X(D)` becomes a theorem. The pair `(L, s)` has
no good notion of equality (one would have to quotient by isomorphism), so it serves as the
`Presentation` interface rather than as the basic encoding.
Sources: Stacks 01WQ, 01WR, 01WS, 01WV, 01WX; the effective Cartier divisors in the proof of
Proposition 2.4 of the paper.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace

noncomputable section

namespace AlgebraicGeometry.Scheme

set_option backward.isDefEq.respectTransparency false

/-- An effective Cartier divisor: a quasi-coherent ideal sheaf locally generated by one nonzerodivisor. -/
@[ext]
structure EffCartier (X : Scheme.{u}) where
  /-- The ideal sheaf `I_D` of `D`. -/
  ideal : X.IdealSheafData
  /-- `I_D` is locally generated by a nonzerodivisor. -/
  isInvertible : MiyaokaMori.Statement.IsInvertibleIdeal ideal

namespace EffCartier

variable {X Y : Scheme.{u}}

/-- `D` as a closed subscheme. -/
abbrev toScheme (D : X.EffCartier) : Scheme.{u} := D.ideal.subscheme

/-- The closed immersion `D ↪ X`. -/
abbrev ι (D : X.EffCartier) : D.toScheme ⟶ X := D.ideal.subschemeι

/-- Local equations: every point has an affine open neighbourhood `U` and a nonzerodivisor `a` with
`I_D(U) = (a)`. -/
theorem exists_localEquation (D : X.EffCartier) (x : X) :
    ∃ (U : X.affineOpens) (_ : x ∈ U.1) (a : Γ(X, U)), a ∈ nonZeroDivisors Γ(X, U) ∧
      D.ideal.ideal U = Ideal.span {a} := by
  obtain ⟨U, hx, a, ha, hI⟩ := D.isInvertible x
  exact ⟨U, hx, a, mem_nonZeroDivisors_iff_right.mpr fun r hr => ha r (by rwa [mul_comm]), hI⟩

/-- The zero divisor: `I = O_X`. -/
instance : Zero X.EffCartier :=
  ⟨⟨⊤, fun x => by
    obtain ⟨_, ⟨U, hU, rfl⟩, hxU, -⟩ :=
      X.isBasis_affineOpens.exists_subset_of_mem_open (Set.mem_univ x) isOpen_univ
    exact ⟨⟨U, hU⟩, hxU, 1, fun r hr => by simpa using hr, by simp [IdealSheafData.ideal_top]⟩⟩⟩

@[simp] theorem zero_ideal : (0 : X.EffCartier).ideal = ⊤ := rfl

/-- Pullback along `f` (Stacks 01WV): requires that `f⁻¹I_D·O_X` is again locally generated by a
nonzerodivisor; no fallback. -/
def comap (D : Y.EffCartier) (f : X ⟶ Y)
    (h : MiyaokaMori.Statement.IsInvertibleIdeal (D.ideal.comap f)) : X.EffCartier :=
  ⟨D.ideal.comap f, h⟩

@[simp] theorem comap_ideal (D : Y.EffCartier) (f : X ⟶ Y)
    (h : MiyaokaMori.Statement.IsInvertibleIdeal (D.ideal.comap f)) :
    (D.comap f h).ideal = D.ideal.comap f := rfl

/-- A presentation of `D`: a line bundle `L` and a section `s` such that `I_D` is the zero ideal of
`(L, s)`. -/
structure Presentation (D : X.EffCartier) where
  /-- The line bundle `L ≅ O_X(D)`. -/
  bundle : X.Modules
  [isLineBundle : bundle.IsLineBundle]
  /-- The section `s`, corresponding to `1_D`. -/
  sec : Γ(bundle, ⊤)
  /-- On every affine open with a frame, `I_D` is generated by the coordinate of `s`. -/
  isZeroIdeal : Modules.IsZeroIdeal D.ideal bundle sec

attribute [instance] Presentation.isLineBundle

/-- A divisor is determined by any of its presentations. -/
theorem Presentation.ideal_eq {D E : X.EffCartier} (P : D.Presentation) (Q : E.Presentation)
    (hb : P.bundle = Q.bundle) (hs : HEq P.sec Q.sec) : D = E := by
  obtain ⟨L, s, hP⟩ := P
  obtain ⟨L', s', hQ⟩ := Q
  obtain rfl : L = L' := hb
  obtain rfl : s = s' := eq_of_heq hs
  exact EffCartier.ext (Modules.IsZeroIdeal.unique hP hQ)

section Canonical

/-- The inclusion `I ↪ O_X`. -/
abbrev idealIncl (I : X.IdealSheafData) : I.toModules ⟶ SheafOfModules.unit X.ringCatSheaf :=
  kernel.ι (SheafOfModules.unitToPushforwardObjUnit I.subschemeι.toRingCatSheafHom)

/-- The component of the inclusion on an open `W`, as a `Γ(X, W)`-linear map. -/
def idealIota (I : X.IdealSheafData) (W : X.Opens) : Γ(I.toModules, W) →ₗ[Γ(X, W)] Γ(X, W) where
  toFun := fun x => (idealIncl I).val.app (op W) x
  map_add' := fun x y => map_add _ x y
  map_smul' := fun r x => ((idealIncl I).val.app (op W)).hom.map_smul r x

theorem idealIota_map (I : X.IdealSheafData) {W' W : X.Opens} (i : W' ⟶ W) (x : Γ(I.toModules, W)) :
    idealIota I W' (I.toModules.presheaf.map i.op x) = X.presheaf.map i.op (idealIota I W x) :=
  PresheafOfModules.naturality_apply (idealIncl I).val i.op x

theorem idealIota_injective (I : X.IdealSheafData) (W : X.Opens) :
    Function.Injective (idealIota I W) := by
  have : Mono ((SheafOfModules.evaluation X.ringCatSheaf (op W)).map (idealIncl I)) := inferInstance
  exact (ModuleCat.mono_iff_injective _).mp this

/-- On an affine open, the image of the inclusion is the ideal `I(U)`. -/
theorem range_idealIota (I : X.IdealSheafData) (U : X.affineOpens) :
    Set.range (idealIota I U.1) = (I.ideal U : Set Γ(X, U)) :=
  I.range_toModules_ι_app U

/-- `O_X(D) := I_D^∨`; sections are compatible families of local functionals on `I_D` (no
sheafification). -/
def sheaf (D : X.EffCartier) : X.Modules := Modules.dualSheaf D.ideal.toModules

/-- The canonical section `1_D ∈ Γ(X, O_X(D))`: the inclusion `I_D ↪ O_X`. -/
def one (D : X.EffCartier) : Γ(D.sheaf, ⊤) :=
  (Modules.dualSheafSections D.ideal.toModules ⊤).symm
    ⟨fun V => idealIota D.ideal V.left, fun _ _ i x => idealIota_map D.ideal i.left x⟩

/-- Evaluating `1_D` is the inclusion map (`rfl`). -/
@[simp] theorem dualPair_one (D : X.EffCartier) {V : X.Opens} (x : Γ(D.ideal.toModules, V)) :
    Modules.dualPair D.one (le_top : V ≤ ⊤) x = idealIota D.ideal V x := rfl

/-- Restrictions of `1_D` are still the inclusion map. -/
@[simp] theorem dualPair_res_one (D : X.EffCartier) {U V : X.Opens} (h : V ≤ U)
    (x : Γ(D.ideal.toModules, V)) :
    Modules.dualPair (D.sheaf.res (le_top : U ≤ ⊤) D.one) h x = idealIota D.ideal V x := rfl

/-- `1_D` is a regular section (Stacks 01WX), proved directly from local equations without knowing
that `I_D` is a line bundle. -/
theorem one_isRegularSection (D : X.EffCartier) : Modules.IsRegularSection D.sheaf D.one := by
  intro U r hr
  have key : ∀ p : U, ∃ (W : X.Opens) (i : W ⟶ U), p.1 ∈ W ∧
      X.presheaf.map i.op r = X.presheaf.map i.op 0 := by
    rintro ⟨p, hp⟩
    obtain ⟨V, hpV, a, ha, hI⟩ := D.exists_localEquation p
    obtain ⟨x, hx⟩ : ∃ x : Γ(D.ideal.toModules, V.1), idealIota D.ideal V.1 x = a := by
      have : a ∈ Set.range (idealIota D.ideal V.1) := by
        rw [range_idealIota, hI]; exact Ideal.subset_span rfl
      exact this
    have hW : U ⊓ V.1 ≤ V.1 := inf_le_right
    refine ⟨U ⊓ V.1, homOfLE inf_le_left, ⟨hp, hpV⟩, ?_⟩
    -- pair r • 1_D|_U = 0 with x|_{U ⊓ V}: r|·a| = 0, while a| is still a nonzerodivisor
    have h0 : Modules.dualPair (r • D.sheaf.res (le_top : U ≤ ⊤) D.one) (inf_le_left : U ⊓ V.1 ≤ U)
        (D.ideal.toModules.res hW x) =
        Modules.dualPair (0 : Γ(D.sheaf, U)) (inf_le_left : U ⊓ V.1 ≤ U)
          (D.ideal.toModules.res hW x) := by rw [hr]
    have hz : Modules.dualPair (0 : Γ(D.sheaf, U)) (inf_le_left : U ⊓ V.1 ≤ U)
        (D.ideal.toModules.res hW x) = 0 := rfl
    rw [hz, Modules.dualPair_smul, dualPair_res_one, idealIota_map D.ideal (homOfLE hW) x, hx] at h0
    rw [map_zero]
    exact (mem_nonZeroDivisors_iff_right.mp (V.2.res_mem_nonZeroDivisors ha hW)) _ h0
  choose W i hpW hW using key
  exact X.sheaf.eq_of_locally_eq' W U i
    (fun p hp => TopologicalSpace.Opens.mem_iSup.mpr ⟨⟨p, hp⟩, hpW _⟩) r 0 hW

end Canonical

end EffCartier

end AlgebraicGeometry.Scheme

end
