import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffCartierLineBundle

/-! # The canonical presentation of an effective Cartier divisor

The **canonical presentation** `D.canonicalPresentation : D.Presentation` of an effective Cartier
divisor `D`: the line bundle `O_X(D) = I_D^∨` with the section `1_D`. The required proposition is
`one_isZeroIdeal`: `I_D` is the zero ideal of `(O_X(D), 1_D)` (Stacks 01WX: `Z(1_D) = D`).
Theorems about `D` are stated for an arbitrary `Presentation`; this module guarantees that a
presentation always exists, so those theorems apply unconditionally to `D`.
Proof of `one_isZeroIdeal`: (`⊆`) from the pairing formula `ι(x) = c·e(x)`; (`⊇`) on basic opens
covering `W`, `c| = ι(x₀|)·unit`, then `map_ideal_basicOpen` and localization
(`Submodule.mem_of_span_eq_top_of_smul_pow_mem`) return to `W`.
-/

set_option autoImplicit false

universe u

open CategoryTheory Opposite

noncomputable section

namespace AlgebraicGeometry.Scheme.EffCartier

set_option backward.isDefEq.respectTransparency false

variable {X : Scheme.{u}}

/-- `Z(1_D) = D`: on every affine open `W` with an `O_X(D)`-frame `e`, `I_D` is generated by the
coordinate of `1_D`.
Route: write `1_D|_W = c • e`. At each point of `W` take a frame `(W₀, x₀)` of `I_D`
(`exists_frame_ideal`; `W₀ ≤ W` may be taken to be a basic open of `W`) and put `a₀ := ι(x₀)`; the
dual frame is `x₀^∨ = u • e|_{W₀}` with `u` a unit (`IsFrame.exists_unit`), and evaluating both sides
at `x₀` gives `c|_{W₀} = a₀·u⁻¹`, so `I_D(W₀) = (a₀) = (c|_{W₀})`. By quasi-coherence
(`map_ideal_basicOpen`), `I_D(W)·Γ(W₀) = (c)·Γ(W₀)` for a family of basic opens covering `W`, hence
`I_D(W) = (c)` (equality of ideals on an affine open can be checked on a basic open cover). -/
theorem one_isZeroIdeal (D : X.EffCartier) : Modules.IsZeroIdeal D.ideal D.sheaf D.one := by
  intro W e hf
  have hid : ∀ {V : X.Opens} (r : Γ(X, V)), X.presheaf.map (homOfLE (le_refl V)).op r = r := by
    intro V r
    have : (homOfLE (le_refl V)).op = 𝟙 (op V) := rfl
    rw [this, X.presheaf.map_id]; rfl
  have hce : hf.coord le_rfl (D.sheaf.res le_top D.one) • e = D.sheaf.res le_top D.one := by
    have := hf.coord_smul_frame le_rfl (D.sheaf.res le_top D.one)
    rwa [Modules.res_self] at this
  -- pairing formula: ι(x) = c|_V · e(x)
  have hpair : ∀ {V : X.Opens} (h : V ≤ W.1) (x : Γ(D.ideal.toModules, V)),
      idealIota D.ideal V x =
        X.presheaf.map (homOfLE h).op (hf.coord le_rfl (D.sheaf.res le_top D.one)) *
          Modules.dualPair e h x := by
    intro V h x
    rw [← Modules.dualPair_smul, hce]
    rfl
  apply le_antisymm
  · intro r hr
    have hr' : r ∈ Set.range (idealIota D.ideal W.1) := by rw [range_idealIota]; exact hr
    obtain ⟨x, rfl⟩ := hr'
    rw [hpair le_rfl x, hid]
    exact Ideal.mem_span_singleton.mpr ⟨_, rfl⟩
  · rw [Ideal.span_singleton_le_iff_mem]
    refine Submodule.mem_of_span_eq_top_of_smul_pow_mem (D.ideal.ideal W)
      {f | X.presheaf.map (homOfLE (X.basicOpen_le f)).op
        (hf.coord le_rfl (D.sheaf.res le_top D.one)) ∈ D.ideal.ideal (X.affineBasicOpen f)} ?_ _ ?_
    · rw [← W.2.self_le_iSup_basicOpen_iff]
      intro p hpW
      obtain ⟨W₀, hp₀, x₀, hx₀⟩ := D.exists_frame_ideal p
      obtain ⟨f, hB, hpf⟩ := W.2.exists_basicOpen_le (V := W.1 ⊓ W₀) ⟨p, ⟨hpW, hp₀⟩⟩ hpW
      have hBW : X.basicOpen f ≤ W.1 := hB.trans inf_le_left
      have hxB := hx₀.restrict (hB.trans inf_le_right)
      have heB := hf.restrict hBW
      obtain ⟨u, hu⟩ := heB.exists_unit hxB.dualFrame_isFrame
      have h1 : Modules.dualPair hxB.dualFrame le_rfl
          (D.ideal.toModules.res le_rfl (D.ideal.toModules.res (hB.trans inf_le_right) x₀)) = 1 := by
        rw [Modules.IsFrame.dualPair_dualFrame]; exact hxB.coord_frame le_rfl
      rw [← hu, Modules.dualPair_smul, hid] at h1
      have h2 := hpair hBW
        (D.ideal.toModules.res le_rfl (D.ideal.toModules.res (hB.trans inf_le_right) x₀))
      have h3 : Modules.dualPair (D.sheaf.res hBW e) le_rfl
          (D.ideal.toModules.res le_rfl (D.ideal.toModules.res (hB.trans inf_le_right) x₀)) =
          Modules.dualPair e hBW
          (D.ideal.toModules.res le_rfl (D.ideal.toModules.res (hB.trans inf_le_right) x₀)) := rfl
      rw [h3] at h1
      refine TopologicalSpace.Opens.mem_iSup.mpr ⟨⟨f, ?_⟩, hpf⟩
      show X.presheaf.map (homOfLE hBW).op _ ∈ D.ideal.ideal (X.affineBasicOpen f)
      have hmem : idealIota D.ideal (X.affineBasicOpen f).1
          (D.ideal.toModules.res le_rfl (D.ideal.toModules.res (hB.trans inf_le_right) x₀)) ∈
          D.ideal.ideal (X.affineBasicOpen f) := by
        have hrange : idealIota D.ideal (X.affineBasicOpen f).1
            (D.ideal.toModules.res le_rfl (D.ideal.toModules.res (hB.trans inf_le_right) x₀)) ∈
            Set.range (idealIota D.ideal (X.affineBasicOpen f).1) := ⟨_, rfl⟩
        rw [range_idealIota] at hrange
        exact hrange
      have h4 : X.presheaf.map (homOfLE hBW).op (hf.coord le_rfl (D.sheaf.res le_top D.one)) =
          idealIota D.ideal (X.basicOpen f)
            (D.ideal.toModules.res le_rfl (D.ideal.toModules.res (hB.trans inf_le_right) x₀)) *
            (u : Γ(X, X.basicOpen f)) := by
        rw [h2, mul_assoc,
          mul_comm (Modules.dualPair e hBW _), h1, mul_one]
      rw [h4]
      exact Ideal.mul_mem_right _ _ hmem
    · rintro ⟨f, hfmem⟩
      replace hfmem : X.presheaf.map (homOfLE (X.basicOpen_le f)).op
          (hf.coord le_rfl (D.sheaf.res le_top D.one)) ∈ D.ideal.ideal (X.affineBasicOpen f) := hfmem
      have hloc := W.2.isLocalization_basicOpen f
      have hfmem' : X.presheaf.map (homOfLE (X.basicOpen_le f)).op
          (hf.coord le_rfl (D.sheaf.res le_top D.one)) ∈
          Ideal.map (algebraMap Γ(X, W.1) Γ(X, X.basicOpen f)) (D.ideal.ideal W) := by
        rw [← D.ideal.map_ideal_basicOpen W f] at hfmem
        exact hfmem
      obtain ⟨⟨⟨i, hi⟩, ⟨_, n, rfl⟩⟩, hx⟩ :=
        (IsLocalization.mem_map_algebraMap_iff (Submonoid.powers f) _).mp hfmem'
      have hx' : algebraMap Γ(X, W.1) Γ(X, X.basicOpen f)
          (hf.coord le_rfl (D.sheaf.res le_top D.one) * f ^ n) =
          algebraMap Γ(X, W.1) Γ(X, X.basicOpen f) i := by
        rw [map_mul]; exact hx
      obtain ⟨⟨_, m, rfl⟩, hm⟩ := (IsLocalization.eq_iff_exists (Submonoid.powers f) _).mp hx'
      refine ⟨m + n, ?_⟩
      have : (f ^ (m + n)) • hf.coord le_rfl (D.sheaf.res le_top D.one) = f ^ m * i := by
        rw [smul_eq_mul, pow_add, ← hm]; ring
      rw [this]
      exact Ideal.mul_mem_left _ _ hi

/-- The canonical presentation `(O_X(D), 1_D)`. -/
def canonicalPresentation (D : X.EffCartier) : D.Presentation where
  bundle := D.sheaf
  sec := D.one
  isZeroIdeal := D.one_isZeroIdeal

@[simp] theorem canonicalPresentation_bundle (D : X.EffCartier) :
    D.canonicalPresentation.bundle = D.sheaf := rfl

@[simp] theorem canonicalPresentation_sec (D : X.EffCartier) :
    D.canonicalPresentation.sec = D.one := rfl

theorem presentation_nonempty (D : X.EffCartier) : Nonempty D.Presentation :=
  ⟨D.canonicalPresentation⟩

end AlgebraicGeometry.Scheme.EffCartier

end
