import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffCartier
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.LocalDivisibility
import MiyaokaMori.AlgebraicGeometry.Modules.Stalk.ModuleLocalIso

/-! # `O_X(D) ≅ L` for a presentation `(L, σ)` of an effective Cartier divisor

**Statement.** Let `D` be an effective Cartier divisor on a scheme `X` (`X.EffCartier`: a
quasi-coherent ideal sheaf `I = D.ideal` locally generated by a non-zero-divisor) and let
`P : D.Presentation` be a presentation of `D` by a line bundle `L = P.bundle` and a global section
`σ = P.sec` (i.e. on every affine open `W` with a frame `e` of `L`, `I(W) = (coord_e σ)`). Assume `σ` is a
regular section (`IsRegularSection`: `r • σ|_U = 0 ⇒ r = 0` on every open `U`). Then
`O_X(D) = I^∨ ≅ L` (`Presentation.sheafIso`), and moreover (auxiliary) `I` is locally generated by a
nonzerodivisor (`isInvertibleIdeal_of_isZeroIdeal`), so `(L, σ)` with regular `σ` always defines an effective
Cartier divisor with ideal sheaf the zero ideal of `σ`.

**Source.** Stacks 01WX (the canonical section `1_D` of `O_X(D)` and `Z(1_D) = D`), Stacks 01X0(2)
(`O_X(Z(σ)) ≅ L` for a regular section `σ` of an invertible sheaf `L`; proof omitted in Stacks, written
out here).

**Proof (as formalized).**
1. *Charts.* Every point has an affine open `W` with a frame `e` of `L` (`exists_affine_frame_le`).
   Put `f := coord_e(σ|_W)`; `f` is a non-zero-divisor (`IsRegularSection.coord_mem_nonZeroDivisors`)
   and `I(W) = (f)` (the presentation). Choose `x ∈ Γ(W, I)` with `ι(x) = f` (`range_idealIota`); then
   `x` is a frame of the module sheaf `I` on `W` (`isFrame_ideal_of_span`: the argument of
   `EffCartier.exists_frame_ideal`, for an arbitrary affine open with `I(W) = (a)`, `a` a non-zero-divisor).
2. *Division by σ.* For `V ≤ W`, `y ∈ Γ(V, I)`, `t ∈ Γ(V, L)`:
   `ι(y) • t = (coord_x y · coord_e t) • σ|_V` (`Chart.iota_smul`): write `y = coord_x y • x|_V`,
   `t = coord_e t • e|_V`, `σ|_V = f|_V • e|_V` and `ι(x|_V) = f|_V`.
   For an arbitrary open `V`, `y`, `t`, there is a unique `r ∈ Γ(V, O_X)` with `r • σ|_V = ι(y) • t`
   (`exists_smul_sec_eq`): uniqueness is regularity; existence: the local quotients of step 2 on the cover
   `{V ⊓ W_p}` agree on overlaps by uniqueness, so they glue (`X.sheaf.existsUnique_gluing'`), and the glued
   section satisfies the equation because `L` is separated (`TopCat.Sheaf.eq_of_locally_eq'`).
   Write `divide y t` for this `r`; it is additive and `Γ(V, O_X)`-linear in `y`, additive and linear in `t`,
   compatible with restriction, and on a chart equals `coord_x y · coord_e t` (`divide_chart`).
3. *The morphism.* `Φ : L ⟶ I^∨`, `Φ_U(t) := (V ≤ U ↦ (y ↦ divide y (t|_V)))`, a compatible family of
   functionals, i.e. a section of `dualSheaf I` (which is not sheafified: its sections *are* such families).
   `Φ` is a morphism of `O_X`-modules (`PresheafOfModules.homMk`).
4. *Iso.* On `V ≤ W` for a chart: `Φ_V(t)(x|_V) = coord_e t`, so `Φ_V` is injective; given `ψ ∈ Γ(V, I^∨)`,
   `t := ψ(x|_V) • e|_V` satisfies `Φ_V(t) = ψ` (check on `y = coord_x y • x|_{V'}`). Hence `Φ` is an
   isomorphism on the restriction to each chart, hence an isomorphism (`AlgebraicGeometry.Scheme.Modules.moduleHom_isIso_of_locally_isIso`,
   `isIso_of_bijective`). `sheafIso := (asIso Φ).symm`.

Edge cases: `X` empty — every open is `⊥`, all statements are vacuous/trivial; `Γ(X, ⊤)` the zero ring —
then `σ = 0` is regular (`0 = 0 ⇒ r = 0` holds in the zero ring), `I = ⊤` and `I^∨ ≅ O_X ≅ L`, all consistent.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory Opposite TopologicalSpace

noncomputable section

namespace AlgebraicGeometry.Scheme.Modules

set_option backward.isDefEq.respectTransparency false

variable {X : Scheme.{u}}

/-- On an affine open `W` with `I(W) = (a)`, `a` a non-zero-divisor, any `x ∈ Γ(W, I)` with `ι(x) = a` is a
frame of the module sheaf `I` on `W`. This is the body of `EffCartier.exists_frame_ideal` for a given
affine open instead of the one produced by `exists_localEquation`. -/
theorem isFrame_ideal_of_span (I : X.IdealSheafData) (W : X.affineOpens) {a : Γ(X, W.1)}
    (ha : a ∈ nonZeroDivisors Γ(X, W.1)) (hI : I.ideal W = Ideal.span {a})
    (x : Γ(I.toModules, W.1)) (hx : EffCartier.idealIota I W.1 x = a) :
    IsFrame I.toModules W.1 x := by
  have hiota : ∀ {W' : X.Opens} (h : W' ≤ W.1),
      EffCartier.idealIota I W' (I.toModules.res h x) = X.presheaf.map (homOfLE h).op a := by
    intro W' h
    rw [← hx]
    exact EffCartier.idealIota_map I (homOfLE h) x
  intro W' h
  refine ⟨?_, ?_⟩
  · intro r r' hrr
    have hrr' : r • I.toModules.res h x = r' • I.toModules.res h x := hrr
    have h1 := congrArg (EffCartier.idealIota I W') hrr'
    rw [_root_.map_smul, _root_.map_smul, smul_eq_mul, smul_eq_mul, hiota h] at h1
    have hnzd := W.2.res_mem_nonZeroDivisors ha h
    have h2 : (r - r') * X.presheaf.map (homOfLE h).op a = 0 := by rw [sub_mul, h1, sub_self]
    exact sub_eq_zero.mp (mem_nonZeroDivisors_iff_right.mp hnzd _ h2)
  · intro y
    have hb : X.presheaf.map (homOfLE h).op a ∣ EffCartier.idealIota I W' y := by
      refine W.2.dvd_of_locally_dvd ha h _ fun q ↦ ?_
      obtain ⟨f, hfW, hqf⟩ := W.2.exists_basicOpen_le q (h q.2)
      have hBW : (X.affineBasicOpen f).1 ≤ W' := hfW
      refine ⟨(X.affineBasicOpen f).1, hBW, hqf, ?_⟩
      have hmem : EffCartier.idealIota I (X.affineBasicOpen f).1 (I.toModules.res hBW y) ∈
          I.ideal (X.affineBasicOpen f) := by
        have hrange : EffCartier.idealIota I (X.affineBasicOpen f).1 (I.toModules.res hBW y) ∈
            Set.range (EffCartier.idealIota I (X.affineBasicOpen f).1) := ⟨_, rfl⟩
        rw [EffCartier.range_idealIota] at hrange
        exact hrange
      rw [← I.map_ideal_basicOpen W f, hI, Ideal.map_span, Set.image_singleton] at hmem
      obtain ⟨c, hc⟩ := Ideal.mem_span_singleton.mp hmem
      exact ⟨c, (EffCartier.idealIota_map I (homOfLE hBW) y).symm.trans hc⟩
    obtain ⟨r, hr⟩ := hb
    refine ⟨r, EffCartier.idealIota_injective I W' ?_⟩
    show EffCartier.idealIota I W' (r • I.toModules.res h x) = EffCartier.idealIota I W' y
    rw [_root_.map_smul, smul_eq_mul, hiota h, hr, mul_comm]

/-- The zero ideal of a regular section of a line bundle is locally generated by a non-zero-divisor
(`IsInvertibleIdeal`): on an affine frame open `W`, `I(W) = (coord_e σ)` and
`coord_e σ` is a non-zero-divisor. -/
theorem isInvertibleIdeal_of_isZeroIdeal {L : X.Modules} [L.IsLineBundle] {σ : Γ(L, ⊤)}
    (hreg : IsRegularSection L σ) {I : X.IdealSheafData} (hI : IsZeroIdeal I L σ) :
    MiyaokaMori.Statement.IsInvertibleIdeal I := by
  intro p
  obtain ⟨W, hW, -, hp, e, he⟩ := exists_affine_frame_le L (U := ⊤) (p := p) trivial
  refine ⟨⟨W, hW⟩, hp, he.coord le_rfl (L.res le_top σ), fun r hr => ?_, hI ⟨W, hW⟩ e he⟩
  exact (mem_nonZeroDivisors_iff_right.mp (hreg.coord_mem_nonZeroDivisors he)) r (by rwa [mul_comm])

namespace EffCartier.Presentation

variable {D : X.EffCartier} (P : D.Presentation) (hreg : IsRegularSection P.bundle P.sec)

/-- A chart for a presentation: an affine open `W`, a frame `e` of `L` on `W`, and a section `x` of the
ideal sheaf on `W` with `ι(x) = coord_e(σ|_W)` (the local equation of `D`). -/
structure Chart where
  /-- the affine open -/
  W : X.affineOpens
  /-- frame of `L` on `W` -/
  e : Γ(P.bundle, W.1)
  he : IsFrame P.bundle W.1 e
  /-- the local equation, as a section of `I` -/
  x : Γ(D.ideal.toModules, W.1)
  hx : EffCartier.idealIota D.ideal W.1 x = he.coord le_rfl (P.bundle.res le_top P.sec)

/-- Every point lies in a chart. -/
theorem exists_chart (p : X) : ∃ c : Chart P, p ∈ c.W.1 := by
  obtain ⟨W, hW, -, hp, e, he⟩ := exists_affine_frame_le P.bundle (U := ⊤) (p := p) trivial
  have hmem : he.coord le_rfl (P.bundle.res le_top P.sec) ∈
      Set.range (EffCartier.idealIota D.ideal W) := by
    rw [EffCartier.range_idealIota D.ideal ⟨W, hW⟩, P.isZeroIdeal ⟨W, hW⟩ e he]
    exact Ideal.mem_span_singleton_self _
  obtain ⟨x, hx⟩ := hmem
  exact ⟨⟨⟨W, hW⟩, e, he, x, hx⟩, hp⟩

namespace Chart

variable {P}

/-- `σ|_V = f|_V • e|_V` on `V ≤ W`, where `f = coord_e σ`. -/
theorem sec_eq (c : Chart P) {V : X.Opens} (h : V ≤ c.W.1) :
    P.bundle.res (le_top : V ≤ ⊤) P.sec =
      X.presheaf.map (homOfLE h).op (c.he.coord le_rfl (P.bundle.res le_top P.sec)) •
        P.bundle.res h c.e := by
  have h1 := c.he.coord_smul_frame le_rfl (P.bundle.res le_top P.sec)
  rw [res_self] at h1
  have h2 := congrArg (P.bundle.res h) h1
  rw [res_smul, res_res] at h2
  exact h2.symm

/-- `ι(x|_V) = f|_V`. -/
theorem iota_res (c : Chart P) {V : X.Opens} (h : V ≤ c.W.1) :
    EffCartier.idealIota D.ideal V (D.ideal.toModules.res h c.x) =
      X.presheaf.map (homOfLE h).op (c.he.coord le_rfl (P.bundle.res le_top P.sec)) := by
  rw [← c.hx]
  exact EffCartier.idealIota_map D.ideal (homOfLE h) c.x

include hreg

/-- The local equation `x` is a frame of the module sheaf `I` on `W`. -/
theorem isFrame (c : Chart P) : IsFrame D.ideal.toModules c.W.1 c.x :=
  isFrame_ideal_of_span D.ideal c.W (hreg.coord_mem_nonZeroDivisors c.he)
    (P.isZeroIdeal c.W c.e c.he) c.x c.hx

/-- The key identity on a chart: `ι(y) • t = (coord_x y · coord_e t) • σ|_V`. -/
theorem iota_smul (c : Chart P) {V : X.Opens} (h : V ≤ c.W.1)
    (y : Γ(D.ideal.toModules, V)) (t : Γ(P.bundle, V)) :
    EffCartier.idealIota D.ideal V y • t =
      ((c.isFrame hreg).coord h y * c.he.coord h t) • P.bundle.res (le_top : V ≤ ⊤) P.sec := by
  have hy := (c.isFrame hreg).coord_smul_frame h y
  have ht := c.he.coord_smul_frame h t
  rw [c.sec_eq h]
  conv_lhs => rw [← hy, ← ht]
  rw [_root_.map_smul, smul_eq_mul, c.iota_res h, smul_smul, smul_smul]
  congr 1
  ring

end Chart

include hreg

/-- Existence of the quotient `(ι(y) • t) / σ` on an arbitrary open `V`: the local quotients on the charts
agree on overlaps (regularity) and glue in the structure sheaf; the glued section satisfies the
defining equation because `L` is a sheaf (separatedness). -/
theorem exists_smul_sec_eq (V : X.Opens) (y : Γ(D.ideal.toModules, V)) (t : Γ(P.bundle, V)) :
    ∃ r : Γ(X, V), r • P.bundle.res (le_top : V ≤ ⊤) P.sec = EffCartier.idealIota D.ideal V y • t := by
  have key : ∀ p : V, ∃ (O : X.Opens) (hO : O ≤ V), p.1 ∈ O ∧ ∃ r : Γ(X, O),
      r • P.bundle.res (le_top : O ≤ ⊤) P.sec =
        EffCartier.idealIota D.ideal O (D.ideal.toModules.res hO y) • P.bundle.res hO t := by
    rintro ⟨p, hp⟩
    obtain ⟨c, hpW⟩ := exists_chart P p
    exact ⟨V ⊓ c.W.1, inf_le_left, ⟨hp, hpW⟩, _, (c.iota_smul hreg inf_le_right _ _).symm⟩
  choose O hO hpO r hr using key
  have hcover : V ≤ iSup O := fun p hp ↦ Opens.mem_iSup.mpr ⟨⟨p, hp⟩, hpO _⟩
  -- restriction of the defining equation
  have hres : ∀ (p : V) {O' : X.Opens} (h' : O' ≤ O p),
      X.presheaf.map (homOfLE h').op (r p) • P.bundle.res (le_top : O' ≤ ⊤) P.sec =
        EffCartier.idealIota D.ideal O' (D.ideal.toModules.res (h'.trans (hO p)) y) •
          P.bundle.res (h'.trans (hO p)) t := by
    intro p O' h'
    have := congrArg (P.bundle.res h') (hr p)
    rw [res_smul, res_res, res_smul, res_res] at this
    rw [this, EffCartier.idealIota_map, EffCartier.idealIota_map, Scheme.presheaf_map_map]
  have hcompat : TopCat.Presheaf.IsCompatible X.presheaf O r := by
    intro p q
    apply (isRegularSection_iff_injective P.bundle P.sec).mp hreg (O p ⊓ O q)
    show X.presheaf.map (homOfLE (inf_le_left : O p ⊓ O q ≤ O p)).op (r p) •
        P.bundle.res le_top P.sec =
      X.presheaf.map (homOfLE (inf_le_right : O p ⊓ O q ≤ O q)).op (r q) • P.bundle.res le_top P.sec
    rw [hres p inf_le_left, hres q inf_le_right]
  obtain ⟨s', hs, -⟩ := X.sheaf.existsUnique_gluing' O V (fun p ↦ homOfLE (hO p)) hcover r hcompat
  let s : Γ(X, V) := s'
  refine ⟨s, ?_⟩
  refine TopCat.Sheaf.eq_of_locally_eq' ⟨P.bundle.presheaf, P.bundle.isSheaf⟩ O V
    (fun p ↦ homOfLE (hO p)) hcover _ _ fun p ↦ ?_
  have hs' : X.presheaf.map (homOfLE (hO p)).op s = r p := hs p
  show P.bundle.res (hO p) (s • P.bundle.res le_top P.sec) =
    P.bundle.res (hO p) (EffCartier.idealIota D.ideal V y • t)
  rw [res_smul P.bundle (hO p) s, res_res, hs', hr p,
    res_smul P.bundle (hO p) (EffCartier.idealIota D.ideal V y) t, EffCartier.idealIota_map]

/-- The quotient `(ι(y) • t) / σ ∈ Γ(V, O_X)`. -/
def divide {V : X.Opens} (y : Γ(D.ideal.toModules, V)) (t : Γ(P.bundle, V)) : Γ(X, V) :=
  Classical.choose (exists_smul_sec_eq P hreg V y t)

theorem divide_spec {V : X.Opens} (y : Γ(D.ideal.toModules, V)) (t : Γ(P.bundle, V)) :
    divide P hreg y t • P.bundle.res (le_top : V ≤ ⊤) P.sec = EffCartier.idealIota D.ideal V y • t :=
  Classical.choose_spec (exists_smul_sec_eq P hreg V y t)

theorem divide_unique {V : X.Opens} {y : Γ(D.ideal.toModules, V)} {t : Γ(P.bundle, V)} {r : Γ(X, V)}
    (hr : r • P.bundle.res (le_top : V ≤ ⊤) P.sec = EffCartier.idealIota D.ideal V y • t) :
    divide P hreg y t = r :=
  (isRegularSection_iff_injective P.bundle P.sec).mp hreg V ((divide_spec P hreg y t).trans hr.symm)

theorem divide_add_left {V : X.Opens} (y y' : Γ(D.ideal.toModules, V)) (t : Γ(P.bundle, V)) :
    divide P hreg (y + y') t = divide P hreg y t + divide P hreg y' t := by
  apply divide_unique
  rw [add_smul, divide_spec, divide_spec, map_add, add_smul]

theorem divide_smul_left {V : X.Opens} (c : Γ(X, V)) (y : Γ(D.ideal.toModules, V)) (t : Γ(P.bundle, V)) :
    divide P hreg (c • y) t = c * divide P hreg y t := by
  apply divide_unique
  rw [mul_smul, divide_spec, _root_.map_smul, smul_eq_mul, mul_smul]

theorem divide_add_right {V : X.Opens} (y : Γ(D.ideal.toModules, V)) (t t' : Γ(P.bundle, V)) :
    divide P hreg y (t + t') = divide P hreg y t + divide P hreg y t' := by
  apply divide_unique
  rw [add_smul, divide_spec, divide_spec, smul_add]

theorem divide_smul_right {V : X.Opens} (y : Γ(D.ideal.toModules, V)) (c : Γ(X, V)) (t : Γ(P.bundle, V)) :
    divide P hreg y (c • t) = c * divide P hreg y t := by
  apply divide_unique
  rw [mul_smul, divide_spec, smul_smul, smul_smul, mul_comm]

theorem divide_res {V' V : X.Opens} (h : V' ≤ V) (y : Γ(D.ideal.toModules, V)) (t : Γ(P.bundle, V)) :
    divide P hreg (D.ideal.toModules.res h y) (P.bundle.res h t) =
      X.presheaf.map (homOfLE h).op (divide P hreg y t) := by
  apply divide_unique
  have := congrArg (P.bundle.res h) (divide_spec P hreg y t)
  rw [res_smul, res_res, res_smul] at this
  rw [EffCartier.idealIota_map]
  exact this

/-- On a chart, the quotient is `coord_x y · coord_e t`. -/
theorem divide_chart (c : Chart P) {V : X.Opens} (h : V ≤ c.W.1)
    (y : Γ(D.ideal.toModules, V)) (t : Γ(P.bundle, V)) :
    divide P hreg y t = (c.isFrame hreg).coord h y * c.he.coord h t :=
  divide_unique P hreg (c.iota_smul hreg h y t).symm

/-- The compatible family of functionals `V ↦ (y ↦ divide y (t|_V))`, i.e. `Φ_U(t) ∈ Γ(U, I^∨)`. -/
def toDualFamily (U : X.Opens) : Γ(P.bundle, U) →ₗ[Γ(X, U)] AlgebraicGeometry.Scheme.Modules.LocalDualSections X D.ideal.toModules U where
  toFun t := ⟨fun V =>
    { toFun := fun y => divide P hreg y (P.bundle.res (leOfHom V.hom) t)
      map_add' := fun y y' => divide_add_left P hreg y y' _
      map_smul' := fun c y => by
        show divide P hreg (c • y) _ = c • divide P hreg y _
        rw [smul_eq_mul]
        exact divide_smul_left P hreg c y _ }, by
    intro V W i y
    show divide P hreg (D.ideal.toModules.res (leOfHom i.left) y) (P.bundle.res (leOfHom V.hom) t) =
      X.presheaf.map (homOfLE (leOfHom i.left)).op
        (divide P hreg y (P.bundle.res (leOfHom W.hom) t))
    have hres : P.bundle.res (leOfHom V.hom) t =
        P.bundle.res (leOfHom i.left) (P.bundle.res (leOfHom W.hom) t) :=
      (res_res _ _ _ _).symm
    rw [hres, divide_res]⟩
  map_add' t t' := by
    apply Subtype.ext
    funext V
    apply LinearMap.ext
    intro y
    show divide P hreg y (P.bundle.res (leOfHom V.hom) (t + t')) =
      divide P hreg y (P.bundle.res (leOfHom V.hom) t) + divide P hreg y (P.bundle.res (leOfHom V.hom) t')
    have hadd : P.bundle.res (leOfHom V.hom) (t + t') =
        P.bundle.res (leOfHom V.hom) t + P.bundle.res (leOfHom V.hom) t' := map_add _ _ _
    rw [hadd]
    exact divide_add_right P hreg y _ _
  map_smul' r t := by
    apply Subtype.ext
    funext V
    apply LinearMap.ext
    intro y
    show divide P hreg y (P.bundle.res (leOfHom V.hom) (r • t)) =
      X.presheaf.map V.hom.op r * divide P hreg y (P.bundle.res (leOfHom V.hom) t)
    rw [res_smul, divide_smul_right]
    rfl

/-- `Φ_U : Γ(U, L) → Γ(U, I^∨)`. -/
def toDualSections (U : X.Opens) : Γ(P.bundle, U) →ₗ[Γ(X, U)] Γ(dualSheaf D.ideal.toModules, U) :=
  (dualSheafSections D.ideal.toModules U).symm.toLinearMap ∘ₗ toDualFamily P hreg U

@[simp] theorem dualPair_toDualSections {U : X.Opens} (t : Γ(P.bundle, U)) {V : X.Opens} (h : V ≤ U)
    (y : Γ(D.ideal.toModules, V)) :
    dualPair (toDualSections P hreg U t) h y = divide P hreg y (P.bundle.res h t) := rfl

/-- Restriction of `Φ_U(t)` is `Φ_V(t|_V)`. -/
theorem res_toDualSections {U V : X.Opens} (h : V ≤ U) (t : Γ(P.bundle, U)) :
    (dualSheaf D.ideal.toModules).res h (toDualSections P hreg U t) =
      toDualSections P hreg V (P.bundle.res h t) := by
  apply dualSheaf_ext
  intro V' h'
  apply LinearMap.ext
  intro y
  rw [dualPair_res_left, dualPair_toDualSections, dualPair_toDualSections, res_res]

/-- The morphism `Φ : L ⟶ I^∨ = O_X(D)`. -/
def toDualHom : P.bundle ⟶ dualSheaf D.ideal.toModules :=
  SheafOfModules.Hom.mk (PresheafOfModules.homMk
    { app := fun U => AddCommGrpCat.ofHom (toDualSections P hreg U.unop).toAddMonoidHom
      naturality := fun U V i => by
        ext t
        exact (res_toDualSections P hreg (leOfHom i.unop) t).symm }
    (fun U r t => (toDualSections P hreg U.unop).map_smul r t))

theorem toDualHom_app (U : X.Opens) (t : Γ(P.bundle, U)) :
    (toDualHom P hreg).app U t = toDualSections P hreg U t := rfl

/-- On `V ≤ W` for a chart, `Φ_V` is bijective. -/
theorem toDualSections_bijective (c : Chart P) {V : X.Opens} (h : V ≤ c.W.1) :
    Function.Bijective (toDualSections P hreg V) := by
  constructor
  · intro t t' htt
    have h1 := congrArg (fun φ => dualPair φ le_rfl (D.ideal.toModules.res h c.x)) htt
    simp only [dualPair_toDualSections, res_self] at h1
    rw [divide_chart P hreg c h, divide_chart P hreg c h, (c.isFrame hreg).coord_frame h, one_mul,
      one_mul] at h1
    exact (c.he.coordEquiv h).injective h1
  · intro ψ
    refine ⟨dualPair ψ le_rfl (D.ideal.toModules.res h c.x) • P.bundle.res h c.e, ?_⟩
    apply dualSheaf_ext
    intro V' h'
    apply LinearMap.ext
    intro y
    rw [dualPair_toDualSections, divide_chart P hreg c (h'.trans h), res_smul, c.he.coord_smul, res_res,
      c.he.coord_frame, mul_one]
    have hy := (c.isFrame hreg).coord_smul_frame (h'.trans h) y
    have h2 : dualPair ψ h' y =
        (c.isFrame hreg).coord (h'.trans h) y *
          X.presheaf.map (homOfLE h').op (dualPair ψ le_rfl (D.ideal.toModules.res h c.x)) := by
      conv_lhs => rw [← hy]
      rw [_root_.map_smul, smul_eq_mul, ← res_res D.ideal.toModules h' h c.x]
      congr 1
      exact dualPair_res ψ h' le_rfl _
    exact h2.symm

/-- `Φ` is an isomorphism: it is one on each chart. -/
theorem toDualHom_isIso : IsIso (toDualHom P hreg) := by
  apply AlgebraicGeometry.Scheme.Modules.moduleHom_isIso_of_locally_isIso
  intro p
  obtain ⟨c, hp⟩ := exists_chart P p
  refine ⟨c.W.1, hp, ?_⟩
  apply isIso_of_bijective
  intro O
  show Function.Bijective (fun s : Γ(P.bundle, c.W.1.ι ''ᵁ O) => (toDualHom P hreg).app (c.W.1.ι ''ᵁ O) s)
  exact toDualSections_bijective P hreg c (image_ι_le c.W.1 O)

/-- **`O_X(D) ≅ L` for any presentation `(L, σ)` of `D` with `σ` regular** (Stacks 01X0(2)). -/
def sheafIso : D.sheaf ≅ P.bundle :=
  haveI := toDualHom_isIso P hreg
  (asIso (toDualHom P hreg)).symm

end EffCartier.Presentation

end AlgebraicGeometry.Scheme.Modules

end
