import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffectiveCartierDivisorScheme
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffectiveCartierOfSectionPresentationIso
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.ZeroSchemeOfSection

/-! # The effective Cartier divisor of a regular section

A global section `σ` of a line bundle `L` that is a nonzerodivisor everywhere defines an effective
Cartier divisor `div(σ)` (locally defined by the local equations of `σ`) with `O(div σ) ≅ L`; hence
its divisor class is `c_1(L)`. Source: Stacks 01X0(2); used for the coordinate divisors in the proof
of Proposition 2.4 of the paper.

**Proof.** Write `I := idealSheafOfSection L σ` (on an affine
open `U`, `I(U)` is the ideal generated by the values `φ(σ|_U)` of all `Γ(X, U)`-linear functionals `φ`).
1. `hσ` is exactly `IsRegularSection L σ` (`isRegularSection_iff_injective`).
2. `I` is the zero ideal of `(L, σ)` (`IsZeroIdeal`): on an affine open `W`
   with a frame `e` of `L`, every functional satisfies `φ(σ|_W) = coord_e(σ|_W) · φ(e)`, and `coord_e` itself
   is a functional, so `I(W) = (coord_e(σ|_W))` (`idealSheafOfSection_isZeroIdeal`, this file).
3. `coord_e(σ|_W)` is a non-zero-divisor by regularity, so `I` is locally generated by a non-zero-divisor
   (`isInvertibleIdeal_of_isZeroIdeal`); `D := ⟨I, _⟩ : X.EffCartier` (= `EffectiveCartierDivisor X`), and
   `D.idealSheaf = I` by definition.
4. `(L, σ)` is a presentation of `D`, so `O_X(D) = I^∨ ≅ L` by `EffCartier.Presentation.sheafIso`
   (module `EffectiveCartierOfSectionPresentationIso`: the morphism `L → I^∨`, `t ↦ (y ↦ (ι(y)·t)/σ)`, is an
   isomorphism on every frame chart).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- The ideal sheaf `idealSheafOfSection L σ` (generated on affine opens by the values of all linear
functionals on `σ`) is the zero ideal of `(L, σ)` (`IsZeroIdeal`): on an affine open `W` with a frame `e`
of `L` it is generated by the coordinate `coord_e(σ|_W)`.
Proof: `φ(σ|_W) = φ(coord_e σ • e) = coord_e σ · φ(e) ∈ (coord_e σ)` for every functional `φ`, and
`coord_e σ` is the value of the functional `coord_e` on `σ|_W`. -/
theorem AlgebraicGeometry.Scheme.idealSheafOfSection_isZeroIdeal {X : AlgebraicGeometry.Scheme.{u}}
    (L : X.Modules) [L.IsLineBundle] (σ : Γ(L, ⊤)) :
    AlgebraicGeometry.Scheme.Modules.IsZeroIdeal (AlgebraicGeometry.Scheme.idealSheafOfSection L σ) L σ := by
  intro W e he
  show Ideal.span (Set.range fun φ : Γ(L, W.1) →ₗ[Γ(X, W.1)] Γ(X, W.1) =>
      φ (L.presheaf.map (CategoryTheory.homOfLE le_top).op σ)) =
    Ideal.span {he.coord le_rfl (L.res le_top σ)}
  have h1 := he.coord_smul_frame le_rfl (L.res le_top σ)
  rw [AlgebraicGeometry.Scheme.Modules.res_self] at h1
  apply le_antisymm
  · rw [Ideal.span_le]
    rintro _ ⟨φ, rfl⟩
    have h2 : φ (L.res le_top σ) = he.coord le_rfl (L.res le_top σ) * φ e := by
      conv_lhs => rw [← h1]
      rw [_root_.map_smul, smul_eq_mul]
    show φ (L.res le_top σ) ∈ Ideal.span {he.coord le_rfl (L.res le_top σ)}
    rw [h2]
    exact Ideal.mul_mem_right _ _ (Ideal.mem_span_singleton_self _)
  · rw [Ideal.span_singleton_le_iff_mem]
    exact Ideal.subset_span ⟨(he.coordEquiv le_rfl).toLinearMap, rfl⟩

open AlgebraicGeometry in
/-- A regular global section `σ` of a line bundle `L` defines an effective Cartier divisor `D` with ideal
sheaf `idealSheafOfSection L σ` and `O_X(D) ≅ L`. -/
theorem AlgebraicGeometry.exists_effectiveCartierDivisor_of_regular_section
    {X : AlgebraicGeometry.Scheme.{u}}
    (L : X.Modules) [L.IsLineBundle] (σ : (L.val.obj (Opposite.op ⊤) : Type u))
    /- σ is regular (a nonzerodivisor): r ↦ r·σ|_U is injective on every open U (equivalent to stalkwise
       regularity; Mathlib's IsRegular is only defined for monoid elements) -/
    (hσ : ∀ U : X.Opens, Function.Injective (fun r : Γ(X, U) =>
        r • ((L.presheaf.map (CategoryTheory.homOfLE (le_top : U ≤ ⊤)).op).hom σ : Γ(L, U)))) :
    ∃ D : AlgebraicGeometry.EffectiveCartierDivisor X,
      D.idealSheaf = AlgebraicGeometry.Scheme.idealSheafOfSection L σ ∧
      Nonempty (AlgebraicGeometry.EffectiveCartierDivisor.lineBundle D ≅ L) := by
  have hreg : AlgebraicGeometry.Scheme.Modules.IsRegularSection L σ :=
    (AlgebraicGeometry.Scheme.Modules.isRegularSection_iff_injective L σ).mpr hσ
  have hZ := AlgebraicGeometry.Scheme.idealSheafOfSection_isZeroIdeal L σ
  let D : X.EffCartier :=
    ⟨AlgebraicGeometry.Scheme.idealSheafOfSection L σ,
      AlgebraicGeometry.Scheme.Modules.isInvertibleIdeal_of_isZeroIdeal hreg hZ⟩
  let P : D.Presentation := { bundle := L, sec := σ, isZeroIdeal := hZ }
  exact ⟨D, rfl, ⟨AlgebraicGeometry.Scheme.Modules.EffCartier.Presentation.sheafIso P hreg⟩⟩

end
