import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Blowup.InvertibleIdealComplement

/-! # The complement of an effective Cartier divisor is scheme-theoretically dense

Stacks 07ZU: the complement `Y ∖ D` of an effective Cartier divisor `D = V(J)` (i.e. `J` locally generated
by a nonzerodivisor, `MiyaokaMori.Statement.IsInvertibleIdeal J`) is scheme-theoretically dense in `Y`:
the open immersion `(J.support.compl).ι` has kernel `⊥`.

Source: Stacks 07ZU (divisors-lemma-complement-effective-Cartier-divisor-scheme-theoretically-dense);
input of the uniqueness half of Stacks 0806 (`Stacks0806_LiftUnique`) through Stacks 01RH.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- **Stacks 07ZU.** `J` locally generated by a nonzerodivisor ⇒ `ker ((J.support.compl).ι) = ⊥`.

Proof. `ι := (J.support.compl).ι` is quasi-compact (`IsInvertibleIdeal.quasiCompact_support_compl`),
so `ι.ker.ideal V = RingHom.ker (ι.app V)` on every affine `V` (`Scheme.Hom.ker_apply`).
Two ideal sheaves agree if they agree on an affine cover (`IdealSheafData.ext_of_iSup_eq_top`); take the
cover by the affine opens `V_y ∋ y` supplied by `IsInvertibleIdeal`, on which `J.ideal V_y = (a_y)` with
`a_y` a nonzerodivisor. On such `V`: `ι.app V` is the restriction `Γ(Y, V) → Γ(Y, ι(ι⁻¹V))`
(`Scheme.Opens.ι_app`), and `ι(ι⁻¹V) = J.support.compl ⊓ V = Y.basicOpen a`
(`support_compl_inf_eq_basicOpen_of_ideal_eq_span`). Since `V` is affine, the
restriction `Γ(Y, V) → Γ(Y, Y.basicOpen a)` is the localization `Γ(Y, V) → Γ(Y, V)_a`
(`IsAffineOpen.isLocalization_of_eq_basicOpen`), which is injective because `a` is a nonzerodivisor
(`IsLocalization.injective`). Hence `RingHom.ker (ι.app V) = ⊥ = (⊥ : IdealSheafData).ideal V`. -/
theorem MiyaokaMori.Statement.IsInvertibleIdeal.ker_ι_support_compl_eq_bot
    {Y : AlgebraicGeometry.Scheme.{u}} {J : Y.IdealSheafData}
    (hJ : MiyaokaMori.Statement.IsInvertibleIdeal J) :
    (AlgebraicGeometry.Scheme.Opens.ι (X := Y) J.support.compl).ker = ⊥ := by
  set ι := AlgebraicGeometry.Scheme.Opens.ι (X := Y) J.support.compl with hι
  have : AlgebraicGeometry.QuasiCompact ι := hJ.quasiCompact_support_compl
  choose V hxV a ha hJV using hJ
  refine AlgebraicGeometry.Scheme.IdealSheafData.ext_of_iSup_eq_top V ?_ fun x => ?_
  · exact eq_top_iff.2 fun y _ => TopologicalSpace.Opens.mem_iSup.2 ⟨y, hxV y⟩
  · rw [AlgebraicGeometry.Scheme.Hom.ker_apply, AlgebraicGeometry.Scheme.IdealSheafData.ideal_bot,
      Pi.bot_apply, ← RingHom.injective_iff_ker_eq_bot, hι, AlgebraicGeometry.Scheme.Opens.ι_app]
    have hW : ι ''ᵁ ι ⁻¹ᵁ (V x).1 = Y.basicOpen (a x) := by
      rw [AlgebraicGeometry.Scheme.Hom.image_preimage_eq_opensRange_inf,
        AlgebraicGeometry.Scheme.Opens.opensRange_ι]
      exact MiyaokaMori.Statement.support_compl_inf_eq_basicOpen_of_ideal_eq_span J (V x) (a x) (hJV x)
    have hloc := (V x).2.isLocalization_of_eq_basicOpen (a x)
      (homOfLE (Set.image_preimage_subset _ _)) hW
    have hnzd : Submonoid.powers (a x) ≤ nonZeroDivisors Γ(Y, (V x).1) :=
      Submonoid.powers_le.2 (mem_nonZeroDivisors_iff_right.mpr fun r hr => ha x r (by rwa [mul_comm]))
    let _ : Algebra Γ(Y, (V x).1) Γ(Y, ι ''ᵁ ι ⁻¹ᵁ (V x).1) :=
      (Y.presheaf.map (homOfLE (Set.image_preimage_subset _ _)).op).hom.toAlgebra
    have : IsLocalization (Submonoid.powers (a x)) Γ(Y, ι ''ᵁ ι ⁻¹ᵁ (V x).1) := hloc
    exact IsLocalization.injective Γ(Y, ι ''ᵁ ι ⁻¹ᵁ (V x).1) hnzd

end
