import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.Dual.DualFreeSheafFree
import MiyaokaMori.AlgebraicGeometry.Modules.Dual.DualRestrictOpen
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.VarietyLineBundle
import MiyaokaMori.AlgebraicGeometry.Modules.IdealSheaf.IdealSheafToModules
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.SheafOfModulesIsLineBundle
import MiyaokaMori.AlgebraicGeometry.Modules.Dual.ModulesDual
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.ModulesInternalHom
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffCartierLineBundle

/-! # Effective Cartier divisors on a scheme (`EffectiveCartierDivisor` interface)

Effective Cartier divisors on a scheme (Stacks 01WR): closed subschemes with invertible ideal sheaf,
and their line bundle `O_X(D) = I_D^{-1}` (Stacks 01WT). All declarations of this file are aliases of
the corresponding declarations for `AlgebraicGeometry.Scheme.EffCartier` (quasi-coherent ideal sheaves
locally generated by a nonzerodivisor).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- An effective Cartier divisor (Stacks 01WR): `X.EffCartier`, a quasi-coherent ideal sheaf that is
locally generated by a nonzerodivisor (`Statement.IsInvertibleIdeal`: every point has an affine
neighbourhood `U` and a nonzerodivisor `a` with `I(U) = (a)`). That the ideal sheaf is a line bundle
is a theorem (`EffCartier.ideal_isLineBundle`). -/
abbrev AlgebraicGeometry.EffectiveCartierDivisor (X : AlgebraicGeometry.Scheme.{u}) : Type u :=
  X.EffCartier

/-- The quasi-coherent ideal sheaf of `D` (Mathlib's `IdealSheafData`; the closed subscheme is
`D = V(I_D)`); this is `EffCartier.ideal`. -/
abbrev AlgebraicGeometry.EffectiveCartierDivisor.idealSheaf
    {X : AlgebraicGeometry.Scheme.{u}} (D : AlgebraicGeometry.EffectiveCartierDivisor X) :
    X.IdealSheafData :=
  AlgebraicGeometry.Scheme.EffCartier.ideal D

/-- The ideal sheaf is invertible as an `O_X`-module (Stacks 01WR): a local equation `a` gives a frame
of `I_D|_U`, and having frames is equivalent to being a line bundle (`EffCartier.ideal_isLineBundle`). -/
instance AlgebraicGeometry.EffectiveCartierDivisor.isLineBundle
    {X : AlgebraicGeometry.Scheme.{u}} (D : AlgebraicGeometry.EffectiveCartierDivisor X) :
    (AlgebraicGeometry.Scheme.IdealSheafData.toModules D.idealSheaf).IsLineBundle :=
  AlgebraicGeometry.Scheme.EffCartier.ideal_isLineBundle D

/-- `D` as a closed subscheme. -/

noncomputable abbrev AlgebraicGeometry.EffectiveCartierDivisor.toScheme
    {X : AlgebraicGeometry.Scheme.{u}} (D : AlgebraicGeometry.EffectiveCartierDivisor X) :
    AlgebraicGeometry.Scheme.{u} :=
  D.idealSheaf.subscheme

/-- `O_X(D) := I_D^{-1} = Hom(I_D, O_X)` (Stacks 01WX), namely `EffCartier.sheaf D = dualSheaf (toModules I_D)`
(packaged directly, without sheafification, so that `Γ(U, O_X(D))` is by definition the module of
compatible families of local functionals). It is isomorphic to the sheafified dual `Modules.dual`
(`dualSheafIsoOld`), but not definitionally equal to it. -/
noncomputable abbrev AlgebraicGeometry.EffectiveCartierDivisor.lineBundle
    {X : AlgebraicGeometry.Scheme.{u}} (D : AlgebraicGeometry.EffectiveCartierDivisor X) : X.Modules :=
  AlgebraicGeometry.Scheme.EffCartier.sheaf D

/-- `O_X(D)` is a line bundle (Stacks 01WT): the dual frame of a frame of `I_D` is a frame of `O_X(D)`
(`EffCartier.sheaf_isLineBundle`). -/
instance AlgebraicGeometry.EffectiveCartierDivisor.lineBundle_isLineBundle
    {X : AlgebraicGeometry.Scheme.{u}} (D : AlgebraicGeometry.EffectiveCartierDivisor X) :
    D.lineBundle.IsLineBundle :=
  AlgebraicGeometry.Scheme.EffCartier.sheaf_isLineBundle D

/-- The canonical section `1_D ∈ Γ(X, O_X(D))`: the family of components of the inclusion `I_D ↪ O_X`
(`kernel.ι`) on every open. This is `EffCartier.one D`, and `dualPair 1_D h x = idealIota I_D V x` holds
by `rfl`. -/
noncomputable abbrev AlgebraicGeometry.EffectiveCartierDivisor.canonicalSection
    {X : AlgebraicGeometry.Scheme.{u}} (D : AlgebraicGeometry.EffectiveCartierDivisor X) :
    (D.lineBundle.val.obj (Opposite.op ⊤) : Type u) :=
  AlgebraicGeometry.Scheme.EffCartier.one D

end
