import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Blowup.BlowupReesLiftMaps
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffCartierLineBundle
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.TensorSectionsBilinear
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.TwistPowerIsoSectionsGeneration
import MiyaokaMori.AlgebraicGeometry.Modules.Basic.SectionRestrictionSequenceMono
import MiyaokaMori.AlgebraicGeometry.Blowup.BlowupIsoAwayFromCenterAffineLeaf

/-! # The multiplication map `J^{⊗n} ⟶ O_Y` of an invertible ideal sheaf is a monomorphism

For an invertible ideal sheaf `J` (locally generated by a nonzerodivisor), the multiplication map
`μ_n = J.monoidalPowToUnit n : J^{⊗n} ⟶ O_Y` is a monomorphism. Used to cancel `μ_{m+n}` in the proof of
`LiftData.map_mul` for the Rees lift data (`Stacks0806_ReesLiftMapsMapMul`).

Route: mono ⇐ injective on all sections
(`SectionRestrictionSequenceAux.mono_of_injective_app`); if `μ_n(s) = 0` then, near every point, `J` has a frame `e`
(`EffCartier.exists_frame_ideal`), every section of `J^{⊗n}` is locally `c • e^{⊗n}` (`locMult_all`, induction on `n`
via "sections of `A ⊗ B` are locally sums of pure tensors"), `μ_n(e^{⊗n}) = (ι e)^n` (`monoidalPowToUnit_app_mpFrame`),
and `ι e` is a nonzerodivisor, so `c = 0`; conclude by separatedness of the sheaf `J^{⊗n}`.

Auxiliary material (namespace `Modules.MonoidalPowToUnitMonoAux`): `mpFrame e n = e^{⊗n} ∈ Γ(L^{⊗n}, W)` in the
`monoidalPow` encoding (`tensorSections` recursion), `mpFrame_res`, the computation `monoidalPowToUnit_app_mpFrame`,
the predicate `LocMult` ("locally a multiple of `e^{⊗n}`") with `zero`/`add`/`tmul`, the local pure-tensor lemma
`exists_locally_sheafifyTensorTo` for `A ⊗ B`, and `locMult_all`.

Source: Stacks 01WQ (an invertible ideal sheaf is a line bundle, locally `J = (g)` with `g` a nonzerodivisor);
Stacks 0806 (where the identification `J^{⊗n} ≅ Jⁿ` is used).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry CategoryTheory.MonoidalCategory

noncomputable section

namespace AlgebraicGeometry.Scheme.Modules.MonoidalPowToUnitMonoAux

set_option backward.isDefEq.respectTransparency false

variable {X : AlgebraicGeometry.Scheme.{u}}

/-- `e^{⊗n} ∈ Γ(L^{⊗n}, W)` for a section `e ∈ Γ(L, W)`, in the monoidal encoding `monoidalPow`:
`e^{⊗0} = 1` (transported along `𝟙_ ≅ O_X`), `e^{⊗(n+1)} = e^{⊗n} ⊗ e` (`tensorSections`). -/
def mpFrame (L : X.Modules) {W : X.Opens} (e : Γ(L, W)) :
    (n : ℕ) → Γ(AlgebraicGeometry.Scheme.Modules.monoidalPow L n, W)
  | 0 => (AlgebraicGeometry.Scheme.IdealSheafData.monoidalUnitIso X).inv.app W (1 : Γ(X, W))
  | n + 1 => AlgebraicGeometry.Scheme.Modules.tensorSections
      (AlgebraicGeometry.Scheme.Modules.monoidalPow L n) L W (mpFrame L e n) e

theorem mpFrame_zero (L : X.Modules) {W : X.Opens} (e : Γ(L, W)) :
    mpFrame L e 0 =
      (AlgebraicGeometry.Scheme.IdealSheafData.monoidalUnitIso X).inv.app W (1 : Γ(X, W)) := rfl

theorem mpFrame_succ (L : X.Modules) {W : X.Opens} (e : Γ(L, W)) (n : ℕ) :
    mpFrame L e (n + 1) = AlgebraicGeometry.Scheme.Modules.tensorSections
      (AlgebraicGeometry.Scheme.Modules.monoidalPow L n) L W (mpFrame L e n) e := rfl

/-- Restriction of `1 ∈ Γ(O_X, W)`. -/
theorem unit_res_one {W W' : X.Opens} (h : W' ≤ W) :
    AlgebraicGeometry.Scheme.Modules.res (SheafOfModules.unit X.ringCatSheaf : X.Modules) h
      (1 : Γ(X, W)) = (1 : Γ(X, W')) := by
  change (X.presheaf.map (homOfLE h).op).hom (1 : Γ(X, W)) = 1
  exact map_one _

/-- `e^{⊗n}` commutes with restriction. -/
theorem mpFrame_res (L : X.Modules) {W W' : X.Opens} (h : W' ≤ W) (e : Γ(L, W)) (n : ℕ) :
    (AlgebraicGeometry.Scheme.Modules.monoidalPow L n).res h (mpFrame L e n) =
      mpFrame L (L.res h e) n := by
  induction n with
  | zero =>
    rw [mpFrame_zero, mpFrame_zero]
    have := (AlgebraicGeometry.Scheme.GradedQCAlgebra.GenAux.app_map_res
      (AlgebraicGeometry.Scheme.IdealSheafData.monoidalUnitIso X).inv h (1 : Γ(X, W))).symm
    change (𝟙_ X.Modules).presheaf.map (homOfLE h).op
      ((AlgebraicGeometry.Scheme.IdealSheafData.monoidalUnitIso X).inv.app W (1 : Γ(X, W))) = _
    rw [this]
    exact congrArg _ (unit_res_one h)
  | succ n ih =>
    rw [mpFrame_succ, mpFrame_succ]
    change (AlgebraicGeometry.Scheme.Modules.monoidalPow L n ⊗ L).presheaf.map (homOfLE h).op
      (AlgebraicGeometry.Scheme.Modules.tensorSections _ L W (mpFrame L e n) e) = _
    rw [AlgebraicGeometry.Scheme.GradedQCAlgebra.GenAux.tensorSections_map h]
    exact congrArg (fun z => AlgebraicGeometry.Scheme.Modules.tensorSections _ L W' z _) ih

/-! ### The computation `μ_n(e^{⊗n}) = (ι e)^n` -/

section Computation

variable {Y : AlgebraicGeometry.Scheme.{u}}

local notation "ε" => AlgebraicGeometry.Scheme.IdealSheafData.monoidalUnitIso Y

/-- `(φ ⊗ₘ ψ)` on a pure tensor, `Hom.app` spelling. -/
theorem tensorHom_app_tensorSections' {A B A' B' : Y.Modules} (φ : A ⟶ A') (ψ : B ⟶ B')
    (U : Y.Opens) (a : Γ(A, U)) (b : Γ(B, U)) :
    (φ ⊗ₘ ψ).app U (AlgebraicGeometry.Scheme.Modules.tensorSections A B U a b) =
      AlgebraicGeometry.Scheme.Modules.tensorSections A' B' U (φ.app U a) (ψ.app U b) :=
  AlgebraicGeometry.Scheme.Modules.tensorHom_tensorSections φ ψ U a b

/-- `ε.hom ∘ ε.inv = id` on sections. -/
theorem monoidalUnitIso_hom_app_inv_app (U : Y.Opens) (x : Γ(Y, U)) :
    (ε).hom.app U ((ε).inv.app U x) = x := by
  rw [← AlgebraicGeometry.Scheme.GradedQCAlgebra.GenAux.comp_app_apply, (ε).inv_hom_id]
  rfl

/-- **`μ_n(e^{⊗n}) = (ι e)^n`** for any section `e ∈ Γ(J, W)`: each factor of `monoidalPowMap ι n`
sends `e ↦ ι e` (`tensorHom_tensorSections`), `unitPowCollapse` multiplies the factors
(`leftUnitor_app_tensorSections`: `r ⊗ a ↦ r • a = r·a` on `O_Y`), and `monoidalUnitIso` is the
identity on sections. -/
theorem monoidalPowToUnit_app_mpFrame (J : Y.IdealSheafData) {W : Y.Opens}
    (e : Γ(J.toModules, W)) (n : ℕ) :
    ((J.monoidalPowToUnit n).app W (mpFrame J.toModules e n) : Γ(Y, W)) =
      (AlgebraicGeometry.Scheme.EffCartier.idealIota J W e) ^ n := by
  induction n with
  | zero =>
    rw [AlgebraicGeometry.Scheme.IdealSheafData.monoidalPowToUnit_zero, mpFrame_zero, pow_zero]
    exact monoidalUnitIso_hom_app_inv_app W 1
  | succ n ih =>
    rw [mpFrame_succ, pow_succ]
    set ι := AlgebraicGeometry.Scheme.EffCartier.idealIncl J with hι
    set a := mpFrame J.toModules e n with ha
    -- unfold `μ_{n+1}`
    have e1 : (J.monoidalPowToUnit (n + 1)).app W
        (AlgebraicGeometry.Scheme.Modules.tensorSections
          (AlgebraicGeometry.Scheme.Modules.monoidalPow J.toModules n) J.toModules W a e) =
        (ε).hom.app W ((λ_ (𝟙_ Y.Modules)).hom.app W
          ((AlgebraicGeometry.Scheme.Modules.unitPowCollapse Y n ▷ 𝟙_ Y.Modules).app W
            ((AlgebraicGeometry.Scheme.Modules.monoidalPowMap ι n ⊗ₘ ι).app W
              (AlgebraicGeometry.Scheme.Modules.tensorSections
                (AlgebraicGeometry.Scheme.Modules.monoidalPow J.toModules n) J.toModules W a e)))) := rfl
    -- the tensor factor
    have e2 := tensorHom_app_tensorSections' (AlgebraicGeometry.Scheme.Modules.monoidalPowMap ι n) ι W a e
    -- the collapse on the left factor
    set a' := (AlgebraicGeometry.Scheme.Modules.monoidalPowMap ι n).app W a with ha'
    set b' := ι.app W e with hb'
    have e3 : (AlgebraicGeometry.Scheme.Modules.unitPowCollapse Y n ▷ 𝟙_ Y.Modules).app W
        (AlgebraicGeometry.Scheme.Modules.tensorSections
          (AlgebraicGeometry.Scheme.Modules.monoidalPow (𝟙_ Y.Modules) n) (𝟙_ Y.Modules) W a' b') =
        AlgebraicGeometry.Scheme.Modules.tensorSections (𝟙_ Y.Modules) (𝟙_ Y.Modules) W
          ((AlgebraicGeometry.Scheme.Modules.unitPowCollapse Y n).app W a') b' :=
      AlgebraicGeometry.Scheme.GradedQCAlgebra.GenAux.whiskerRight_app_tensorSections
        (AlgebraicGeometry.Scheme.Modules.unitPowCollapse Y n) W a' b'
    set r := (AlgebraicGeometry.Scheme.Modules.unitPowCollapse Y n).app W a' with hr
    -- the left unitor
    have e4 : (λ_ (𝟙_ Y.Modules)).hom.app W
        (AlgebraicGeometry.Scheme.Modules.tensorSections (𝟙_ Y.Modules) (𝟙_ Y.Modules) W r b') =
        r • b' :=
      AlgebraicGeometry.Scheme.Modules.leftUnitor_app_tensorSections (𝟙_ Y.Modules) W r b'
    -- `ε` and the scalar action of the unit
    have e5 : ((ε).hom.app W (r • b') : Γ(Y, W)) =
        (show Γ(Y, W) from r) * (show Γ(Y, W) from b') :=
      (AlgebraicGeometry.Scheme.IdealSheafData.monoidalUnitIso_hom_app W (r • b')).trans
        (AlgebraicGeometry.Scheme.IdealSheafData.smul_monoidalUnit_eq_mul W r b')
    -- the induction hypothesis identifies `r`
    have e6 : (show Γ(Y, W) from r) = (AlgebraicGeometry.Scheme.EffCartier.idealIota J W e) ^ n := by
      rw [← ih]
      exact (AlgebraicGeometry.Scheme.IdealSheafData.monoidalUnitIso_hom_app W r).symm
    have e7 : (show Γ(Y, W) from b') = AlgebraicGeometry.Scheme.EffCartier.idealIota J W e := rfl
    rw [e1, e2]
    change (ε).hom.app W ((λ_ (𝟙_ Y.Modules)).hom.app W
      ((AlgebraicGeometry.Scheme.Modules.unitPowCollapse Y n ▷ 𝟙_ Y.Modules).app W
        (AlgebraicGeometry.Scheme.Modules.tensorSections
          (AlgebraicGeometry.Scheme.Modules.monoidalPow (𝟙_ Y.Modules) n) (𝟙_ Y.Modules) W a' b'))) = _
    rw [e3, e4, e5, e6, e7]

end Computation

/-! ### Sections of `L^{⊗n}` over a frame open are locally multiples of `e^{⊗n}` -/

section LocMult

variable {X : AlgebraicGeometry.Scheme.{u}}

/-- `ε.inv` is the identity on sections (`Hom.app` spelling). -/
theorem monoidalUnitIso_inv_app' (U : X.Opens) (x : Γ(X, U)) :
    (((AlgebraicGeometry.Scheme.IdealSheafData.monoidalUnitIso X).inv.app U x : Γ(𝟙_ X.Modules, U)) :
      Γ(X, U)) = x :=
  AlgebraicGeometry.Scheme.IdealSheafData.monoidalUnitIso_inv_app U x

/-- `t ∈ Γ(L^{⊗n}, W')` (`W' ≤ W`) is, near every point of `W'`, a multiple of `e^{⊗n}`. -/
def LocMult (L : X.Modules) {W : X.Opens} (e : Γ(L, W)) (n : ℕ) {W' : X.Opens} (hW' : W' ≤ W)
    (t : Γ(AlgebraicGeometry.Scheme.Modules.monoidalPow L n, W')) : Prop :=
  ∀ p ∈ W', ∃ (V : X.Opens) (hV : V ≤ W'), p ∈ V ∧
    ∃ c : Γ(X, V), (AlgebraicGeometry.Scheme.Modules.monoidalPow L n).res hV t =
      c • mpFrame L (L.res (hV.trans hW') e) n

theorem LocMult.zero (L : X.Modules) {W : X.Opens} (e : Γ(L, W)) (n : ℕ) {W' : X.Opens}
    (hW' : W' ≤ W) : LocMult L e n hW' 0 :=
  fun _ hp => ⟨W', le_rfl, hp, 0, by
    have h0 : (AlgebraicGeometry.Scheme.Modules.monoidalPow L n).res le_rfl
        (0 : Γ(AlgebraicGeometry.Scheme.Modules.monoidalPow L n, W')) = 0 := map_zero _
    rw [h0, zero_smul]⟩

theorem LocMult.add {L : X.Modules} {W : X.Opens} {e : Γ(L, W)} {n : ℕ} {W' : X.Opens}
    {hW' : W' ≤ W} {t₁ t₂ : Γ(AlgebraicGeometry.Scheme.Modules.monoidalPow L n, W')}
    (h₁ : LocMult L e n hW' t₁) (h₂ : LocMult L e n hW' t₂) : LocMult L e n hW' (t₁ + t₂) := by
  intro p hp
  obtain ⟨V₁, hV₁, hp₁, c₁, hc₁⟩ := h₁ p hp
  obtain ⟨V₂, hV₂, hp₂, c₂, hc₂⟩ := h₂ p hp
  refine ⟨V₁ ⊓ V₂, inf_le_left.trans hV₁, ⟨hp₁, hp₂⟩,
    X.presheaf.map (homOfLE (inf_le_left : V₁ ⊓ V₂ ≤ V₁)).op c₁ +
      X.presheaf.map (homOfLE (inf_le_right : V₁ ⊓ V₂ ≤ V₂)).op c₂, ?_⟩
  have e₁ := congrArg ((AlgebraicGeometry.Scheme.Modules.monoidalPow L n).res
    (inf_le_left : V₁ ⊓ V₂ ≤ V₁)) hc₁
  have e₂ := congrArg ((AlgebraicGeometry.Scheme.Modules.monoidalPow L n).res
    (inf_le_right : V₁ ⊓ V₂ ≤ V₂)) hc₂
  rw [AlgebraicGeometry.Scheme.Modules.res_res, AlgebraicGeometry.Scheme.Modules.res_smul,
    mpFrame_res, AlgebraicGeometry.Scheme.Modules.res_res] at e₁ e₂
  have hadd : (AlgebraicGeometry.Scheme.Modules.monoidalPow L n).res
        ((inf_le_left : V₁ ⊓ V₂ ≤ V₁).trans hV₁) (t₁ + t₂) =
      (AlgebraicGeometry.Scheme.Modules.monoidalPow L n).res ((inf_le_left : V₁ ⊓ V₂ ≤ V₁).trans hV₁) t₁ +
        (AlgebraicGeometry.Scheme.Modules.monoidalPow L n).res ((inf_le_left : V₁ ⊓ V₂ ≤ V₁).trans hV₁) t₂ :=
    map_add _ _ _
  rw [hadd, add_smul, e₁, e₂]

theorem LocMult.tmul {L : X.Modules} {W : X.Opens} {e : Γ(L, W)}
    (he : AlgebraicGeometry.Scheme.Modules.IsFrame L W e) {n : ℕ} {W' : X.Opens} {hW' : W' ≤ W}
    {a : Γ(AlgebraicGeometry.Scheme.Modules.monoidalPow L n, W')} (ha : LocMult L e n hW' a)
    (b : Γ(L, W')) :
    LocMult L e (n + 1) hW' (AlgebraicGeometry.Scheme.Modules.tensorSections
      (AlgebraicGeometry.Scheme.Modules.monoidalPow L n) L W' a b) := by
  intro p hp
  obtain ⟨V, hV, hpV, c, hc⟩ := ha p hp
  obtain ⟨d, hd⟩ : ∃ d : Γ(X, W'), d = he.coord hW' b := ⟨_, rfl⟩
  have hb : b = d • L.res hW' e := by rw [hd]; exact (he.coord_smul_frame hW' b).symm
  refine ⟨V, hV, hpV, X.presheaf.map (homOfLE hV).op d * c, ?_⟩
  change (AlgebraicGeometry.Scheme.Modules.monoidalPow L n ⊗ L).presheaf.map (homOfLE hV).op
    (AlgebraicGeometry.Scheme.Modules.tensorSections _ L W' a b) = _
  rw [AlgebraicGeometry.Scheme.GradedQCAlgebra.GenAux.tensorSections_map hV, hb]
  change AlgebraicGeometry.Scheme.Modules.tensorSections _ L V
    ((AlgebraicGeometry.Scheme.Modules.monoidalPow L n).res hV a)
    (L.res hV (d • L.res hW' e)) = _
  rw [hc, AlgebraicGeometry.Scheme.Modules.res_smul, AlgebraicGeometry.Scheme.Modules.res_res,
    AlgebraicGeometry.Scheme.Modules.tensorSections_smul_right _ _ _ _ _ _ _ rfl,
    AlgebraicGeometry.Scheme.Modules.tensorSections_smul_left _ _ _ _ _ _ _ rfl, smul_smul]
  rfl

/-- Sections of `A ⊗ B` are locally in the image of the pure-tensor presheaf: near every point,
`y` restricts to `sheafifyTensorTo (η z)` for a section `z` of the presheaf tensor product
(`GenAux.exists_tensor_unit_app_eq_map` transported along `Modules.tensor A B ≅ A ⊗ B`). -/
theorem exists_locally_sheafifyTensorTo (A B : X.Modules) (U : X.Opens)
    (y : Γ(A ⊗ B, U)) (p : X) (hp : p ∈ U) :
    ∃ (V : X.Opens) (hVU : V ≤ U), p ∈ V ∧
      ∃ z : (CategoryTheory.MonoidalCategoryStruct.tensorObj
        ((SheafOfModules.forget X.ringCatSheaf ⋙
          _root_.PresheafOfModules.restrictScalars (𝟙 X.ringCatSheaf.obj)).obj A)
        ((SheafOfModules.forget X.ringCatSheaf ⋙
          _root_.PresheafOfModules.restrictScalars (𝟙 X.ringCatSheaf.obj)).obj B)).obj (op V),
      (AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj A B).hom.app V
        (((_root_.PresheafOfModules.sheafificationAdjunction (𝟙 X.ringCatSheaf.obj)).unit.app
          (CategoryTheory.MonoidalCategoryStruct.tensorObj
            ((SheafOfModules.forget X.ringCatSheaf ⋙
              _root_.PresheafOfModules.restrictScalars (𝟙 X.ringCatSheaf.obj)).obj A)
            ((SheafOfModules.forget X.ringCatSheaf ⋙
              _root_.PresheafOfModules.restrictScalars (𝟙 X.ringCatSheaf.obj)).obj B))).app (op V) z) =
        (A ⊗ B).res hVU y := by
  obtain ⟨V, hVU, hpV, z, hz⟩ := AlgebraicGeometry.Scheme.GradedQCAlgebra.GenAux.exists_tensor_unit_app_eq_map
    A B U ((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj A B).inv.app U y) p hp
  refine ⟨V, hVU, hpV, z, ?_⟩
  have h1 : (AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj A B).hom.app V
      ((AlgebraicGeometry.Scheme.Modules.tensor A B).presheaf.map (homOfLE hVU).op
        ((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj A B).inv.app U y)) =
      (A ⊗ B).res hVU y := by
    rw [AlgebraicGeometry.Scheme.GradedQCAlgebra.GenAux.app_map_res]
    exact congrArg _ (AlgebraicGeometry.Scheme.GradedQCAlgebra.GenAux.tensorIsoTensorObj_hom_app_inv_app U y)
  rw [← h1]
  exact congrArg _ hz

/-- **Every section of `L^{⊗n}` over `W' ≤ W` is locally a multiple of `e^{⊗n}`**, for a frame `e` of
`L` on `W`. Induction on `n`: `n = 0` is `t = t • 1`; for `n + 1`, a section of `L^{⊗n} ⊗ L` is locally
a sum of pure tensors `a ⊗ b` (`exists_locally_sheafifyTensorTo`), `b = r • e`, and `a` is locally
`c • e^{⊗n}` by induction. -/
theorem locMult_all (L : X.Modules) {W : X.Opens} {e : Γ(L, W)}
    (he : AlgebraicGeometry.Scheme.Modules.IsFrame L W e) (n : ℕ) :
    ∀ (W' : X.Opens) (hW' : W' ≤ W) (t : Γ(AlgebraicGeometry.Scheme.Modules.monoidalPow L n, W')),
      LocMult L e n hW' t := by
  induction n with
  | zero =>
    intro W' hW' t p hp
    refine ⟨W', le_rfl, hp, (show Γ(X, W') from t), ?_⟩
    rw [AlgebraicGeometry.Scheme.Modules.res_self, mpFrame_zero]
    have h := AlgebraicGeometry.Scheme.IdealSheafData.smul_monoidalUnit_eq_mul W' (show Γ(X, W') from t)
      ((AlgebraicGeometry.Scheme.IdealSheafData.monoidalUnitIso X).inv.app W' (1 : Γ(X, W')))
    rw [monoidalUnitIso_inv_app', mul_one] at h
    exact h.symm
  | succ n ih =>
    intro W' hW' y p hp
    obtain ⟨V, hVW', hpV, z, hz⟩ := exists_locally_sheafifyTensorTo
      (AlgebraicGeometry.Scheme.Modules.monoidalPow L n) L W' y p hp
    have key : ∀ z, LocMult L e (n + 1) (hVW'.trans hW')
        ((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj
          (AlgebraicGeometry.Scheme.Modules.monoidalPow L n) L).hom.app V
          (((_root_.PresheafOfModules.sheafificationAdjunction (𝟙 X.ringCatSheaf.obj)).unit.app
            (CategoryTheory.MonoidalCategoryStruct.tensorObj
              ((SheafOfModules.forget X.ringCatSheaf ⋙
                _root_.PresheafOfModules.restrictScalars (𝟙 X.ringCatSheaf.obj)).obj
                  (AlgebraicGeometry.Scheme.Modules.monoidalPow L n))
              ((SheafOfModules.forget X.ringCatSheaf ⋙
                _root_.PresheafOfModules.restrictScalars (𝟙 X.ringCatSheaf.obj)).obj L))).app (op V) z)) := by
      intro z
      induction z using TensorProduct.induction_on with
      | zero =>
        rw [map_zero, map_zero]
        exact LocMult.zero L e (n + 1) _
      | tmul a b =>
        exact (ih V (hVW'.trans hW') a).tmul he b
      | add z₁ z₂ h₁ h₂ =>
        rw [map_add, map_add]
        exact h₁.add h₂
    have hk := key z
    rw [hz] at hk
    obtain ⟨V', hV', hpV', c, hc⟩ := hk p hpV
    refine ⟨V', hV'.trans hVW', hpV', c, ?_⟩
    rw [← AlgebraicGeometry.Scheme.Modules.res_res _ hV' hVW']
    exact hc

end LocMult

/-! ### Assembly -/

section Assembly

variable {Y : AlgebraicGeometry.Scheme.{u}}

/-- If `μ_n(s) = 0` then `s = 0`: near every point `s` is `c • e^{⊗n}` for a frame `e` of `J` with
`ι e` a nonzerodivisor (`exists_frame_ideal`, `locMult_all`), `μ_n(c • e^{⊗n}) = c·(ι e)^n`
(`monoidalPowToUnit_app_mpFrame`), so `c = 0`; conclude by separatedness of the sheaf `J^{⊗n}`. -/
theorem eq_zero_of_monoidalPowToUnit_app_eq_zero (J : Y.IdealSheafData)
    (hJ : MiyaokaMori.Statement.IsInvertibleIdeal J) (n : ℕ) (U : Y.Opens)
    (s : Γ(AlgebraicGeometry.Scheme.Modules.monoidalPow J.toModules n, U))
    (hs : (J.monoidalPowToUnit n).app U s = 0) : s = 0 := by
  have key : ∀ p : U, ∃ (V : Y.Opens) (hV : V ≤ U), p.1 ∈ V ∧
      (AlgebraicGeometry.Scheme.Modules.monoidalPow J.toModules n).res hV s = 0 := by
    rintro ⟨p, hp⟩
    obtain ⟨W, hpW, e, he⟩ := AlgebraicGeometry.Scheme.EffCartier.exists_frame_ideal ⟨J, hJ⟩ p
    have he : AlgebraicGeometry.Scheme.Modules.IsFrame J.toModules W e := he
    have hW₁ : U ⊓ W ≤ W := inf_le_right
    obtain ⟨V, hV, hpV, c, hc⟩ := locMult_all J.toModules he n (U ⊓ W) hW₁
      ((AlgebraicGeometry.Scheme.Modules.monoidalPow J.toModules n).res (inf_le_left : U ⊓ W ≤ U) s)
      p ⟨hp, hpW⟩
    rw [AlgebraicGeometry.Scheme.Modules.res_res] at hc
    refine ⟨V, hV.trans inf_le_left, hpV, ?_⟩
    rw [hc]
    set e' := J.toModules.res (hV.trans hW₁) e with he'
    have he'f : AlgebraicGeometry.Scheme.Modules.IsFrame J.toModules V e' := he.restrict _
    -- `g := ι e'` is a nonzerodivisor on `V`
    have hg : AlgebraicGeometry.Scheme.EffCartier.idealIota J V e' ∈ nonZeroDivisors Γ(Y, V) := by
      refine mem_nonZeroDivisors_iff_right.mpr fun r hr => ?_
      have h1 : AlgebraicGeometry.Scheme.EffCartier.idealIota J V (r • e') =
          AlgebraicGeometry.Scheme.EffCartier.idealIota J V 0 := by
        rw [_root_.map_smul, map_zero, smul_eq_mul]; exact hr
      have h2 := AlgebraicGeometry.Scheme.EffCartier.idealIota_injective J V h1
      apply (he'f V le_rfl).1
      show r • J.toModules.res le_rfl e' = (0 : Γ(Y, V)) • J.toModules.res le_rfl e'
      rw [AlgebraicGeometry.Scheme.Modules.res_self, h2, zero_smul]
    -- `μ_n(c • e'^{⊗n}) = c · g^n = 0`
    have h4 : (J.monoidalPowToUnit n).app V
        ((AlgebraicGeometry.Scheme.Modules.monoidalPow J.toModules n).res (hV.trans inf_le_left) s) = 0 := by
      rw [AlgebraicGeometry.Scheme.GradedQCAlgebra.GenAux.app_map_res, hs, map_zero]
    rw [hc, AlgebraicGeometry.Scheme.Modules.Hom.app_smul] at h4
    have h5 : c * (AlgebraicGeometry.Scheme.EffCartier.idealIota J V e') ^ n = 0 := by
      rw [← monoidalPowToUnit_app_mpFrame J e' n]
      exact h4
    have hc0 : c = 0 := (mem_nonZeroDivisors_iff_right.mp (pow_mem hg n)) c h5
    rw [hc0, zero_smul]
  choose V hV hpV hzero using key
  exact TopCat.Sheaf.eq_of_locally_eq'
    ⟨(AlgebraicGeometry.Scheme.Modules.monoidalPow J.toModules n).presheaf,
      (AlgebraicGeometry.Scheme.Modules.monoidalPow J.toModules n).isSheaf⟩
    V U (fun p => homOfLE (hV p))
    (fun x hx => TopologicalSpace.Opens.mem_iSup.mpr ⟨⟨x, hx⟩, hpV ⟨x, hx⟩⟩) s 0
    (fun p => by rw [map_zero]; exact hzero p)

end Assembly

end AlgebraicGeometry.Scheme.Modules.MonoidalPowToUnitMonoAux

/-- **`μ_n : J^{⊗n} ⟶ O_Y` is a monomorphism when `J` is invertible.** (Stacks 01WQ.)

Proof.
1. **Reduction to sections.** A morphism of `O_Y`-modules injective on sections over every open is a
   monomorphism (`SectionRestrictionSequenceAux.mono_of_injective_app`); by linearity it suffices that
   `μ_n(s) = 0 ⇒ s = 0` (`MonoidalPowToUnitMonoAux.eq_zero_of_monoidalPowToUnit_app_eq_zero`).
2. **Local frames.** By `hJ`, `⟨J, hJ⟩ : Y.EffCartier`, and `EffCartier.exists_frame_ideal` gives, near every
   point `p ∈ U`, an open `W ∋ p` and a frame `e ∈ Γ(W, J)` of `J.toModules` (every section over `W' ≤ W` is
   uniquely `r • e|_{W'}`). Then `g := ι e` is a nonzerodivisor on every `W' ≤ W`: `r·g = 0 ⇒ ι(r • e) = 0 ⇒
   r • e = 0` (`idealIota_injective`) `⇒ r = 0` (frame).
3. **Frame powers.** `e^{⊗n} := mpFrame e n ∈ Γ(W, J^{⊗n})` (`1` for `n = 0`, `e^{⊗n} ⊗ e` via `tensorSections`).
   Every section of `J^{⊗n}` over `W' ≤ W` is *locally* `c • e^{⊗n}` (`locMult_all`): induction on `n`; a section
   of `J^{⊗n} ⊗ J` is locally a sum of pure tensors `a ⊗ b` (`exists_locally_sheafifyTensorTo`, from the
   sheafification unit being locally surjective), `b = r • e`, and `a` is locally `c • e^{⊗n}` by induction.
4. **Computation.** `μ_n(e^{⊗n}) = gⁿ` (`monoidalPowToUnit_app_mpFrame`): `monoidalPowMap ι n` acts factorwise
   (`tensorHom_tensorSections`), `unitPowCollapse` multiplies (`(λ_ 𝟙_).hom` is `r ⊗ a ↦ r • a`,
   `leftUnitor_app_tensorSections`), and `monoidalUnitIso` is the identity on sections (`monoidalUnitIso_hom_app`,
   `smul_monoidalUnit_eq_mul`). Hence `μ_n(c • e^{⊗n}) = c·gⁿ`.
5. **Conclusion.** If `μ_n(s) = 0`, then near each `p ∈ U`, `s|_V = c • e^{⊗n}|_V` and `c·gⁿ = 0` with `gⁿ` a
   nonzerodivisor (`pow_mem`), so `c = 0` and `s|_V = 0`; by separatedness of the sheaf `J^{⊗n}`
   (`TopCat.Sheaf.eq_of_locally_eq'`), `s = 0`.

Edge cases. `n = 0`: `μ_0 = monoidalUnitIso.hom` (`monoidalPowToUnit_zero`), an isomorphism; the argument covers
it (`e^{⊗0} = 1`, `g⁰ = 1`). `Y = ∅`: trivial. `J = ⊤`: `g` a unit. `J = ⊥` is excluded by `hJ` unless `Y = ∅`. -/
theorem AlgebraicGeometry.Scheme.IdealSheafData.monoidalPowToUnit_mono
    {Y : AlgebraicGeometry.Scheme.{u}} (J : Y.IdealSheafData)
    (hJ : MiyaokaMori.Statement.IsInvertibleIdeal J) (n : ℕ) :
    CategoryTheory.Mono (J.monoidalPowToUnit n) := by
  apply AlgebraicGeometry.Scheme.Modules.SectionRestrictionSequenceAux.mono_of_injective_app
  intro U s t hst
  rw [← sub_eq_zero]
  exact AlgebraicGeometry.Scheme.Modules.MonoidalPowToUnitMonoAux.eq_zero_of_monoidalPowToUnit_app_eq_zero
    J hJ n U (s - t) (by rw [map_sub, hst, sub_self])

end
