import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.Frame

/-! # Regular sections and zero ideals

(1) A global section `s` of a module sheaf `M` is a **regular section** (`IsRegularSection`) if for every
open `U` and `r ∈ Γ(X, U)`, `r • s|_U = 0` implies `r = 0` (i.e. `O_X →s M` is a monomorphism; the
regular sections of Stacks 01WX). In any frame the coordinate of `s` is a nonzerodivisor
(`coord_mem_nonZeroDivisors`).
(2) An ideal sheaf `I` is the **zero ideal** of `(M, s)` (`IsZeroIdeal I M s`) if on every affine open
`W` with a frame `e`, `I(W)` is generated by the coordinate of `s` in `e`. On a line bundle the zero
ideal is unique (`IsZeroIdeal.unique`); the construction `zeroIdeal M s` uses Mathlib's
`IdealSheafData.ofIdeals` (no proof obligation in the definition), and its characterization is the
theorem `zeroIdeal_isZeroIdeal`.
Design: "local equation = coordinate" is taken as the relation `IsZeroIdeal`, since this is what the
applications use; given `D`, finding `(L, s)` needs no construction, and constructing `D` from `(L, s)`
uses `zeroIdeal`. Sources: Stacks 01WX, 01X0.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory Opposite TopologicalSpace

noncomputable section

namespace AlgebraicGeometry.Scheme.Modules

set_option backward.isDefEq.respectTransparency false

variable {X : Scheme.{u}}

/-- A regular section: on every open, `r • s| = 0` implies `r = 0`. -/
def IsRegularSection (M : X.Modules) (s : Γ(M, ⊤)) : Prop :=
  ∀ (U : X.Opens) (r : Γ(X, U)), r • M.res (le_top : U ≤ ⊤) s = 0 → r = 0

/-- Equivalent formulation: on every open, `r ↦ r • s|` is injective. -/
theorem isRegularSection_iff_injective (M : X.Modules) (s : Γ(M, ⊤)) :
    IsRegularSection M s ↔
      ∀ U : X.Opens, Function.Injective (fun r : Γ(X, U) => r • M.res (le_top : U ≤ ⊤) s) := by
  constructor
  · intro h U r r' hr
    have : (r - r') • M.res (le_top : U ≤ ⊤) s = 0 := by
      rw [sub_smul]; exact sub_eq_zero.mpr hr
    exact sub_eq_zero.mp (h U _ this)
  · intro h U r hr
    exact h U (by simpa using hr)

/-- The coordinate of a regular section in any frame is a nonzerodivisor. -/
theorem IsRegularSection.coord_mem_nonZeroDivisors {M : X.Modules} {s : Γ(M, ⊤)}
    (hs : IsRegularSection M s) {W : X.Opens} {e : Γ(M, W)} (hf : IsFrame M W e) :
    hf.coord le_rfl (M.res le_top s) ∈ nonZeroDivisors Γ(X, W) := by
  rw [mem_nonZeroDivisors_iff_right]
  intro r hr
  apply hs W r
  rw [← hf.coord_eq_zero_iff le_rfl, hf.coord_smul]
  exact hr

/-- A regular section is nonzero (when `Γ(X, ⊤)` is nontrivial, e.g. when `X` is nonempty). -/
theorem IsRegularSection.ne_zero [Nontrivial Γ(X, ⊤)] {M : X.Modules} {s : Γ(M, ⊤)}
    (hs : IsRegularSection M s) : s ≠ 0 := by
  rintro rfl
  have h := hs ⊤ 1 (by simp)
  exact one_ne_zero h

/-- `I` is the zero ideal of `(M, s)`: on every affine open with a frame, `I` is generated by the
coordinate of `s`. -/
def IsZeroIdeal (I : X.IdealSheafData) (M : X.Modules) (s : Γ(M, ⊤)) : Prop :=
  ∀ (W : X.affineOpens) (e : Γ(M, W.1)) (hf : IsFrame M W.1 e),
    I.ideal W = Ideal.span {hf.coord le_rfl (M.res le_top s)}

/-- On a line bundle the zero ideal is unique. -/
theorem IsZeroIdeal.unique {I J : X.IdealSheafData} {M : X.Modules} [M.IsLineBundle] {s : Γ(M, ⊤)}
    (hI : IsZeroIdeal I M s) (hJ : IsZeroIdeal J M s) : I = J := by
  have key : ∀ x : X, ∃ W : X.affineOpens, x ∈ W.1 ∧ I.ideal W = J.ideal W := by
    intro x
    obtain ⟨W, hW, -, hx, e, he⟩ := exists_affine_frame_le M (U := ⊤) (p := x) trivial
    exact ⟨⟨W, hW⟩, hx, (hI ⟨W, hW⟩ e he).trans (hJ ⟨W, hW⟩ e he).symm⟩
  choose W hxW hW using key
  refine IdealSheafData.ext_of_iSup_eq_top W ?_ hW
  exact top_le_iff.mp fun x _ => TopologicalSpace.Opens.mem_iSup.mpr ⟨x, hxW x⟩

/-- The construction of the zero ideal of `(M, s)`: the largest ideal sheaf contained in the family of
ideals "divisible everywhere by the local equation". The definition has no proof obligation; the
characterization is `zeroIdeal_isZeroIdeal`. -/
def zeroIdeal (M : X.Modules) (s : Γ(M, ⊤)) : X.IdealSheafData :=
  IdealSheafData.ofIdeals fun U =>
    { carrier := {r | ∀ (W : X.Opens) (h : W ≤ U.1) (e : Γ(M, W)) (hf : IsFrame M W e),
        hf.coord le_rfl (M.res le_top s) ∣ X.presheaf.map (homOfLE h).op r}
      add_mem' := fun ha hb W h e hf => by
        rw [map_add]; exact dvd_add (ha W h e hf) (hb W h e hf)
      zero_mem' := fun W h e hf => by rw [map_zero]; exact dvd_zero _
      smul_mem' := fun c r hr W h e hf => by
        rw [smul_eq_mul, map_mul]; exact Dvd.dvd.mul_left (hr W h e hf) _ }

/-- Affine sections of the zero ideal are divisible by the local equation. -/
theorem zeroIdeal_dvd (M : X.Modules) (s : Γ(M, ⊤)) (U : X.affineOpens) {r : Γ(X, U)}
    (hr : r ∈ (zeroIdeal M s).ideal U) {W : X.Opens} (h : W ≤ U.1) {e : Γ(M, W)} (hf : IsFrame M W e) :
    hf.coord le_rfl (M.res le_top s) ∣ X.presheaf.map (homOfLE h).op r :=
  IdealSheafData.ideal_ofIdeals_le _ U hr W h e hf

end AlgebraicGeometry.Scheme.Modules

end
