import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Varieties.Curves.CurveDimensionOne
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffectiveCartierDivisorScheme
import MiyaokaMori.AlgebraicGeometry.Varieties.Curves.ClosedPointCoheightOne

/-! # A regular closed point of a curve is an effective Cartier divisor (Stacks 0B8Y)

Stacks 0B8Y, direction (1)⇒(5): for a closed point `x` of a curve over a field with `O_{X,x}` regular,
the reduced point `x` is an effective Cartier divisor on `X`. This is the first step of the fibre
decomposition in the proof of Lemma 5.1 of the paper.

Proof: verify directly the defining condition `IsInvertibleIdeal` of `EffCartier` (every point has an
affine neighbourhood `U` and a nonzerodivisor `a` with `I(U) = (a)`):
* `y ≠ x`: take an affine neighbourhood not containing `x`; then `I(U) = ⊤ = (1)`.
* `y = x`: take an affine `U = Spec R ∋ x`, `𝔭 = 𝔭_x`, `I(U) = 𝔭` (the vanishing ideal of a point is its
  prime), `O_{X,x} = R_𝔭`. `coheight x = 1` (integral, one-dimensional, closed point) gives
  `dim O_{X,x} = 1`, so regularity gives that `m_x` is generated by one element, which may be taken to be
  the germ of some `b ∈ 𝔭`; `m_x ≠ 0` gives `germ b ≠ 0`. `R` is Noetherian, so `𝔭` is finitely
  generated; spread `𝔭 R_𝔭 ⊆ (b)` out to a basic open `D(s)` with `s ∉ 𝔭` (`spread_map_le_span`); by
  quasi-coherence `I(D(s)) = 𝔭 R_s = (b)`; `Γ(D(s))` is a domain (`X` integral) and `b ≠ 0`, so `b` is a
  nonzerodivisor.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- Spreading-out lemma: let `R` be a commutative ring, `𝔭` a prime, `S = R_𝔭`, `J` a finitely generated
ideal and `a ∈ R`. If `J R_𝔭 ⊆ (a)`, then there is `s ∉ 𝔭` such that `J T ⊆ (a)` in every `R`-algebra `T`
in which `s` becomes a unit. (Clear denominators in the relation `g = a·b/u` for each generator `g` of
`J` and take the product of all denominators.) -/
private theorem spread_map_le_span {R : Type u} [CommRing R] (𝔭 : Ideal R) [𝔭.IsPrime]
    (S : Type v) [CommRing S] [Algebra R S] [IsLocalization.AtPrime S 𝔭]
    (J : Ideal R) (hJ : J.FG) (a : R)
    (h : J.map (algebraMap R S) ≤ Ideal.span {algebraMap R S a}) :
    ∃ s : R, s ∉ 𝔭 ∧ ∀ {T : Type w} [CommRing T] (f : R →+* T), IsUnit (f s) →
      J.map f ≤ Ideal.span {f a} := by
  classical
  obtain ⟨G, hG⟩ := hJ
  have key : ∀ g ∈ G, ∃ s : R, s ∉ 𝔭 ∧ ∃ b : R, s * g = a * b := by
    intro g hg
    have hgJ : g ∈ J := hG ▸ Ideal.subset_span hg
    have hmem : algebraMap R S g ∈ Ideal.span {algebraMap R S a} :=
      h (Ideal.mem_map_of_mem _ hgJ)
    obtain ⟨y, hy⟩ := Ideal.mem_span_singleton'.mp hmem
    obtain ⟨⟨b, u⟩, rfl⟩ := IsLocalization.mk'_surjective 𝔭.primeCompl y
    have h1 : algebraMap R S (g * u) = algebraMap R S (b * a) := by
      rw [map_mul, map_mul, ← hy, mul_comm (IsLocalization.mk' S b u) _, mul_assoc,
        IsLocalization.mk'_spec, mul_comm]
    obtain ⟨c, hc⟩ := (IsLocalization.eq_iff_exists 𝔭.primeCompl S).mp h1
    refine ⟨(c : R) * u, (𝔭.primeCompl.mul_mem c.2 u.2 : _), (c : R) * b, ?_⟩
    calc (c : R) * u * g = c * (g * u) := by ring
      _ = c * (b * a) := hc
      _ = a * (c * b) := by ring
  choose! sg hsg bg hbg using key
  refine ⟨∏ g ∈ G, sg g, fun hmem => ?_, ?_⟩
  · obtain ⟨g, hg, hg'⟩ := Ideal.IsPrime.prod_mem_iff.mp hmem
    exact hsg g hg hg'
  · intro T _ f hf
    rw [← hG, Ideal.map_span, Ideal.span_le]
    rintro _ ⟨g, hg, rfl⟩
    have hu : IsUnit (f (sg g)) := by
      refine isUnit_of_mul_isUnit_left (y := f (∏ x ∈ G.erase g, sg x)) ?_
      rw [← map_mul, Finset.mul_prod_erase G sg hg]
      exact hf
    obtain ⟨u, hu'⟩ := hu
    have hrel : f (sg g) * f g = f a * f (bg g) := by
      rw [← map_mul, ← map_mul, hbg g hg]
    rw [SetLike.mem_coe, Ideal.mem_span_singleton']
    refine ⟨↑u⁻¹ * f (bg g), ?_⟩
    calc ↑u⁻¹ * f (bg g) * f a = ↑u⁻¹ * (f a * f (bg g)) := by ring
      _ = ↑u⁻¹ * (f (sg g) * f g) := by rw [hrel]
      _ = f g := by rw [← hu', ← mul_assoc, Units.inv_mul, one_mul]

theorem AlgebraicGeometry.closedPoint_effectiveCartier_of_regular {k : Type u} [Field k]
    (X : AlgebraicGeometry.Scheme.{u}) [X.Over (AlgebraicGeometry.Spec (CommRingCat.of k))]
    [AlgebraicGeometry.IsIntegral X]
    [AlgebraicGeometry.LocallyOfFiniteType (X ↘ AlgebraicGeometry.Spec (CommRingCat.of k))]
    (hdim : SchemeIsOneDimensional X) (x : X) (hx : IsClosed ({x} : Set X))
    [IsRegularLocalRing (X.presheaf.stalk x)] :
    ∃ D : AlgebraicGeometry.EffectiveCartierDivisor X,
      D.idealSheaf = AlgebraicGeometry.Scheme.IdealSheafData.vanishingIdeal ⟨{x}, hx⟩ := by
  suffices hinv : MiyaokaMori.Statement.IsInvertibleIdeal
      (AlgebraicGeometry.Scheme.IdealSheafData.vanishingIdeal (X := X) ⟨{x}, hx⟩) from
    ⟨⟨_, hinv⟩, rfl⟩
  intro y
  by_cases hxy : x = y
  · subst hxy
    -- affine neighbourhood V ∋ x
    obtain ⟨V, hxV⟩ : ∃ V : X.affineOpens, x ∈ (V : X.Opens) := by
      obtain ⟨_, ⟨U, hU, rfl⟩, hxU, -⟩ :=
        X.isBasis_affineOpens.exists_subset_of_mem_open (Set.mem_univ x) isOpen_univ
      exact ⟨⟨U, hU⟩, hxU⟩
    set 𝔭 : Ideal Γ(X, V) := (V.2.primeIdealOf ⟨x, hxV⟩).asIdeal with h𝔭
    let _ : Algebra Γ(X, V) (X.presheaf.stalk x) := X.presheaf.algebra_section_stalk ⟨x, hxV⟩
    have hloc : IsLocalization.AtPrime (X.presheaf.stalk x) 𝔭 := V.2.isLocalization_stalk ⟨x, hxV⟩
    -- I(V) = 𝔭
    have hIV : (AlgebraicGeometry.Scheme.IdealSheafData.vanishingIdeal (X := X) ⟨{x}, hx⟩).ideal V
        = 𝔭 := by
      have hV : AlgebraicGeometry.IsAffineOpen (V : X.Opens) := V.2
      have hpre : hV.fromSpec ⁻¹' ({x} : Set X) = {hV.primeIdealOf ⟨x, hxV⟩} := by
        ext p
        simp only [Set.mem_preimage, Set.mem_singleton_iff]
        constructor
        · intro hp
          apply hV.fromSpec.isOpenEmbedding.injective
          rw [hp, AlgebraicGeometry.IsAffineOpen.fromSpec_primeIdealOf]
        · rintro rfl
          exact hV.fromSpec_primeIdealOf ⟨x, hxV⟩
      rw [AlgebraicGeometry.Scheme.IdealSheafData.vanishingIdeal_ideal]
      convert PrimeSpectrum.vanishingIdeal_singleton (hV.primeIdealOf ⟨x, hxV⟩) using 2
      exact hpre
    -- dim O_{X,x} = 1
    have hdim1 : ringKrullDim (X.presheaf.stalk x) = 1 := by
      rw [AlgebraicGeometry.ringKrullDim_stalk_eq_coheight x,
        AlgebraicGeometry.Scheme.closedPoint_coheight_eq_one_of_dimension_one X hdim x hx]
      norm_num
    -- Noetherian
    have : AlgebraicGeometry.IsLocallyNoetherian X :=
      AlgebraicGeometry.LocallyOfFiniteType.isLocallyNoetherian
        (X ↘ AlgebraicGeometry.Spec (CommRingCat.of k))
    have : IsNoetherianRing Γ(X, V) := AlgebraicGeometry.IsLocallyNoetherian.component_noetherian V
    -- m_x is generated by one element
    obtain ⟨G, hGcard, hGspan⟩ := Submodule.FG.exists_span_finset_card_eq_spanFinrank
      (IsNoetherian.noetherian (IsLocalRing.maximalIdeal (X.presheaf.stalk x)))
    have hGcard' : G.card = 1 := by
      have h := IsRegularLocalRing.spanFinrank_maximalIdeal (R := X.presheaf.stalk x)
      rw [hdim1, ← hGcard] at h
      exact_mod_cast h
    obtain ⟨τ, rfl⟩ := Finset.card_eq_one.mp hGcard'
    have hmax : IsLocalRing.maximalIdeal (X.presheaf.stalk x) = Ideal.span {τ} := by
      rw [← hGspan, Finset.coe_singleton]
    -- τ may be replaced by the germ of some b ∈ Γ(X, V)
    obtain ⟨⟨b, u⟩, hbu⟩ := IsLocalization.mk'_surjective 𝔭.primeCompl τ
    have hmaxb : IsLocalRing.maximalIdeal (X.presheaf.stalk x) =
        Ideal.span {algebraMap Γ(X, V) (X.presheaf.stalk x) b} := by
      rw [hmax, ← hbu, ← IsLocalization.mk'_spec (X.presheaf.stalk x) b u,
        Ideal.span_singleton_mul_right_unit (IsLocalization.map_units (X.presheaf.stalk x) u)]
    have hb𝔭 : b ∈ 𝔭 :=
      (IsLocalization.AtPrime.to_map_mem_maximal_iff (X.presheaf.stalk x) 𝔭 b).mp
        (hmaxb ▸ Ideal.mem_span_singleton_self _)
    have hbne : algebraMap Γ(X, V) (X.presheaf.stalk x) b ≠ 0 := by
      intro h0
      have hfield : IsField (X.presheaf.stalk x) := by
        rw [IsLocalRing.isField_iff_maximalIdeal_eq, hmaxb, h0, Ideal.span_singleton_zero]
      rw [ringKrullDim_eq_zero_of_isField hfield] at hdim1
      exact zero_ne_one hdim1
    -- spread out to D(s)
    have hle : 𝔭.map (algebraMap Γ(X, V) (X.presheaf.stalk x)) ≤
        Ideal.span {algebraMap Γ(X, V) (X.presheaf.stalk x) b} := by
      rw [IsLocalization.AtPrime.map_eq_maximalIdeal 𝔭 (X.presheaf.stalk x), hmaxb]
    obtain ⟨s, hs𝔭, hs⟩ := spread_map_le_span 𝔭 (X.presheaf.stalk x) 𝔭
      (IsNoetherian.noetherian 𝔭) b hle
    set W : X.affineOpens := X.affineBasicOpen (U := V) s
    have hxW : x ∈ (W : X.Opens) :=
      (X.mem_basicOpen s x hxV).mpr
        ((IsLocalization.AtPrime.isUnit_to_map_iff (X.presheaf.stalk x) 𝔭 s).mpr hs𝔭)
    let res : Γ(X, V) ⟶ Γ(X, W) := X.presheaf.map (homOfLE (X.basicOpen_le s)).op
    have hIW : (AlgebraicGeometry.Scheme.IdealSheafData.vanishingIdeal (X := X) ⟨{x}, hx⟩).ideal W
        = Ideal.span {res.hom b} := by
      show (AlgebraicGeometry.Scheme.IdealSheafData.vanishingIdeal (X := X) ⟨{x}, hx⟩).ideal
        (X.affineBasicOpen (U := V) s) = Ideal.span {res.hom b}
      rw [← (AlgebraicGeometry.Scheme.IdealSheafData.vanishingIdeal (X := X)
        ⟨{x}, hx⟩).map_ideal_basicOpen V s, hIV]
      exact le_antisymm (hs res.hom (AlgebraicGeometry.RingedSpace.isUnit_res_basicOpen _ s))
        (Ideal.span_le.mpr (Set.singleton_subset_iff.mpr (Ideal.mem_map_of_mem _ hb𝔭)))
    -- b is a nonzerodivisor in Γ(X, W) (a domain)
    have : Nonempty ((W : X.Opens) : Type u) := ⟨⟨x, hxW⟩⟩
    have hbW : res.hom b ≠ 0 := by
      intro h0
      apply hbne
      have := X.presheaf.germ_res_apply (homOfLE (X.basicOpen_le s)) x hxW b
      change X.presheaf.germ (W : X.Opens) x hxW (res.hom b) = _ at this
      rw [h0, map_zero] at this
      exact this.symm
    refine ⟨W, hxW, res.hom b, fun r hr => ?_, hIW⟩
    exact (mul_eq_zero.mp hr).resolve_left hbW
  · -- y ≠ x: take an affine neighbourhood not containing x; I(V) = ⊤
    obtain ⟨V, hyV, hVx⟩ : ∃ V : X.affineOpens, y ∈ (V : X.Opens) ∧ ((V : X.Opens) : Set X) ⊆ {x}ᶜ := by
      obtain ⟨_, ⟨U, hU, rfl⟩, hyU, hUx⟩ :=
        X.isBasis_affineOpens.exists_subset_of_mem_open
          (show y ∈ ({x}ᶜ : Set X) from fun h => hxy (Set.mem_singleton_iff.mp h).symm)
          hx.isOpen_compl
      exact ⟨⟨U, hU⟩, hyU, hUx⟩
    refine ⟨V, hyV, 1, fun r hr => by simpa using hr, ?_⟩
    rw [Ideal.span_singleton_one, AlgebraicGeometry.Scheme.IdealSheafData.vanishingIdeal_ideal,
      PrimeSpectrum.vanishingIdeal_eq_top_iff]
    ext p
    simp only [Set.mem_empty_iff_false, iff_false]
    intro hp
    have hxV : x ∈ ((V : X.Opens) : Set X) := V.2.range_fromSpec ▸ ⟨p, hp⟩
    exact hVx hxV rfl

end
