import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffectiveCartierDivisorScheme
-- the next two imports are not used by this proof; they are kept for downstream modules that reach
-- these declarations transitively
import MiyaokaMori.AlgebraicGeometry.Modules.Stalk.ModulesSupport
import MiyaokaMori.AlgebraicGeometry.Modules.Glue.ModulesGlueIso

/-! # Locally principal ideal sheaves generated by nonzerodivisors on stalks (Stacks 0AG8)

Stacks 0AG8(2): if an ideal sheaf `I` on a locally Noetherian scheme `X` has, at every point of its
support, a stalk ideal generated by one nonzerodivisor, then `V(I)` is an effective Cartier divisor.
Sources: Stacks 0AG8; the proof of Stacks 0B8Y.

Proof: verify directly the defining condition `MiyaokaMori.Statement.IsInvertibleIdeal` of `EffCartier`
(every point has an affine neighbourhood `U` and a nonzerodivisor `a` with `I(U) = (a)`):
* `y ∉ I.support`: take an affine `U ∋ y`; by definition of the support `I(U) ⊄ 𝔭_y`, so there is
  `s ∈ I(U)` with `y ∈ D(s)`, and `I(D(s))` contains the unit `res s`, so `I(D(s)) = ⊤ = (1)`.
* `y ∈ I.support`: the hypothesis gives an affine `U = Spec A ∋ y` and `t ∈ A` with `I(U)·A_𝔭 = (t)` and
  `t` a nonzerodivisor of `A_𝔭 = O_{X,y}`.
  - Spreading out the principal generator (0AG8(1)): `A` Noetherian gives `I(U)` finitely generated;
    `I(U) A_𝔭 ⊆ (t)` spreads out to `D(s₁)` (`stacks0ag8_exists_map_le_span_of_fg`: clear denominators
    of each generator and take the product of the denominators); `t ∈ I(U) A_𝔭` means `t·u = a` in `A_𝔭`
    with `a ∈ I(U)`, `u ∉ 𝔭`, so there is `c ∉ 𝔭` with `c·t·u = c·a` in `A`, and on `D(c·u)` we get
    `res t ∈ I(U)·Γ(D(c u))`.
  - Spreading out the nonzerodivisor property (0AG8(2)): `Ann_A(t) = ker(t·)` is finitely generated,
    and each generator `a_i` satisfies `germ t · germ a_i = 0`, hence `germ a_i = 0`, hence `c_i a_i = 0`
    for some `c_i ∉ 𝔭`; `s₂ := ∏ c_i` kills all of `Ann_A(t)`. Then in `A_s` (`s := s₁ c u s₂`): if
    `res t · (b/sⁿ) = 0` then `s^k t b = 0` for some `k`, so `s^k b ∈ Ann(t)`, `s·s^k b = 0`, and `b/sⁿ = 0`.
  - Combine: `W := D(s)`, `y ∈ W` (`s ∉ 𝔭_y`), `I(W) = I(U)·Γ(W) = (res t)` (both inclusions from the
    above), and `res t` is a nonzerodivisor of `Γ(W)`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- Spreading-out lemma (the algebraic core of Stacks 0AG8(1)): let `R` be a commutative ring, `M` a
submonoid, `S = M⁻¹R`, `J` a finitely generated ideal and `a ∈ R`. If `J S ⊆ (a)`, then there is `s ∈ M`
such that `J T ⊆ (f a)` for every ring homomorphism `f : R → T` making `s` a unit.

Proof: `J = (g_1, …, g_r)`. In `S` each `g_i = a · (b_i / u_i)`; clearing denominators,
`c_i u_i g_i = a c_i b_i` in `R` with `c_i, u_i ∈ M`. Put `s := ∏ c_i u_i`; in `T`, `f(c_i u_i)` is a
unit, so `f g_i = f(c_i u_i)⁻¹ f(c_i b_i) · f a ∈ (f a)`. -/
theorem AlgebraicGeometry.stacks0ag8_exists_map_le_span_of_fg {R : Type u} [CommRing R]
    (M : Submonoid R) (S : Type v) [CommRing S] [Algebra R S] [IsLocalization M S]
    (J : Ideal R) (hJ : J.FG) (a : R)
    (h : J.map (algebraMap R S) ≤ Ideal.span {algebraMap R S a}) :
    ∃ s ∈ M, ∀ {T : Type w} [CommRing T] (f : R →+* T), IsUnit (f s) →
      J.map f ≤ Ideal.span {f a} := by
  classical
  obtain ⟨G, hG⟩ := hJ
  have key : ∀ g ∈ G, ∃ s ∈ M, ∃ b : R, s * g = a * b := by
    intro g hg
    have hgJ : g ∈ J := hG ▸ Ideal.subset_span hg
    have hmem : algebraMap R S g ∈ Ideal.span {algebraMap R S a} :=
      h (Ideal.mem_map_of_mem _ hgJ)
    obtain ⟨y, hy⟩ := Ideal.mem_span_singleton'.mp hmem
    obtain ⟨⟨b, u⟩, rfl⟩ := IsLocalization.mk'_surjective M y
    have h1 : algebraMap R S (g * u) = algebraMap R S (b * a) := by
      rw [map_mul, map_mul, ← hy, mul_comm (IsLocalization.mk' S b u) _, mul_assoc,
        IsLocalization.mk'_spec, mul_comm]
    obtain ⟨c, hc⟩ := (IsLocalization.eq_iff_exists M S).mp h1
    refine ⟨(c : R) * u, M.mul_mem c.2 u.2, (c : R) * b, ?_⟩
    calc (c : R) * u * g = c * (g * u) := by ring
      _ = c * (b * a) := hc
      _ = a * (c * b) := by ring
  choose! sg hsg bg hbg using key
  refine ⟨∏ g ∈ G, sg g, M.prod_mem (fun g hg => hsg g hg), ?_⟩
  intro T _ f hf
  rw [← hG, Ideal.map_span, Ideal.span_le]
  rintro _ ⟨g, hg, rfl⟩
  have hu : IsUnit (f (sg g)) := by
    refine isUnit_of_mul_isUnit_left (y := f (∏ x ∈ G.erase g, sg x)) ?_
    rw [← map_mul, Finset.mul_prod_erase G sg hg]
    exact hf
  obtain ⟨u, hu'⟩ := hu
  have hrel : f (sg g) * f g = f a * f (bg g) := by
    rw [← map_mul, ← map_mul, hbg g hg]
  rw [SetLike.mem_coe, Ideal.mem_span_singleton']
  refine ⟨↑u⁻¹ * f (bg g), ?_⟩
  calc ↑u⁻¹ * f (bg g) * f a = ↑u⁻¹ * (f a * f (bg g)) := by ring
    _ = ↑u⁻¹ * (f (sg g) * f g) := by rw [hrel]
    _ = f g := by rw [← hu', ← mul_assoc, Units.inv_mul, one_mul]

theorem AlgebraicGeometry.effectiveCartier_of_locally_principal_nzd {X : AlgebraicGeometry.Scheme.{u}}
    [AlgebraicGeometry.IsLocallyNoetherian X] (I : X.IdealSheafData)
    (h : ∀ x ∈ I.support, ∃ (U : X.affineOpens) (hx : x ∈ (U : X.Opens)) (t : Γ(X, (U : X.Opens))),
      (I.ideal U).map (X.presheaf.germ (U : X.Opens) x hx).hom
        = Ideal.span {(X.presheaf.germ (U : X.Opens) x hx).hom t} ∧
      (X.presheaf.germ (U : X.Opens) x hx).hom t ∈ nonZeroDivisors (X.presheaf.stalk x)) :
    ∃ D : AlgebraicGeometry.EffectiveCartierDivisor X, D.idealSheaf = I := by
  suffices hinv : MiyaokaMori.Statement.IsInvertibleIdeal I from ⟨⟨I, hinv⟩, rfl⟩
  intro y
  by_cases hy : y ∈ I.support
  · obtain ⟨U, hyU, t, hspan, hnzd⟩ := h y hy
    classical
    have : IsNoetherianRing Γ(X, (U : X.Opens)) :=
      AlgebraicGeometry.IsLocallyNoetherian.component_noetherian U
    set 𝔭 : Ideal Γ(X, (U : X.Opens)) := (U.2.primeIdealOf ⟨y, hyU⟩).asIdeal with h𝔭
    let _ : Algebra Γ(X, (U : X.Opens)) (X.presheaf.stalk y) :=
      X.presheaf.algebra_section_stalk ⟨y, hyU⟩
    have hloc : IsLocalization.AtPrime (X.presheaf.stalk y) 𝔭 := U.2.isLocalization_stalk ⟨y, hyU⟩
    have hgerm : algebraMap Γ(X, (U : X.Opens)) (X.presheaf.stalk y)
        = (X.presheaf.germ (U : X.Opens) y hyU).hom := rfl
    -- spread out the principal generator (⊆)
    obtain ⟨s₁, hs₁, hspread⟩ := AlgebraicGeometry.stacks0ag8_exists_map_le_span_of_fg
      𝔭.primeCompl (X.presheaf.stalk y) (I.ideal U) (IsNoetherian.noetherian _) t
      (by rw [hgerm, hspan])
    -- spread out the principal generator (⊇): t·u = a on the stalk; clear denominators
    have ht : algebraMap Γ(X, (U : X.Opens)) (X.presheaf.stalk y) t
        ∈ (I.ideal U).map (algebraMap Γ(X, (U : X.Opens)) (X.presheaf.stalk y)) := by
      rw [hgerm, hspan]; exact Ideal.mem_span_singleton_self _
    obtain ⟨⟨⟨a, ha⟩, u⟩, hau⟩ := (IsLocalization.mem_map_algebraMap_iff 𝔭.primeCompl _).mp ht
    rw [← map_mul] at hau
    obtain ⟨c, hc⟩ := (IsLocalization.eq_iff_exists 𝔭.primeCompl (X.presheaf.stalk y)).mp hau
    -- spread out the nonzerodivisor property
    set K : Ideal Γ(X, (U : X.Opens)) := LinearMap.ker (LinearMap.mulLeft Γ(X, (U : X.Opens)) t) with hK
    obtain ⟨G, hG⟩ := IsNoetherian.noetherian K
    have hann : ∀ g ∈ G, ∃ m ∈ 𝔭.primeCompl, m * g = 0 := by
      intro g hg
      have hgK : t * g = 0 := by
        have : g ∈ K := hG ▸ Ideal.subset_span hg
        simpa [hK, LinearMap.mem_ker] using this
      have h0 : algebraMap Γ(X, (U : X.Opens)) (X.presheaf.stalk y) g = 0 := by
        apply (mem_nonZeroDivisors_iff.mp hnzd).1
        rw [← hgerm, ← map_mul, hgK, map_zero]
      obtain ⟨m, hm⟩ := (IsLocalization.map_eq_zero_iff 𝔭.primeCompl (X.presheaf.stalk y) g).mp h0
      exact ⟨m, m.2, hm⟩
    choose! cg hcg hcg0 using hann
    set s₂ : Γ(X, (U : X.Opens)) := ∏ g ∈ G, cg g with hs₂
    have hs₂K : ∀ k ∈ K, s₂ * k = 0 := by
      intro k hk
      have : K ≤ LinearMap.ker (LinearMap.mulLeft Γ(X, (U : X.Opens)) s₂) := by
        rw [← hG, Ideal.span_le]
        intro g hg
        rw [SetLike.mem_coe, LinearMap.mem_ker, LinearMap.mulLeft_apply, hs₂,
          ← Finset.mul_prod_erase G cg hg, mul_assoc, mul_comm (∏ x ∈ G.erase g, cg x), ← mul_assoc,
          hcg0 g hg, zero_mul]
      simpa [LinearMap.mem_ker] using this hk
    -- combine
    set s : Γ(X, (U : X.Opens)) := s₁ * ((c : Γ(X, (U : X.Opens))) * u) * s₂ with hs
    have hs𝔭 : s ∈ 𝔭.primeCompl :=
      𝔭.primeCompl.mul_mem (𝔭.primeCompl.mul_mem hs₁ (𝔭.primeCompl.mul_mem c.2 u.2))
        (𝔭.primeCompl.prod_mem (fun g hg => hcg g hg))
    have hyW : y ∈ X.basicOpen s :=
      (X.mem_basicOpen s y hyU).mpr
        ((IsLocalization.AtPrime.isUnit_to_map_iff (X.presheaf.stalk y) 𝔭 s).mpr hs𝔭)
    let res : Γ(X, (U : X.Opens)) ⟶ Γ(X, X.basicOpen s) :=
      X.presheaf.map (homOfLE (X.basicOpen_le s)).op
    have hres_s : IsUnit (res.hom s) := AlgebraicGeometry.RingedSpace.isUnit_res_basicOpen _ s
    have hres_s₁ : IsUnit (res.hom s₁) := by
      refine isUnit_of_mul_isUnit_left (y := res.hom ((c : Γ(X, (U : X.Opens))) * u * s₂)) ?_
      have e : s₁ * ((c : Γ(X, (U : X.Opens))) * u * s₂) = s := by rw [hs]; ring
      rw [← map_mul, e]; exact hres_s
    have hres_cu : IsUnit (res.hom ((c : Γ(X, (U : X.Opens))) * u)) := by
      refine isUnit_of_mul_isUnit_left (y := res.hom (s₁ * s₂)) ?_
      have e : (c : Γ(X, (U : X.Opens))) * u * (s₁ * s₂) = s := by rw [hs]; ring
      rw [← map_mul, e]; exact hres_s
    have hIW : I.ideal (X.affineBasicOpen (U := U) s) = Ideal.span {res.hom t} := by
      rw [← I.map_ideal_basicOpen U s]
      refine le_antisymm (hspread res.hom hres_s₁) (Ideal.span_le.mpr ?_)
      rintro _ rfl
      rw [SetLike.mem_coe, ← Ideal.mul_unit_mem_iff_mem _ hres_cu, ← map_mul]
      have hrel : t * ((c : Γ(X, (U : X.Opens))) * u) = c * a := by
        rw [← hc]; ring
      rw [hrel, map_mul]
      exact Ideal.mul_mem_left _ _ (Ideal.mem_map_of_mem _ ha)
    -- res t is a nonzerodivisor
    have hnzdW : ∀ r : Γ(X, X.basicOpen s), res.hom t * r = 0 → r = 0 := by
      have := U.2.isLocalization_basicOpen s
      intro r hr
      change algebraMap Γ(X, (U : X.Opens)) Γ(X, X.basicOpen s) t * r = 0 at hr
      obtain ⟨⟨b, m⟩, rfl⟩ := IsLocalization.mk'_surjective (Submonoid.powers s) r
      rw [IsLocalization.mul_mk'_eq_mk'_of_mul, IsLocalization.mk'_eq_zero_iff] at hr
      obtain ⟨⟨_, k, rfl⟩, hk⟩ := hr
      rw [IsLocalization.mk'_eq_zero_iff]
      refine ⟨⟨s ^ (k + 1), pow_mem (Submonoid.mem_powers s) _⟩, ?_⟩
      have hkK : s ^ k * b ∈ K := by
        rw [hK, LinearMap.mem_ker, LinearMap.mulLeft_apply]
        rw [← hk]; ring
      have := hs₂K _ hkK
      change s ^ (k + 1) * b = 0
      calc s ^ (k + 1) * b = (s₁ * ((c : Γ(X, (U : X.Opens))) * u)) * (s₂ * (s ^ k * b)) := by
            rw [hs]; ring
        _ = 0 := by rw [this, mul_zero]
    exact ⟨X.affineBasicOpen (U := U) s, hyW, res.hom t, hnzdW, hIW⟩
  · -- y ∉ I.support: I is ⊤ near y
    obtain ⟨U, hyU⟩ : ∃ U : X.affineOpens, y ∈ (U : X.Opens) := by
      obtain ⟨_, ⟨U, hU, rfl⟩, hyU, -⟩ :=
        X.isBasis_affineOpens.exists_subset_of_mem_open (Set.mem_univ y) isOpen_univ
      exact ⟨⟨U, hU⟩, hyU⟩
    rw [AlgebraicGeometry.Scheme.IdealSheafData.mem_support_iff_of_mem hyU,
      AlgebraicGeometry.Scheme.mem_zeroLocus_iff] at hy
    push Not at hy
    obtain ⟨s, hsI, hys⟩ := hy
    refine ⟨X.affineBasicOpen (U := U) s, hys, 1, fun r hr => by simpa using hr, ?_⟩
    rw [Ideal.span_singleton_one, ← I.map_ideal_basicOpen U s]
    exact Ideal.eq_top_of_isUnit_mem _ (Ideal.mem_map_of_mem _ hsI)
      (AlgebraicGeometry.RingedSpace.isUnit_res_basicOpen _ s)

end
