import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffectiveCartierDivisorScheme

/-! # Sums of effective Cartier divisors (Stacks 01WU)

The sum of two effective Cartier divisors (the product of ideal sheaves `I_{D₁}·I_{D₂}`) is again an
effective Cartier divisor (Stacks 01WU, `divisors-lemma-sum-effective-Cartier-divisors`).

Proof: the product of ideal sheaves is Mathlib's multiplication on `IdealSheafData`
(`IdealSheafData.ideal_mul` is `rfl`). It suffices to show that `I₁·I₂` is locally generated by a
nonzerodivisor: for `x ∈ X` take local equations `(U₁, a₁)`, `(U₂, a₂)` of `D₁`, `D₂`
(`EffCartier.exists_localEquation`) and a basic open `W = D(f) ⊆ U₁ ∩ U₂` of `U₁` containing `x`
(`IsAffineOpen.exists_basicOpen_le`); by quasi-coherence `I_k(W) = I_k(U_k)·O(W)`
(`IdealSheafData.map_ideal`), so `I_k(W) = (a_k|_W)` with `a_k|_W` still a nonzerodivisor
(`IsAffineOpen.res_mem_nonZeroDivisors`), hence `(I₁·I₂)(W) = (a₁|_W · a₂|_W)`, and a product of
nonzerodivisors is a nonzerodivisor (`mul_mem`).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- Stacks 01WU: the ideal sheaf of `D₁ + D₂` is `I_{D₁}·I_{D₂}` (the product of ideals on each affine
open), and it is again an effective Cartier divisor. -/

theorem AlgebraicGeometry.EffectiveCartierDivisor.exists_add {X : AlgebraicGeometry.Scheme.{u}}
    (D₁ D₂ : AlgebraicGeometry.EffectiveCartierDivisor X) :
    ∃ D : AlgebraicGeometry.EffectiveCartierDivisor X, ∀ U : X.affineOpens,
      D.idealSheaf.ideal U = D₁.idealSheaf.ideal U * D₂.idealSheaf.ideal U := by
  refine ⟨⟨D₁.idealSheaf * D₂.idealSheaf, ?_⟩, fun U => rfl⟩
  intro x
  obtain ⟨U₁, hx₁, a₁, ha₁, hI₁⟩ := AlgebraicGeometry.Scheme.EffCartier.exists_localEquation D₁ x
  obtain ⟨U₂, hx₂, a₂, ha₂, hI₂⟩ := AlgebraicGeometry.Scheme.EffCartier.exists_localEquation D₂ x
  obtain ⟨f, hfle, hxf⟩ := U₁.2.exists_basicOpen_le (V := U₁.1 ⊓ U₂.1) ⟨x, hx₁, hx₂⟩ hx₁
  have hW₁ : X.affineBasicOpen f ≤ U₁ := X.basicOpen_le f
  have hW₂ : X.affineBasicOpen f ≤ U₂ := hfle.trans inf_le_right
  have hn₁ := U₁.2.res_mem_nonZeroDivisors ha₁ hW₁
  have hn₂ := U₂.2.res_mem_nonZeroDivisors ha₂ hW₂
  refine ⟨X.affineBasicOpen f, hxf,
    X.presheaf.map (homOfLE hW₁).op a₁ * X.presheaf.map (homOfLE hW₂).op a₂, ?_, ?_⟩
  · intro r hr
    exact (mem_nonZeroDivisors_iff_right.mp (mul_mem hn₁ hn₂)) r (by rwa [mul_comm])
  · change (D₁.idealSheaf.ideal _ * D₂.idealSheaf.ideal _) = _
    rw [← D₁.idealSheaf.map_ideal hW₁, ← D₂.idealSheaf.map_ideal hW₂, hI₁, hI₂, Ideal.map_span,
      Ideal.map_span, Set.image_singleton, Set.image_singleton,
      Ideal.span_singleton_mul_span_singleton]
    rfl

end
