import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Proj.WeightedProj.WeightedPowerChartFinite
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.WeightedPowerMapPullbackTwistLocal

/-! # Pullback of the twisting sheaf along the power map

For the power map `g : P(1,…,1) → P(w)` (`InducedByPowerMap g`) and the twisting sheaves: when every
`w_i` divides `m`, `g^* O_{P(w)}(m) ≅ O_{P^N}(m)` (the identification `φ_k^* O(m) ≃ O(m)` in the proof
of the Veronese polarization lemma of the paper).

References: Stacks 01MS (`O(nd)|_{D_+(f)}` is generated by `f^n`), 01MY (`g` is
`Spec (Away.map ψ x_j)` on `D_+(u_j)`).

## Route

The whole argument is carried out for arbitrary graded rings `𝒜`, `ℬ`, a graded homomorphism `ψ`
and the morphism `g` given chartwise by `ψ`; this file only instantiates it:

* gluing of isomorphisms of sheaves of modules along an open cover (step (c)),
  `Scheme.Modules.exists_iso_of_local_isos`;
* the chart map `Proj.awayChartMap ψ f : D_+(ψ f) → D_+(f)`, its action on sections
  `awayChartMap_appTop` (the sections version of 01MY, step (b)), and the fact that `r_ψ` on a chart
  is this map (`Proj.mapOfGradedHom_basicOpen`);
* the local frames `f^n`, the pulled-back frames (`pullbackFrameIso`, step (a)), the local
  comparison isomorphisms with their coordinate formulas, agreement on overlaps and compatibility
  with restriction, and the gluing `Proj.TwistPullback.pullback_twist_iso_of_charts`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- If every `w_i` divides `m`, then `g^* O_{P(w)}(m) ≅ O_{P^N}(m)`.

References: Stacks 01MS (for `f ∈ S_d`, `O(nd)|_{D_+(f)}` is generated by `f^n`), 01MY.

Proof: `InducedByPowerMap g` gives `g = r_ψ` (`ψ = weightedPowerGradedHom k w`, `x_j ↦ u_j^{w_j}`,
`U(ψ) = ⊤`). Take the charts `f_j = x_j ∈ 𝒜_{w_j}` and `n_j = m / w_j`. The opens
`D_+(ψ x_j) = D_+(u_j^{w_j}) = D_+(u_j)` cover `P^N` (`Proj.iSup_basicOpen_eq_top'`), and by 01MY
(`Proj.ι_comp_mapOfGradedHom_eq_awayChartMap`) `g` is the chart map `awayChartMap ψ x_j` on
`D_+(ψ x_j)`. Then `Proj.TwistPullback.pullback_twist_iso_of_charts` gives the claim: on `D_+(x_j)`
the sheaf `O(m)` is generated by `x_j^{n_j}`, on `V ≤ D_+(u_j)` it is generated by
`(ψ x_j)^{n_j} = u_j^m`, and the pulled-back frame and the source frame give a local comparison
isomorphism sending the pullback of a global section `a ∈ 𝒜_m` to `ψ(a)` (both sides are the
restriction of the chart function `a/x_j^{n_j} ↦ ψ(a)/(ψ x_j)^{n_j}`; on the pullback side by the
sections formula `awayChartMap_appTop` of 01MY, on the source side by dividing by the frame). Hence
the local isomorphisms agree on overlaps and are compatible with restriction, and they glue along
the cover (Stacks 04TN).

Edge case: `m = 0` also holds (`n_j = 0`, the frame is `1`). -/
theorem weightedPowerMap_pullback_twist (k : Type u) [Field k] {σ : Type u} [Fintype σ]
    (w : σ → ℕ) (hw : ∀ i, 0 < w i)
    (g : weightedProjectiveSpace k (fun _ : σ => 1) (fun _ => Nat.one_pos) ⟶
      weightedProjectiveSpace k w hw) (hg : InducedByPowerMap g)
    (m : ℕ) (hm : ∀ i, w i ∣ m) :
    Nonempty ((AlgebraicGeometry.Scheme.Modules.pullback g).obj (weightedProjTwist k w hw (m : ℤ)) ≅
      weightedProjTwist k (fun _ : σ => 1) (fun _ => Nat.one_pos) (m : ℤ)) := by
  let _ := MvPolynomial.weightedGradedAlgebra (R := k) w
  let _ := MvPolynomial.weightedGradedAlgebra (R := k) (fun _ : σ => 1)
  obtain ⟨h, rfl⟩ := hg
  set ψ := weightedPowerGradedHom k w with hψ
  have h' : AlgebraicGeometry.Proj.mapDomain ψ = ⊤ := h
  -- the coordinates are homogeneous of degree `w j`
  have hX : ∀ j : σ, (MvPolynomial.X j : MvPolynomial σ k) ∈
      MvPolynomial.weightedHomogeneousSubmodule k w (w j) := fun j =>
    (MvPolynomial.mem_weightedHomogeneousSubmodule k w (w j) _).mpr
      (MvPolynomial.isWeightedHomogeneous_X k w j)
  -- `D_+(ψ x_j) = D_+(u_j^{w_j}) = D_+(u_j)` cover `P^N`
  have hcov : ∀ x : AlgebraicGeometry.Proj (MvPolynomial.weightedHomogeneousSubmodule k (fun _ : σ => 1)),
      ∃ j, x ∈ AlgebraicGeometry.Proj.basicOpen
        (MvPolynomial.weightedHomogeneousSubmodule k (fun _ : σ => 1)) (ψ (MvPolynomial.X j)) := by
    intro x
    have hb : ∀ j, AlgebraicGeometry.Proj.basicOpen
        (MvPolynomial.weightedHomogeneousSubmodule k (fun _ : σ => 1)) (ψ (MvPolynomial.X j)) =
        AlgebraicGeometry.Proj.basicOpen
          (MvPolynomial.weightedHomogeneousSubmodule k (fun _ : σ => 1)) (MvPolynomial.X j) := by
      intro j
      rw [hψ, weightedPowerGradedHom_X]
      exact AlgebraicGeometry.Proj.basicOpen_pow _ _ _ (hw j)
    have htop : ⨆ j, AlgebraicGeometry.Proj.basicOpen
        (MvPolynomial.weightedHomogeneousSubmodule k (fun _ : σ => 1)) (ψ (MvPolynomial.X j)) = ⊤ := by
      simp only [hb]
      apply AlgebraicGeometry.Proj.iSup_basicOpen_eq_top'
      · intro i
        exact ⟨1, (MvPolynomial.mem_weightedHomogeneousSubmodule k _ _ _).mpr
          (MvPolynomial.isWeightedHomogeneous_X k (fun _ : σ => 1) i)⟩
      · apply top_unique
        intro p hp
        clear hp
        induction p using MvPolynomial.induction_on with
        | C r =>
          exact (Algebra.adjoin (MvPolynomial.weightedHomogeneousSubmodule k (fun _ : σ => 1) 0)
            (Set.range (MvPolynomial.X : σ → MvPolynomial σ k))).algebraMap_mem
              ⟨MvPolynomial.C r, (MvPolynomial.mem_weightedHomogeneousSubmodule k _ _ _).mpr
                (MvPolynomial.isWeightedHomogeneous_C (fun _ : σ => 1) r)⟩
        | add p q hp hq => exact Subalgebra.add_mem _ hp hq
        | mul_X p i hp =>
          exact Subalgebra.mul_mem _ hp (Algebra.subset_adjoin (Set.mem_range_self i))
    exact TopologicalSpace.Opens.mem_iSup.mp (htop.ge (Set.mem_univ x))
  exact AlgebraicGeometry.Proj.TwistPullback.pullback_twist_iso_of_charts
    (MvPolynomial.weightedHomogeneousSubmodule k w)
    (MvPolynomial.weightedHomogeneousSubmodule k (fun _ : σ => 1)) ψ _ MvPolynomial.X w hX hw hcov
    (fun j => AlgebraicGeometry.Proj.ι_comp_mapOfGradedHom_eq_awayChartMap ψ (MvPolynomial.X j)
      (hX j) (hw j) h')
    m (fun j => m / w j) (fun j => Nat.div_mul_cancel (hm j))

end
