import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.GeneratedInDegreeOne
import MiyaokaMori.Paper.S2WeightedJets.Ygg.JetWeightLcm
import MiyaokaMori.Paper.S2WeightedJets.Ygg.MonomialSplitIntoWeightM
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.VeroneseSubalgebra
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.QcSectionsBasicOpenLocalization
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.OfGradedQCAlgebra
import MiyaokaMori.AlgebraicGeometry.Proj.WeightedProj.WeightedPolynomialAtlas

/-! # Veronese generation for a locally weighted polynomial algebra

Let the graded quasi-coherent algebra `S` have a weighted polynomial atlas of weights `w : σ → ℕ`,
all between `1` and `k`. Then for `m = |σ| · jetWeight k` the Veronese algebra `S⁽ᵐ⁾` is generated by
its degree-one part. This is the claim in the proof of the Veronese polarization lemma of the paper.

Proof:
1. By the definition of `GeneratedInDegreeOne`, show for every `l > 0` that `(S_m)^⊗l → S_{lm}` is
   an epimorphism, using the local surjectivity criterion for morphisms of sheaves of modules on the
   affine cover of the atlas: `epi_iff_locally_surjective_sections`, together with the
   quasi-coherent localization `exists_pow_smul_eq_map_basicOpen` on a basic open `D(f) ⊆ U` inside
   a chart `C ∋ p` (a section over `D(f)` is `f^{-n} · t|_{D(f)}` with `t ∈ Γ(C)`); see the general
   lemma `Modules.epi_of_surjective_sections_affine_cover`.
2. The ring isomorphism of each chart identifies the sections of `S_j` with the homogeneous
   polynomials of weight `j`. After renumbering the variables along `Fintype.equivFin σ`, every
   monomial of weight `l m` splits by `exists_split_of_weight_eq_mul` into a product of `l`
   monomials of weight `m` (`exists_split_of_weight_eq_mul_fintype`).
3. Use `IsWeightedHomogeneous.induction_on` on weighted homogeneous polynomials: monomials have
   preimages by step 2, and sums and scalar multiples stay in the image. The chart isomorphism
   preserves multiplication and grading (`ofPiece`, `sectionsUnitHom_mul_ofPiece`,
   `ofPiece_injective`), and the recursive definition of `mulPowOne` together with `tensorSections`
   lifts these polynomial preimages to local preimages in the tensor powers.
4. The charts cover `X`, so the local criterion gives a global epimorphism for all `l > 0`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-! ## Step 2: splitting monomials (general finite index set) -/

/-- The version of `exists_split_of_weight_eq_mul` for a general finite index set: transport the
exponent `e : σ →₀ ℕ` to `Fin (card σ)` along `Fintype.equivFin σ`, split there, and transport back. -/
theorem exists_split_of_weight_eq_mul_fintype {σ : Type*} [Fintype σ] {k : ℕ} (w : σ → ℕ)
    (hw : ∀ i, w i ∈ Finset.Icc 1 k) (e : σ →₀ ℕ) (l : ℕ) (hl : 1 ≤ l)
    (h : Finsupp.weight w e = l * (Fintype.card σ * jetWeight k)) :
    ∃ f : Fin l → (σ →₀ ℕ),
      (∀ j, Finsupp.weight w (f j) = Fintype.card σ * jetWeight k) ∧ ∑ j, f j = e := by
  classical
  let φ : σ ≃ Fin (Fintype.card σ) := Fintype.equivFin σ
  let w' : Fin (Fintype.card σ) → ℕ := w ∘ φ.symm
  have hw' : ∀ i, w' i ∈ Finset.Icc 1 k := fun i => hw _
  have hweight : ∀ x : σ →₀ ℕ,
      Finsupp.weight w' (Finsupp.mapDomain φ x) = Finsupp.weight w x := by
    intro x
    rw [Finsupp.weight_apply, Finsupp.weight_apply, Finsupp.sum_mapDomain_index_inj φ.injective]
    refine Finsupp.sum_congr fun i _ => ?_
    simp [w']
  have hback : ∀ x : Fin (Fintype.card σ) →₀ ℕ,
      Finsupp.mapDomain φ (Finsupp.mapDomain φ.symm x) = x := by
    intro x
    rw [← Finsupp.mapDomain_comp, Equiv.self_comp_symm, Finsupp.mapDomain_id]
  have hback' : ∀ x : σ →₀ ℕ,
      Finsupp.mapDomain φ.symm (Finsupp.mapDomain φ x) = x := by
    intro x
    rw [← Finsupp.mapDomain_comp, Equiv.symm_comp_self, Finsupp.mapDomain_id]
  obtain ⟨f', hf', hsum'⟩ := exists_split_of_weight_eq_mul w' hw' (Finsupp.mapDomain φ e) l hl
    (by rw [hweight]; exact h)
  refine ⟨fun j => Finsupp.mapDomain φ.symm (f' j), ?_, ?_⟩
  · intro j
    rw [← hweight, hback]
    exact hf' j
  · show ∑ j, Finsupp.mapDomain φ.symm (f' j) = e
    rw [← Finsupp.mapDomain_finsetSum, hsum', hback']

/-! ## Step 3 (algebraic part): on a chart, homogeneous elements of weight `ℓ m` lie in the additive
subgroup generated by the products `unit × (elements of weight m)` -/

namespace AlgebraicGeometry.Scheme.GradedQCAlgebra

variable {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra)

/-- `𝒜.equiv i` sends the structure map to the constants; conversely, the preimage of the constant
`C c` is `sectionsUnitHom c`. -/
theorem atlas_equiv_symm_C {σ : Type u} (w : σ → ℕ)
    (𝒜 : S.toGradedAffineAlgebra.WeightedPolynomialAtlas w) (i : 𝒜.I)
    (c : Γ(X, (𝒜.chart i).toOpens)) :
    (𝒜.equiv i).symm (MvPolynomial.C c) = S.sectionsUnitHom (𝒜.chart i).toOpens c := by
  apply (𝒜.equiv i).injective
  rw [RingEquiv.apply_symm_apply]
  exact (𝒜.equiv_unit i c).symm

/-- **Algebraic core**: let `P` be an additive subgroup of the sections ring `S.sectionsRing C` of
the chart `C = 𝒜.chart i` containing all `sectionsUnitHom c * ∏_{j<ℓ} ofPiece (1*m) (b j)`
(`m = |σ| · jetWeight k`). Then every weighted homogeneous polynomial of weight `ℓ m` lands in `P`
under `(𝒜.equiv i).symm`.

Proof: by `IsWeightedHomogeneous.induction_on`; `0` and sums are clear, and a monomial `monomial d c`
is written by `exists_split_of_weight_eq_mul_fintype` as `C c * ∏_j monomial (f j) 1` with factors of
weight `m`, whose preimages lie in the piece `1*m` (`WeightedPolynomialAtlas.symm_mem`), i.e. are of
the form `ofPiece (1*m) (b j)`. -/
theorem symm_mem_of_isWeightedHomogeneous {σ : Type u} [Fintype σ] {k : ℕ} (w : σ → ℕ)
    (hw : ∀ i, w i ∈ Finset.Icc 1 k)
    (𝒜 : S.toGradedAffineAlgebra.WeightedPolynomialAtlas w) (i : 𝒜.I) (ℓ : ℕ) (hℓ : 1 ≤ ℓ)
    (P : AddSubgroup (S.sectionsRing (𝒜.chart i).toOpens))
    (hP : ∀ (c : Γ(X, (𝒜.chart i).toOpens))
      (b : Fin ℓ → S.sectionsPiece (𝒜.chart i).toOpens (1 * (Fintype.card σ * jetWeight k))),
      S.sectionsUnitHom (𝒜.chart i).toOpens c *
        ∏ j, S.ofPiece (𝒜.chart i).toOpens (1 * (Fintype.card σ * jetWeight k)) (b j) ∈ P)
    (p : MvPolynomial σ Γ(X, (𝒜.chart i).toOpens))
    (hp : p.IsWeightedHomogeneous w (ℓ * (Fintype.card σ * jetWeight k))) :
    (𝒜.equiv i).symm p ∈ P := by
  classical
  induction hp using MvPolynomial.IsWeightedHomogeneous.induction_on with
  | zero => rw [map_zero]; exact P.zero_mem
  | add p q _ _ ihp ihq => rw [map_add]; exact P.add_mem ihp ihq
  | monomial d c hd =>
    obtain ⟨f, hf, hsum⟩ := exists_split_of_weight_eq_mul_fintype w hw d ℓ hℓ hd
    rw [← hsum, MvPolynomial.monomial_sum_index, map_mul, map_prod, S.atlas_equiv_symm_C w 𝒜 i c]
    have hmem : ∀ j, (𝒜.equiv i).symm (MvPolynomial.monomial (f j) 1) ∈
        S.sectionsGrading (𝒜.chart i).toOpens (1 * (Fintype.card σ * jetWeight k)) :=
      fun j => 𝒜.symm_mem i (MvPolynomial.isWeightedHomogeneous_monomial w (f j) 1
        ((hf j).trans (Nat.one_mul _).symm))
    have hex : ∀ j, ∃ b : S.sectionsPiece (𝒜.chart i).toOpens (1 * (Fintype.card σ * jetWeight k)),
        S.ofPiece (𝒜.chart i).toOpens (1 * (Fintype.card σ * jetWeight k)) b =
          (𝒜.equiv i).symm (MvPolynomial.monomial (f j) 1) :=
      fun j => hmem j
    choose b hb using hex
    rw [show (∏ j, (𝒜.equiv i).symm (MvPolynomial.monomial (f j) 1)) =
        ∏ j, S.ofPiece (𝒜.chart i).toOpens (1 * (Fintype.card σ * jetWeight k)) (b j) from
      Finset.prod_congr rfl fun j _ => (hb j).symm]
    exact hP c b

end AlgebraicGeometry.Scheme.GradedQCAlgebra

/-! ## Step 3 (sheaf part): lifting products of sections of weight `m` to sections of tensor powers -/

open scoped CategoryTheory.MonoidalCategory

namespace AlgebraicGeometry.Scheme.Modules

variable {X : AlgebraicGeometry.Scheme.{u}}

/-- A composite morphism evaluated on sections. -/
theorem comp_app_apply {A B D : X.Modules} (f : A ⟶ B) (g : B ⟶ D) (U : X.Opens) (x : Γ(A, U)) :
    (f ≫ g).app U x = g.app U (f.app U x) := by
  rw [AlgebraicGeometry.Scheme.Modules.Hom.comp_app, ConcreteCategory.comp_apply]

/-- Right whiskering on pairs of sections: `(f ▷ B)(a ⊗ b) = f a ⊗ b` (`tensorHom_tensorSections`
with `ψ = 𝟙`). -/
theorem whiskerRight_app_tensorSections {A A' B : X.Modules} (f : A ⟶ A') (U : X.Opens)
    (a : Γ(A, U)) (b : Γ(B, U)) :
    (f ▷ B).app U (AlgebraicGeometry.Scheme.Modules.tensorSections A B U a b) =
      AlgebraicGeometry.Scheme.Modules.tensorSections A' B U (f.app U a) b := by
  rw [← MonoidalCategory.tensorHom_id]
  exact AlgebraicGeometry.Scheme.Modules.tensorHom_tensorSections f (𝟙 B) U a b

/-- For the isomorphism `Modules.tensor A B ≅ A ⊗ B`, `hom.app ∘ inv.app = id` on sections. -/
theorem tensorIsoTensorObj_hom_app_inv_app {A B : X.Modules} (U : X.Opens)
    (z : Γ(CategoryTheory.MonoidalCategoryStruct.tensorObj (C := X.Modules) A B, U)) :
    (AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj A B).hom.app U
      ((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj A B).inv.app U z) = z := by
  rw [← comp_app_apply, Iso.inv_hom_id, AlgebraicGeometry.Scheme.Modules.Hom.id_app]
  rfl

end AlgebraicGeometry.Scheme.Modules

namespace AlgebraicGeometry.Scheme.GradedQCAlgebra

variable {X : AlgebraicGeometry.Scheme.{u}}

/-- The value of `mulPowOne (ℓ+1)` on `(section of the tensor power) ⊗ (degree-one section)`: first
`mulPowOne ℓ`, then multiply. -/
theorem mulPowOne_succ_app (T : X.GradedQCAlgebra) (ℓ : ℕ) (C : X.Opens)
    (y : Γ(AlgebraicGeometry.Scheme.Modules.tensorPow (T.part 1) ℓ, C)) (b : Γ(T.part 1, C)) :
    (T.mulPowOne (ℓ + 1)).app C
        ((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj
          (AlgebraicGeometry.Scheme.Modules.tensorPow (T.part 1) ℓ) (T.part 1)).inv.app C
          (AlgebraicGeometry.Scheme.Modules.tensorSections
            (AlgebraicGeometry.Scheme.Modules.tensorPow (T.part 1) ℓ) (T.part 1) C y b)) =
      (T.mul ℓ 1).app C (AlgebraicGeometry.Scheme.Modules.tensorSections (T.part ℓ) (T.part 1) C
        ((T.mulPowOne ℓ).app C y) b) := by
  show ((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj
          (AlgebraicGeometry.Scheme.Modules.tensorPow (T.part 1) ℓ) (T.part 1)).hom ≫
        (T.mulPowOne ℓ ▷ T.part 1) ≫ T.mul ℓ 1).app C _ = _
  rw [AlgebraicGeometry.Scheme.Modules.comp_app_apply,
    AlgebraicGeometry.Scheme.Modules.comp_app_apply]
  refine congrArg ((T.mul ℓ 1).app C) ?_
  refine (congrArg ((T.mulPowOne ℓ ▷ T.part 1).app C)
    (AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj_hom_app_inv_app C _)).trans ?_
  exact AlgebraicGeometry.Scheme.Modules.whiskerRight_app_tensorSections (T.mulPowOne ℓ) C y b

variable (S : X.GradedQCAlgebra)

/-- The Veronese multiplication `S^{(m)}_ℓ ⊗ S^{(m)}_1 → S^{(m)}_{ℓ+1}` on a pair of sections is the
product in the sections ring. -/
theorem veronese_mul_app_ofPiece (m ℓ : ℕ) (C : X.Opens)
    (x : S.sectionsPiece C (ℓ * m)) (b : S.sectionsPiece C (1 * m)) :
    S.ofPiece C ((ℓ + 1) * m) (((S.veronese m).mul ℓ 1).app C
        (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part (ℓ * m)) (S.part (1 * m)) C x b)) =
      S.ofPiece C (ℓ * m) x * S.ofPiece C (1 * m) b := by
  have h1 : ((S.veronese m).mul ℓ 1).app C
      (AlgebraicGeometry.Scheme.Modules.tensorSections (S.part (ℓ * m)) (S.part (1 * m)) C x b) =
      (eqToHom (congrArg S.part (add_mul ℓ 1 m).symm)).app C (S.sectionsGMul C x b) :=
    AlgebraicGeometry.Scheme.Modules.comp_app_apply (S.mul (ℓ * m) (1 * m))
      (eqToHom (congrArg S.part (add_mul ℓ 1 m).symm)) C _
  refine (congrArg (S.ofPiece C ((ℓ + 1) * m)) h1).trans ?_
  refine (DirectSum.of_eq_of_gradedMonoid_eq
    (S.mk_eqToHom_app C (add_mul ℓ 1 m).symm (S.sectionsGMul C x b))).trans ?_
  exact (DirectSum.of_mul_of (A := S.sectionsPiece C) x b).symm

/-- The Veronese unit evaluated at `1` is `1` in the sections ring. -/
theorem veronese_mulPowOne_zero_app_ofPiece (m : ℕ) (C : X.Opens) :
    S.ofPiece C (0 * m) (((S.veronese m).mulPowOne 0).app C (1 : Γ(X, C))) = 1 := by
  have h0 : ((S.veronese m).mulPowOne 0).app C (1 : Γ(X, C)) =
      (eqToHom (congrArg S.part (zero_mul m).symm)).app C (S.one.app C (1 : Γ(X, C))) :=
    AlgebraicGeometry.Scheme.Modules.comp_app_apply S.one
      (eqToHom (congrArg S.part (zero_mul m).symm)) C (1 : Γ(X, C))
  refine (congrArg (S.ofPiece C (0 * m)) h0).trans ?_
  refine (DirectSum.of_eq_of_gradedMonoid_eq
    (S.mk_eqToHom_app C (zero_mul m).symm (S.one.app C (1 : Γ(X, C))))).trans ?_
  exact (DirectSum.one_def (S.sectionsPiece C)).symm

/-- **Product formula for sections of tensor powers**: for `b : Fin ℓ → Γ(S_{1·m}, C)` there is a
section `y` of the tensor power `(S^{(m)}_1)^{⊗ℓ}` over `C` which `mulPowOne ℓ` of the Veronese
algebra sends to `∏_j ofPiece (1*m) (b j)` in the sections ring.

Proof: induction on `ℓ`. For `ℓ = 0` take `y = 1` (`veronese_mulPowOne_zero_app_ofPiece`); for
`ℓ+1` take `y' = tensorIsoTensorObj.inv (y ⊗ b_ℓ)` and use `mulPowOne_succ_app` and
`veronese_mul_app_ofPiece`. -/
theorem exists_tensorPow_section_prod (m : ℕ) (C : X.Opens) :
    ∀ (ℓ : ℕ) (b : Fin ℓ → S.sectionsPiece C (1 * m)),
      ∃ y : Γ(AlgebraicGeometry.Scheme.Modules.tensorPow ((S.veronese m).part 1) ℓ, C),
        S.ofPiece C (ℓ * m) (((S.veronese m).mulPowOne ℓ).app C y) =
          ∏ j, S.ofPiece C (1 * m) (b j)
  | 0, _ => by
    refine ⟨(1 : Γ(X, C)), ?_⟩
    rw [Fin.prod_univ_zero]
    exact S.veronese_mulPowOne_zero_app_ofPiece m C
  | ℓ + 1, b => by
    obtain ⟨y, hy⟩ := exists_tensorPow_section_prod m C ℓ (fun j => b (Fin.castSucc j))
    refine ⟨(AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj
        (AlgebraicGeometry.Scheme.Modules.tensorPow ((S.veronese m).part 1) ℓ)
        ((S.veronese m).part 1)).inv.app C
      (AlgebraicGeometry.Scheme.Modules.tensorSections
        (AlgebraicGeometry.Scheme.Modules.tensorPow ((S.veronese m).part 1) ℓ)
        ((S.veronese m).part 1) C y (b (Fin.last ℓ))), ?_⟩
    refine (congrArg (S.ofPiece C ((ℓ + 1) * m))
      ((S.veronese m).mulPowOne_succ_app ℓ C y (b (Fin.last ℓ)))).trans ?_
    refine (S.veronese_mul_app_ofPiece m ℓ C _ _).trans ?_
    rw [hy, Fin.prod_univ_castSucc]

/-! ## Step 3 (assembly): on a chart, `mulPowOne ℓ` is surjective on sections -/

/-- **Surjectivity on a chart**: for a chart `C = 𝒜.chart i` and `ℓ ≥ 1`, the map on sections over `C`
of `mulPowOne ℓ : (S^{(m)}_1)^{⊗ℓ} → S^{(m)}_ℓ` of the Veronese algebra `S^{(m)}`
(`m = |σ| · jetWeight k`) is surjective.

Proof: the image `P` (in the sections ring) is an additive subgroup; by
`exists_tensorPow_section_prod` and `sectionsUnitHom_mul_ofPiece` it contains all
`unit c · ∏ ofPiece (b j)`; `ofPiece t` lies in the piece `ℓ m`, is a homogeneous polynomial of
weight `ℓ m` under the chart isomorphism, so `ofPiece t ∈ P` by `symm_mem_of_isWeightedHomogeneous`;
injectivity of `ofPiece` gives the preimage. -/
theorem exists_tensorPow_section_of_chart {σ : Type u} [Fintype σ] {k : ℕ} (w : σ → ℕ)
    (hw : ∀ i, w i ∈ Finset.Icc 1 k)
    (𝒜 : S.toGradedAffineAlgebra.WeightedPolynomialAtlas w) (i : 𝒜.I) (ℓ : ℕ) (hℓ : 1 ≤ ℓ)
    (m : ℕ) (hm : m = Fintype.card σ * jetWeight k)
    (t : Γ((S.veronese m).part ℓ, (𝒜.chart i).toOpens)) :
    ∃ y : Γ(AlgebraicGeometry.Scheme.Modules.tensorPow ((S.veronese m).part 1) ℓ,
        (𝒜.chart i).toOpens),
      ((S.veronese m).mulPowOne ℓ).app (𝒜.chart i).toOpens y = t := by
  classical
  subst hm
  let Φ : Γ(AlgebraicGeometry.Scheme.Modules.tensorPow
      ((S.veronese (Fintype.card σ * jetWeight k)).part 1) ℓ, (𝒜.chart i).toOpens) →
      S.sectionsRing (𝒜.chart i).toOpens :=
    fun y => S.ofPiece (𝒜.chart i).toOpens (ℓ * (Fintype.card σ * jetWeight k))
      (((S.veronese (Fintype.card σ * jetWeight k)).mulPowOne ℓ).app (𝒜.chart i).toOpens y)
  let P : AddSubgroup (S.sectionsRing (𝒜.chart i).toOpens) :=
    { carrier := Set.range Φ
      zero_mem' := ⟨0, by
        show S.ofPiece (𝒜.chart i).toOpens (ℓ * (Fintype.card σ * jetWeight k))
          (((S.veronese (Fintype.card σ * jetWeight k)).mulPowOne ℓ).app (𝒜.chart i).toOpens 0) = 0
        rw [map_zero]
        exact map_zero (DirectSum.of (S.sectionsPiece (𝒜.chart i).toOpens)
          (ℓ * (Fintype.card σ * jetWeight k)))⟩
      add_mem' := by
        rintro _ _ ⟨y₁, rfl⟩ ⟨y₂, rfl⟩
        refine ⟨y₁ + y₂, ?_⟩
        show S.ofPiece (𝒜.chart i).toOpens (ℓ * (Fintype.card σ * jetWeight k))
          (((S.veronese (Fintype.card σ * jetWeight k)).mulPowOne ℓ).app (𝒜.chart i).toOpens
            (y₁ + y₂)) = _
        rw [map_add]
        exact map_add (DirectSum.of (S.sectionsPiece (𝒜.chart i).toOpens)
          (ℓ * (Fintype.card σ * jetWeight k))) _ _
      neg_mem' := by
        rintro _ ⟨y, rfl⟩
        refine ⟨-y, ?_⟩
        show S.ofPiece (𝒜.chart i).toOpens (ℓ * (Fintype.card σ * jetWeight k))
          (((S.veronese (Fintype.card σ * jetWeight k)).mulPowOne ℓ).app (𝒜.chart i).toOpens
            (-y)) = _
        rw [map_neg]
        exact map_neg (DirectSum.of (S.sectionsPiece (𝒜.chart i).toOpens)
          (ℓ * (Fintype.card σ * jetWeight k))) _ }
  have hP : ∀ (c : Γ(X, (𝒜.chart i).toOpens))
      (b : Fin ℓ → S.sectionsPiece (𝒜.chart i).toOpens (1 * (Fintype.card σ * jetWeight k))),
      S.sectionsUnitHom (𝒜.chart i).toOpens c *
        ∏ j, S.ofPiece (𝒜.chart i).toOpens (1 * (Fintype.card σ * jetWeight k)) (b j) ∈ P := by
    intro c b
    obtain ⟨y, hy⟩ :=
      S.exists_tensorPow_section_prod (Fintype.card σ * jetWeight k) (𝒜.chart i).toOpens ℓ b
    refine ⟨c • y, ?_⟩
    show S.ofPiece (𝒜.chart i).toOpens (ℓ * (Fintype.card σ * jetWeight k))
      (((S.veronese (Fintype.card σ * jetWeight k)).mulPowOne ℓ).app (𝒜.chart i).toOpens
        (c • y)) = _
    rw [← hy, AlgebraicGeometry.Scheme.Modules.Hom.app_smul]
    exact (S.sectionsUnitHom_mul_ofPiece (𝒜.chart i).toOpens c _).symm
  have ht : S.ofPiece (𝒜.chart i).toOpens (ℓ * (Fintype.card σ * jetWeight k)) t ∈
      S.sectionsGrading (𝒜.chart i).toOpens (ℓ * (Fintype.card σ * jetWeight k)) := ⟨t, rfl⟩
  have hhom : (𝒜.equiv i (S.ofPiece (𝒜.chart i).toOpens (ℓ * (Fintype.card σ * jetWeight k)) t)
      ).IsWeightedHomogeneous w (ℓ * (Fintype.card σ * jetWeight k)) :=
    𝒜.equiv_isWeightedHomogeneous i ht
  obtain ⟨y, hy⟩ := S.symm_mem_of_isWeightedHomogeneous w hw 𝒜 i ℓ hℓ P hP _ hhom
  refine ⟨y, S.ofPiece_injective (𝒜.chart i).toOpens (ℓ * (Fintype.card σ * jetWeight k)) ?_⟩
  exact hy.trans ((𝒜.equiv i).symm_apply_apply _)

end AlgebraicGeometry.Scheme.GradedQCAlgebra

/-! ## Steps 1 and 4: the local surjectivity criterion and quasi-coherent localization -/

namespace AlgebraicGeometry.Scheme.Modules

variable {X : AlgebraicGeometry.Scheme.{u}}

/-- A morphism of sheaves of modules commutes with restriction (`PresheafOfModules.naturality_apply`
in the `X.Modules` spelling). -/
theorem app_map_res {M N : X.Modules} (φ : M ⟶ N) {U W : X.Opens} (h : W ≤ U) (x : Γ(M, U)) :
    φ.app W (M.presheaf.map (homOfLE h).op x) = N.presheaf.map (homOfLE h).op (φ.app U x) :=
  _root_.PresheafOfModules.naturality_apply φ.val (homOfLE h).op x

/-- **Surjective on sections over an affine cover implies epimorphism** (quasi-coherent target).
Let `φ : M ⟶ N` with `N` quasi-coherent, and let the affine opens `chart i` cover `X`; if the map
of `φ` on sections over every `chart i` is surjective, then `φ` is an epimorphism.

Proof: use the local criterion `epi_iff_locally_surjective_sections`. Given `U`, `s ∈ Γ(N, U)` and
`p ∈ U`, take a chart `C ∋ p` and a basic open `D(f) ⊆ U` of the affine open `C` containing `p`
(`IsAffineOpen.exists_basicOpen_le`). Quasi-coherence (`exists_pow_smul_eq_map_basicOpen`) gives `n`
and `t ∈ Γ(N, C)` with `t|_{D(f)} = f^n · s|_{D(f)}`. Take a preimage `y ∈ Γ(M, C)` of `t`; `f` is
invertible on `D(f)` (`isUnit_res_basicOpen`), so `f^{-n} · y|_{D(f)}` is a preimage of `s|_{D(f)}`. -/
theorem epi_of_surjective_sections_affine_cover {M N : X.Modules} [N.IsQuasicoherent]
    (φ : M ⟶ N) {I : Type*} (chart : I → X.AffineZariskiSite)
    (covers : ∀ x : X, ∃ i, x ∈ (chart i).toOpens)
    (h : ∀ (i : I) (t : Γ(N, (chart i).toOpens)),
      ∃ y : Γ(M, (chart i).toOpens), φ.app (chart i).toOpens y = t) :
    CategoryTheory.Epi φ := by
  rw [AlgebraicGeometry.Scheme.Modules.epi_iff_locally_surjective_sections]
  intro U s p hp
  obtain ⟨i, hi⟩ := covers p
  have hC : AlgebraicGeometry.IsAffineOpen (chart i).toOpens := (chart i).2
  obtain ⟨f, hfU, hpf⟩ := hC.exists_basicOpen_le (V := U) ⟨p, hp⟩ hi
  obtain ⟨n, t, ht⟩ := AlgebraicGeometry.Scheme.Modules.exists_pow_smul_eq_map_basicOpen N hC f
    (N.presheaf.map (homOfLE hfU).op s)
  obtain ⟨y, hy⟩ := h i t
  have hu : IsUnit (X.presheaf.map (homOfLE (X.basicOpen_le f)).op f) :=
    X.toRingedSpace.isUnit_res_basicOpen f
  have hvu : ((↑hu.unit⁻¹ : Γ(X, X.basicOpen f)) ^ n) *
      (X.presheaf.map (homOfLE (X.basicOpen_le f)).op f) ^ n = 1 := by
    rw [← mul_pow, IsUnit.val_inv_mul, one_pow]
  refine ⟨X.basicOpen f, hfU, hpf,
    ((↑hu.unit⁻¹ : Γ(X, X.basicOpen f)) ^ n) • M.presheaf.map (homOfLE (X.basicOpen_le f)).op y, ?_⟩
  rw [AlgebraicGeometry.Scheme.Modules.Hom.app_smul,
    AlgebraicGeometry.Scheme.Modules.app_map_res φ (X.basicOpen_le f) y, hy, ht, smul_smul, hvu,
    one_smul]

end AlgebraicGeometry.Scheme.Modules

theorem AlgebraicGeometry.Scheme.GradedQCAlgebra.veronese_generatedInDegreeOne_of_atlas
    {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra)
    {σ : Type u} [Fintype σ] [Nonempty σ] {k : ℕ} (w : σ → ℕ)
    (hw : ∀ i, w i ∈ Finset.Icc 1 k)
    (_atlas : S.toGradedAffineAlgebra.WeightedPolynomialAtlas w) :
    (S.veronese (Fintype.card σ * jetWeight k)).GeneratedInDegreeOne := by
  intro ℓ hℓ
  have : ((S.veronese (Fintype.card σ * jetWeight k)).part ℓ).IsQuasicoherent :=
    (S.veronese (Fintype.card σ * jetWeight k)).quasicoherent ℓ
  exact AlgebraicGeometry.Scheme.Modules.epi_of_surjective_sections_affine_cover _ _atlas.chart
    _atlas.covers
    (fun i t => S.exists_tensorPow_section_of_chart w hw _atlas i ℓ hℓ _ rfl t)

end
