import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.IdealSheaf.IdealSheafComapIdealEqMap
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks01og
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0804
import MiyaokaMori.AlgebraicGeometry.Blowup.SurfaceBlowup

/-! # The exceptional ideal of a blowup is invertible

Stacks 02OS (2) (= first half of Stacks 0806): the inverse image ideal `I·O_{Bl_I X}` of the centre on the
blowup `b : Bl_I X = Proj_X(⊕ Iⁿ) → X` is invertible, i.e. locally generated by a nonzerodivisor
(the predicate `MiyaokaMori.Statement.IsInvertibleIdeal`, which is the second field of
`EffCartier`, so this is literally "the exceptional divisor is an effective Cartier divisor").

Source: Stacks 0806 (first assertion), proved there via Stacks 02OS (2) and 052Q; the paper uses the
blowup only through this universal property (point blowups of surfaces, strict transforms).

The proof assembles the affine charts of Stacks 0804 (`blowup_preimage_affine_cover`), the affine-local
formula for `comap` (`IdealSheafData.comap_ideal_eq_map_appLE`) and the ring-theoretic facts on
`A[I/a]` (`MiyaokaMori.RingTheory.IdealFractionChart`), via two helper lemmas:
`Scheme.Hom.appLE_eq_of_iso_spec` (transport of `appLE` along a chart) and
`Ideal.map_comp_eq_span_singleton_of_bijective` (transport of a principal ideal along a ring isomorphism).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- Step 3 of `blowup_exceptional_isInvertibleIdeal` (transport along an affine chart), stated for an
arbitrary morphism `f : Y ⟶ X`: if an open `W ≤ f⁻¹U` of `Y` (with `U ⊆ X` affine) carries an
isomorphism `e : W ≅ Spec R` under which `f|_W` becomes `Spec.map φ` for a ring map `φ : Γ(X, U) ⟶ R`
(the compatibility `he` is exactly the one produced by `blowup_preimage_affine_cover`, Stacks 0804),
then the ring map `f.appLE U W : Γ(X, U) ⟶ Γ(Y, W)` is `φ` followed by the ring isomorphism
`R ≅ Γ(Spec R, ⊤) ≅ Γ(W, ⊤) ≅ Γ(Y, W)` induced by `e`.

Proof: compose `he` with `U.isoSpec.inv ≫ U.ι` to get `W.ι ≫ f = e.hom ≫ Spec.map φ ≫ U.fromSpec`
(`morphismRestrict_ι`, `homOfLE_ι`); apply `appLE U ⊤` to both sides. On the left this is
`f.appLE U W ≫ W.topIso.inv` (`appLE_comp_appLE`, `Opens.ι_appLE`); on the right it is
`(ΓSpecIso Γ(X, U)).inv ≫ (Spec.map φ).appTop ≫ e.hom.appTop` (`fromSpec_app_self`, `appLE_eq_app`),
and `ΓSpecIso_inv_naturality` identifies the first two factors with `φ ≫ (ΓSpecIso R).inv`. -/
theorem AlgebraicGeometry.Scheme.Hom.appLE_eq_of_iso_spec {X Y : AlgebraicGeometry.Scheme.{u}}
    (f : Y ⟶ X) (U : X.affineOpens) (W : Y.Opens) (h : W ≤ f ⁻¹ᵁ (U : X.Opens))
    (R : CommRingCat.{u}) (φ : Γ(X, U) ⟶ R) (e : W.toScheme ≅ AlgebraicGeometry.Spec R)
    (he : e.inv ≫ Y.homOfLE h ≫ (f ∣_ (U : X.Opens)) ≫ U.2.isoSpec.hom =
      AlgebraicGeometry.Spec.map φ) :
    f.appLE U W h =
      φ ≫ (AlgebraicGeometry.Scheme.ΓSpecIso R).inv ≫ e.hom.appTop ≫ W.topIso.hom := by
  have h1 : W.ι ≫ f = e.hom ≫ AlgebraicGeometry.Spec.map φ ≫ U.2.fromSpec := by
    rw [← he]
    show _ = e.hom ≫ (e.inv ≫ Y.homOfLE h ≫ (f ∣_ (U : X.Opens)) ≫ U.2.isoSpec.hom) ≫
      U.2.isoSpec.inv ≫ (U : X.Opens).ι
    simp only [Category.assoc, Iso.hom_inv_id_assoc]
    rw [morphismRestrict_ι, Scheme.homOfLE_ι_assoc]
  have hle : (⊤ : W.toScheme.Opens) ≤ (W.ι ≫ f) ⁻¹ᵁ (U : X.Opens) := by
    intro x _
    exact h x.2
  have hWle : (⊤ : W.toScheme.Opens) ≤ W.ι ⁻¹ᵁ W := by
    intro x _
    exact x.2
  have h2 : f.appLE U W h ≫ W.topIso.inv = (W.ι ≫ f).appLE U ⊤ hle := by
    rw [← Scheme.Hom.appLE_comp_appLE W.ι f (U : X.Opens) W ⊤ h hWle, Scheme.Opens.ι_appLE,
      Scheme.Opens.topIso_inv]
    rfl
  have key : ∀ (g : W.toScheme ⟶ X) (hg : (⊤ : W.toScheme.Opens) ≤ g ⁻¹ᵁ (U : X.Opens)),
      g = e.hom ≫ AlgebraicGeometry.Spec.map φ ≫ U.2.fromSpec →
      g.appLE U ⊤ hg = (AlgebraicGeometry.Scheme.ΓSpecIso Γ(X, U)).inv ≫
        (AlgebraicGeometry.Spec.map φ).appTop ≫ e.hom.appTop := by
    rintro g hg rfl
    have hA' : (⊤ : (AlgebraicGeometry.Spec Γ(X, U)).Opens) ≤ U.2.fromSpec ⁻¹ᵁ (U : X.Opens) := by
      rw [U.2.fromSpec_preimage_self]
    have hA : U.2.fromSpec.appLE U ⊤ hA' = (AlgebraicGeometry.Scheme.ΓSpecIso Γ(X, U)).inv := by
      rw [Scheme.Hom.appLE, U.2.fromSpec_app_self, Category.assoc, ← Functor.map_comp]
      convert Category.comp_id _
      exact CategoryTheory.Functor.map_id _ _
    have hB' : (⊤ : (AlgebraicGeometry.Spec R).Opens) ≤ AlgebraicGeometry.Spec.map φ ⁻¹ᵁ ⊤ :=
      fun _ _ => trivial
    have hC' : (⊤ : W.toScheme.Opens) ≤ e.hom ⁻¹ᵁ ⊤ := fun _ _ => trivial
    have hA'' : (⊤ : (AlgebraicGeometry.Spec R).Opens) ≤
        (AlgebraicGeometry.Spec.map φ ≫ U.2.fromSpec) ⁻¹ᵁ (U : X.Opens) :=
      fun x _ => hA' (Set.mem_univ (AlgebraicGeometry.Spec.map φ x))
    have hB : (AlgebraicGeometry.Spec.map φ).appLE ⊤ ⊤ hB' =
        (AlgebraicGeometry.Spec.map φ).appTop := Scheme.Hom.appLE_eq_app _
    have hC : e.hom.appLE ⊤ ⊤ hC' = e.hom.appTop := Scheme.Hom.appLE_eq_app _
    have s2 := Scheme.Hom.appLE_comp_appLE (AlgebraicGeometry.Spec.map φ) U.2.fromSpec
      (U : X.Opens) ⊤ ⊤ hA' hB'
    have s1 := Scheme.Hom.appLE_comp_appLE e.hom (AlgebraicGeometry.Spec.map φ ≫ U.2.fromSpec)
      (U : X.Opens) ⊤ ⊤ hA'' hC'
    calc (e.hom ≫ AlgebraicGeometry.Spec.map φ ≫ U.2.fromSpec).appLE U ⊤ hg
        = (AlgebraicGeometry.Spec.map φ ≫ U.2.fromSpec).appLE U ⊤ hA'' ≫ e.hom.appLE ⊤ ⊤ hC' :=
          s1.symm
      _ = (U.2.fromSpec.appLE U ⊤ hA' ≫ (AlgebraicGeometry.Spec.map φ).appLE ⊤ ⊤ hB') ≫
          e.hom.appLE ⊤ ⊤ hC' := by rw [s2]
      _ = _ := by rw [hA, hB, hC, Category.assoc]
  have h3 := key _ hle h1
  have h5 : f.appLE U W h = ((AlgebraicGeometry.Scheme.ΓSpecIso Γ(X, U)).inv ≫
      (AlgebraicGeometry.Spec.map φ).appTop ≫ e.hom.appTop) ≫ W.topIso.hom :=
    (Iso.comp_inv_eq _).mp (h2.trans h3)
  rw [h5]
  simp only [Category.assoc]
  rw [Scheme.ΓSpecIso_inv_naturality_assoc]

/-- Step 4 of `blowup_exceptional_isInvertibleIdeal`: if `I₀ φ = (φ a)` with `φ a` a nonzerodivisor,
then along a bijective ring map `ψ` we still have `I₀ (ψ ∘ φ) = (ψ (φ a))` with `ψ (φ a)` a
nonzerodivisor (`Ideal.map_map`, `Ideal.map_span`; for the nonzerodivisor property write `r = ψ s`
and use injectivity of `ψ`). -/
theorem Ideal.map_comp_eq_span_singleton_of_bijective {A B C : Type*} [CommRing A] [CommRing B]
    [CommRing C] (I₀ : Ideal A) (φ : A →+* B) (ψ : B →+* C) (hψ : Function.Bijective ψ) (a : A)
    (hspan : I₀.map φ = Ideal.span {φ a}) (hnzd : ∀ r : B, φ a * r = 0 → r = 0) :
    (∀ r : C, ψ (φ a) * r = 0 → r = 0) ∧ I₀.map (ψ.comp φ) = Ideal.span {ψ (φ a)} := by
  refine ⟨fun r hr => ?_, ?_⟩
  · obtain ⟨s, rfl⟩ := hψ.2 r
    rw [← map_mul] at hr
    have hs : φ a * s = 0 := hψ.1 (hr.trans (map_zero ψ).symm)
    rw [hnzd s hs, map_zero]
  · rw [← Ideal.map_map, hspan, Ideal.map_span, Set.image_singleton]

/-- **Stacks 02OS(2)**: the exceptional ideal `I.comap b` of the blowup `b = (blowup I).hom` is invertible.

Proof. `IsInvertibleIdeal` is a pointwise condition, so fix a point
`x'` of `Bl := (blowup I).left` and put `x := b x'`. Choose an affine open `U ∋ x` of `X`, write
`A := Γ(X, U)` and `I₀ := I.ideal U`.

1. **Affine charts of the blowup (Stacks 0804, `blowup_preimage_affine_cover`)**:
   `b⁻¹U = ⋃_{a ∈ I₀} V_a` with isomorphisms `e_a : V_a ≅ Spec A[I₀/a]` (`Ideal.affineBlowup I₀ a`
   `= MiyaokaMori.RingTheory.IdealFractionChart.chart I₀ a ⊆ A_a`) such that
   `e_a.inv ≫ (V_a ↪ b⁻¹U) ≫ (b ∣_ U) ≫ U.isoSpec.hom = Spec.map (algebraMap A A[I₀/a])`.
   Pick `a` with `x' ∈ V_a`. `V_a` is an affine open (it is isomorphic to an affine scheme), so it is the
   affine neighbourhood required by `IsInvertibleIdeal`; it remains to produce the generator.
2. **Affine-local formula for the inverse image ideal** (`IdealSheafData.comap_ideal_eq_map_appLE`):
   since `V_a ≤ b⁻¹U`, `(I.comap b).ideal V_a = I₀.map (b.appLE U V_a _)`.
3. **Transport along the chart**: taking global sections of the compatibility in 1 (and `Γ(U, ⊤) ≅ A` via
   `U.isoSpec`, `Scheme.ΓSpecIso`), the ring map `b.appLE U V_a _ : A → Γ(Bl, V_a)` is, up to the ring
   isomorphism `Γ(Bl, V_a) ≅ A[I₀/a]` induced by `e_a`, the structure map `algebraMap A A[I₀/a]`.
   Hence `(I.comap b).ideal V_a` corresponds under this ring isomorphism to
   `I₀.map (algebraMap A A[I₀/a]) = span {algebraMap A A[I₀/a] a}`
   (`MiyaokaMori.RingTheory.IdealFractionChart.centerExtension_eq_span`; needs `a ∈ I₀`, which holds).
4. **The generator is a nonzerodivisor**: `algebraMap A A[I₀/a] a` is a nonzerodivisor in `A[I₀/a]`
   (`MiyaokaMori.RingTheory.IdealFractionChart.generator_mul_eq_zero`: `A[I₀/a] ⊆ A_a` and `a` is a unit of `A_a`).
   Pull the generator back along the ring isomorphism of 3: ring isomorphisms preserve `Ideal.span {·}` and
   nonzerodivisors, giving `t ∈ Γ(Bl, V_a)` with `(I.comap b).ideal V_a = span {t}` and `t` a nonzerodivisor.

Edge cases: `I = ⊤`: `comap ⊤ = ⊤`, generated by the nonzerodivisor `1` (fine). `I = ⊥`: the Rees algebra
is `O_X` in degree `0`, its relative Proj is empty, and the statement is vacuous. `X = ∅`: vacuous.

Stacks 0AG8 (`effectiveCartier_of_locally_principal_nzd`, which needs `IsLocallyNoetherian`)
is **not** needed: `IsInvertibleIdeal` already *is* the local condition. -/
theorem AlgebraicGeometry.Scheme.blowup_exceptional_isInvertibleIdeal {X : AlgebraicGeometry.Scheme.{u}}
    (I : X.IdealSheafData) :
    MiyaokaMori.Statement.IsInvertibleIdeal (I.comap (AlgebraicGeometry.Scheme.blowup I).hom) := by
  intro x'
  obtain ⟨_, ⟨U, hU, rfl⟩, hxU, -⟩ := X.isBasis_affineOpens.exists_subset_of_mem_open
    (Set.mem_univ ((AlgebraicGeometry.Scheme.blowup I).hom x')) isOpen_univ
  obtain ⟨V, hV, hE, hcov⟩ := AlgebraicGeometry.Scheme.blowup_preimage_affine_cover I ⟨U, hU⟩
  have hx'cov : x' ∈ ⨆ a, V a := by
    rw [hcov]
    exact hxU
  obtain ⟨a, hxa⟩ := Opens.mem_iSup.mp hx'cov
  obtain ⟨e, he⟩ := hE a
  have hWaff : IsAffineOpen (V a) := IsAffine.of_isIso e.hom
  refine ⟨⟨V a, hWaff⟩, hxa, ?_⟩
  have hideal := AlgebraicGeometry.Scheme.IdealSheafData.comap_ideal_eq_map_appLE I
    (AlgebraicGeometry.Scheme.blowup I).hom ⟨U, hU⟩ ⟨V a, hWaff⟩ (hV a)
  rw [Scheme.Hom.appLE_eq_of_iso_spec _ ⟨U, hU⟩ (V a) (hV a) _ _ e he] at hideal
  let ψ : CommRingCat.of (Ideal.affineBlowup (I.ideal ⟨U, hU⟩) (a : Γ(X, U))) ⟶
      Γ((AlgebraicGeometry.Scheme.blowup I).left, V a) :=
    (AlgebraicGeometry.Scheme.ΓSpecIso _).inv ≫ e.hom.appTop ≫ (V a).topIso.hom
  have hbij : Function.Bijective ψ.hom := ConcreteCategory.bijective_of_isIso
    ((AlgebraicGeometry.Scheme.ΓSpecIso _).symm ≪≫ AlgebraicGeometry.Scheme.Γ.mapIso e.op ≪≫
      (V a).topIso).hom
  obtain ⟨h1, h2⟩ := Ideal.map_comp_eq_span_singleton_of_bijective (I.ideal ⟨U, hU⟩)
    (algebraMap Γ(X, U) (Ideal.affineBlowup (I.ideal ⟨U, hU⟩) (a : Γ(X, U)))) ψ.hom hbij a
    (MiyaokaMori.RingTheory.IdealFractionChart.centerExtension_eq_span _ _ a.2)
    (MiyaokaMori.RingTheory.IdealFractionChart.generator_mul_eq_zero _ _)
  exact ⟨ψ.hom (algebraMap Γ(X, U) (Ideal.affineBlowup (I.ideal ⟨U, hU⟩) (a : Γ(X, U))) a), h1,
    hideal.trans h2⟩

end
