import MiyaokaMori.AlgebraicGeometry.Blowup.SurfaceBlowup

/-!
# The centre ideal away from a closed point

The unit ideal is locally generated by the nonzerodivisor `1`. For a closed point,
the support of its canonical point ideal is the point itself. Pulling that ideal
back along a morphism whose image avoids the point therefore gives the unit ideal.
These ordinary lemmas supply the ideal-theoretic input for the universal-property
proof that a point blowup is an isomorphism away from its centre.
-/

open AlgebraicGeometry CategoryTheory TopologicalSpace

namespace MiyaokaMori.Statement

universe u

/-- The unit ideal is invertible, with local generator `1` on every affine open. -/
theorem isInvertibleIdeal_top (X : Scheme.{u}) :
    IsInvertibleIdeal (⊤ : X.IdealSheafData) := by
  intro x
  obtain ⟨_, ⟨U, hU, rfl⟩, hxU, -⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open (Set.mem_univ x) isOpen_univ
  refine ⟨⟨U, hU⟩, hxU, 1, ?_, ?_⟩
  · intro r hr
    simpa only [one_mul] using hr
  · simp

/-- The actual point ideal pulls back to the unit ideal along any morphism whose
image avoids the closed point. -/
theorem pointIdeal_comap_eq_top_of_avoids
    {X T : Scheme.{u}} (x : X) (hx : IsClosed ({x} : Set X))
    (f : T ⟶ X) (havoid : ∀ t : T, f t ≠ x) :
    (pointIdeal X x).comap f = ⊤ := by
  apply (Scheme.IdealSheafData.support_eq_bot_iff _).mp
  rw [Scheme.IdealSheafData.support_comap]
  ext t
  change f t ∈ ((pointIdeal X x).support : Set X) ↔ t ∈ (∅ : Set T)
  rw [pointIdeal, Scheme.Hom.support_ker, Scheme.range_fromSpecResidueField, hx.closure_eq]
  simpa only [Set.mem_singleton_iff, Set.mem_empty_iff_false, iff_false] using havoid t

end MiyaokaMori.Statement
