import MiyaokaMori.AlgebraicGeometry.Blowup.SurfaceBlowup

/-!
# The complement of an invertible ideal and its pullbacks

The complement of the support of an invertible ideal is affine over the ambient
scheme, hence its open immersion is quasi-compact. Locally the ideal is generated
by an actual section, and its complement is the corresponding affine basic open.

For any morphism to the ambient scheme, the complement of the pulled-back ideal
is the inverse image of this same open. Its inclusion is quasi-compact by base
change, even when the pulled-back ideal is no longer invertible.

This is the quasi-compactness input for the strict-transform closure model used for the
point blowups of Corollary 4.3 of the paper (§4). Sources: Stacks Tag 07ZT and the
paragraph preceding the strict-transform definition, Tag 080D.
-/

open AlgebraicGeometry CategoryTheory

namespace MiyaokaMori.Statement

universe u

variable {X T : Scheme.{u}}

/-- On an affine open where the actual ideal is generated by `a`, its support
complement is the actual basic open of `a`. -/
theorem support_compl_inf_eq_basicOpen_of_ideal_eq_span
    (I : X.IdealSheafData) (U : X.affineOpens) (a : Γ(X, U))
    (ha : I.ideal U = Ideal.span ({a} : Set Γ(X, U))) :
    I.support.compl ⊓ U.1 = X.basicOpen a := by
  ext x
  change (x ∉ I.support ∧ x ∈ U.1) ↔ x ∈ X.basicOpen a
  have hlocal (hxU : x ∈ U.1) : x ∈ I.support ↔ x ∉ X.basicOpen a := by
    rw [I.mem_support_iff_of_mem hxU, ha, X.zeroLocus_span, X.zeroLocus_singleton]
    rfl
  constructor
  · rintro ⟨hx, hxU⟩
    exact not_not.mp (mt (hlocal hxU).mpr hx)
  · intro hx
    have hxU : x ∈ U.1 := X.basicOpen_le a hx
    exact ⟨fun hs ↦ (hlocal hxU).mp hs hx, hxU⟩

/-- The support complement of the same invertible ideal is affine over `X`.
Only local principal generation is used; no global finiteness of `X` is assumed. -/
theorem IsInvertibleIdeal.isAffineHom_support_compl
    {I : X.IdealSheafData} (hI : IsInvertibleIdeal I) :
    IsAffineHom (Scheme.Opens.ι (X := X) I.support.compl) := by
  apply isAffineHom_of_forall_exists_isAffineOpen
  intro x
  obtain ⟨U, hxU, a, _, ha⟩ := hI x
  refine ⟨U.1, hxU, U.2, ?_⟩
  apply (Scheme.Opens.ι (X := X) I.support.compl).isAffineOpen_iff_of_isOpenImmersion.mp
  rw [Scheme.Hom.image_preimage_eq_opensRange_inf, Scheme.Opens.opensRange_ι,
    support_compl_inf_eq_basicOpen_of_ideal_eq_span I U a ha]
  exact U.2.basicOpen a

/-- The support-complement inclusion of an invertible ideal is quasi-compact. -/
theorem IsInvertibleIdeal.quasiCompact_support_compl
    {I : X.IdealSheafData} (hI : IsInvertibleIdeal I) :
    QuasiCompact (Scheme.Opens.ι (X := X) I.support.compl) := by
  have : IsAffineHom (Scheme.Opens.ι (X := X) I.support.compl) := hI.isAffineHom_support_compl
  infer_instance

/-- Pulling back an actual ideal pulls back its support complement as the same open subset. -/
theorem support_comap_compl_eq_preimage (I : X.IdealSheafData) (f : T ⟶ X) :
    (I.comap f).support.compl = f ⁻¹ᵁ I.support.compl := by
  rw [Scheme.IdealSheafData.support_comap]
  rfl

/-- After arbitrary base change, the support-complement inclusion remains quasi-compact.
The pulled-back ideal need not be invertible, and `f` need not be flat or quasi-compact. -/
theorem IsInvertibleIdeal.quasiCompact_comap_support_compl
    {I : X.IdealSheafData} (hI : IsInvertibleIdeal I) (f : T ⟶ X) :
    QuasiCompact (Scheme.Opens.ι (X := T) (I.comap f).support.compl) := by
  rw [support_comap_compl_eq_preimage]
  exact MorphismProperty.of_isPullback (P := @QuasiCompact)
    (isPullback_morphismRestrict f I.support.compl) hI.quasiCompact_support_compl

end MiyaokaMori.Statement
