import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Blowup.QuasiCompactComplSupportLocallyPrincipal
import MiyaokaMori.AlgebraicGeometry.Modules.IdealSheaf.IdealSheafComapIdealEqMap
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks01og
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0806IsBlowup
import MiyaokaMori.AlgebraicGeometry.Modules.IdealSheaf.Stacks07zp

/-! # Stacks 080D / 080E (1): the strict transform is the blowup of the inverse image ideal

Let `f : X → S` be a morphism and `Z ⊂ S` a closed subscheme. The strict transform of `X` relative to
the blowup `S' = Bl_Z S` (the closed subscheme of `X ×_S S'` cut out by the ideal generated by the
sections supported on the exceptional divisor) is the blowup of `X` along `f⁻¹Z`.

Used in the proof of Lemma 5.1 of the paper (§5): the strict transform of a smooth
rational curve is again a smooth rational curve.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- **Stacks 080D**: the ideal of the strict transform, i.e. the sections of `X ×_S Bl_Z S` supported on
`E' := pr₂⁻¹(E)`, where `E` is the exceptional divisor (the support of `exceptionalIdeal`). It is written
as the kernel `ker(O → j_*O)` of the open immersion `j` of the complement of `E'`, which is the body of
the definition of `IdealSheafData.supportedOn E'` (Stacks 07ZP); `supportedOn` additionally carries the
instance hypothesis that `j` is quasi-compact, used only for its properties (here quasi-compactness of
`j` follows from Stacks 0806 but is not used in the definition). -/
noncomputable def AlgebraicGeometry.Scheme.strictTransformIdeal {X S : AlgebraicGeometry.Scheme.{u}}
    (f : X ⟶ S) (I : S.IdealSheafData) :
    (CategoryTheory.Limits.pullback f (AlgebraicGeometry.Scheme.blowup I).hom).IdealSheafData :=
  let Pb : AlgebraicGeometry.Scheme.{u} :=
    CategoryTheory.Limits.pullback f (AlgebraicGeometry.Scheme.blowup I).hom
  let E' : TopologicalSpace.Closeds Pb :=
    ((AlgebraicGeometry.Scheme.blowup.exceptionalIdeal I).comap
      (CategoryTheory.Limits.pullback.snd f (AlgebraicGeometry.Scheme.blowup I).hom)).support
  (AlgebraicGeometry.Scheme.Opens.ι
    (⟨(E' : Set Pb)ᶜ, E'.isClosed.isOpen_compl⟩ : Pb.Opens)).ker

namespace AlgebraicGeometry.Scheme

variable {X S : Scheme.{u}} (f : X ⟶ S) (I : S.IdealSheafData)

/-- The pulled-back exceptional locus `E' = pr₂⁻¹(E) ⊆ X ×_S Bl_I S` (a closed set). -/
abbrev strictTransform.exceptionalLocus : Closeds (pullback f (blowup I).hom : Scheme.{u}) :=
  ((blowup.exceptionalIdeal I).comap (pullback.snd f (blowup I).hom)).support

/-- The open complement `X ×_S Bl_I S ∖ E'`. -/
abbrev strictTransform.exceptionalCompl : (pullback f (blowup I).hom : Scheme.{u}).Opens :=
  ⟨((strictTransform.exceptionalLocus f I : Set (pullback f (blowup I).hom : Scheme.{u})))ᶜ,
    (strictTransform.exceptionalLocus f I).isClosed.isOpen_compl⟩

theorem strictTransformIdeal_eq :
    strictTransformIdeal f I = (strictTransform.exceptionalCompl f I).ι.ker := rfl

/-- `E'` is the preimage of the centre `Z = supp I` under `X ×_S Bl_I S → X → S`. -/
theorem strictTransform.coe_exceptionalLocus :
    (strictTransform.exceptionalLocus f I : Set (pullback f (blowup I).hom : Scheme.{u})) =
      (pullback.fst f (blowup I).hom ≫ f).base ⁻¹' (I.support : Set S) := by
  rw [pullback.condition]
  simp only [strictTransform.exceptionalLocus, blowup.exceptionalIdeal,
    IdealSheafData.support_comap, Closeds.coe_preimage, Scheme.Hom.comp_base, TopCat.coe_comp,
    Set.preimage_comp]

/-- For any `l : Y ⟶ X ×_S Bl_I S`, `l⁻¹(E')` is the support of `(f⁻¹I)·O_Y` pulled back along
`l ≫ pr₁`. -/
theorem strictTransform.preimage_exceptionalLocus {Y : Scheme.{u}}
    (l : Y ⟶ pullback f (blowup I).hom) :
    l.base ⁻¹' (strictTransform.exceptionalLocus f I : Set (pullback f (blowup I).hom : Scheme.{u})) =
      (((I.comap f).comap (l ≫ pullback.fst f (blowup I).hom)).support : Set Y) := by
  rw [strictTransform.coe_exceptionalLocus]
  simp only [IdealSheafData.support_comap, Closeds.coe_preimage, Scheme.Hom.comp_base, TopCat.coe_comp,
    Set.preimage_comp]

end AlgebraicGeometry.Scheme

/-- A section vanishing off the support of a locally principal (invertible) ideal is zero. -/
theorem MiyaokaMori.Statement.IsInvertibleIdeal.eq_zero_of_res_eq_zero {Y : AlgebraicGeometry.Scheme.{u}}
    {D : Y.IdealSheafData} (hD : MiyaokaMori.Statement.IsInvertibleIdeal D) {V W : Y.Opens}
    (hWV : W ≤ V) (hW : (V : Set Y) \ (D.support : Set Y) ⊆ W) (s : Γ(Y, V))
    (hs : Y.presheaf.map (homOfLE hWV).op s = 0) : s = 0 := by
  apply TopCat.Presheaf.section_ext Y.sheaf V s 0
  intro y hyV
  obtain ⟨U₀, hyU₀, a, ha, hDa⟩ := hD y
  obtain ⟨g, hgV, hyg⟩ := U₀.2.exists_basicOpen_le ⟨y, hyV⟩ hyU₀
  have hUaff : AlgebraicGeometry.IsAffineOpen (Y.basicOpen g) := U₀.2.basicOpen g
  let U : Y.affineOpens := ⟨Y.basicOpen g, hUaff⟩
  have hUU₀ : U.1 ≤ U₀.1 := Y.basicOpen_le g
  let a' : Γ(Y, U) := Y.presheaf.map (homOfLE hUU₀).op a
  have hDa' : D.ideal U = Ideal.span {a'} := by
    rw [← D.map_ideal hUU₀, hDa, Ideal.map_span, Set.image_singleton]
    rfl
  have ha' : ∀ r : Γ(Y, U), a' * r = 0 → r = 0 := by
    have hnzd := U₀.2.res_mem_nonZeroDivisors
      (mem_nonZeroDivisors_iff_right.mpr fun r hr => ha r (by rwa [mul_comm])) hUU₀
    intro r hr
    exact mem_nonZeroDivisors_iff_right.mp hnzd r (by rwa [mul_comm])
  let s' : Γ(Y, U) := Y.presheaf.map (homOfLE hgV).op s
  have hbW : Y.basicOpen a' ≤ W := by
    intro x hx
    have hxU : x ∈ U.1 := Y.basicOpen_le a' hx
    apply hW
    refine ⟨hgV hxU, fun hxD => ?_⟩
    have hxD' : x ∈ D.support := hxD
    rw [D.mem_support_iff_of_mem hxU, hDa', AlgebraicGeometry.Scheme.zeroLocus_span,
      AlgebraicGeometry.Scheme.zeroLocus_singleton] at hxD'
    exact hxD' hx
  have hs' : Y.presheaf.map (homOfLE (Y.basicOpen_le a')).op s' = 0 := by
    have : Y.presheaf.map (homOfLE (Y.basicOpen_le a')).op s' =
        Y.presheaf.map (homOfLE hbW).op (Y.presheaf.map (homOfLE hWV).op s) := by
      simp only [s', ← ConcreteCategory.comp_apply, ← Functor.map_comp]
      rfl
    rw [this, hs, map_zero]
  have hloc := hUaff.isLocalization_basicOpen a'
  have hs'' : algebraMap Γ(Y, U) Γ(Y, Y.basicOpen a') s' = 0 := hs'
  obtain ⟨⟨m, n, rfl⟩, hm⟩ :=
    (IsLocalization.map_eq_zero_iff (Submonoid.powers a') Γ(Y, Y.basicOpen a') s').mp hs''
  have hs'0 : s' = 0 := by
    clear hs'' hs' hloc
    induction n with
    | zero => simpa using hm
    | succ n ih =>
      apply ih
      apply ha'
      rw [← mul_assoc, ← pow_succ']
      exact hm
  rw [map_zero]
  change Y.presheaf.germ V y hyV s = 0
  rw [← Y.presheaf.germ_res_apply (homOfLE hgV) y hyg s]
  change Y.presheaf.germ U y hyg s' = 0
  rw [hs'0, map_zero]

namespace AlgebraicGeometry.Scheme

variable {X S : Scheme.{u}} (f : X ⟶ S) (I : S.IdealSheafData)

/-- Sections supported on `E'` pull back to zero along any `l : Y ⟶ X ×_S Bl_I S` for which the
pulled-back centre `(f⁻¹I)·O_Y` is invertible. -/
theorem strictTransformIdeal_le_ker {Y : Scheme.{u}} (l : Y ⟶ pullback f (blowup I).hom)
    (hl : MiyaokaMori.Statement.IsInvertibleIdeal
      ((I.comap f).comap (l ≫ pullback.fst f (blowup I).hom))) :
    strictTransformIdeal f I ≤ l.ker := by
  rw [strictTransformIdeal_eq]
  refine IdealSheafData.le_ofIdeals_iff.mpr ?_
  intro U s hs
  have h1 : (strictTransform.exceptionalCompl f I).ι.app U s = 0 :=
    (strictTransform.exceptionalCompl f I).ι.ideal_ker_le U hs
  rw [Opens.ι_app] at h1
  set j := (strictTransform.exceptionalCompl f I).ι with hj
  set W₀ : (pullback f (blowup I).hom : Scheme.{u}).Opens := j ''ᵁ (j ⁻¹ᵁ U) with hW₀
  have hW₀U : W₀ ≤ U := j.image_preimage_le U
  have hWV : l ⁻¹ᵁ W₀ ≤ l ⁻¹ᵁ U := fun y hy => hW₀U hy
  show l.app U s = 0
  refine hl.eq_zero_of_res_eq_zero hWV ?_ (l.app U s) ?_
  · rintro y ⟨hyU, hyD⟩
    have hyE : l.base y ∉ (strictTransform.exceptionalLocus f I :
        Set (pullback f (blowup I).hom : Scheme.{u})) := by
      intro h
      apply hyD
      rw [← strictTransform.preimage_exceptionalLocus]
      exact h
    show l.base y ∈ W₀
    rw [hW₀, j.image_preimage_eq_opensRange_inf, Opens.opensRange_ι]
    exact ⟨hyE, hyU⟩
  · have hnat := congrArg (fun φ => φ s) (l.naturality (homOfLE hW₀U).op)
    simp only [CommRingCat.comp_apply, Quiver.Hom.unop_op] at hnat
    have h1' : (pullback f (blowup I).hom : Scheme.{u}).presheaf.map (homOfLE hW₀U).op s = 0 := h1
    rw [h1', map_zero] at hnat
    exact hnat.symm

/-- The pulled-back exceptional ideal `(π⁻¹I)·O_P` on `P = X ×_S Bl_I S` is locally principal. -/
theorem strictTransform.exceptionalIdeal_comap_locallyPrincipal
    (x : (pullback f (blowup I).hom : Scheme.{u})) :
    ∃ U : (pullback f (blowup I).hom : Scheme.{u}).affineOpens, x ∈ U.1 ∧
      ∃ a : Γ((pullback f (blowup I).hom : Scheme.{u}), U.1),
        ((blowup.exceptionalIdeal I).comap (pullback.snd f (blowup I).hom)).ideal U =
          Ideal.span {a} := by
  obtain ⟨V, hxV, a, -, hV⟩ := (blowup_isBlowup I).1 (pullback.snd f (blowup I).hom x)
  obtain ⟨_, ⟨U, hU, rfl⟩, hxU, hUV⟩ :=
    (pullback f (blowup I).hom : Scheme.{u}).isBasis_affineOpens.exists_subset_of_mem_open
      (show x ∈ (pullback.snd f (blowup I).hom) ⁻¹ᵁ V.1 from hxV)
      ((pullback.snd f (blowup I).hom) ⁻¹ᵁ V.1).isOpen
  refine ⟨⟨U, hU⟩, hxU, (pullback.snd f (blowup I).hom).appLE V.1 U hUV a, ?_⟩
  rw [IdealSheafData.comap_ideal_eq_map_appLE _ _ V ⟨U, hU⟩ hUV, blowup.exceptionalIdeal, hV,
    Ideal.map_span, Set.image_singleton]

/-- The centre pulled back to the strict transform is an effective Cartier divisor. -/
theorem strictTransform_isInvertibleIdeal :
    MiyaokaMori.Statement.IsInvertibleIdeal ((I.comap f).comap
      ((strictTransformIdeal f I).subschemeι ≫ pullback.fst f (blowup I).hom)) := by
  have hqc : QuasiCompact (strictTransform.exceptionalCompl f I).ι :=
    IdealSheafData.quasiCompact_ι_compl_support_of_locallyPrincipal _
      (strictTransform.exceptionalIdeal_comap_locallyPrincipal f I)
  have hJ : (I.comap f).comap ((strictTransformIdeal f I).subschemeι ≫ pullback.fst f (blowup I).hom)
      = ((blowup.exceptionalIdeal I).comap (pullback.snd f (blowup I).hom)).comap
          (strictTransformIdeal f I).subschemeι := by
    simp only [blowup.exceptionalIdeal, ← IdealSheafData.comap_comp, Category.assoc,
      pullback.condition]
  rw [hJ]
  intro t
  obtain ⟨U, hxU, a, ha⟩ :=
    strictTransform.exceptionalIdeal_comap_locallyPrincipal f I ((strictTransformIdeal f I).subschemeι t)
  have hUT : AlgebraicGeometry.IsAffineOpen ((strictTransformIdeal f I).subschemeι ⁻¹ᵁ U.1) :=
    U.2.preimage _
  -- the strict-transform ideal on `U` is the `a`-power torsion (Stacks 07ZP(2))
  have hK : (strictTransformIdeal f I).ideal U = {x | ∃ n : ℕ, ∀ i : Fin 1, (fun _ => a) i ^ n * x = 0} := by
    refine IdealSheafData.supportedOn_ideal (strictTransform.exceptionalLocus f I) U (fun _ : Fin 1 => a) ?_
    ext x
    simp only [Set.mem_inter_iff, Set.mem_sdiff, Set.mem_iUnion, not_exists, SetLike.mem_coe]
    constructor
    · rintro ⟨hE, hU⟩
      refine ⟨hU, fun _ hb => ?_⟩
      rw [IdealSheafData.mem_support_iff_of_mem hU, ha, AlgebraicGeometry.Scheme.zeroLocus_span,
        AlgebraicGeometry.Scheme.zeroLocus_singleton] at hE
      exact hE hb
    · rintro ⟨hU, hb⟩
      refine ⟨?_, hU⟩
      rw [IdealSheafData.mem_support_iff_of_mem hU, ha, AlgebraicGeometry.Scheme.zeroLocus_span,
        AlgebraicGeometry.Scheme.zeroLocus_singleton]
      exact hb 0
  refine ⟨⟨_, hUT⟩, hxU, (strictTransformIdeal f I).subschemeι.app U.1 a, ?_, ?_⟩
  · intro r hr
    obtain ⟨r, rfl⟩ := (strictTransformIdeal f I).subschemeι_app_surjective U r
    rw [← map_mul] at hr
    have hmem : a * r ∈ ((strictTransformIdeal f I).ideal U : Set _) := by
      show a * r ∈ (strictTransformIdeal f I).ideal U
      rw [← IdealSheafData.ker_subschemeι_app]
      exact hr
    rw [hK] at hmem
    obtain ⟨n, hn⟩ := hmem
    have hr' : r ∈ (strictTransformIdeal f I).ideal U := by
      show r ∈ ((strictTransformIdeal f I).ideal U : Set _)
      rw [hK]
      refine ⟨n + 1, fun i => ?_⟩
      have := hn i
      simp only at this ⊢
      rw [pow_succ, mul_assoc]
      exact this
    rw [← IdealSheafData.ker_subschemeι_app] at hr'
    exact hr'
  · rw [IdealSheafData.comap_ideal_eq_map_appLE _ _ U ⟨_, hUT⟩ le_rfl, ha, Ideal.map_span,
      Set.image_singleton, Hom.appLE_eq_app]

/-- The strict transform `T ⊆ X ×_S Bl_I S`, with `T → X`, is a blowup of `X` along `f⁻¹I`
in the sense of the universal property. -/
theorem strictTransform_isBlowup :
    MiyaokaMori.Statement.IsBlowup (I.comap f)
      ((strictTransformIdeal f I).subschemeι ≫ pullback.fst f (blowup I).hom) := by
  refine ⟨strictTransform_isInvertibleIdeal f I, fun Y g hg => ?_⟩
  have hgf : MiyaokaMori.Statement.IsInvertibleIdeal (I.comap (g ≫ f)) := by
    rwa [IdealSheafData.comap_comp]
  obtain ⟨h, hh, huniq⟩ := (blowup_isBlowup I).2 Y (g ≫ f) hgf
  let l : Y ⟶ pullback f (blowup I).hom := pullback.lift g h hh.symm
  have hl : MiyaokaMori.Statement.IsInvertibleIdeal
      ((I.comap f).comap (l ≫ pullback.fst f (blowup I).hom)) := by
    show MiyaokaMori.Statement.IsInvertibleIdeal
      ((I.comap f).comap (pullback.lift g h hh.symm ≫ pullback.fst f (blowup I).hom))
    rw [pullback.lift_fst]
    exact hg
  have hK : (strictTransformIdeal f I).subschemeι.ker ≤ l.ker := by
    rw [IdealSheafData.ker_subschemeι]
    exact strictTransformIdeal_le_ker f I l hl
  refine ⟨IsClosedImmersion.lift (strictTransformIdeal f I).subschemeι l hK, ?_, ?_⟩
  · dsimp only
    rw [IsClosedImmersion.lift_fac_assoc]
    exact pullback.lift_fst g h hh.symm
  · intro u hu
    have h2 : u ≫ (strictTransformIdeal f I).subschemeι ≫ pullback.snd f (blowup I).hom = h := by
      apply huniq
      rw [Category.assoc, Category.assoc, ← pullback.condition, ← hu]
      simp only [Category.assoc]
    have h3 : u ≫ (strictTransformIdeal f I).subschemeι = l := by
      apply pullback.hom_ext
      · show (u ≫ (strictTransformIdeal f I).subschemeι) ≫ pullback.fst f (blowup I).hom =
          pullback.lift g h hh.symm ≫ pullback.fst f (blowup I).hom
        rw [pullback.lift_fst, Category.assoc]
        exact hu
      · show (u ≫ (strictTransformIdeal f I).subschemeι) ≫ pullback.snd f (blowup I).hom =
          pullback.lift g h hh.symm ≫ pullback.snd f (blowup I).hom
        rw [pullback.lift_snd, Category.assoc]
        exact h2
    rw [← cancel_mono (strictTransformIdeal f I).subschemeι, h3, IsClosedImmersion.lift_fac]

end AlgebraicGeometry.Scheme

/-- **Stacks 080E (1).** The strict transform of `X` in `X ×_S Bl_I S` is the blowup of `X` along
`f⁻¹I`: there is a closed immersion `i : Bl_{f⁻¹I} X ⟶ X ×_S Bl_I S` with kernel the strict transform
ideal, compatible with the projections to `X`. -/
theorem AlgebraicGeometry.Scheme.strictTransform_eq_blowup {X S : AlgebraicGeometry.Scheme.{u}}
    (f : X ⟶ S) (I : S.IdealSheafData) :
    ∃ i : (AlgebraicGeometry.Scheme.blowup (I.comap f)).left ⟶
        CategoryTheory.Limits.pullback f (AlgebraicGeometry.Scheme.blowup I).hom,
      AlgebraicGeometry.IsClosedImmersion i ∧
      AlgebraicGeometry.Scheme.Hom.ker i = AlgebraicGeometry.Scheme.strictTransformIdeal f I ∧
      i ≫ CategoryTheory.Limits.pullback.fst _ _ = (AlgebraicGeometry.Scheme.blowup (I.comap f)).hom := by
  obtain ⟨e, he⟩ := MiyaokaMori.Statement.IsBlowup.exists_iso
    (AlgebraicGeometry.Scheme.blowup_isBlowup (I.comap f))
    (AlgebraicGeometry.Scheme.strictTransform_isBlowup f I)
  refine ⟨e.hom ≫ (AlgebraicGeometry.Scheme.strictTransformIdeal f I).subschemeι, inferInstance, ?_, ?_⟩
  · rw [AlgebraicGeometry.Scheme.Hom.ker_comp_of_isIso,
      AlgebraicGeometry.Scheme.IdealSheafData.ker_subschemeι]
  · rw [CategoryTheory.Category.assoc]
    exact he

end
