import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffectiveCartierDivisorScheme
import MiyaokaMori.AlgebraicGeometry.Blowup.BlowupExceptionalInvertible

/-! # Stacks 0809: pulling back an effective Cartier divisor along a blowup

If `b : Bl_I X → X` is the blowup along a quasi-coherent ideal sheaf `I`, then for every effective
Cartier divisor `D` on `X` the inverse image `b⁻¹D` is again an effective Cartier divisor; that is, the
pullback of effective Cartier divisors along a blowup is defined.

Source: Stacks 0809 (divisors-lemma-blow-up-pullback-effective-Cartier).

Proof. `EffectiveCartierDivisor Y = Y.EffCartier`, whose second field is `IsInvertibleIdeal`
("locally generated by a nonzerodivisor"), so the statement is `IsInvertibleIdeal (I_D.comap b)`. The
proof is the same chart bookkeeping as `blowup_exceptional_isInvertibleIdeal` (Stacks 02OS (2)), with
the exceptional ideal replaced by `I_D`: pick a local equation `I_D(U) = (a)`, `a ∈ A := Γ(X, U)` a
nonzerodivisor (`EffCartier.exists_localEquation`); cover `b⁻¹U` by the charts `V_c ≅ Spec A[I(U)/c]`
of Stacks 0804 (`blowup_preimage_affine_cover`); on `V_c`, `(I_D.comap b)(V_c) = I_D(U)·Γ(V_c)`
(`comap_ideal_eq_map_appLE`) is, under the chart isomorphism (`Scheme.Hom.appLE_eq_of_iso_spec`),
`(a)·A[I/c] = (a)`, and `a` stays a nonzerodivisor in `A[I/c] ⊆ A_c` because it is one in `A_c`
(`IsLocalization.nonZeroDivisors_le_comap`; this is the algebraic step of the Stacks proof).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- The algebraic step of Stacks 0809: a nonzerodivisor `x` of `R` stays a nonzerodivisor in the affine
blowup algebra `R[I/a] ⊆ R_a`. Proof: `R[I/a]` is a subring of the localization `R_a`, in which the image
of `x` is a nonzerodivisor (`IsLocalization.nonZeroDivisors_le_comap`): if `x·(y/aⁿ) = 0` then
`aᵐ x y = 0` in `R` for some `m`, so `aᵐ y = 0` and `y/aⁿ = 0`. -/
theorem MiyaokaMori.RingTheory.IdealFractionChart.algebraMap_mem_nonZeroDivisors {R : Type u} [CommRing R]
    (I : Ideal R) (a x : R) (hx : x ∈ nonZeroDivisors R) :
    algebraMap R (MiyaokaMori.RingTheory.IdealFractionChart.chart I a) x ∈
      nonZeroDivisors (MiyaokaMori.RingTheory.IdealFractionChart.chart I a) := by
  rw [mem_nonZeroDivisors_iff_left]
  intro y hy
  apply Subtype.ext
  have h' : algebraMap R (Localization.Away a) x * (y : Localization.Away a) = 0 :=
    congrArg Subtype.val hy
  have hx' : algebraMap R (Localization.Away a) x ∈ nonZeroDivisors (Localization.Away a) :=
    IsLocalization.nonZeroDivisors_le_comap (Submonoid.powers a) (Localization.Away a) hx
  exact (mem_nonZeroDivisors_iff_left.mp hx') _ h'

/-- **Stacks 0809 (effective Cartier divisors).** If `b : Bl_I X → X` is the blowup along a quasi-coherent
ideal sheaf `I`, then for every effective Cartier divisor `D` on `X` the inverse image ideal
`I_D.comap b` is the ideal sheaf of an effective Cartier divisor `b⁻¹D` on `Bl_I X`, i.e. the pullback of
`D` along `b` is defined (Stacks 01WV). The statement of Stacks 0809 about pulling back meromorphic
functions is not formalized. -/
theorem AlgebraicGeometry.EffectiveCartierDivisor.exists_comap_blowup {X : AlgebraicGeometry.Scheme.{u}}
    (I : X.IdealSheafData) (D : AlgebraicGeometry.EffectiveCartierDivisor X) :
    ∃ D' : AlgebraicGeometry.EffectiveCartierDivisor (AlgebraicGeometry.Scheme.blowup I).left,
      D'.idealSheaf = D.idealSheaf.comap (AlgebraicGeometry.Scheme.blowup I).hom := by
  refine ⟨⟨D.idealSheaf.comap (AlgebraicGeometry.Scheme.blowup I).hom, ?_⟩, rfl⟩
  intro x'
  obtain ⟨U, hxU, a, ha, hI⟩ :=
    AlgebraicGeometry.Scheme.EffCartier.exists_localEquation D ((AlgebraicGeometry.Scheme.blowup I).hom x')
  obtain ⟨V, hV, hE, hcov⟩ := AlgebraicGeometry.Scheme.blowup_preimage_affine_cover I U
  have hx'cov : x' ∈ ⨆ c, V c := by
    rw [hcov]
    exact hxU
  obtain ⟨c, hxc⟩ := Opens.mem_iSup.mp hx'cov
  obtain ⟨e, he⟩ := hE c
  have hWaff : IsAffineOpen (V c) := IsAffine.of_isIso e.hom
  refine ⟨⟨V c, hWaff⟩, hxc, ?_⟩
  have hideal := AlgebraicGeometry.Scheme.IdealSheafData.comap_ideal_eq_map_appLE D.idealSheaf
    (AlgebraicGeometry.Scheme.blowup I).hom U ⟨V c, hWaff⟩ (hV c)
  rw [AlgebraicGeometry.Scheme.Hom.appLE_eq_of_iso_spec _ U (V c) (hV c) _ _ e he] at hideal
  let ψ : CommRingCat.of (Ideal.affineBlowup (I.ideal U) (c : Γ(X, U))) ⟶
      Γ((AlgebraicGeometry.Scheme.blowup I).left, V c) :=
    (AlgebraicGeometry.Scheme.ΓSpecIso _).inv ≫ e.hom.appTop ≫ (V c).topIso.hom
  have hbij : Function.Bijective ψ.hom := ConcreteCategory.bijective_of_isIso
    ((AlgebraicGeometry.Scheme.ΓSpecIso _).symm ≪≫ AlgebraicGeometry.Scheme.Γ.mapIso e.op ≪≫
      (V c).topIso).hom
  have hspan : (D.idealSheaf.ideal U).map
      (algebraMap Γ(X, U) (Ideal.affineBlowup (I.ideal U) (c : Γ(X, U)))) =
      Ideal.span {algebraMap Γ(X, U) (Ideal.affineBlowup (I.ideal U) (c : Γ(X, U))) a} := by
    rw [hI, Ideal.map_span, Set.image_singleton]
  have hnzd : ∀ r, algebraMap Γ(X, U) (Ideal.affineBlowup (I.ideal U) (c : Γ(X, U))) a * r = 0 →
      r = 0 :=
    mem_nonZeroDivisors_iff_left.mp
      (MiyaokaMori.RingTheory.IdealFractionChart.algebraMap_mem_nonZeroDivisors (I.ideal U) (c : Γ(X, U)) a ha)
  obtain ⟨h1, h2⟩ := Ideal.map_comp_eq_span_singleton_of_bijective (D.idealSheaf.ideal U)
    (algebraMap Γ(X, U) (Ideal.affineBlowup (I.ideal U) (c : Γ(X, U)))) ψ.hom hbij a hspan hnzd
  exact ⟨ψ.hom (algebraMap Γ(X, U) (Ideal.affineBlowup (I.ideal U) (c : Γ(X, U))) a), h1,
    hideal.trans h2⟩

end
