import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks01og
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks02ns
import MiyaokaMori.AlgebraicGeometry.Blowup.BlowupExceptionalInvertible
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0agq
import MiyaokaMori.AlgebraicGeometry.Modules.IdealSheaf.Stacks0ahhBlowupImproveDivide
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0ahhBlowupImproveInvertible
import MiyaokaMori.AlgebraicGeometry.Proj.ProjectiveSpace.ProjectiveLineIrreducible

/-! # The largest exponent of an invertible ideal sheaf dividing a given ideal sheaf

Variable-level core of the first paragraph of Stacks 0AGT (`exists_blowup_improve_exponent`):
on a locally Noetherian scheme `X` with an invertible ideal sheaf `E` (locally generated by a
nonzerodivisor, `MiyaokaMori.Statement.IsInvertibleIdeal`) whose support is nonempty, and an ideal
sheaf `IX` with `E^n ≤ IX ≤ E`, there is a **largest** `d` with `IX ≤ E^d`; it satisfies
`1 ≤ d ≤ n`, and `IX = E^d · I'` for the quotient ideal sheaf `I' = (IX : E^d)`
(`exists_maximal_exponent_of_invertible`).

The concrete input for 0AGT is `blowup_regularLocalRing_dimTwo_exceptional_support_nonempty`: the
exceptional divisor of `Bl_𝔪 Spec A` (`A` a two-dimensional regular local ring) has a point, because
its closed fibre is `P¹_κ` (Stacks 0AGQ) and `P¹_κ` is irreducible, hence
nonempty (`AlgebraicGeometry.Proj.ProjectiveLineIrreducible.projectiveLine_irreducible`).

Source: Stacks 0AGT, proof, first paragraph ("Since `I ⊆ 𝔪` we see that every element of `I`
vanishes on `E`. Thus we see that `d ≥ 1`. On the other hand, since `𝔪ⁿ ⊆ I` we see that
`d ≤ n`."); the division `IX = E^d · I'` is `exists_eq_mul_of_le_of_isInvertibleIdeal`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

namespace AlgebraicGeometry.Scheme.IdealSheafData

/-- `ofIdealTop` is monotone (`Ideal.map` is monotone on every affine open). -/
theorem ofIdealTop_mono {X : AlgebraicGeometry.Scheme.{u}} {K K' : Ideal Γ(X, ⊤)} (h : K ≤ K') :
    ofIdealTop K ≤ ofIdealTop K' := by
  intro U
  simp only [ofIdealTop_ideal]
  exact Ideal.map_mono h

/-- `(ofIdealTop K)^n = ofIdealTop (K^n)` (`Ideal.map_pow` on every affine open). -/
theorem ofIdealTop_pow {X : AlgebraicGeometry.Scheme.{u}} (K : Ideal Γ(X, ⊤)) (n : ℕ) :
    ofIdealTop K ^ n = ofIdealTop (K ^ n) := by
  ext U : 2
  simp only [ideal_pow, Pi.pow_apply, ofIdealTop_ideal, Ideal.map_pow]

/-- On an affine open `U` containing a point of the support of `E`, `E(U)` is a proper ideal:
otherwise `1 ∈ E(U)` and `y ∉ D(1) = U` (`mem_support_iff_of_mem`, `basicOpen_of_isUnit`). -/
theorem ideal_ne_top_of_mem_support {X : AlgebraicGeometry.Scheme.{u}} (E : X.IdealSheafData)
    {y : X} (hy : y ∈ E.support) (U : X.affineOpens) (hyU : y ∈ (U : X.Opens)) :
    E.ideal U ≠ ⊤ := by
  intro htop
  rw [mem_support_iff_of_mem hyU, Scheme.mem_zeroLocus_iff] at hy
  apply hy 1 (htop ▸ Submodule.mem_top)
  rw [X.basicOpen_of_isUnit isUnit_one]
  exact hyU

/-- **Boundedness of the exponent** (Stacks 0AGT: "since `𝔪ⁿ ⊆ I` we see that `d ≤ n`").
`E` invertible with a point `y` in its support and `E^n ≤ IX` ⇒ `IX ⊄ E^(n+1)`.

Proof. Take an affine `U ∋ y` with `E(U) = (a)`, `a` a nonzerodivisor; `E(U) ≠ ⊤` since `y` is in
the support. If `IX ≤ E^(n+1)`, then `a^n ∈ (E^n)(U) ⊆ IX(U) ⊆ (a^(n+1))`, so `a^n = r a^(n+1)`,
`a^n (1 - r a) = 0`, hence `1 - r a = 0` (`a^n` is a nonzerodivisor), so `a` is a unit and
`E(U) = ⊤`, a contradiction. -/
theorem not_le_pow_succ_of_pow_le {X : AlgebraicGeometry.Scheme.{u}} {E IX : X.IdealSheafData}
    (hE : MiyaokaMori.Statement.IsInvertibleIdeal E) {y : X} (hy : y ∈ E.support) (n : ℕ)
    (hn : E ^ n ≤ IX) : ¬ IX ≤ E ^ (n + 1) := by
  intro hle
  obtain ⟨U, hyU, a, ha, hEU⟩ := hE y
  have hne := ideal_ne_top_of_mem_support E hy U hyU
  have h1 : a ^ n ∈ IX.ideal U := by
    apply hn U
    rw [ideal_pow, Pi.pow_apply, hEU, Ideal.span_singleton_pow]
    exact Ideal.mem_span_singleton_self _
  have h2 := hle U h1
  rw [ideal_pow, Pi.pow_apply, hEU, Ideal.span_singleton_pow, Ideal.mem_span_singleton'] at h2
  obtain ⟨r, hr⟩ := h2
  have h0 : a ^ n * (1 - r * a) = 0 := by
    calc a ^ n * (1 - r * a) = a ^ n - r * a ^ (n + 1) := by ring
      _ = 0 := by rw [hr, sub_self]
  have := pow_mul_eq_zero_imp ha n _ h0
  apply hne
  rw [hEU, Ideal.span_singleton_eq_top]
  exact isUnit_iff_exists_inv.mpr ⟨r, by linear_combination -this⟩

/-- **Largest exponent and division** (Stacks 0AGT, first paragraph, at the variable level).
`X` locally Noetherian, `E` invertible with nonempty support, `E^n ≤ IX ≤ E`. Then there are
`d ≥ 1` and an ideal sheaf `I'` with `IX = E^d · I'` and `IX ⊄ E^(d+1)`.

Proof. The set `{m | IX ⊄ E^(m+1)}` is nonempty (`m = n`, `not_le_pow_succ_of_pow_le`); let `d` be
its least element (`Nat.find`). `d ≠ 0` because `IX ≤ E = E^(0+1)`. For `m = d - 1 < d` we have
`IX ≤ E^(m+1) = E^d`; since `E^d` is invertible (`isInvertibleIdeal_pow`), division
(`exists_eq_mul_of_le_of_isInvertibleIdeal`) gives `I'`
with `IX = E^d · I'`. -/
theorem exists_maximal_exponent_of_invertible {X : AlgebraicGeometry.Scheme.{u}}
    [AlgebraicGeometry.IsLocallyNoetherian X] {E IX : X.IdealSheafData}
    (hE : MiyaokaMori.Statement.IsInvertibleIdeal E) {y : X} (hy : y ∈ E.support)
    (h1 : IX ≤ E) (n : ℕ) (hn : E ^ n ≤ IX) :
    ∃ (d : ℕ) (I' : X.IdealSheafData), 0 < d ∧ IX = E ^ d * I' ∧ ¬ IX ≤ E ^ (d + 1) := by
  classical
  have hP : ∃ m : ℕ, ¬ IX ≤ E ^ (m + 1) := ⟨n, not_le_pow_succ_of_pow_le hE hy n hn⟩
  let d := Nat.find hP
  have hd : ¬ IX ≤ E ^ (d + 1) := Nat.find_spec hP
  have hdpos : 0 < d := by
    rcases Nat.eq_zero_or_pos d with h | h
    · exfalso
      apply hd
      rw [h, zero_add, pow_one]
      exact h1
    · exact h
  have hle : IX ≤ E ^ d := by
    have := Nat.find_min hP (Nat.sub_lt hdpos Nat.one_pos)
    rw [not_not, Nat.sub_add_cancel hdpos] at this
    exact this
  obtain ⟨I', hI'⟩ := exists_eq_mul_of_le_of_isInvertibleIdeal (isInvertibleIdeal_pow hE d) hle
  exact ⟨d, I', hdpos, hI', hd⟩

end AlgebraicGeometry.Scheme.IdealSheafData

/-- **The exceptional divisor of `Bl_𝔪 Spec A` is nonempty** (`A` a two-dimensional regular local
ring): some point `y` of the blowup lies in the support of the exceptional ideal `E = 𝔪·O_X`.

Proof. By Stacks 0AGQ (`blowup_regularLocalRing_dimTwo_exceptional_over_residueField`)
the closed fibre `X ×_{Spec A} Spec κ` is isomorphic to `P¹_κ`, which is
irreducible (`AlgebraicGeometry.Proj.ProjectiveLineIrreducible.projectiveLine_irreducible`), hence nonempty. Take
a point `q` of the fibre and `y := pr₁ q`. Then `b y = g (pr₂ q)` where `g : Spec κ → Spec A`
(`pullback.condition`), and `g` maps the unique point of `Spec κ` to the closed point: its prime
is `(algebraMap A κ)⁻¹(0) = 𝔪` (`IsLocalRing.residue_eq_zero_iff`). Finally
`supp E = b⁻¹(supp J)` (`support_comap`) and `supp J = V(𝔪)` in `Spec A`
(`coe_support_ofIdealTop`, `Spec_zeroLocus`), which contains the closed point. -/
theorem AlgebraicGeometry.blowup_regularLocalRing_dimTwo_exceptional_support_nonempty
    (A : Type u) [CommRing A] [IsRegularLocalRing A] (hdim : ringKrullDim A = 2) :
    let e := (AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of A)).inv.hom
    let J : (AlgebraicGeometry.Spec (CommRingCat.of A)).IdealSheafData :=
      AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop ((IsLocalRing.maximalIdeal A).map e)
    ∃ y : (AlgebraicGeometry.Scheme.blowup J).left,
      y ∈ (AlgebraicGeometry.Scheme.blowup.exceptionalIdeal J).support := by
  intro e J
  obtain ⟨ε, -⟩ := AlgebraicGeometry.blowup_regularLocalRing_dimTwo_exceptional_over_residueField A hdim
  have : IrreducibleSpace (ProjectiveLine (IsLocalRing.ResidueField A)) :=
    AlgebraicGeometry.Proj.ProjectiveLineIrreducible.projectiveLine_irreducible _
  obtain ⟨p⟩ : Nonempty (ProjectiveLine (IsLocalRing.ResidueField A)) := inferInstance
  let b := (AlgebraicGeometry.Scheme.blowup J).hom
  let g := AlgebraicGeometry.Spec.map (CommRingCat.ofHom (algebraMap A (IsLocalRing.ResidueField A)))
  let q := ε.inv p
  refine ⟨pullback.fst b g q, ?_⟩
  have hcond := congrArg (fun f => f q) (pullback.condition (f := b) (g := g))
  simp only [Scheme.Hom.comp_apply] at hcond
  show pullback.fst b g q ∈ (J.comap b).support
  rw [AlgebraicGeometry.Scheme.IdealSheafData.support_comap]
  show b (pullback.fst b g q) ∈ (J.support : Set _)
  rw [hcond, AlgebraicGeometry.Scheme.IdealSheafData.coe_support_ofIdealTop,
    AlgebraicGeometry.Spec_zeroLocus]
  refine (PrimeSpectrum.mem_zeroLocus _ _).mpr ?_
  intro a ha
  rw [Set.mem_preimage, SetLike.mem_coe] at ha
  have hbot : (pullback.snd b g q : AlgebraicGeometry.Spec
      (CommRingCat.of (IsLocalRing.ResidueField A))).asIdeal = ⊥ := by
    rcases Ideal.eq_bot_or_top (pullback.snd b g q).asIdeal with h | h
    · exact h
    · exact absurd h (pullback.snd b g q).isPrime.ne_top
  show a ∈ Ideal.comap (algebraMap A (IsLocalRing.ResidueField A))
    (pullback.snd b g q : AlgebraicGeometry.Spec (CommRingCat.of (IsLocalRing.ResidueField A))).asIdeal
  rw [hbot, Ideal.mem_comap, Ideal.mem_bot]
  obtain ⟨a', ha', haa⟩ := Ideal.mem_map_iff_of_surjective _
    (ConcreteCategory.bijective_of_isIso (AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of A)).inv).2
    |>.mp ha
  have hinj := (ConcreteCategory.bijective_of_isIso
    (AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of A)).inv).1 haa
  rw [← hinj]
  show algebraMap A (IsLocalRing.ResidueField A) a' = 0
  rw [IsLocalRing.ResidueField.algebraMap_eq, IsLocalRing.residue_eq_zero_iff]
  exact ha'

end
