import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.Stalk.ModuleSheafStalk
import MiyaokaMori.AlgebraicGeometry.Modules.Stalk.ModulesSupport
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffectiveCartierDivisorScheme
import MiyaokaMori.AlgebraicGeometry.Cohomology.Basic.CohomologyLongExactSequence
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffectiveDivisor
import MiyaokaMori.RingTheory.Length.LengthSumInertia
import MiyaokaMori.AlgebraicGeometry.Chow.Cycles.Stacks02qt
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks01og
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0806
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0agq
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0agtLeaves

/-! # Stacks 0AGT: blowing up improves an ideal of a regular local ring of dimension two

Stacks 0AGT: let `(A, 𝔪)` be a two-dimensional regular local ring, `b : X = Bl_𝔪 Spec A → Spec A`,
`𝔪ⁿ ⊆ I ⊆ 𝔪`, and let `d` be the largest integer with `I·O_X ⊆ O_X(−dE)`. Then `d > 0`, the
cosupport of `I' := I·O_X(dE)` consists of finitely many closed points, and the sum over these
points of `length(O_{X,x}/I'_x)` is strictly smaller than `length_A(A/I)`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/- Stacks 0AGT. Setting as in Stacks 0AGQ: `A` is a two-dimensional regular local ring,
   `b : X = Bl_𝔪 Spec A → Spec A`, `E` is the ideal sheaf of the exceptional divisor
   (`Scheme.blowup.exceptionalIdeal`, `= 𝔪·O_X`), and `I·O_X = (Ĩ).comap b`. The ideal sheaf of
   `O_X(−dE)` is `E^d` on every affine open; "`d` is largest with `I·O_X ⊆ O_X(−dE)`" is written as
   `I·O_X ⊄ E^{d+1}`; `I' := I·O_X(dE)` is written as `I·O_X = E^d · I'` (`E` is locally generated by
   a nonzerodivisor, so `I'` is unique).
   Conclusions: `d > 0`; the support of `O_X/I'` is a finite set `T` of closed points;
   `Σ_{x∈T} length_{O_{X,x}}(O_{X,x}/I'_x) < length_A(A/I)`. The stalk ideal `I'_x` is the image
   under the germ map of the ideal on any affine open `W` containing `x` (it does not depend on `W`,
   so the statement quantifies over all choices).

   The proof is assembled from the three lemmas `exists_blowup_improve_exponent`,
   `blowup_improve_support_finite` and `blowup_improve_length_lt` of `Stacks0agtLeaves.lean`, which
   correspond to the three paragraphs of the proof in Stacks 0AGT. -/

theorem AlgebraicGeometry.blowup_regularLocalRing_dimTwo_improve
    (A : Type u) [CommRing A] [IsRegularLocalRing A] (hdim : ringKrullDim A = 2)
    (I : Ideal A) (n : ℕ) (hmI : IsLocalRing.maximalIdeal A ^ n ≤ I)
    (hIm : I ≤ IsLocalRing.maximalIdeal A) :
    let e := (AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of A)).inv.hom
    let J : (AlgebraicGeometry.Spec (CommRingCat.of A)).IdealSheafData :=
      AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop ((IsLocalRing.maximalIdeal A).map e)
    let X := (AlgebraicGeometry.Scheme.blowup J).left
    let E : X.IdealSheafData := AlgebraicGeometry.Scheme.blowup.exceptionalIdeal J
    let IX : X.IdealSheafData :=
      (AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop (I.map e)).comap
        (AlgebraicGeometry.Scheme.blowup J).hom
    ∃ (d : ℕ) (I' : X.IdealSheafData),
      0 < d ∧
      (∀ U : X.affineOpens, IX.ideal U = E.ideal U ^ d * I'.ideal U) ∧
      ¬ (∀ U : X.affineOpens, IX.ideal U ≤ E.ideal U ^ (d + 1)) ∧
      ∃ T : Finset X, (I'.support : Set X) = ↑T ∧ (∀ x ∈ T, IsClosed ({x} : Set X)) ∧
        ∀ (W : T → X.affineOpens) (hW : ∀ x : T, x.1 ∈ ((W x : X.affineOpens) : X.Opens)),
          ∑ x : T, Module.length (X.presheaf.stalk x.1)
              (X.presheaf.stalk x.1 ⧸
                (I'.ideal (W x)).map (X.presheaf.germ ((W x : X.affineOpens) : X.Opens) x.1 (hW x)).hom)
            < Module.length A (A ⧸ I) := by
  intro e J X E IX
  obtain ⟨d, I', hd, hprod, hmax⟩ :=
    AlgebraicGeometry.exists_blowup_improve_exponent A hdim I n hmI hIm
  obtain ⟨T, hT, hTclosed⟩ :=
    AlgebraicGeometry.blowup_improve_support_finite A hdim I n hmI hIm d I' hd hprod hmax
  exact ⟨d, I', hd, hprod, hmax, T, hT, hTclosed,
    AlgebraicGeometry.blowup_improve_length_lt A hdim I n hmI hIm d I' hd hprod T hT hTclosed⟩

end
