import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffectiveCartierDivisorScheme
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks01og
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0806IsBlowup
import MiyaokaMori.AlgebraicGeometry.Blowup.BlowupInvertibleIdeal

/-! # Stacks 0807: blowing up an effective Cartier divisor is an isomorphism

The blowup of `X` along the ideal sheaf of an effective Cartier divisor `D` has an isomorphism as
its structure morphism ("immediate from the universal property", Stacks 0807). It is used in the
proof of Lemma 5.1 of the paper (§5).

Proof: `D.idealSheaf` is an invertible ideal (locally generated by a nonzerodivisor) by
`D.isInvertible`; by `blowup_isBlowup` (Stacks 0806) the morphism `(blowup D.idealSheaf).hom`
satisfies the predicate `IsBlowup`; by `IsBlowup.isIso_of_isInvertibleIdeal`, `𝟙 X` is also a blowup
of an invertible ideal (`isBlowup_id_iff`), and the unique isomorphism between two blowups is `b`
itself, so `IsIso b`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- **Stacks 0807.** The blowup `b : X' → X` along an effective Cartier divisor `D` is an isomorphism.
Proof: `D.idealSheaf` is invertible (`D.isInvertible`), `b` is a blowup of it (`blowup_isBlowup`,
i.e. Stacks 0806), and every blowup of an invertible ideal is an isomorphism
(`IsBlowup.isIso_of_isInvertibleIdeal`: `𝟙 X` is also such a blowup, and the universal property
gives uniqueness). -/
theorem AlgebraicGeometry.Scheme.blowup_isIso_of_effectiveCartier {X : AlgebraicGeometry.Scheme.{u}}
    (D : AlgebraicGeometry.EffectiveCartierDivisor X) :
    CategoryTheory.IsIso (AlgebraicGeometry.Scheme.blowup D.idealSheaf).hom :=
  (AlgebraicGeometry.Scheme.blowup_isBlowup D.idealSheaf).isIso_of_isInvertibleIdeal D.isInvertible


end
