import MiyaokaMori.Prelude
import MiyaokaMori.RingTheory.RegularLocalRing.Stacks0agrChartLocalRegular
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0agrExceptionalFibreStalk

/-! # Stacks 0AGR: regularity of the blowup of a regular local ring of dimension two

Stacks 0AGR (local form): for a two-dimensional regular local ring `(A, 𝔪, κ)` and the blowup
`X = Bl_𝔪 Spec A`, the local ring of `X` at every point of the exceptional fibre (the closed fibre
`π⁻¹(𝔪)`) is a regular local ring.

Sources: Stacks 0AGR; the proof of Hartshorne V.3.1; the paper uses it (smoothness of `Bl_p S`) in
the proof of Corollary 4.3 (§4). `AlgebraicGeometry.Scheme.blowupClosedPoint_isRegular`
reduces the local rings of `Bl_p S` on the exceptional fibre to the local rings treated here.

The proof assembles three inputs:
* `Scheme.blowup_spec_stalk_over_closedPoint` (geometric glue: the affine charts of Stacks 0804,
  and the stalk is a localization);
* `Ideal.affineBlowup_isRegularLocalRing_localization_atPrime_of_comap_eq_maximalIdeal`
  (the commutative-algebra core: the regular sequence of Stacks 00NQ, `A[𝔪/a]/(a) ≅ κ[T]`, and
  Stacks 00NU);
* the two-generator presentation of the affine blowup (`A[J/a] ≅ A[T]/(aT − b)`,
  `A[J/a]/(a) ≅ (A/J)[T]`).
The assembly only transports the regularity and the dimension of `A` to `Γ(Spec A, ⊤)` along
`ΓSpecIso` and computes the ideal of `ofIdealTop` on `⊤`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- **Stacks 0AGR, local form.** Let `(A, 𝔪, κ)` be a two-dimensional regular local ring, let `I` be
the ideal sheaf on `Spec A` given by `𝔪` transported to `Γ(Spec A)` along `ΓSpecIso.inv`, and let
`X = Bl_I Spec A`. For every point `y` of `X` lying over the closed point `𝔪` (i.e. `π(y) = 𝔪`),
the local ring `O_{X,y}` is a regular local ring.

Only the points of the exceptional fibre are treated: for the points not over `𝔪`, the blowup is an
isomorphism over `Spec A ∖ {𝔪}`, so the question reduces to the regularity of `A_𝔮` (`𝔮 ⊊ 𝔪`),
which is Stacks 0AFS (localizations of regular local rings are regular, via Serre's homological
characterization) and is not needed here. The hypothesis `(blowup I).hom y = IsLocalRing.closedPoint A`
is an equality of points of `Spec A` (`↑(Spec (CommRingCat.of A))` is `PrimeSpectrum A` by `rfl`), and
the ideal of `I` on `⊤` is the maximal ideal of `Γ(Spec A, ⊤)` (`hJ` in the proof), so `blowup I` is
`Bl_𝔪 Spec A` as in Stacks 0AGR.

**Proof** (the argument of Stacks 0AGR / 0AGQ):
1. **`𝔪 = (x, y)`**: `A` is regular of dimension `2`, so `𝔪` is generated by two elements `x, y`
   (`spanFinrank 𝔪 = ringKrullDim A = 2`, `Submodule.FG.exists_span_finset_card_eq_spanFinrank`);
   a regular system of parameters is a regular sequence (Stacks 00NQ,
   `IsRegularLocalRing.isWeaklyRegular_of_span_eq_maximalIdeal`). In particular `x` is a
   nonzerodivisor of `A` and `y` is a nonzerodivisor of `A/xA`.
2. **Affine charts**: `Spec A` is affine, and Stacks 0804 (`blowup_preimage_affine_cover`) covers
   `X = π⁻¹(Spec A)` by opens `V_a ≅ Spec A[I/a]` (`a ∈ 𝔪`, `Ideal.affineBlowup 𝔪 a ⊆ A_a`) such
   that `π|_{V_a}` is induced by `A → A[I/a]`. A point `y ∈ X` lies in some `V_a`, so
   `O_{X,y} ≅ (A[I/a])_𝔮` for the prime `𝔮 ⊂ A[I/a]` corresponding to `y`, and `π(y) = 𝔪` means
   `𝔮 ∩ A = 𝔪`. For any `a ∈ 𝔪`, `𝔮 ∩ A = 𝔪` forces `a ∉ 𝔪²` (otherwise
   `1 = a·c ∈ 𝔪·A[𝔪/a] ⊆ 𝔮`), so `a` extends to a minimal system of generators `(a, b)`
   (`Ideal.notMem_sq_of_affineBlowup_le_comap`); below we write `x = a`, `y = b`.
3. **`A[𝔪/x] ≅ A[T]/(xT − y)`**: the `A`-algebra map `A[T] → A[𝔪/x] ⊆ A_x`, `T ↦ y/x`, is
   surjective (`A[𝔪/x]` is generated by `{m/x : m ∈ 𝔪}`, and `m = αx + βy` gives
   `m/x = α + β·(y/x)`) and its kernel contains `(xT − y)`. Conversely `x` is a nonzerodivisor of
   `B := A[T]/(xT − y)`: if `x·G ∈ (xT − y)`, write `xG = (xT − y)H`; reducing modulo `x` gives
   `−ȳ·H̄ = 0` in `(A/x)[T]`, and `ȳ` is a nonzerodivisor of `A/x` (step 1), so `H̄ = 0`,
   `H = xH'`, and cancelling `x` gives `G = (xT − y)H' ∈ (xT − y)`. Hence
   `B → B_x = A_x[T]/(T − y/x) ≅ A_x` is injective with image `A[𝔪/x]`.
4. **`A[𝔪/x]/(x) ≅ κ[T]`**: by step 3,
   `A[𝔪/x]/(x) ≅ A[T]/(x, xT − y) = A[T]/(x, y) = (A/𝔪)[T] = κ[T]`
   (`Ideal.polynomialQuotientEquivQuotientPolynomial`).
5. **Points on the exceptional fibre**: `𝔮 ∩ A = 𝔪` gives `x ∈ 𝔮`. The local ring
   `R := (A[𝔪/x])_𝔮` is Noetherian local with `x ∈ 𝔪_R`; `x` is still a nonzerodivisor of `R`
   (it is a nonzerodivisor of `A[𝔪/x]` by `MiyaokaMori.RingTheory.IdealFractionChart.generator_mul_eq_zero`, and
   localization preserves nonzerodivisors); `R/xR ≅ (A[𝔪/x]/x)_𝔮̄ ≅ κ[T]_𝔮̄` (localization
   commutes with quotients), and `κ[T]` is a polynomial ring in one variable over a field, a
   Dedekind domain (PID), whose localizations at primes are regular local rings
   (`IsRegularRing.isRegularLocalRing_localization`, or `Polynomial.isRegularRing_of_isRegularRing`).
6. **Conclusion by Stacks 00NU**
   (`IsRegularLocalRing.of_quotient_span_singleton_of_mem_nonZeroDivisors`): `R` is Noetherian
   local, `x ∈ 𝔪_R` is a nonzerodivisor and `R/xR` is regular, so `R` is regular. Hence
   `O_{X,y} ≅ R` is regular (`IsRegularLocalRing.of_ringEquiv`).

Edge cases: `dim A = 2` excludes fields and DVRs; `IsLocalRing.closedPoint A : PrimeSpectrum A` is
definitionally a point of `Spec (CommRingCat.of A)`. -/
theorem AlgebraicGeometry.blowup_regularLocalRing_dimTwo_isRegularLocalRing_stalk
    (A : Type u) [CommRing A] [IsRegularLocalRing A] (hdim : ringKrullDim A = 2) :
    let I : (AlgebraicGeometry.Spec (CommRingCat.of A)).IdealSheafData :=
      AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop
        ((IsLocalRing.maximalIdeal A).map
          (AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of A)).inv.hom)
    ∀ y : ↑(AlgebraicGeometry.Scheme.blowup I).left,
      (AlgebraicGeometry.Scheme.blowup I).hom y = IsLocalRing.closedPoint A →
      IsRegularLocalRing ((AlgebraicGeometry.Scheme.blowup I).left.presheaf.stalk y) := by
  intro I y hy
  -- the chart of Stacks 0804 containing `y`, and `O_{X,y} ≅ A[𝔪/a]_𝔮`
  obtain ⟨a, 𝔮, hprime, hcomap, ⟨ε⟩⟩ :=
    AlgebraicGeometry.Scheme.blowup_spec_stalk_over_closedPoint A I y hy
  -- transport regularity and dimension of `A` to `Γ(Spec A, ⊤)` along `ΓSpecIso`
  let e : A ≃+* Γ(AlgebraicGeometry.Spec (CommRingCat.of A), ⊤) :=
    (AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of A)).symm.commRingCatIsoToRingEquiv
  haveI : IsRegularLocalRing Γ(AlgebraicGeometry.Spec (CommRingCat.of A), ⊤) :=
    IsRegularLocalRing.of_ringEquiv e
  have hdim' : ringKrullDim Γ(AlgebraicGeometry.Spec (CommRingCat.of A), ⊤) = 2 := by
    rw [← ringKrullDim_eq_of_ringEquiv e, hdim]
  have hmax : (IsLocalRing.maximalIdeal A).map
      (AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of A)).inv.hom =
        IsLocalRing.maximalIdeal Γ(AlgebraicGeometry.Spec (CommRingCat.of A), ⊤) :=
    IsLocalRing.map_ringEquiv_maximalIdeal e
  -- the ideal of `I = ofIdealTop (𝔪.map ΓSpecIso.inv)` on `⊤` is the maximal ideal of `Γ(Spec A, ⊤)`
  have hJ : I.ideal ⟨⊤, AlgebraicGeometry.isAffineOpen_top _⟩ =
      IsLocalRing.maximalIdeal Γ(AlgebraicGeometry.Spec (CommRingCat.of A), ⊤) := by
    show (AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop _).ideal ⟨⊤, _⟩ = _
    simpa using hmax
  haveI := hprime
  haveI := Ideal.affineBlowup_isRegularLocalRing_localization_atPrime_of_comap_eq_maximalIdeal hdim'
    _ hJ (a : Γ(AlgebraicGeometry.Spec (CommRingCat.of A), ⊤)) a.2 𝔮 (hcomap.trans hmax)
  exact IsRegularLocalRing.of_ringEquiv (R := Localization.AtPrime 𝔮) ε

end
