import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0agtLeavesExponentCore
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0agtLeavesSupportCore
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0agtLeavesSupportTopology
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0agtLeavesLengthCore
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0agtLeavesSectionsSurjective
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0ags

/-! # The three leaves of Stacks 0AGT

Stacks 0AGT (blowing up a two-dimensional regular local ring improves an `𝔪`-primary ideal) is split
into three independent statements, matching the three paragraphs of the proof in Stacks:
(1) the exponent `d` and the ideal sheaf `I'` with `I·O_X = E^d·I'` (with `d` maximal);
(2) the support of `I'` consists of finitely many closed points;
(3) the length strictly decreases. The top-level statement is assembled from these in `Stacks0agt`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry
open scoped AlgebraicGeometry.Scheme.IdealSheafData.QuotFamilies0agt

noncomputable section

/-- **Leaf (1): the exponent `d`** (first paragraph of the proof of Stacks 0AGT). There is a largest `d`
with `I·O_X ⊆ O_X(−dE)`, and `1 ≤ d ≤ n`; since `E` is locally cut out by a nonzerodivisor there is a
unique ideal sheaf `I'` with `I·O_X = E^d·I'`.

Proof:
1. `d ≥ 1`: `I ⊆ 𝔪`, so `I·O_X ⊆ 𝔪·O_X = O_X(−E)` (`Scheme.blowup.exceptionalIdeal` is by definition
   `J.comap b` for `J` the ideal sheaf of `𝔪`, and it is the ideal sheaf of an effective Cartier divisor by
   Stacks 0806).
2. `d ≤ n`: `𝔪ⁿ ⊆ I` gives `Eⁿ ⊆ I·O_X`. `E` is nonempty (Stacks 0AGQ: `E ≅ P¹_κ`, which is irreducible)
   and an effective Cartier divisor; a local equation `t` at a point of `E` satisfies `tⁿ ∈ I·O_{X,x}`,
   `tⁿ ∉ (tⁿ⁺¹)`, so `I·O_X ⊄ Eⁿ⁺¹`. Hence `d := Nat.find {m | IX ⊄ E^(m+1)}` satisfies `1 ≤ d ≤ n`
   (`exists_maximal_exponent_of_invertible`).
3. Existence of `I'`: on every affine open `U`, `E` is generated by a nonzerodivisor `t_U`; by step 2,
   `I·O_X(U) ⊆ (t_U^d)`, so every element is uniquely `t_U^d·s`, and these `s` form the ideal `I'(U)`
   (`exists_eq_mul_of_le_of_isInvertibleIdeal`, which needs `IsLocallyNoetherian X`: the blowup is
   projective, hence of finite type, over the Noetherian `Spec A`, Stacks 02NS). Powers of ideal sheaves
   are computed affine-locally (`ideal_pow`), and `comap_pow` / `ofIdealTop_pow` relate `Eⁿ = 𝔪ⁿ·O_X` to
   `IX`. -/
theorem AlgebraicGeometry.exists_blowup_improve_exponent
    (A : Type u) [CommRing A] [IsRegularLocalRing A] (hdim : ringKrullDim A = 2)
    (I : Ideal A) (n : ℕ) (hmI : IsLocalRing.maximalIdeal A ^ n ≤ I)
    (hIm : I ≤ IsLocalRing.maximalIdeal A) :
    let e := (AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of A)).inv.hom
    let J : (AlgebraicGeometry.Spec (CommRingCat.of A)).IdealSheafData :=
      AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop ((IsLocalRing.maximalIdeal A).map e)
    let X := (AlgebraicGeometry.Scheme.blowup J).left
    let E : X.IdealSheafData := AlgebraicGeometry.Scheme.blowup.exceptionalIdeal J
    let IX : X.IdealSheafData :=
      (AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop (I.map e)).comap
        (AlgebraicGeometry.Scheme.blowup J).hom
    ∃ (d : ℕ) (I' : X.IdealSheafData),
      0 < d ∧
      (∀ U : X.affineOpens, IX.ideal U = E.ideal U ^ d * I'.ideal U) ∧
      ¬ (∀ U : X.affineOpens, IX.ideal U ≤ E.ideal U ^ (d + 1)) := by
  intro e J X E IX
  -- `X` is locally Noetherian: the blowup morphism is projective (02NS), hence of finite type,
  -- over the Noetherian scheme `Spec A`.
  have : AlgebraicGeometry.IsNoetherian (AlgebraicGeometry.Spec (CommRingCat.of A)) := inferInstance
  have : AlgebraicGeometry.IsProjectiveMorphism (AlgebraicGeometry.Scheme.blowup J).hom :=
    AlgebraicGeometry.Scheme.blowup_isProjectiveMorphism J
  have : AlgebraicGeometry.IsProper (AlgebraicGeometry.Scheme.blowup J).hom :=
    AlgebraicGeometry.IsProjectiveMorphism.isProper _
  have : AlgebraicGeometry.IsLocallyNoetherian X :=
    AlgebraicGeometry.LocallyOfFiniteType.isLocallyNoetherian (AlgebraicGeometry.Scheme.blowup J).hom
  -- `E` is invertible (Stacks 02OS(2) / 0806) and nonempty (Stacks 0AGQ)
  have hE : MiyaokaMori.Statement.IsInvertibleIdeal E :=
    AlgebraicGeometry.Scheme.blowup_exceptional_isInvertibleIdeal J
  obtain ⟨y, hy⟩ := AlgebraicGeometry.blowup_regularLocalRing_dimTwo_exceptional_support_nonempty A hdim
  -- `I ⊆ 𝔪` gives `IX ≤ E`; `𝔪^n ⊆ I` gives `E^n ≤ IX`
  have h1 : IX ≤ E :=
    AlgebraicGeometry.Scheme.IdealSheafData.comap_mono _
      (AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop_mono (Ideal.map_mono hIm))
  have hn : E ^ n ≤ IX := by
    show (J.comap (AlgebraicGeometry.Scheme.blowup J).hom) ^ n ≤ IX
    rw [← AlgebraicGeometry.Scheme.IdealSheafData.comap_pow,
      AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop_pow, ← Ideal.map_pow]
    exact AlgebraicGeometry.Scheme.IdealSheafData.comap_mono _
      (AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop_mono (Ideal.map_mono hmI))
  obtain ⟨d, I', hd, hprod, hmax⟩ :=
    AlgebraicGeometry.Scheme.IdealSheafData.exists_maximal_exponent_of_invertible hE hy h1 n hn
  refine ⟨d, I', hd, fun U => ?_, fun h => hmax fun U => ?_⟩
  · rw [hprod, AlgebraicGeometry.Scheme.IdealSheafData.ideal_mul, Pi.mul_apply,
      AlgebraicGeometry.Scheme.IdealSheafData.ideal_pow, Pi.pow_apply]
  · have := h U
    rwa [AlgebraicGeometry.Scheme.IdealSheafData.ideal_pow, Pi.pow_apply]

/-- **Leaf (2): finiteness of the support** in the second paragraph of the proof of Stacks 0AGT
(where Stacks uses the "codimension 1 part", Stacks 0AGB): `O_X(−dE)/I·O_X`, i.e. `O_X/I'`, is supported
in finitely many closed points of `X`.

Proof (a purely topological route, avoiding 0AGB, DVRs and UFDs):
1. `supp I' ⊆ supp E`: `IX = E^d·I'` and `E^n ≤ IX` (`support_le_of_eq_mul_of_pow_le`).
2. `supp E ⊄ supp I'`: otherwise, since `E` is a radical ideal sheaf (the exceptional divisor is
   reduced: on the chart `A[𝔪/a]/(a) ≅ κ[T]` is a domain, `blowup_regularLocalRing_dimTwo_exceptionalIdeal_radical`),
   the Nullstellensatz for ideal sheaves (`le_of_support_le_of_radical`) gives `I' ≤ E`, hence
   `IX ≤ E^(d+1)`, contradicting the maximality of `d`.
3. `supp E` is topologically the image of a closed embedding of `P¹_κ`
   (`blowup_regularLocalRing_dimTwo_exceptional_support_closedEmbedding`), and a proper closed subset of
   `P¹_κ` is a finite set of closed points (`ProjectiveLine.finite_of_isClosed_of_ne_univ`); the closed
   embedding carries closed points back to `X`. -/
theorem AlgebraicGeometry.blowup_improve_support_finite
    (A : Type u) [CommRing A] [IsRegularLocalRing A] (hdim : ringKrullDim A = 2)
    (I : Ideal A) (n : ℕ) (hmI : IsLocalRing.maximalIdeal A ^ n ≤ I)
    (hIm : I ≤ IsLocalRing.maximalIdeal A) :
    let e := (AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of A)).inv.hom
    let J : (AlgebraicGeometry.Spec (CommRingCat.of A)).IdealSheafData :=
      AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop ((IsLocalRing.maximalIdeal A).map e)
    let X := (AlgebraicGeometry.Scheme.blowup J).left
    let E : X.IdealSheafData := AlgebraicGeometry.Scheme.blowup.exceptionalIdeal J
    let IX : X.IdealSheafData :=
      (AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop (I.map e)).comap
        (AlgebraicGeometry.Scheme.blowup J).hom
    ∀ (d : ℕ) (I' : X.IdealSheafData), 0 < d →
      (∀ U : X.affineOpens, IX.ideal U = E.ideal U ^ d * I'.ideal U) →
      ¬ (∀ U : X.affineOpens, IX.ideal U ≤ E.ideal U ^ (d + 1)) →
      ∃ T : Finset X, (I'.support : Set X) = ↑T ∧ (∀ x ∈ T, IsClosed ({x} : Set X)) := by
  intro e J X E IX d I' _hd hprod hmax
  -- `E^n ≤ IX` (as in leaf (1)), hence `supp I' ⊆ supp E`
  have hn : E ^ n ≤ IX := by
    show (J.comap (AlgebraicGeometry.Scheme.blowup J).hom) ^ n ≤ IX
    rw [← AlgebraicGeometry.Scheme.IdealSheafData.comap_pow,
      AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop_pow, ← Ideal.map_pow]
    exact AlgebraicGeometry.Scheme.IdealSheafData.comap_mono _
      (AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop_mono (Ideal.map_mono hmI))
  have hsub : I'.support ≤ E.support :=
    AlgebraicGeometry.Scheme.IdealSheafData.support_le_of_eq_mul_of_pow_le d n hprod hn
  -- `supp E ⊄ supp I'`: otherwise `I' ≤ E` (E is radical) and `IX ≤ E^(d+1)`
  have hrad := AlgebraicGeometry.blowup_regularLocalRing_dimTwo_exceptionalIdeal_radical A hdim
  have hne : ¬ E.support ≤ I'.support := by
    intro hle
    have hI'E : I' ≤ E :=
      AlgebraicGeometry.Scheme.IdealSheafData.le_of_support_le_of_radical hrad hle
    apply hmax
    intro U
    rw [hprod U, pow_succ]
    exact Ideal.mul_mono_right (hI'E U)
  -- `supp E` is a closed copy of `P¹_κ`; proper closed subsets of `P¹_κ` are finite sets of closed points
  obtain ⟨f, hf, hrange⟩ :=
    AlgebraicGeometry.blowup_regularLocalRing_dimTwo_exceptional_support_closedEmbedding A hdim
  obtain ⟨Z, hZdef⟩ : ∃ Z : Set (ProjectiveLine (IsLocalRing.ResidueField A)),
      Z = f ⁻¹' (I'.support : Set X) := ⟨_, rfl⟩
  have hZc : IsClosed Z := hZdef ▸ I'.support.isClosed.preimage hf.continuous
  have hZne : Z ≠ Set.univ := by
    intro hZ
    apply hne
    intro y hy
    have hy' : y ∈ Set.range f := hrange ▸ hy
    obtain ⟨p, rfl⟩ := hy'
    have hp : p ∈ Z := hZ ▸ Set.mem_univ p
    rw [hZdef] at hp
    exact hp
  obtain ⟨hfin, hcl⟩ := ProjectiveLine.finite_of_isClosed_of_ne_univ _ Z hZc hZne
  have himg : (I'.support : Set X) = f '' Z := by
    ext y
    constructor
    · intro hy
      have hy' : y ∈ Set.range f := hrange ▸ hsub hy
      obtain ⟨p, rfl⟩ := hy'
      exact ⟨p, by rw [hZdef]; exact hy, rfl⟩
    · rintro ⟨p, hp, rfl⟩
      rw [hZdef] at hp
      exact hp
  refine ⟨(hfin.image f).toFinset, by rw [Set.Finite.coe_toFinset, himg], ?_⟩
  intro y hy
  rw [Set.Finite.mem_toFinset] at hy
  obtain ⟨p, hp, rfl⟩ := hy
  have : ({f p} : Set X) = f '' {p} := (Set.image_singleton).symm
  rw [this]
  exact hf.isClosedMap _ (hcl p hp)

/-- **Leaf (3): the length inequality** of Stacks 0AGT (second and third paragraphs of the proof):
`length_A(A/I) > length_A Γ(X, O_X/I') ≥ ∑ᵢ length_{O_{X,xᵢ}}(O_{X,xᵢ}/I'_{xᵢ})`.

Route (no sheaf cohomology, no quotient sheaves, no twisting sheaf `O_X(dE)`): "global sections of
`O_X/J`" are modelled by the compatible families `J.quotFamilies` over all affine opens, and the chain
`∑ₓ ℓ(O_x/I'_x) = ∑ₓ ℓ(E^d_x/IX_x) ≤ ℓ_R(Γ(E^d/IX)) < ℓ_R(Γ(O_X/IX)) ≤ ℓ_R(R/IR) ≤ ℓ_A(A/I)`
(`R = Γ(X, O_X)`) is `length_sum_lt_of_quotFamilies`. Inputs:
* 0AGS(4), `Γ(X, O_X) = A`: `blowup_regularLocalRing_dimTwo_sections`;
* 0AGS(3) in Čech-`H⁰` form, `Γ(X, O_X) ↠ Γ(X, O_X/IX)`:
  `blowup_regularLocalRing_dimTwo_toQuotFamilies_surjective` (a two-chart Čech argument using the
  Laurent splitting `A[u,u⁻¹] = A[u] + A[u⁻¹]`);
* the skyscraper step (Stacks' "detail omitted"): `subFamiliesGerm_surjective`, resting on the pure
  algebra `Module.bijective_pi_localizedModule_of_support_subset`; only left exactness and
  `1 ∉ Γ(E^d/IX)` are needed, no `H¹` of a skyscraper sheaf;
* at the stalks, `O_X(dE)` invertible gives `ℓ(O_x/I'_x) = ℓ(E^d_x/IX_x)`: `length_stalkPiece_pow_mul_eq`;
* `ℓ_A(M) ≥ ℓ_{O_{X,x}}(M)`: `Submodule.length_le_length_restrictScalars`;
* `ℓ_A(A/I) < ∞` from `𝔪ⁿ ⊆ I`: `Module.length_quotient_ne_top_of_maximalIdeal_pow_le`. -/
theorem AlgebraicGeometry.blowup_improve_length_lt
    (A : Type u) [CommRing A] [IsRegularLocalRing A] (hdim : ringKrullDim A = 2)
    (I : Ideal A) (n : ℕ) (hmI : IsLocalRing.maximalIdeal A ^ n ≤ I)
    (hIm : I ≤ IsLocalRing.maximalIdeal A) :
    let e := (AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of A)).inv.hom
    let J : (AlgebraicGeometry.Spec (CommRingCat.of A)).IdealSheafData :=
      AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop ((IsLocalRing.maximalIdeal A).map e)
    let X := (AlgebraicGeometry.Scheme.blowup J).left
    let E : X.IdealSheafData := AlgebraicGeometry.Scheme.blowup.exceptionalIdeal J
    let IX : X.IdealSheafData :=
      (AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop (I.map e)).comap
        (AlgebraicGeometry.Scheme.blowup J).hom
    ∀ (d : ℕ) (I' : X.IdealSheafData), 0 < d →
      (∀ U : X.affineOpens, IX.ideal U = E.ideal U ^ d * I'.ideal U) →
      ∀ T : Finset X, (I'.support : Set X) = ↑T → (∀ x ∈ T, IsClosed ({x} : Set X)) →
        ∀ (W : T → X.affineOpens) (hW : ∀ x : T, x.1 ∈ ((W x : X.affineOpens) : X.Opens)),
          ∑ x : T, Module.length (X.presheaf.stalk x.1)
              (X.presheaf.stalk x.1 ⧸
                (I'.ideal (W x)).map (X.presheaf.germ ((W x : X.affineOpens) : X.Opens) x.1 (hW x)).hom)
            < Module.length A (A ⧸ I) := by
  intro e J X E IX d I' hd hprod T hT hTclosed W hW
  -- `X` is locally Noetherian (as in leaf (1))
  have : AlgebraicGeometry.IsNoetherian (AlgebraicGeometry.Spec (CommRingCat.of A)) := inferInstance
  have : AlgebraicGeometry.IsProjectiveMorphism (AlgebraicGeometry.Scheme.blowup J).hom :=
    AlgebraicGeometry.Scheme.blowup_isProjectiveMorphism J
  have : AlgebraicGeometry.IsProper (AlgebraicGeometry.Scheme.blowup J).hom :=
    AlgebraicGeometry.IsProjectiveMorphism.isProper _
  have : AlgebraicGeometry.IsLocallyNoetherian X :=
    AlgebraicGeometry.LocallyOfFiniteType.isLocallyNoetherian (AlgebraicGeometry.Scheme.blowup J).hom
  -- `E` invertible (0806) and nonempty (0AGQ)
  have hE : MiyaokaMori.Statement.IsInvertibleIdeal E :=
    AlgebraicGeometry.Scheme.blowup_exceptional_isInvertibleIdeal J
  obtain ⟨y, hy⟩ := AlgebraicGeometry.blowup_regularLocalRing_dimTwo_exceptional_support_nonempty A hdim
  have hIX : IX = E ^ d * I' := by
    ext U : 2
    rw [hprod U, AlgebraicGeometry.Scheme.IdealSheafData.ideal_mul, Pi.mul_apply,
      AlgebraicGeometry.Scheme.IdealSheafData.ideal_pow, Pi.pow_apply]
  -- `φ : A → Γ(X, O_X)` is surjective (0AGS(4))
  have hiso : IsIso (AlgebraicGeometry.Scheme.blowup J).hom.appTop :=
    AlgebraicGeometry.blowup_regularLocalRing_dimTwo_sections A hdim
  obtain ⟨φ, hφdef⟩ : ∃ φ : A →+* Γ(X, ⊤),
      φ = ((AlgebraicGeometry.Scheme.blowup J).hom.appTop).hom.comp e := ⟨_, rfl⟩
  have hφ : Function.Surjective φ := by
    rw [hφdef]
    exact (ConcreteCategory.bijective_of_isIso (AlgebraicGeometry.Scheme.blowup J).hom.appTop).2.comp
      (ConcreteCategory.bijective_of_isIso (AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of A)).inv).2
  -- `Γ(X, O_X) ↠ Γ(X, O_X/IX)` (0AGS(3) in Čech-`H⁰` form)
  have hsurj : Function.Surjective (E ^ d * I').toQuotFamilies := by
    have h := AlgebraicGeometry.blowup_regularLocalRing_dimTwo_toQuotFamilies_surjective A hdim I
    change Function.Surjective IX.toQuotFamilies at h
    rwa [hIX] at h
  -- `I` dies in `Γ(X, O_X/IX)`: `IX(U) = I·Γ(U)`
  have hker : ∀ a ∈ I, (E ^ d * I').toQuotFamilies (φ a) = 0 := by
    rw [← hIX, hφdef]
    intro a ha
    apply Subtype.ext
    funext U
    rw [AlgebraicGeometry.Scheme.IdealSheafData.toQuotFamilies_apply_coe]
    show Ideal.Quotient.mk (IX.ideal U) _ = 0
    have hU : (U : X.Opens) ≤ (AlgebraicGeometry.Scheme.blowup J).hom ⁻¹ᵁ
        (⊤ : (AlgebraicGeometry.Spec (CommRingCat.of A)).Opens) := fun _ _ => trivial
    rw [Ideal.Quotient.eq_zero_iff_mem,
      AlgebraicGeometry.Scheme.IdealSheafData.comap_ideal_eq_map_appLE _ _
        ⟨⊤, AlgebraicGeometry.isAffineOpen_top _⟩ U hU]
    have hid : (AlgebraicGeometry.Spec (CommRingCat.of A)).presheaf.map
        (homOfLE (le_top : (⊤ : (AlgebraicGeometry.Spec (CommRingCat.of A)).Opens) ≤ ⊤)).op =
          𝟙 _ :=
      (AlgebraicGeometry.Spec (CommRingCat.of A)).presheaf.map_id (op ⊤)
    have hmem : e a ∈ (AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop (I.map e)).ideal
        ⟨⊤, AlgebraicGeometry.isAffineOpen_top _⟩ := by
      rw [AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop_ideal, hid, CommRingCat.hom_id,
        Ideal.map_id]
      exact Ideal.mem_map_of_mem _ ha
    exact Ideal.mem_map_of_mem _ hmem
  have hfin : Module.length A (A ⧸ I) ≠ ⊤ :=
    Module.length_quotient_ne_top_of_maximalIdeal_pow_le I n hmI
  have hcore := AlgebraicGeometry.Scheme.IdealSheafData.length_sum_lt_of_quotFamilies E I' hE d hd hy
    T hTclosed hT A φ hφ I hfin hsurj hker
  refine lt_of_eq_of_lt ?_ hcore
  exact Finset.sum_congr rfl fun x _ => by
    rw [← I'.stalkIdeal_eq_map_germ x.1 (W x) (hW x)]

end
