import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial
import Mathlib.AlgebraicGeometry.Noetherian
import Mathlib.AlgebraicGeometry.Morphisms.Proper
import Mathlib.RingTheory.RegularLocalRing.Defs

/-!
# Blowups and finite sequences of point blowups

The blowup is specified by its geometric universal property, Stacks Project Tag 0806.
Its structural morphism is an actual scheme morphism. The inverse image of the centre
must be an effective Cartier divisor, and every morphism with this property factors
uniquely through it. This characterizes the relative Proj of the Rees algebra up to
unique isomorphism; existence is a separate theorem, not a field of a certificate.

Ideal sheaves use Mathlib's quasi-coherent `Scheme.IdealSheafData`, including its
actual scheme-theoretic pullback. Local generators are required to be nonzerodivisors,
so a merely principal zero ideal does not count as an invertible ideal.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace

namespace MiyaokaMori.Statement

universe u

/-- An ideal sheaf is invertible if it is locally generated by a nonzerodivisor.
For an ideal subsheaf of the structure sheaf this is precisely the effective Cartier
condition, including the unit ideal and the empty divisor. -/
def IsInvertibleIdeal {X : Scheme.{u}} (I : X.IdealSheafData) : Prop :=
  ∀ x : X, ∃ U : X.affineOpens, x ∈ U.1 ∧
    ∃ a : Γ(X, U), (∀ r : Γ(X, U), a * r = 0 → r = 0) ∧
      I.ideal U = Ideal.span ({a} : Set Γ(X, U))

/-- The geometric universal property of blowing up an actual quasi-coherent ideal.
The quantified test objects and all factorization maps are actual schemes and scheme
morphisms. Stacks Tag 0806 identifies this property with the Rees relative Proj blowup. -/
def IsBlowup {X B : Scheme.{u}} (I : X.IdealSheafData) (b : B ⟶ X) : Prop :=
  IsInvertibleIdeal (I.comap b) ∧
    ∀ (T : Scheme.{u}) (f : T ⟶ X), IsInvertibleIdeal (I.comap f) →
      ∃! lift : T ⟶ B, lift ≫ b = f

/-- The geometric universal property determines the blowup up to an isomorphism
over its actual base scheme. -/
theorem IsBlowup.exists_iso {X B C : Scheme.{u}} {I : X.IdealSheafData}
    {b : B ⟶ X} {c : C ⟶ X} (hb : IsBlowup I b) (hc : IsBlowup I c) :
    ∃ e : B ≅ C, e.hom ≫ c = b := by
  obtain ⟨i, hi, _⟩ := hc.2 B b hb.1
  obtain ⟨j, hj, _⟩ := hb.2 C c hc.1
  have hij : i ≫ j = 𝟙 B := (hb.2 B b hb.1).unique
    (by rw [Category.assoc, hj, hi]) (Category.id_comp b)
  have hji : j ≫ i = 𝟙 C := (hc.2 C c hc.1).unique
    (by rw [Category.assoc, hi, hj]) (Category.id_comp c)
  exact ⟨⟨i, j, hij, hji⟩, hi⟩

/-- The ideal of the scheme-theoretic image of the residue-field point.
For a closed point this is the ideal of its canonical reduced closed subscheme. -/
def pointIdeal (X : Scheme.{u}) (x : X) : X.IdealSheafData :=
  (X.fromSpecResidueField x).ker

/-- A finite sequence of blowups at closed points whose images on the original
scheme lie in `allowed`. The constructors retain every actual structural morphism
and centre. The identity permits a sequence of length zero. -/
inductive IsPointBlowupSequenceOver (X : Scheme.{u}) (allowed : Set X) :
    {Y : Scheme.{u}} → (Y ⟶ X) → Prop
  | id : IsPointBlowupSequenceOver X allowed (𝟙 X)
  | cons {Y Z : Scheme.{u}} (f : Y ⟶ X) (b : Z ⟶ Y)
      (previous : IsPointBlowupSequenceOver X allowed f)
      (centre : Y) (closed : IsClosed ({centre} : Set Y))
      (centre_allowed : f centre ∈ allowed) (blowup : IsBlowup (pointIdeal Y centre) b) :
      IsPointBlowupSequenceOver X allowed (b ≫ f)

/-- An actual noetherian regular scheme of absolute dimension two. Regularity is
the regular-local-ring condition on every structure-sheaf stalk. -/
def IsRegularSurface (X : Scheme.{u}) : Prop :=
  IsNoetherian X ∧ (∀ x : X, IsRegularLocalRing (X.presheaf.stalk x)) ∧
    topologicalKrullDim X = 2

/-- The morphism induces an isomorphism over the specified open subscheme. -/
def IsIsoOverOpen {X Y : Scheme.{u}} (f : Y ⟶ X) (U : X.Opens) : Prop :=
  IsIso (morphismRestrict f U)

end MiyaokaMori.Statement
