import MiyaokaMori.Prelude
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

/-! # Adjoining weighted roots of finitely many elements

A finite field extension in which finitely many elements simultaneously acquire roots of
prescribed weights: if `K` is a field, `ι` is finite, `b : ι → K` and `q : ι → ℕ` is everywhere
positive, then there is a finite extension `K'/K` and `c : ι → K'` with
`c j ^ q j = algebraMap K K' (b j)`.

This is the field-theoretic step of Lemma 3.1 of the paper: after a further
finite extension, taken simultaneously for the finitely many charts, every nonzero coefficient
$b_{\alpha,i,q}$ of weight $q$ has a $q$-th root.

**Proof.** Let `L = AlgebraicClosure K`. Since `L` is algebraically closed, for every `j` there is
`z j ∈ L` with `z j ^ q j = algebraMap K L (b j)` (`IsAlgClosed.exists_pow_nat_eq`, which needs
`0 < q j`). Put `S = Set.range z` (a finite set) and `K' := IntermediateField.adjoin K S`.
Each `z j` is integral over `K`, since its `q j`-th power lies in the image of `K`
(`IsIntegral.of_pow` and `isIntegral_algebraMap`). An intermediate field generated by finitely many
integral elements is finite-dimensional (`IntermediateField.finiteDimensional_adjoin`), so
`Module.Finite K K'`. Take `c j := ⟨z j, subset_adjoin …⟩`; the relation holds in `L`, and pulls
back along the injection `K' ↪ L`. ∎

Note that the hypothesis `b j ≠ 0` is not needed: for `b j = 0` the root `z j = 0` works.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v

noncomputable section

/-- Simultaneous weighted roots of finitely many elements: there is a finite extension `K'/K`
in which every `b j` has a `q j`-th root (Lemma 3.1 of the paper).

The extension is the intermediate field of `AlgebraicClosure K` generated by the chosen roots;
finiteness comes from `IntermediateField.finiteDimensional_adjoin`. -/
theorem exists_finite_extension_with_roots {K : Type u} [Field K] {ι : Type v} [Finite ι]
    (b : ι → K) (q : ι → ℕ) (hq : ∀ j, 0 < q j) :
    ∃ (K' : Type u) (_ : Field K') (_ : Algebra K K') (_ : Module.Finite K K') (c : ι → K'),
      ∀ j, c j ^ q j = algebraMap K K' (b j) := by
  classical
  have hz : ∀ j, ∃ z : AlgebraicClosure K, z ^ q j = algebraMap K (AlgebraicClosure K) (b j) :=
    fun j => IsAlgClosed.exists_pow_nat_eq _ (hq j)
  choose z hzspec using hz
  have hSfin : (Set.range z).Finite := Set.finite_range z
  have : Finite (Set.range z : Set (AlgebraicClosure K)) := hSfin
  have hint : ∀ x ∈ Set.range z, IsIntegral K x := by
    rintro x ⟨j, rfl⟩
    refine IsIntegral.of_pow (hq j) ?_
    rw [hzspec j]
    exact isIntegral_algebraMap
  have : FiniteDimensional K (IntermediateField.adjoin K (Set.range z)) :=
    IntermediateField.finiteDimensional_adjoin hint
  refine ⟨IntermediateField.adjoin K (Set.range z), inferInstance, inferInstance, inferInstance,
    fun j => ⟨z j, IntermediateField.subset_adjoin K (Set.range z) ⟨j, rfl⟩⟩, fun j => ?_⟩
  apply Subtype.ext
  rw [IntermediateField.coe_pow, IntermediateField.coe_algebraMap_apply]
  exact hzspec j

end
