import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.RelativeProjLiftDataOfEpi
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.RelativeProjLift
import MiyaokaMori.AlgebraicGeometry.Modules.Pullback.EpiOfTransposeFrames
import MiyaokaMori.AlgebraicGeometry.Modules.FrameLocusOn
import MiyaokaMori.AlgebraicGeometry.Morphisms.IsImmersionOfAffineCharts
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.ProjFromGlobalSectionsCharts
import MiyaokaMori.AlgebraicGeometry.Modules.FrameLocusCoordinate
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.RelativeProjLiftLocalRingHomDegreeOne
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.RelativeProjLiftPieceOnChart
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.ModuleSheafFrame
import MiyaokaMori.AlgebraicGeometry.Proj.WeightedProj.WeightedPolynomialAlgebraPullback

/-! # The immersion criterion for `X → P(E)` from chart data

**Immersion criterion for the morphism `X → P(E) = Proj_S Sym E`** (Stacks 07RM, fifth paragraph; Stacks 01O9,
07RK): `f : X ⟶ S`, `M` a line bundle on `X`, `E` quasi-coherent on `S`, `ψ : f^*E ↠ M` an epimorphism with
transpose `φ : E ⟶ f_*M`, and `r := relativeProj.lift (Sym E) f M (liftDataOfEpi f E M ψ hψ) : X ⟶ P(E)`
(`relativeProj.liftDataOfEpi`). Suppose that every `x ∈ X` has an affine open `V ∋ f(x)` and a section
`e ∈ E(V)` such that, with `s := φ(e) ∈ Γ(f⁻¹V, M)` (`transposeSection f ψ e`) and `X_s := M.frameLocusOn s`,
(a) `x ∈ X_s` and `X_s` is affine, and (b) `Γ(X_s, O_X)` is generated by the image of `Γ(V, O_S)` and the ratios
`φ(e')/s`, `e' ∈ E(V)`. Then `r` is an immersion.

**Proof (Stacks 01O9 / 07RK / 01NQ / 01O4; formalized below and in the four modules
`…_ProjChart`, `…_FrameCoord`, `…_DegreeOne`, `…_Piece`).**
1. *Charts of `P(E)`* (`…_Piece.lean`, `…_ProjChart.lean`). Over the affine `V`, `chartHom (Sym E) V : Proj A(V) ≅ π⁻¹V ↪ P(E)`
   with `A(V) := Γ(V, Sym E) = ⊕_m Γ(V, Sym^m E)` (`relativeProj.affineIso`, Stacks 01NQ). For `e ∈ E(V)` let
   `a := π₁(e) = (symGen E).app V e ∈ A(V)_1` (`symChartGen`). The chart `C(V, e) := chartHom(D₊(a)) ⊆ P(E)`
   (`symChart`) is affine (Mathlib `Proj.isAffineOpen_basicOpen`, image under an open immersion).
2. *Pieces adapted to the chart* (`exists_piece_chart`, `…_Piece.lean`, from `homOfLE_liftLocal` and
   `liftLocalPiece_change_W`): every `y ∈ f⁻¹V` lies in an affine `V₃ ⊆ f⁻¹V` with a trivialization `et` of `M` such that
   `V₃.ι ≫ r = Proj.fromOfGlobalSections A(V) Φ ≫ chartHom (Sym E) V`, `Φ := liftLocalRingHomAux D V₃.ι et V` the local
   ring map of Stacks 01O4.
3. *Degree one* (`liftLocalPieceAux_one_symGen_app`, `…_DegreeOne.lean`, proved): `Φ(π₁ e') = coordOn et (φ e')`, the
   coordinate of the section `φ(e') ∈ Γ(M, f⁻¹V)` in the trivialization `et`
   (`pullback_map_symGen_comp_symGradedPullbackDesc_one`: `Sym^1 ψ = ψ`; `app_unit_app_eq_homEquiv_app`).
4. *Preimage of the chart* (`preimage_symChart_eq_frameLocusOn`, proved): `r⁻¹C(V,e) = X_s`. Pointwise on a piece
   `V₃ ∋ y`: `V₃.ι⁻¹(r⁻¹C) = (fromOfGlobalSections Φ ≫ chartHom)⁻¹(chartHom(D₊(a))) = V₃.basicOpen (Φ a)` (Mathlib
   `fromOfGlobalSections_preimage_basicOpen`), and `V₃.ι⁻¹X_s = V₃.basicOpen (coordOn et s)`
   (`preimage_frameLocusOn_eq_basicOpen_coordOn`, `…_FrameCoord.lean`: `s` is a frame near `ι y` iff its coordinate is a
   unit near `y`); the two basic opens agree by step 3.
5. *The ring map on the chart is surjective* (`surjective_appLE_symChart`, proved): by (b)
   it suffices to hit the generators of `Γ(X_s, O)`. The image of `c ∈ Γ(V, O)` is `r^♯(π^♯ c|_C)` since `r ≫ π = f`
   (`lift_hom`). For a ratio `g` with `φ(e')|_{X_s} = g • s|_{X_s}`, take the degree-zero fraction
   `u := π₁(e')/π₁(e) ∈ A(V)_{(a)} = Γ(D₊(a), O)` read on `C` through `chartHom.appIso`; then `r^♯(u) = g` is checked
   locally on `X_s` (sheaf axiom of `O_X`) on the pieces `V₃ ∩ X_s = V₃.basicOpen (Φ a)` of step 2: there
   `r^♯(u) = Φ(π₁ e')/Φ(π₁ e)` (Stacks 01O4 (2), `fromOfGlobalSections_appLE_awayToSection_mk_mul`), while applying the
   coordinate map to `φ(e') = g • s` gives `Φ(π₁ e') = ι^♯(g) · Φ(π₁ e)` (`coordOn_smul`, step 3); cancel the unit
   `Φ(π₁ e)`.
6. *Conclusion* (`isImmersion_of_affine_charts`): the charts `C(V,e)`,
   one for each `x`, are affine (step 1), cover the image of `r` (`x ∈ X_s = r⁻¹C(V,e)`, step 4), have affine preimages
   `X_s` (a), and surjective ring maps (step 5). Hence `r` is an immersion.

**Edge cases.** `X = ∅`: vacuous. `E = 0`: then `M = 0` is not a line bundle unless `X = ∅` (the hypothesis
`Epi ψ` forces `M` to be locally generated by `E`). `V` with `f⁻¹V = ∅`: the chart is not needed. -/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- `ψ^♭(e) = φ(e) ∈ Γ(M, f⁻¹V)`: the section of `M` over `f⁻¹V` corresponding to `e ∈ E(V)` under the
transpose `φ : E ⟶ f_*M` of `ψ : f^*E ⟶ M`. -/
abbrev AlgebraicGeometry.Scheme.Modules.transposeSection {X S : AlgebraicGeometry.Scheme.{u}} (f : X ⟶ S)
    {E : S.Modules} {M : X.Modules} (ψ : (AlgebraicGeometry.Scheme.Modules.pullback f).obj E ⟶ M)
    {V : S.Opens} (e : Γ(E, V)) : Γ(M, f ⁻¹ᵁ V) :=
  AlgebraicGeometry.Scheme.Modules.ofPushforwardSection f M
    (((AlgebraicGeometry.Scheme.Modules.pullbackPushforwardAdjunction f).homEquiv E M ψ).app V e)

namespace AlgebraicGeometry.Scheme.relativeProj

open AlgebraicGeometry.Scheme.Modules

variable {X S : AlgebraicGeometry.Scheme.{u}}

/-- The degree-one element `π₁(e) = (symGen E).app V e` of the section ring `A(V) = ⊕_m Γ(V, Sym^m E)`. -/
def symChartGen (E : S.Modules) (V : S.Opens) (e : Γ(E, V)) :
    (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E).sectionsRing V :=
  DirectSum.of ((AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E).sectionsPiece V) 1
    ((AlgebraicGeometry.Scheme.Modules.symGen E).app V e)

theorem symChartGen_mem (E : S.Modules) (V : S.Opens) (e : Γ(E, V)) :
    symChartGen E V e ∈ (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E).sectionsGrading V 1 :=
  ⟨_, rfl⟩

/-- **The chart `C(V, e) = chartHom(D₊(π₁ e)) ⊆ P(E)`** of Stacks 01O9 over the affine open `V`. -/
def symChart (E : S.Modules) (V : S.affineOpens) (e : Γ(E, V.1)) :
    (AlgebraicGeometry.Scheme.relativeProj (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E)).left.Opens :=
  haveI := AlgebraicGeometry.Scheme.relativeProj.isOpenImmersion_chartHom
    (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) V
  AlgebraicGeometry.Scheme.relativeProj.chartHom (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) V ''ᵁ
    AlgebraicGeometry.Proj.basicOpen
      ((AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E).sectionsGrading V.1) (symChartGen E V.1 e)

/-- The chart `C(V, e)` is affine (Mathlib `Proj.isAffineOpen_basicOpen`). -/
theorem isAffineOpen_symChart (E : S.Modules) (V : S.affineOpens) (e : Γ(E, V.1)) :
    AlgebraicGeometry.IsAffineOpen (symChart E V e) :=
  haveI := AlgebraicGeometry.Scheme.relativeProj.isOpenImmersion_chartHom
    (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) V
  AlgebraicGeometry.Proj.isAffineOpen_image_basicOpen _ _ Nat.one_pos (symChartGen_mem E V.1 e)

/-- The chart `C(V, e)` lies in `π⁻¹V`. -/
theorem symChart_le (E : S.Modules) (V : S.affineOpens) (e : Γ(E, V.1)) :
    symChart E V e ≤
      (AlgebraicGeometry.Scheme.relativeProj (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E)).hom ⁻¹ᵁ V.1 := by
  have := AlgebraicGeometry.Scheme.relativeProj.isOpenImmersion_chartHom
    (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) V
  refine (AlgebraicGeometry.Scheme.Hom.image_le_opensRange _ _).trans (le_of_eq ?_)
  exact AlgebraicGeometry.Scheme.relativeProj.opensRange_chartHom _ V

variable (f : X ⟶ S) (M : X.Modules) [M.IsLineBundle] (E : S.Modules) [E.IsQuasicoherent]
  (ψ : (AlgebraicGeometry.Scheme.Modules.pullback f).obj E ⟶ M) (hψ : CategoryTheory.Epi ψ)

/-- `appLE` of two equal morphisms, applied pointwise (transport of the dependent proof). -/
private theorem appLE_congr_hom_apply_07rm {Y P : AlgebraicGeometry.Scheme.{u}} {k k' : Y ⟶ P}
    (h : k = k') (U : P.Opens) (W : Y.Opens) (e : W ≤ k ⁻¹ᵁ U) (e' : W ≤ k' ⁻¹ᵁ U) (c : Γ(P, U)) :
    k.appLE U W e c = k'.appLE U W e' c := by
  subst h
  rfl

local notation "𝒮" => AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E
local notation "𝔇" => AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ
local notation "𝕣" => AlgebraicGeometry.Scheme.relativeProj.lift (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E)
  f M (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ)

/-- `r⁻¹C(V, e) ⊆ f⁻¹V` (`r ≫ π = f`). -/
theorem preimage_symChart_le (V : S.affineOpens) (e : Γ(E, V.1)) :
    AlgebraicGeometry.Scheme.relativeProj.lift (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) f M
        (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ) ⁻¹ᵁ symChart E V e ≤ f ⁻¹ᵁ V.1 := by
  have h := (AlgebraicGeometry.Scheme.relativeProj.lift (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) f M
    (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ)).preimage_mono (symChart_le E V e)
  refine h.trans (le_of_eq ?_)
  show (AlgebraicGeometry.Scheme.relativeProj.lift (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) f M
    (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ) ≫
      (AlgebraicGeometry.Scheme.relativeProj (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E)).hom) ⁻¹ᵁ V.1 =
    f ⁻¹ᵁ V.1
  rw [AlgebraicGeometry.Scheme.relativeProj.lift_hom]

/-- **Degree one of the local ring map on a chart-adapted piece is the coordinate of `φ(e')`**
(`liftLocalRingHomAux_of` + `liftLocalPieceAux_one_symGen_app`). -/
theorem liftLocalRingHomAux_symChartGen {Y : AlgebraicGeometry.Scheme.{u}} (ι : Y ⟶ X)
    (et : (AlgebraicGeometry.Scheme.Modules.pullback ι).obj M ≅ SheafOfModules.unit Y.ringCatSheaf)
    (V : S.Opens) (hW : (⊤ : Y.Opens) ≤ (ι ≫ f) ⁻¹ᵁ V) (e' : Γ(E, V)) :
    AlgebraicGeometry.Scheme.relativeProj.liftLocalRingHomAux
        (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ) ι et V hW (symChartGen E V e') =
      coordOn ι M et (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e') hW := by
  exact (AlgebraicGeometry.Scheme.relativeProj.liftLocalRingHomAux_of 𝔇 ι et V hW 1 _).trans
    (AlgebraicGeometry.Scheme.relativeProj.liftLocalPieceAux_one_symGen_app f M E ψ hψ ι et V hW e')

set_option backward.isDefEq.respectTransparency false in
/-- **Preimage of the chart is the frame locus**: `r⁻¹C(V, e) = X_{φ(e)}` (Stacks 01O9, 07RK). -/
theorem preimage_symChart_eq_frameLocusOn (V : S.affineOpens) (e : Γ(E, V.1)) :
    AlgebraicGeometry.Scheme.relativeProj.lift (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) f M
        (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ) ⁻¹ᵁ symChart E V e =
      M.frameLocusOn (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e) := by
  have := AlgebraicGeometry.Scheme.relativeProj.isOpenImmersion_chartHom
    (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) V
  have hL := preimage_symChart_le f M E ψ hψ V e
  have hR := M.frameLocusOn_le (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e)
  apply TopologicalSpace.Opens.ext
  ext y
  simp only [SetLike.mem_coe]
  by_cases hy : y ∈ f ⁻¹ᵁ V.1
  · obtain ⟨V₃, hV₃, et, hW, hyV₃, hr⟩ := AlgebraicGeometry.Scheme.relativeProj.exists_piece_chart
      (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) f M
      (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ) V y hy
    have e1 : V₃.ι ⁻¹ᵁ (AlgebraicGeometry.Scheme.relativeProj.lift
          (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) f M
          (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ) ⁻¹ᵁ symChart E V e) =
        V₃.toScheme.basicOpen (AlgebraicGeometry.Scheme.relativeProj.liftLocalRingHomAux
          (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ) V₃.ι et V.1 hW
          (symChartGen E V.1 e)) := by
      show (V₃.ι ≫ AlgebraicGeometry.Scheme.relativeProj.lift
          (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) f M
          (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ)) ⁻¹ᵁ symChart E V e = _
      rw [hr]
      exact AlgebraicGeometry.Proj.fromOfGlobalSections_comp_preimage_image_basicOpen _ _ _ _ Nat.one_pos
        (symChartGen_mem E V.1 e)
    have e2 := preimage_frameLocusOn_eq_basicOpen_coordOn V₃.ι M et
      (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e) hW
    have e3 := liftLocalRingHomAux_symChartGen f M E ψ hψ V₃.ι et V.1 hW e
    have h1 : (y ∈ AlgebraicGeometry.Scheme.relativeProj.lift (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E)
          f M (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ) ⁻¹ᵁ symChart E V e) ↔
        (⟨y, hyV₃⟩ : V₃.toScheme) ∈ V₃.ι ⁻¹ᵁ (AlgebraicGeometry.Scheme.relativeProj.lift
          (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) f M
          (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ) ⁻¹ᵁ symChart E V e) := Iff.rfl
    have h2 : (y ∈ M.frameLocusOn (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e)) ↔
        (⟨y, hyV₃⟩ : V₃.toScheme) ∈
          V₃.ι ⁻¹ᵁ M.frameLocusOn (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e) := Iff.rfl
    rw [h1, h2, e1, e2, e3]
  · exact ⟨fun h => absurd (hL h) hy, fun h => absurd (hR h) hy⟩

/-- `appLE` of `f` through a factorization `g ≫ h = f` (`comp_appLE`). -/
theorem _root_.AlgebraicGeometry.Scheme.Hom.appLE_of_comp_eq {X Y Z : AlgebraicGeometry.Scheme.{u}}
    {g : X ⟶ Y} {h : Y ⟶ Z} {k : X ⟶ Z} (hk : g ≫ h = k) (U : Z.Opens) (W : X.Opens) (e : W ≤ k ⁻¹ᵁ U)
    (e' : W ≤ g ⁻¹ᵁ (h ⁻¹ᵁ U)) (c : Γ(Z, U)) :
    k.appLE U W e c = g.appLE (h ⁻¹ᵁ U) W e' (h.app U c) := by
  subst hk
  rw [AlgebraicGeometry.Scheme.Hom.comp_appLE, CommRingCat.comp_apply]

/-- Units of `Γ(Y, ⊤)` restricted to an open equal to a basic open (transport along an equality of opens). -/
theorem _root_.AlgebraicGeometry.Scheme.isUnit_res_of_eq_basicOpen (Y : AlgebraicGeometry.Scheme.{u}) (x : Γ(Y, ⊤))
    {O : Y.Opens} (h : O = Y.basicOpen x) : IsUnit (Y.presheaf.map (homOfLE (le_top : O ≤ ⊤)).op x) := by
  subst h
  exact AlgebraicGeometry.RingedSpace.isUnit_res_basicOpen _ x

set_option backward.isDefEq.respectTransparency false in
/-- **The ring map of `r` on the chart `C(V, e)` is surjective** (Stacks 01O9 / 07RK), given that
`Γ(X_s, O)` is generated by the image of `Γ(V, O)` and the ratios `φ(e')/s`. -/
theorem surjective_appLE_symChart (V : S.affineOpens) (e : Γ(E, V.1))
    (hgen : Subring.closure
      (Set.range (f.appLE V.1 (M.frameLocusOn (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e))
        (M.frameLocusOn_le (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e))) ∪
      {g | ∃ e' : Γ(E, V.1),
        M.res (M.frameLocusOn_le (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e))
            (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e') =
          g • M.res (M.frameLocusOn_le (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e))
            (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e)}) = ⊤) :
    Function.Surjective
      ((AlgebraicGeometry.Scheme.relativeProj.lift (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) f M
        (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ)).appLE (symChart E V e)
        (AlgebraicGeometry.Scheme.relativeProj.lift (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) f M
          (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ) ⁻¹ᵁ symChart E V e) le_rfl) := by
  have := AlgebraicGeometry.Scheme.relativeProj.isOpenImmersion_chartHom
    (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) V
  have hB := preimage_symChart_eq_frameLocusOn f M E ψ hψ V e
  have hX := preimage_symChart_le f M E ψ hψ V e
  have hC := symChart_le E V e
  -- transport the generation hypothesis from `X_s` to `r⁻¹C` (equal opens)
  have hgen' : Subring.closure
      (Set.range (f.appLE V.1 (𝕣 ⁻¹ᵁ symChart E V e) hX) ∪
      {g | ∃ e' : Γ(E, V.1),
        M.res hX (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e') =
          g • M.res hX (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e)}) = ⊤ := by
    revert hX
    rw [hB]
    intro hX
    exact hgen
  -- it suffices to hit the generators
  have hle : Subring.closure
      (Set.range (f.appLE V.1 (𝕣 ⁻¹ᵁ symChart E V e) hX) ∪
      {g | ∃ e' : Γ(E, V.1),
        M.res hX (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e') =
          g • M.res hX (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e)}) ≤
      ((𝕣).appLE (symChart E V e) (𝕣 ⁻¹ᵁ symChart E V e) le_rfl).hom.range := by
    refine Subring.closure_le.2 ?_
    rintro g (⟨c, rfl⟩ | ⟨e', he'⟩)
    · -- (i) the image of `Γ(V, O)`: `f = r ≫ π`
      refine RingHom.mem_range.2 ⟨(AlgebraicGeometry.Scheme.relativeProj 𝒮).left.presheaf.map (homOfLE hC).op
        ((AlgebraicGeometry.Scheme.relativeProj 𝒮).hom.app V.1 c), ?_⟩
      have h1 := AlgebraicGeometry.Scheme.Hom.appLE_of_comp_eq
        (AlgebraicGeometry.Scheme.relativeProj.lift_hom 𝒮 f M 𝔇) V.1 (𝕣 ⁻¹ᵁ symChart E V e) hX
        ((𝕣).preimage_mono hC) c
      have h2 := ConcreteCategory.congr_hom
        (AlgebraicGeometry.Scheme.Hom.map_appLE 𝕣 (le_rfl : 𝕣 ⁻¹ᵁ symChart E V e ≤ 𝕣 ⁻¹ᵁ symChart E V e)
          (homOfLE hC).op) ((AlgebraicGeometry.Scheme.relativeProj 𝒮).hom.app V.1 c)
      rw [CommRingCat.comp_apply] at h2
      exact h2.trans h1.symm
    · -- (ii) a ratio `g` with `φ(e') = g • φ(e)` on `r⁻¹C`: the fraction `π₁(e')/π₁(e)` read on the chart
      have hb : symChartGen E V.1 e' ∈ (𝒮).sectionsGrading V.1 (1 • 1) := by
        rw [one_nsmul]
        exact symChartGen_mem E V.1 e'
      refine RingHom.mem_range.2 ⟨((AlgebraicGeometry.Scheme.relativeProj.chartHom 𝒮 V).appIso
        (AlgebraicGeometry.Proj.basicOpen ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e))).inv
        (AlgebraicGeometry.Proj.awayToSection ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e)
          (HomogeneousLocalization.Away.mk ((𝒮).sectionsGrading V.1) (symChartGen_mem E V.1 e) 1
            (symChartGen E V.1 e') hb)), ?_⟩
      -- check `r^♯(u) = g` locally on `r⁻¹C`, on the pieces of `exists_piece_chart`
      have hpiece : ∀ y : (𝕣 ⁻¹ᵁ symChart E V e), ∃ (V₃ : X.Opens) (hV₃ : AlgebraicGeometry.IsAffineOpen V₃)
          (et : (AlgebraicGeometry.Scheme.Modules.pullback V₃.ι).obj M ≅
            SheafOfModules.unit V₃.toScheme.ringCatSheaf)
          (hW : (⊤ : V₃.toScheme.Opens) ≤ (V₃.ι ≫ f) ⁻¹ᵁ V.1),
          y.1 ∈ V₃ ∧
            V₃.ι ≫ 𝕣 =
              AlgebraicGeometry.Proj.fromOfGlobalSections ((𝒮).sectionsGrading V.1)
                  (AlgebraicGeometry.Scheme.relativeProj.liftLocalRingHomAux 𝔇 V₃.ι et V.1 hW)
                  (haveI : AlgebraicGeometry.IsAffine V₃.toScheme := hV₃
                   AlgebraicGeometry.Scheme.relativeProj.liftLocalRingHomAux_map_irrelevant 𝔇 V₃.ι et V hW) ≫
                AlgebraicGeometry.Scheme.relativeProj.chartHom 𝒮 V :=
        fun y => AlgebraicGeometry.Scheme.relativeProj.exists_piece_chart 𝒮 f M 𝔇 V y.1 (hX y.2)
      choose V₃ hV₃ et hW hyV₃ hr using hpiece
      have hO : ∀ y : (𝕣 ⁻¹ᵁ symChart E V e),
          (V₃ y).ι ''ᵁ ((V₃ y).ι ⁻¹ᵁ (𝕣 ⁻¹ᵁ symChart E V e)) ≤ 𝕣 ⁻¹ᵁ symChart E V e :=
        fun y => (V₃ y).ι.image_preimage_le _
      have hcov : 𝕣 ⁻¹ᵁ symChart E V e ≤
          iSup (fun y : (𝕣 ⁻¹ᵁ symChart E V e) => (V₃ y).ι ''ᵁ ((V₃ y).ι ⁻¹ᵁ (𝕣 ⁻¹ᵁ symChart E V e))) := by
        intro x hx
        exact TopologicalSpace.Opens.mem_iSup.2 ⟨⟨x, hx⟩, ⟨⟨x, hyV₃ ⟨x, hx⟩⟩, hx, rfl⟩⟩
      refine X.sheaf.eq_of_locally_eq' _ (𝕣 ⁻¹ᵁ symChart E V e) (fun y => homOfLE (hO y)) hcov _ _ (fun y => ?_)
      -- on the piece `V₃ y`: compare after `appIso`, i.e. compare `ι^♯` of both sides on `ι⁻¹(r⁻¹C)`
      have key : ∀ z : Γ(X, 𝕣 ⁻¹ᵁ symChart E V e),
          ((V₃ y).ι.appIso ((V₃ y).ι ⁻¹ᵁ (𝕣 ⁻¹ᵁ symChart E V e))).hom (X.sheaf.obj.map (homOfLE (hO y)).op z) =
            (V₃ y).ι.appLE (𝕣 ⁻¹ᵁ symChart E V e) ((V₃ y).ι ⁻¹ᵁ (𝕣 ⁻¹ᵁ symChart E V e)) le_rfl z := by
        intro z
        show ((V₃ y).ι.appIso ((V₃ y).ι ⁻¹ᵁ (𝕣 ⁻¹ᵁ symChart E V e))).hom
          (X.presheaf.map (homOfLE (hO y)).op z) = _
        rw [AlgebraicGeometry.Scheme.Hom.appIso_hom']
        have h := ConcreteCategory.congr_hom (AlgebraicGeometry.Scheme.Hom.map_appLE (V₃ y).ι
          ((V₃ y).ι.preimage_image_eq _).ge (homOfLE (hO y)).op) z
        rw [CommRingCat.comp_apply] at h
        exact h
      refine (ConcreteCategory.bijective_of_isIso
        ((V₃ y).ι.appIso ((V₃ y).ι ⁻¹ᵁ (𝕣 ⁻¹ᵁ symChart E V e))).hom).1 ?_
      rw [key, key]
      -- the piece: `ι⁻¹(r⁻¹C) = basicOpen (Φ a)`
      have hO' : (V₃ y).ι ⁻¹ᵁ (𝕣 ⁻¹ᵁ symChart E V e) =
          (V₃ y).toScheme.basicOpen (AlgebraicGeometry.Scheme.relativeProj.liftLocalRingHomAux 𝔇 (V₃ y).ι (et y)
            V.1 (hW y) (symChartGen E V.1 e)) := by
        show ((V₃ y).ι ≫ 𝕣) ⁻¹ᵁ symChart E V e = _
        rw [hr y]
        exact AlgebraicGeometry.Proj.fromOfGlobalSections_comp_preimage_image_basicOpen _ _ _ _ Nat.one_pos
          (symChartGen_mem E V.1 e)
      have hunit := AlgebraicGeometry.Scheme.isUnit_res_of_eq_basicOpen (V₃ y).toScheme _ hO'
      have hle' : (V₃ y).ι ⁻¹ᵁ (𝕣 ⁻¹ᵁ symChart E V e) ≤
          AlgebraicGeometry.Proj.fromOfGlobalSections ((𝒮).sectionsGrading V.1)
            (AlgebraicGeometry.Scheme.relativeProj.liftLocalRingHomAux 𝔇 (V₃ y).ι (et y) V.1 (hW y))
            (haveI : AlgebraicGeometry.IsAffine (V₃ y).toScheme := hV₃ y
             AlgebraicGeometry.Scheme.relativeProj.liftLocalRingHomAux_map_irrelevant 𝔇 (V₃ y).ι (et y) V (hW y)) ⁻¹ᵁ
            AlgebraicGeometry.Proj.basicOpen ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e) := by
        rw [hO', AlgebraicGeometry.Proj.fromOfGlobalSections_preimage_basicOpen _ _ _ Nat.one_pos
          (symChartGen_mem E V.1 e)]
      -- LHS: `ι^♯(r^♯ u) = φ^♯(u')`, the fraction formula (stated in the `''ᵁ` spelling of the chart)
      have hL : (V₃ y).ι.appLE
          (𝕣 ⁻¹ᵁ (AlgebraicGeometry.Scheme.relativeProj.chartHom 𝒮 V ''ᵁ
            AlgebraicGeometry.Proj.basicOpen ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e)))
          ((V₃ y).ι ⁻¹ᵁ (𝕣 ⁻¹ᵁ (AlgebraicGeometry.Scheme.relativeProj.chartHom 𝒮 V ''ᵁ
            AlgebraicGeometry.Proj.basicOpen ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e)))) le_rfl
          ((𝕣).appLE
            (AlgebraicGeometry.Scheme.relativeProj.chartHom 𝒮 V ''ᵁ
              AlgebraicGeometry.Proj.basicOpen ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e))
            (𝕣 ⁻¹ᵁ (AlgebraicGeometry.Scheme.relativeProj.chartHom 𝒮 V ''ᵁ
              AlgebraicGeometry.Proj.basicOpen ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e))) le_rfl
            (((AlgebraicGeometry.Scheme.relativeProj.chartHom 𝒮 V).appIso
              (AlgebraicGeometry.Proj.basicOpen ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e))).inv
              (AlgebraicGeometry.Proj.awayToSection ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e)
                (HomogeneousLocalization.Away.mk ((𝒮).sectionsGrading V.1) (symChartGen_mem E V.1 e) 1
                  (symChartGen E V.1 e') hb)))) =
          (AlgebraicGeometry.Proj.fromOfGlobalSections ((𝒮).sectionsGrading V.1)
            (AlgebraicGeometry.Scheme.relativeProj.liftLocalRingHomAux 𝔇 (V₃ y).ι (et y) V.1 (hW y))
            (haveI : AlgebraicGeometry.IsAffine (V₃ y).toScheme := hV₃ y
             AlgebraicGeometry.Scheme.relativeProj.liftLocalRingHomAux_map_irrelevant 𝔇 (V₃ y).ι (et y) V (hW y))).appLE
            (AlgebraicGeometry.Proj.basicOpen ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e))
            ((V₃ y).ι ⁻¹ᵁ (𝕣 ⁻¹ᵁ symChart E V e)) hle'
            (AlgebraicGeometry.Proj.awayToSection ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e)
              (HomogeneousLocalization.Away.mk ((𝒮).sectionsGrading V.1) (symChartGen_mem E V.1 e) 1
                (symChartGen E V.1 e') hb)) := by
        have h0 := ConcreteCategory.congr_hom (AlgebraicGeometry.Scheme.Hom.comp_appLE (V₃ y).ι 𝕣
          (AlgebraicGeometry.Scheme.relativeProj.chartHom 𝒮 V ''ᵁ
            AlgebraicGeometry.Proj.basicOpen ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e))
          ((V₃ y).ι ⁻¹ᵁ (𝕣 ⁻¹ᵁ (AlgebraicGeometry.Scheme.relativeProj.chartHom 𝒮 V ''ᵁ
            AlgebraicGeometry.Proj.basicOpen ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e)))) le_rfl)
          (((AlgebraicGeometry.Scheme.relativeProj.chartHom 𝒮 V).appIso
              (AlgebraicGeometry.Proj.basicOpen ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e))).inv
              (AlgebraicGeometry.Proj.awayToSection ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e)
                (HomogeneousLocalization.Away.mk ((𝒮).sectionsGrading V.1) (symChartGen_mem E V.1 e) 1
                  (symChartGen E V.1 e') hb)))
        rw [CommRingCat.comp_apply, ← AlgebraicGeometry.Scheme.Hom.appLE_eq_app] at h0
        rw [← h0, appLE_congr_hom_apply_07rm (hr y)
          (AlgebraicGeometry.Scheme.relativeProj.chartHom 𝒮 V ''ᵁ
            AlgebraicGeometry.Proj.basicOpen ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e))
          ((V₃ y).ι ⁻¹ᵁ (𝕣 ⁻¹ᵁ (AlgebraicGeometry.Scheme.relativeProj.chartHom 𝒮 V ''ᵁ
            AlgebraicGeometry.Proj.basicOpen ((𝒮).sectionsGrading V.1) (symChartGen E V.1 e)))) le_rfl (by rw [← hr y]; exact le_rfl)]
        exact AlgebraicGeometry.Scheme.Hom.comp_appLE_image_appIso_inv _ _ _ _ hle' _
      have hP2 := AlgebraicGeometry.Proj.fromOfGlobalSections_appLE_awayToSection_mk_mul
        ((𝒮).sectionsGrading V.1) (AlgebraicGeometry.Scheme.relativeProj.liftLocalRingHomAux 𝔇 (V₃ y).ι (et y) V.1 (hW y))
        (haveI : AlgebraicGeometry.IsAffine (V₃ y).toScheme := hV₃ y
         AlgebraicGeometry.Scheme.relativeProj.liftLocalRingHomAux_map_irrelevant 𝔇 (V₃ y).ι (et y) V (hW y))
        (symChartGen_mem E V.1 e) Nat.one_pos 1 hb hle'
      rw [pow_one] at hP2
      -- RHS: `Φ(π₁ e') = ι^♯(g) · Φ(π₁ e)` from `φ(e') = g • φ(e)` through the coordinate map
      have hR := congrArg (fun m => coordOn (V₃ y).ι M (et y) m
        (le_rfl : (V₃ y).ι ⁻¹ᵁ (𝕣 ⁻¹ᵁ symChart E V e) ≤ (V₃ y).ι ⁻¹ᵁ (𝕣 ⁻¹ᵁ symChart E V e))) he'
      rw [coordOn_smul, coordOn_res_left, coordOn_res_left,
        ← coordOn_res_right (V₃ y).ι M (et y) (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e') (hW y) le_top,
        ← coordOn_res_right (V₃ y).ι M (et y) (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e) (hW y) le_top,
        ← liftLocalRingHomAux_symChartGen f M E ψ hψ (V₃ y).ι (et y) V.1 (hW y) e',
        ← liftLocalRingHomAux_symChartGen f M E ψ hψ (V₃ y).ι (et y) V.1 (hW y) e] at hR
      -- cancel the unit `Φ(π₁ e)`
      exact hL.trans (hunit.mul_left_injective (hP2.trans hR))
  rw [hgen'] at hle
  exact RingHom.range_eq_top.1 (top_le_iff.1 hle)

/-- **Immersion criterion for `X → P(E)`** (Stacks 07RM paragraph 5 / 01O9 / 07RK): if every point has an affine
chart `(V, e)` on which `s = φ(e)` has affine frame locus `X_s` with `Γ(X_s, O)` generated over `Γ(V, O)` by the
ratios `φ(e')/s`, then `relativeProj.lift (Sym E) f M (liftDataOfEpi f E M ψ hψ)` is an immersion. -/
theorem isImmersion_lift_symGradedAlgebra_of_charts
    (hcharts : ∀ x : X, ∃ (V : S.affineOpens) (e : Γ(E, V.1)),
      x ∈ M.frameLocusOn (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e) ∧
      AlgebraicGeometry.IsAffineOpen (M.frameLocusOn (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e)) ∧
      Subring.closure
        (Set.range (f.appLE V.1 (M.frameLocusOn (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e))
          (M.frameLocusOn_le (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e))) ∪
        {g | ∃ e' : Γ(E, V.1),
          M.res (M.frameLocusOn_le (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e)) (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e') =
            g • M.res (M.frameLocusOn_le (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e)) (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e)}) = ⊤) :
    AlgebraicGeometry.IsImmersion
      (AlgebraicGeometry.Scheme.relativeProj.lift (AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E) f M
        (AlgebraicGeometry.Scheme.relativeProj.liftDataOfEpi f E M ψ hψ)) := by
  choose V e hmem haff hgen using hcharts
  refine AlgebraicGeometry.isImmersion_of_affine_charts _ (fun x => symChart E (V x) (e x)) ?_
    (fun x => isAffineOpen_symChart E (V x) (e x)) ?_ (fun x => surjective_appLE_symChart f M E ψ hψ (V x) (e x) (hgen x))
  · intro x
    refine ⟨x, ?_⟩
    have h := hmem x
    rw [← preimage_symChart_eq_frameLocusOn f M E ψ hψ (V x) (e x)] at h
    exact h
  · intro x
    rw [preimage_symChart_eq_frameLocusOn f M E ψ hψ (V x) (e x)]
    exact haff x

end AlgebraicGeometry.Scheme.relativeProj

end
