import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.ModulesTensorUnitIso
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.ProjectiveQuasiProjectiveProperSectionsFiniteType
import MiyaokaMori.AlgebraicGeometry.Morphisms.ProjectiveQuasiProjectiveProperSectionsGenerated
import MiyaokaMori.AlgebraicGeometry.Morphisms.QuasiProjectiveMorphism
import MiyaokaMori.AlgebraicGeometry.Modules.Ample.AmpleLineBundle
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.NonvanishingLocusIsoInvariant
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.GeneratedInDegreeOne
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.GradedQcAlgebraSectionsRing
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.GradedQuasicoherentAlgebra
import MiyaokaMori.AlgebraicGeometry.Morphisms.ProjectiveMorphism
import MiyaokaMori.AlgebraicGeometry.Proj.ProjectiveSpace.SerreTwistIsLineBundle
import MiyaokaMori.AlgebraicGeometry.Modules.Ample.IsAmpleOfIso
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.Stacks01mw
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.Stacks01nq
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.Stacks01nr
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.Stacks01o4
import MiyaokaMori.AlgebraicGeometry.Morphisms.Stacks01wc
import MiyaokaMori.AlgebraicGeometry.Modules.Ample.Stacks01pu

/-! # Projective morphisms are quasi-projective and proper

A projective morphism is quasi-projective and proper (Stacks Project, Tags 07RL and 01WC). The main theorem
`IsProjectiveMorphism.isQuasiProjective_isProper` is assembled from: properness (Tag 01WC, module
`Stacks01wc`); `O(1)` is invertible (Tag 01O4); the comparison of `O(1)|_{π⁻¹V}` with `O_{Proj A}(1)` is an
isomorphism (Tag 01NR); the nonvanishing locus of `x_f` is `D_+(f)` (Tag 01MW); `Γ(V, 𝒜)` is generated by
its degree-one part and is a finite-type `Γ(V, 𝒜)_0`-algebra.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000
set_option linter.style.haveILetI false

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- **Ampleness criterion for `O(1)` on `Proj`** (the ampleness form of Stacks Project, Tag 01MW (5)): if
`Proj 𝒜` is compact and covered by the basic opens `D_+(f)` of degree-one homogeneous elements `f ∈ 𝒜 1`,
then `O(1)` is ample. Proof: for every point choose `f ∈ 𝒜 1` with `x ∈ D_+(f)`; `f` gives a global section
`x_f ∈ Γ(O(1))` (`Proj.twistSection`) whose nonvanishing locus is exactly `D_+(f)` (Tag 01MW), and `D_+(f)`
is affine (Mathlib `Proj.isAffineOpen_basicOpen`); take `m = 1` in the definition of `IsAmple` and transport
along `O(1)^{⊗1} ≅ O(1)` (`unitTensorIso`). -/
theorem AlgebraicGeometry.Proj.twist_one_isAmple_of_iSup_basicOpen {σ A : Type u} [CommRing A]
    [SetLike σ A] [AddSubgroupClass σ A] (𝒜 : ℕ → σ) [GradedRing 𝒜]
    [CompactSpace (AlgebraicGeometry.Proj 𝒜)]
    (hcover : ⨆ f : 𝒜 1, AlgebraicGeometry.Proj.basicOpen 𝒜 (f : A) = ⊤)
    [(AlgebraicGeometry.Proj.twist 𝒜 1).IsLineBundle] :
    AlgebraicGeometry.IsAmple (AlgebraicGeometry.Proj.twist 𝒜 1) := by
  refine ⟨inferInstance, fun x => ?_⟩
  obtain ⟨f, hf⟩ := TopologicalSpace.Opens.mem_iSup.mp (hcover.ge (Set.mem_univ x))
  let L : (AlgebraicGeometry.Proj 𝒜).Modules := AlgebraicGeometry.Proj.twist 𝒜 1
  let e1 : AlgebraicGeometry.Scheme.Modules.tensorPow L 1 ≅ L := by
    change AlgebraicGeometry.Scheme.Modules.tensor
      (SheafOfModules.unit (AlgebraicGeometry.Proj 𝒜).ringCatSheaf) L ≅ L
    exact AlgebraicGeometry.Scheme.Modules.unitTensorIso L
  let s : Γ(L, ⊤) := AlgebraicGeometry.Proj.twistSection 𝒜 (f : A) f.2
  let s1 : Γ(AlgebraicGeometry.Scheme.Modules.tensorPow L 1, ⊤) := e1.inv.app ⊤ s
  have he1 : e1.hom.app ⊤ s1 = s := by
    dsimp only [s1]
    have hh := e1.inv_hom_id
    have hh' := congrArg (fun q => q.val.app (Opposite.op ⊤)) hh
    exact congrArg (fun q => q.hom s) hh'
  have hloc : L.nonvanishingLocus s = AlgebraicGeometry.Proj.basicOpen 𝒜 (f : A) := by
    ext y
    change y ∈ L.nonvanishingLocus s ↔ y ∈ AlgebraicGeometry.Proj.basicOpen 𝒜 (f : A)
    rw [AlgebraicGeometry.Scheme.Modules.mem_nonvanishingLocus]
    change ¬ IsZeroAt (AlgebraicGeometry.Proj.twistSection 𝒜 (f : A) f.2) y ↔ _
    exact AlgebraicGeometry.Proj.not_isZeroAt_twistSection_iff_of_iSup_basicOpen_eq_top 𝒜 (f : A) f.2 hcover y
  refine ⟨1, Nat.one_pos, s1, ?_, ?_⟩
  · rw [← AlgebraicGeometry.Scheme.Modules.mem_nonvanishingLocus_iso e1 s1 x, he1, hloc]
    exact hf
  · rw [← AlgebraicGeometry.Scheme.Modules.nonvanishingLocus_iso e1 s1, he1, hloc]
    exact AlgebraicGeometry.Proj.isAffineOpen_basicOpen 𝒜 (f : A) f.2 Nat.one_pos

/-- **`O(1)` on the relative `Proj` is ample over the preimage of every affine open `V ⊆ X`** (the core of
Stacks Project, Tag 07RL): `π⁻¹(V) ≅ Proj A` with `A = Γ(V, 𝒜)` (Tag 01NQ, `affineIso`), and `O(1)|_{π⁻¹V}`
corresponds to `O_{Proj A}(1)` (Tag 01NR, `twistAffineIso`). `A` is generated by `A_1`
(`adjoin_sectionsGrading_one_eq_top`), so the `D_+(f)` with `f ∈ A_1` cover `Proj A` (Mathlib
`Proj.iSup_basicOpen_eq_top'`); `A` is a finite-type `A_0`-algebra (`finiteType_sectionsRing`), so
`Proj A → Spec A_0` is quasi-compact (Mathlib) and `Proj A` is compact. Hence `O_{Proj A}(1)` is ample
(`twist_one_isAmple_of_iSup_basicOpen`), and ampleness is transported along the isomorphism
(`IsAmple.pullback_of_isClosedImmersion` applied to an isomorphism, `IsAmple.of_iso`). -/
theorem AlgebraicGeometry.Scheme.relativeProj.isAmple_twist_one_pullback_preimage_ι
    {X : AlgebraicGeometry.Scheme.{u}} (𝒜 : X.GradedQCAlgebra) (h𝒜 : 𝒜.GeneratedInDegreeOne)
    (hfin : (𝒜.part 1).IsFiniteType) [(AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1).IsLineBundle]
    (V : X.affineOpens) :
    AlgebraicGeometry.IsAmple
      ((AlgebraicGeometry.Scheme.Modules.pullback
        ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1).ι).obj
        (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1)) := by
  have hrange : Set.range (fun f : 𝒜.sectionsGrading V.1 1 => (f : 𝒜.sectionsRing V.1)) =
      ((𝒜.sectionsGrading V.1 1 : AddSubgroup (𝒜.sectionsRing V.1)) : Set (𝒜.sectionsRing V.1)) :=
    Subtype.range_coe
  have hcover : ⨆ f : 𝒜.sectionsGrading V.1 1,
      AlgebraicGeometry.Proj.basicOpen (𝒜.sectionsGrading V.1) (f : 𝒜.sectionsRing V.1) = ⊤ := by
    apply AlgebraicGeometry.Proj.iSup_basicOpen_eq_top' (𝒜.sectionsGrading V.1)
      (fun f : 𝒜.sectionsGrading V.1 1 => (f : 𝒜.sectionsRing V.1)) (fun f => ⟨1, f.2⟩)
    rw [hrange]
    exact 𝒜.adjoin_sectionsGrading_one_eq_top h𝒜 V
  haveI : Algebra.FiniteType (𝒜.sectionsGrading V.1 0) (𝒜.sectionsRing V.1) :=
    𝒜.finiteType_sectionsRing h𝒜 hfin V
  haveI : CompactSpace (AlgebraicGeometry.Proj (𝒜.sectionsGrading V.1)) :=
    AlgebraicGeometry.QuasiCompact.compactSpace_of_compactSpace
      (AlgebraicGeometry.Proj.toSpecZero (𝒜.sectionsGrading V.1))
  haveI : (AlgebraicGeometry.Proj.twist (𝒜.sectionsGrading V.1) 1).IsLineBundle :=
    AlgebraicGeometry.Proj.twist_isLineBundle (𝒜.sectionsGrading V.1)
      (fun f : 𝒜.sectionsGrading V.1 1 => (f : 𝒜.sectionsRing V.1)) (fun f => f.2) hcover 1
  have h1 : AlgebraicGeometry.IsAmple (AlgebraicGeometry.Proj.twist (𝒜.sectionsGrading V.1) 1) :=
    AlgebraicGeometry.Proj.twist_one_isAmple_of_iSup_basicOpen (𝒜.sectionsGrading V.1) hcover
  have h2 := AlgebraicGeometry.IsAmple.pullback_of_isClosedImmersion
    (AlgebraicGeometry.Scheme.relativeProj.affineIso 𝒜 V).hom _ h1
  have h3 : AlgebraicGeometry.IsAmple
      ((AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1).restrict
        ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1).ι) :=
    AlgebraicGeometry.IsAmple.of_iso (AlgebraicGeometry.Scheme.relativeProj.twistAffineIso 𝒜 V 1).symm h2
  exact AlgebraicGeometry.IsAmple.of_iso
    ((AlgebraicGeometry.Scheme.Modules.restrictFunctorIsoPullback
      ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1).ι).app
      (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1)) h3

/-- **A projective morphism is quasi-projective and proper** (Stacks Project, Tags 07RL and 01WC).
Properness is Tag 01WC (`IsProjectiveMorphism.isProper`). Quasi-projectivity: take the closed immersion
`i : X ⟶ Proj_S 𝒜` from the definition and `L := i^* O(1)` (invertible by Tag 01O4); for an affine open `V`
of the base, `f⁻¹V = i⁻¹(π⁻¹V)` and `L|_{f⁻¹V} ≅ (i|_{π⁻¹V})^* (O(1)|_{π⁻¹V})` (Mathlib `pullbackComp`,
`morphismRestrict_ι`); `O(1)|_{π⁻¹V}` is ample (`isAmple_twist_one_pullback_preimage_ι`) and stays ample
under pullback along the closed immersion `i|_{π⁻¹V}` (Tag 01PU). Finite type and quasi-compactness follow
from properness. -/
theorem AlgebraicGeometry.IsProjectiveMorphism.isQuasiProjective_isProper {X S : AlgebraicGeometry.Scheme.{u}}
    (f : X ⟶ S) [AlgebraicGeometry.IsProjectiveMorphism f] :
    AlgebraicGeometry.IsQuasiProjectiveMorphism f ∧ AlgebraicGeometry.IsProper f := by
  haveI hproper : AlgebraicGeometry.IsProper f := AlgebraicGeometry.IsProjectiveMorphism.isProper f
  refine ⟨?_, hproper⟩
  obtain ⟨𝒜, i, h𝒜, hfin, hi, hif⟩ :=
    (‹AlgebraicGeometry.IsProjectiveMorphism f›).exists_closed_immersion
  subst hif
  haveI : (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1).IsLineBundle :=
    (AlgebraicGeometry.Scheme.relativeProj.twist_one_universalQuotient 𝒜 h𝒜).1 1
  refine ⟨inferInstance, inferInstance,
    ⟨(AlgebraicGeometry.Scheme.Modules.pullback i).obj (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1),
      inferInstance, fun V => ?_⟩⟩
  have hamp := AlgebraicGeometry.Scheme.relativeProj.isAmple_twist_one_pullback_preimage_ι 𝒜 h𝒜 hfin V
  haveI hL1 : ((AlgebraicGeometry.Scheme.Modules.pullback
      ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1).ι).obj
        (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1)).IsLineBundle :=
    AlgebraicGeometry.Scheme.Modules.IsLineBundle.pullback _ _
  haveI hL2 : ((AlgebraicGeometry.Scheme.Modules.pullback
      (i ∣_ ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1))).obj
        ((AlgebraicGeometry.Scheme.Modules.pullback
          ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1).ι).obj
          (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1))).IsLineBundle :=
    AlgebraicGeometry.Scheme.Modules.IsLineBundle.pullback _ _
  have hamp' := AlgebraicGeometry.IsAmple.pullback_of_isClosedImmersion
    (i ∣_ ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1)) _ hamp
  haveI hL3 : ((AlgebraicGeometry.Scheme.Modules.pullback
      ((i ≫ (AlgebraicGeometry.Scheme.relativeProj 𝒜).hom) ⁻¹ᵁ V.1).ι).obj
        ((AlgebraicGeometry.Scheme.Modules.pullback i).obj
          (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1))).IsLineBundle :=
    AlgebraicGeometry.Scheme.Modules.IsLineBundle.pullback _ _
  have e : (AlgebraicGeometry.Scheme.Modules.pullback
        (i ∣_ ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1))).obj
        ((AlgebraicGeometry.Scheme.Modules.pullback
          ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1).ι).obj
          (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1)) ≅
      (AlgebraicGeometry.Scheme.Modules.pullback
        ((i ≫ (AlgebraicGeometry.Scheme.relativeProj 𝒜).hom) ⁻¹ᵁ V.1).ι).obj
        ((AlgebraicGeometry.Scheme.Modules.pullback i).obj
          (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1)) :=
    ((AlgebraicGeometry.Scheme.Modules.pullbackComp
        (i ∣_ ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1))
        ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1).ι).app
        (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1)) ≪≫
    ((AlgebraicGeometry.Scheme.Modules.pullbackCongr
        (AlgebraicGeometry.morphismRestrict_ι i ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1))).app
        (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1)) ≪≫
    ((AlgebraicGeometry.Scheme.Modules.pullbackComp
        (i ⁻¹ᵁ ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1)).ι i).app
        (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1)).symm
  exact @AlgebraicGeometry.IsAmple.of_iso _ _ _ hL2 hL3 e hamp'

end
