import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Proj.ProjectiveSpace.ProjectiveSpaceOver
import MiyaokaMori.AlgebraicGeometry.Morphisms.ProjectiveMorphism
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.ProjMapClosedImmersionOfSurjective
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.Stacks01nq
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.SectionsRingGeneratedInDegreeOne
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.Stacks01pbAffineOpen
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.OfGradedQCAlgebra
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.ProjMapToSpecZero

/-! # A projective morphism is affine-locally a closed subscheme of projective space

A projective morphism (`IsProjectiveMorphism`: closed immersion into the relative Proj of a graded
quasi-coherent algebra generated in degree one with finite-type degree-one part) is, over every affine open
`V ⊆ S`, a closed subscheme of a projective space over the ring `Γ(S, V)`:
`f⁻¹V ↪ P^n_{Γ(S,V)}`, compatibly with `f⁻¹V → V ≅ Spec Γ(S, V)`.

This is the reduction step of Stacks 02O4 (proof, first paragraph: "we may assume `S = Spec R` affine and
`X` a closed subscheme of `P^n_R`"), i.e. Stacks 01WB/01W8 ("locally projective ⇒ locally H-projective")
specialised to this project's `IsProjectiveMorphism`.

The file is organised as three reusable steps followed by the leaf:
* Step A (`Proj.exists_closedImmersion_projectiveSpaceOver_of_generated`): a graded ring generated in
  positive degrees by finitely many degree-one elements over a coefficient ring `A → 𝒜_0` has `Proj 𝒜` a
  closed subscheme of `P^n_A` over `Spec A` (Stacks 01MZ, Hartshorne II Ex. 3.12(a));
* Step B (`GradedQCAlgebra.exists_finset_degOne_mem_closure_of_generatedInDegreeOne`): the section ring of a
  graded quasi-coherent algebra generated in degree one, with `S_1` of finite type, over an affine open,
  satisfies the hypothesis of Step A (Stacks 01O4 + 01PB);
* Step C (`relativeProj.affineIso_hom_toSpecZero_sectionsUnit`): base compatibility of the affine chart
  `π⁻¹V ≅ Proj S(V)` of the relative Proj (Stacks 01NQ);
* the leaf `IsProjectiveMorphism.exists_closedImmersion_projectiveSpaceOver` assembles them.

Source: Stacks 01WB, 01W8 (Morphisms, projective morphisms); Stacks 01O4/01NQ (affine-local description of the
relative Proj); Hartshorne II Ex. 3.12(a) (surjective graded homomorphisms give closed immersions of Proj).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

-- `MvPolynomial.gradedAlgebra` is not a global instance in Mathlib (cf. `ProjectiveSpaceOver.lean`).
attribute [local instance] MvPolynomial.gradedAlgebra

/-! ## Step A: `Proj` of a graded ring generated in positive degrees by finitely many degree-one
elements over a coefficient ring is a closed subscheme of projective space over that ring -/

namespace AlgebraicGeometry.Proj

variable {A B : Type u} [CommRing A] [CommRing B] (𝒜 : ℕ → AddSubgroup B) [GradedRing 𝒜]

/-- The coefficient map `A → 𝒜_0 ⊆ B` (same as `Proj.coeffHom` in
`ProjToSpecProperOfGenerated.lean`, kept private to avoid the import). -/
private def coeffHom' (φ : A →+* 𝒜 0) : A →+* B where
  toFun a := (φ a : B)
  map_one' := by rw [map_one]; rfl
  map_mul' a b := by rw [map_mul]; rfl
  map_zero' := by rw [map_zero]; rfl
  map_add' a b := by rw [map_add]; rfl

/-- **Stacks 01MZ / Hartshorne II Ex. 3.12(a), packaged.** Let `𝒜` be a graded ring, `φ : A → 𝒜_0` a
ring homomorphism and `s ⊆ 𝒜_1` a finite set such that every element of positive degree lies in the
subring generated by `φ(A)` and `s`. Then there are `n` and a closed immersion `j : Proj 𝒜 → P^n_A`
over `Spec A` (`ProjectiveSpaceOver n A`), i.e.
`j ≫ toSpecBase = toSpecZero ≫ Spec φ`.

Proof (the construction of `Proj.isProper_toSpecZero_comp_of_generated`, `ProjToSpecProperOfGenerated.lean`,
with the closed immersion kept instead of being used for properness): with `n := #s`, the graded
`A`-algebra map `ψ : A[T_0, …, T_n] → 𝒜`, `T_0 ↦ 0`, `T_{i+1} ↦ s_i`, `A → 𝒜_0` via `φ`, is graded
(homogeneous degree-`d` monomials go to `𝒜_d`) and surjective in every positive degree (the degree-`d`
component of `ψ(p)` is `ψ(p_d)`, `GradedRingHom.map_directSumDecompose`); hence `Proj.map ψ` is a closed
immersion (`Proj.isClosedImmersion_map`) and
`Proj.map ψ ≫ toSpecZero = toSpecZero ≫ Spec ψ_0` (`AlgebraicGeometry.Proj.proj_map_toSpecZero`) with
`ψ_0 ∘ (A → A[T]_0) = φ`. -/
theorem exists_closedImmersion_projectiveSpaceOver_of_generated (φ : A →+* 𝒜 0) (s : Finset B)
    (hs : ∀ x ∈ s, x ∈ 𝒜 1)
    (hgen : ∀ n, 0 < n → ∀ x ∈ 𝒜 n,
      x ∈ Subring.closure (Set.range (fun a : A => ((φ a : 𝒜 0) : B)) ∪ (↑s : Set B))) :
    ∃ (n : ℕ) (j : Proj 𝒜 ⟶ ProjectiveSpaceOver n A),
      IsClosedImmersion j ∧
        j ≫ ProjectiveSpaceOver.toSpecBase n A =
          Proj.toSpecZero 𝒜 ≫ Spec.map (CommRingCat.ofHom φ) := by
  classical
  -- the variables: `T_0 ↦ 0`, `T_{i+1} ↦ i`-th element of `s`
  set N := s.card with hN
  let v : Fin (N + 1) → B := Fin.cases 0 (fun i => ((s.equivFin.symm i : B)))
  have hv : ∀ i, v i ∈ 𝒜 1 := by
    intro i
    refine Fin.cases ?_ (fun j => ?_) i
    · exact zero_mem _
    · exact hs _ (s.equivFin.symm j).2
  have hsv : (↑s : Set B) ⊆ Set.range v := by
    intro x hx
    refine ⟨Fin.succ (s.equivFin ⟨x, hx⟩), ?_⟩
    simp [v]
  let φ' : A →+* B := coeffHom' 𝒜 φ
  let ψ0 : MvPolynomial (Fin (N + 1)) A →+* B := MvPolynomial.eval₂Hom φ' v
  -- `ψ0` is graded
  have hψ0 : ∀ (n : ℕ) (p : MvPolynomial (Fin (N + 1)) A),
      p ∈ MvPolynomial.homogeneousSubmodule (Fin (N + 1)) A n → ψ0 p ∈ 𝒜 n := by
    intro n p hp
    have hp' : p.IsHomogeneous n := hp
    have hsum : ψ0 p = ∑ d ∈ p.support, ψ0 (MvPolynomial.monomial d (MvPolynomial.coeff d p)) := by
      conv_lhs => rw [MvPolynomial.as_sum p]
      rw [map_sum]
    rw [hsum]
    refine sum_mem fun d hd => ?_
    rw [MvPolynomial.eval₂Hom_monomial]
    have h1 : φ' (MvPolynomial.coeff d p) ∈ 𝒜 0 := (φ _).2
    have hw : (∑ i ∈ d.support, d i • (1 : ℕ)) = n := by
      have := hp' (MvPolynomial.mem_support_iff.mp hd)
      rw [Finsupp.weight_apply] at this
      simpa [Finsupp.sum, Pi.one_apply] using this
    have h2 : (d.prod fun i k => v i ^ k) ∈ 𝒜 n := by
      rw [Finsupp.prod, ← hw]
      exact SetLike.prod_pow_mem_graded 𝒜 (fun _ => 1) v (fun i => d i) (fun i _ => hv i)
    rw [← zero_add n]
    exact SetLike.mul_mem_graded h1 h2
  let ψ : MvPolynomial.homogeneousSubmodule (Fin (N + 1)) A →+*ᵍ 𝒜 :=
    { toRingHom := ψ0, map_mem := fun {n} {p} hp => hψ0 n p hp }
  have hψC : ∀ a : A, ψ (MvPolynomial.C a) = (φ a : B) := fun a =>
    MvPolynomial.eval₂Hom_C φ' v a
  have hψX : ∀ i, ψ (MvPolynomial.X i) = v i := fun i => MvPolynomial.eval₂Hom_X' φ' v i
  -- surjective in positive degrees
  have hsurj : ∀ n, 0 < n → ∀ y ∈ 𝒜 n,
      ∃ p ∈ MvPolynomial.homogeneousSubmodule (Fin (N + 1)) A n, ψ p = y := by
    intro n hn y hy
    have hle : Subring.closure (Set.range (fun a : A => ((φ a : 𝒜 0) : B)) ∪ (↑s : Set B)) ≤
        ψ0.range := by
      rw [Subring.closure_le]
      rintro x (⟨a, rfl⟩ | hx)
      · exact RingHom.mem_range.mpr ⟨MvPolynomial.C a, hψC a⟩
      · obtain ⟨i, rfl⟩ := hsv hx
        exact RingHom.mem_range.mpr ⟨MvPolynomial.X i, hψX i⟩
    obtain ⟨p, hp⟩ := RingHom.mem_range.mp (hle (hgen n hn y hy))
    refine ⟨(DirectSum.decompose (MvPolynomial.homogeneousSubmodule (Fin (N + 1)) A) p n :
      MvPolynomial (Fin (N + 1)) A), SetLike.coe_mem _, ?_⟩
    rw [GradedRingHom.map_directSumDecompose]
    change (DirectSum.decompose 𝒜 (ψ0 p) n : B) = y
    rw [hp]
    exact DirectSum.decompose_of_mem_same 𝒜 hy
  -- the irrelevant-ideal condition for `Proj.map`
  have hψ : HomogeneousIdeal.irrelevant 𝒜 ≤
      (HomogeneousIdeal.irrelevant (MvPolynomial.homogeneousSubmodule (Fin (N + 1)) A)).map ψ := by
    rw [HomogeneousIdeal.irrelevant_le]
    intro d hd y hy
    obtain ⟨p, hp, rfl⟩ := hsurj d hd y hy
    show ψ p ∈ Ideal.map ψ
      (HomogeneousIdeal.irrelevant (MvPolynomial.homogeneousSubmodule (Fin (N + 1)) A)).toIdeal
    exact Ideal.mem_map_of_mem _ (HomogeneousIdeal.mem_irrelevant_of_mem _ hd hp)
  refine ⟨N, Proj.map ψ hψ, isClosedImmersion_map ψ hψ hsurj, ?_⟩
  show Proj.map ψ hψ ≫ (Proj.toSpecZero (MvPolynomial.homogeneousSubmodule (Fin (N + 1)) A) ≫
      Spec.map (CommRingCat.ofHom
        (algebraMap A (MvPolynomial.homogeneousSubmodule (Fin (N + 1)) A 0)))) =
      Proj.toSpecZero 𝒜 ≫ Spec.map (CommRingCat.ofHom φ)
  rw [← Category.assoc, AlgebraicGeometry.Proj.proj_map_toSpecZero ψ hψ, Category.assoc, ← Spec.map_comp]
  congr 2
  refine CommRingCat.hom_ext (RingHom.ext fun a => Subtype.ext ?_)
  exact hψC a

end AlgebraicGeometry.Proj

/-! ## Step B: the section ring of a graded quasi-coherent algebra generated in degree one, over an
affine open, is generated in positive degrees by finitely many degree-one elements over the base -/

/-- **Degree induction (pure algebra).** Let `𝒜` be a grading of a commutative ring `A` with
`𝒜₊ ⊆ (𝒜_1)` and let `C` be a subring containing `𝒜_1`. Then `C` contains every element of positive
degree. (Variant of `GradedRing.adjoin_one_eq_top_of_irrelevant_le_span_one`,
`ProjectiveQuasiProjectiveProperSectionsGenerated.lean`, where the base case is degree `1` instead of
degree `0`, so that no degree-`0` element is required to lie in `C`.)

Proof: induction on `k` for `𝒜_{k+1} ⊆ C`. `k = 0` is the hypothesis. For `x ∈ 𝒜_{k+2} ⊆ 𝒜₊ ⊆ (𝒜_1)`,
`Submodule.span_induction` shows `∀ a, (a * x)_{k+2} ∈ C`: on a generator `b ∈ 𝒜_1`,
`(a * b)_{k+2} = a_{k+1} * b` (`DirectSum.coe_decompose_mul_of_right_mem_of_le`) with `a_{k+1} ∈ C` by
induction and `b ∈ C`; `0`, `+`, `•` are additivity of `decompose`. Take `a = 1`
(`DirectSum.decompose_of_mem_same`). -/
theorem GradedRing.mem_subring_of_pos_of_irrelevant_le_span_one
    {A : Type*} [CommRing A] (𝒜 : ℕ → AddSubgroup A) [GradedRing 𝒜] (C : Subring A)
    (h1 : ∀ x ∈ 𝒜 1, x ∈ C)
    (h : (HomogeneousIdeal.irrelevant 𝒜).toIdeal ≤ Ideal.span ((𝒜 1 : AddSubgroup A) : Set A)) :
    ∀ n, 0 < n → ∀ x ∈ 𝒜 n, x ∈ C := by
  have key : ∀ k : ℕ, ∀ x ∈ 𝒜 (k + 1), x ∈ C := by
    intro k
    induction k with
    | zero => exact h1
    | succ k ih =>
      intro x hx
      have hx' : x ∈ Ideal.span ((𝒜 1 : AddSubgroup A) : Set A) :=
        h (HomogeneousIdeal.mem_irrelevant_of_mem 𝒜 (Nat.succ_pos _) hx)
      have hP : ∀ a : A, (DirectSum.decompose 𝒜 (a * x) (k + 1 + 1) : A) ∈ C := by
        refine Submodule.span_induction
          (p := fun y _ => ∀ a : A, (DirectSum.decompose 𝒜 (a * y) (k + 1 + 1) : A) ∈ C)
          ?_ ?_ ?_ ?_ hx'
        · intro b hb a
          rw [DirectSum.coe_decompose_mul_of_right_mem_of_le 𝒜 hb (Nat.le_add_left 1 (k + 1)),
            Nat.add_sub_cancel]
          exact C.mul_mem (ih _ (SetLike.coe_mem _)) (h1 b hb)
        · intro a
          rw [mul_zero, DirectSum.decompose_zero, DirectSum.zero_apply, ZeroMemClass.coe_zero]
          exact C.zero_mem
        · intro y z _ _ hy hz a
          rw [mul_add, DirectSum.decompose_add, DirectSum.add_apply, AddMemClass.coe_add]
          exact C.add_mem (hy a) (hz a)
        · intro c y _ hy a
          rw [smul_eq_mul, ← mul_assoc]
          exact hy (a * c)
      have h1' := hP 1
      rwa [one_mul, DirectSum.decompose_of_mem_same 𝒜 hx] at h1'
  intro n hn x hx
  obtain ⟨k, rfl⟩ : ∃ k, n = k + 1 := ⟨n - 1, by omega⟩
  exact key k x hx

namespace AlgebraicGeometry.Scheme.GradedQCAlgebra

variable {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra)

/-- The section ring `B := S(V) = ⊕_m Γ(V, S_m)` of a graded quasi-coherent algebra generated in degree
one with `S_1` of finite type, over an affine open `V`, is generated in positive degrees by finitely many
degree-one elements over the structure map `Γ(X, V) → B_0`: there is a finite `s ⊆ B_1` such that every
element of positive degree lies in the subring generated by `sectionsUnitHom V (Γ(X,V))` and `s`.

Proof. `Γ(V, S_1)` is a finite `Γ(X,V)`-module (Stacks 01PB, `Modules.finite_sections_of_isFiniteType`);
take generators `t` and `s := ofPiece V 1 '' t ⊆ B_1`. Every `x ∈ B_1` is `ofPiece V 1 a`, and
`a ∈ span t`, so `x` lies in the closure `C` by `Submodule.span_induction`
(`ofPiece (r • a) = sectionsUnitHom r * ofPiece a`, `sectionsUnitHom_mul_ofPiece`). Positive degrees
follow from `B₊ ⊆ (B_1)` (`irrelevant_le_span_degOne_of_generatedInDegreeOne`) by degree induction
(`GradedRing.mem_subring_of_pos_of_irrelevant_le_span_one`). -/
theorem exists_finset_degOne_mem_closure_of_generatedInDegreeOne (hS : S.GeneratedInDegreeOne)
    [hft : (S.part 1).IsFiniteType] (V : X.affineOpens) :
    ∃ s : Finset (S.sectionsRing V.1), (∀ x ∈ s, x ∈ S.sectionsGrading V.1 1) ∧
      ∀ n, 0 < n → ∀ x ∈ S.sectionsGrading V.1 n,
        x ∈ Subring.closure
          (Set.range (S.sectionsUnitHom V.1) ∪ (↑s : Set (S.sectionsRing V.1))) := by
  classical
  have := S.quasicoherent 1
  have hfin : Module.Finite Γ(X, V.1) Γ(S.part 1, V.1) :=
    AlgebraicGeometry.Scheme.Modules.finite_sections_of_isFiniteType (S.part 1) V.2
  obtain ⟨t, ht⟩ := hfin.fg_top
  refine ⟨t.image (S.ofPiece V.1 1), ?_, ?_⟩
  · intro x hx
    obtain ⟨a, -, rfl⟩ := Finset.mem_image.mp hx
    exact ⟨a, rfl⟩
  set C := Subring.closure
    (Set.range (S.sectionsUnitHom V.1) ∪ (↑(t.image (S.ofPiece V.1 1)) : Set (S.sectionsRing V.1)))
    with hC
  have hunit : ∀ r, S.sectionsUnitHom V.1 r ∈ C := fun r =>
    Subring.subset_closure (Or.inl ⟨r, rfl⟩)
  have hpiece : ∀ a : Γ(S.part 1, V.1), S.ofPiece V.1 1 a ∈ C := by
    intro a
    have ha : a ∈ Submodule.span Γ(X, V.1) (↑t : Set Γ(S.part 1, V.1)) := by
      rw [ht]; trivial
    refine Submodule.span_induction
      (p := fun (a : Γ(S.part 1, V.1)) _ => S.ofPiece V.1 1 a ∈ C) ?_ ?_ ?_ ?_ ha
    · intro a hat
      exact Subring.subset_closure
        (Or.inr (Finset.mem_coe.mpr (Finset.mem_image_of_mem (S.ofPiece V.1 1) hat)))
    · have e : S.ofPiece V.1 1 (0 : Γ(S.part 1, V.1)) = 0 :=
        map_zero (DirectSum.of (S.sectionsPiece V.1) 1)
      exact Eq.mpr (congrArg (fun x => x ∈ C) e) C.zero_mem
    · intro a b _ _ ha hb
      have e : S.ofPiece V.1 1 (a + b) = S.ofPiece V.1 1 a + S.ofPiece V.1 1 b :=
        map_add (DirectSum.of (S.sectionsPiece V.1) 1) a b
      rw [e]
      exact C.add_mem ha hb
    · intro r a _ ha
      have e := S.sectionsUnitHom_mul_ofPiece V.1 r a
      rw [← e]
      exact C.mul_mem (hunit r) ha
  have hdeg1 : ∀ x ∈ S.sectionsGrading V.1 1, x ∈ C := by
    rintro x ⟨a, rfl⟩
    exact hpiece a
  exact GradedRing.mem_subring_of_pos_of_irrelevant_le_span_one (S.sectionsGrading V.1) C hdeg1
    (S.irrelevant_le_span_degOne_of_generatedInDegreeOne hS V)

end AlgebraicGeometry.Scheme.GradedQCAlgebra

/-! ## Step C: base compatibility of the affine chart of the relative Proj -/

/-- The affine chart `π⁻¹V ≅ Proj S(V)` of the relative Proj (`relativeProj.affineIso`, Stacks 01NQ)
is compatible with the structure maps to `Spec Γ(X, V)`:
`affineIso.hom ≫ toSpecZero ≫ Spec (Γ(X,V) → S(V)_0) = (π ∣_ V) ≫ isoSpec.hom`.

Proof: `affineIso.inv ≫ π⁻¹V.ι = projChart V` (`affineIso_inv_ι`), `projChart V ≫ π = projToOpen V ≫ V.ι`
(`projChart_hom`) and `(π ∣_ V) ≫ V.ι = π⁻¹V.ι ≫ π` (`morphismRestrict_ι`); cancel the monomorphism
`V.ι` to get `affineIso.inv ≫ (π ∣_ V) = projToOpen V = toSpecZero ≫ Spec unitZero ≫ isoSpec.inv`
(definition of `projToOpen`), and `unitZero = sectionsUnit V` for `S.toGradedAffineAlgebra`. -/
theorem AlgebraicGeometry.Scheme.relativeProj.affineIso_hom_toSpecZero_sectionsUnit
    {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra) (V : X.affineOpens) :
    (AlgebraicGeometry.Scheme.relativeProj.affineIso S V).hom ≫
        AlgebraicGeometry.Proj.toSpecZero (S.sectionsGrading V.1) ≫
          AlgebraicGeometry.Spec.map (CommRingCat.ofHom (S.sectionsUnit V.1)) =
      ((AlgebraicGeometry.Scheme.relativeProj S).hom ∣_ V.1) ≫ V.2.isoSpec.hom := by
  -- `projToOpen ⟨V.1, V.2⟩`, retyped with the spelling `Proj (S.sectionsGrading V.1)` (definitional)
  obtain ⟨P, hP⟩ : ∃ P : AlgebraicGeometry.Proj (S.sectionsGrading V.1) ⟶ V.1.toScheme,
      P = S.toGradedAffineAlgebra.projToOpen ⟨V.1, V.2⟩ := ⟨_, rfl⟩
  have h : (AlgebraicGeometry.Scheme.relativeProj.affineIso S V).inv ≫
      ((AlgebraicGeometry.Scheme.relativeProj S).hom ∣_ V.1) = P := by
    rw [hP]
    apply (cancel_mono V.1.ι).mp
    rw [Category.assoc, morphismRestrict_ι, ← Category.assoc,
      AlgebraicGeometry.Scheme.relativeProj.affineIso_inv_ι]
    exact S.toGradedAffineAlgebra.projChart_hom ⟨V.1, V.2⟩
  have h2 : P ≫ V.2.isoSpec.hom =
      AlgebraicGeometry.Proj.toSpecZero (S.sectionsGrading V.1) ≫
        AlgebraicGeometry.Spec.map (CommRingCat.ofHom (S.sectionsUnit V.1)) := by
    rw [hP]
    show (AlgebraicGeometry.Proj.toSpecZero (S.sectionsGrading V.1) ≫
      AlgebraicGeometry.Spec.map
        (CommRingCat.ofHom (S.toGradedAffineAlgebra.unitZero ⟨V.1, V.2⟩)) ≫ V.2.isoSpec.inv) ≫
      V.2.isoSpec.hom = _
    rw [Category.assoc, Category.assoc, Iso.inv_hom_id, Category.comp_id]
    rfl
  rw [Iso.inv_comp_eq] at h
  rw [h, Category.assoc, h2]


/-- **Affine-local closed immersion into projective space** (Stacks 02O4 proof, reduction step;
Stacks 01WB). `f : X → S` projective (`IsProjectiveMorphism`), `V ⊆ S` affine open, `R := Γ(S, V)`. Then there
are `n` and a closed immersion `j : f⁻¹V → P^n_R` (`ProjectiveSpaceOver n R`) over `Spec R`:
`j ≫ ProjectiveSpaceOver.toSpecBase n R = (f ∣_ V) ≫ isoSpec`, where
`f ∣_ V : f⁻¹V → V` is Mathlib's `morphismRestrict` and `isoSpec : V ≅ Spec Γ(S, V)` is
`IsAffineOpen.isoSpec`.

**Proof.**
1. Unfold `IsProjectiveMorphism f`: a graded quasi-coherent `O_S`-algebra
   `𝒜` (`GradedQCAlgebra`), generated in degree one (`𝒜.GeneratedInDegreeOne`) with `𝒜_1` of finite type,
   a closed immersion `i : X → Proj_S 𝒜 = (relativeProj 𝒜).left` and `f = i ≫ π`, `π := (relativeProj 𝒜).hom`.
2. Affine-local chart of the relative Proj (Stacks 01NQ): `W := π⁻¹V ≅ Proj B`
   (`AlgebraicGeometry.Scheme.relativeProj.affineIso 𝒜 V`), where `B := 𝒜.sectionsRing V = ⊕_m Γ(V, 𝒜_m)`
   is graded by `𝒜.sectionsGrading V` and `B_0` receives the structure map `unitZero : R → B_0`
   (`OfGradedQCAlgebra.lean`, `toGradedAffineAlgebra`). Its base compatibility: with
   `projToOpen V := toSpecZero ≫ Spec.map unitZero ≫ isoSpec.inv : Proj B → V`, `projChart V ≫ π = projToOpen V ≫ V.ι` (`projChart_hom`) and
   `affineIso.inv ≫ W.ι = projChart V` (`relativeProj.affineIso_inv_ι`), so, `V.ι` being a monomorphism
   and `(π ∣_ V) ≫ V.ι = W.ι ≫ π` (Mathlib `morphismRestrict_ι`), `affineIso.hom ≫ projToOpen V = π ∣_ V`.
3. `f ∣_ V = (i ∣_ W) ≫ (π ∣_ V)` (Mathlib `morphismRestrict_comp`; the source `(i ≫ π)⁻¹V` is
   `i⁻¹(π⁻¹V)` by definition), and `i ∣_ W` is a closed immersion (closed immersions are local on the
   target; Mathlib instance `IsClosedImmersion (i ∣_ W)`).
4. Generators. `B_1 = Γ(V, 𝒜_1)` is a finite `R`-module (`V` affine, `𝒜_1` quasi-coherent of finite type:
   Stacks 01PB, `AlgebraicGeometry.Scheme.Modules.finite_sections_of_isFiniteType`);
   pick generators `x_0, …, x_n ∈ B_1`. `B` is generated as an `R`-algebra by `B_1`
   (`GradedQCAlgebra.adjoin_sectionsGrading_one_eq_top`, with the `R`-algebra structure
   `sectionsAlgebraBC`, `RelativeProjBaseChangeAlgebra.lean`), so the graded
   `R`-algebra homomorphism `φ : R[T_0, …, T_n] → B`, `T_k ↦ x_k`, is surjective onto `B_d` for every
   `d ≥ 1` (induction on `d`: `B_{d+1} = B_1 · B_d`, i.e. `B_d` is the `R`-span of the degree-`d`
   monomials in the `x_k`). In degree `0` it is `unitZero : R → B_0`, which need not be surjective.
5. `Proj.map φ : Proj B → Proj R[T] = P^n_R` (Mathlib `AlgebraicGeometry.Proj.map`; the required
   inclusion of irrelevant ideals holds because `B_+` is generated by the `x_k = φ(T_k)`) is a closed
   immersion (Hartshorne II Ex. 3.12(a); EGA II 3.6.2): being a closed immersion is local on the target
   (Mathlib `IsZariskiLocalAtTarget`), `P^n_R = ⋃ D_+(T_k)`, the preimage of `D_+(T_k)` is `D_+(x_k)`
   (Mathlib `Proj.ι_comp_map`), and on these charts the map is `Spec` of
   `R[T]_{(T_k)} = R[T_l/T_k] → B_{(x_k)}`, which is surjective because every element of `B_{(x_k)}` is
   `b / x_k^d` with `b ∈ B_d`, `d ≥ 1`, a polynomial in the `x_l` with coefficients in `R`; `Spec` of a
   surjection is a closed immersion (Mathlib `IsClosedImmersion.spec_of_surjective`). The degree-zero
   defect of step 4 is invisible here: `Proj` only sees positive degrees.
6. Base compatibility of `Proj.map`: `Proj.map φ ≫ toSpecZero_{R[T]} = toSpecZero_B ≫ Spec.map φ_0`
   (`φ` restricted to degree `0`; Mathlib has `Proj.awayι_toSpecZero`, the identity on the charts
   `D_+(T_k)`; the global statement follows since the charts cover — this project has the analogous
   `ProjCongrGrading.map_congrGradingHom_toSpecZero`), and `φ_0 ∘ (R → R[T]_0) = unitZero` (both are the
   structure map of the `R`-algebra `B` in degree `0`; `algebraMap_eq_sectionsUnitHom`).
7. Put `j := (i ∣_ W) ≫ affineIso.hom ≫ Proj.map φ`. It is a closed immersion (steps 3, 5; closed
   immersions are stable under composition and `affineIso.hom` is an isomorphism), and
   `j ≫ toSpec = (i ∣_ W) ≫ affineIso.hom ≫ toSpecZero_B ≫ Spec.map unitZero`
   `= (i ∣_ W) ≫ affineIso.hom ≫ projToOpen V ≫ isoSpec.hom = (i ∣_ W) ≫ (π ∣_ V) ≫ isoSpec.hom`
   `= (f ∣_ V) ≫ isoSpec.hom` by steps 6, 2, 3.

**Formalization.** Step 5 is `Proj.isClosedImmersion_map`,
step 6 is `AlgebraicGeometry.Proj.proj_map_toSpecZero`, and the construction of `φ` with its positive-degree surjectivity is
the body of `Proj.isProper_toSpecZero_comp_of_generated`, repackaged
here as `Proj.exists_closedImmersion_projectiveSpaceOver_of_generated` (Step A). Step 4 in the form needed
by Step A is `GradedQCAlgebra.exists_finset_degOne_mem_closure_of_generatedInDegreeOne` (Step B; degree
induction `GradedRing.mem_subring_of_pos_of_irrelevant_le_span_one` from `B₊ ⊆ (B_1)`,
`irrelevant_le_span_degOne_of_generatedInDegreeOne`, plus Stacks 01PB for the finite generators of `B_1`).
Steps 2 and 7's base compatibility is `relativeProj.affineIso_hom_toSpecZero_sectionsUnit` (Step C).
Step A is applied with the coefficient map `φ := sectionsUnit V : Γ(S,V) → B_0` — surjectivity of `φ` is
*not* needed, exactly as explained in step 4.

**Edge cases.** `V = ⊥`: `R = 0`, `P^n_0 = ∅`, `f⁻¹V = ∅`, `j` the empty morphism. `B_1 = 0`: then
`B_+ = 0`, `Proj B = ∅ = f⁻¹V`, take `n = 0`. `X = ∅`: any `n`. `f` an isomorphism onto `S`
(`𝒜 = O_S[T]`): `n = 0`, `P^0_R = Spec R`. -/
theorem AlgebraicGeometry.IsProjectiveMorphism.exists_closedImmersion_projectiveSpaceOver
    {X S : AlgebraicGeometry.Scheme.{u}} (f : X ⟶ S) [AlgebraicGeometry.IsProjectiveMorphism f]
    (V : S.affineOpens) :
    ∃ (n : ℕ) (j : (f ⁻¹ᵁ V.1).toScheme ⟶ ProjectiveSpaceOver n Γ(S, V.1)),
      AlgebraicGeometry.IsClosedImmersion j ∧
        j ≫ ProjectiveSpaceOver.toSpecBase n Γ(S, V.1) = (f ∣_ V.1) ≫ V.2.isoSpec.hom := by
  obtain ⟨𝒜, i, hgen, hft, hi, rfl⟩ :=
    (‹AlgebraicGeometry.IsProjectiveMorphism f›).exists_closed_immersion
  have := hft
  obtain ⟨s, hs, hcl⟩ := 𝒜.exists_finset_degOne_mem_closure_of_generatedInDegreeOne hgen V
  obtain ⟨n, j', hj', hcomp⟩ :=
    AlgebraicGeometry.Proj.exists_closedImmersion_projectiveSpaceOver_of_generated
      (𝒜.sectionsGrading V.1) (𝒜.sectionsUnit V.1) s hs hcl
  have := hj'
  have := hi
  have hci1 : AlgebraicGeometry.IsClosedImmersion
      (i ∣_ ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1)) := inferInstance
  have hci2 : AlgebraicGeometry.IsClosedImmersion
      (AlgebraicGeometry.Scheme.relativeProj.affineIso 𝒜 V).hom := inferInstance
  have hci3 : AlgebraicGeometry.IsClosedImmersion
      ((AlgebraicGeometry.Scheme.relativeProj.affineIso 𝒜 V).hom ≫ j') :=
    AlgebraicGeometry.IsClosedImmersion.comp _ _
  have hci4 : AlgebraicGeometry.IsClosedImmersion
      ((i ∣_ ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1)) ≫
        (AlgebraicGeometry.Scheme.relativeProj.affineIso 𝒜 V).hom ≫ j') :=
    AlgebraicGeometry.IsClosedImmersion.comp _ _
  refine ⟨n, (i ∣_ ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1)) ≫
    (AlgebraicGeometry.Scheme.relativeProj.affineIso 𝒜 V).hom ≫ j', hci4, ?_⟩
  have key : ((i ∣_ ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1)) ≫
      (AlgebraicGeometry.Scheme.relativeProj.affineIso 𝒜 V).hom ≫ j') ≫
        ProjectiveSpaceOver.toSpecBase n Γ(S, V.1) =
      ((i ∣_ ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ V.1)) ≫
        ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ∣_ V.1)) ≫ V.2.isoSpec.hom := by
    simp only [Category.assoc]
    rw [hcomp, AlgebraicGeometry.Scheme.relativeProj.affineIso_hom_toSpecZero_sectionsUnit]
  rw [morphismRestrict_comp]
  exact key

end
