import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Morphisms.QuasiProjectiveMorphism
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.LocallyFreeQuasicoherent
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.GeneratedInDegreeOne
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.RelativeProjQC
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.SymGradedAlgebraGeneratedInDegreeOne
import MiyaokaMori.AlgebraicGeometry.Modules.SymGradedAlgebraPartOneFiniteType
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.QcFiniteTypeApproxFiniteSections
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.Stacks01lc
import MiyaokaMori.AlgebraicGeometry.Morphisms.Stacks07rm_QuasiSeparated
import MiyaokaMori.AlgebraicGeometry.Modules.Ample.Stacks07rm_RelativeChartSections
import MiyaokaMori.AlgebraicGeometry.Morphisms.Stacks07rm_ExistsImmersionOfCharts

/-! # Quasi-projective morphisms: the immersion into a relative Proj

Stacks 07RM, paragraphs 1–5 of the proof (everything except the final scheme-theoretic closure):
`S` quasi-compact quasi-separated, `f : X → S` quasi-projective ⇒ `X` admits an **immersion** `r` over `S`
into the relative Proj of a graded quasi-coherent `O_S`-algebra generated in degree one with finite type
degree-one part (namely `P(E) = Proj_S Sym E` for a finite type quasi-coherent `E`).

The closure step (Stacks 01RG) is done in `Stacks07rm.lean` with Mathlib's scheme-theoretic image
(`Scheme.Hom.toImage` / `imageι`).

The theorem is glued from the following pieces (Steps refer to the proof in the docstring below):
* Steps 1–2: `IsQuasiProjectiveMorphism.exists_relative_chart_sections`
  (`Stacks07rm_RelativeChartSections.lean`), itself resting on
  `IsAmple.exists_charts_generators_of_isAffine` (`Stacks07rm_AmpleChartsAffineBase.lean`);
* Step 3: `IsQuasiProjectiveMorphism.quasiSeparated`, `Modules.isQuasicoherent_pushforward` (Stacks 01LC) and
  `Modules.exists_isFiniteType_hom_of_finite_affine_sections`;
* Step 4: `Modules.epi_of_transpose_frames`, `relativeProj.liftDataOfEpi`, `relativeProj.lift` /
  `lift_hom`, `symGradedAlgebra_generatedInDegreeOne`, `symGradedAlgebra_part_one_isFiniteType`;
* Step 5: `relativeProj.exists_isImmersion_symGradedAlgebra_of_charts` (`Stacks07rm_ExistsImmersionOfCharts.lean`),
  the existence form of `relativeProj.isImmersion_lift_symGradedAlgebra_of_charts`
  (`Stacks07rm_LiftSymImmersionOfCharts.lean`), whose route uses the general criterion
  `isImmersion_of_affine_charts`.
The charts are the frame loci `M.frameLocusOn s` of local sections. -/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- **Quasi-projective ⇒ immersion into a relative Proj over the base** (Stacks 07RM,
morphisms-lemma-quasi-projective-open-projective, paragraphs 1–5 of the proof).

`S` quasi-compact quasi-separated, `f : X ⟶ S` quasi-projective (`IsQuasiProjectiveMorphism`: locally of
finite type, quasi-compact, with a line bundle `L` on `X` whose restriction to `f⁻¹V` is ample for every
affine open `V ⊆ S`). Then there are a graded quasi-coherent `O_S`-algebra `𝒜` generated in degree one with
`𝒜₁` of finite type and an **immersion** `r : X ⟶ Proj_S 𝒜` with `r ≫ π = f`.

**Proof (Stacks 07RM; self-contained, written against this library).** Fix `L` from
`IsQuasiProjectiveMorphism.exists_relativelyAmple`. Choose a finite affine cover `S = V_1 ∪ … ∪ V_m`
(`CompactSpace S`) and write `X_j := f⁻¹V_j`,
`f_j := f ∣_ V_j : X_j ⟶ V_j`; `X_j` is quasi-compact (`QuasiCompact f`), `f_j` is of finite type, `V_j` is
affine and `L|_{X_j}` is ample.

*Step 1 (local very-ample sections; Stacks 01VU + 02NP, "sections form", one `j` at a time).*
Over the affine `V_j` there are `d_j > 0` and finitely many sections `s_{j,0}, …, s_{j,n_j}` of
`L^{⊗d_j}` on `X_j` and a subset `I_j` of indices such that
(a) the nonvanishing loci `(X_j)_{s_{j,t}}`, `t ∈ I_j`, cover `X_j` and are affine;
(b) for `t ∈ I_j`, the `Γ(V_j, O)`-algebra `Γ((X_j)_{s_{j,t}}, O)` is generated by the ratios
`s_{j,t'} / s_{j,t}` (`t' = 0, …, n_j`).
This is exactly the argument of `IsAmple.exists_projectivizationMorphism_isImmersion`
(`AmpleFiniteProjectivizationImmersion.lean`, Stacks 01VU over a field) with the field `k`
replaced by the affine base `V_j`: ampleness gives finitely many sections of one power `L^{⊗d}` whose
nonvanishing loci are affine and cover (`IsAmple.exists_finite_affine_cover`, proved); each affine piece
`(X_j)_s` is of finite type over the affine `V_j`, so `Γ((X_j)_s, O)` is a finitely generated
`Γ(V_j, O)`-algebra (Mathlib: `LocallyOfFiniteType` is `HasRingHomProperty` for `RingHom.FiniteType`);
by Stacks 01PW (`exists_tensorPow_section_restrict_eq`) each generator `g` of
`Γ((X_j)_s, O)` becomes, after multiplying by `s^{⊗e}`, the restriction of a global section
`t ∈ Γ(X_j, L^{⊗de})`, i.e. `g = t / s^{e}`; take a common `e` (finitely many generators; `X_j` is
quasi-separated because `L|_{X_j}` is ample, `IsAmple.quasiSeparatedSpace`) and replace the covering sections
`s` by `s^{e}` (same loci). The new family (covering sections `s^{e}` and extended generators `t`) satisfies
(a) and (b) with `d_j := d·e`. **Lean:** `IsAmple.exists_charts_generators_of_isAffine`.

*Step 2 (a common degree).* Replace `d_j` by `d := ∏_j d_j` and each family by all monomials of degree
`d/d_j` in the `s_{j,t}` (`(X_j)_{s^{k}} = (X_j)_{s}`; the ratios `s_{j,t'} s_{j,t}^{k-1} / s_{j,t}^{k} =
s_{j,t'}/s_{j,t}` are among the new ratios, so (a), (b) persist with the covering indices the pure powers).
Set `M := L^{⊗d}` (a line bundle, `IsLineBundle.tensorPow`). Nothing below uses ampleness of `M` any more:
only (a), (b) and the covering property of the `s_{j,t}` are used. **Lean:** Steps 1–2 together are
`IsQuasiProjectiveMorphism.exists_relative_chart_sections`,
stated on `X` with the sections `s_{j,t} ∈ Γ(f⁻¹V_j, M)` and the charts `M.frameLocusOn (s_{j,t})`.

*Step 3 (finite type approximation).*
`F := f_* M` is quasi-coherent on `S` (Stacks 01LC, `Modules.isQuasicoherent_pushforward`; `f` is quasi-compact by definition and quasi-separated because
`QuasiSeparated` is local on the target and, over the affine `V_j`, it is quasi-separatedness of the space
`X_j`, which holds by `IsAmple.quasiSeparatedSpace` for `L|_{X_j}`: `IsQuasiProjectiveMorphism.quasiSeparated`).
The sections `s_{j,t} ∈ Γ(X_j, M) = F(V_j)`. Apply
`Modules.exists_isFiniteType_hom_of_finite_affine_sections` to `F`, the affine opens `V_j` and the finitely
many sections `s_{j,t}` (re-indexed by `Fin N`, `N := card (Σ j, Fin n_j)`): get `E` quasi-coherent of finite
type, `φ : E ⟶ F` and `e_{j,t} ∈ E(V_j)` with `φ(e_{j,t}) = s_{j,t}`.

*Step 4 (the morphism `r : X → P(E)`; Stacks 01O9, library `relativeProj.lift`).* Let
`𝒜 := symGradedAlgebra E`; it is generated in degree one
(`symGradedAlgebra_generatedInDegreeOne`) with
`𝒜₁ ≅ E` of finite type (`symGradedAlgebra_part_one_isFiniteType`). The adjoint of `φ : E ⟶ f_* M` is
`ψ : f^*E ⟶ M` (`pullbackPushforwardAdjunction`). `ψ` is an epimorphism: on the frame locus of
`s_{j,t} = φ(e_{j,t})` the section `φ(e_{j,t})` is a frame of `M`, and these loci cover `X` (Step 1(a)), so
`Modules.epi_of_transpose_frames` applies. The symmetric powers
`Sym^m ψ = symGradedPullbackDesc f ψ m` assemble to `relativeProj.liftDataOfEpi f E M ψ : LiftData 𝒜 f M`
(`map_one`, `map_mul` are the computations of
`ProjectiveBundleUniversalPropertySymPowDesc.lean`, `generates` is `Sym^1 ψ` epi), and
`r := relativeProj.lift 𝒜 f M D` satisfies `r ≫ π = f` (`relativeProj.lift_hom`).

*Step 5 (`r` is an immersion; Stacks 07RK/01O9 on the affine pieces).* For `x ∈ X` pick `j` with `f(x) ∈ V_j`
and `t ∈ I_j` with `x` in the frame locus `X_{s_{j,t}}` of `s_{j,t} = φ(e_{j,t})`; this locus is affine and its
coordinate ring is generated over `Γ(V_j, O)` by the ratios `s_{j,t'}/s_{j,t} = φ(e_{j,t'})/φ(e_{j,t})`
(Step 1(b)), which are among the ratios `φ(e')/φ(e_{j,t})`, `e' ∈ E(V_j)`. This is the chart hypothesis of
`relativeProj.exists_isImmersion_symGradedAlgebra_of_charts` (the
existence form of `relativeProj.isImmersion_lift_symGradedAlgebra_of_charts`):
over the affine `V_j`, `π⁻¹V_j ≅ Proj A_j` with `A_j = Sym_{Γ(V_j,O)} Γ(V_j, E)` (Stacks 01NQ,
`relativeProj.affineIso`), the chart `D_+(e_{j,t})` is affine with ring generated over `Γ(V_j,O)` by the
`a/e_{j,t}`, `a ∈ Γ(V_j, E)`; `r⁻¹(D_+(e_{j,t})) = X_{s_{j,t}}` and the ring map sends `a/e_{j,t} ↦ φ(a)/s_{j,t}`
(Stacks 01O4, `relativeProj.lift_inducedBy`), hence is surjective; so each `X_{s_{j,t}} → D_+(e_{j,t})` is a
closed immersion (`Spec` of a surjection) and `r` is an immersion by Mathlib
`IsZariskiLocalAtTarget.of_range_subset_iSup` (`isImmersion_of_affine_charts`).

**Edge cases.** `X = ∅`: `r` is the empty immersion (any `E`, e.g. `E := 0`, `𝒜 := Sym 0`, whose Proj over `S`
is empty — fine, the statement only asks for an immersion over `S`). `S = ∅`: trivial. `m = 0` covering
pieces only when `S = ∅`. Degrees: all `d_j > 0`, so `d > 0` and `M` is a genuine line bundle. -/
theorem AlgebraicGeometry.IsQuasiProjectiveMorphism.exists_isImmersion_relativeProj
    {X S : AlgebraicGeometry.Scheme.{u}} (f : X ⟶ S) [AlgebraicGeometry.IsQuasiProjectiveMorphism f]
    [CompactSpace S] [QuasiSeparatedSpace S] :
    ∃ (𝒜 : S.GradedQCAlgebra) (r : X ⟶ (AlgebraicGeometry.Scheme.relativeProj 𝒜).left),
      𝒜.GeneratedInDegreeOne ∧ (𝒜.part 1).IsFiniteType ∧
      AlgebraicGeometry.IsImmersion r ∧ r ≫ (AlgebraicGeometry.Scheme.relativeProj 𝒜).hom = f := by
  classical
  -- Steps 1–2: the line bundle `M`, the affine cover `V j` and the chart sections `s j t`.
  obtain ⟨M, hM, m, V, n, s, I, hVcov, hcov, haff, hgen⟩ :=
    AlgebraicGeometry.IsQuasiProjectiveMorphism.exists_relative_chart_sections f
  have := hM
  -- Step 3: `f_*M` is quasi-coherent; finite type approximation of the finitely many sections.
  have : AlgebraicGeometry.QuasiSeparated f := AlgebraicGeometry.IsQuasiProjectiveMorphism.quasiSeparated f
  have : AlgebraicGeometry.QuasiCompact f := AlgebraicGeometry.IsQuasiProjectiveMorphism.quasiCompact (f := f)
  have : ((AlgebraicGeometry.Scheme.Modules.pushforward f).obj M).IsQuasicoherent :=
    AlgebraicGeometry.Scheme.Modules.isQuasicoherent_pushforward f M
  let κ := Σ j : Fin m, Fin (n j)
  let eκ : κ ≃ Fin (Fintype.card κ) := Fintype.equivFin κ
  obtain ⟨E, hEqc, hEft, φ, e, hφe⟩ :=
    AlgebraicGeometry.Scheme.Modules.exists_isFiniteType_hom_of_finite_affine_sections
      ((AlgebraicGeometry.Scheme.Modules.pushforward f).obj M) (fun i => V (eκ.symm i).1)
      (fun i => s (eκ.symm i).1 (eκ.symm i).2)
  have := hEqc
  have := hEft
  -- Step 4: the adjoint `ψ : f^*E ⟶ M` is an epimorphism; lift data and the morphism `r`.
  let ψ : (AlgebraicGeometry.Scheme.Modules.pullback f).obj E ⟶ M :=
    ((AlgebraicGeometry.Scheme.Modules.pullbackPushforwardAdjunction f).homEquiv E M).symm φ
  have hφψ : (AlgebraicGeometry.Scheme.Modules.pullbackPushforwardAdjunction f).homEquiv E M ψ = φ :=
    Equiv.apply_symm_apply _ _
  -- for every pair `(j, t)` a section `e' ⟨j, t⟩ ∈ E(V j)` with `φ(e' ⟨j, t⟩) = s j t`
  have hsec : ∀ q : κ, ∃ e' : Γ(E, (V q.1).1),
      AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e' = s q.1 q.2 := by
    intro q
    have h' : ∃ e' : Γ(E, (V (eκ.symm (eκ q)).1).1),
        AlgebraicGeometry.Scheme.Modules.transposeSection f ψ e' =
          s (eκ.symm (eκ q)).1 (eκ.symm (eκ q)).2 := by
      refine ⟨e (eκ q), ?_⟩
      show AlgebraicGeometry.Scheme.Modules.ofPushforwardSection f M
        (((AlgebraicGeometry.Scheme.Modules.pullbackPushforwardAdjunction f).homEquiv E M ψ).app _ (e (eκ q))) = _
      rw [hφψ]
      exact hφe (eκ q)
    rwa [Equiv.symm_apply_apply] at h'
  choose e' key' using hsec
  have key : ∀ (j : Fin m) (t : Fin (n j)),
      AlgebraicGeometry.Scheme.Modules.transposeSection f ψ (e' ⟨j, t⟩) = s j t := fun j t => key' ⟨j, t⟩
  have hchart : ∀ x : X, ∃ (j : Fin m) (t : Fin (n j)), t ∈ I j ∧ x ∈ M.frameLocusOn (s j t) := by
    intro x
    obtain ⟨j, hj⟩ := hVcov (f.base x)
    obtain ⟨t, ht, hx⟩ := hcov j x hj
    exact ⟨j, t, ht, hx⟩
  have hψ : CategoryTheory.Epi ψ := by
    refine AlgebraicGeometry.Scheme.Modules.epi_of_transpose_frames f ψ fun x => ?_
    obtain ⟨j, t, -, hx⟩ := hchart x
    refine ⟨(V j).1, e' ⟨j, t⟩, M.frameLocusOn (s j t), M.frameLocusOn_le (s j t), hx, ?_⟩
    show M.IsFrame (M.frameLocusOn (s j t)) (M.res (M.frameLocusOn_le (s j t))
      (AlgebraicGeometry.Scheme.Modules.transposeSection f ψ (e' ⟨j, t⟩)))
    rw [key j t]
    exact M.isFrame_res_frameLocusOn (s j t)
  -- Step 5: the immersion `r` from the chart data `(V j, e (j,t))` (existence form, see the module docstring).
  refine Exists.elim
    (AlgebraicGeometry.Scheme.relativeProj.exists_isImmersion_symGradedAlgebra_of_charts f M E ψ hψ ?_)
    (fun r hr => ⟨AlgebraicGeometry.Scheme.Modules.symGradedAlgebra E, r,
      AlgebraicGeometry.Scheme.Modules.symGradedAlgebra_generatedInDegreeOne E,
      AlgebraicGeometry.Scheme.Modules.symGradedAlgebra_part_one_isFiniteType E, hr.1, hr.2⟩)
  intro x
  obtain ⟨j, t, ht, hx⟩ := hchart x
  refine ⟨V j, e' ⟨j, t⟩, ?_⟩
  rw [key j t]
  refine ⟨hx, haff j t ht, ?_⟩
  refine top_unique ?_
  rw [← hgen j t ht]
  refine Subring.closure_mono (Set.union_subset_union_right _ ?_)
  rintro g ⟨t', ht'⟩
  exact ⟨e' ⟨j, t'⟩, by rw [key j t']; exact ht'⟩

end
