import MiyaokaMori.Prelude
import MiyaokaMori.Paper.S2WeightedJets.Jets.WeightDefectSections
import MiyaokaMori.Algebra.WeightDecompositionAlgebra
import MiyaokaMori.AlgebraicGeometry.Morphisms.WeightDecompositionPolynomialChart
import MiyaokaMori.AlgebraicGeometry.Morphisms.WeightDecompositionCoassoc

/-! # Weight decomposition of sections under a nonnegative `G_m`-action

Under a nonnegative `G_m`-action on a scheme `T` over `S`, every section over an affine open
is a finite sum of eigensections (the "`A = Σ A_n` is generated by the `A_n`" half of
Stacks Project, Tag 0EKK, in its relative, nonnegative, sheaf-of-sections form):
`GroupSchemeAction.exists_weight_decomposition`. Nonnegativity means that the action extends
to the monoid scheme `A¹` (`GroupSchemeAction.IsNonnegative`); this is the nonnegative grading of
the coordinate algebra of the cone, §2.1 of the paper.

## Structure

* The purely algebraic part is `WeightDecomposition.exists_weight_decomposition_of_charts`
  (`MiyaokaMori.Algebra.WeightDecompositionAlgebra`). It is stated in terms of "generators":
  a chart `e`, a counit `s`, a coassociativity chart `(ψ, lam₁, e₂, m, a₂)` and a nonnegativity
  chart `(φ', actS', lam', e', ι)`; on the geometric side one only has to compute ring
  homomorphisms on the generators `pr₂^♯(a)` and `λ`.
* The geometric translation is split into the following lemmas:
  - `act_appLE_structure` (this file): `act^♯` and `pr₂^♯` agree on `k` (`k`-linearity);
  - `snd_appLE_structure` (this file): the two `Gm.sectionsAlgebra` structures on `Γ(V)` and
    `Γ(pr₂⁻¹V)` are compatible via `pr₂^♯`;
  - `exists_counit_appLE` (this file): taking sections of the unit section `σ = (e, 𝟙)` gives the
    counit `s` (uses `one_act`);
  - `exists_coassoc_appLE` (`WeightDecompositionCoassoc`): `(μ × 1)^♯`, `(1 × act)^♯` and the
    coassociativity identity (uses `mul_act`);
  - `IsNonnegative.exists_act'_over` (this file): the extension `act'` respects the structure
    morphism to `S`; this is part of the definition of `IsNonnegative`;
  - `exists_polynomial_chart_of_act'` (`WeightDecompositionPolynomialChart`): the polynomial chart
    of `A¹ ×_k V` (the general chart `SpecChart.pullback_sections_tensorEquiv` with `A = k[X]`)
    and its restriction along `G_m ↪ A¹`;
  - `Gm_pullback_sections_tensorEquiv` (the chart of `G_m ×_k V`), used twice in this file
    (for `V` over `T` and for `pr₂⁻¹V` over `W`).
  The one-line lemmas `appLE_hom_congr_of_eq`, `act_comp_structure_eq` and the elementwise
  lemmas are in `WeightDecompositionAppLE`.
* `exists_weight_decomposition` assembles all of the above.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry TensorProduct

noncomputable section

namespace GroupSchemeAction

variable {k : Type u} [Field k] {S : AlgebraicGeometry.Scheme.{u}}
    [S.Over (AlgebraicGeometry.Spec (CommRingCat.of k))] {T : CategoryTheory.Over S}

/-! ## Notation (local to this file; expanded textually, so the variables must be named `k`, `S`, `T`, `U`) -/

set_option quotPrecheck false
set_option hygiene false

/-- Spec k -/
local notation "Specₖ" => AlgebraicGeometry.Spec (CommRingCat.of k)
/-- G_m → Spec k -/
local notation "𝔤" => ((Gm k).asOver (AlgebraicGeometry.Spec (CommRingCat.of k))).hom
/-- q := π ≫ (S ↘ Spec k) : T → Spec k -/
local notation "𝔮" => (T.hom ≫ (S ↘ AlgebraicGeometry.Spec (CommRingCat.of k)))
/-- pr₂ : W = G_m ×_k T → T -/
local notation "𝔭𝔯₂" => CategoryTheory.Limits.pullback.snd
  ((Gm k).asOver (AlgebraicGeometry.Spec (CommRingCat.of k))).hom
  (T.hom ≫ (S ↘ AlgebraicGeometry.Spec (CommRingCat.of k)))
/-- V := π⁻¹U -/
local notation "𝔙" => (T.hom ⁻¹ᵁ U)
/-- The structure homomorphism `k → Γ(T, V)` via `q^♯` (the `algebraMap` of `Gm.sectionsAlgebra 𝔮 𝔙`) -/
local notation "𝔞𝔩𝔤" => ((AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of k)).inv ≫
  (T.hom ≫ (S ↘ AlgebraicGeometry.Spec (CommRingCat.of k))).appLE ⊤ (T.hom ⁻¹ᵁ U) le_top)

/-- **`k`-linearity of `act^♯`**: `act^♯` and `pr₂^♯` agree on the image of `k`.
Proof: `appLE_comp_appLE` rewrites `q^♯ ≫ act^♯` as `(act ≫ q)^♯` and likewise
`q^♯ ≫ pr₂^♯ = (pr₂ ≫ q)^♯`, and `act ≫ q = pr₂ ≫ q` (`act_comp_structure_eq`). -/
theorem act_appLE_structure (α : GmActionOver k T) (U : S.Opens) (c : k) :
    (α.act.appLE 𝔙 _ (snd_comp_preimage_eq_act_preimage α U).le).hom ((𝔞𝔩𝔤).hom c) =
      ((𝔭𝔯₂).appLE 𝔙 _ le_rfl).hom ((𝔞𝔩𝔤).hom c) := by
  have h₁ := AlgebraicGeometry.Scheme.Hom.appLE_comp_appLE α.act 𝔮 ⊤ 𝔙 (𝔭𝔯₂ ⁻¹ᵁ 𝔙) le_top
    (snd_comp_preimage_eq_act_preimage α U).le
  have h₂ := AlgebraicGeometry.Scheme.Hom.appLE_comp_appLE 𝔭𝔯₂ 𝔮 ⊤ 𝔙 (𝔭𝔯₂ ⁻¹ᵁ 𝔙) le_top le_rfl
  have h := congrArg (fun φ : Γ(Specₖ, ⊤) ⟶ Γ(CategoryTheory.Limits.pullback 𝔤 𝔮, 𝔭𝔯₂ ⁻¹ᵁ 𝔙) =>
    φ.hom ((AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of k)).inv.hom c))
    (h₁.trans ((appLE_hom_congr_of_eq (act_comp_structure_eq α) ⊤ (𝔭𝔯₂ ⁻¹ᵁ 𝔙) _).trans h₂.symm))
  exact h

/-- **Compatibility of the two `Gm.sectionsAlgebra` structures**: the `k`-structure of `Γ(V)`
transported by `pr₂^♯` is the `k`-structure of `Γ(pr₂⁻¹V)`
(`Gm.sectionsAlgebra (pr₂ ≫ q) (pr₂⁻¹V)`). Proof: `appLE_comp_appLE`. -/
theorem snd_appLE_structure (U : S.Opens) (c : k) :
    ((𝔭𝔯₂).appLE 𝔙 _ le_rfl).hom ((𝔞𝔩𝔤).hom c) =
      ((AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of k)).inv ≫
        (𝔭𝔯₂ ≫ 𝔮).appLE ⊤ (𝔭𝔯₂ ⁻¹ᵁ 𝔙) le_top).hom c := by
  have h₂ := AlgebraicGeometry.Scheme.Hom.appLE_comp_appLE 𝔭𝔯₂ 𝔮 ⊤ 𝔙 (𝔭𝔯₂ ⁻¹ᵁ 𝔙) le_top le_rfl
  have h := congrArg (fun φ : Γ(Specₖ, ⊤) ⟶ Γ(CategoryTheory.Limits.pullback 𝔤 𝔮, 𝔭𝔯₂ ⁻¹ᵁ 𝔙) =>
    φ.hom ((AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of k)).inv.hom c)) h₂
  exact h

/-! ## Geometric lemmas -/

/-- **The counit.** The unit section `σ := lift((π ≫ (S ↘ Spec k)) ≫ e, 𝟙_T) : T → W = G_m ×_k T`
(the left factor of `one_act`), on sections over `U`, gives `s := σ^♯ : Γ(W, pr₂⁻¹V) → Γ(T, V)`
with `s ∘ pr₂^♯ = id`, `s(λ) = 1` and `s ∘ act^♯ = id`.

Reference: Stacks Project, Tag 0EKK (the counit identity `(ε ⊗ id) ∘ co = id`); Mathlib's
`AlgebraicGeometry.one_spec_asOver_spec_left` (the `MonObj.one` of `G_m` is
`Spec.map (counitAlgHom)`) and `LaurentPolynomial.counit_T`.

Proof sketch:
1. `σ ≫ pr₂ = 𝟙` (`pullback.lift_snd`), so `σ⁻¹(pr₂⁻¹V) = V` and `s := σ.appLE (pr₂⁻¹V) V _`
   makes sense; `s ∘ pr₂^♯ = (σ ≫ pr₂)^♯ = 𝟙^♯ = id` (`appLE_comp_appLE`; the `appLE` of `𝟙` is the
   identity).
2. `s ∘ act^♯ = (σ ≫ act)^♯ = 𝟙^♯ = id`: `α.one_act` is exactly `σ ≫ act = 𝟙_T`.
3. `s(λ)`: `λ = Gm.lambdaOn 𝔮 V = res(pr₁^♯(Gm.lambda k))`, `σ ≫ pr₁ = q ≫ e` (`pullback.lift_fst`),
   `e = MonObj.one.left = Spec.map (ofHom (counitAlgHom k k[λ^{±1}]))` (`one_spec_asOver_spec_left`,
   by `rfl`), and `e^♯(ΓSpecIso.inv (T 1)) = ΓSpecIso.inv (counit (T 1)) = ΓSpecIso.inv 1 = 1`
   (`ΓSpecIso_naturality`, `counit_T`), hence `s(λ) = q^♯(1) = 1`.
Edge case: for `U = ∅` we have `Γ(V) = 0` and all three identities are trivial. -/
theorem exists_counit_appLE (α : GmActionOver k T) (U : S.Opens) :
    ∃ s : Γ(CategoryTheory.Limits.pullback 𝔤 𝔮, 𝔭𝔯₂ ⁻¹ᵁ 𝔙) →+* Γ(T.left, 𝔙),
      (∀ a, s (((𝔭𝔯₂).appLE 𝔙 _ le_rfl).hom a) = a) ∧
      s (Gm.lambdaOn 𝔮 𝔙) = 1 ∧
      ∀ a, s ((α.act.appLE 𝔙 _ (snd_comp_preimage_eq_act_preimage α U).le).hom a) = a := by
  -- the unit section σ = (q ≫ e, 𝟙); e := MonObj.one.left = Spec.map (counit)
  let eMor : Specₖ ⟶ Gm k :=
    (CategoryTheory.MonObj.one : CategoryTheory.MonoidalCategory.tensorUnit _ ⟶ (Gm k).asOver Specₖ).left
  have he : eMor = AlgebraicGeometry.Spec.map
      (CommRingCat.ofHom (Bialgebra.counitAlgHom k (LaurentPolynomial k))) := rfl
  let pr₁ : CategoryTheory.Limits.pullback 𝔤 𝔮 ⟶ Gm k := CategoryTheory.Limits.pullback.fst 𝔤 𝔮
  let σ : T.left ⟶ CategoryTheory.Limits.pullback 𝔤 𝔮 :=
    CategoryTheory.Limits.pullback.lift (𝔮 ≫ eMor)
      (CategoryTheory.CategoryStruct.id T.left) (GroupSchemeAction.oneAct_cond _ T)
  have hσ_act : σ ≫ α.act = CategoryTheory.CategoryStruct.id T.left := α.one_act
  have hσ_snd : σ ≫ 𝔭𝔯₂ = CategoryTheory.CategoryStruct.id T.left :=
    CategoryTheory.Limits.pullback.lift_snd _ _ _
  have hσ_fst : σ ≫ pr₁ = 𝔮 ≫ eMor := CategoryTheory.Limits.pullback.lift_fst _ _ _
  have hle : 𝔙 ≤ σ ⁻¹ᵁ (𝔭𝔯₂ ⁻¹ᵁ 𝔙) := by
    rw [← AlgebraicGeometry.Scheme.Hom.comp_preimage, hσ_snd, AlgebraicGeometry.Scheme.Hom.id_preimage]
  -- the appLE of 𝟙 is the identity
  have hid : ∀ (e : 𝔙 ≤ (CategoryTheory.CategoryStruct.id T.left) ⁻¹ᵁ 𝔙),
      (CategoryTheory.CategoryStruct.id T.left).appLE 𝔙 𝔙 e = CategoryTheory.CategoryStruct.id _ :=
    fun _ => (AlgebraicGeometry.Scheme.Hom.appLE_eq_app _).trans (AlgebraicGeometry.Scheme.Hom.id_app 𝔙)
  refine ⟨(σ.appLE (𝔭𝔯₂ ⁻¹ᵁ 𝔙) 𝔙 hle).hom, ?_, ?_, ?_⟩
  · intro a
    have h := AlgebraicGeometry.Scheme.Hom.appLE_comp_appLE σ 𝔭𝔯₂ 𝔙 (𝔭𝔯₂ ⁻¹ᵁ 𝔙) 𝔙 le_rfl hle
    rw [appLE_hom_congr_of_eq hσ_snd, hid] at h
    exact congrArg (fun φ : Γ(T.left, 𝔙) ⟶ Γ(T.left, 𝔙) => φ.hom a) h
  · -- s(λ) = 1
    -- e^♯(λ_Gm) = ΓSpecIso.inv (counit (T 1)) = 1
    have hlam : (eMor.app ⊤).hom (Gm.lambda k) = 1 := by
      have h := congrArg (fun φ : CommRingCat.of (LaurentPolynomial k) ⟶ Γ(Specₖ, ⊤) =>
        φ.hom (LaurentPolynomial.T 1))
        (AlgebraicGeometry.Scheme.ΓSpecIso_inv_naturality
          (CommRingCat.ofHom (Bialgebra.counitAlgHom k (LaurentPolynomial k))))
      simp only [CommRingCat.hom_comp, RingHom.comp_apply, CommRingCat.hom_ofHom] at h
      have hc : ((Bialgebra.counitAlgHom k (LaurentPolynomial k) : LaurentPolynomial k →+* k)
          (LaurentPolynomial.T 1)) = 1 := by
        rw [RingHom.coe_coe, Bialgebra.counitAlgHom_apply, LaurentPolynomial.counit_T]
      rw [hc, map_one] at h
      exact (h.symm : _)
    -- pr₁^♯ ≫ σ^♯ = e^♯ ≫ q^♯ (both equal (σ ≫ pr₁)^♯ = (q ≫ e)^♯)
    have hA := AlgebraicGeometry.Scheme.Hom.appLE_comp_appLE σ pr₁ ⊤ (pr₁ ⁻¹ᵁ ⊤) 𝔙 le_rfl le_top
    have hB := AlgebraicGeometry.Scheme.Hom.appLE_comp_appLE 𝔮 eMor ⊤ (eMor ⁻¹ᵁ ⊤) 𝔙 le_rfl le_top
    rw [AlgebraicGeometry.Scheme.Hom.appLE_eq_app] at hA hB
    have hφ := hA.trans ((appLE_hom_congr_of_eq hσ_fst ⊤ 𝔙 _).trans hB.symm)
    have h1 := congrArg (fun φ : Γ(Gm k, ⊤) ⟶ Γ(T.left, 𝔙) => φ.hom (Gm.lambda k)) hφ
    -- unfold λ: s(res(pr₁^♯ λ_Gm)) = σ^♯_{⊤→V}(pr₁^♯ λ_Gm)
    have h0 := AlgebraicGeometry.Scheme.Hom.map_appLE σ hle
      (CategoryTheory.homOfLE (le_top : 𝔭𝔯₂ ⁻¹ᵁ 𝔙 ≤ ⊤)).op
    have h0' := congrArg (fun φ : Γ(CategoryTheory.Limits.pullback 𝔤 𝔮, ⊤) ⟶ Γ(T.left, 𝔙) =>
      φ.hom ((pr₁.app ⊤).hom (Gm.lambda k))) h0
    have h2 := congrArg ((𝔮).appLE (eMor ⁻¹ᵁ ⊤) 𝔙 le_top).hom hlam
    rw [map_one] at h2
    exact (h0'.trans h1).trans h2
  · intro a
    have h := AlgebraicGeometry.Scheme.Hom.appLE_comp_appLE σ α.act 𝔙 (𝔭𝔯₂ ⁻¹ᵁ 𝔙) 𝔙
      (snd_comp_preimage_eq_act_preimage α U).le hle
    rw [appLE_hom_congr_of_eq hσ_act, hid] at h
    exact congrArg (fun φ : Γ(T.left, 𝔙) ⟶ Γ(T.left, 𝔙) => φ.hom a) h

/-- The extension `act' : A¹ ×_k T → T` provided by nonnegativity **respects the structure
morphism to `S`**: `act' ≫ π = pr₂' ≫ π`. This is the second component of
`GroupSchemeAction.IsNonnegative`, so the statement is immediate from `hα`.

The geometric meaning of the extension to `A¹` is the nonnegative grading of the coordinate
algebra of the cone, §2.1 of the paper.

Remark: the compatibility with `π` is in fact automatic (for arbitrary `S` and `T`), by the
following argument, which is why it is harmless to include it in the definition. Let
`X := A¹ ×_k T`, `U := G_m ×_k T ⊆ X` (an open subscheme via `j = incl ×_k 𝟙`), `f := act' ≫ π`,
`g := pr₂' ≫ π : X → S`. From `(incl × 𝟙) ≫ act' = act` and `α.act_over` (`act ≫ π = pr₂ ≫ π`) we
get `f|_U = g|_U`.
1. For every open `N ⊆ X` the restriction `Γ(N, O_X) → Γ(N ∩ U, O_X)` is injective (`U` is
   scheme-theoretically dense in `X`): cover `N` by basic opens `D(h)` of `X_V := pr₂'⁻¹V` with
   `V ⊆ T` affine; `Γ(X_V) ≅ Γ(V)[X]` (`SpecChart.pullback_sections_tensorEquiv`),
   `U ∩ X_V = D(lam')`, and `Γ(D(h)) → Γ(D(h · lam'))` is the localization at `lam'`
   (`IsAffineOpen.isLocalization_basicOpen`), which is injective since `lam'` is a nonzerodivisor.
2. For every `x ∈ X`, `f(x)` and `g(x)` lie in a common affine open of `S`: with `t := pr₂'(x)`,
   the curve `c_t : A¹_{κ(t)} → X` through `x` is irreducible, so `f⁻¹(Spec B)` contains its generic
   point `ξ`, which lies in `U`; then `g(x) = π(t) = g(c_t ξ) = f(c_t ξ) ∈ Spec B`.
3. Locally, `f` and `g` on a basic open `D(h) ⊆ f⁻¹(Spec B) ∩ g⁻¹(Spec B)` are determined by ring
   homomorphisms `B → Γ(D(h))`, which agree after composing with the injection of step 1.
4. These `D(h)` cover `X`, hence `f = g` (`Scheme.Cover.hom_ext`).
The reference for step 1 is the local version of Stacks Project, Tag 01RH. -/
theorem IsNonnegative.exists_act'_over (α : GmActionOver k T) (hα : α.IsNonnegative) :
    ∃ act' : CategoryTheory.Limits.pullback
        (AlgebraicGeometry.Spec (CommRingCat.of (Polynomial k)) ↘ AlgebraicGeometry.Spec (CommRingCat.of k))
        𝔮 ⟶ T.left,
      CategoryTheory.Limits.pullback.map _ _ _ _
          (AlgebraicGeometry.Spec.map (CommRingCat.ofHom (Polynomial.toLaurentAlg (R := k)).toRingHom))
          (CategoryTheory.CategoryStruct.id _) (CategoryTheory.CategoryStruct.id _)
          GroupSchemeAction.isNonnegative_cond₁ (GroupSchemeAction.isNonnegative_cond₂ T) ≫ act' =
        α.act ∧
      act' ≫ T.hom = CategoryTheory.Limits.pullback.snd _ _ ≫ T.hom :=
  hα

/-! ## Assembly -/

/-- `G_m = Spec k[λ^{±1}]` is an affine scheme (`Gm` is an irreducible `def`, so instance search
cannot see through it; stated explicitly and not registered as a global instance). -/
theorem gm_isAffine : AlgebraicGeometry.IsAffine (Gm k) :=
  inferInstanceAs (AlgebraicGeometry.IsAffine (AlgebraicGeometry.Spec (CommRingCat.of (LaurentPolynomial k))))

set_option backward.isDefEq.respectTransparency.types false in
/-- `pr₂ : G_m ×_k T → T` is an affine morphism (base change of the affine morphism `G_m → Spec k`).
Not registered as a global instance; introduce it with `have` (as for the analogous instances in
Mathlib's `Morphisms/Affine.lean`, `backward.isDefEq.respectTransparency.types false` is needed
to find the `IsStableUnderBaseChangeAlong` instance). -/
theorem snd_isAffineHom : AlgebraicGeometry.IsAffineHom (𝔭𝔯₂ : CategoryTheory.Limits.pullback 𝔤 𝔮 ⟶ T.left) := by
  have : AlgebraicGeometry.IsAffine ((Gm k).asOver Specₖ).left := gm_isAffine
  have : AlgebraicGeometry.IsAffineHom 𝔤 := AlgebraicGeometry.isAffineHom_of_isAffine _
  exact MorphismProperty.pullback_snd (P := @AlgebraicGeometry.IsAffineHom) _ _ this

/-- **Weight decomposition** (the "generation" half of Stacks Project, Tag 0EKK, in its relative
nonnegative form, for sheaves of sections). Let `α` be a nonnegative `G_m`-action
(`α.IsNonnegative`: `act` extends to an action `act'` of the monoid scheme `A¹ = Spec k[λ]`),
`U ⊆ S` an affine open, `π := T.hom` affine, `V := π⁻¹U`, `R := Γ(V)`. Then every `a ∈ R` is a
finite sum `a = Σ_{n ∈ ℕ} y_n` where each `y_n` is a `λ^n`-eigensection: `φ_n(y_n) = 0`
(`φ_n = weightDefect α n`, on sections over `U`).

Notation: `W := G_m ×_k T`, `pr₂ : W → T`, `q := π ≫ (S ↘ Spec k)`, `λ := Gm.lambdaOn q V`;
`act^♯ := α.act.appLE V (pr₂⁻¹V) : R → Γ(W, pr₂⁻¹V)` (the inclusion of opens is
`snd_comp_preimage_eq_act_preimage`), `pr₂^♯ := pr₂.appLE V (pr₂⁻¹V)`. By
`weightDefect_val_app_apply`, `φ_n(y) = 0 ⟺ act^♯(y) = λ^n · pr₂^♯(y)`.

Proof (the argument of Stacks 0EKK relativized over `R`; the algebraic core is
`WeightDecomposition.exists_weight_decomposition_of_charts`):
1. The chart `e : Γ(W, pr₂⁻¹V) ≃+* k[λ^{±1}] ⊗_k R` with `e(pr₂^♯ a) = 1 ⊗ a` and
   `e(λ) = T 1 ⊗ 1`: `Gm_pullback_sections_tensorEquiv` (`V` is affine since `U` is and `π` is
   affine).
2. `k`-linearity: `act_appLE_structure`, `snd_appLE_structure`.
3. The counit `s`: `exists_counit_appLE` (from `one_act`).
4. Coassociativity: `Gm_pullback_sections_tensorEquiv` again (for the affine open `pr₂⁻¹V` of `W`;
   `pr₂` is affine) gives `e₂`, `ψ`, `λ₁`; `m`, `a₂` and the identity come from
   `exists_coassoc_appLE` (from `mul_act`).
5. Nonnegativity: `IsNonnegative.exists_act'_over` gives `act'`, and
   `exists_polynomial_chart_of_act'` gives `(φ', actS', lam', e', ι)`.
6. Feeding all of this into `exists_weight_decomposition_of_charts` yields `y` with
   `act^♯(y_n) = λ^n · pr₂^♯(y_n)`, which `weightDefect_val_app_apply` turns into `φ_n(y_n) = 0`.

Edge cases: for `U = ∅`, `R = 0` and `y = 0`; for the trivial action (`act = pr₂`), `a = a_0` and
`y = single 0 a`; for `T = ∅` the statement is trivial; for `a = 0` take `y = 0`. -/
theorem exists_weight_decomposition [AlgebraicGeometry.IsAffineHom T.hom]
    (α : GmActionOver k T) (hα : α.IsNonnegative) (U : S.Opens) (hU : AlgebraicGeometry.IsAffineOpen U)
    (a : Γ(T.left, T.hom ⁻¹ᵁ U)) :
    ∃ y : ℕ →₀ Γ(T.left, T.hom ⁻¹ᵁ U),
      (∀ n, ((GroupSchemeAction.weightDefect α n).val.app (Opposite.op U)).hom
        (show (((AlgebraicGeometry.Scheme.Modules.pushforward T.hom).obj
            (SheafOfModules.unit T.left.ringCatSheaf)).val.obj (Opposite.op U) : Type u) from y n) = 0) ∧
      y.sum (fun _ b => b) = a := by
  have hV : AlgebraicGeometry.IsAffineOpen 𝔙 := hU.preimage T.hom
  have : AlgebraicGeometry.IsAffineHom (𝔭𝔯₂ : CategoryTheory.Limits.pullback 𝔤 𝔮 ⟶ T.left) := snd_isAffineHom
  have hVW : AlgebraicGeometry.IsAffineOpen (𝔭𝔯₂ ⁻¹ᵁ 𝔙) := hV.preimage 𝔭𝔯₂
  have hle := (snd_comp_preimage_eq_act_preimage α U).le
  let _ : Algebra k Γ(T.left, 𝔙) := Gm.sectionsAlgebra 𝔮 𝔙
  let _ : Algebra k Γ(CategoryTheory.Limits.pullback 𝔤 𝔮, 𝔭𝔯₂ ⁻¹ᵁ 𝔙) :=
    Gm.sectionsAlgebra (𝔭𝔯₂ ≫ 𝔮) (𝔭𝔯₂ ⁻¹ᵁ 𝔙)
  -- 1. the chart
  obtain ⟨e, he_φ, he_lam⟩ := Gm_pullback_sections_tensorEquiv 𝔮 𝔙 hV
  -- 3. the counit
  obtain ⟨s, hsφ, hs_lam, hs_act⟩ := exists_counit_appLE α U
  -- 4. the coassociativity chart
  obtain ⟨e₂, he₂_ψ, he₂_lam₁⟩ := Gm_pullback_sections_tensorEquiv (𝔭𝔯₂ ≫ 𝔮) (𝔭𝔯₂ ⁻¹ᵁ 𝔙) hVW
  obtain ⟨m, a₂, hmφ, hm_lam, ha₂φ, ha₂_lam, hcoassoc⟩ := exists_coassoc_appLE α U
  -- 5. nonnegativity
  obtain ⟨act', hact', hover⟩ := IsNonnegative.exists_act'_over α hα
  obtain ⟨φ', actS', lam', e', ι, he'_φ, he'_lam, hιφ, hι_lam, hι_act⟩ :=
    exists_polynomial_chart_of_act' α U hV act' hact' hover
  -- 6. the algebraic core
  obtain ⟨y, hy, hsum⟩ := WeightDecomposition.exists_weight_decomposition_of_charts
    (k := k) (R := Γ(T.left, 𝔙))
    ((𝔭𝔯₂).appLE 𝔙 _ le_rfl).hom (α.act.appLE 𝔙 _ hle).hom (Gm.lambdaOn 𝔮 𝔙) e he_φ he_lam
    (fun c => snd_appLE_structure U c) (fun c => act_appLE_structure α U c)
    s hsφ hs_lam hs_act
    ((CategoryTheory.Limits.pullback.snd 𝔤 (𝔭𝔯₂ ≫ 𝔮)).appLE (𝔭𝔯₂ ⁻¹ᵁ 𝔙) _ le_rfl).hom m a₂
    (Gm.lambdaOn (𝔭𝔯₂ ≫ 𝔮) (𝔭𝔯₂ ⁻¹ᵁ 𝔙)) e₂ he₂_ψ he₂_lam₁ hmφ hm_lam ha₂φ ha₂_lam hcoassoc
    φ' actS' lam' e' he'_φ he'_lam ι hιφ hι_lam hι_act a
  refine ⟨y, fun n => ?_, hsum⟩
  have h := weightDefect_val_app_apply α n U (y n) hle
  rw [hy n, sub_self] at h
  exact h

end GroupSchemeAction

end
