import MiyaokaMori.Prelude
import MiyaokaMori.Paper.S3PositiveLine.Rescaling.JetPointRingHom
import MiyaokaMori.RingTheory.GradedAlgebraMonomialHom

/-! # Weight components of the glued jet on the chart coordinates
(step 4 of the proof of Lemma 3.1 of the paper)

Once `J|_{p_L⁻¹U} = localJet Ψ` with `Ψ = quotToSections_μ ∘ homEquiv φ`, the pieces of `J` on `U` are
`J.pieceSection V n c |_U = φ(d_{n-1} c) • μ^{⊗n}` (`pieceSection_of_localJet`, `frameJetRingMap_π`), which
identifies `Ψ_n(d_{n-1} c)|_U` for the **jet coordinates** `d_{n-1} c`. The chart coordinates
`x_{i,q} = chart.coords (i,q)` are polynomials in the jet coordinates (`J_κ(B_V, s^♯)` is generated by the
`d_q c` over `Γ(V)`), so the identity has to be extended to every homogeneous `x`:
`Ψ_m(x)|_U = φ(y) • μ^{⊗m}` whenever `y ∈ J_κ(B_V, s^♯)` represents `x` (`partι x = jetCoordinateSection V y`).
This module proves that extension (`weightComponent_of_localJet`) by comparing two ring homomorphisms
`J_κ(B_V, s^♯) →+* Γ(Tot(L), p⁻¹U)`: `Φ₁ = φ_J^♯ ∘ χ_V` (`jetPointRingHom`, `JetPointRingHom`)
and the monomial map `Φ₂ : y ↦ Σ_n p^♯(φ(y_n)) · 𝔪^n` on the weight grading (`GradedAlgebra.monomialHom`,
with the frame monomials `𝔪^n` of `TotalSpaceFrameMonomial`).
They agree on `Γ(V)` and on the generators `d_q c`, hence everywhere; taking the `m`-th ξ-coefficient
(`symCoeffHom`, `weightComponent_adj_app`, `frameHom_symCoeffHom`) gives the claim.

-/
set_option autoImplicit false
set_option maxHeartbeats 400000
set_option linter.style.haveILetI false

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

namespace jetNeighborhood

variable {k : Type u} [Field k] {X : SmoothProjectiveVariety k} {C : SmoothProjectiveCurve k}
  (f : C.toScheme ⟶ X.toScheme) [MMSetup f] (κ : ℕ) (ρ : FiniteCover k C)
  (L : LineBundle ρ.source.toVariety)

set_option linter.unusedVariables false in
/-- **Weight components of `J` on `U` from the local jet** (Lemma 3.1 of the paper;
§3 of the paper). Let `J : BasedJet f ρ L κ`, `V` an affine open of `C`, `U ≤ ρ⁻¹V` an
affine open of `C̃`, `μ` a frame of `L^{-1}` on `U`, `φ : J_κ(B_V, s^♯) → 𝒪(U)` a `Γ(V)`-algebra map, and
suppose `J|_{p_L⁻¹U} = localJet (frameJetRingMap μ φ)` (`hJ`). Then for every `m`, every `x ∈ S_m(V)` and
every `y ∈ J_κ(B_V, s^♯)` with `partι x = jetCoordinateSection V y`:
`Ψ_m(x)|_U = φ(y) • μ^{⊗m}`, where `Ψ_m(x) ∈ Γ(ρ⁻¹V, (L^∨)^{⊗m})` is `J.weightComponent m` transposed
along `pullbackPushforwardAdjunction ρ` and `μ^{⊗m} := pieceIso (framePow μ m)`.

Proof (fully formalized; notation: `J_κ^s` the affine jet scheme, `Tot := Tot(L)` with
`Tot|_U := Tot.hom⁻¹U`, `φ_J := J.jetPoint : Tot → J_κ^s`, `χ_V := chartEquiv V` (`= jetCoordinateSection V`,
`jetCoordinateSection_eq_chartEquiv`), `𝔪^n := frameMonomial L U μ n = frameHom n (pieceIso μ^{⊗n})`).
1. **Jet coordinates** (`jetPointRingHom_coeffClass_of_localJet`, `JetPointRingHom`):
   `φ_J^♯(χ_V(d_q c))|_{Tot|_U} = frameHom (q+1) (J.pieceSection V (q+1) c)|_U` (`jetPoint_appLE_jetCoordinate`,
   `appLE_map`, `PresheafOfModules.naturality_apply`) `= frameHom (q+1) (pieceIso (φ(d_q c) • μ^{⊗(q+1)}))`
   (`pieceSection_of_localJet`, `frameJetRingMap_π`) `= p^♯(φ(d_q c)) · 𝔪^{q+1}` (`𝒪`-linearity,
   `pushforward_unit_smul_eq`).
2. **The two ring maps.** `Φ₁ := φ_J^♯|_{Tot|_U} ∘ χ_V : J_κ(B_V, s^♯) →+* Γ(Tot|_U)` (`jetPointRingHom`) and
   `Φ₂ := GradedAlgebra.monomialHom (grading) (p^♯ ∘ φ) 𝔪 : y ↦ Σ_n p^♯(φ(y_n)) · 𝔪^n` (well defined because
   `𝔪^0 = 1`, `𝔪^{a+b} = 𝔪^a 𝔪^b`: `frameMonomial_zero`, `frameMonomial_add`, from `frameHom_pieceMul` and
   `pieceMul_app_framePow`).
3. **They agree** (`Ideal.Quotient.ringHom_ext`, `MvPolynomial.ringHom_ext`): on `Γ(V)`,
   `Φ₁(algebraMap r) = p^♯(ρ^♯ r)` (`jetPointRingHom_algebraMap`: `chartEquiv_unitHom`, `Over.w J.jetPoint`) and
   `Φ₂(algebraMap r) = p^♯(φ(algebraMap r)) · 𝔪^0 = p^♯(ρ^♯ r)` (`algebraMap_mem_grading_zero`, `φ.commutes`);
   on `d_q c = mk (X (q,c))` (`coeffClass_succ`) both are `p^♯(φ(d_q c)) · 𝔪^{q+1}` (step 1;
   `coeffClass_mem_grading`, `monomialHom_of_mem`).
4. **Conclusion.** `y ∈ grading m` (`kernel_ι_app_apply` on `partι x`, `weightDefect_app_chartEquiv_eq_zero_iff`),
   so `Φ₁ y = Φ₂ y = p^♯(φ y) · 𝔪^m = φ y • 𝔪^m`. By `weightComponent_adj_app` and naturality of `symCoeffHom`,
   `Ψ_m(x)|_U = symCoeffHom_m (Φ₁ y) = φ y • symCoeffHom_m (frameHom m (pieceIso μ^{⊗m})) = φ y • pieceIso μ^{⊗m}`
   (`frameHom_symCoeffHom`). ∎

The frame hypothesis `hμ` is not needed for this identity (kept for the parent's call). Edge cases: `κ = 0`
(`J_κ(B_V, s^♯) = Γ(V)`, no generators `d_q c`, only the constant case of step 3); `m = 0`
(`y ∈ Γ(V)`, `Ψ_0(x)|_U = ρ^♯ y • 1`, consistent with `weightComponent_map_one`); `m > κ` (the statement holds,
step 2 uses all weights). -/
theorem weightComponent_of_localJet (J : BasedJet f ρ L κ)
    {V : C.toScheme.Opens} (hV : AlgebraicGeometry.IsAffineOpen V)
    {U : ρ.source.toScheme.Opens} (hU : AlgebraicGeometry.IsAffineOpen U) (hUV : U ≤ ρ.hom ⁻¹ᵁ V)
    (μ : Γ((L.zpow (-1)).toModules, U)) (hμ : AlgebraicGeometry.Scheme.Modules.IsFrame (L.zpow (-1)).toModules U μ)
    (φ : letI := relativeJetScheme.sectionsAlgebra (MMSetup.cone f) V
      letI := baseAlgebra ρ hUV
      coneJetAlgebra f κ V →ₐ[Γ(C.toScheme, V)] Γ(ρ.source.toScheme, U))
    (hJ : (jetNeighborhood.proj L κ ⁻¹ᵁ U).ι ≫ J.hom =
      localJet f κ ρ L hV hU (frameJetRingMap f κ ρ L hUV μ φ))
    (m : ℕ) (x : (jetAlgebra f κ).sectionsPiece V m) (y : coneJetAlgebra f κ V)
    (hxy : (BasedJet.partι f κ m).val.app (Opposite.op V) x = jetCoordinateSection f κ ⟨V, hV⟩ y) :
    (show Γ(AlgebraicGeometry.Scheme.Modules.monoidalPow
        (AlgebraicGeometry.Scheme.Modules.dual L.toModules) m, U) from
      ((AlgebraicGeometry.Scheme.Modules.monoidalPow
        (AlgebraicGeometry.Scheme.Modules.dual L.toModules) m).val.map (CategoryTheory.homOfLE hUV).op).hom
      (((((AlgebraicGeometry.Scheme.Modules.pullbackPushforwardAdjunction ρ.hom).homEquiv _ _)
        (J.weightComponent m)).val.app (Opposite.op V)).hom x)) =
    φ y • (show Γ(AlgebraicGeometry.Scheme.Modules.monoidalPow
        (AlgebraicGeometry.Scheme.Modules.dual L.toModules) m, U) from
      (((truncatedJetAlgebra.pieceIso L m).hom.val.app (Opposite.op U)).hom
        (truncatedJetAlgebra.framePow L U μ m))) := by
  letI := relativeJetScheme.sectionsAlgebra (MMSetup.cone f) V
  letI := baseAlgebra ρ hUV
  set π := (relativeJetScheme (k := k) (MMSetup.cone f) (MMSetup.seed f).1 (MMSetup.seed f).2 κ).hom with hπ
  set Tot := AlgebraicGeometry.Scheme.totalSpace L.toModules with hTot
  -- `Φ₂ : y ↦ Σ_n p^♯(φ(y_n)) · 𝔪^n`
  set Φ₂ : coneJetAlgebra f κ V →+* Γ(Tot.left, Tot.hom ⁻¹ᵁ U) :=
    GradedAlgebra.monomialHom (BasedJetAlgebra.grading
      (relativeJetScheme.augmentation (MMSetup.cone f) (MMSetup.seed f).1 (MMSetup.seed f).2 V) κ)
      ((Tot.hom.app U).hom.comp φ.toRingHom) (frameMonomial L U μ)
      (frameMonomial_zero L U μ) (frameMonomial_add L U μ) with hΦ₂
  -- `Φ₁ = Φ₂`: both are ring maps agreeing on `Γ(V)` and on the generators `d_q c`
  have hΦ : jetPointRingHom f κ ρ L J hV hUV = Φ₂ := by
    apply Ideal.Quotient.ringHom_ext
    apply MvPolynomial.ringHom_ext
    · intro r
      show jetPointRingHom f κ ρ L J hV hUV (algebraMap Γ(C.toScheme, V) (coneJetAlgebra f κ V) r) =
        Φ₂ (algebraMap Γ(C.toScheme, V) (coneJetAlgebra f κ V) r)
      rw [jetPointRingHom_algebraMap, hΦ₂,
        GradedAlgebra.monomialHom_of_mem _ _ _ _ _ (BasedJetAlgebra.algebraMap_mem_grading_zero
          (relativeJetScheme.augmentation (MMSetup.cone f) (MMSetup.seed f).1 (MMSetup.seed f).2 V) κ r),
        frameMonomial_zero, mul_one, RingHom.comp_apply, AlgHom.toRingHom_eq_coe, RingHom.coe_coe, φ.commutes r]
      rfl
    · rintro ⟨q, c⟩
      show jetPointRingHom f κ ρ L J hV hUV (Ideal.Quotient.mk _ (MvPolynomial.X (q, c))) =
        Φ₂ (Ideal.Quotient.mk _ (MvPolynomial.X (q, c)))
      rw [← BasedJetAlgebra.coeffClass_succ
          (relativeJetScheme.augmentation (MMSetup.cone f) (MMSetup.seed f).1 (MMSetup.seed f).2 V) κ q.1 q.2 c,
        jetPointRingHom_coeffClass_of_localJet f κ ρ L J hV hUV μ hU φ hJ q c, hΦ₂,
        GradedAlgebra.monomialHom_of_mem _ _ _ _ _ (BasedJetAlgebra.coeffClass_mem_grading
          (relativeJetScheme.augmentation (MMSetup.cone f) (MMSetup.seed f).1 (MMSetup.seed f).2 V) κ (q.1 + 1) c)]
      rfl
  -- `y` is homogeneous of weight `m`
  have hχ : relativeJetScheme.chartEquiv (k := k) (MMSetup.cone f) (MMSetup.seed f).1 (MMSetup.seed f).2 κ ⟨V, hV⟩ y =
      ((BasedJet.partι f κ m).val.app (Opposite.op V)).hom x :=
    (jetCoordinateSection_eq_chartEquiv f κ ⟨V, hV⟩ y).symm.trans hxy.symm
  have hy : y ∈ BasedJetAlgebra.grading
      (relativeJetScheme.augmentation (MMSetup.cone f) (MMSetup.seed f).1 (MMSetup.seed f).2 V) κ m := by
    have hker : ((GroupSchemeAction.weightDefect
        (jetRescalingAction (k := k) (MMSetup.cone f) (MMSetup.seed f).1 (MMSetup.seed f).2 κ) m).val.app
          (Opposite.op V)).hom (((BasedJet.partι f κ m).val.app (Opposite.op V)).hom x) = 0 :=
      AlgebraicGeometry.Scheme.Modules.kernel_ι_app_apply _ V x
    exact (relativeJetScheme.weightDefect_app_chartEquiv_eq_zero_iff (k := k) (MMSetup.cone f) (MMSetup.seed f).1
      (MMSetup.seed f).2 κ ⟨V, hV⟩ m y).mp
      ((congrArg ((GroupSchemeAction.weightDefect
        (jetRescalingAction (k := k) (MMSetup.cone f) (MMSetup.seed f).1 (MMSetup.seed f).2 κ) m).val.app
          (Opposite.op V)).hom hχ).trans hker)
  -- the main chain
  have hle := totOver_preimage_le_jetPoint_preimage f κ ρ L J V
  have h1 := J.weightComponent_adj_app m V x hle
  refine (congrArg ((AlgebraicGeometry.Scheme.Modules.monoidalPow
    (AlgebraicGeometry.Scheme.Modules.dual L.toModules) m).val.map (CategoryTheory.homOfLE hUV).op).hom h1).trans ?_
  have hnat := PresheafOfModules.naturality_apply (BasedJet.symCoeffHom L m).val (CategoryTheory.homOfLE hUV).op
    ((J.jetPoint.left.appLE (π ⁻¹ᵁ V) ((BasedJet.totOver ρ L).hom ⁻¹ᵁ V) hle).hom
      (((BasedJet.partι f κ m).val.app (Opposite.op V)).hom x))
  refine hnat.symm.trans ?_
  -- the restricted section is `Φ₁ y`
  have hres : (Tot.left.presheaf.map (CategoryTheory.homOfLE (tot_preimage_le_totOver_preimage ρ L hUV)).op).hom
      ((J.jetPoint.left.appLE (π ⁻¹ᵁ V) ((BasedJet.totOver ρ L).hom ⁻¹ᵁ V) hle).hom
        (((BasedJet.partι f κ m).val.app (Opposite.op V)).hom x)) = jetPointRingHom f κ ρ L J hV hUV y := by
    refine (congrArg (fun g : Γ((relativeJetScheme (k := k) (MMSetup.cone f) (MMSetup.seed f).1 (MMSetup.seed f).2 κ).left,
        π ⁻¹ᵁ V) ⟶ Γ(Tot.left, Tot.hom ⁻¹ᵁ U) => g.hom (((BasedJet.partι f κ m).val.app (Opposite.op V)).hom x))
      (AlgebraicGeometry.Scheme.Hom.appLE_map J.jetPoint.left hle
        (CategoryTheory.homOfLE (tot_preimage_le_totOver_preimage ρ L hUV)).op)).trans ?_
    rw [jetPointRingHom_apply, hχ]
    rfl
  refine (congrArg ((BasedJet.symCoeffHom L m).val.app (Opposite.op U)).hom hres).trans ?_
  rw [hΦ, hΦ₂, GradedAlgebra.monomialHom_of_mem _ _ _ _ _ hy]
  -- `symCoeffHom_m (φ y • 𝔪^m) = φ y • pieceIso μ^{⊗m}`
  refine (congrArg ((BasedJet.symCoeffHom L m).val.app (Opposite.op U)).hom
    (pushforward_unit_smul_eq L U (φ y) (frameMonomial L U μ m)).symm).trans ?_
  refine (LinearMap.map_smul ((BasedJet.symCoeffHom L m).val.app (Opposite.op U)).hom (φ y) _).trans ?_
  refine congrArg (fun t : Γ(AlgebraicGeometry.Scheme.Modules.monoidalPow
    (AlgebraicGeometry.Scheme.Modules.dual L.toModules) m, U) => φ y • t) ?_
  have hc : ((truncatedJetAlgebra.pieceIso L m).hom ≫ BasedJet.frameHom L m) ≫ BasedJet.symCoeffHom L m =
      (truncatedJetAlgebra.pieceIso L m).hom := by
    rw [CategoryTheory.Category.assoc, BasedJet.frameHom_symCoeffHom, CategoryTheory.Category.comp_id]
  exact congrArg (fun g : truncatedJetAlgebra.piece L m ⟶ AlgebraicGeometry.Scheme.Modules.monoidalPow
    (AlgebraicGeometry.Scheme.Modules.dual L.toModules) m => (g.val.app (Opposite.op U)).hom
      (truncatedJetAlgebra.framePow L U μ m)) hc

end jetNeighborhood

end
