import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.IdealSheaf.Stacks0agtLeavesQuotFamilies
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0ahhBlowupImproveInvertible
import MiyaokaMori.AlgebraicGeometry.Blowup.SurfaceBlowup

/-! # Twisting a stalk piece by an invertible ideal: `E^d_x/(E^d·I')_x ≅ O_{X,x}/I'_x`

For an invertible ideal sheaf `E` (Stacks 0AGT: `E = O_X(-E)` the exceptional divisor), an ideal
sheaf `I'` and `d : ℕ`, the stalk piece `K_x/J_x ⊆ O_{X,x}/J_x` with `K = E^d`, `J = E^d · I'`
has the same length over `O_{X,x}` as `O_{X,x}/I'_x`: multiplication by `t^d` (`t` a generator of
`E_x`, a nonzerodivisor) is an isomorphism `O_{X,x}/I'_x ≅ t^d O_{X,x}/t^d I'_x`.

This is step 4 of Stacks 0AGT ("`O_X(dE)` is invertible, so `Γ(X, O_X(−dE)/I·O_X)` and
`Γ(X, O_X/I')` have the same length") at the level of stalks; the twisting by `O_X(dE)` is never
formed as a sheaf. `stalkIdeal_pow` comes from `Stacks0ahhBlowupImproveInvertible`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {X : AlgebraicGeometry.Scheme.{u}}

/-- The stalk of an invertible ideal sheaf is principal, generated by a nonzerodivisor
(the germ of a local generator; nonzerodivisors map to nonzerodivisors under localization). -/
theorem exists_stalkIdeal_eq_span_of_isInvertibleIdeal {E : X.IdealSheafData}
    (hE : MiyaokaMori.Statement.IsInvertibleIdeal E) (x : X) :
    ∃ t : X.presheaf.stalk x, t ∈ nonZeroDivisors (X.presheaf.stalk x) ∧
      E.stalkIdeal x = Ideal.span {t} := by
  obtain ⟨U, hxU, a, ha, hEU⟩ := hE x
  refine ⟨X.presheaf.germ U.1 x hxU a, ?_, ?_⟩
  · let _inst := X.presheaf.algebra_section_stalk ⟨x, hxU⟩
    have hloc := U.2.isLocalization_stalk ⟨x, hxU⟩
    have ha' : a ∈ nonZeroDivisors Γ(X, U) :=
      mem_nonZeroDivisors_iff.2 ⟨fun r hr => ha r hr, fun r hr => ha r (by rwa [mul_comm])⟩
    exact IsLocalization.map_nonZeroDivisors_le (U.2.primeIdealOf ⟨x, hxU⟩).asIdeal.primeCompl
      (X.presheaf.stalk x) ⟨a, ha', rfl⟩
  · rw [E.stalkIdeal_eq_map_germ x U hxU, hEU, Ideal.map_span, Set.image_singleton]

/-- **Twisting at a stalk.** `E` invertible: `ℓ_{O_x}(E^d_x / (E^d·I')_x) = ℓ_{O_x}(O_x/I'_x)`.
Proof: `E_x = (t)`, `t` a nonzerodivisor; the `O_x`-linear map `r ↦ r·t^d mod (t^d)·I'_x` has
kernel `I'_x` (cancel `t^d`) and range `(t^d)/(t^d)·I'_x`, the stalk piece. -/
theorem length_stalkPiece_pow_mul_eq {E : X.IdealSheafData}
    (hE : MiyaokaMori.Statement.IsInvertibleIdeal E) (I' : X.IdealSheafData) (d : ℕ) (x : X) :
    Module.length (X.presheaf.stalk x) ((E ^ d * I').stalkPiece (E ^ d) x) =
      Module.length (X.presheaf.stalk x) (X.presheaf.stalk x ⧸ I'.stalkIdeal x) := by
  obtain ⟨t, ht, hEt⟩ := exists_stalkIdeal_eq_span_of_isInvertibleIdeal hE x
  have hK : (E ^ d).stalkIdeal x = Ideal.span {t ^ d} := by
    rw [stalkIdeal_pow, hEt, Ideal.span_singleton_pow]
  have hJ : (E ^ d * I').stalkIdeal x = Ideal.span {t ^ d} * I'.stalkIdeal x := by
    rw [stalkIdeal_mul, hK]
  have htd : t ^ d ∈ nonZeroDivisors (X.presheaf.stalk x) := pow_mem ht d
  let f : X.presheaf.stalk x →ₗ[X.presheaf.stalk x]
      X.presheaf.stalk x ⧸ (E ^ d * I').stalkIdeal x :=
    ((E ^ d * I').stalkIdeal x).mkQ ∘ₗ LinearMap.mulRight (X.presheaf.stalk x) (t ^ d)
  have hker : LinearMap.ker f = I'.stalkIdeal x := by
    ext r
    show ((E ^ d * I').stalkIdeal x).mkQ (r * t ^ d) = 0 ↔ r ∈ I'.stalkIdeal x
    rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero, hJ, Ideal.mem_span_singleton_mul]
    constructor
    · rintro ⟨z, hz, hzr⟩
      have h1 : z * t ^ d = r * t ^ d := by rw [mul_comm z, hzr]
      rw [← (mul_cancel_right_mem_nonZeroDivisors htd).1 h1]
      exact hz
    · intro hr
      exact ⟨r, hr, mul_comm _ _⟩
  have hrange : LinearMap.range f = (E ^ d * I').stalkPiece (E ^ d) x := by
    ext q
    rw [LinearMap.mem_range, stalkPiece, Submodule.mem_map, hK]
    constructor
    · rintro ⟨r, rfl⟩
      exact ⟨r * t ^ d, Ideal.mem_span_singleton'.2 ⟨r, rfl⟩, rfl⟩
    · rintro ⟨k, hk, rfl⟩
      obtain ⟨r, rfl⟩ := Ideal.mem_span_singleton'.1 hk
      exact ⟨r, rfl⟩
  calc Module.length (X.presheaf.stalk x) ((E ^ d * I').stalkPiece (E ^ d) x)
      = Module.length (X.presheaf.stalk x) (LinearMap.range f) := by rw [hrange]
    _ = Module.length (X.presheaf.stalk x) (X.presheaf.stalk x ⧸ LinearMap.ker f) :=
        (LinearMap.quotKerEquivRange f).length_eq.symm
    _ = Module.length (X.presheaf.stalk x) (X.presheaf.stalk x ⧸ I'.stalkIdeal x) := by rw [hker]

end AlgebraicGeometry.Scheme.IdealSheafData

end
