import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffectiveCartierDivisorScheme

/-! # Division of an ideal sheaf by an invertible ideal sheaf

Division of a quasi-coherent ideal sheaf by an invertible ideal sheaf containing it: on a locally
Noetherian scheme, if `E` is invertible (locally generated by a nonzerodivisor) and `J ≤ E`, then
`J = E · I'` for a (unique) quasi-coherent ideal sheaf `I'`, namely the colon sheaf
`I' = (J : E)`. Applied with `E ↦ E^d` this is the construction of `I' := I·O_{W'}(dE)` in
Stacks 0AGT / 0AHH (blow-up improvement step).

Source: Stacks 0AGT proof (first paragraph: "`I' = I O_X(dE)`"); Stacks 01WR (invertible ideal
sheaves are locally free of rank 1); colon ideals commute with localization for finitely generated
divisors (Stacks 00DK / Atiyah–Macdonald 3.15).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- Colon ideals commute with localization when the divisor is finitely generated:
`(J : E)·S = (J·S : E·S)` for `S` a localization of `R` and `E` finitely generated.

Proof. `⊆`: for `r ∈ (J : E)` and a generator `e ∈ E`, `r e ∈ J`, so `r·e ∈ J·S` in `S`.
`⊇`: an element of `S` is `r/m`; for each generator `e` of `E`, `(r/m)·e ∈ J·S` gives `y_e ∈ M` with
`y_e r e ∈ J` (`IsLocalization.mk'_mem_map_algebraMap_iff`); with `u := ∏ y_e ∈ M` we get
`u r ∈ (J : E)`, hence `r/m = (u r)/(u m) ∈ (J : E)·S`. -/
theorem Ideal.map_colon_of_fg {R : Type u} {S : Type v} [CommRing R] [CommRing S] [Algebra R S]
    (M : Submonoid R) [IsLocalization M S] (J E : Ideal R) (hE : E.FG) :
    (J.colon (E : Set R)).map (algebraMap R S) =
      (J.map (algebraMap R S)).colon (E.map (algebraMap R S) : Set S) := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    intro r hr
    rw [Ideal.mem_comap]
    show algebraMap R S r ∈ (J.map (algebraMap R S)).colon (Ideal.span (algebraMap R S '' E) : Set S)
    rw [Submodule.colon_span, Submodule.mem_colon]
    rintro _ ⟨e, he, rfl⟩
    rw [smul_eq_mul, ← map_mul]
    exact Ideal.mem_map_of_mem _ (Submodule.mem_colon.mp hr e he)
  · classical
    intro t ht
    obtain ⟨⟨r, m⟩, rfl⟩ := IsLocalization.mk'_surjective M t
    obtain ⟨s, hs⟩ := hE
    have key : ∀ e ∈ s, ∃ y ∈ M, y * (r * e) ∈ J := by
      intro e he
      have h1 : IsLocalization.mk' S (r * e) m ∈ J.map (algebraMap R S) := by
        rw [mul_comm r e, ← IsLocalization.mul_mk'_eq_mk'_of_mul, mul_comm]
        exact (Submodule.mem_colon.mp ht) (algebraMap R S e)
          (Ideal.mem_map_of_mem _ (hs ▸ Ideal.subset_span he))
      rwa [IsLocalization.mk'_mem_map_algebraMap_iff M] at h1
    choose! y hyM hyJ using key
    have huM : (∏ e ∈ s, y e) ∈ M := Submonoid.prod_mem M fun e he => hyM e he
    have hcolon : (∏ e ∈ s, y e) * r ∈ J.colon (E : Set R) := by
      rw [← hs, Submodule.colon_span, Submodule.mem_colon]
      intro e he
      rw [smul_eq_mul]
      have : (∏ e ∈ s, y e) * r * e = (∏ e' ∈ s.erase e, y e') * (y e * (r * e)) := by
        rw [← Finset.mul_prod_erase s y he]
        ring
      rw [this]
      exact J.mul_mem_left _ (hyJ e he)
    rw [IsLocalization.mk'_mem_map_algebraMap_iff M]
    exact ⟨_, huM, hcolon⟩

namespace AlgebraicGeometry.Scheme.IdealSheafData

/-- The colon ideal sheaf `(J : E)` on a locally Noetherian scheme: `U ↦ (J(U) : E(U))`. It is
quasi-coherent because colon commutes with localization for finitely generated `E(U)`
(`Ideal.map_colon_of_fg`; `Γ(X, U)` is Noetherian). -/
def colonSheaf {X : AlgebraicGeometry.Scheme.{u}} [AlgebraicGeometry.IsLocallyNoetherian X]
    (J E : X.IdealSheafData) : X.IdealSheafData where
  ideal U := (J.ideal U).colon (E.ideal U : Set Γ(X, U))
  map_ideal_basicOpen U f := by
    have hloc := U.2.isLocalization_basicOpen f
    have : IsNoetherianRing Γ(X, U) := AlgebraicGeometry.IsLocallyNoetherian.component_noetherian U
    have hfg : (E.ideal U).FG := IsNoetherian.noetherian _
    have h := Ideal.map_colon_of_fg (S := Γ(X, X.basicOpen f)) (Submonoid.powers f) (J.ideal U)
      (E.ideal U) hfg
    have halg : algebraMap Γ(X, U) Γ(X, X.basicOpen f) =
        (X.presheaf.map (homOfLE (X.basicOpen_le f)).op).hom := rfl
    rw [halg] at h
    rw [h, J.map_ideal_basicOpen, E.map_ideal_basicOpen]
    rfl

theorem colonSheaf_ideal {X : AlgebraicGeometry.Scheme.{u}} [AlgebraicGeometry.IsLocallyNoetherian X]
    (J E : X.IdealSheafData) (U : X.affineOpens) :
    (colonSheaf J E).ideal U = (J.ideal U).colon (E.ideal U : Set Γ(X, U)) := rfl

/-- **Division by an invertible ideal sheaf.** `X` locally Noetherian, `E` invertible, `J ≤ E`
⇒ `∃ I', J = E * I'` (namely `I' = colonSheaf J E`).

Proof. `E · (J : E) ≤ J` on every affine open (`Submodule.mem_colon`). Conversely, on an affine open
`U` with `E(U) = (a)`, `a` a nonzerodivisor (definition of `IsInvertibleIdeal`), every `j ∈ J(U) ⊆ (a)`
is `r·a` with `r ∈ (J(U) : (a))`, so `j ∈ E(U)·(J(U) : E(U))`. These `U` cover `X`
(`ext_of_iSup_eq_top`). Uniqueness is `eq_of_pow_mul_eq_pow_mul` (`d = 1`). -/
theorem exists_eq_mul_of_le_of_isInvertibleIdeal {X : AlgebraicGeometry.Scheme.{u}}
    [AlgebraicGeometry.IsLocallyNoetherian X] {E J : X.IdealSheafData}
    (hE : MiyaokaMori.Statement.IsInvertibleIdeal E) (hJ : J ≤ E) :
    ∃ I' : X.IdealSheafData, J = E * I' := by
  refine ⟨colonSheaf J E, ?_⟩
  choose U hxU a ha hEU using hE
  refine ext_of_iSup_eq_top U ?_ fun x => ?_
  · rw [eq_top_iff]
    intro y _
    exact Opens.mem_iSup.mpr ⟨y, hxU y⟩
  rw [ideal_mul, Pi.mul_apply, colonSheaf_ideal]
  apply le_antisymm
  · rw [hEU x]
    intro j hj
    have hj' : j ∈ E.ideal (U x) := hJ (U x) hj
    rw [hEU x, Ideal.mem_span_singleton'] at hj'
    obtain ⟨r, rfl⟩ := hj'
    rw [mul_comm r]
    refine Ideal.mul_mem_mul (Ideal.mem_span_singleton_self _) ?_
    rw [Submodule.mem_colon]
    intro s hs
    rw [SetLike.mem_coe, Ideal.mem_span_singleton'] at hs
    obtain ⟨b, rfl⟩ := hs
    have : r • (b * a x) = b * (r * a x) := by rw [smul_eq_mul]; ring
    rw [this]
    exact (J.ideal (U x)).mul_mem_left b hj
  · rw [Ideal.mul_le]
    intro e he r hr
    rw [mul_comm]
    exact Submodule.mem_colon.mp hr e he

end AlgebraicGeometry.Scheme.IdealSheafData

end
