import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.ZeroSchemeOfSection
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.Frame
import MiyaokaMori.AlgebraicGeometry.Chow.Cycles.AlgebraicCycles

/-! # Stalks of a closed subscheme

The local ring of a closed subscheme `Z = V(I)` at a point `z′`: the stalk map `O_{X,z} → O_{Z,z′}`
(`z = ι z′`) of `ι : Z → X` is surjective, and its kernel is the ideal generated by `I(U)` in the
stalk `O_{X,z}` (`U` any affine open containing `z`); hence `O_{Z,z′} ≅ O_{X,z}/I_z` and
`length_{O_{X,z}} O_{Z,z′} = length (O_{X,z}/I_z)`. For the zero scheme `Z(σ)`
(`idealSheafOfSection`), on an affine open `W` with a frame `e` one has `I(W) = (c)` where `c` is
the coordinate of `σ|_W` in the frame `e` (`σ|_W = c·e`), so `I_z = (f)` with `f = germ_z c`.

Sources: Stacks 01QP/01QQ (stalks of a quasi-coherent ideal sheaf are localizations of the ideal;
stalk maps of closed immersions are surjective), Stacks 01WX/01X0 (the ideal sheaf of `Z(σ)` is
`(f)` on a frame). Mathlib: `IdealSheafData.ker_subschemeι_app` (`ker (ι^♯_U) = I(U)`),
`IdealSheafData.map_ideal` (`I(V) = I(U)·Γ(X,V)`), `Scheme.Hom.germ_stalkMap_apply`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {X : AlgebraicGeometry.Scheme.{u}} (I : X.IdealSheafData)

/-- Elements of `I(U)` vanish in the stalks of `Z = V(I)` (`ker (ι^♯_U) = I(U)`, `ker_subschemeι_app`). -/
theorem stalkMap_subschemeι_germ_eq_zero (U : X.affineOpens) (z' : I.subscheme)
    (hz : I.subschemeι.base z' ∈ U.1) {a : Γ(X, U.1)} (ha : a ∈ I.ideal U) :
    I.subschemeι.stalkMap z' (X.presheaf.germ U.1 (I.subschemeι.base z') hz a) = 0 := by
  rw [AlgebraicGeometry.Scheme.Hom.germ_stalkMap_apply]
  have h0 : I.subschemeι.app U.1 a = 0 := by
    rw [← I.ker_subschemeι_app U] at ha
    exact ha
  rw [h0, map_zero]

/-- **Kernel of the stalk map of a closed subscheme**: `ker (O_{X,z} → O_{Z,z′}) = I(U)·O_{X,z}` (`U`
any affine open containing `z = ι z′`).
Proof: `⊇` by `stalkMap_subschemeι_germ_eq_zero`. `⊆`: an element `a` of the kernel is the germ of a
section `a_V` on some `V ≤ U`; the germ of `ι^♯_V(a_V)` at `z′` is zero, so it vanishes on an open
neighbourhood `W₁ = ι⁻¹(O)` of `z′`; take an affine `V₂ ∋ z` with `V₂ ≤ O ⊓ V`; then
`ι^♯_{V₂}(a_V|_{V₂}) = ι^♯_V(a_V)|_{ι⁻¹V₂} = 0`, i.e. `a_V|_{V₂} ∈ ker ι^♯_{V₂} = I(V₂) = I(U)·Γ(X,V₂)`
(`map_ideal`), and taking germs gives `a ∈ I(U)·O_{X,z}`. -/
theorem ker_stalkMap_subschemeι (U : X.affineOpens) (z' : I.subscheme)
    (hz : I.subschemeι.base z' ∈ U.1) :
    RingHom.ker (I.subschemeι.stalkMap z').hom =
      (I.ideal U).map (X.presheaf.germ U.1 (I.subschemeι.base z') hz).hom := by
  apply le_antisymm
  · intro a ha
    rw [RingHom.mem_ker] at ha
    obtain ⟨V, hVU, hzV, aV, rfl⟩ := X.presheaf.exists_le_germ_eq a hz
    rw [AlgebraicGeometry.Scheme.Hom.germ_stalkMap_apply] at ha
    have ha' : I.subscheme.presheaf.germ (I.subschemeι ⁻¹ᵁ V) z' hzV (I.subschemeι.app V aV) =
        I.subscheme.presheaf.germ (I.subschemeι ⁻¹ᵁ V) z' hzV 0 := by
      rw [ha, map_zero]
    obtain ⟨W₁, hzW₁, iU, iV, heq⟩ := I.subscheme.presheaf.germ_eq z' hzV hzV _ _ ha'
    rw [map_zero] at heq
    obtain ⟨O, hO, hOW₁⟩ := I.subschemeι.isEmbedding.isInducing.isOpen_iff.mp W₁.isOpen
    have hzO : I.subschemeι.base z' ∈ (⟨O, hO⟩ : X.Opens) := by
      have : z' ∈ I.subschemeι.base ⁻¹' O := by rw [hOW₁]; exact hzW₁
      exact this
    obtain ⟨_, ⟨V₂, hV₂, rfl⟩, hzV₂, hV₂le⟩ := X.isBasis_affineOpens.exists_subset_of_mem_open
      (show I.subschemeι.base z' ∈ ((⟨O, hO⟩ : X.Opens) ⊓ V : X.Opens) from ⟨hzO, hzV⟩)
      ((⟨O, hO⟩ : X.Opens) ⊓ V).isOpen
    have hV₂V : V₂ ≤ V := fun x hx => (hV₂le hx).2
    have hV₂O : V₂ ≤ (⟨O, hO⟩ : X.Opens) := fun x hx => (hV₂le hx).1
    have hV₂U : (⟨V₂, hV₂⟩ : X.affineOpens) ≤ U := hV₂V.trans hVU
    have hpre : I.subschemeι ⁻¹ᵁ V₂ ≤ W₁ := by
      intro y hy
      have : y ∈ I.subschemeι.base ⁻¹' O := hV₂O hy
      rw [hOW₁] at this
      exact this
    -- a_V|_{V₂} ∈ I(V₂)
    have hmem : X.presheaf.map (homOfLE hV₂V).op aV ∈ I.ideal ⟨V₂, hV₂⟩ := by
      rw [← I.ker_subschemeι_app ⟨V₂, hV₂⟩, RingHom.mem_ker]
      have hnat := congrArg (fun φ => φ aV)
        (CommRingCat.hom_ext_iff.mp (I.subschemeι.naturality (homOfLE hV₂V).op))
      simp only [CommRingCat.hom_comp, RingHom.comp_apply, Quiver.Hom.unop_op] at hnat
      change I.subschemeι.app V₂ (X.presheaf.map (homOfLE hV₂V).op aV) = 0
      rw [hnat]
      have h1 : I.subscheme.presheaf.map ((Opens.map I.subschemeι.base).map (homOfLE hV₂V)).op
          (I.subschemeι.app V aV) =
          I.subscheme.presheaf.map (homOfLE hpre).op (I.subscheme.presheaf.map iU.op
            (I.subschemeι.app V aV)) := by
        conv_rhs => rw [← ConcreteCategory.comp_apply, ← Functor.map_comp]
        rfl
      rw [h1, heq, map_zero]
    rw [← I.map_ideal hV₂U] at hmem
    have hgerm : X.presheaf.germ V (I.subschemeι.base z') hzV aV =
        X.presheaf.germ V₂ (I.subschemeι.base z') hzV₂ (X.presheaf.map (homOfLE hV₂V).op aV) :=
      (X.presheaf.germ_res_apply (homOfLE hV₂V) _ hzV₂ aV).symm
    rw [hgerm]
    have hcomp : (X.presheaf.germ V₂ (I.subschemeι.base z') hzV₂).hom.comp
        (X.presheaf.map (homOfLE (show V₂ ≤ U.1 from hV₂U)).op).hom =
        (X.presheaf.germ U.1 (I.subschemeι.base z') hz).hom := by
      rw [← CommRingCat.hom_comp, X.presheaf.germ_res]
    rw [← hcomp, ← Ideal.map_map]
    exact Ideal.mem_map_of_mem _ hmem
  · rw [Ideal.map_le_iff_le_comap]
    intro a ha
    rw [Ideal.mem_comap, RingHom.mem_ker]
    exact I.stalkMap_subschemeι_germ_eq_zero U z' hz ha

/-- The length of `O_{Z,z′}` as an `O_{X,z}`-module equals `length (O_{X,z}/I_z)` (the stalk map is
surjective with the kernel of the previous theorem). -/
theorem closedSubschemeStalkLength_subschemeι_eq (U : X.affineOpens) (z' : I.subscheme)
    (hz : I.subschemeι.base z' ∈ U.1) :
    AlgebraicGeometry.Intersection.closedSubschemeStalkLength I.subschemeι z' =
      Module.length (X.presheaf.stalk (I.subschemeι.base z'))
        (X.presheaf.stalk (I.subschemeι.base z') ⧸
          (I.ideal U).map (X.presheaf.germ U.1 (I.subschemeι.base z') hz).hom) := by
  let _ : Algebra (X.presheaf.stalk (I.subschemeι.base z')) (I.subscheme.presheaf.stalk z') :=
    (I.subschemeι.stalkMap z').hom.toAlgebra
  change Module.length (X.presheaf.stalk (I.subschemeι.base z')) (I.subscheme.presheaf.stalk z') = _
  have hs : Function.Surjective
      (Algebra.linearMap (X.presheaf.stalk (I.subschemeι.base z')) (I.subscheme.presheaf.stalk z')) :=
    fun b => I.subschemeι.stalkMap_surjective z' b
  rw [← (LinearMap.quotKerEquivOfSurjective _ hs).length_eq]
  refine (Submodule.quotEquivOfEq _ _ ?_).length_eq
  rw [← I.ker_stalkMap_subschemeι U z' hz]
  ext a
  simp only [LinearMap.mem_ker, Algebra.linearMap_apply, RingHom.mem_ker, RingHom.algebraMap_toAlgebra]

end AlgebraicGeometry.Scheme.IdealSheafData

namespace AlgebraicGeometry.Scheme

/-- The ideal of the zero scheme `Z(σ)` on an affine open `W` with a frame `e` is the principal ideal
`(c)`, where `c` is the coordinate of `σ|_W` in `e` (`σ|_W = c • e`). -/
theorem idealSheafOfSection_ideal_eq_span_coord {X : AlgebraicGeometry.Scheme.{u}} (L : X.Modules)
    [L.IsLineBundle] (σ : (L.val.obj (Opposite.op ⊤) : Type u)) {W : X.Opens} (hW : IsAffineOpen W)
    {e : Γ(L, W)} (hf : AlgebraicGeometry.Scheme.Modules.IsFrame L W e) :
    (AlgebraicGeometry.Scheme.idealSheafOfSection L σ).ideal ⟨W, hW⟩ =
      Ideal.span {hf.coord le_rfl (L.res (le_top : W ≤ ⊤) (show Γ(L, ⊤) from σ))} := by
  set σW : Γ(L, W) := L.res (le_top : W ≤ ⊤) (show Γ(L, ⊤) from σ) with hσW
  set c := hf.coord le_rfl σW with hcdef
  have hc : c • L.res le_rfl e = σW := hf.coord_smul_frame le_rfl σW
  apply le_antisymm
  · show Ideal.span (Set.range fun φ : Γ(L, W) →ₗ[Γ(X, W)] Γ(X, W) =>
      φ (L.presheaf.map (CategoryTheory.homOfLE le_top).op (show Γ(L, ⊤) from σ))) ≤ _
    rw [Ideal.span_le]
    rintro _ ⟨φ, rfl⟩
    show φ σW ∈ Ideal.span {c}
    rw [← hc, map_smul, smul_eq_mul]
    exact Ideal.mul_mem_right _ _ (Ideal.mem_span_singleton_self c)
  · rw [Ideal.span_le, Set.singleton_subset_iff]
    show c ∈ Ideal.span (Set.range fun φ : Γ(L, W) →ₗ[Γ(X, W)] Γ(X, W) =>
      φ (L.presheaf.map (CategoryTheory.homOfLE le_top).op (show Γ(L, ⊤) from σ)))
    exact Ideal.subset_span ⟨(hf.coordEquiv le_rfl).toLinearMap, rfl⟩

end AlgebraicGeometry.Scheme

end
