import MiyaokaMori.Prelude

/-! # Expanding a product `∏ (H + aⱼ)` when pairwise products vanish

A purely algebraic identity, stated with an additive map `φ`: in a commutative ring `R`, if
`φ(aᵢ aⱼ y) = 0` for all distinct indices `i ≠ j` in `s` and all `y ∈ R`, then
`φ(∏_{j ∈ s} (H + aⱼ)) = φ(H^{|s|}) + ∑_{j ∈ s} φ(H^{|s|-1} aⱼ)`.
When expanding the weighted relation ((2.10) of the paper), `R` is the commutative
algebra generated by the Chow endomorphisms and `φ` is "act on `[Y^sp]`, take the 0-dimensional
component, take the degree".
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

theorem Finset.map_prod_add_of_map_mul_mul_eq_zero {R M : Type*} [CommRing R] [AddCommGroup M]
    {ι : Type*} [DecidableEq ι] (s : Finset ι) (hs : s.Nonempty) (φ : R →+ M) (H : R) (a : ι → R)
    (ha : ∀ i ∈ s, ∀ j ∈ s, i ≠ j → ∀ y : R, φ (a i * a j * y) = 0) :
    φ (∏ j ∈ s, (H + a j)) = φ (H ^ s.card) + ∑ j ∈ s, φ (H ^ (s.card - 1) * a j) := by
  clear hs
  revert φ H a ha
  induction s using Finset.induction_on with
  | empty =>
      intro φ H a ha
      simp
  | @insert x t hx ih =>
      intro φ H a ha
      have ha_t : ∀ i ∈ t, ∀ j ∈ t, i ≠ j → ∀ y : R, φ (a i * a j * y) = 0 := by
        intro i hi j hj hij y
        exact ha i (Finset.mem_insert_of_mem hi) j (Finset.mem_insert_of_mem hj) hij y
      let ψH : R →+ M :=
        { toFun := fun y => φ (H * y)
          map_zero' := by simp
          map_add' := by
            intro y z
            rw [mul_add, φ.map_add] }
      let ψa : R →+ M :=
        { toFun := fun y => φ (a x * y)
          map_zero' := by simp
          map_add' := by
            intro y z
            rw [mul_add, φ.map_add] }
      have haH : ∀ i ∈ t, ∀ j ∈ t, i ≠ j → ∀ y : R,
          ψH (a i * a j * y) = 0 := by
        intro i hi j hj hij y
        dsimp [ψH]
        simpa [mul_assoc, mul_left_comm, mul_comm] using
          ha i (Finset.mem_insert_of_mem hi) j (Finset.mem_insert_of_mem hj) hij (H * y)
      have haa : ∀ i ∈ t, ∀ j ∈ t, i ≠ j → ∀ y : R,
          ψa (a i * a j * y) = 0 := by
        intro i hi j hj hij y
        dsimp [ψa]
        simpa [mul_assoc, mul_left_comm, mul_comm] using
          ha i (Finset.mem_insert_of_mem hi) j (Finset.mem_insert_of_mem hj) hij (a x * y)
      have hH := ih ψH H a haH
      have hA := ih ψa H a haa
      have hcross : ∀ j ∈ t, ψa (H ^ (t.card - 1) * a j) = 0 := by
        intro j hj
        dsimp [ψa]
        simpa [mul_assoc, mul_left_comm, mul_comm] using
          ha x (Finset.mem_insert_self x t) j (Finset.mem_insert_of_mem hj) (by
            intro h
            subst h
            exact hx hj) (H ^ (t.card - 1))
      rw [Finset.prod_insert hx]
      rw [add_mul, φ.map_add]
      rw [show φ (H * ∏ j ∈ t, (H + a j)) = ψH (∏ j ∈ t, (H + a j)) by rfl]
      rw [show φ (a x * ∏ j ∈ t, (H + a j)) = ψa (∏ j ∈ t, (H + a j)) by rfl]
      rw [hH, hA]
      simp only [Finset.card_insert_of_notMem hx]
      simp only [Finset.sum_insert hx]
      have hcardexp : t.card + 1 - 1 = t.card := by omega
      have hpowH : ψH (H ^ t.card) = φ (H ^ (t.card + 1)) := by
        dsimp [ψH]
        rw [pow_succ']
      have hpowA : ψa (H ^ t.card) = φ (H ^ t.card * a x) := by
        dsimp [ψa]
        rw [mul_comm]
      have hsumH : (∑ j ∈ t, ψH (H ^ (t.card - 1) * a j)) =
          ∑ j ∈ t, φ (H ^ t.card * a j) := by
        apply Finset.sum_congr rfl
        intro j hj
        dsimp [ψH]
        have hjcard : 0 < t.card := Finset.card_pos.mpr ⟨j, hj⟩
        rw [← mul_assoc, ← pow_succ' H (t.card - 1), Nat.sub_add_cancel hjcard]
      have hsumA : (∑ j ∈ t, ψa (H ^ (t.card - 1) * a j)) = 0 := by
        apply Finset.sum_eq_zero
        intro j hj
        exact hcross j hj
      rw [hpowH, hpowA, hsumH, hsumA, hcardexp]
      abel

end
