import MiyaokaMori.Prelude
import MiyaokaMori.RingTheory.GradedRing.ReesAwayAffineBlowup
import MiyaokaMori.AlgebraicGeometry.Blowup.Stacks0agrChartPresentation

/-! # The two charts `(Rees J)_{(aX)}`, `(Rees J)_{(bX)}` of the Rees algebra and their overlap

Ring-level facts about the two charts `D₊(aX)`, `D₊(bX)` of `Proj (⊕ₙ Jⁿ Xⁿ)` for `J = (a, b)`,
used for the surjectivity of the sections of the blowup onto the quotient families (Stacks 0AGS(3)
in Čech form).

General graded-ring part (`𝒜` any `ℕ`-graded ring, `f ∈ 𝒜 d`, `g ∈ 𝒜 e`, `x = f g`;
`t = gᵈ/fᵉ ∈ 𝒜_{(f)}` is Mathlib's `HomogeneousLocalization.Away.isLocalizationElem`):
* `awayMap_isLocalizationElem_mul_awayMap_isLocalizationElem`: in `𝒜_{(fg)}`, the images of
  `t = gᵈ/fᵉ ∈ 𝒜_{(f)}` and `t' = fᵉ/gᵈ ∈ 𝒜_{(g)}` are inverse to each other;
* `exists_mul_awayMap_isLocalizationElem_pow_eq`: `𝒜_{(fg)} = 𝒜_{(f)}[1/t]` in the form
  "every `z` satisfies `z · tⁿ ∈ 𝒜_{(f)}` for some `n`" (from Mathlib's `Away.isLocalization_mul`).

Rees-algebra part (`J = (a, b)`, `𝒜 = J.reesGrading`, `f = aX`, `g = bX` of degree `1`):
* `reesAwayEquivAffineBlowup_isLocalizationElem`: under `(Rees J)_{(aX)} ≃ A[J/a]`
  (`Ideal.reesAwayEquivAffineBlowup`), `t = bX/aX ↦ b/a`;
* `exists_eval₂_isLocalizationElem_eq`: `(Rees J)_{(aX)} = A[t]` — every element is a polynomial in
  `t` over `A` (from the presentation `A[T] ↠ A[J/a]`, `T ↦ b/a`,
  `affineBlowupPresentation_surjective`);
* `reesX_mem_span_pair`, `reesGrading_basicOpen_sup_basicOpen_eq_top`: `D₊(aX) ∪ D₊(bX) = Proj`
  (the irrelevant ideal is generated by `J·X ⊆ (aX, bX)`).

Source: Stacks 0AGS proof / 0804 (charts of the blowup); Hartshorne II.7 (`Proj`, `D₊`).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open Polynomial

noncomputable section

namespace HomogeneousLocalization

variable {ι R A : Type*} [AddCommMonoid ι] [DecidableEq ι] [CommRing A] [CommRing R] [Algebra R A]
variable {σ : Type*} [SetLike σ A] [AddSubgroupClass σ A]
variable {𝒜 : ℕ → σ} [GradedRing 𝒜]
variable {d e : ℕ} {f g x : A} (hf : f ∈ 𝒜 d) (hg : g ∈ 𝒜 e) (hx : x = f * g)

/-- In `𝒜_{(fg)}`, the images of `gᵈ/fᵉ ∈ 𝒜_{(f)}` and `fᵉ/gᵈ ∈ 𝒜_{(g)}` multiply to `1`. -/
theorem awayMap_isLocalizationElem_mul_awayMap_isLocalizationElem :
    awayMap 𝒜 hg hx (Away.isLocalizationElem hf hg) *
      awayMap 𝒜 hf (hx.trans (mul_comm f g)) (Away.isLocalizationElem hg hf) = 1 := by
  apply HomogeneousLocalization.val_injective
  simp only [Away.isLocalizationElem, awayMap_mk, val_mul, val_one, Away.val_mk, Localization.mk_mul]
  rw [← Localization.mk_one, Localization.mk_eq_mk_iff, Localization.r_iff_exists]
  refine ⟨1, ?_⟩
  simp only [OneMemClass.coe_one, one_mul, mul_one, Submonoid.coe_mul, hx]
  ring

/-- `𝒜_{(fg)} = 𝒜_{(f)}[1/t]`, `t = gᵈ/fᵉ`: every `z ∈ 𝒜_{(fg)}` satisfies `z · tⁿ ∈ 𝒜_{(f)}`
for some `n` (Mathlib `HomogeneousLocalization.Away.isLocalization_mul`). -/
theorem exists_mul_awayMap_isLocalizationElem_pow_eq (hd : d ≠ 0) (z : Away 𝒜 x) :
    ∃ (b : Away 𝒜 f) (n : ℕ),
      z * awayMap 𝒜 hg hx (Away.isLocalizationElem hf hg) ^ n = awayMap 𝒜 hg hx b := by
  let _ := (awayMap 𝒜 hg hx).toAlgebra
  let _ := Away.isLocalization_mul hf hg hx hd
  obtain ⟨⟨b, s⟩, h⟩ := IsLocalization.surj (Submonoid.powers (Away.isLocalizationElem hf hg)) z
  obtain ⟨n, hn⟩ := s.2
  refine ⟨b, n, ?_⟩
  simp only [RingHom.algebraMap_toAlgebra] at h
  rw [← map_pow, show Away.isLocalizationElem hf hg ^ n = (s : Away 𝒜 f) from hn]
  exact h

end HomogeneousLocalization

namespace Ideal

variable {A : Type u} [CommRing A] (J : Ideal A) (a b : A) (ha : a ∈ J) (hb : b ∈ J)

/-- Under `(Rees J)_{(aX)} ≃ A[J/a]`, the element `t = bX/aX` corresponds to `b/a`. -/
theorem reesAwayEquivAffineBlowup_isLocalizationElem :
    J.reesAwayEquivAffineBlowup a ha
        (HomogeneousLocalization.Away.isLocalizationElem (J.reesX_mem a ha) (J.reesX_mem b hb)) =
      J.affineBlowupFraction a b hb := by
  apply Subtype.ext
  rw [reesAwayEquivAffineBlowup_apply, coe_reesAwayToAffineBlowup, coe_affineBlowupFraction]
  erw [reesAwayToLocalization_mk J a ha 1]
  rw [pow_one, reesEvalOne_reesX]
  congr 1
  exact Subtype.ext (pow_one a)

/-- `(Rees J)_{(aX)} = A[t]`, `t = bX/aX`, when `J = (a, b)`: every element is `p(t)` for a polynomial
`p` over `A` (through any ring map `ψ : A → (Rees J)_{(aX)}` equal to `r ↦ (r X⁰)/1`). Proof: transport
`affineBlowupPresentation_surjective` (`A[T] ↠ A[J/a]`, `T ↦ b/a`) along
`Ideal.reesAwayEquivAffineBlowup`, using `reesAwayEquivAffineBlowup_isLocalizationElem` and
`reesAwayEquivAffineBlowup_fromZeroRingHom`. -/
theorem exists_eval₂_isLocalizationElem_eq (hJ : J = Ideal.span {a, b})
    (ψ : A →+* HomogeneousLocalization.Away J.reesGrading (J.reesX a ha))
    (hψ : ∀ r, ψ r = HomogeneousLocalization.fromZeroRingHom _ _
      ⟨algebraMap A (reesAlgebra J) r, J.algebraMap_mem_reesGrading_zero r⟩)
    (z : HomogeneousLocalization.Away J.reesGrading (J.reesX a ha)) :
    ∃ p : A[X], p.eval₂ ψ
      (HomogeneousLocalization.Away.isLocalizationElem (J.reesX_mem a ha) (J.reesX_mem b hb)) = z := by
  set ε := J.reesAwayEquivAffineBlowup a ha
  obtain ⟨p, hp⟩ := J.affineBlowupPresentation_surjective a b hb hJ (ε z)
  refine ⟨p, ε.injective ?_⟩
  rw [← hp, affineBlowupPresentation, Polynomial.aeval_def]
  have h1 := Polynomial.hom_eval₂ p ψ
    (ε : HomogeneousLocalization.Away J.reesGrading (J.reesX a ha) →+* J.affineBlowup a)
    (HomogeneousLocalization.Away.isLocalizationElem (J.reesX_mem a ha) (J.reesX_mem b hb))
  simp only [RingEquiv.coe_toRingHom] at h1
  rw [h1, reesAwayEquivAffineBlowup_isLocalizationElem]
  congr 1
  refine RingHom.ext fun r => ?_
  rw [RingHom.comp_apply, hψ, RingEquiv.coe_toRingHom]
  exact J.reesAwayEquivAffineBlowup_fromZeroRingHom a ha r

/-- `cX ∈ (aX, bX)` in the Rees algebra for `c ∈ J = (a, b)`: `c = αa + βb` gives
`cX = α·(aX) + β·(bX)`. -/
theorem reesX_mem_span_pair (hJ : J = Ideal.span {a, b}) (c : A) (hc : c ∈ J) :
    J.reesX c hc ∈ Ideal.span {J.reesX a ha, J.reesX b hb} := by
  have hc' : c ∈ Ideal.span {a, b} := hJ ▸ hc
  obtain ⟨α, β, hαβ⟩ := Ideal.mem_span_pair.mp hc'
  have : J.reesX c hc =
      algebraMap A (reesAlgebra J) α * J.reesX a ha + algebraMap A (reesAlgebra J) β * J.reesX b hb := by
    apply Subtype.ext
    rw [Subalgebra.coe_add, Subalgebra.coe_mul, Subalgebra.coe_mul, coe_reesX, coe_reesX, coe_reesX,
      Subalgebra.coe_algebraMap, Subalgebra.coe_algebraMap, Polynomial.algebraMap_eq,
      Polynomial.C_mul_monomial, Polynomial.C_mul_monomial, ← map_add, hαβ]
  rw [this]
  exact Ideal.add_mem _ (Ideal.mul_mem_left _ _ (Ideal.subset_span (Set.mem_insert _ _)))
    (Ideal.mul_mem_left _ _ (Ideal.subset_span (Set.mem_insert_of_mem _ (Set.mem_singleton _))))

/-- **The two charts cover `Proj (Rees J)`**: `D₊(aX) ∪ D₊(bX) = Proj` when `J = (a, b)` (the
irrelevant ideal `⊕_{n≥1} Jⁿ Xⁿ` is generated by `J·X`, `reesGrading_irrelevant_le_span`, and
`J·X ⊆ (aX, bX)`, `reesX_mem_span_pair`). -/
theorem reesGrading_basicOpen_sup_basicOpen_eq_top (hJ : J = Ideal.span {a, b}) :
    AlgebraicGeometry.Proj.basicOpen J.reesGrading (J.reesX a ha) ⊔
      AlgebraicGeometry.Proj.basicOpen J.reesGrading (J.reesX b hb) = ⊤ := by
  have h := AlgebraicGeometry.Proj.iSup_basicOpen_eq_top J.reesGrading
    (fun c : Bool => cond c (J.reesX a ha) (J.reesX b hb)) ?_
  · rwa [iSup_bool_eq] at h
  · refine J.reesGrading_irrelevant_le_span.trans (Ideal.span_le.mpr ?_)
    rintro _ ⟨c, rfl⟩
    refine Ideal.span_mono ?_ (J.reesX_mem_span_pair a b ha hb hJ c c.2)
    rintro _ (rfl | rfl)
    · exact ⟨true, rfl⟩
    · exact ⟨false, rfl⟩

end Ideal

end
