import MiyaokaMori.Prelude
import MiyaokaMori.RingTheory.PolynomialRingN2
import Mathlib.RingTheory.NoetherNormalization
import Mathlib.RingTheory.Jacobson.Ring
import Mathlib.RingTheory.Ideal.MinimalPrime.Noetherian
import Mathlib.FieldTheory.AlgebraicClosure

/-! # Finiteness of the integral closure over a finite type algebra over a field

A finite type algebra `A` over a field is a Nagata ring (Stacks 035B/0335); hence for every reduced
algebra `C` of finite type over `A`, the integral closure of `A` in `C` is a finite `A`-module
(Stacks 03GH; the ring-theoretic form of 035S).

References: Stacks 035B (morphisms-lemma-ubiquity-nagata), 0335
(algebra-proposition-ubiquity-nagata), 0334 (finite type algebras over a Nagata ring are Nagata),
03GH (algebra-lemma-nagata-in-reduced-finite-type-finite-integral-closure).

## Proof structure

The Nagata-ring theory (Stacks 032E–0335, absent from Mathlib) is **not** used. Instead the statement
is reduced, following the proof of Stacks 03GH, to the single ring-theoretic fact "polynomial rings
over `k` are N-2" (`Field.PolynomialRingsN2 k`, module `Stacks035b_PolynomialN2`), whose
characteristic-`0` case is Mathlib's `IsIntegralClosure.finite` and whose characteristic-`p` case
(`Field.polynomialRingsN2_of_charP`, arbitrary field) is proved there by E. Noether's `q`-th root
argument in Frobenius form.

1. `MvPolynomial.module_finite_integralClosure_of_finiteType_isDomain` (**L3**): `P = k[x_1..x_d] ⊆ D`
   a domain of finite type over `P` ⇒ `integralClosure P D` is a finite `P`-module. Zariski's lemma
   (Mathlib `finite_of_algHom_finiteType_of_isJacobsonRing`) replaces Stacks 037J, and N-2 for `P`
   replaces the Nagata hypothesis.
2. `Algebra.module_finite_integralClosure_of_finiteType_isDomain` (**L2**): `A` of finite type over
   `k`, `D` a domain of finite type over `A` ⇒ `integralClosure A D` finite over `A`: replace `A` by
   its image `A' = A ⧸ ker` in `D` (a domain), apply Noether normalization `P ⊆ A'` and L3.
3. `Algebra.finite_integralClosure_of_finiteType_over_field_of_polynomialRingsN2` (**L1**, the
   reduction of 03GH): `C` reduced Noetherian embeds into the finite product of the `C ⧸ q`, `q` a
   minimal prime; apply L2 to each factor and use that `A` is Noetherian.
4. `Algebra.finite_integralClosure_of_finiteType_over_field` (the main statement) = L1 applied
   with `Field.polynomialRingsN2 k`; `Algebra.finite_integralClosure_of_finiteType_over_field_of_charZero`
   is the same statement for `[CharZero k]`, using only the characteristic-`0` case of N-2.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000
set_option linter.style.haveILetI false

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- **L3 (polynomial base ring).** Let `P = k[x_1, …, x_d] ⊆ D` with `D` a domain of finite type over
`P`. If polynomial rings over `k` are N-2 (`hk`), then the integral closure of `P` in `D` is a
finite `P`-module.

Source: the proof of Stacks 03GH (algebra-lemma-nagata-in-reduced-finite-type-finite-integral-closure),
domain case, with Stacks 037J replaced by Zariski's lemma.

Proof (matching the Lean):
1. Let `K = Frac D` and `F = Frac P ⊆ K` (`FractionRing.liftAlgebra`). Let `T ⊆ K` be the
   `F`-subalgebra generated by (the image of) `D`; it is generated by the finitely many `P`-generators
   of `D`, so `T` is a finite type `F`-algebra (and a domain).
2. Let `G ⊆ T` be the set of elements of `T` algebraic over `F`; it is a subalgebra, and since it is
   algebraic over the field `F` it is a subfield `G'` of `K` (`Algebra.IsAlgebraic.toIntermediateField`).
   By Zariski's lemma in the form Mathlib `finite_of_algHom_finiteType_of_isJacobsonRing` (a subfield
   of a nontrivial finite type algebra over the Jacobson Noetherian ring `F` is finite over `F`),
   `G'/F` is a finite extension.
3. By `hk`, `integralClosure P G'` is a finite `P`-module.
4. Every `x ∈ D` integral over `P` maps to an element of `K` integral over `P`, hence algebraic over
   `F`, and lying in `T`; so `x ↦ x` is an injective `P`-linear map `integralClosure P D →
   integralClosure P G'`. `P` is Noetherian, so `integralClosure P D` is a finite `P`-module. -/
theorem MvPolynomial.module_finite_integralClosure_of_finiteType_isDomain
    (k : Type u) [Field k] (hk : Field.PolynomialRingsN2 k) (d : ℕ)
    (D : Type u) [CommRing D] [IsDomain D] [Algebra (MvPolynomial (Fin d) k) D]
    [FaithfulSMul (MvPolynomial (Fin d) k) D] [Algebra.FiniteType (MvPolynomial (Fin d) k) D] :
    Module.Finite (MvPolynomial (Fin d) k) ↥(integralClosure (MvPolynomial (Fin d) k) D) := by
  classical
  set P := MvPolynomial (Fin d) k with hPdef
  let K := FractionRing D
  have hDK : Function.Injective (algebraMap D K) := IsFractionRing.injective D K
  have hPD : Function.Injective (algebraMap P D) := FaithfulSMul.algebraMap_injective P D
  haveI : FaithfulSMul P K := by
    rw [faithfulSMul_iff_algebraMap_injective, IsScalarTower.algebraMap_eq P D K]
    exact hDK.comp hPD
  letI := FractionRing.liftAlgebra P K
  haveI := FractionRing.isScalarTower_liftAlgebra P K
  let F := FractionRing P
  -- the finite type `F`-subalgebra of `K` generated by `D`
  let T : Subalgebra F K := Algebra.adjoin F (Set.range (algebraMap D K))
  have hT : Algebra.FiniteType F ↥T := by
    rw [← Subalgebra.fg_iff_finiteType]
    obtain ⟨s, hs⟩ := Algebra.FiniteType.out (R := P) (A := D)
    refine ⟨s.image (algebraMap D K), ?_⟩
    apply le_antisymm
    · refine Algebra.adjoin_mono ?_
      intro y hy
      rw [Finset.coe_image] at hy
      obtain ⟨x, _, rfl⟩ := hy
      exact ⟨x, rfl⟩
    · apply Algebra.adjoin_le
      rintro _ ⟨x, rfl⟩
      have hx : x ∈ Algebra.adjoin P (s : Set D) := by rw [hs]; trivial
      have : algebraMap D K x ∈ (Algebra.adjoin P (s : Set D)).map (IsScalarTower.toAlgHom P D K) :=
        ⟨x, hx, rfl⟩
      rw [AlgHom.map_adjoin] at this
      have hle : Algebra.adjoin P ((IsScalarTower.toAlgHom P D K) '' (s : Set D)) ≤
          (Algebra.adjoin F ((s.image (algebraMap D K) : Finset K) : Set K)).restrictScalars P := by
        apply Algebra.adjoin_le
        intro y hy
        rw [SetLike.mem_coe, Subalgebra.mem_restrictScalars]
        apply Algebra.subset_adjoin
        rw [Finset.coe_image]
        exact hy
      exact hle this
  -- the algebraic elements of `T`: a subfield of `K`, finite over `F` (Zariski's lemma)
  let G : Subalgebra F K := integralClosure F K ⊓ T
  haveI hGalg : Algebra.IsAlgebraic F ↥G := by
    rw [← Subalgebra.isAlgebraic_iff]
    intro x hx
    exact (show IsIntegral F x from hx.1).isAlgebraic
  let G' : IntermediateField F K := Algebra.IsAlgebraic.toIntermediateField G
  have hG'T : G'.toSubalgebra ≤ T := inf_le_right
  haveI : Module.Finite F ↥G' :=
    finite_of_algHom_finiteType_of_isJacobsonRing (Subalgebra.inclusion hG'T)
  haveI : Module.Finite P ↥(integralClosure P ↥G') := hk d F ↥G'
  -- the `P`-linear injection `integralClosure P D → integralClosure P G'`
  let ψ : ↥(integralClosure P D) →ₗ[P] ↥(integralClosure P ↥G') :=
    { toFun := fun x =>
        ⟨⟨algebraMap D K x.1, ⟨((x.2 : IsIntegral P x.1).map
            (IsScalarTower.toAlgHom P D K)).tower_top, Algebra.subset_adjoin ⟨x.1, rfl⟩⟩⟩,
          (IntermediateField.coe_isIntegral_iff (R := P)).mp
            ((x.2 : IsIntegral P x.1).map (IsScalarTower.toAlgHom P D K))⟩
      map_add' := fun x y => Subtype.ext (Subtype.ext (map_add (algebraMap D K) x.1 y.1))
      map_smul' := fun a x =>
        Subtype.ext (Subtype.ext (map_smul (IsScalarTower.toAlgHom P D K) a x.1)) }
  have hψ : Function.Injective ψ := by
    rw [injective_iff_map_eq_zero]
    intro x hx
    have h1 := congrArg (fun z => ((z : ↥(integralClosure P ↥G')) : ↥G').1) hx
    simp only [ψ] at h1
    ext
    exact hDK (by simpa using h1)
  exact Module.Finite.of_injective ψ hψ

/-- **L2 (finite type base ring, domain target).** `A` of finite type over `k`, `D` a domain of finite
type over `A`; if polynomial rings over `k` are N-2 (`hk`), the integral closure of `A` in `D` is a
finite `A`-module.

Source: proof of Stacks 03GH (domain case) — the Nagata hypothesis on `A` is replaced by `hk`.

Proof (matching the Lean): `A` is Noetherian. Let `A' := A ⧸ ker(A → D)`, a domain (the kernel is
prime because `D` is a domain) of finite type over `k`, and `A' → D` is injective; `D` is of finite
type over `A'`. Noether normalization (Mathlib `exists_finite_inj_algHom_of_fg`) gives an injective
`k`-algebra map `P = k[x_1, …, x_d] → A'` with `A'` finite over `P`; then `D` is of finite type over
`P` and `P → D` is injective, so L3 gives that `integralClosure P D` is a finite `P`-module. Since `A'`
is integral over `P`, `integralClosure P D = integralClosure A' D` as subsets of `D`
(`isIntegral_trans`, `IsIntegral.tower_top`), so the latter is a finite `P`-module and hence a finite
`A'`-module, hence a finite `A`-module (`A'` is a quotient of `A`). Finally `integralClosure A D ⊆
integralClosure A' D` (`IsIntegral.tower_top`) and `A` is Noetherian, so `integralClosure A D` is a
finite `A`-module. -/
theorem Algebra.module_finite_integralClosure_of_finiteType_isDomain
    (k : Type u) [Field k] (hk : Field.PolynomialRingsN2 k)
    (A : Type u) [CommRing A] [Algebra k A] [Algebra.FiniteType k A]
    (D : Type u) [CommRing D] [IsDomain D] [Algebra A D] [Algebra.FiniteType A D] :
    Module.Finite A ↥(integralClosure A D) := by
  haveI : IsNoetherianRing A := Algebra.FiniteType.isNoetherianRing k A
  -- `A' := A ⧸ ker (A → D)`, a domain of finite type over `k`, embedded in `D`
  let f : A →+* D := algebraMap A D
  let A' := A ⧸ RingHom.ker f
  haveI : (RingHom.ker f).IsPrime := RingHom.ker_isPrime f
  haveI : IsDomain A' := Ideal.Quotient.isDomain _
  let f' : A' →+* D := RingHom.kerLift f
  have hf' : Function.Injective f' := RingHom.kerLift_injective f
  letI : Algebra A' D := f'.toAlgebra
  haveI : IsScalarTower A A' D := .of_algebraMap_eq fun a => (RingHom.kerLift_mk f a).symm
  haveI : Algebra.FiniteType A' D := Algebra.FiniteType.of_restrictScalars_finiteType A A' D
  -- Noether normalization of `A'`
  obtain ⟨d, g, hinj, hgfin⟩ := exists_finite_inj_algHom_of_fg k A'
  have hgfin' : (g.toRingHom).Finite := hgfin
  have hinj' : Function.Injective (g.toRingHom) := hinj
  algebraize [g.toRingHom, f'.comp g.toRingHom]
  haveI : FaithfulSMul (MvPolynomial (Fin d) k) D :=
    (faithfulSMul_iff_algebraMap_injective _ D).mpr (hf'.comp hinj')
  haveI : Algebra.FiniteType (MvPolynomial (Fin d) k) D :=
    Algebra.FiniteType.trans (Module.Finite.finiteType A' (R := MvPolynomial (Fin d) k)) inferInstance
  have h3 : Module.Finite (MvPolynomial (Fin d) k)
      ↥(integralClosure (MvPolynomial (Fin d) k) D) :=
    MvPolynomial.module_finite_integralClosure_of_finiteType_isDomain k hk d D
  -- pass from `P` to `A'`
  have h2 : Module.Finite A' ↥(integralClosure A' D) := by
    have hmod : Module.Finite (MvPolynomial (Fin d) k) ↥(integralClosure A' D) := by
      refine Module.Finite.of_surjective
        ({ toFun := fun x =>
              (⟨x.1, (show IsIntegral (MvPolynomial (Fin d) k) x.1 from x.2).tower_top⟩ :
                ↥(integralClosure A' D))
           map_add' := fun _ _ => rfl
           map_smul' := fun _ _ => rfl } :
          ↥(integralClosure (MvPolynomial (Fin d) k) D) →ₗ[MvPolynomial (Fin d) k]
            ↥(integralClosure A' D)) ?_
      rintro ⟨x, hx⟩
      exact ⟨⟨x, isIntegral_trans x hx⟩, rfl⟩
    exact Module.Finite.of_restrictScalars_finite (MvPolynomial (Fin d) k) A' _
  -- pass from `A'` to `A`
  haveI : Module.Finite A ↥(integralClosure A' D) := Module.Finite.trans A' _
  refine Module.Finite.of_injective
    ({ toFun := fun x =>
        (⟨x.1, (show IsIntegral A x.1 from x.2).tower_top⟩ : ↥(integralClosure A' D))
       map_add' := fun _ _ => rfl
       map_smul' := fun _ _ => rfl } :
      ↥(integralClosure A D) →ₗ[A] ↥(integralClosure A' D)) ?_
  intro x y h
  ext
  exact congrArg (fun z : ↥(integralClosure A' D) => z.1) h

/-- **L1 (Stacks 03GH, reduction to the domain case).** `A` of finite type over `k`, `C` a reduced
algebra of finite type over `A`; if polynomial rings over `k` are N-2 (`hk`), then the integral
closure of `A` in `C` is a finite `A`-module.

Proof (matching the Lean): `A` and `C` are Noetherian (finite type over `k`), so `C` has finitely
many minimal primes `q` (Mathlib `minimalPrimes.finite_of_isNoetherianRing`); `C` reduced means
`⋂ q = nilradical C = 0` (`Ideal.sInf_minimalPrimes`), so `C → ∏_q C ⧸ q` is injective. Each `C ⧸ q`
is a domain of finite type over `A`, so by L2 the integral closure of `A` in it is a finite
`A`-module. The induced `A`-linear map `integralClosure A C → ∏_q integralClosure A (C ⧸ q)` is
injective, the target is a finite `A`-module (`Module.Finite.pi`), and `A` is Noetherian, so the
source is a finite `A`-module. -/
theorem Algebra.finite_integralClosure_of_finiteType_over_field_of_polynomialRingsN2
    {k A C : Type u} [Field k] [CommRing A]
    [CommRing C] [Algebra k A] [Algebra A C] [Algebra.FiniteType k A] [Algebra.FiniteType A C]
    [IsReduced C] (hk : Field.PolynomialRingsN2 k) : Module.Finite A (integralClosure A C) := by
  haveI : IsNoetherianRing A := Algebra.FiniteType.isNoetherianRing k A
  letI : Algebra k C := ((algebraMap A C).comp (algebraMap k A)).toAlgebra
  haveI : IsScalarTower k A C := .of_algebraMap_eq fun _ => rfl
  haveI : Algebra.FiniteType k C := Algebra.FiniteType.trans ‹Algebra.FiniteType k A› ‹_›
  haveI : IsNoetherianRing C := Algebra.FiniteType.isNoetherianRing k C
  haveI : Finite (minimalPrimes C) := (minimalPrimes.finite_of_isNoetherianRing C).to_subtype
  haveI : ∀ q : minimalPrimes C, (q.1).IsPrime := fun q => q.2.1.1
  haveI : ∀ q : minimalPrimes C, IsDomain (C ⧸ q.1) := fun q => Ideal.Quotient.isDomain _
  haveI : ∀ q : minimalPrimes C, Module.Finite A ↥(integralClosure A (C ⧸ q.1)) := fun q =>
    Algebra.module_finite_integralClosure_of_finiteType_isDomain k hk A (C ⧸ q.1)
  let Φ : ↥(integralClosure A C) →ₗ[A] ∀ q : minimalPrimes C, ↥(integralClosure A (C ⧸ q.1)) :=
    { toFun := fun x q => ⟨Ideal.Quotient.mkₐ A q.1 x.1,
        (show IsIntegral A x.1 from x.2).map (Ideal.Quotient.mkₐ A q.1)⟩
      map_add' := fun x y => by funext q; ext; simp
      map_smul' := fun a x => by funext q; ext; simp }
  have hΦ : Function.Injective Φ := by
    rw [injective_iff_map_eq_zero]
    intro x hx
    ext
    have h1 : ∀ q : minimalPrimes C, x.1 ∈ q.1 := fun q => by
      have := congrArg Subtype.val (congrFun hx q)
      simpa [Φ, Ideal.Quotient.eq_zero_iff_mem] using this
    have h2 : x.1 ∈ nilradical C := by
      rw [show nilradical C = sInf (minimalPrimes C) from
        (Ideal.sInf_minimalPrimes (I := (⊥ : Ideal C))).symm, Ideal.mem_sInf]
      intro q hq
      exact h1 ⟨q, hq⟩
    rw [nilradical_eq_zero] at h2
    simpa using h2
  exact Module.Finite.of_injective Φ hΦ

/- The ring-theoretic form of Stacks 035B / 0335(1)(5) (finite type algebras over a field are Nagata)
   combined with 03GH (for a reduced algebra `S` essentially of finite type over a Nagata ring `R`,
   the integral closure of `R` in `S` is finite over `R`); 035S (normalization of a Nagata scheme is
   finite) is its scheme version. `A` of finite type over a field `k`, `C` a reduced algebra of
   finite type over `A` ⇒ the integral closure of `A` in `C` is a finite `A`-module. -/

theorem Algebra.finite_integralClosure_of_finiteType_over_field {k A C : Type u} [Field k] [CommRing A]
    [CommRing C] [Algebra k A] [Algebra A C] [Algebra.FiniteType k A] [Algebra.FiniteType A C]
    [IsReduced C] : Module.Finite A (integralClosure A C) :=
  Algebra.finite_integralClosure_of_finiteType_over_field_of_polynomialRingsN2
    (Field.polynomialRingsN2 k)

/-- The main statement for a field of **characteristic `0`**, depending only on the
characteristic-`0` case of N-2 (Mathlib's `IsIntegralClosure.finite`), not on
`Field.polynomialRingsN2_of_charP`. Kept as a lighter-weight variant for users with `[CharZero k]`. -/
theorem Algebra.finite_integralClosure_of_finiteType_over_field_of_charZero
    {k A C : Type u} [Field k] [CharZero k] [CommRing A]
    [CommRing C] [Algebra k A] [Algebra A C] [Algebra.FiniteType k A] [Algebra.FiniteType A C]
    [IsReduced C] : Module.Finite A (integralClosure A C) :=
  Algebra.finite_integralClosure_of_finiteType_over_field_of_polynomialRingsN2
    (Field.polynomialRingsN2_of_charZero k)

end
