import MiyaokaMori.Prelude
import MiyaokaMori.RingTheory.GradedRing.WeightedSymGrading

/-! # Positive-weight pieces of the weighted symmetric algebra lie in the ideal of the generators

In the algebraic weighted symmetric algebra `Sym_R(⨁_q W_q)` with weights `w q ≠ 0`, the weight-`m` piece
`WeightedSym.piece w m` for `m ≠ 0` is contained in the ideal `genIdeal` generated by all generators `gen q x`
("the coordinates generate the algebra over `A_0`", §2 of the paper). Proof: the induction principle
`WeightedSym.piece_le_of_gen` (module `WeightedSymGrading`) applied to `Q k := if k = 0 then ⊤ else genIdeal`:
`1 ∈ Q 0`; `Q i * Q j ≤ Q (i + j)` (if `i + j = 0` trivially, else one factor lies in the ideal); `genSpan q ≤ Q (w q)`
since `w q ≠ 0` and generators lie in `genIdeal`. -/

set_option autoImplicit false

universe u v w'

open DirectSum

noncomputable section

namespace WeightedSym

variable (R : Type u) [CommRing R] {ι : Type v} [DecidableEq ι] [Fintype ι]
  (W : ι → Type w') [∀ q, AddCommGroup (W q)] [∀ q, Module R (W q)]

/-- The ideal of `Sym_R(⨁_q W_q)` generated by all generators `gen q x`. -/
def genIdeal : Ideal (SymmetricAlgebra R (⨁ p, W p)) :=
  Ideal.span (Set.range (fun qx : Σ q : ι, W q => gen R W qx.1 qx.2))

omit [Fintype ι] in
theorem gen_mem_genIdeal (q : ι) (x : W q) : gen R W q x ∈ genIdeal R W :=
  Ideal.subset_span ⟨⟨q, x⟩, rfl⟩

variable {R W}

/-- **Positive-weight pieces lie in the ideal of the generators.** -/
theorem piece_le_genIdeal {w : ι → ℕ} (hw : ∀ q, w q ≠ 0) {m : ℕ} (hm : m ≠ 0) :
    piece R W w m ≤ (genIdeal R W).restrictScalars R := by
  let Q : ℕ → Submodule R (SymmetricAlgebra R (⨁ p, W p)) := fun k =>
    if k = 0 then ⊤ else (genIdeal R W).restrictScalars R
  have hQ : ∀ k, k ≠ 0 → Q k = (genIdeal R W).restrictScalars R := fun k hk => by simp [Q, hk]
  have h1 : (1 : SymmetricAlgebra R (⨁ p, W p)) ∈ Q 0 := by simp [Q]
  have hmul : ∀ i j, Q i * Q j ≤ Q (i + j) := by
    intro i j
    refine Submodule.mul_le.mpr fun x hx y hy => ?_
    by_cases hij : i + j = 0
    · simp [Q, hij]
    · rw [hQ _ hij]
      rcases Nat.eq_zero_or_pos i with hi | hi
      · have hj : j ≠ 0 := by omega
        rw [hQ _ hj] at hy
        exact Ideal.mul_mem_left _ x hy
      · rw [hQ _ (Nat.pos_iff_ne_zero.mp hi)] at hx
        exact Ideal.mul_mem_right y _ hx
  have hgen : ∀ q, genSpan R W q ≤ Q (w q) := by
    intro q
    rw [hQ _ (hw q)]
    rintro _ ⟨x, rfl⟩
    exact gen_mem_genIdeal R W q x
  have := piece_le_of_gen h1 hmul hgen m
  rwa [hQ _ hm] at this

end WeightedSym

end
