import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.ZeroSchemeOfSection
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.EvaluateHomogeneousAtSections
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.ModulesTensorPowMapIso
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.ModulesTensorMonoidalIso
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.Frame

/-! # Lemmas on the vanishing of homogeneous equation sections

Three lemmas used for the vanishing of a homogeneous equation along the section given by a tuple:
1. `Modules.iso_hom_app_top_eq_zero_iff_hes`: an isomorphism of modules preserves and reflects zero on
   global sections.
2. `idealSheafOfSection_eq_bot_iff`: the zero-scheme ideal sheaf of a global section `s` of a line bundle
   is `⊥` iff `s = 0`. Proof: (⇐) the generators `φ(0|_U) = 0`, so the ideal on every affine open is `⊥`.
   (⇒) For every point `x` take an affine open neighbourhood `W` with a frame `e` (`exists_affine_frame_le`);
   the coordinate map `coordEquiv : Γ(M,W) ≃ₗ Γ(X,W)` is an element of `Hom_{Γ(X,W)}(Γ(M,W), Γ(X,W))`, so
   `coord(s|_W)` lies in `I(W) = ⊥` and `s|_W = 0` (`coord_eq_zero_iff`); these `W` cover `X`, and
   separatedness of the sheaf (`TopCat.Sheaf.eq_of_locally_eq'`) gives `s = 0`.
3. `evalHomogeneousAtSections_mapIso`: functoriality of homogeneous evaluation under an isomorphism of
   line bundles `Φ : A' ≅ A`: the tensor power isomorphism `tensorPowMapIso Φ e` sends `F(f')` to `F(Φ f')`.
   Proof: for monomials by induction on `e`, using `tensorHom_tensorSections` and the action of
   `tensorIsoTensorObj` on `sectionTensor`; then linearity in sums and scalars.

Reference: Stacks 01CR (an invertible sheaf is locally generated by one section).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000
set_option linter.style.haveILetI false

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- An isomorphism of modules preserves and reflects zero on global sections. -/
theorem AlgebraicGeometry.Scheme.Modules.iso_hom_app_top_eq_zero_iff_hes {X : AlgebraicGeometry.Scheme.{u}}
    {M M' : X.Modules} (e : M ≅ M') (x : (M.val.obj (Opposite.op ⊤) : Type u)) :
    e.hom.app ⊤ x = 0 ↔ x = 0 := by
  constructor
  · intro h
    have h1 := congrArg (fun φ : M ⟶ M => φ.app ⊤ x) e.hom_inv_id
    change e.inv.app ⊤ (e.hom.app ⊤ x) = x at h1
    rw [← h1, h]
    exact map_zero _
  · rintro rfl
    exact map_zero _

theorem AlgebraicGeometry.Scheme.idealSheafOfSection_eq_bot_iff {X : AlgebraicGeometry.Scheme.{u}}
    (M : X.Modules) [M.IsLineBundle] (s : (M.val.obj (Opposite.op ⊤) : Type u)) :
    AlgebraicGeometry.Scheme.idealSheafOfSection M s = ⊥ ↔ s = 0 := by
  constructor
  · intro h
    have hloc : ∀ x : X, ∃ W : X.Opens, x ∈ W ∧
        M.presheaf.map (CategoryTheory.homOfLE (le_top : W ≤ ⊤)).op s = 0 := by
      intro x
      obtain ⟨W, hW, -, hx, e, he⟩ :=
        AlgebraicGeometry.Scheme.Modules.exists_affine_frame_le M (U := ⊤) (p := x) trivial
      refine ⟨W, hx, ?_⟩
      have hmem : (he.coordEquiv le_rfl : Γ(M, W) →ₗ[Γ(X, W)] Γ(X, W))
          (M.presheaf.map (CategoryTheory.homOfLE le_top).op (show Γ(M, ⊤) from s)) ∈
            (AlgebraicGeometry.Scheme.idealSheafOfSection M s).ideal ⟨W, hW⟩ :=
        Ideal.subset_span ⟨_, rfl⟩
      rw [h] at hmem
      have h0 : he.coord le_rfl (M.presheaf.map (CategoryTheory.homOfLE le_top).op s) = 0 :=
        Ideal.mem_bot.mp hmem
      exact (he.coord_eq_zero_iff le_rfl _).mp h0
    choose W hxW hW using hloc
    refine TopCat.Sheaf.eq_of_locally_eq' ⟨M.presheaf, M.isSheaf⟩ W ⊤
      (fun x => CategoryTheory.homOfLE le_top) ?_ s 0 ?_
    · intro x _
      exact TopologicalSpace.Opens.mem_iSup.mpr ⟨x, hxW x⟩
    · intro x
      rw [map_zero]
      exact hW x
  · rintro rfl
    refine AlgebraicGeometry.Scheme.IdealSheafData.ext (funext fun U => ?_)
    change Ideal.span (Set.range fun φ : Γ(M, U.1) →ₗ[Γ(X, U.1)] Γ(X, U.1) =>
      φ (M.presheaf.map (CategoryTheory.homOfLE le_top).op (show Γ(M, ⊤) from 0))) = ⊥
    refine Ideal.span_eq_bot.mpr ?_
    rintro _ ⟨φ, rfl⟩
    show φ (M.presheaf.map (CategoryTheory.homOfLE le_top).op (show Γ(M, ⊤) from 0)) = 0
    rw [map_zero]
    exact map_zero φ


private theorem tensorIsoTensorObj_sectionTensor' {X : AlgebraicGeometry.Scheme.{u}}
    {M N : X.Modules} (s : (M.val.obj (Opposite.op ⊤) : Type u))
    (t : (N.val.obj (Opposite.op ⊤) : Type u)) :
    ((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj M N).hom.val.app (Opposite.op ⊤)).hom
        (sectionTensor s t) =
      AlgebraicGeometry.Scheme.Modules.tensorSections M N ⊤ s t := by
  rfl

private theorem tensorIsoTensorObj_inv_tensorSections' {X : AlgebraicGeometry.Scheme.{u}}
    {M N : X.Modules} (s : (M.val.obj (Opposite.op ⊤) : Type u))
    (t : (N.val.obj (Opposite.op ⊤) : Type u)) :
    ((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj M N).inv.val.app (Opposite.op ⊤)).hom
        (AlgebraicGeometry.Scheme.Modules.tensorSections M N ⊤ s t) =
      sectionTensor s t := by
  have h := congrArg (fun φ : AlgebraicGeometry.Scheme.Modules.tensor M N ⟶ _ =>
    (φ.val.app (Opposite.op ⊤)).hom (sectionTensor s t))
    (AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj M N).hom_inv_id
  change ((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj M N).inv.val.app (Opposite.op ⊤)).hom
    (((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj M N).hom.val.app (Opposite.op ⊤)).hom
      (sectionTensor s t)) = sectionTensor s t at h
  rw [tensorIsoTensorObj_sectionTensor'] at h
  exact h

private theorem evalHomogeneousAtSections_mapIso_monomial {X : AlgebraicGeometry.Scheme.{u}}
    {A' A : X.Modules} (Φ : A' ≅ A) {N : ℕ}
    (f : Fin (N + 1) → (A'.val.obj (Opposite.op ⊤) : Type u)) :
    ∀ e (q : Fin e → Fin (N + 1)),
      ((AlgebraicGeometry.Scheme.Modules.tensorPowMapIso Φ e).hom.val.app (Opposite.op ⊤)).hom
          (evalHomogeneousAtSections.monomial A' f e q) =
        evalHomogeneousAtSections.monomial A (fun i => (Φ.hom.val.app (Opposite.op ⊤)).hom (f i)) e q := by
  intro e
  induction e with
  | zero =>
      intro q
      rfl
  | succ e ih =>
      intro q
      change ((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj _ _ ≪≫
          CategoryTheory.MonoidalCategory.tensorIso (C := X.Modules)
            (AlgebraicGeometry.Scheme.Modules.tensorPowMapIso Φ e) Φ ≪≫
          (AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj _ _).symm).hom.val.app (Opposite.op ⊤)).hom
          (sectionTensor (evalHomogeneousAtSections.monomial A' f e (fun i => q i.castSucc))
            (f (q (Fin.last e)))) =
        sectionTensor (evalHomogeneousAtSections.monomial A
          (fun i => (Φ.hom.val.app (Opposite.op ⊤)).hom (f i)) e (fun i => q i.castSucc))
          ((Φ.hom.val.app (Opposite.op ⊤)).hom (f (q (Fin.last e))))
      change ((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj _ _).inv.val.app (Opposite.op ⊤)).hom
        (((CategoryTheory.MonoidalCategoryStruct.tensorHom (C := X.Modules)
          (AlgebraicGeometry.Scheme.Modules.tensorPowMapIso Φ e).hom Φ.hom).val.app (Opposite.op ⊤)).hom
          (((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj _ _).hom.val.app (Opposite.op ⊤)).hom
            (sectionTensor (evalHomogeneousAtSections.monomial A' f e (fun i => q i.castSucc))
              (f (q (Fin.last e)))))) = _
      rw [tensorIsoTensorObj_sectionTensor']
      change ((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj _ _).inv.val.app (Opposite.op ⊤)).hom
        ((CategoryTheory.MonoidalCategoryStruct.tensorHom (C := X.Modules)
          (AlgebraicGeometry.Scheme.Modules.tensorPowMapIso Φ e).hom Φ.hom).val.app (Opposite.op ⊤)
          (AlgebraicGeometry.Scheme.Modules.tensorSections _ _ ⊤
            (evalHomogeneousAtSections.monomial A' f e (fun i => q i.castSucc))
            (f (q (Fin.last e))))) = _
      rw [AlgebraicGeometry.Scheme.Modules.tensorHom_tensorSections]
      change ((AlgebraicGeometry.Scheme.Modules.tensorIsoTensorObj _ _).inv.val.app (Opposite.op ⊤)).hom
        (AlgebraicGeometry.Scheme.Modules.tensorSections _ _ ⊤
          (((AlgebraicGeometry.Scheme.Modules.tensorPowMapIso Φ e).hom.val.app (Opposite.op ⊤)).hom
            (evalHomogeneousAtSections.monomial A' f e (fun i => q i.castSucc)))
          ((Φ.hom.val.app (Opposite.op ⊤)).hom (f (q (Fin.last e))))) = _
      rw [ih (fun i => q i.castSucc)]
      exact tensorIsoTensorObj_inv_tensorSections' _ _

theorem evalHomogeneousAtSections_mapIso {k : Type u} [Field k] {X : AlgebraicGeometry.Scheme.{u}}
    [X.Over (AlgebraicGeometry.Spec (CommRingCat.of k))] {A' A : X.Modules} [A'.IsLineBundle] [A.IsLineBundle]
    (Φ : A' ≅ A) {N e : ℕ} (F : MvPolynomial (Fin (N + 1)) k) (hF : F.IsHomogeneous e)
    (f : Fin (N + 1) → (A'.val.obj (Opposite.op ⊤) : Type u)) :
    (AlgebraicGeometry.Scheme.Modules.tensorPowMapIso Φ e).hom.app ⊤
        (evalHomogeneousAtSections A' F hF f) =
      evalHomogeneousAtSections A F hF (fun i => Φ.hom.app ⊤ (f i)) := by
  simp only [evalHomogeneousAtSections]
  change ((AlgebraicGeometry.Scheme.Modules.tensorPowMapIso Φ e).hom.val.app (Opposite.op ⊤)).hom
    (∑ i ∈ F.support.attach, _) = _
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro x _
  refine ((ModuleCat.Hom.hom
    ((AlgebraicGeometry.Scheme.Modules.tensorPowMapIso Φ e).hom.val.app (Opposite.op ⊤))).map_smul _ _).trans ?_
  congr 1
  exact evalHomogeneousAtSections_mapIso_monomial Φ f e _


end
