import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.QuasicoherentAffineLocal
import Mathlib.RingTheory.LocalProperties.FinitePresentation
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.Frame
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.QcLocalizedModule
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.LocallyFreeQuasicoherent

/-! # The zero scheme of a section

The zero scheme of a global section of a line bundle (or module), as an ideal sheaf.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/- On an affine open `U`: `I(U) :=` the ideal generated by `{φ(s|_U) | φ ∈ Hom_{Γ(X,U)}(Γ(M,U), Γ(X,U))}`
   (the ideal generated by the "local equations" of `s`, Stacks 01WX/01X0). On a trivialization `U` of `M`
   with `s = f·e`, `I(U) = (f)`. -/


/-- **Purely algebraic lemma** (Stacks 01BG, Hom commutes with localization): `A` a commutative ring, `P` a
finitely presented `A`-module, `f ∈ A`, `A'` the localization of `A` at `f`, `r : P → P'` the localization of
the module `P` at `f` (`P'` an `A'`-module, `r` `A`-linear). Then for `s ∈ P`, the ideal generated in `A'` by
the "coordinate ideal" `span {φ s | φ ∈ Hom_A(P, A)}` of `s` equals `span {ψ (r s) | ψ ∈ Hom_{A'}(P', A')}`.

Proof: `IsLocalizedModule.mapExtendScalars` gives `Φ : Hom_A(P, A) → Hom_{A'}(P', A')` with
`Φ φ (r s) = φ s / 1`; for finitely presented `P`, `Φ` is itself the localization at `f`
(`Module.FinitePresentation.isLocalizedModule_mapExtendScalars`).
* `⊆`: the generators `φ s / 1 = Φ φ (r s)` lie on the right.
* `⊇`: every `ψ` satisfies `f^n • ψ = Φ φ` (surjectivity of localization), so
  `(f^n/1) · ψ (r s) = φ s / 1 ∈` left-hand side, and `f^n / 1` is a unit of `A'`, so `ψ (r s) ∈` left-hand side. -/
theorem Ideal.map_span_range_eval_eq_of_isLocalizedModule
    {A A' P P' : Type*} [CommRing A] [CommRing A'] [Algebra A A']
    [AddCommGroup P] [Module A P] [AddCommGroup P'] [Module A P'] [Module A' P']
    [IsScalarTower A A' P'] (f : A) [IsLocalization.Away f A'] [Module.FinitePresentation A P]
    (r : P →ₗ[A] P') [IsLocalizedModule (Submonoid.powers f) r] (s : P) :
    (Ideal.span (Set.range fun φ : P →ₗ[A] A => φ s)).map (algebraMap A A') =
      Ideal.span (Set.range fun ψ : P' →ₗ[A'] A' => ψ (r s)) := by
  let Φ : (P →ₗ[A] A) →ₗ[A] (P' →ₗ[A'] A') :=
    IsLocalizedModule.mapExtendScalars (Submonoid.powers f) r (Algebra.linearMap A A') A'
  have hΦ : ∀ φ : P →ₗ[A] A, Φ φ (r s) = algebraMap A A' (φ s) := fun φ => by
    simp [Φ]
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap, Ideal.span_le]
    rintro _ ⟨φ, rfl⟩
    show algebraMap A A' (φ s) ∈ Ideal.span _
    exact Ideal.subset_span ⟨Φ φ, hΦ φ⟩
  · rw [Ideal.span_le]
    rintro _ ⟨ψ, rfl⟩
    obtain ⟨⟨φ, t⟩, hφ⟩ := IsLocalizedModule.surj (Submonoid.powers f) Φ ψ
    have h1 : algebraMap A A' (t : A) * ψ (r s) = algebraMap A A' (φ s) := by
      have := LinearMap.congr_fun hφ (r s)
      simp only [LinearMap.smul_apply] at this
      rw [Submonoid.smul_def, Algebra.smul_def, hΦ] at this
      exact this
    have hu : IsUnit (algebraMap A A' (t : A)) := IsLocalization.map_units A' t
    have hmem : algebraMap A A' (φ s) ∈
        (Ideal.span (Set.range fun φ : P →ₗ[A] A => φ s)).map (algebraMap A A') :=
      Ideal.mem_map_of_mem _ (Ideal.subset_span ⟨φ, rfl⟩)
    rw [← h1] at hmem
    obtain ⟨u, hu⟩ := hu
    have := Ideal.mul_mem_left _ (↑u⁻¹ : A') hmem
    rwa [← mul_assoc, ← hu, Units.inv_mul, one_mul] at this

/-- **The module of sections of a line bundle over an affine open is finitely presented** (Stacks 00NX:
finite locally free ⇒ finitely presented; here directly through `Module.FinitePresentation.of_localizationSpan'`).

Proof: let `s ⊆ Γ(X, U)` be the set of `g` such that `M` has a frame (`IsFrame`) on `D(g)`. Every point
`p ∈ U` has a frame neighbourhood `W ≤ U` (`exists_frame_le`), affineness gives `p ∈ D(g) ≤ W`
(`IsAffineOpen.exists_basicOpen_le`), and the frame restricted to `D(g)` is still a frame, so `g ∈ s`; hence
`span s = ⊤` (`QcAffineLocalAux.ideal_eq_top`). For each `g ∈ s`: `Γ(M, D(g))` is the localization of
`Γ(M, U)` at `g` (quasi-coherence, `isLocalizedModule_basicOpen`), `Γ(X, D(g))` is the localization of
`Γ(X, U)` at `g` (`isLocalization_basicOpen`), and the frame coordinate gives
`Γ(M, D(g)) ≃ₗ[Γ(X, D(g))] Γ(X, D(g))`, so `Γ(M, D(g))` is a finitely presented `Γ(X, D(g))`-module. -/
theorem AlgebraicGeometry.Scheme.Modules.finitePresentation_sections_of_isLineBundle
    {X : AlgebraicGeometry.Scheme.{u}} (M : X.Modules) [M.IsLineBundle] (U : X.affineOpens) :
    Module.FinitePresentation Γ(X, U.1) Γ(M, U.1) := by
  classical
  let s : Set Γ(X, U.1) :=
    {g | ∃ e : Γ(M, X.basicOpen g), AlgebraicGeometry.Scheme.Modules.IsFrame M (X.basicOpen g) e}
  have hs : Ideal.span s = ⊤ := by
    refine QcAffineLocalAux.ideal_eq_top U.2 _ fun p hp => ?_
    obtain ⟨W, hWU, hpW, e, he⟩ := AlgebraicGeometry.Scheme.Modules.exists_frame_le M hp
    obtain ⟨g, hgW, hpg⟩ := U.2.exists_basicOpen_le ⟨p, hpW⟩ hp
    exact ⟨g, 1, hpg, by rw [pow_one]; exact Ideal.subset_span ⟨M.res hgW e, he.restrict hgW⟩⟩
  let inst1 : ∀ g : s, Module Γ(X, U.1) Γ(M, X.basicOpen g.1) := fun g =>
    Module.compHom Γ(M, X.basicOpen g.1) (X.presheaf.map (homOfLE (X.basicOpen_le g.1)).op).hom
  have inst2 : ∀ g : s,
      IsScalarTower Γ(X, U.1) Γ(X, X.basicOpen g.1) Γ(M, X.basicOpen g.1) := fun g =>
    ⟨fun a b x => by
      show ((X.presheaf.map (homOfLE (X.basicOpen_le g.1)).op).hom a * b) • x =
        (X.presheaf.map (homOfLE (X.basicOpen_le g.1)).op).hom a • (b • x)
      exact mul_smul _ _ _⟩
  have inst3 : ∀ g : s, IsLocalization.Away g.1 Γ(X, X.basicOpen g.1) := fun g =>
    U.2.isLocalization_basicOpen g.1
  let ϕ : ∀ g : s, Γ(M, U.1) →ₗ[Γ(X, U.1)] Γ(M, X.basicOpen g.1) := fun g =>
    { toFun := fun x => M.presheaf.map (homOfLE (X.basicOpen_le g.1)).op x
      map_add' := fun x y => map_add _ x y
      map_smul' := fun a x => AlgebraicGeometry.Scheme.Modules.map_smul M _ a x }
  have inst4 : ∀ g : s, IsLocalizedModule (Submonoid.powers g.1) (ϕ g) := fun g =>
    AlgebraicGeometry.Scheme.Modules.isLocalizedModule_basicOpen M U.2 g.1 (fun _ _ => rfl) (ϕ g)
      (fun _ => rfl)
  refine Module.FinitePresentation.of_localizationSpan' s hs
    (Rₚ := fun g => Γ(X, X.basicOpen g.1)) ϕ fun g => ?_
  obtain ⟨e, he⟩ := g.2
  exact Module.FinitePresentation.of_equiv (he.coordEquiv le_rfl).symm

/-- Compatibility of the ideal of local equations with basic opens (the `map_ideal_basicOpen` obligation of
`idealSheafOfSection`): for an affine open `U` and `f ∈ Γ(X, U)`, the `Γ(X, D(f))`-ideal generated by the
image of `I(U)` under restriction is `I(D(f))`.

Proof route (Stacks 01WX/01X0 + 01BG):
* `M` is a line bundle, so `M|_U` is quasi-coherent and finitely presented; the lemmas around
  `Scheme.Modules.exists_pow_smul_eq_map_basicOpen` give the canonical isomorphism
  `Γ(M, D(f)) ≅ Γ(M, U) ⊗_{Γ(X,U)} Γ(X, U)_f`, compatible with restriction.
* `⊆`: for `φ : Γ(M,U) →ₗ[Γ(X,U)] Γ(X,U)`, its localization `φ_f` is `Γ(M,D(f)) →ₗ Γ(X,D(f))` with
  `φ_f (s|_{D(f)}) = (φ s)|_{D(f)}`, so the image of the restriction lies in `I(D(f))`.
* `⊇`: `Γ(M,U)` is finitely presented over `Γ(X,U)`, so
  `Hom_{A_f}(Γ(M,U)_f, A_f) ≅ Hom_A(Γ(M,U), A)_f` (the isomorphism `LinearMap.localizedModule` /
  `IsLocalizedModule.mapExtendScalars` under `Module.Finite`/`Module.FinitePresentation`). Hence every
  `ψ : Γ(M,D(f)) →ₗ Γ(X,D(f))` has the form `φ_f / f^n`, and `f` is a unit of `Γ(X,D(f))`, so
  `ψ (s|_{D(f)}) ∈ I(U)·Γ(X, D(f))`.
* The two inclusions give the equality (check generators of `Ideal.span` one by one, `Ideal.map_span`).

The purely algebraic part is `Ideal.map_span_range_eval_eq_of_isLocalizedModule` above, finite
presentation is `finitePresentation_sections_of_isLineBundle`, and `Γ(M, D(f))` being the localization of
`Γ(M, U)` is `isLocalizedModule_basicOpen`. -/

theorem AlgebraicGeometry.Scheme.idealSheafOfSection_map_ideal_basicOpen
    {X : AlgebraicGeometry.Scheme.{u}} (M : X.Modules) [M.IsLineBundle]
    (s : (M.val.obj (Opposite.op ⊤) : Type u)) (U : X.affineOpens) (f : Γ(X, U.1)) :
    (Ideal.span (Set.range fun φ : Γ(M, U.1) →ₗ[Γ(X, U.1)] Γ(X, U.1) =>
        φ (M.presheaf.map (CategoryTheory.homOfLE le_top).op (show Γ(M, ⊤) from s)))).map
      (X.presheaf.map (CategoryTheory.homOfLE <| X.basicOpen_le f).op).hom =
    Ideal.span (Set.range fun
        φ : Γ(M, (X.affineBasicOpen f).1) →ₗ[Γ(X, (X.affineBasicOpen f).1)]
          Γ(X, (X.affineBasicOpen f).1) =>
      φ (M.presheaf.map (CategoryTheory.homOfLE le_top).op (show Γ(M, ⊤) from s))) := by
  have := U.2.isLocalization_basicOpen f
  let : Module Γ(X, U.1) Γ(M, X.basicOpen f) :=
    Module.compHom Γ(M, X.basicOpen f) (X.presheaf.map (homOfLE (X.basicOpen_le f)).op).hom
  have : IsScalarTower Γ(X, U.1) Γ(X, X.basicOpen f) Γ(M, X.basicOpen f) :=
    ⟨fun a b x => by
      show ((X.presheaf.map (homOfLE (X.basicOpen_le f)).op).hom a * b) • x =
        (X.presheaf.map (homOfLE (X.basicOpen_le f)).op).hom a • (b • x)
      exact mul_smul _ _ _⟩
  let r : Γ(M, U.1) →ₗ[Γ(X, U.1)] Γ(M, X.basicOpen f) :=
    { toFun := fun x => M.presheaf.map (homOfLE (X.basicOpen_le f)).op x
      map_add' := fun x y => map_add _ x y
      map_smul' := fun a x => AlgebraicGeometry.Scheme.Modules.map_smul M _ a x }
  have : IsLocalizedModule (Submonoid.powers f) r :=
    AlgebraicGeometry.Scheme.Modules.isLocalizedModule_basicOpen M U.2 f (fun _ _ => rfl) r
      (fun _ => rfl)
  have := AlgebraicGeometry.Scheme.Modules.finitePresentation_sections_of_isLineBundle M U
  have key := Ideal.map_span_range_eval_eq_of_isLocalizedModule (A' := Γ(X, X.basicOpen f)) f r
    (M.presheaf.map (CategoryTheory.homOfLE le_top).op (show Γ(M, ⊤) from s))
  have hs : r (M.presheaf.map (CategoryTheory.homOfLE le_top).op (show Γ(M, ⊤) from s)) =
      M.presheaf.map (CategoryTheory.homOfLE le_top).op (show Γ(M, ⊤) from s) :=
    AlgebraicGeometry.Scheme.Modules.res_res M (X.basicOpen_le f) le_top _
  rw [hs] at key
  exact key

noncomputable def AlgebraicGeometry.Scheme.idealSheafOfSection {X : AlgebraicGeometry.Scheme.{u}}
    (M : X.Modules) [M.IsLineBundle] (s : (M.val.obj (Opposite.op ⊤) : Type u)) :
    X.IdealSheafData where
  ideal U := Ideal.span (Set.range fun φ : Γ(M, U.1) →ₗ[Γ(X, U.1)] Γ(X, U.1) =>
    φ (M.presheaf.map (CategoryTheory.homOfLE le_top).op (show Γ(M, ⊤) from s)))
  -- quasi-coherence: Γ(D(f), M) = Γ(U, M)_f; Hom of a finitely presented module commutes with localization, so I(D(f)) = I(U)·Γ(X, U)_f
  map_ideal_basicOpen := AlgebraicGeometry.Scheme.idealSheafOfSection_map_ideal_basicOpen M s

end
