import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.FiniteTypeOfFiniteAffineSections
import MiyaokaMori.AlgebraicGeometry.Modules.Differentials.OmegaQuasicoherent
import MiyaokaMori.AlgebraicGeometry.Modules.Differentials.RelativeDifferentials

/-! # The sheaf of relative differentials of a morphism of finite type is of finite type

The sheaf of relative differentials of a morphism locally of finite type is a finite type `O_X`-module
(on affine pieces `Ω_{B/A}` is generated by finitely many `db_i`); in particular `Ω` of a smooth
morphism is of finite type.

References: Stacks 01V2 (`Ω` is of finite type for morphisms of finite type); Mathlib
`KaehlerDifferential.finite`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

theorem AlgebraicGeometry.Omega_isFiniteType {X S : AlgebraicGeometry.Scheme.{u}} (f : X ⟶ S)
    [AlgebraicGeometry.LocallyOfFiniteType f] :
    (AlgebraicGeometry.Omega f).IsFiniteType := by
  have := AlgebraicGeometry.Omega_isQuasicoherent f
  refine AlgebraicGeometry.Scheme.Modules.isFiniteType_of_finite_affine_sections _ fun x => ?_
  obtain ⟨_, ⟨V, hV, rfl⟩, hxV, -⟩ :=
    S.isBasis_affineOpens.exists_subset_of_mem_open (Set.mem_univ (f x)) isOpen_univ
  obtain ⟨_, ⟨U, hU, rfl⟩, hxU, e⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open hxV (V.2.preimage f.continuous)
  refine ⟨U, hU, hxU, ?_⟩
  let := (f.appLE V U e).hom.toAlgebra
  have : Algebra.FiniteType Γ(S, V) Γ(X, U) := f.finiteType_appLE hV hU e
  exact Module.Finite.equiv (AlgebraicGeometry.Omega_appIso f hV hU e).symm

end
