import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.Ample.AmpleFiniteAffineCover
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.AmpleUniformSectionExtension
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.Stacks01q1
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.ModuleSheafFrame

/-! # Very-ample sections over an affine base

**Very-ample sections over an affine base** (Stacks 01VU, "sections form", proof paragraphs 1–2, with the field
`k` replaced by an affine base; used in Stacks 07RM, first paragraph of the proof, over each affine `V_j ⊆ S`):
`f : X ⟶ V` locally of finite type with `V` affine, `L` an ample line bundle on `X`. Then there are `n > 0` and
finitely many sections `P_ℓ ∈ Γ(X, L^{⊗n})` together with a set `I` of "covering indices" such that
(a) the nonvanishing loci `X_{P_ℓ}`, `ℓ ∈ I`, are affine and cover `X`;
(b) for `ℓ ∈ I` the ring `Γ(X_{P_ℓ}, O_X)` is generated by the image of `Γ(V, O_V)` (along `f`) and the ratios
`P_j / P_ℓ` (the unique `g` with `P_j|_{X_{P_ℓ}} = g • P_ℓ|_{X_{P_ℓ}}`; `P_ℓ` is a frame on `X_{P_ℓ}`).

It is the exact analogue over an affine base of the ingredients of
`IsAmple.exists_projectivizationMorphism_isImmersion` (Stacks 01VU over a field), and the proof below
follows that module step by step.

**Proof (Stacks 01VU / 01PW).**
1. *Finite affine cover.* `IsAmple.exists_finite_affine_cover` gives `n > 0` and a finite family
   `s_i ∈ Γ(X, L^{⊗n})` whose nonvanishing loci `X_{s_i}` are affine and cover `X`
   (`X` is quasi-compact: first conjunct of `IsAmple`).
2. *Finitely many generators on each chart.* `X_{s_i}` is an affine open of `X` and `f` is locally of finite
   type, so `f.appLE ⊤ X_{s_i} : Γ(V, O) → Γ(X_{s_i}, O)` is of finite type
   (`HasRingHomProperty @LocallyOfFiniteType RingHom.FiniteType`, `HasRingHomProperty.appLE`); choose finitely
   many algebra generators `t_{i,1}, …, t_{i,m_i} ∈ Γ(X_{s_i}, O)` (`Algebra.FiniteType` ⇒ finite generating set
   of the subalgebra `⊤`; in ring terms: `Subring.closure (range (f.appLE) ∪ {t_{i,a}}) = ⊤`).
3. *Extension of the generators (Stacks 01PW).* `X` is quasi-separated (`IsAmple.quasiSeparatedSpace`).
   `Scheme.Modules.exists_uniform_tensorPow_extension` gives `n' > 0` and sections
   `S_i, T_{i,a} ∈ Γ(X, L^{⊗n'})` with `X_{S_i} = X_{s_i}` and `T_{i,a}|_{X_{s_i}} = t_{i,a} • S_i|_{X_{s_i}}`.
4. *The family.* Index set `ι := I ⊕ Σ i, Fin (m_i)` (finite), `P := Sum.elim S (fun p ↦ T p.1 p.2)`,
   covering indices `I := range Sum.inl`. (a) is Step 1 (with `X_{S_i} = X_{s_i}`). (b): for `ℓ = inl i`, each
   generator `t_{i,a}` is the ratio `P_{inr (i,a)} / P_ℓ` by Step 3, and the image of `Γ(V, O)` is in the
   generating set, so `Subring.closure` of the set in (b) contains `range (f.appLE) ∪ {t_{i,a}}`, whose closure is
   `⊤` by Step 2.

**Edge cases.** `X = ∅`: any `n`, `ι := PEmpty`, `I := ∅`, (a)–(b) vacuous. `V` is the zero scheme: then `X = ∅`.
`m_i = 0` (a chart with `Γ(X_{s_i}, O)` generated by the image of `Γ(V, O)` alone): fine.

Used for the quasi-projective immersion into a relative Proj (Stacks 07RM). -/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- **Very-ample sections over an affine base** (Stacks 01VU over an affine base): a finite family of sections of
`L^{⊗n}` with affine, covering nonvanishing loci `X_{P_ℓ}` (`ℓ ∈ I`) on which the coordinate ring is generated
over `Γ(V, O)` by the ratios `P_j / P_ℓ`. -/
theorem AlgebraicGeometry.IsAmple.exists_charts_generators_of_isAffine
    {X V : AlgebraicGeometry.Scheme.{u}} (f : X ⟶ V) [AlgebraicGeometry.IsAffine V]
    [AlgebraicGeometry.LocallyOfFiniteType f] (L : X.Modules) [L.IsLineBundle]
    (hL : AlgebraicGeometry.IsAmple L) :
    ∃ (n : ℕ) (_ : 0 < n) (ι : Type u) (_ : Fintype ι)
      (P : ι → Γ(AlgebraicGeometry.Scheme.Modules.tensorPow L n, ⊤)) (I : Set ι),
      (∀ x : X, ∃ ℓ ∈ I, x ∈ (AlgebraicGeometry.Scheme.Modules.tensorPow L n).nonvanishingLocus (P ℓ)) ∧
      (∀ ℓ ∈ I, AlgebraicGeometry.IsAffineOpen
        ((AlgebraicGeometry.Scheme.Modules.tensorPow L n).nonvanishingLocus (P ℓ))) ∧
      ∀ ℓ ∈ I, Subring.closure
        (Set.range (f.appLE ⊤ ((AlgebraicGeometry.Scheme.Modules.tensorPow L n).nonvanishingLocus (P ℓ)) le_top) ∪
          {g | ∃ j, (AlgebraicGeometry.Scheme.Modules.tensorPow L n).res
              (le_top : (AlgebraicGeometry.Scheme.Modules.tensorPow L n).nonvanishingLocus (P ℓ) ≤ ⊤) (P j) =
            g • (AlgebraicGeometry.Scheme.Modules.tensorPow L n).res
              (le_top : (AlgebraicGeometry.Scheme.Modules.tensorPow L n).nonvanishingLocus (P ℓ) ≤ ⊤) (P ℓ)}) =
        ⊤ := by
  classical
  have hqs : QuasiSeparatedSpace X := AlgebraicGeometry.IsAmple.quasiSeparatedSpace L hL
  have hcpt : CompactSpace X := hL.1
  -- Step 1: finite affine cover by nonvanishing loci of sections of one power `L^{⊗n}`
  obtain ⟨n, hn, ι, hι, s, hcov, haff⟩ := AlgebraicGeometry.IsAmple.exists_finite_affine_cover L hL
  -- Step 2: finitely many ring generators of `Γ(X_{s i}, O)` over `Γ(V, O)`
  have hgen : ∀ i, ∃ (m : ℕ)
      (t : Fin m → Γ(X, (AlgebraicGeometry.Scheme.Modules.tensorPow L n).nonvanishingLocus (s i))),
      Subring.closure
        (Set.range (f.appLE ⊤ ((AlgebraicGeometry.Scheme.Modules.tensorPow L n).nonvanishingLocus (s i)) le_top) ∪
          Set.range t) = ⊤ := by
    intro i
    have hft : RingHom.FiniteType
        (f.appLE ⊤ ((AlgebraicGeometry.Scheme.Modules.tensorPow L n).nonvanishingLocus (s i)) le_top).hom :=
      AlgebraicGeometry.HasRingHomProperty.appLE (P := @AlgebraicGeometry.LocallyOfFiniteType) f inferInstance
        ⟨⊤, AlgebraicGeometry.isAffineOpen_top V⟩ ⟨_, haff i⟩ le_top
    let _ : Algebra Γ(V, ⊤) Γ(X, (AlgebraicGeometry.Scheme.Modules.tensorPow L n).nonvanishingLocus (s i)) :=
      (f.appLE ⊤ ((AlgebraicGeometry.Scheme.Modules.tensorPow L n).nonvanishingLocus (s i)) le_top).hom.toAlgebra
    have hft' : Algebra.FiniteType Γ(V, ⊤)
        Γ(X, (AlgebraicGeometry.Scheme.Modules.tensorPow L n).nonvanishingLocus (s i)) := hft
    obtain ⟨T, hT⟩ := hft'.out
    let eT := Fintype.equivFin (↥T)
    refine ⟨Fintype.card (↥T), fun k => ((eT.symm k).1 :
      Γ(X, (AlgebraicGeometry.Scheme.Modules.tensorPow L n).nonvanishingLocus (s i))), ?_⟩
    have hrange : Set.range (fun k => ((eT.symm k).1 :
        Γ(X, (AlgebraicGeometry.Scheme.Modules.tensorPow L n).nonvanishingLocus (s i)))) = (T : Set _) := by
      ext x
      constructor
      · rintro ⟨k, rfl⟩
        exact (eT.symm k).2
      · intro hx
        exact ⟨eT ⟨x, hx⟩, by simp⟩
    rw [hrange]
    have h := Algebra.adjoin_eq_ring_closure (R := Γ(V, ⊤))
      (↑T : Set Γ(X, (AlgebraicGeometry.Scheme.Modules.tensorPow L n).nonvanishingLocus (s i)))
    rw [hT, Algebra.top_toSubring, RingHom.algebraMap_toAlgebra] at h
    exact h.symm
  choose m t hgen using hgen
  -- Step 3: extend the generators (times a common power of the covering sections)
  obtain ⟨n', hn', S, T, hS, hT⟩ :=
    AlgebraicGeometry.Scheme.Modules.exists_uniform_tensorPow_extension L hn s m t
  -- Step 4: the family
  let J := ι ⊕ Σ i : ι, Fin (m i)
  let P : J → Γ(AlgebraicGeometry.Scheme.Modules.tensorPow L n', ⊤) := Sum.elim S (fun p => T p.1 p.2)
  refine ⟨n', hn', J, inferInstance, P, Set.range Sum.inl, ?_, ?_, ?_⟩
  · intro x
    obtain ⟨i, hx⟩ := hcov x
    refine ⟨Sum.inl i, ⟨i, rfl⟩, ?_⟩
    show x ∈ (AlgebraicGeometry.Scheme.Modules.tensorPow L n').nonvanishingLocus (S i)
    rw [hS i]
    exact hx
  · rintro _ ⟨i, rfl⟩
    show AlgebraicGeometry.IsAffineOpen ((AlgebraicGeometry.Scheme.Modules.tensorPow L n').nonvanishingLocus (S i))
    rw [hS i]
    exact haff i
  · rintro _ ⟨i, rfl⟩
    show Subring.closure
        (Set.range (f.appLE ⊤ ((AlgebraicGeometry.Scheme.Modules.tensorPow L n').nonvanishingLocus (S i)) le_top) ∪
          {g | ∃ j, (AlgebraicGeometry.Scheme.Modules.tensorPow L n').res
              (le_top : (AlgebraicGeometry.Scheme.Modules.tensorPow L n').nonvanishingLocus (S i) ≤ ⊤) (P j) =
            g • (AlgebraicGeometry.Scheme.Modules.tensorPow L n').res
              (le_top : (AlgebraicGeometry.Scheme.Modules.tensorPow L n').nonvanishingLocus (S i) ≤ ⊤) (S i)}) = ⊤
    rw [hS i]
    refine top_unique ?_
    rw [← hgen i]
    refine Subring.closure_mono (Set.union_subset_union_right _ ?_)
    rintro _ ⟨a, rfl⟩
    exact ⟨Sum.inr ⟨i, a⟩, hT i a⟩

end
