import MiyaokaMori.Prelude
import MiyaokaMori.Paper.S2WeightedJets.Intersection.DeformedJetAlgebra_Construction
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.ModulesMonoidalPreadditive
import MiyaokaMori.AlgebraicGeometry.Modules.Flat.AffineLinePullbackTorsionFree
import MiyaokaMori.AlgebraicGeometry.Modules.Basic.ModulesExactIffLocallyLift
import MiyaokaMori.AlgebraicGeometry.Modules.Basic.BiproductSections

/-! # The Rees syzygy sequence is exact

For a graded QC algebra `S` on `X`, `π : A¹_X → X` and `j : ℕ`, the `j`-th Rees piece `R_j = Im (gen S j)` is generated by
`gen S j : ⊕_{e ≤ j} π^*I^{(j-e)}_j → π^*S_j` (`e`-th component `λ^e · π^*incl`). The syzygy
`ψ_j : ⊕_{e ≤ j} π^*I^{(j-e+1)}_j → ⊕_{e ≤ j} π^*I^{(j-e)}_j` (on the `e`-th summand `π^*(stepHom) ≫ ι_e - λ ≫ ι_{e-1}`)
encodes the obvious relations `λ^e·x = λ^{e-1}·(λx)` for `x ∈ I^{(j-e+1)}_j ⊆ I^{(j-e)}_j`. **Main result**
(`reesDeformation.exact_syzygy_gen`, `epi_kernel_lift_syzygy`): `ker (gen S j) = Im ψ_j`, i.e. these are *all* the
relations. Consequence (in `DeformedJetAlgebraFiberAtZero_PartIso`): `s₀^*(ker gen)` dies in `coker (s₀^*ψ_j)`, the local
content of the description of the fibre at `λ = 0`.

Structure:
* §1, §1a, §1b: `I^{(p+1)}_n ⊆ I^{(p)}_n`
  (`landsIn_irrelevantPow_succ`, `irrelevantPow.stepHom`), `I^{(p)}_j = 0` for `p > j`, the syzygy `ψ_j` and
  `syzygy_comp_gen : ψ_j ≫ gen = 0`.
* §2: exactness. The proof is a section-level chase over an arbitrary open `V ⊆ A¹_X`
  (`Modules.exact_iff_locally_lift_sections`): given `x = (a_e)_e ∈ Γ(V, ⊕ π^*I^{(j-e)}_j)` with `Σ_e λ^e ā_e = 0`
  (`ā_e` the image in `Γ(V, π^*S_j)`), put `c_e := Σ_{f ≥ e} λ^{f-e} ā_f` (`ReesSyzygyAux.revSum`), so that
  `c_e = ā_e + λ c_{e+1}`, `c_{j+1} = 0`, and `λ^e c_e = -Σ_{f<e} λ^f ā_f ∈ Im(π^*I^{(j-e+1)}_j)` (as `I^{(j-f)} ⊆ I^{(j-e+1)}`
  for `f < e`). By **λ-saturation** (`AffineLinePullbackTorsionFree`: the only local input, namely that `λ` is a
  nonzerodivisor on `π^*N` and that `π^*` preserves monomorphisms) `c_e` itself comes from `π^*I^{(j-e+1)}_j`, say
  `c_e = incl(z_e)`; then `ψ_j((z_e)_e) = (c_e - λ c_{e+1})_e = (ā_e)_e = x` (checked componentwise inside `π^*S_j`,
  using injectivity of `π^*incl` on sections). This proves `ker gen = Im ψ_j` outright and needs no affine cover.

Source: Stacks 052P (extended Rees algebra, `R/λR = gr_I(A)`); Lemma 2.3 of the paper.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v₁ u₁

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

open scoped CategoryTheory.MonoidalCategory

/-! ## §1 `I^{(p+1)}_n ⊆ I^{(p)}_n` -/

namespace AlgebraicGeometry.Scheme.GradedQCAlgebra

variable {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra)

/-- `I^{(p+1)}_n ⊆ I^{(p)}_n`: every component `S_{c+1} ⊗ I^{(p)}_{n-c-1} → S_n` of the generating map of `I^{(p+1)}_n`
lands in `I^{(p)}_n` (`landsIn_whiskerLeft_mul`), so the image does (`landsIn_biproduct`, `landsIn_of_epi`). -/
theorem landsIn_irrelevantPow_succ (p n : ℕ) : S.LandsIn (S.irrelevantPow (p + 1) n).2 p := by
  show S.LandsIn (CategoryTheory.Limits.image.ι (irrelevantPow.gen S p n)) p
  apply S.landsIn_of_epi (CategoryTheory.Limits.factorThruImage (irrelevantPow.gen S p n))
  rw [CategoryTheory.Limits.image.fac]
  apply S.landsIn_biproduct
  intro c
  rw [S.ι_gen]
  exact S.landsIn_comp_eqToHom (by have := c.2; omega)
    (S.landsIn_whiskerLeft_mul p (S.landsIn_self p _) (c.1 + 1))

/-- The inclusion `I^{(p+1)}_n ⟶ I^{(p)}_n` (`Abelian.monoLift` of `landsIn_irrelevantPow_succ`); its cokernel is the
`p`-th graded piece `I^{(p)}_n / I^{(p+1)}_n` of `gr_{S_+}(S)` in degree `n`. For `p = 1`, `n ≥ 1`: `I^{(1)}_n = S_n`
(every `S_n` with `n ≥ 1` lies in `S_+`), so `cokernel (stepHom S 1 n) = S_n / I^{(2)}_n = (S_+/S_+^2)_n` is the
**linear piece** of weight `n`. -/
noncomputable def irrelevantPow.stepHom (p n : ℕ) : (S.irrelevantPow (p + 1) n).1 ⟶ (S.irrelevantPow p n).1 :=
  haveI := S.mono_irrelevantPow p n
  CategoryTheory.Abelian.monoLift (S.irrelevantPow p n).2 (S.irrelevantPow (p + 1) n).2
    (S.landsIn_irrelevantPow_succ p n)

theorem irrelevantPow.stepHom_comp (p n : ℕ) :
    irrelevantPow.stepHom S p n ≫ (S.irrelevantPow p n).2 = (S.irrelevantPow (p + 1) n).2 :=
  haveI := S.mono_irrelevantPow p n
  CategoryTheory.Abelian.monoLift_comp _ _ _

/-! ## §1a `I^{(p)}_j = 0` for `p > j` -/

/-- `I^{(p)}_j = 0` for `p > j`: the generating biproduct of `I^{(p+1)}_j` runs over `a : Fin j` with factors
`I^{(p)}_{j-a-1}`, `j - a - 1 < p`, which vanish by induction; the image of a map out of a zero object is zero
(`imageZero'`). Edge case `j = 0`, `p ≥ 1`: empty biproduct. -/
theorem irrelevantPow_isZero_of_lt : ∀ (p j : ℕ), j < p → CategoryTheory.Limits.IsZero (S.irrelevantPow p j).1
  | 0, j, h => absurd h (Nat.not_lt_zero j)
  | p + 1, j, h => by
    have hsrc : CategoryTheory.Limits.IsZero (CategoryTheory.Limits.biproduct
        (fun a : Fin j => S.part (a.1 + 1) ⊗ (S.irrelevantPow p (j - (a.1 + 1))).1)) := by
      rw [CategoryTheory.Limits.IsZero.iff_id_eq_zero]
      apply CategoryTheory.Limits.biproduct.hom_ext
      intro a
      have hz : CategoryTheory.Limits.IsZero (S.irrelevantPow p (j - (a.1 + 1))).1 :=
        irrelevantPow_isZero_of_lt p (j - (a.1 + 1)) (by have := a.2; omega)
      have h1 : 𝟙 (S.part (a.1 + 1) ⊗ (S.irrelevantPow p (j - (a.1 + 1))).1) = 0 := by
        rw [← CategoryTheory.MonoidalCategory.whiskerLeft_id, hz.eq_of_src (𝟙 _) 0,
          AlgebraicGeometry.Scheme.Modules.whiskerLeft_zero']
      rw [Category.id_comp, zero_comp, ← Category.comp_id (CategoryTheory.Limits.biproduct.π _ a), h1, comp_zero]
    have hgen : irrelevantPow.gen S p j = 0 := hsrc.eq_of_src _ _
    show CategoryTheory.Limits.IsZero (CategoryTheory.Limits.image (irrelevantPow.gen S p j))
    exact CategoryTheory.Limits.IsZero.of_iso (CategoryTheory.Limits.isZero_zero _)
      (CategoryTheory.Limits.imageZero' hgen)

/-- The inclusion `I^{(p)}_j → S_j` vanishes for `p > j`. -/
theorem irrelevantPow_snd_eq_zero_of_lt (p j : ℕ) (h : j < p) : (S.irrelevantPow p j).2 = 0 :=
  (S.irrelevantPow_isZero_of_lt p j h).eq_of_src _ _

/-! ## §1b The syzygy `ψ_j` of the generating map `gen S j` of the Rees piece `R_j`

`gen S j : ⊕_{e ≤ j} π^*I^{(j-e)}_j → π^*S_j`, `e`-th component `λ^e · π^*(incl)`. The obvious relations among these
components are: for `e ≥ 1` and `x ∈ I^{(j-e+1)}_j ⊆ I^{(j-e)}_j`, `λ^e·x` (slot `e`) equals `λ^{e-1}·(λx)` (slot `e-1`).
`ψ_j` encodes them: on the summand `π^*I^{(j-e+1)}_j` it is `π^*(stepHom) ≫ ι_e - λ ≫ ι_{e-1}` (no `λ`-term for `e = 0`,
where the summand `π^*I^{(j+1)}_j` is `0` anyway). Along `λ = 0` the `λ`-terms die and `s₀^*ψ_j = ⊕_e stepHom (j-e) j`,
whose cokernel is `⊕_p I^{(p)}_j/I^{(p+1)}_j`; that `ψ_j` generates `ker (gen S j)` modulo `λ` is the local content of (c1)
(`reesDeformation.kernel_ι_comp_cokernel_π_pullback_syzygy`). -/

namespace reesDeformation

/-- The `λ`-part of the syzygy on the `e`-th summand: `0` for `e = 0`; for `e = e'+1`, `λ · (–)` into slot `e'`
(`I^{(j-(e'+1)+1)}_j = I^{(j-e')}_j` by `eqToHom`). -/
noncomputable def syzygyLam (j : ℕ) : ∀ e : Fin (j + 1),
    (Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow (j - e.1 + 1) j).1 ⟶
      CategoryTheory.Limits.biproduct (fun e : Fin (j + 1) =>
        (Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow (j - e.1) j).1)
  | ⟨0, _⟩ => 0
  | ⟨e' + 1, h⟩ =>
    affineLineOver.mulCoordPow 1 _ ≫
      eqToHom (congrArg (fun m => (Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow m j).1)
        (by omega : j - (e' + 1) + 1 = j - e')) ≫
      CategoryTheory.Limits.biproduct.ι (fun e : Fin (j + 1) => (Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow (j - e.1) j).1) (⟨e', by omega⟩ : Fin (j + 1))

theorem syzygyLam_zero (j : ℕ) (h : 0 < j + 1) : syzygyLam S j ⟨0, h⟩ = 0 := rfl

theorem syzygyLam_succ (j e' : ℕ) (h : e' + 1 < j + 1) :
    syzygyLam S j ⟨e' + 1, h⟩ =
      affineLineOver.mulCoordPow 1 _ ≫
        eqToHom (congrArg (fun m => (Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow m j).1)
          (by omega : j - (e' + 1) + 1 = j - e')) ≫
        CategoryTheory.Limits.biproduct.ι (fun e : Fin (j + 1) => (Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow (j - e.1) j).1) (⟨e', by omega⟩ : Fin (j + 1)) := rfl

/-- The syzygy `ψ_j : ⊕_{e ≤ j} π^*I^{(j-e+1)}_j ⟶ ⊕_{e ≤ j} π^*I^{(j-e)}_j`. -/
noncomputable def syzygy (j : ℕ) :
    CategoryTheory.Limits.biproduct (fun e : Fin (j + 1) =>
        (Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow (j - e.1 + 1) j).1) ⟶
      CategoryTheory.Limits.biproduct (fun e : Fin (j + 1) =>
        (Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow (j - e.1) j).1) :=
  CategoryTheory.Limits.biproduct.desc fun e =>
    (Modules.pullback (affineLineOver.toBase X)).map (irrelevantPow.stepHom S (j - e.1) j) ≫
        CategoryTheory.Limits.biproduct.ι (fun e : Fin (j + 1) => (Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow (j - e.1) j).1) e -
      syzygyLam S j e

theorem ι_syzygy (j : ℕ) (e : Fin (j + 1)) :
    CategoryTheory.Limits.biproduct.ι _ e ≫ syzygy S j =
      (Modules.pullback (affineLineOver.toBase X)).map (irrelevantPow.stepHom S (j - e.1) j) ≫
          CategoryTheory.Limits.biproduct.ι (fun e : Fin (j + 1) => (Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow (j - e.1) j).1) e -
        syzygyLam S j e :=
  CategoryTheory.Limits.biproduct.ι_desc _ e

/-- Transport of `π^*(incl)` along an index equality (stated with `pullMap`, the spelling produced by `ι_gen`). -/
theorem eqToHom_comp_pullMap_irrelevantPow_snd (j : ℕ) {a b : ℕ} (h : a = b) :
    eqToHom (congrArg (fun m => (Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow m j).1) h) ≫
        pullMap S (S.irrelevantPow b j).2 = pullMap S (S.irrelevantPow a j).2 := by
  subst h
  simp

/-- `π^*(stepHom) ≫ π^*(incl_p) = π^*(incl_{p+1})` (with `pullMap`). -/
theorem pullback_map_stepHom_comp_pullMap (p j : ℕ) :
    (Modules.pullback (affineLineOver.toBase X)).map (irrelevantPow.stepHom S p j) ≫
      pullMap S (S.irrelevantPow p j).2 = pullMap S (S.irrelevantPow (p + 1) j).2 := by
  show (Modules.pullback (affineLineOver.toBase X)).map (irrelevantPow.stepHom S p j) ≫
    (Modules.pullback (affineLineOver.toBase X)).map (S.irrelevantPow p j).2 =
    (Modules.pullback (affineLineOver.toBase X)).map (S.irrelevantPow (p + 1) j).2
  rw [← Functor.map_comp, irrelevantPow.stepHom_comp]

/-- `λ^a ≫ λ^b = λ^b ≫ λ^a`. -/
theorem mulCoordPow_comm (a b : ℕ) (M : (affineLineOver X).Modules) :
    affineLineOver.mulCoordPow a M ≫ affineLineOver.mulCoordPow b M =
      affineLineOver.mulCoordPow b M ≫ affineLineOver.mulCoordPow a M := by
  rw [← affineLineOver.mulCoordPow_add, ← affineLineOver.mulCoordPow_add, Nat.add_comm]

/-- **`ψ_j ≫ gen S j = 0`**: on the `e`-th summand, `π^*(stepHom ≫ incl) ≫ λ^e = π^*(incl_{j-e+1}) ≫ λ^e` and, for
`e = e'+1`, `λ ≫ π^*(incl_{j-e'}) ≫ λ^{e'} = π^*(incl_{j-e'}) ≫ λ^{e'+1}` (`mulCoordPow_naturality`, `mulCoordPow_add`);
for `e = 0` the summand is `π^*I^{(j+1)}_j = 0`. -/
theorem syzygy_comp_gen (j : ℕ) : syzygy S j ≫ gen S j = 0 := by
  apply CategoryTheory.Limits.biproduct.hom_ext'
  rintro ⟨e, he⟩
  rw [← Category.assoc, ι_syzygy, Preadditive.sub_comp, Category.assoc, ι_gen, comp_zero,
    ← Category.assoc]
  simp only [Fin.val_mk]
  rw [pullback_map_stepHom_comp_pullMap]
  cases e with
  | zero =>
    rw [syzygyLam_zero, zero_comp, sub_zero]
    show pullMap S (S.irrelevantPow (j - 0 + 1) j).2 ≫ affineLineOver.mulCoordPow 0 _ = 0
    rw [S.irrelevantPow_snd_eq_zero_of_lt (j - 0 + 1) j (by omega)]
    show (Modules.pullback (affineLineOver.toBase X)).map 0 ≫ affineLineOver.mulCoordPow 0 _ = 0
    rw [Functor.map_zero, zero_comp]
  | succ e' =>
    rw [syzygyLam_succ, Category.assoc, Category.assoc, ι_gen]
    simp only [Fin.val_mk]
    rw [← Category.assoc (eqToHom _),
      eqToHom_comp_pullMap_irrelevantPow_snd S j (by omega : j - (e' + 1) + 1 = j - e'), ← Category.assoc,
      affineLineOver.mulCoordPow_naturality, Category.assoc, ← affineLineOver.mulCoordPow_add,
      Nat.add_comm 1 e', sub_self]

end reesDeformation

end AlgebraicGeometry.Scheme.GradedQCAlgebra

/-! ## §2 Exactness of the syzygy sequence -/

namespace ReesSyzygyAux

variable {G : Type*} [AddCommGroup G]

/-- `revSum j lam1 ab m = ab (j-m+1) + lam1 (ab (j-m+2) + lam1 (⋯ + lam1 (ab j)))`: the tail sum
`c_e = Σ_{f ≥ e} λ^{f-e} a_f` at `e = j + 1 - m`, by recursion on `m`. -/
def revSum (j : ℕ) (lam1 : G → G) (ab : ℕ → G) : ℕ → G
  | 0 => 0
  | m + 1 => ab (j - m) + lam1 (revSum j lam1 ab m)

theorem revSum_invariant (j : ℕ) (lam : ℕ → G →+ G) (hlam : ∀ a y, lam a (lam 1 y) = lam (a + 1) y)
    (ab : ℕ → G) : ∀ m, m ≤ j + 1 →
    (∑ f ∈ Finset.range (j + 1 - m), lam f (ab f)) + lam (j + 1 - m) (revSum j (lam 1) ab m) =
      ∑ f ∈ Finset.range (j + 1), lam f (ab f)
  | 0, _ => by simp [revSum]
  | m + 1, hm => by
    have h1 : j + 1 - (m + 1) = j - m := by omega
    have h2 : j + 1 - m = (j - m) + 1 := by omega
    have ih := revSum_invariant j lam hlam ab m (by omega)
    rw [h1, revSum, map_add, hlam, ← h2, ← ih, h2, Finset.sum_range_succ, add_assoc]

end ReesSyzygyAux

namespace AlgebraicGeometry.Scheme.GradedQCAlgebra

variable {X : AlgebraicGeometry.Scheme.{u}} (S : X.GradedQCAlgebra)

/-- `I^{(p')}_j ⊆ I^{(p)}_j` for `p ≤ p'` (iterate `landsIn_irrelevantPow_succ` via `stepHom_comp`). -/
theorem landsIn_irrelevantPow_of_le {p p' : ℕ} (h : p ≤ p') (j : ℕ) :
    S.LandsIn (S.irrelevantPow p' j).2 p := by
  induction p', h using Nat.le_induction with
  | base => exact S.landsIn_self p j
  | succ p' _ ih =>
    exact (irrelevantPow.stepHom_comp S p' j) ▸ S.landsIn_comp (irrelevantPow.stepHom S p' j) ih

namespace reesDeformation

/-- `y ∈ Γ(V, π^*S_j)` comes from `Γ(V, π^*I^{(p)}_j)`. -/
def InPullbackIrrelevantPow (j p : ℕ) (V : (affineLineOver X).Opens)
    (y : Γ((S.pullback (affineLineOver.toBase X)).part j, V)) : Prop :=
  ∃ z : Γ((Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow p j).1, V),
    (pullMap S (S.irrelevantPow p j).2).app V z = y

variable {S}

theorem InPullbackIrrelevantPow.zero (j p : ℕ) (V : (affineLineOver X).Opens) :
    InPullbackIrrelevantPow S j p V 0 :=
  ⟨0, Modules.Hom.app_zero' _ V⟩

theorem InPullbackIrrelevantPow.add {j p : ℕ} {V : (affineLineOver X).Opens}
    {y y' : Γ((S.pullback (affineLineOver.toBase X)).part j, V)}
    (h : InPullbackIrrelevantPow S j p V y) (h' : InPullbackIrrelevantPow S j p V y') :
    InPullbackIrrelevantPow S j p V (y + y') := by
  obtain ⟨z, rfl⟩ := h
  obtain ⟨z', rfl⟩ := h'
  exact ⟨z + z', Modules.Hom.app_add' _ V z z'⟩

theorem InPullbackIrrelevantPow.neg {j p : ℕ} {V : (affineLineOver X).Opens}
    {y : Γ((S.pullback (affineLineOver.toBase X)).part j, V)}
    (h : InPullbackIrrelevantPow S j p V y) : InPullbackIrrelevantPow S j p V (-y) := by
  obtain ⟨z, rfl⟩ := h
  exact ⟨-z, Modules.Hom.app_neg' _ V z⟩

theorem InPullbackIrrelevantPow.sum {j p : ℕ} {V : (affineLineOver X).Opens} {ι : Type*} (s : Finset ι)
    (f : ι → Γ((S.pullback (affineLineOver.toBase X)).part j, V))
    (h : ∀ i ∈ s, InPullbackIrrelevantPow S j p V (f i)) :
    InPullbackIrrelevantPow S j p V (∑ i ∈ s, f i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa using InPullbackIrrelevantPow.zero (S := S) j p V
  | insert a s ha ih =>
    rw [Finset.sum_insert ha]
    exact (h a (Finset.mem_insert_self a s)).add (ih fun i hi => h i (Finset.mem_insert_of_mem hi))

/-- Images are stable under `λ^e` (`mulCoordPow_naturality`). -/
theorem InPullbackIrrelevantPow.mulCoordPow {j p : ℕ} {V : (affineLineOver X).Opens}
    {y : Γ((S.pullback (affineLineOver.toBase X)).part j, V)}
    (h : InPullbackIrrelevantPow S j p V y) (e : ℕ) :
    InPullbackIrrelevantPow S j p V
      ((affineLineOver.mulCoordPow e ((S.pullback (affineLineOver.toBase X)).part j)).app V y) := by
  obtain ⟨z, rfl⟩ := h
  refine ⟨(affineLineOver.mulCoordPow e _).app V z, ?_⟩
  have := congrArg (fun φ : (Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow p j).1 ⟶
      (S.pullback (affineLineOver.toBase X)).part j => φ.app V z)
    (affineLineOver.mulCoordPow_naturality e (pullMap S (S.irrelevantPow p j).2))
  simp only [Modules.Hom.comp_app] at this
  exact this

/-- Monotonicity in `p`: `I^{(p')}_j ⊆ I^{(p)}_j` for `p ≤ p'`. -/
theorem InPullbackIrrelevantPow.of_le {j p p' : ℕ} (hpp : p ≤ p') {V : (affineLineOver X).Opens}
    {y : Γ((S.pullback (affineLineOver.toBase X)).part j, V)}
    (h : InPullbackIrrelevantPow S j p' V y) : InPullbackIrrelevantPow S j p V y := by
  obtain ⟨z, rfl⟩ := h
  obtain ⟨g, hg⟩ := (S.landsIn_iff_exists _ p).1 (S.landsIn_irrelevantPow_of_le hpp j)
  refine ⟨((Modules.pullback (affineLineOver.toBase X)).map g).app V z, ?_⟩
  have : pullMap S (S.irrelevantPow p' j).2 =
      (Modules.pullback (affineLineOver.toBase X)).map g ≫ pullMap S (S.irrelevantPow p j).2 := by
    show (Modules.pullback (affineLineOver.toBase X)).map (S.irrelevantPow p' j).2 =
      (Modules.pullback (affineLineOver.toBase X)).map g ≫
        (Modules.pullback (affineLineOver.toBase X)).map (S.irrelevantPow p j).2
    rw [← Functor.map_comp, ← hg]
  rw [this]
  rfl

/-- λ-saturation of the images: `λ^e y ∈ Im(π^*I^{(p)}_j) ⟹ y ∈ Im(π^*I^{(p)}_j)`. -/
theorem InPullbackIrrelevantPow.of_mulCoordPow {j p : ℕ} {V : (affineLineOver X).Opens}
    {y : Γ((S.pullback (affineLineOver.toBase X)).part j, V)} (e : ℕ)
    (h : InPullbackIrrelevantPow S j p V
      ((affineLineOver.mulCoordPow e ((S.pullback (affineLineOver.toBase X)).part j)).app V y)) :
    InPullbackIrrelevantPow S j p V y := by
  obtain ⟨z, hz⟩ := h
  haveI := S.mono_irrelevantPow p j
  haveI := S.irrelevantPow_isQuasicoherent p j
  haveI := S.quasicoherent j
  exact affineLineOver.exists_pullback_toBase_map_app_eq_of_mulCoordPow (S.irrelevantPow p j).2 V e y z hz

/-- `π^*(I^{(p)}_j → S_j)` is injective on sections (`mono_pullback_toBase_map`). -/
theorem pullMap_irrelevantPow_app_injective (p j : ℕ) (V : (affineLineOver X).Opens) :
    Function.Injective ((pullMap S (S.irrelevantPow p j).2).app V) := by
  haveI := S.mono_irrelevantPow p j
  haveI := S.irrelevantPow_isQuasicoherent p j
  haveI := S.quasicoherent j
  exact @Modules.app_injective_of_mono _ _ _ (pullMap S (S.irrelevantPow p j).2)
    (affineLineOver.mono_pullback_toBase_map (X := X) (S.irrelevantPow p j).2) V

variable (S)

/-- The `(e, e')` matrix entry of `ψ_j`, pushed into `π^*S_j`: `ι_e ≫ ψ_j ≫ π_{e'} ≫ π^*incl_{j-e'}` is
`π^*incl_{j-e+1}` if `e = e'`, `-λ ≫ π^*incl_{j-e+1}` if `e = e' + 1`, and `0` otherwise. -/
theorem ι_syzygy_π_pullMap (j : ℕ) (e e' : Fin (j + 1)) :
    CategoryTheory.Limits.biproduct.ι (fun e : Fin (j + 1) =>
        (Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow (j - e.1 + 1) j).1) e ≫
      syzygy S j ≫
      CategoryTheory.Limits.biproduct.π (fun e : Fin (j + 1) =>
        (Modules.pullback (affineLineOver.toBase X)).obj (S.irrelevantPow (j - e.1) j).1) e' ≫
      pullMap S (S.irrelevantPow (j - e'.1) j).2 =
    (if e = e' then pullMap S (S.irrelevantPow (j - e.1 + 1) j).2 else 0) -
    (if e.1 = e'.1 + 1 then
      affineLineOver.mulCoordPow 1 _ ≫ pullMap S (S.irrelevantPow (j - e.1 + 1) j).2 else 0) := by
  rw [← Category.assoc, ι_syzygy, Preadditive.sub_comp]
  congr 1
  · rw [Category.assoc, ← Category.assoc (CategoryTheory.Limits.biproduct.ι _ e),
      CategoryTheory.Limits.biproduct.ι_π]
    split_ifs with h
    · subst h
      rw [eqToHom_refl, Category.id_comp]
      exact pullback_map_stepHom_comp_pullMap S (j - e.1) j
    · rw [zero_comp, comp_zero]
  · obtain ⟨e, he⟩ := e
    cases e with
    | zero =>
      rw [syzygyLam_zero, zero_comp, if_neg]
      exact fun h => Nat.succ_ne_zero _ h.symm
    | succ e'' =>
      rw [syzygyLam_succ, Category.assoc, Category.assoc,
        ← Category.assoc (CategoryTheory.Limits.biproduct.ι _ _), CategoryTheory.Limits.biproduct.ι_π]
      by_cases h : (⟨e'', by omega⟩ : Fin (j + 1)) = e'
      · subst h
        rw [dif_pos rfl, eqToHom_refl, Category.id_comp, if_pos rfl,
          eqToHom_comp_pullMap_irrelevantPow_snd S j (by omega : j - (e'' + 1) + 1 = j - e'')]
      · rw [dif_neg h, zero_comp, comp_zero, comp_zero, if_neg]
        intro h'
        apply h
        exact Fin.ext (Nat.succ_injective h')

/-- **Exactness of the Rees syzygy sequence** `⊕_e π^*I^{(j-e+1)}_j --ψ_j--> ⊕_e π^*I^{(j-e)}_j --gen--> π^*S_j`. -/
theorem exact_syzygy_gen (j : ℕ) :
    (CategoryTheory.ShortComplex.mk (syzygy S j) (gen S j) (syzygy_comp_gen S j)).Exact := by
  classical
  rw [Modules.exact_iff_locally_lift_sections]
  intro V x hx p hp
  refine ⟨V, le_rfl, hp, ?_⟩
  let P := Modules.pullback (affineLineOver.toBase X)
  let Bf : Fin (j + 1) → (affineLineOver X).Modules := fun e => P.obj (S.irrelevantPow (j - e.1) j).1
  let Af : Fin (j + 1) → (affineLineOver X).Modules := fun e => P.obj (S.irrelevantPow (j - e.1 + 1) j).1
  let T : (affineLineOver X).Modules := (S.pullback (affineLineOver.toBase X)).part j
  let lam : ℕ → Γ(T, V) →+ Γ(T, V) := fun a => ((affineLineOver.mulCoordPow a T).app V).hom
  have hlam : ∀ a y, lam a (lam 1 y) = lam (a + 1) y := by
    intro a y
    have := congrArg (fun φ : T ⟶ T => φ.app V y) (affineLineOver.mulCoordPow_add 1 a T)
    simp only [Modules.Hom.comp_app] at this
    rw [Nat.add_comm] at this
    exact this.symm
  let a : ∀ e : Fin (j + 1), Γ(Bf e, V) := fun e => (CategoryTheory.Limits.biproduct.π Bf e).app V x
  let abar : Fin (j + 1) → Γ(T, V) := fun e => (pullMap S (S.irrelevantPow (j - e.1) j).2).app V (a e)
  let ab : ℕ → Γ(T, V) := fun f => if h : f < j + 1 then abar ⟨f, h⟩ else 0
  have hab : ∀ e : Fin (j + 1), ab e.1 = abar e := fun e => dif_pos e.2
  -- (1) `Σ_e λ^e ā_e = gen x = 0`
  have hsum : ∑ f ∈ Finset.range (j + 1), lam f (ab f) = 0 := by
    rw [← Fin.sum_univ_eq_sum_range (fun f => lam f (ab f)) (j + 1)]
    have hx' : (gen S j).app V x = 0 := hx
    rw [Modules.biproduct_sections_total Bf V x, Modules.Hom.app_sum] at hx'
    refine Eq.trans ?_ hx'
    refine Finset.sum_congr rfl fun e _ => ?_
    have := congrArg (fun φ : Bf e ⟶ T => φ.app V (a e)) (ι_gen S j e)
    simp only [Modules.Hom.comp_app] at this
    rw [hab e]
    exact this.symm
  -- (2) the tail sums `c_e = Σ_{f ≥ e} λ^{f-e} ā_f`
  let c : ℕ → Γ(T, V) := fun e => ReesSyzygyAux.revSum j (lam 1) ab (j + 1 - e)
  have hc_step : ∀ e, e ≤ j → c e = ab e + lam 1 (c (e + 1)) := by
    intro e he
    have h1 : j + 1 - e = (j - e) + 1 := by omega
    have h2 : j + 1 - (e + 1) = j - e := by omega
    have h3 : j - (j - e) = e := by omega
    simp only [c, h1, h2, ReesSyzygyAux.revSum, h3]
  have hinv : ∀ e, e ≤ j + 1 → (∑ f ∈ Finset.range e, lam f (ab f)) + lam e (c e) = 0 := by
    intro e he
    have := ReesSyzygyAux.revSum_invariant j lam hlam ab (j + 1 - e) (by omega)
    have h1 : j + 1 - (j + 1 - e) = e := by omega
    rw [h1] at this
    exact this.trans hsum
  -- (3) `Σ_{f<e} λ^f ā_f ∈ Im(π^*I^{(j-e+1)}_j)` for `e ≤ j`
  have hT : ∀ e, e ≤ j →
      InPullbackIrrelevantPow S j (j - e + 1) V (∑ f ∈ Finset.range e, lam f (ab f)) := by
    intro e he
    refine InPullbackIrrelevantPow.sum _ _ fun f hf => ?_
    rw [Finset.mem_range] at hf
    have hfj : f < j + 1 := by omega
    have : ab f = abar ⟨f, hfj⟩ := dif_pos hfj
    rw [this]
    exact InPullbackIrrelevantPow.mulCoordPow
      (InPullbackIrrelevantPow.of_le (show j - e + 1 ≤ j - f by omega) ⟨a ⟨f, hfj⟩, rfl⟩) f
  -- (4) saturation: `c_e ∈ Im(π^*I^{(j-e+1)}_j)`
  have hc_mem : ∀ e : Fin (j + 1), InPullbackIrrelevantPow S j (j - e.1 + 1) V (c e.1) := by
    intro e
    have h2 : lam e.1 (c e.1) = -(∑ f ∈ Finset.range e.1, lam f (ab f)) :=
      eq_neg_of_add_eq_zero_right (hinv e.1 (by omega))
    have hmem : InPullbackIrrelevantPow S j (j - e.1 + 1) V (lam e.1 (c e.1)) :=
      h2 ▸ (hT e.1 (by omega)).neg
    exact InPullbackIrrelevantPow.of_mulCoordPow e.1 hmem
  choose z hz using hc_mem
  refine ⟨∑ e : Fin (j + 1), (CategoryTheory.Limits.biproduct.ι Af e).app V (z e), ?_⟩
  have hres : (CategoryTheory.ShortComplex.mk (syzygy S j) (gen S j) (syzygy_comp_gen S j)).X₂.presheaf.map
      (homOfLE (le_refl V)).op x = x := by
    have hid : (CategoryTheory.ShortComplex.mk (syzygy S j) (gen S j) (syzygy_comp_gen S j)).X₂.presheaf.map
        (homOfLE (le_refl V)).op = 𝟙 _ :=
      (CategoryTheory.ShortComplex.mk (syzygy S j) (gen S j) (syzygy_comp_gen S j)).X₂.presheaf.map_id (op V)
    rw [hid]
    rfl
  rw [hres]
  -- (5) compare componentwise, inside `π^*S_j`
  apply (Modules.biproduct_sections_bijective Bf V).1
  funext e'
  show (CategoryTheory.Limits.biproduct.π Bf e').app V
    ((syzygy S j).app V (∑ e : Fin (j + 1), (CategoryTheory.Limits.biproduct.ι Af e).app V (z e))) = a e'
  apply pullMap_irrelevantPow_app_injective (S := S) (j - e'.1) j V
  rw [Modules.Hom.app_sum, Modules.Hom.app_sum, Modules.Hom.app_sum]
  have hterm : ∀ e : Fin (j + 1), (pullMap S (S.irrelevantPow (j - e'.1) j).2).app V
      ((CategoryTheory.Limits.biproduct.π Bf e').app V
        ((syzygy S j).app V ((CategoryTheory.Limits.biproduct.ι Af e).app V (z e)))) =
      (if e = e' then c e.1 else 0) - (if e.1 = e'.1 + 1 then lam 1 (c e.1) else 0) := by
    intro e
    have := congrArg (fun φ : Af e ⟶ T => φ.app V (z e)) (ι_syzygy_π_pullMap S j e e')
    simp only [Modules.Hom.comp_app] at this
    refine this.trans ?_
    rw [Modules.Hom.sub_app_apply]
    congr 1
    · split_ifs with h
      · exact hz e
      · rfl
    · split_ifs with h
      · rw [affineLineOver.mulCoordPow_naturality 1 (pullMap S (S.irrelevantPow (j - e.1 + 1) j).2)]
        simp only [Modules.Hom.comp_app]
        show lam 1 ((pullMap S (S.irrelevantPow (j - e.1 + 1) j).2).app V (z e)) = _
        rw [hz e]
      · rfl
  simp only [hterm]
  rw [Finset.sum_sub_distrib, Finset.sum_ite_eq', if_pos (Finset.mem_univ e')]
  have hsecond : (∑ e : Fin (j + 1), if e.1 = e'.1 + 1 then lam 1 (c e.1) else 0) = lam 1 (c (e'.1 + 1)) := by
    by_cases h : e'.1 + 1 < j + 1
    · have : ∀ e : Fin (j + 1), (if e.1 = e'.1 + 1 then lam 1 (c e.1) else 0) =
          (if e = ⟨e'.1 + 1, h⟩ then lam 1 (c e.1) else 0) := by
        intro e
        congr 1
        exact propext ⟨fun h' => Fin.ext h', fun h' => congrArg Fin.val h'⟩
      simp only [this]
      rw [Finset.sum_ite_eq', if_pos (Finset.mem_univ _)]
    · have hj : e'.1 = j := by have := e'.2; omega
      have hz0 : c (e'.1 + 1) = 0 := by simp [c, hj, ReesSyzygyAux.revSum]
      rw [hz0, map_zero]
      refine Finset.sum_eq_zero fun e _ => ?_
      rw [if_neg]
      have := e.2
      omega
  rw [hsecond, ← sub_eq_zero, hc_step e'.1 (by have := e'.2; omega), hab e']
  abel

/-- The lift `ψ'_j : ⊕_e π^*I^{(j-e+1)}_j ⟶ ker (gen S j)` of the syzygy is an epimorphism (`ker gen = Im ψ_j`). -/
theorem epi_kernel_lift_syzygy (j : ℕ) :
    Epi (CategoryTheory.Limits.kernel.lift (gen S j) (syzygy S j) (syzygy_comp_gen S j)) :=
  (CategoryTheory.ShortComplex.exact_iff_epi_kernel_lift _).1 (exact_syzygy_gen S j)

end reesDeformation

end AlgebraicGeometry.Scheme.GradedQCAlgebra

end
