import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Chow.DivisorOperator.RatDivisorOpOfCycleClass
import MiyaokaMori.AlgebraicGeometry.Varieties.Basic.ClosedSubvariety
import MiyaokaMori.AlgebraicGeometry.Varieties.Curves.SmoothProjectiveCurve
import MiyaokaMori.AlgebraicGeometry.Varieties.Basic.Variety
import MiyaokaMori.AlgebraicGeometry.Varieties.Basic.VarietySchemeAccessors
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.VectorBundle
import MiyaokaMori.AlgebraicGeometry.Divisors.Degree.VectorBundleDegree
import MiyaokaMori.AlgebraicGeometry.Chow.CapCommutes
import MiyaokaMori.AlgebraicGeometry.Chow.Degree.ChowDegreeRat
import MiyaokaMori.AlgebraicGeometry.Divisors.Degree.DegreeAdditiveFiltration
import MiyaokaMori.Paper.S2WeightedJets.Intersection.DoubleSumReciprocal
import MiyaokaMori.AlgebraicGeometry.Divisors.Effective.EffectiveCartierDivisorScheme
import MiyaokaMori.AlgebraicGeometry.Chow.IntersectionNumber.FiberDegree
import MiyaokaMori.AlgebraicGeometry.Chow.Cycles.FundamentalClassRat
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.SheafOfModulesIsLineBundle
import MiyaokaMori.RingTheory.ProdAddOfMulEqZero
import MiyaokaMori.AlgebraicGeometry.Morphisms.ProperOverField
import MiyaokaMori.Paper.S2WeightedJets.Intersection.PullbackClassDegree
import MiyaokaMori.AlgebraicGeometry.Chow.IntersectionNumber.PullbackSquareVanishes
import MiyaokaMori.AlgebraicGeometry.Chow.DivisorOperator.RatDivisorOpToEnd
import MiyaokaMori.AlgebraicGeometry.Chow.DivisorOperator.RatDivisorOperator
import MiyaokaMori.AlgebraicGeometry.Chow.IntersectionNumber.RationalTopSelfIntersection
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.RelativeProjTwistQC
import MiyaokaMori.AlgebraicGeometry.Varieties.Dimension.SchemeDimension
import MiyaokaMori.Paper.S2WeightedJets.Intersection.SplitTautologicalClass
import MiyaokaMori.Paper.S2WeightedJets.Intersection.SplitWeightedAlgebra
import MiyaokaMori.Paper.S2WeightedJets.Intersection.SplitWeightedProjectivization
import MiyaokaMori.AlgebraicGeometry.Modules.SubbundleFiltration
import MiyaokaMori.AlgebraicGeometry.Varieties.Dimension.VarietyDimension
import MiyaokaMori.Paper.S2WeightedJets.Intersection.WeightedRelation
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.WeightedSymAlgebra
import MiyaokaMori.AlgebraicGeometry.Morphisms.IsProjectiveOverIsProper

/-! # Expanding the weighted relation

Expand eq. (2.10) of the paper and take degrees:
`(H^sp)^{s_k} = −v Σ_i Σ_q deg Q_i/q = −v·d·h_k` (`v` = the fiber degree at a closed point `c` divided by
`m^{s_k−1}`), which is eq. (2.9) of Proposition 2.4. The product is expanded in the
commutative algebra generated by the Chow endomorphisms; for a term containing two pulled-back factors, commutativity
moves these two factors to the outside, and the vanishing of the square of a pullback (`CH_2(C) = 0`) makes its
degree zero.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

private theorem lineBundle_ratDivisorOp_comm {K : Type u} [Field K]
    {X : AlgebraicGeometry.Scheme.{u}}
    [X.Over (AlgebraicGeometry.Spec (CommRingCat.of K))]
    [AlgebraicGeometry.LocallyOfFiniteType (X ↘ AlgebraicGeometry.Spec (CommRingCat.of K))]
    (L L' : X.Modules) [L.IsLineBundle] [L'.IsLineBundle] (d : ℕ) :
    (AlgebraicGeometry.ratDivisorOpOfLineBundle L d).comp
        (AlgebraicGeometry.ratDivisorOpOfLineBundle L' (d + 1)) =
      (AlgebraicGeometry.ratDivisorOpOfLineBundle L' d).comp
        (AlgebraicGeometry.ratDivisorOpOfLineBundle L (d + 1)) := by
  unfold AlgebraicGeometry.ratDivisorOpOfLineBundle AddMonoidHom.ratExtend
  apply LinearMap.ext
  intro z
  change
    ((LinearMap.baseChange ℚ
      (AlgebraicGeometry.firstChernClass L (d + 1)).toIntLinearMap).comp
      (LinearMap.baseChange ℚ
        (AlgebraicGeometry.firstChernClass L' (d + 2)).toIntLinearMap)) z =
    ((LinearMap.baseChange ℚ
      (AlgebraicGeometry.firstChernClass L' (d + 1)).toIntLinearMap).comp
      (LinearMap.baseChange ℚ
        (AlgebraicGeometry.firstChernClass L (d + 2)).toIntLinearMap)) z
  rw [← LinearMap.baseChange_comp, ← LinearMap.baseChange_comp]
  have hcomp :
      (AlgebraicGeometry.firstChernClass L (d + 1)).toIntLinearMap.comp
          (AlgebraicGeometry.firstChernClass L' (d + 2)).toIntLinearMap =
        (AlgebraicGeometry.firstChernClass L' (d + 1)).toIntLinearMap.comp
          (AlgebraicGeometry.firstChernClass L (d + 2)).toIntLinearMap := by
    apply LinearMap.ext
    intro x
    exact congrArg (fun f => f x)
      (AlgebraicGeometry.firstChernClass_comm (k := K) (X := X) L L' d)
  rw [hcomp]

private theorem lineBundle_toEnd_comm {K : Type u} [Field K]
    {X : AlgebraicGeometry.Scheme.{u}}
    [X.Over (AlgebraicGeometry.Spec (CommRingCat.of K))]
    [AlgebraicGeometry.LocallyOfFiniteType (X ↘ AlgebraicGeometry.Spec (CommRingCat.of K))]
    (L L' : X.Modules) [L.IsLineBundle] [L'.IsLineBundle] :
    Commute
      (AlgebraicGeometry.RatDivisorOp.toEnd
        (AlgebraicGeometry.ratDivisorOpOfLineBundle L))
      (AlgebraicGeometry.RatDivisorOp.toEnd
        (AlgebraicGeometry.ratDivisorOpOfLineBundle L')) := by
  apply LinearMap.ext
  intro z
  refine DirectSum.induction_on z ?_ ?_ ?_
  · simp only [Module.End.mul_apply, map_zero]
  · intro j x
    cases j with
    | zero =>
        change
          AlgebraicGeometry.RatDivisorOp.toEnd
              (AlgebraicGeometry.ratDivisorOpOfLineBundle L)
            (AlgebraicGeometry.RatDivisorOp.toEnd
              (AlgebraicGeometry.ratDivisorOpOfLineBundle L')
              (DirectSum.of _ 0 x)) =
          AlgebraicGeometry.RatDivisorOp.toEnd
              (AlgebraicGeometry.ratDivisorOpOfLineBundle L')
            (AlgebraicGeometry.RatDivisorOp.toEnd
              (AlgebraicGeometry.ratDivisorOpOfLineBundle L)
              (DirectSum.of _ 0 x))
        rw [AlgebraicGeometry.RatDivisorOp.toEnd_of_zero,
          AlgebraicGeometry.RatDivisorOp.toEnd_of_zero, map_zero, map_zero]
    | succ d =>
        cases d with
        | zero =>
            change
              AlgebraicGeometry.RatDivisorOp.toEnd
                  (AlgebraicGeometry.ratDivisorOpOfLineBundle L)
                (AlgebraicGeometry.RatDivisorOp.toEnd
                  (AlgebraicGeometry.ratDivisorOpOfLineBundle L')
                  (DirectSum.of _ 1 x)) =
              AlgebraicGeometry.RatDivisorOp.toEnd
                  (AlgebraicGeometry.ratDivisorOpOfLineBundle L')
                (AlgebraicGeometry.RatDivisorOp.toEnd
                  (AlgebraicGeometry.ratDivisorOpOfLineBundle L)
                  (DirectSum.of _ 1 x))
            rw [AlgebraicGeometry.RatDivisorOp.toEnd_of,
              AlgebraicGeometry.RatDivisorOp.toEnd_of,
              AlgebraicGeometry.RatDivisorOp.toEnd_of_zero,
              AlgebraicGeometry.RatDivisorOp.toEnd_of_zero]
        | succ e =>
            change
              AlgebraicGeometry.RatDivisorOp.toEnd
                  (AlgebraicGeometry.ratDivisorOpOfLineBundle L)
                (AlgebraicGeometry.RatDivisorOp.toEnd
                  (AlgebraicGeometry.ratDivisorOpOfLineBundle L')
                  (DirectSum.of _ (e + 2) x)) =
              AlgebraicGeometry.RatDivisorOp.toEnd
                  (AlgebraicGeometry.ratDivisorOpOfLineBundle L')
                (AlgebraicGeometry.RatDivisorOp.toEnd
                  (AlgebraicGeometry.ratDivisorOpOfLineBundle L)
                  (DirectSum.of _ (e + 2) x))
            rw [AlgebraicGeometry.RatDivisorOp.toEnd_of,
              AlgebraicGeometry.RatDivisorOp.toEnd_of,
              AlgebraicGeometry.RatDivisorOp.toEnd_of,
              AlgebraicGeometry.RatDivisorOp.toEnd_of]
            exact congrArg (DirectSum.of _ e) (congrArg (fun f => f x)
              (lineBundle_ratDivisorOp_comm (K := K) (X := X) L L' e))
  · intro x y hx hy
    simpa only [Module.End.mul_apply, map_add] using congrArg₂ (· + ·) hx hy

private theorem commute_add_smul {M : Type u} [AddCommGroup M] [Module ℚ M]
    (A B C : Module.End ℚ M) (c d : ℚ)
    (hAB : Commute A B) (hAC : Commute A C) (hBC : Commute B C) :
    Commute (A + c • B) (A + d • C) := by
  change (A + c • B) * (A + d • C) = (A + d • C) * (A + c • B)
  simp only [add_mul, mul_add, smul_mul_assoc, mul_smul_comm]
  rw [hAB.eq, hAC.eq, hBC.eq]
  module

private theorem component_of {X : AlgebraicGeometry.Scheme.{u}} (i j : ℕ)
    (x : AlgebraicGeometry.ChowGroupRat X j) :
    DirectSum.component ℚ ℕ (fun d => AlgebraicGeometry.ChowGroupRat X d) i
        (DirectSum.of _ j x) = if h : j = i then Eq.recOn h x else 0 := by
  rw [← DirectSum.lof_eq_of ℚ ℕ (fun d => AlgebraicGeometry.ChowGroupRat X d) j x]
  exact DirectSum.component.of (R := ℚ) i j x

private theorem component_zero_toEnd_toEnd {X : AlgebraicGeometry.Scheme.{u}}
    (D E : AlgebraicGeometry.RatDivisorOp X) (z : AlgebraicGeometry.ChowRat X) :
    DirectSum.component ℚ ℕ (fun j => AlgebraicGeometry.ChowGroupRat X j) 0
        (AlgebraicGeometry.RatDivisorOp.toEnd D
          (AlgebraicGeometry.RatDivisorOp.toEnd E z)) =
      D 0 (E 1 (DirectSum.component ℚ ℕ
        (fun j => AlgebraicGeometry.ChowGroupRat X j) 2 z)) := by
  refine DirectSum.induction_on z ?_ ?_ ?_
  · simp
  · intro j x
    rcases j with _ | _ | j
    · rw [AlgebraicGeometry.RatDivisorOp.toEnd_of_zero,
        map_zero]
      simp [component_of]
    · rw [AlgebraicGeometry.RatDivisorOp.toEnd_of,
        AlgebraicGeometry.RatDivisorOp.toEnd_of_zero]
      simp [component_of]
    · rcases j with _ | j
      · rw [AlgebraicGeometry.RatDivisorOp.toEnd_of,
          AlgebraicGeometry.RatDivisorOp.toEnd_of]
        simp [component_of]
      · rw [AlgebraicGeometry.RatDivisorOp.toEnd_of,
          AlgebraicGeometry.RatDivisorOp.toEnd_of]
        simp [component_of]
  · intro x y hx hy
    simpa only [map_add] using congrArg₂ (· + ·) hx hy

private theorem of_congr_local {X : AlgebraicGeometry.Scheme.{u}} {p q : ℕ}
    (h : p = q) (α : AlgebraicGeometry.ChowGroupRat X p) :
    DirectSum.of _ p α = DirectSum.of _ q
      (AlgebraicGeometry.ChowGroupRat.congr X h α) := by
  cases h
  rfl

private theorem of_cast_local {X : AlgebraicGeometry.Scheme.{u}} {p q : ℕ}
    (h : p = q) (α : AlgebraicGeometry.ChowGroupRat X p) :
    DirectSum.of _ q (h ▸ α) = DirectSum.of _ p α := by
  cases h
  rfl

private theorem sum_fin_succ_eq_sum_Icc_local {M : Type*} [AddCommMonoid M]
    (f : ℕ → M) (r : ℕ) :
    ∑ q : Fin r, f ((q : ℕ) + 1) = ∑ q ∈ Finset.Icc 1 r, f q := by
  rw [Finset.sum_fin_eq_sum_range]
  rw [← Finset.Ico_add_one_right_eq_Icc 1 r]
  rw [Finset.sum_Ico_eq_sum_range]
  apply Finset.sum_congr rfl
  intro x hx
  simp only [Finset.mem_range] at hx
  rw [dif_pos hx]
  simp [Nat.add_comm]

private theorem probe_cross {K : Type u} [Field K] [IsAlgClosed K]
    {C : SmoothProjectiveCurve K} {n kk : ℕ}
    (E : AlgebraicGeometry.VectorBundle C.toVariety) (F : SubbundleFiltration E (n + 1))
    (m : ℕ) (hm : 0 < m) (i j : Fin (n + 1) × Fin kk)
    [AlgebraicGeometry.IsProper (splitWeightedProjectivization F kk).hom]
    (hY : letI : (splitWeightedProjectivization F kk).left.Over (AlgebraicGeometry.Spec (CommRingCat.of K)) :=
        ⟨(splitWeightedProjectivization F kk).hom ≫
          (C.toScheme ↘ AlgebraicGeometry.Spec (CommRingCat.of K))⟩;
      IsProperOver K (splitWeightedProjectivization F kk).left)
    (β : AlgebraicGeometry.ChowGroupRat (splitWeightedProjectivization F kk).left 2) :
    letI : (splitWeightedProjectivization F kk).left.Over
        (AlgebraicGeometry.Spec (CommRingCat.of K)) :=
      ⟨(splitWeightedProjectivization F kk).hom ≫
        (C.toScheme ↘ AlgebraicGeometry.Spec (CommRingCat.of K))⟩;
    let Li := (AlgebraicGeometry.Scheme.Modules.pullback
      (splitWeightedProjectivization F kk).hom).obj (F.lineQuotient i.1).toModules
    let Lj := (AlgebraicGeometry.Scheme.Modules.pullback
      (splitWeightedProjectivization F kk).hom).obj (F.lineQuotient j.1).toModules
    AlgebraicGeometry.ChowGroupRat.degree (splitWeightedProjectivization F kk).left hY
      ((AlgebraicGeometry.ratDivisorOpOfLineBundle Li) 0
        ((AlgebraicGeometry.ratDivisorOpOfLineBundle Lj) 1 β)) = 0 := by
  letI : (splitWeightedProjectivization F kk).left.Over
      (AlgebraicGeometry.Spec (CommRingCat.of K)) :=
    ⟨(splitWeightedProjectivization F kk).hom ≫
      (C.toScheme ↘ AlgebraicGeometry.Spec (CommRingCat.of K))⟩
  have hC : IsProperOver K C.carrier := by
    change AlgebraicGeometry.IsProper
      (C.carrier ↘ AlgebraicGeometry.Spec (CommRingCat.of K))
    exact IsProjectiveOver.isProper C.projective
  letI : ((splitWeightedProjectivization F kk).hom).IsOver
      (AlgebraicGeometry.Spec (CommRingCat.of K)) := ⟨rfl⟩
  dsimp
  exact pullback_divisor_mul_cap_degree_eq_zero hY hC
    (splitWeightedProjectivization F kk).hom
    (F.lineQuotient i.1).toModules (F.lineQuotient j.1).toModules β
theorem expand_weighted_relation {K : Type u} [Field K] [IsAlgClosed K]
    {C : SmoothProjectiveCurve K} {n kk : ℕ} (hkk : 1 ≤ kk)
    (E : AlgebraicGeometry.VectorBundle C.toVariety) (hE : E.rank = n + 1) (d : ℤ) (hd : VectorBundle.degree E = d)
    (F : SubbundleFiltration E (n + 1)) (m : ℕ) (hm : 0 < m)
    (hdiv : ∀ q ∈ Finset.Icc 1 kk, q ∣ m)
    [AlgebraicGeometry.IsIntegral (splitWeightedProjectivization F kk).left]
    [AlgebraicGeometry.IsProper (splitWeightedProjectivization F kk).hom]
    [SheafOfModules.IsLineBundle
      (AlgebraicGeometry.Scheme.relativeProj.twist (splitWeightedAlgebraOf F kk) (m : ℤ))]
    (hdim : (splitWeightedProjectivization F kk).left.dimension = (n + 1) * kk)
    (hY : letI : (splitWeightedProjectivization F kk).left.Over (AlgebraicGeometry.Spec (CommRingCat.of K)) :=
        ⟨(splitWeightedProjectivization F kk).hom ≫ (C.toScheme ↘ AlgebraicGeometry.Spec (CommRingCat.of K))⟩;
      IsProperOver K (splitWeightedProjectivization F kk).left)
    (c : C.carrier) (hc : IsClosed {c})
    (h₁ : letI := (splitWeightedProjectivization F kk).hom.fiberOverSpecResidueField c;
      IsProperOver (C.carrier.residueField c) ((splitWeightedProjectivization F kk).hom.fiber c)) :
    letI : (splitWeightedProjectivization F kk).left.Over (AlgebraicGeometry.Spec (CommRingCat.of K)) :=
      ⟨(splitWeightedProjectivization F kk).hom ≫ (C.toScheme ↘ AlgebraicGeometry.Spec (CommRingCat.of K))⟩;
    AlgebraicGeometry.RatDivisorOp.topSelfIntersection
        (splitWeightedProjectivization F kk).left hY
        (ratDivisorOpOfCycleClass (splitTautologicalClass F kk m hm)) ((n + 1) * kk) hdim
      = - ((AlgebraicGeometry.relativePolarizationFiberDegree (splitWeightedProjectivization F kk).hom
            (AlgebraicGeometry.Scheme.relativeProj.twist
              (splitWeightedAlgebraOf F kk) (m : ℤ)) c h₁ : ℚ)
          / (m : ℚ) ^ ((n + 1) * kk - 1))
          * (d : ℚ) * ∑ q ∈ Finset.Icc 1 kk, (1 : ℚ) / (q : ℚ) := by
  let Y := (splitWeightedProjectivization F kk).left
  let π := (splitWeightedProjectivization F kk).hom
  let s := (n + 1) * kk
  let ι := Fin (n + 1) × Fin kk
  let H : AlgebraicGeometry.RatDivisorOp Y :=
    ratDivisorOpOfCycleClass (splitTautologicalClass F kk m hm)
  let B : ι → AlgebraicGeometry.RatDivisorOp Y := fun p ↦
    (((p.2 : ℕ) + 1 : ℚ))⁻¹ • AlgebraicGeometry.ratDivisorOpOfLineBundle
      ((AlgebraicGeometry.Scheme.Modules.pullback π).obj
        (F.lineQuotient p.1).toModules)
  let D : ι → AlgebraicGeometry.RatDivisorOp Y := fun p ↦ H + B p
  let HE := AlgebraicGeometry.RatDivisorOp.toEnd H
  let BE : ι → Module.End ℚ (AlgebraicGeometry.ChowRat Y) := fun p ↦
    AlgebraicGeometry.RatDivisorOp.toEnd (B p)
  let DE : ι → Module.End ℚ (AlgebraicGeometry.ChowRat Y) := fun p ↦
    AlgebraicGeometry.RatDivisorOp.toEnd (D p)
  letI : Y.Over (AlgebraicGeometry.Spec (CommRingCat.of K)) :=
    ⟨π ≫ (C.toScheme ↘ AlgebraicGeometry.Spec (CommRingCat.of K))⟩
  letI : AlgebraicGeometry.IsProper
      (Y ↘ AlgebraicGeometry.Spec (CommRingCat.of K)) := hY
  letI : AlgebraicGeometry.LocallyOfFiniteType
      (Y ↘ AlgebraicGeometry.Spec (CommRingCat.of K)) :=
    AlgebraicGeometry.IsProper.toLocallyOfFiniteType
  let hdimY : Y.dimension = s := by simpa [Y, s] using hdim
  let O := AlgebraicGeometry.Scheme.relativeProj.twist
    (splitWeightedAlgebraOf F kk) (m : ℤ)
  have hH : H = (m : ℚ)⁻¹ •
      AlgebraicGeometry.ratDivisorOpOfLineBundle O := by
    funext e
    dsimp [H, ratDivisorOpOfCycleClass]
    rw [splitTautologicalClass_eq_of_dvd F kk m hm hdiv (e + 1)]
    rfl
  have hHE : HE = (m : ℚ)⁻¹ • AlgebraicGeometry.RatDivisorOp.toEnd
      (AlgebraicGeometry.ratDivisorOpOfLineBundle O) := by
    dsimp [HE]
    rw [hH]
    exact AlgebraicGeometry.RatDivisorOp.toEnd.map_smul _ _
  have hBE (p : ι) : BE p = (((p.2 : ℕ) + 1 : ℚ))⁻¹ •
      AlgebraicGeometry.RatDivisorOp.toEnd
        (AlgebraicGeometry.ratDivisorOpOfLineBundle
          ((AlgebraicGeometry.Scheme.Modules.pullback π).obj
            (F.lineQuotient p.1).toModules)) := by
    dsimp [BE, B]
    exact AlgebraicGeometry.RatDivisorOp.toEnd.map_smul _ _
  have hHB (p : ι) : Commute HE (BE p) := by
    rw [hHE, hBE]
    exact ((lineBundle_toEnd_comm (K := K) O
      ((AlgebraicGeometry.Scheme.Modules.pullback π).obj
        (F.lineQuotient p.1).toModules)).smul_left _).smul_right _
  have hBB (p q : ι) : Commute (BE p) (BE q) := by
    rw [hBE, hBE]
    exact ((lineBundle_toEnd_comm (K := K)
      ((AlgebraicGeometry.Scheme.Modules.pullback π).obj
        (F.lineQuotient p.1).toModules)
      ((AlgebraicGeometry.Scheme.Modules.pullback π).obj
        (F.lineQuotient q.1).toModules)).smul_left _).smul_right _
  have hcomm : ∀ p q : ι, Commute (DE p) (DE q) := by
    intro p q
    dsimp [DE, D]
    rw [AlgebraicGeometry.RatDivisorOp.toEnd.map_add,
      AlgebraicGeometry.RatDivisorOp.toEnd.map_add]
    simpa [one_smul, HE, BE] using
      commute_add_smul HE (BE p) (BE q) 1 1 (hHB p) (hHB q) (hBB p q)
  let R := Algebra.adjoin ℚ ({HE} ∪ Set.range BE)
  have hmul : IsMulCommutative R := Algebra.isMulCommutative_adjoin ℚ (by
    rintro x hx y hy
    rcases hx with hx | ⟨p, rfl⟩
    · have : x = HE := by simpa using hx
      subst x
      rcases hy with hy | ⟨q, rfl⟩
      · have : y = HE := by simpa using hy
        subst y
        rfl
      · exact (hHB q).eq
    · rcases hy with hy | ⟨q, rfl⟩
      · have : y = HE := by simpa using hy
        subst y
        exact (hHB p).eq.symm
      · exact (hBB p q).eq)
  letI : CommRing R := { (inferInstance : Ring R) with
    mul_comm := hmul.is_comm.comm }
  let dR : ι → R := fun p => ⟨BE p, Algebra.subset_adjoin (Set.mem_union_right _ (Set.mem_range_self p))⟩
  let α : AlgebraicGeometry.ChowGroupRat Y s :=
    AlgebraicGeometry.fundamentalClassRat Y s hdimY
  let φlin : Module.End ℚ (AlgebraicGeometry.ChowRat Y) →ₗ[ℚ] ℚ :=
    (AlgebraicGeometry.ChowGroupRat.degree Y hY).comp
      ((DirectSum.component ℚ ℕ (fun j => AlgebraicGeometry.ChowGroupRat Y j) 0).comp
        (LinearMap.applyₗ (DirectSum.of _ s α)))
  let φ : R →+ ℚ := φlin.toAddMonoidHom.comp R.val.toRingHom.toAddMonoidHom
  have hcross_end (p q : ι) (y : Module.End ℚ (AlgebraicGeometry.ChowRat Y)) :
      AlgebraicGeometry.ChowGroupRat.degree Y hY
          (DirectSum.component ℚ ℕ (fun j => AlgebraicGeometry.ChowGroupRat Y j) 0
            ((BE p * BE q * y) (DirectSum.of _ s α))) = 0 := by
    change AlgebraicGeometry.ChowGroupRat.degree Y hY
      (DirectSum.component ℚ ℕ (fun j => AlgebraicGeometry.ChowGroupRat Y j) 0
        (BE p (BE q (y (DirectSum.of _ s α))))) = 0
    rw [hBE p, hBE q]
    simp only [LinearMap.smul_apply, Module.End.mul_apply]
    simp only [map_smul]
    rw [component_zero_toEnd_toEnd]
    let β : AlgebraicGeometry.ChowGroupRat Y 2 :=
      DirectSum.component ℚ ℕ (fun j => AlgebraicGeometry.ChowGroupRat Y j) 2
        (y (DirectSum.of _ s α))
    have hz := probe_cross (K := K) E F m hm p q hY β
    have hz' :
        AlgebraicGeometry.ChowGroupRat.degree Y hY
          ((AlgebraicGeometry.ratDivisorOpOfLineBundle
            ((AlgebraicGeometry.Scheme.Modules.pullback π).obj
              (F.lineQuotient p.1).toModules) 0)
            ((AlgebraicGeometry.ratDivisorOpOfLineBundle
              ((AlgebraicGeometry.Scheme.Modules.pullback π).obj
                (F.lineQuotient q.1).toModules) 1) β)) = 0 := hz
    rw [hz']
    simp
  have hcross : ∀ p ∈ (Finset.univ : Finset ι), ∀ q ∈ (Finset.univ : Finset ι),
      p ≠ q → ∀ y : R, φ (dR p * dR q * y) = 0 := by
    intro p hp q hq hpq y
    change φlin ((dR p * dR q * y : R) : Module.End ℚ (AlgebraicGeometry.ChowRat Y)) = 0
    change AlgebraicGeometry.ChowGroupRat.degree Y hY
      (DirectSum.component ℚ ℕ (fun j => AlgebraicGeometry.ChowGroupRat Y j) 0
        (((BE p * BE q) * (y : Module.End ℚ (AlgebraicGeometry.ChowRat Y)))
          (DirectSum.of _ s α))) = 0
    exact hcross_end p q (y : Module.End ℚ (AlgebraicGeometry.ChowRat Y))
  let hR : R := ⟨HE, Algebra.subset_adjoin (Set.mem_union_left _ (Set.mem_singleton _))⟩
  have hDsum : ∀ p : ι, ((hR + dR p : R) : Module.End ℚ (AlgebraicGeometry.ChowRat Y)) = DE p := by
    intro p
    change HE + BE p = DE p
    dsimp [DE, D]
    rw [AlgebraicGeometry.RatDivisorOp.toEnd.map_add]
  have hcommD : (Set.univ : Set ι).Pairwise (fun p q => Commute (DE p) (DE q)) := by
    intro p _ q _ hpq
    exact hcomm p q
  have hprodmap :
      ((∏ p : ι, (hR + dR p) : R) : Module.End ℚ (AlgebraicGeometry.ChowRat Y)) =
        Finset.univ.noncommProd DE (hcommD.mono (by simp)) := by
    let g : R →* Module.End ℚ (AlgebraicGeometry.ChowRat Y) := R.val.toRingHom.toMonoidHom
    have hm := Finset.map_noncommProd (s := (Finset.univ : Finset ι))
      (f := fun p : ι => hR + dR p)
      (comm := fun _ _ _ _ _ => Commute.all _ _)
      (g := g)
    rw [Finset.noncommProd_eq_prod] at hm
    have hfun : (fun p : ι => g (hR + dR p)) = DE := by
      funext p
      exact hDsum p
    change g (∏ p : ι, (hR + dR p)) =
      Finset.univ.noncommProd DE (hcommD.mono (by simp))
    simpa only [hfun] using hm
  have hprodzero : φ (∏ p : ι, (hR + dR p)) = 0 := by
    have hcard : s = Fintype.card ι := by simp [s, ι]
    change AlgebraicGeometry.ChowGroupRat.degree Y hY
      (DirectSum.component ℚ ℕ (fun j => AlgebraicGeometry.ChowGroupRat Y j) 0
        (((∏ p : ι, (hR + dR p) : R) : Module.End ℚ (AlgebraicGeometry.ChowRat Y))
          (DirectSum.of _ s α))) = 0
    rw [hprodmap]
    have hcap :
        DirectSum.of _ 0 (AlgebraicGeometry.RatDivisorOp.capProd D 0
          (AlgebraicGeometry.ChowGroupRat.congr Y (by rw [hcard]; simp) α)) =
          (Finset.univ.noncommProd (fun p => DE p) (hcommD.mono (by simp)))
            (DirectSum.of _ (0 + Fintype.card ι)
              (AlgebraicGeometry.ChowGroupRat.congr Y (by rw [hcard]; simp) α)) := by
      exact AlgebraicGeometry.RatDivisorOp.capProd_eq_noncommProd_toEnd
        D hcommD 0
          (AlgebraicGeometry.ChowGroupRat.congr Y (by rw [hcard]; simp) α)
    have hrel := weighted_relation hkk F m hm hdiv
      (hdim := hdim)
    have hα0 :
        DirectSum.of _ (0 + Fintype.card ι)
            (AlgebraicGeometry.ChowGroupRat.congr Y (by rw [hcard]; simp) α) =
          DirectSum.of _ s α := by
      exact (of_congr_local (X := Y)
        (hcard.trans (Nat.zero_add _).symm) α).symm
    have hzero : AlgebraicGeometry.RatDivisorOp.capProd D 0
        (AlgebraicGeometry.ChowGroupRat.congr Y (by rw [hcard]; simp) α) = 0 := by
      simpa [D, H, B, Y, π, ι, hcard, α] using hrel
    rw [hzero] at hcap
    have hprodzero' :
        (Finset.univ.noncommProd (fun p => DE p) (hcommD.mono (by simp)))
            (DirectSum.of _ s α) = 0 := by
      rw [← hα0]
      simpa using hcap.symm
    rw [hprodzero']
    simp
  have hι : (Finset.univ : Finset ι).Nonempty := by
    let x : ι := (⟨0, by omega⟩, ⟨0, by omega⟩)
    exact ⟨x, Finset.mem_univ _⟩
  have hexpand := Finset.map_prod_add_of_map_mul_mul_eq_zero
    (s := (Finset.univ : Finset ι)) hι φ hR dR hcross
  have hpowH : φ (hR ^ s) =
      AlgebraicGeometry.RatDivisorOp.topSelfIntersection Y hY H s
        hdimY := by
    change AlgebraicGeometry.ChowGroupRat.degree Y hY
      (DirectSum.component ℚ ℕ (fun j => AlgebraicGeometry.ChowGroupRat Y j) 0
        (((hR ^ s : R) : Module.End ℚ (AlgebraicGeometry.ChowRat Y))
          (DirectSum.of _ s α))) = _
    change AlgebraicGeometry.ChowGroupRat.degree Y hY
      (DirectSum.component ℚ ℕ (fun j => AlgebraicGeometry.ChowGroupRat Y j) 0
        ((HE ^ s) (DirectSum.of _ s α))) = _
    let α0 : AlgebraicGeometry.ChowGroupRat Y (0 + s) := (zero_add s).symm ▸ α
    have hcapH := AlgebraicGeometry.RatDivisorOp.capPow_eq_pow_toEnd H s 0 α0
    have hcapH' := congrArg
      (fun z : AlgebraicGeometry.ChowRat Y =>
        AlgebraicGeometry.ChowGroupRat.degree Y hY
          (DirectSum.component ℚ ℕ (fun j => AlgebraicGeometry.ChowGroupRat Y j) 0 z)) hcapH
    have hin :
        DirectSum.of _ (0 + s) ((zero_add s).symm ▸ α) =
          DirectSum.of _ s α := by
      exact of_cast_local (X := Y) (Nat.zero_add s).symm α
    rw [hin] at hcapH'
    have hcomponent :
        DirectSum.component ℚ ℕ (fun j => AlgebraicGeometry.ChowGroupRat Y j) 0
            (DirectSum.of _ 0 (H.capPow s 0 α0)) = H.capPow s 0 α0 := by
      simp [component_of]
    rw [hcomponent] at hcapH'
    simpa [HE, α0, AlgebraicGeometry.RatDivisorOp.topSelfIntersection] using hcapH'.symm
  have hterm (p : ι) :
      φ (hR ^ (s - 1) * dR p) =
        (((p.2 : ℕ) + 1 : ℚ)⁻¹) *
          ((AlgebraicGeometry.relativePolarizationFiberDegree π O c h₁ : ℚ) /
          (m : ℚ) ^ (s - 1)) *
          (LineBundle.degree (F.lineQuotient p.1) : ℚ) := by
    change AlgebraicGeometry.ChowGroupRat.degree Y hY
      (DirectSum.component ℚ ℕ (fun j => AlgebraicGeometry.ChowGroupRat Y j) 0
        (((HE ^ (s - 1) * BE p)) (DirectSum.of _ s α))) = _
    have hp := (hHB p).pow_left (s - 1)
    rw [hp.eq]
    rw [hBE p]
    simp only [LinearMap.smul_apply, Module.End.mul_apply, map_smul]
    have hspos : 1 ≤ s := by
      dsimp [s]
      exact Nat.one_le_iff_ne_zero.mpr
        (Nat.mul_ne_zero (Nat.succ_ne_zero n) (by omega))
    let α1 : AlgebraicGeometry.ChowGroupRat Y (1 + (s - 1)) :=
      AlgebraicGeometry.ChowGroupRat.congr Y (by omega) α
    have hin1 :
        DirectSum.of _ (1 + (s - 1)) α1 = DirectSum.of _ s α := by
      exact (of_congr_local (X := Y) (by omega) α).symm
    rw [← hin1]
    have hpow := AlgebraicGeometry.RatDivisorOp.capPow_eq_pow_toEnd H (s - 1) 1 α1
    rw [← hpow]
    rw [AlgebraicGeometry.RatDivisorOp.toEnd_of]
    rw [component_of]
    simp only [dif_pos trivial]
    have hdeg := degree_taut_pow_cap_pullback hkk F m hm hdiv hdim hY p.1 c hc h₁
    rw [hdeg]
    dsimp [s]
    ring
  have hsumzero :
      φ (hR ^ s) + ∑ p : ι, φ (hR ^ (s - 1) * dR p) = 0 := by
    have hexpand' :
        φ (∏ p : ι, (hR + dR p)) =
          φ (hR ^ s) + ∑ p : ι, φ (hR ^ (s - 1) * dR p) := by
      simpa [ι, s] using hexpand
    rw [← hexpand']
    exact hprodzero
  have hsumterm :
      ∑ p : ι, φ (hR ^ (s - 1) * dR p) =
        ((AlgebraicGeometry.relativePolarizationFiberDegree π O c h₁ : ℚ) /
          (m : ℚ) ^ (s - 1)) *
          ∑ i : Fin (n + 1), ∑ q : Fin kk,
            (((q : ℕ) + 1 : ℚ)⁻¹) * (LineBundle.degree (F.lineQuotient i) : ℚ) := by
    calc
      ∑ p : ι, φ (hR ^ (s - 1) * dR p) =
          ∑ p : ι, (((p.2 : ℕ) + 1 : ℚ)⁻¹) *
            ((AlgebraicGeometry.relativePolarizationFiberDegree π O c h₁ : ℚ) /
              (m : ℚ) ^ (s - 1)) *
            (LineBundle.degree (F.lineQuotient p.1) : ℚ) := by
        apply Finset.sum_congr rfl
        intro p hp
        exact hterm p
      _ = ((AlgebraicGeometry.relativePolarizationFiberDegree π O c h₁ : ℚ) /
          (m : ℚ) ^ (s - 1)) *
          ∑ i : Fin (n + 1), ∑ q : Fin kk,
            (((q : ℕ) + 1 : ℚ)⁻¹) * (LineBundle.degree (F.lineQuotient i) : ℚ) := by
        rw [show (Finset.univ : Finset ι) =
          (Finset.univ : Finset (Fin (n + 1))) ×ˢ (Finset.univ : Finset (Fin kk)) by
            simp [ι]]
        rw [Finset.sum_product]
        simp only [Prod.fst, Prod.snd]
        have hfactor (i : Fin (n + 1)) :
            (∑ q : Fin kk, (((q : ℕ) + 1 : ℚ)⁻¹) *
              ((AlgebraicGeometry.relativePolarizationFiberDegree π O c h₁ : ℚ) /
                (m : ℚ) ^ (s - 1)) *
              (LineBundle.degree (F.lineQuotient i) : ℚ)) =
              ((AlgebraicGeometry.relativePolarizationFiberDegree π O c h₁ : ℚ) /
                (m : ℚ) ^ (s - 1)) *
                ∑ q : Fin kk, (((q : ℕ) + 1 : ℚ)⁻¹) *
                  (LineBundle.degree (F.lineQuotient i) : ℚ) := by
          rw [Finset.mul_sum]
          apply Finset.sum_congr rfl
          intro q hq
          ring
        rw [show (∑ i : Fin (n + 1), ∑ q : Fin kk, _ ) =
            ∑ i : Fin (n + 1),
              ((AlgebraicGeometry.relativePolarizationFiberDegree π O c h₁ : ℚ) /
                (m : ℚ) ^ (s - 1)) *
                ∑ q : Fin kk, (((q : ℕ) + 1 : ℚ)⁻¹) *
                  (LineBundle.degree (F.lineQuotient i) : ℚ) by
          apply Finset.sum_congr rfl
          intro i hi
          exact hfactor i]
        rw [Finset.mul_sum]
  have hdouble :
      ∑ i : Fin (n + 1), ∑ q : Fin kk,
          (((q : ℕ) + 1 : ℚ)⁻¹) * (LineBundle.degree (F.lineQuotient i) : ℚ) =
        ∑ i : Fin (n + 1), ∑ q ∈ Finset.Icc 1 kk,
          (LineBundle.degree (F.lineQuotient i) : ℚ) / (q : ℚ) := by
    apply Finset.sum_congr rfl
    intro i hi
    have hqsum := sum_fin_succ_eq_sum_Icc_local
      (f := fun q => (q : ℚ)⁻¹ * (LineBundle.degree (F.lineQuotient i) : ℚ)) kk
    simpa [Nat.cast_add, Nat.cast_one, div_eq_mul_inv, mul_comm] using hqsum
  have hdouble' := sum_sum_div_eq_sum_mul_harmonic
    (s := (Finset.univ : Finset (Fin (n + 1))))
    (e := fun i => LineBundle.degree (F.lineQuotient i)) kk
  have hdegreeF :
      VectorBundle.degree E = ∑ i : Fin (n + 1), LineBundle.degree (F.lineQuotient i) :=
    by
      let E' : AlgebraicGeometry.VectorBundle C.toVariety :=
        { toModules := E.toModules
          rank := n + 1
          locallyFree := E.locallyFree
          isFiniteType := E.isFiniteType
          rankAtStalk_eq := fun x => (E.rankAtStalk_eq x).trans hE }
      let hF' : SubbundleFiltration E' (n + 1) :=
        { sub := F.sub
          incl := F.incl
          mono := F.mono
          rank_eq := F.rank_eq
          lastIso := F.lastIso
          lineQuotient := F.lineQuotient
          quotient_iso := F.quotient_iso }
      have hsum := degree_eq_sum_lineQuotient_degrees E' hF'
      have hdeg : VectorBundle.degree E' = VectorBundle.degree E := by
        rw [VectorBundle.degree_eq_lineBundle_degree_det, VectorBundle.degree_eq_lineBundle_degree_det]
        apply LineBundle.degree_congr
        dsimp only [AlgebraicGeometry.VectorBundle.det]
        exact eqToIso (congrArg (AlgebraicGeometry.Scheme.Modules.moduleExteriorPower C.toScheme E.toModules) hE.symm)
      rw [hdeg] at hsum
      simpa [hF'] using hsum
  have hfinal :
      AlgebraicGeometry.RatDivisorOp.topSelfIntersection Y hY H s hdimY =
        - ((AlgebraicGeometry.relativePolarizationFiberDegree π O c h₁ : ℚ) /
          (m : ℚ) ^ (s - 1)) * (d : ℚ) *
          ∑ q ∈ Finset.Icc 1 kk, (1 : ℚ) / (q : ℚ) := by
    rw [← hpowH]
    rw [hsumterm, hdouble, hdouble'] at hsumzero
    have hdegree' :
        (∑ i : Fin (n + 1), (LineBundle.degree (F.lineQuotient i) : ℚ)) = (d : ℚ) := by
      exact_mod_cast hdegreeF.symm.trans hd
    rw [hdegree'] at hsumzero
    linarith
  exact hfinal

end
