import MiyaokaMori.Prelude
import MiyaokaMori.Paper.S2WeightedJets.Intersection.CoordinatePowerSection
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.WeightedSymSectionsRingEquivSym
import MiyaokaMori.AlgebraicGeometry.Modules.DualMapAdditiveBiproduct
import MiyaokaMori.RingTheory.WeightedSymGenIdeal
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.RelativeProjEvaluationGermNotMem
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.Stacks01nqPointRestrict
import MiyaokaMori.AlgebraicGeometry.Modules.Dual.DualFrameOldSections
import MiyaokaMori.AlgebraicGeometry.Modules.TensorFrameGermCriterion
import MiyaokaMori.AlgebraicGeometry.Modules.FramePowIsFrame
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.TwistPullbackPowLocal
import MiyaokaMori.Paper.S2WeightedJets.Intersection.SplitCoordPowMultiplicative
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.CoordinateSectionResOnFrame

/-! # Local generators of the split weighted algebra

Local generators of the split weighted algebra `S^sp = splitWeightedAlgebraOf F kk` on an affine open `V ⊆ C`, and
the two facts behind "the coordinates cannot all vanish at a point of `Y^sp`" (proof of Proposition 2.4 of the paper: all coordinates cannot vanish at a projective point):

* `splitCoordIncl F i q hq : Q_i^∨ ⟶ S^sp_q` — the copy of `Q_i^∨` sitting in the weight-`q` generator piece
  (the same composite `dualMap (biproduct.π i) ≫ genIncl ≫ eqToHom` that `splitWeightedCoord` uses);
* `splitCoordGen F V p φ ∈ A(V)_q` — the image of a section `φ ∈ Γ(V, Q_i^∨)` in the section ring
  `A(V) = ⊕_m Γ(V, S^sp_m)` (`GradedQCAlgebra.sectionsRing`), `p = (i, q-1)`;
* `splitWeightedAlgebra_irrelevant_le_span_splitCoordGen`: for affine `V` the irrelevant ideal of `A(V)` is
  contained in the ideal generated by all `splitCoordGen F V p φ` ("the coordinates generate the algebra over
  `A_0`"). Route: `A(V)` is the image of the algebraic weighted symmetric algebra under `symLiftHom` (surjective on
  affine `V`); positive-weight pieces of the latter lie in the ideal of its generators (`WeightedSym.piece_le_genIdeal`);
  a generator `genSections q w` is the sum over `j` of `splitCoordGen F V (j, q) ((π_j)^∨ w)` because a section of
  `(⊕_j Q_j)^∨` is the sum of its components (`eq_sum_dualMap_π_app`) and `splitCoordIncl = (π_j)^∨ ≫ genIncl`
  (`splitCoordIncl_eq`);
* `mem_nonvanishingLocus_coordPowSection_of_splitCoordGen_not_mem`: if `y ∈ π⁻¹V` and the generator
  `splitCoordGen F V p φ` is not in the homogeneous prime of `φ_V(y) ∈ Proj A(V)` (`φ_V = relativeProj.affineIso`,
  Stacks 01NQ), then the coordinate power `σ_p = x_p^{m/q}` does not vanish at `y` ("`D_+(x_p)` is the
  nonvanishing locus of `σ_p`"). Route: shrink to an affine `W ≤ V`, `π y ∈ W`, with a frame `ε` of `Q_i`
  (`exists_affine_frame_le`); transport the prime along `A(V) → A(W)` (`sectionsRestrict_notMem_affineIso_of_notMem`,
  Stacks 01NQ on points) and the generator along restriction (`splitCoordGen_res`); `φ|_W = a • ε^∨`
  (`IsFrame.exists_eq_smul_dualFrameOld`) so `c_p(φ)|_W = a · c₀` (`splitCoordGen_smul`), `c₀ := c_p(ε^∨) ∉ 𝔭`,
  `c₀^k ∉ 𝔭` (prime), `c₀^k = of m w` for a section `w ∈ Γ(W, S^sp_m)` (`SetLike.pow_mem_graded`); the germ of
  `w/1 = evaluationLocal S m W w` at `y` is not in `𝔪_y O(m)_y` (`germ_evaluationLocal_notMem_maximalIdeal_smul`,
  Stacks 01MW(5)); finally `coordPowSection_germ_mem_of_frame`: on `π⁻¹W`, `σ_p = (c₀^k/1) ⊗ π^*ε^{⊗k}` with the
  second factor a frame, so `σ_p` vanishes at `y` only where `c₀^k/1` does. Its pieces: the germ criterion for a
  tensor with a frame, `coordPowSection_res_eq_moduleTensorSection_of_frame` (assembled from the local form of the
  coordinate `splitWeightedCoord_res_eq_moduleTensorSection_of_frame`, the power computation for
  `twistPullbackPow`, the bridge `splitTwistMul_eq_twistPullbackPow` and frames of tensor powers).

The assembly (`exists_mem_nonvanishingLocus_coordPowSection`, `splitWeightedCoord_not_all_vanish`) is in
`CoordinatesNotAllVanish`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- `ι_{i,q} : Q_i^∨ ⟶ S^sp_q`: the dual of the `i`-th projection `⊕_j Q_j → Q_i` (`Modules.dualMap`) followed by
the inclusion of the weight-`q` generator piece `(⊕_j Q_j)^∨ → S^sp_q` (`weightedSymAlgebra.genIncl`; the `(q-1)`-th
copy of `(⊕_j Q_j)^∨` has weight `q`). This is literally the `let ι` inside `splitWeightedCoord`. -/
noncomputable def splitCoordIncl {K : Type u} [Field K] {C : SmoothProjectiveCurve K}
    {n kk : ℕ} {E : AlgebraicGeometry.VectorBundle C.toVariety} (F : SubbundleFiltration E (n + 1))
    (i : Fin (n + 1)) (q : ℕ) (hq : q ∈ Finset.Icc 1 kk) :
    AlgebraicGeometry.Scheme.Modules.dual (F.lineQuotient i).toModules ⟶
      (splitWeightedAlgebraOf F kk).part q :=
  haveI : ∀ j : Fin (n + 1), (F.lineQuotient j).toModules.IsLocallyFree := fun j => (F.lineQuotient j).locallyFree
  haveI : ∀ j : Fin (n + 1), (F.lineQuotient j).toModules.IsFiniteType := fun j => (F.lineQuotient j).isFiniteType
  let S := splitWeightedAlgebraOf F kk
  let V : Fin kk → C.toScheme.Modules := fun _ =>
    CategoryTheory.Limits.biproduct (fun j : Fin (n + 1) => (F.lineQuotient j).toModules)
  have hq' : 1 ≤ q ∧ q ≤ kk := Finset.mem_Icc.mp hq
  let j₀ : Fin kk := ⟨q - 1, by omega⟩
  AlgebraicGeometry.Scheme.Modules.dualMap
      (CategoryTheory.Limits.biproduct.π (fun j : Fin (n + 1) => (F.lineQuotient j).toModules) i) ≫
    AlgebraicGeometry.Scheme.weightedSymAlgebra.genIncl V j₀ ≫
    CategoryTheory.eqToHom (congrArg S.part (by simp only [j₀]; omega))

/-- The local generator `c_p(φ) ∈ A(V)_q`: the image of `φ ∈ Γ(V, Q_i^∨)` under `ι_{i,q}` on sections over `V`,
placed in the weight-`q` homogeneous part of the section ring `A(V) = ⊕_m Γ(V, S^sp_m)`
(`GradedQCAlgebra.sectionsOf`). Here `p = (i, q-1)`, `q = p.2 + 1`.
On a `V` where `Q_i` has a frame `ε`, `c_p(ε^∨)` is the paper's coordinate `x_{i,q}` read in the local polynomial
algebra `O(V)[x_{i,q}]`. -/
noncomputable def splitCoordGen {K : Type u} [Field K] {C : SmoothProjectiveCurve K}
    {n kk : ℕ} {E : AlgebraicGeometry.VectorBundle C.toVariety} (F : SubbundleFiltration E (n + 1))
    (V : C.toScheme.Opens) (p : Fin (n + 1) × Fin kk)
    (φ : Γ(AlgebraicGeometry.Scheme.Modules.dual (F.lineQuotient p.1).toModules, V)) :
    (splitWeightedAlgebraOf F kk).sectionsRing V :=
  ((splitWeightedAlgebraOf F kk).sectionsOf V ((p.2 : ℕ) + 1)
    (((splitCoordIncl F p.1 ((p.2 : ℕ) + 1) (by simp only [Finset.mem_Icc]; omega)).val.app
      (Opposite.op V)).hom φ)).1


/-! ## `S^sp` as a `weightedSymAlgebra`, and the local generators as `genSections`

`splitWeightedAlgebraOf F kk` is by definition `weightedSymAlgebra (fun _ : Fin kk => ⊕_j Q_j)`; the two abbreviations
below only name the families so that instance search finds the biproduct instances. -/

/-- The line quotients `Q_j` as a family of `O_C`-modules. -/
abbrev splitLineQuotientFamily {K : Type u} [Field K] {C : SmoothProjectiveCurve K}
    {n : ℕ} {E : AlgebraicGeometry.VectorBundle C.toVariety} (F : SubbundleFiltration E (n + 1)) :
    Fin (n + 1) → C.toScheme.Modules :=
  fun j => (F.lineQuotient j).toModules

/-- The generator family of `S^sp`: `kk` copies of `⊕_j Q_j` (the `q`-th copy has weight `q`). -/
abbrev splitGenFamily {K : Type u} [Field K] {C : SmoothProjectiveCurve K}
    {n : ℕ} {E : AlgebraicGeometry.VectorBundle C.toVariety} (F : SubbundleFiltration E (n + 1)) (kk : ℕ) :
    Fin kk → C.toScheme.Modules :=
  fun _ => CategoryTheory.Limits.biproduct (splitLineQuotientFamily F)

/-- Moving the index of a generator inclusion along `j₀ = q` (the `eqToHom`s are identities up to the index). -/
theorem AlgebraicGeometry.Scheme.weightedSymAlgebra.genIncl_comp_eqToHom {X : AlgebraicGeometry.Scheme.{u}}
    {r : ℕ} (V : Fin r → X.Modules) [∀ q, (V q).IsLocallyFree] [∀ q, (V q).IsFiniteType]
    {j₀ q : Fin r} (h : j₀ = q)
    (e : (AlgebraicGeometry.Scheme.weightedSymAlgebra V).part ((j₀ : ℕ) + 1) =
      (AlgebraicGeometry.Scheme.weightedSymAlgebra V).part ((q : ℕ) + 1)) :
    AlgebraicGeometry.Scheme.weightedSymAlgebra.genIncl V j₀ ≫ CategoryTheory.eqToHom e =
      CategoryTheory.eqToHom (congrArg (fun j => AlgebraicGeometry.Scheme.Modules.dual (V j)) h) ≫
        AlgebraicGeometry.Scheme.weightedSymAlgebra.genIncl V q := by
  subst h
  rw [CategoryTheory.eqToHom_refl, CategoryTheory.eqToHom_refl, CategoryTheory.Category.comp_id,
    CategoryTheory.Category.id_comp]

/-- `ι_{i,q} = (π_i)^∨ ≫ genIncl_{q-1}` (the `eqToHom` in `splitCoordIncl` is the identity). -/
theorem splitCoordIncl_eq {K : Type u} [Field K] {C : SmoothProjectiveCurve K}
    {n kk : ℕ} {E : AlgebraicGeometry.VectorBundle C.toVariety} (F : SubbundleFiltration E (n + 1))
    (j : Fin (n + 1)) (q : Fin kk) :
    have : ∀ j : Fin (n + 1), (F.lineQuotient j).toModules.IsLocallyFree := fun j => (F.lineQuotient j).locallyFree
    have : ∀ j : Fin (n + 1), (F.lineQuotient j).toModules.IsFiniteType := fun j => (F.lineQuotient j).isFiniteType
    splitCoordIncl F j ((q : ℕ) + 1) (by simp only [Finset.mem_Icc]; omega) =
      AlgebraicGeometry.Scheme.Modules.dualMap
          (CategoryTheory.Limits.biproduct.π (splitLineQuotientFamily F) j) ≫
        AlgebraicGeometry.Scheme.weightedSymAlgebra.genIncl (splitGenFamily F kk) q := by
  have : ∀ j : Fin (n + 1), (F.lineQuotient j).toModules.IsLocallyFree := fun j => (F.lineQuotient j).locallyFree
  have : ∀ j : Fin (n + 1), (F.lineQuotient j).toModules.IsFiniteType := fun j => (F.lineQuotient j).isFiniteType
  unfold splitCoordIncl
  dsimp only
  have hj : (⟨(q : ℕ) + 1 - 1, by omega⟩ : Fin kk) = q := Fin.ext (Nat.add_sub_cancel _ _)
  refine (congrArg (fun g => AlgebraicGeometry.Scheme.Modules.dualMap
      (CategoryTheory.Limits.biproduct.π (splitLineQuotientFamily F) j) ≫ g)
    (AlgebraicGeometry.Scheme.weightedSymAlgebra.genIncl_comp_eqToHom (splitGenFamily F kk) hj _)).trans ?_
  rw [CategoryTheory.eqToHom_refl, CategoryTheory.Category.id_comp]

/-- The local generator `c_p(φ)` is the `genSections` of the component `(π_i)^∨ φ`. -/
theorem splitCoordGen_eq_genSections {K : Type u} [Field K] {C : SmoothProjectiveCurve K}
    {n kk : ℕ} {E : AlgebraicGeometry.VectorBundle C.toVariety} (F : SubbundleFiltration E (n + 1))
    (V : C.toScheme.Opens) (p : Fin (n + 1) × Fin kk)
    (φ : Γ(AlgebraicGeometry.Scheme.Modules.dual (F.lineQuotient p.1).toModules, V)) :
    have : ∀ j : Fin (n + 1), (F.lineQuotient j).toModules.IsLocallyFree := fun j => (F.lineQuotient j).locallyFree
    have : ∀ j : Fin (n + 1), (F.lineQuotient j).toModules.IsFiniteType := fun j => (F.lineQuotient j).isFiniteType
    splitCoordGen F V p φ =
      AlgebraicGeometry.Scheme.weightedSymAlgebra.genSections (splitGenFamily F kk) V p.2
        ((AlgebraicGeometry.Scheme.Modules.dualMap
          (CategoryTheory.Limits.biproduct.π (splitLineQuotientFamily F) p.1)).app V φ) := by
  have : ∀ j : Fin (n + 1), (F.lineQuotient j).toModules.IsLocallyFree := fun j => (F.lineQuotient j).locallyFree
  have : ∀ j : Fin (n + 1), (F.lineQuotient j).toModules.IsFiniteType := fun j => (F.lineQuotient j).isFiniteType
  unfold splitCoordGen
  rw [splitCoordIncl_eq]
  rfl

/-- **The coordinates generate the algebra over `A_0`** (proof of Proposition 2.4 of the paper: locally
`Y^sp` is the Proj of a weighted polynomial algebra whose coordinates generate it over `A_0`). For an affine open
`V ⊆ C`, the irrelevant ideal `A(V)_+ = ⊕_{m ≥ 1} Γ(V, S^sp_m)` of the section ring `A(V)` of
`S^sp = Sym(⊕_{q=1}^{kk} (⊕_j Q_j)^∨)` (weight `q` on the `q`-th copy) is contained in the ideal generated by the local
generators `c_p(φ) = splitCoordGen F V p φ`, `p = (i, q-1)`, `φ ∈ Γ(V, Q_i^∨)`.

Proof sketch. Via `weightedSymAlgebra.exists_sectionsRing_equiv_symmetricAlgebra`
(`A(V) ≃+* Sym_{O(V)}(⊕_q Γ(V, (⊕_j Q_j)^∨))` with `A(V)_m ↔ WeightedSym.piece … m`), the piece of weight `m ≥ 1` of
the algebraic weighted symmetric algebra lies in the ideal generated by the generators `WeightedSym.gen q x`, which
correspond to the `c_p(φ)` (the `(q-1)`-th generator module is `Γ(V, ⊕_j Q_j^∨) = ⊕_j Γ(V, Q_j^∨)`), and the
equivalence carries the ideal they span onto the ideal spanned by the `c_p(φ)`.
For `kk = 0` there are no generators, `S^sp_m = 0` for `m ≥ 1`, and both sides are `⊥`. -/
theorem splitWeightedAlgebra_irrelevant_le_span_splitCoordGen {K : Type u} [Field K]
    {C : SmoothProjectiveCurve K} {n kk : ℕ} {E : AlgebraicGeometry.VectorBundle C.toVariety}
    (F : SubbundleFiltration E (n + 1)) (V : C.toScheme.affineOpens) :
    (HomogeneousIdeal.irrelevant ((splitWeightedAlgebraOf F kk).sectionsGrading V.1)).toIdeal ≤
      Ideal.span (Set.range (fun pφ : Σ p : Fin (n + 1) × Fin kk,
          Γ(AlgebraicGeometry.Scheme.Modules.dual (F.lineQuotient p.1).toModules, V.1) =>
        splitCoordGen F V.1 pφ.1 pφ.2)) := by
  have : ∀ j : Fin (n + 1), (F.lineQuotient j).toModules.IsLocallyFree := fun j => (F.lineQuotient j).locallyFree
  have : ∀ j : Fin (n + 1), (F.lineQuotient j).toModules.IsFiniteType := fun j => (F.lineQuotient j).isFiniteType
  classical
  open AlgebraicGeometry.Scheme.weightedSymAlgebra in
  change (HomogeneousIdeal.irrelevant
      ((AlgebraicGeometry.Scheme.weightedSymAlgebra (splitGenFamily F kk)).sectionsGrading V.1)).toIdeal ≤
    Ideal.span (Set.range (fun pφ : Σ p : Fin (n + 1) × Fin kk,
        Γ(AlgebraicGeometry.Scheme.Modules.dual (F.lineQuotient p.1).toModules, V.1) =>
      splitCoordGen F V.1 pφ.1 pφ.2))
  set I : Ideal ((AlgebraicGeometry.Scheme.weightedSymAlgebra (splitGenFamily F kk)).sectionsRing V.1) :=
    Ideal.span (Set.range (fun pφ : Σ p : Fin (n + 1) × Fin kk,
        Γ(AlgebraicGeometry.Scheme.Modules.dual (F.lineQuotient p.1).toModules, V.1) =>
      splitCoordGen F V.1 pφ.1 pφ.2)) with hI
  -- Step 1: every `genSections q w` lies in `I` (a section of `(⊕_j Q_j)^∨` is the sum of its components).
  have hgen : ∀ (q : Fin kk) (w : Γ(AlgebraicGeometry.Scheme.Modules.dual (splitGenFamily F kk q), V.1)),
      AlgebraicGeometry.Scheme.weightedSymAlgebra.genSections (splitGenFamily F kk) V.1 q w ∈ I := by
    intro q w
    have hw := AlgebraicGeometry.Scheme.Modules.eq_sum_dualMap_π_app (splitLineQuotientFamily F) V.1 w
    have hsum : AlgebraicGeometry.Scheme.weightedSymAlgebra.genSections (splitGenFamily F kk) V.1 q w =
        ∑ j, AlgebraicGeometry.Scheme.weightedSymAlgebra.genSections (splitGenFamily F kk) V.1 q
          ((AlgebraicGeometry.Scheme.Modules.dualMap
              (CategoryTheory.Limits.biproduct.π (splitLineQuotientFamily F) j)).app V.1
            ((AlgebraicGeometry.Scheme.Modules.dualMap
              (CategoryTheory.Limits.biproduct.ι (splitLineQuotientFamily F) j)).app V.1 w)) := by
      conv_lhs => rw [hw]
      exact map_sum (AlgebraicGeometry.Scheme.weightedSymAlgebra.genLinear (splitGenFamily F kk) V.1 q) _ _
    rw [hsum]
    refine Ideal.sum_mem I fun j _ => ?_
    refine Ideal.subset_span ⟨⟨(j, q), (AlgebraicGeometry.Scheme.Modules.dualMap
      (CategoryTheory.Limits.biproduct.ι (splitLineQuotientFamily F) j)).app V.1 w⟩, ?_⟩
    exact splitCoordGen_eq_genSections F V.1 (j, q) _
  -- Step 2: the ideal of generators of `Sym` maps into `I`.
  have hmap : Ideal.map (AlgebraicGeometry.Scheme.weightedSymAlgebra.symLiftHom (splitGenFamily F kk) V.1)
      (WeightedSym.genIdeal Γ(C.toScheme, V.1)
        (AlgebraicGeometry.Scheme.weightedSymAlgebra.genSectionsModule (splitGenFamily F kk) V.1)) ≤ I := by
    rw [WeightedSym.genIdeal, Ideal.map_span]
    refine Ideal.span_le.mpr ?_
    rintro _ ⟨_, ⟨⟨q, w⟩, rfl⟩, rfl⟩
    rw [AlgebraicGeometry.Scheme.weightedSymAlgebra.symLiftHom_gen]
    exact hgen q w
  -- Step 3: an element of the irrelevant ideal is `φ b` with `b_0 = 0`; the other pieces of `b` have positive weight.
  intro a ha
  have ha0 : ((DirectSum.decompose
      ((AlgebraicGeometry.Scheme.weightedSymAlgebra (splitGenFamily F kk)).sectionsGrading V.1) a 0 : _) :
      (AlgebraicGeometry.Scheme.weightedSymAlgebra (splitGenFamily F kk)).sectionsRing V.1) = 0 := ha
  obtain ⟨b, rfl⟩ := (AlgebraicGeometry.Scheme.weightedSymAlgebra.symLiftHom_bijective (splitGenFamily F kk) V.2).2 a
  set ℳ := WeightedSym.piece Γ(C.toScheme, V.1)
    (AlgebraicGeometry.Scheme.weightedSymAlgebra.genSectionsModule (splitGenFamily F kk) V.1)
    (AlgebraicGeometry.Scheme.weightedSymAlgebra.weight (r := kk)) with hℳ
  rw [← DirectSum.sum_support_decompose ℳ b, map_sum]
  refine Ideal.sum_mem I fun k _ => ?_
  by_cases hk : k = 0
  · subst hk
    have h0 : AlgebraicGeometry.Scheme.weightedSymAlgebra.symLiftHom (splitGenFamily F kk) V.1
        (DirectSum.decompose ℳ b 0 : _) = 0 :=
      (AlgebraicGeometry.Scheme.weightedSymAlgebra.decompose_symLiftHom (splitGenFamily F kk) V.1 b 0).symm.trans ha0
    rw [h0]
    exact I.zero_mem
  · have hb : (DirectSum.decompose ℳ b k).1 ∈ WeightedSym.genIdeal Γ(C.toScheme, V.1)
        (AlgebraicGeometry.Scheme.weightedSymAlgebra.genSectionsModule (splitGenFamily F kk) V.1) :=
      (Submodule.restrictScalars_mem _ _ _).mp
        (WeightedSym.piece_le_genIdeal (fun q => Nat.succ_ne_zero _) hk (DirectSum.decompose ℳ b k).2)
    exact hmap (Ideal.mem_map_of_mem _ hb)

/-! ## The local generator under restriction and scalars -/

/-- The local generator commutes with restriction: for `V' ≤ V`, `c_p(φ)|_{V'} = c_p(φ|_{V'})` in `A(V')`
(`sectionsRestrict` is the graded restriction `A(V) → A(V')`; naturality of `ι_{i,q}` on sections). -/
theorem splitCoordGen_res {K : Type u} [Field K] {C : SmoothProjectiveCurve K}
    {n kk : ℕ} {E : AlgebraicGeometry.VectorBundle C.toVariety} (F : SubbundleFiltration E (n + 1))
    {V' V : C.toScheme.Opens} (h : V' ≤ V) (p : Fin (n + 1) × Fin kk)
    (φ : Γ(AlgebraicGeometry.Scheme.Modules.dual (F.lineQuotient p.1).toModules, V)) :
    (splitWeightedAlgebraOf F kk).sectionsRestrict h (splitCoordGen F V p φ) =
      splitCoordGen F V' p ((AlgebraicGeometry.Scheme.Modules.dual (F.lineQuotient p.1).toModules).res h φ) := by
  unfold splitCoordGen
  change (splitWeightedAlgebraOf F kk).sectionsRestrictRingHom h
    (DirectSum.of ((splitWeightedAlgebraOf F kk).sectionsPiece V) ((p.2 : ℕ) + 1) _) =
    DirectSum.of ((splitWeightedAlgebraOf F kk).sectionsPiece V') ((p.2 : ℕ) + 1) _
  rw [AlgebraicGeometry.Scheme.GradedQCAlgebra.sectionsRestrictRingHom_of]
  congr 1
  exact (_root_.PresheafOfModules.naturality_apply
    (splitCoordIncl (kk := kk) F p.1 ((p.2 : ℕ) + 1) (by simp only [Finset.mem_Icc]; omega)).val
    (CategoryTheory.homOfLE h).op φ).symm

/-- The local generator is `O(V)`-linear: `c_p(r • φ) = r · c_p(φ)` in `A(V)`, where `r ∈ Γ(V, O_C)` acts on
`A(V)` through the unit `A(V)_0 ∋ sectionsUnit V r` (`sectionsUnit_mul_of`). -/
theorem splitCoordGen_smul {K : Type u} [Field K] {C : SmoothProjectiveCurve K}
    {n kk : ℕ} {E : AlgebraicGeometry.VectorBundle C.toVariety} (F : SubbundleFiltration E (n + 1))
    (V : C.toScheme.Opens) (p : Fin (n + 1) × Fin kk) (r : Γ(C.toScheme, V))
    (φ : Γ(AlgebraicGeometry.Scheme.Modules.dual (F.lineQuotient p.1).toModules, V)) :
    splitCoordGen F V p (r • φ) =
      ((splitWeightedAlgebraOf F kk).sectionsUnit V r : (splitWeightedAlgebraOf F kk).sectionsRing V) *
        splitCoordGen F V p φ := by
  unfold splitCoordGen
  have h := ((splitCoordIncl (kk := kk) F p.1 ((p.2 : ℕ) + 1)
    (by simp only [Finset.mem_Icc]; omega)).val.app (Opposite.op V)).hom.map_smul r φ
  erw [h]
  exact (AlgebraicGeometry.Scheme.GradedQCAlgebra.sectionsUnit_mul_of (splitWeightedAlgebraOf F kk) V r _).symm

/-- Index transport on `O(a) ⊗ π^*N` acts on the first factor of a pure tensor (`subst`). -/
theorem AlgebraicGeometry.Scheme.relativeProj.eqToHom_tensor_app_moduleTensorSection {X : AlgebraicGeometry.Scheme.{u}}
    (S : X.GradedQCAlgebra) {a b : ℕ} (h : a = b) (N : (AlgebraicGeometry.Scheme.relativeProj S).left.Modules)
    (U : (AlgebraicGeometry.Scheme.relativeProj S).left.Opens)
    (s : Γ(AlgebraicGeometry.Scheme.relativeProj.twist S (a : ℤ), U)) (t : Γ(N, U)) :
    (CategoryTheory.eqToHom (congrArg (fun k : ℕ => AlgebraicGeometry.Scheme.Modules.tensor
        (AlgebraicGeometry.Scheme.relativeProj.twist S (k : ℤ)) N) h)).app U (AlgebraicGeometry.Scheme.Modules.moduleTensorSection s t) =
      AlgebraicGeometry.Scheme.Modules.moduleTensorSection
        ((CategoryTheory.eqToHom (congrArg (fun k : ℕ => AlgebraicGeometry.Scheme.relativeProj.twist S (k : ℤ)) h)).app U s)
        t := by
  subst h
  rfl

/-- Transporting a graded section along `h` and back is the identity (`subst`). -/
theorem AlgebraicGeometry.Scheme.GradedQCAlgebra.eqToHom_app_eqToHom_symm_app {X : AlgebraicGeometry.Scheme.{u}}
    (S : X.GradedQCAlgebra) {a b : ℕ} (h : a = b) (V : X.Opens) (x : Γ(S.part b, V)) :
    (CategoryTheory.eqToHom (congrArg S.part h)).app V
        ((CategoryTheory.eqToHom (congrArg S.part h.symm)).app V x) = x := by
  subst h
  rfl

/-- **Local form of the coordinate on a frame open.** `V ⊆ C` affine, `ε` a frame of `Q_i` on `V`, `1 ≤ q ≤ kk`.
Then `x_{i,q}|_{π⁻¹V} = evaluationLocal S q V (ι_{i,q} ε^∨) ⊗ η(ε)` in `Γ(π⁻¹V, O(q) ⊗ π^*Q_i)`
(`moduleTensorSection`), where `ι_{i,q} = splitCoordIncl F i q hq : Q_i^∨ ⟶ S_q`, `ε^∨ = hε.dualFrameOld` and
`η = unitSec` is the adjunction unit (pullback of sections). Informally: `x_{i,q} = (ε^∨ copy) ⊗ ε` on `π⁻¹V`
(the weight-`q` coordinate takes values in `Q_i`, as in the proof of Proposition 2.4 of the paper).

Source: Stacks 01CD (pullback commutes with tensor).

Proof sketch. By definition (`splitWeightedCoord`), `x_{i,q} = Φ (pullbackTensorIso π (Q^∨) Q).hom (π^* coev_Q)` with
`Φ = τ ≫ (φ ▷ π^*Q) ≫ τ⁻¹`, `φ = π^*ι ≫ ev_q`, and `π^* coev_Q = η_{Q^∨ ⊗ Q}(coev_Q)`.
1. On the frame open, `coev_Q|_V = ε^∨ ⊗ ε` (`ε^∨ ⊗ ε` is a frame of `Q^∨ ⊗ Q` and the zigzag identity on `ε` fixes
   the coordinate to `1`; `IsFrame.res_coevSection`).
2. `η` commutes with restriction and `pullbackTensorIso.hom (η(a ⊗ b)) = η(a) ⊗ η(b)`, so
   `(π^*coev)|_{π⁻¹V} = η(ε^∨) ⊗ η(ε)` as a pure tensor over `π⁻¹V`.
3. `Φ` acts on the first factor of a pure tensor: `Φ(η(ε^∨) ⊗ η(ε)) = φ(η(ε^∨)) ⊗ η(ε)`, and
   `φ(η(ε^∨)) = ev_q(η(ι ε^∨)) = evaluationLocal S q V (ι ε^∨)` (`evaluation_app_unit`).
Steps 1–3 are carried out for an arbitrary `S`, line bundle `Q` and `ι : Q^∨ ⟶ S_q` in
`relativeProj.coord_res_eq_moduleTensorSection_of_frame`, instantiated here at `ι = splitCoordIncl F i q hq`. -/
theorem splitWeightedCoord_res_eq_moduleTensorSection_of_frame {K : Type u} [Field K]
    {C : SmoothProjectiveCurve K} {n kk : ℕ} {E : AlgebraicGeometry.VectorBundle C.toVariety}
    (F : SubbundleFiltration E (n + 1)) (i : Fin (n + 1)) (q : ℕ) (hq : q ∈ Finset.Icc 1 kk)
    (V : C.toScheme.affineOpens) {ε : Γ((F.lineQuotient i).toModules, V.1)}
    (hε : AlgebraicGeometry.Scheme.Modules.IsFrame (F.lineQuotient i).toModules V.1 ε) :
    AlgebraicGeometry.Scheme.Modules.res
        ((AlgebraicGeometry.Scheme.relativeProj.twist (splitWeightedAlgebraOf F kk) (q : ℤ)).tensor
          ((AlgebraicGeometry.Scheme.Modules.pullback (splitWeightedProjectivization F kk).hom).obj
            (F.lineQuotient i).toModules))
        le_top (splitWeightedCoord F i q hq) =
      AlgebraicGeometry.Scheme.Modules.moduleTensorSection
        (AlgebraicGeometry.Scheme.relativeProj.evaluationLocal (splitWeightedAlgebraOf F kk) q V
          (((splitCoordIncl F i q hq).val.app (Opposite.op V.1)).hom hε.dualFrameOld))
        (MiyaokaMori.DualPullback.unitSec (splitWeightedProjectivization F kk).hom (F.lineQuotient i).toModules ε) := by
  -- the variable-level core, instantiated at `ι = splitCoordIncl F i q hq`; `splitWeightedCoord` unfolds to exactly the
  -- expression of the general lemma (`splitCoordIncl` is literally its `let ι`), and `dualFrameOld = dualFrameSection`
  -- definitionally (`IsFrame.dualFrameOld_eq_dualFrameSection`)
  have h := AlgebraicGeometry.Scheme.relativeProj.coord_res_eq_moduleTensorSection_of_frame
    (splitWeightedAlgebraOf F kk) (F.lineQuotient i).toModules q (splitCoordIncl F i q hq) V hε
  exact h

/-- **The coordinate power restricted to a frame open is `(c₀^k/1) ⊗ (frame)`.**
Let `V ⊆ C` be affine with a frame `ε` of `Q_i = F.lineQuotient i` on `V` (`p = (i, q-1)`, `q = p.2 + 1`, `k := m/q`),
and `w ∈ Γ(V, S^sp_m)` with `of m w = c₀^k` in `A(V)`, `c₀ := c_p(ε^∨) = splitCoordGen F V p hε.dualFrameOld`.
Then there is a frame `t` of `π^*Q_i^{⊗k}` on `π⁻¹V` with
`σ_p|_{π⁻¹V} = evaluationLocal S m V w ⊗ t` in `Γ(π⁻¹V, O(m) ⊗ π^*Q_i^{⊗k})` (`moduleTensorSection`).
(`t` is `η(ε^{⊗k})`, the pullback along `π` of the tensor power of the frame; only its existence is stated.)

Source: proof of Proposition 2.4 of the paper (the coordinate powers `x_{i,q}^{m/q}`); Stacks 01MO
(`(a/1)(b/1) = ab/1`), 01NR.

Proof sketch. The local form of the coordinate is `splitWeightedCoord_res_eq_moduleTensorSection_of_frame`:
`x|_{π⁻¹V} = evaluationLocal S q V (ι ε^∨) ⊗ η(ε)`, where `ι ε^∨ ∈ Γ(V, S_q)` has class `c₀` in `A(V)`. The power
`σ_p = splitTwistMul (x^{⊗k}) = Ψ_k(x^{⊗k})` with `Ψ = twistPullbackPow S q Q` (`splitTwistMul_eq_twistPullbackPow`,
followed by the index transport `q·k = m`); by induction on `e` (`twistPullbackPow_succ`), on `π⁻¹V`,
`Ψ_e(x^{⊗e})|_{π⁻¹V} = evaluationLocal S (qe) V w_e ⊗ η(ε^{⊗e})` for the `w_e ∈ Γ(V, S_{qe})` with
`of (qe) w_e = c₀^e` (`twistPullbackPow_comp_eqToHom_app_res_tensorPowSection`). The inductive step uses the
multiplicativity of the evaluation with respect to `twistMul` (`twistMul_app_moduleTensorSection_evaluationLocal`:
chart by chart this is Stacks 01MO on `Proj A(V)`, `twistSection a · twistSection b = twistSection (ab)`), the
pure-tensor formulas for `twistPullbackMul` and `pullbackTensorIso⁻¹`, and `of (qe+q) (sectionsGMul w_e (ι ε^∨)) =
c₀^e · c₀` (`DirectSum.of_mul_of`). Finally `ε^{⊗e}` is a frame of `Q^{⊗e}` (tensor of frames is a frame) and the
pullback of a frame is a frame (`DualPullback.isFrame_unitSec_pullback`).
Edge cases: `m = 0` (`k = 0`, `σ_p = ev_0(1) ⊗ 1`, `w = S.one 1`, `t = η(1)`); `kk = 0` has no `p`; `V = ⊥`. -/
theorem coordPowSection_res_eq_moduleTensorSection_of_frame {K : Type u} [Field K]
    {C : SmoothProjectiveCurve K} {n kk : ℕ} {E : AlgebraicGeometry.VectorBundle C.toVariety}
    (F : SubbundleFiltration E (n + 1)) (m : ℕ)
    (hdiv : ∀ q ∈ Finset.Icc 1 kk, q ∣ m) (p : Fin (n + 1) × Fin kk)
    (V : C.toScheme.affineOpens) {ε : Γ((F.lineQuotient p.1).toModules, V.1)}
    (hε : AlgebraicGeometry.Scheme.Modules.IsFrame (F.lineQuotient p.1).toModules V.1 ε)
    (w : Γ((splitWeightedAlgebraOf F kk).part m, V.1))
    (hw : (((splitWeightedAlgebraOf F kk).sectionsOf V.1 m w : (splitWeightedAlgebraOf F kk).sectionsGrading V.1 m) :
        (splitWeightedAlgebraOf F kk).sectionsRing V.1) =
      splitCoordGen F V.1 p hε.dualFrameOld ^ (m / ((p.2 : ℕ) + 1))) :
    ∃ t : Γ((AlgebraicGeometry.Scheme.Modules.pullback (splitWeightedProjectivization F kk).hom).obj
          (AlgebraicGeometry.Scheme.Modules.tensorPow (F.lineQuotient p.1).toModules (m / ((p.2 : ℕ) + 1))),
        (splitWeightedProjectivization F kk).hom ⁻¹ᵁ V.1),
      AlgebraicGeometry.Scheme.Modules.IsFrame
        ((AlgebraicGeometry.Scheme.Modules.pullback (splitWeightedProjectivization F kk).hom).obj
          (AlgebraicGeometry.Scheme.Modules.tensorPow (F.lineQuotient p.1).toModules (m / ((p.2 : ℕ) + 1))))
        ((splitWeightedProjectivization F kk).hom ⁻¹ᵁ V.1) t ∧
      ((AlgebraicGeometry.Scheme.relativeProj.twist (splitWeightedAlgebraOf F kk) (m : ℤ)).tensor
          ((AlgebraicGeometry.Scheme.Modules.pullback (splitWeightedProjectivization F kk).hom).obj
            (AlgebraicGeometry.Scheme.Modules.tensorPow (F.lineQuotient p.1).toModules
              (m / ((p.2 : ℕ) + 1))))).res le_top (coordPowSection F m hdiv p) =
        AlgebraicGeometry.Scheme.Modules.moduleTensorSection
          (AlgebraicGeometry.Scheme.relativeProj.evaluationLocal (splitWeightedAlgebraOf F kk) m V w) t := by
  have hq : (p.2 : ℕ) + 1 ∈ Finset.Icc 1 kk := by simp only [Finset.mem_Icc]; omega
  have hkq : ((p.2 : ℕ) + 1) * (m / ((p.2 : ℕ) + 1)) = m := Nat.mul_div_cancel' (hdiv _ hq)
  have hx := splitWeightedCoord_res_eq_moduleTensorSection_of_frame F p.1 ((p.2 : ℕ) + 1) hq V hε
  have hx' : AlgebraicGeometry.Scheme.Modules.res
      (AlgebraicGeometry.Scheme.Modules.tensor
        (AlgebraicGeometry.Scheme.relativeProj.twist (splitWeightedAlgebraOf F kk) (((p.2 : ℕ) + 1 : ℕ) : ℤ))
        ((AlgebraicGeometry.Scheme.Modules.pullback
          (AlgebraicGeometry.Scheme.relativeProj (splitWeightedAlgebraOf F kk)).hom).obj (F.lineQuotient p.1).toModules))
      le_top (splitWeightedCoord F p.1 ((p.2 : ℕ) + 1) hq) =
      AlgebraicGeometry.Scheme.Modules.moduleTensorSection
        (AlgebraicGeometry.Scheme.relativeProj.evaluationLocal (splitWeightedAlgebraOf F kk) ((p.2 : ℕ) + 1) V
          (((splitCoordIncl F p.1 ((p.2 : ℕ) + 1) hq).val.app (Opposite.op V.1)).hom hε.dualFrameOld))
        (MiyaokaMori.DualPullback.unitSec (AlgebraicGeometry.Scheme.relativeProj (splitWeightedAlgebraOf F kk)).hom
          (F.lineQuotient p.1).toModules ε) := hx
  have hw' : (((splitWeightedAlgebraOf F kk).sectionsOf V.1 m w : (splitWeightedAlgebraOf F kk).sectionsGrading V.1 m) :
        (splitWeightedAlgebraOf F kk).sectionsRing V.1) =
      (((splitWeightedAlgebraOf F kk).sectionsOf V.1 ((p.2 : ℕ) + 1)
        (((splitCoordIncl F p.1 ((p.2 : ℕ) + 1) hq).val.app (Opposite.op V.1)).hom hε.dualFrameOld) :
          (splitWeightedAlgebraOf F kk).sectionsGrading V.1 ((p.2 : ℕ) + 1)) :
        (splitWeightedAlgebraOf F kk).sectionsRing V.1) ^ (m / ((p.2 : ℕ) + 1)) := hw
  have key := AlgebraicGeometry.Scheme.relativeProj.twistPullbackPow_comp_eqToHom_app_res_tensorPowSection
    (splitWeightedAlgebraOf F kk) ((p.2 : ℕ) + 1) (F.lineQuotient p.1).toModules V
    (splitWeightedCoord F p.1 ((p.2 : ℕ) + 1) hq)
    (((splitCoordIncl F p.1 ((p.2 : ℕ) + 1) hq).val.app (Opposite.op V.1)).hom hε.dualFrameOld) ε hx'
    (m / ((p.2 : ℕ) + 1)) m hkq w hw' (splitTwistMul_index_eq F kk p.1 ((p.2 : ℕ) + 1) m (hdiv _ hq))
  -- `σ_p = splitTwistMul (x^{⊗k})` (definitional) `= (Ψ_k ≫ eqToHom) (x^{⊗k})` (bridge `splitTwistMul_eq_twistPullbackPow`);
  -- the object equation and the frame witness are taken from `key` unchanged, so that the instance of the general
  -- lemma is syntactically the goal (any spelling difference under `res`/`Hom.app` makes the kernel unfold
  -- `twistPullbackPow`; measured > 60 s)
  -- (`x^{⊗k}` is spelled with `relativeProj` so that it is syntactically the term inside `key`)
  have hσ : coordPowSection F m hdiv p = splitTwistMul F kk p.1 ((p.2 : ℕ) + 1) m (hdiv _ hq)
      (AlgebraicGeometry.Scheme.Modules.tensorPowSection
        (M := AlgebraicGeometry.Scheme.Modules.tensor
          (AlgebraicGeometry.Scheme.relativeProj.twist (splitWeightedAlgebraOf F kk) (((p.2 : ℕ) + 1 : ℕ) : ℤ))
          ((AlgebraicGeometry.Scheme.Modules.pullback
            (AlgebraicGeometry.Scheme.relativeProj (splitWeightedAlgebraOf F kk)).hom).obj
            (F.lineQuotient p.1).toModules))
        (splitWeightedCoord F p.1 ((p.2 : ℕ) + 1) hq) (m / ((p.2 : ℕ) + 1))) := rfl
  delta splitWeightedProjectivization
  rw [hσ, splitTwistMul_eq_twistPullbackPow F kk p.1 ((p.2 : ℕ) + 1) m (hdiv _ hq)]
  refine ⟨_, ?_, key⟩
  exact MiyaokaMori.DualPullback.isFrame_unitSec_pullback _ _
    (AlgebraicGeometry.Scheme.Modules.isFrame_framePow hε (m / ((p.2 : ℕ) + 1)))

/-- **Local form of the coordinate power.**
Let `V ⊆ C` be affine with a frame `ε` of `Q_i = F.lineQuotient i` on `V` (`p = (i, q-1)`, `q = p.2 + 1`,
`k := m/q`), `y ∈ π⁻¹V`, and `w ∈ Γ(V, S^sp_m)` with `w = c₀^k` in `A(V)`, where `c₀ := c_p(ε^∨) ∈ A(V)_q` is the
local generator of the dual frame (`IsFrame.dualFrameOld`). If the germ at `y` of the coordinate power
`σ_p = coordPowSection F m hdiv p ∈ Γ(Y^sp, O(m) ⊗ π^*Q_i^{⊗k})` lies in `𝔪_y · (O(m) ⊗ π^*Q_i^{⊗k})_y`, then the
germ at `y` of `evaluationLocal S m V w ∈ Γ(π⁻¹V, O(m))` ("`c₀^k/1`") lies in `𝔪_y · O(m)_y`.

Source: proof of Proposition 2.4 of the paper ("`D_+(x_p)` is exactly the nonvanishing locus of `σ_p`");
Stacks 01MO, 01NR.

Proof: by `coordPowSection_res_eq_moduleTensorSection_of_frame`, on `π⁻¹V` we have `σ_p = evaluationLocal S m V w ⊗ t`
with `t` a frame of `π^*Q_i^{⊗k}`; for a section `s ⊗ t` with `t` a frame of `N`,
`germ_y (s ⊗ t) ∈ 𝔪_y • ⊤ ↔ germ_y s ∈ 𝔪_y • ⊤` (under `(L ⊗ N)_y ≅ L_y ⊗ O_y ≅ L_y` the germ of `s ⊗ t` corresponds
to the germ of `s`; `IsFrame.germ_mem_maximalIdeal_smul_of_germ_moduleTensorSection_mem`). Finally
`germ_⊤ y σ_p = germ_{π⁻¹V} y (σ_p|_{π⁻¹V})` (`germ_res_apply`).
Only this direction (vanishing of `σ_p` forces vanishing of `c₀^k/1`) is needed for coverage; the converse needs
`O(m)` invertible. `hm : 0 < m` is not needed (`m = 0`: `k = 0`, `σ_p = ev_0(1) ⊗ 1`, `w = 1`, both sides agree).
Edge cases: `kk = 0` has no `p`; `V = ⊥` has no `y`. -/
theorem coordPowSection_germ_mem_of_frame {K : Type u} [Field K]
    {C : SmoothProjectiveCurve K} {n kk : ℕ} {E : AlgebraicGeometry.VectorBundle C.toVariety}
    (F : SubbundleFiltration E (n + 1)) (m : ℕ)
    (hdiv : ∀ q ∈ Finset.Icc 1 kk, q ∣ m) (p : Fin (n + 1) × Fin kk)
    (V : C.toScheme.affineOpens) {ε : Γ((F.lineQuotient p.1).toModules, V.1)}
    (hε : AlgebraicGeometry.Scheme.Modules.IsFrame (F.lineQuotient p.1).toModules V.1 ε)
    (y : (splitWeightedProjectivization F kk).left)
    (hy : y ∈ (splitWeightedProjectivization F kk).hom ⁻¹ᵁ V.1)
    (w : Γ((splitWeightedAlgebraOf F kk).part m, V.1))
    (hw : (((splitWeightedAlgebraOf F kk).sectionsOf V.1 m w : (splitWeightedAlgebraOf F kk).sectionsGrading V.1 m) :
        (splitWeightedAlgebraOf F kk).sectionsRing V.1) =
      splitCoordGen F V.1 p hε.dualFrameOld ^ (m / ((p.2 : ℕ) + 1)))
    (hσ : ((AlgebraicGeometry.Scheme.relativeProj.twist (splitWeightedAlgebraOf F kk) (m : ℤ)).tensor
        ((AlgebraicGeometry.Scheme.Modules.pullback (splitWeightedProjectivization F kk).hom).obj
          (AlgebraicGeometry.Scheme.Modules.tensorPow (F.lineQuotient p.1).toModules
            (m / ((p.2 : ℕ) + 1))))).presheaf.germ ⊤ y trivial (coordPowSection F m hdiv p) ∈
      (IsLocalRing.maximalIdeal ((splitWeightedProjectivization F kk).left.presheaf.stalk y)) •
        (⊤ : Submodule ((splitWeightedProjectivization F kk).left.presheaf.stalk y)
          (((AlgebraicGeometry.Scheme.relativeProj.twist (splitWeightedAlgebraOf F kk) (m : ℤ)).tensor
            ((AlgebraicGeometry.Scheme.Modules.pullback (splitWeightedProjectivization F kk).hom).obj
              (AlgebraicGeometry.Scheme.Modules.tensorPow (F.lineQuotient p.1).toModules
                (m / ((p.2 : ℕ) + 1))))).stalk y))) :
    (AlgebraicGeometry.Scheme.relativeProj.twist (splitWeightedAlgebraOf F kk) (m : ℤ)).presheaf.germ
        ((splitWeightedProjectivization F kk).hom ⁻¹ᵁ V.1) y hy
        (AlgebraicGeometry.Scheme.relativeProj.evaluationLocal (splitWeightedAlgebraOf F kk) m V w) ∈
      (IsLocalRing.maximalIdeal ((splitWeightedProjectivization F kk).left.presheaf.stalk y)) •
        (⊤ : Submodule ((splitWeightedProjectivization F kk).left.presheaf.stalk y)
          ((AlgebraicGeometry.Scheme.relativeProj.twist (splitWeightedAlgebraOf F kk) (m : ℤ)).stalk y)) := by
  obtain ⟨t, ht, hres⟩ := coordPowSection_res_eq_moduleTensorSection_of_frame F m hdiv p V hε w hw
  have h1 := (TopCat.Presheaf.germ_res_apply
    ((AlgebraicGeometry.Scheme.relativeProj.twist (splitWeightedAlgebraOf F kk) (m : ℤ)).tensor
      ((AlgebraicGeometry.Scheme.Modules.pullback (splitWeightedProjectivization F kk).hom).obj
        (AlgebraicGeometry.Scheme.Modules.tensorPow (F.lineQuotient p.1).toModules
          (m / ((p.2 : ℕ) + 1))))).presheaf
    (CategoryTheory.homOfLE (le_top : (splitWeightedProjectivization F kk).hom ⁻¹ᵁ V.1 ≤ ⊤)) y hy
    (coordPowSection F m hdiv p)).symm
  change _ = ((AlgebraicGeometry.Scheme.relativeProj.twist (splitWeightedAlgebraOf F kk) (m : ℤ)).tensor
      ((AlgebraicGeometry.Scheme.Modules.pullback (splitWeightedProjectivization F kk).hom).obj
        (AlgebraicGeometry.Scheme.Modules.tensorPow (F.lineQuotient p.1).toModules
          (m / ((p.2 : ℕ) + 1))))).presheaf.germ _ y hy
      (((AlgebraicGeometry.Scheme.relativeProj.twist (splitWeightedAlgebraOf F kk) (m : ℤ)).tensor
        ((AlgebraicGeometry.Scheme.Modules.pullback (splitWeightedProjectivization F kk).hom).obj
          (AlgebraicGeometry.Scheme.Modules.tensorPow (F.lineQuotient p.1).toModules
            (m / ((p.2 : ℕ) + 1))))).res le_top (coordPowSection F m hdiv p)) at h1
  rw [h1, hres] at hσ
  exact ht.germ_mem_maximalIdeal_smul_of_germ_moduleTensorSection_mem _ hy _ hσ

/-- **`D_+(x_p)` is where `σ_p = x_p^{m/q}` does not vanish** (proof of Proposition 2.4 of the paper),
in the direction needed for coverage. Let `V ⊆ C` be affine, `y ∈ π⁻¹V`, and `φ_V(y) ∈ Proj A(V)` its image under
`relativeProj.affineIso` (Stacks 01NQ). If a local generator `c_p(φ) = splitCoordGen F V p φ` (`p = (i, q-1)`,
`φ ∈ Γ(V, Q_i^∨)`) is not in the homogeneous prime of `φ_V(y)`, then the germ of the coordinate power
`σ_p = coordPowSection F m hdiv p ∈ Γ(Y^sp, O(m) ⊗ π^*Q_i^{⊗ m/q})` at `y` is not in `𝔪_y L_y`, i.e.
`y ∈ nonvanishingLocus σ_p`.

Proof sketch. Shrink: choose an affine `V' ≤ V` with `π(y) ∈ V'` on which `Q_i` has a frame `ε`
(`Modules.exists_affine_frame_le`). The restriction `A(V) → A(V')` is a graded ring map compatible with the chart
isomorphisms (Stacks 01NQ, `affineIso_restrict`): the point `φ_{V'}(y)` maps to `φ_V(y)` under `Proj.map`, so its
prime is the preimage of `𝔭 := 𝔭_{φ_V(y)}`, and `c_p(φ)|_{V'} ∉ 𝔭_{φ_{V'}(y)}`. On `V'`, `φ = a • ε^∨`
(`IsFrame.eq_smul_dualFrame` through the bridge `dualSheafSectionsEquivOld`), so `c_p(φ)|_{V'} = a · c₀` with
`c₀ := c_p(ε^∨)`; as `𝔭_{φ_{V'}(y)}` is an ideal, `c₀ ∉ 𝔭_{φ_{V'}(y)}`, hence `c₀^{k} ∉ 𝔭_{φ_{V'}(y)}` (prime),
`k := m/q ≥ 1`. By `coordPowSection_germ_mem_of_frame` it suffices that the germ of `evaluationLocal S m V' (c₀^k)`
at `y` is not in `𝔪_y O(m)_y`. Transporting along `φ_{V'}` and `twistAffineIso` (Stacks 01NR; `evaluationLocal` is by
definition the transport of `Proj.twistSection (c₀^k)`), this is the statement on `Proj A(V')`: for
`f := c₀^k ∈ A(V')_m` with `f ∉ 𝔭`, the germ of `f/1` in `O(m)_𝔭 = (A(V')_𝔭)_m` is not in `𝔪_𝔭 (A(V')_𝔭)_m`. Indeed
`f/1` generates `(A_𝔭)_m` (`g/h = (g/(h f)) · (f/1)` with `g/(hf) ∈ (A_𝔭)_0`) and is nonzero (`h f ≠ 0` for `h ∉ 𝔭`),
and a nonzero cyclic module over a local ring is not equal to `𝔪` times itself (Nakayama for one generator, as in
`IsFrame.germ_notMem_maximalIdeal_smul`). No invertibility of `O(m)` is needed for this direction; `hm`, `hdiv` only
provide the line-bundle instance that makes `nonvanishingLocus` an open set.
Edge cases: `kk = 0` has no `p`. -/
theorem mem_nonvanishingLocus_coordPowSection_of_splitCoordGen_not_mem {K : Type u} [Field K]
    {C : SmoothProjectiveCurve K} {n kk : ℕ} {E : AlgebraicGeometry.VectorBundle C.toVariety}
    (F : SubbundleFiltration E (n + 1)) (m : ℕ) (hm : 0 < m)
    (hdiv : ∀ q ∈ Finset.Icc 1 kk, q ∣ m) (p : Fin (n + 1) × Fin kk)
    (V : C.toScheme.affineOpens)
    (φ : Γ(AlgebraicGeometry.Scheme.Modules.dual (F.lineQuotient p.1).toModules, V.1))
    (y : (splitWeightedProjectivization F kk).left)
    (hy : y ∈ (splitWeightedProjectivization F kk).hom ⁻¹ᵁ V.1)
    (hφ : splitCoordGen F V.1 p φ ∉
      ((AlgebraicGeometry.Scheme.relativeProj.affineIso (splitWeightedAlgebraOf F kk) V).hom
        ⟨y, hy⟩).asHomogeneousIdeal) :
    haveI := coordPowSection_isLineBundle F m hm hdiv p
    y ∈ AlgebraicGeometry.Scheme.Modules.nonvanishingLocus
      ((AlgebraicGeometry.Scheme.relativeProj.twist (splitWeightedAlgebraOf F kk) (m : ℤ)).tensor
        ((AlgebraicGeometry.Scheme.Modules.pullback (splitWeightedProjectivization F kk).hom).obj
          (AlgebraicGeometry.Scheme.Modules.tensorPow (F.lineQuotient p.1).toModules
            (m / ((p.2 : ℕ) + 1)))))
      (coordPowSection F m hdiv p) := by
  have := coordPowSection_isLineBundle F m hm hdiv p
  have hq : (p.2 : ℕ) + 1 ∈ Finset.Icc 1 kk := by simp only [Finset.mem_Icc]; omega
  -- Step 1: shrink to an affine `W ≤ V` containing `π y` on which `Q_i` has a frame `ε`.
  have hπy : (splitWeightedProjectivization F kk).hom y ∈ V.1 := hy
  obtain ⟨W, hWaff, hWV, hyW, ε, hε⟩ :=
    AlgebraicGeometry.Scheme.Modules.exists_affine_frame_le (F.lineQuotient p.1).toModules hπy
  let V' : C.toScheme.affineOpens := ⟨W, hWaff⟩
  have hy' : y ∈ (splitWeightedProjectivization F kk).hom ⁻¹ᵁ V'.1 := hyW
  -- the prime of `φ_W(y)` does not contain `c_p(φ)|_W` (prime transport along `A(V) → A(W)`)
  have h1 := AlgebraicGeometry.Scheme.relativeProj.sectionsRestrict_notMem_affineIso_of_notMem
    (splitWeightedAlgebraOf F kk) V' V hWV y hy' (splitCoordGen F V.1 p φ) hφ
  rw [splitCoordGen_res F hWV p φ] at h1
  -- Step 2: `φ|_W = a • ε^∨`, so `c_p(φ)|_W = a · c₀`; hence `c₀ ∉ 𝔭` and `c₀^k ∉ 𝔭`.
  obtain ⟨a, ha⟩ := hε.exists_eq_smul_dualFrameOld
    ((AlgebraicGeometry.Scheme.Modules.dual (F.lineQuotient p.1).toModules).res hWV φ)
  rw [ha, splitCoordGen_smul] at h1
  have hc₀ : splitCoordGen F V'.1 p hε.dualFrameOld ∉
      ((AlgebraicGeometry.Scheme.relativeProj.affineIso (splitWeightedAlgebraOf F kk) V').hom
        ⟨y, hy'⟩).asHomogeneousIdeal :=
    fun hc => h1 (Ideal.mul_mem_left _ _ hc)
  have hpow : splitCoordGen F V'.1 p hε.dualFrameOld ^ (m / ((p.2 : ℕ) + 1)) ∉
      ((AlgebraicGeometry.Scheme.relativeProj.affineIso (splitWeightedAlgebraOf F kk) V').hom
        ⟨y, hy'⟩).asHomogeneousIdeal :=
    fun hc => hc₀ (((AlgebraicGeometry.Scheme.relativeProj.affineIso (splitWeightedAlgebraOf F kk) V').hom
      ⟨y, hy'⟩).isPrime.mem_of_pow_mem _ hc)
  -- `c₀^k` is homogeneous of degree `m`: it is `of m w` for a section `w ∈ Γ(W, S_m)`.
  have hc₀mem : splitCoordGen F V'.1 p hε.dualFrameOld ∈
      (splitWeightedAlgebraOf F kk).sectionsGrading V'.1 ((p.2 : ℕ) + 1) :=
    ((splitWeightedAlgebraOf F kk).sectionsOf V'.1 ((p.2 : ℕ) + 1) _).2
  have hpowmem := SetLike.pow_mem_graded (m / ((p.2 : ℕ) + 1)) hc₀mem
  have hkq : (m / ((p.2 : ℕ) + 1)) • ((p.2 : ℕ) + 1) = m := by
    rw [smul_eq_mul]; exact Nat.div_mul_cancel (hdiv _ hq)
  rw [hkq] at hpowmem
  obtain ⟨w, hw⟩ := AddMonoidHom.mem_range.mp hpowmem
  have hw' : (((splitWeightedAlgebraOf F kk).sectionsOf V'.1 m w :
      (splitWeightedAlgebraOf F kk).sectionsGrading V'.1 m) : (splitWeightedAlgebraOf F kk).sectionsRing V'.1) =
      splitCoordGen F V'.1 p hε.dualFrameOld ^ (m / ((p.2 : ℕ) + 1)) := hw
  -- Step 6: the germ of `c₀^k/1` at `y` is not in `𝔪_y O(m)_y`.
  have hev := AlgebraicGeometry.Scheme.relativeProj.germ_evaluationLocal_notMem_maximalIdeal_smul
    (splitWeightedAlgebraOf F kk) m V' w y hy' (by rw [hw']; exact hpow)
  -- Steps 3–5: the coordinate power vanishes at `y` only where `c₀^k/1` does.
  refine (AlgebraicGeometry.Scheme.Modules.mem_nonvanishingLocus _ _ _).mpr fun hσ => hev ?_
  exact coordPowSection_germ_mem_of_frame F m hdiv p V' hε y hy' w hw' hσ

end
