import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Proj.ProjectiveSpace.ProjectiveEmbedding
import MiyaokaMori.AlgebraicGeometry.Proj.ProjectiveSpace.ProjectiveVanishingIdeal

/-! # `IsVanishingLocus`: a family of forms generates the saturated ideal of `X ⊂ P^N`

Source: §2 of the paper (the generators `F_j` of the homogeneous ideal of `X ⊂ P^N`) and the proof
of Theorem 4.2 ("if the `F_j` vanish after substitution, the morphism factors through `X`").

`IsVanishingLocus e F` says that the ideal generated by the family `F : ι → k[x_0,…,x_N]` is the
saturated homogeneous vanishing ideal `Γ_*(I_X)` (`projectiveVanishingIdeal e.emb.ker`) of the closed
immersion `e.emb : X ↪ P^N`. It is a predicate on the *equations* of `X`, not a factorization datum:
the factorization of a morphism `T → P^N` through `X` is `AlgebraicGeometry.Proj.ProjectiveEmbeddingGlobalFactorization`
(hypothesis: the chart kernels are killed), and the two are linked by `projectivizationMorphism_factors`
(`Paper/S3PositiveLine/Realization/ProjectivizationOfNowhereZeroTuple`) via `projectiveVanishingIdeal_localizes`.
`EmbeddingEquations.spans` (`Paper/S2WeightedJets/Cone/HomogeneousIdealGenerators`) is typed by this predicate.
-/

set_option autoImplicit false

universe u

open CategoryTheory Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

attribute [local instance] MvPolynomial.gradedAlgebra

/-- The family `F` generates the saturated homogeneous vanishing ideal `Γ_*(I_X)` of `X ↪ P^N`
(§2 of the paper). Note this is stronger than "`X = V(F)` as schemes": it asks for the saturated
ideal itself, not merely for an ideal with the same saturation. -/
def IsVanishingLocus {k : Type u} [Field k] {X : AlgebraicGeometry.Scheme.{u}}
    [X.Over (AlgebraicGeometry.Spec (CommRingCat.of k))] {N : ℕ} {ι : Type u}
    (e : ProjectiveEmbedding k X N) (F : ι → MvPolynomial (Fin (N + 1)) k) : Prop :=
    Ideal.span (Set.range F)
    = (projectiveVanishingIdeal e.emb.ker).toIdeal

end
