import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Proj.ProjectiveSpace.ProjectiveSpace

/-! # The saturated homogeneous vanishing ideal of a closed subscheme of `P^N`

The saturated homogeneous vanishing ideal `Γ_*(I)` of a closed subscheme of `P^N`; the
defining equations `F_j` of `X ⊂ P^N` in §2 of the paper are a set of generators of it.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

attribute [local instance] MvPolynomial.gradedAlgebra

/-- The degree-`d` part `I_*(d)`: the forms `F ∈ k[x]_d` such that for every `i` the fraction
`F/x_i^d ∈ Away 𝒜 x_i`, sent through `awayToSection`, lies in the ideal `I` on the affine open
`D_+(x_i)`. -/

def projectiveVanishingIdealDeg {k : Type u} [Field k] {N : ℕ}
    (I : (ProjectiveSpace N k).IdealSheafData) (d : ℕ) :
    Set (MvPolynomial (Fin (N + 1)) k) :=
  {F | ∃ hF : F ∈ MvPolynomial.homogeneousSubmodule (Fin (N + 1)) k d,
    ∀ i : Fin (N + 1),
      (AlgebraicGeometry.Proj.awayToSection (MvPolynomial.homogeneousSubmodule (Fin (N + 1)) k)
          (MvPolynomial.X i)).hom
        (HomogeneousLocalization.Away.mk (MvPolynomial.homogeneousSubmodule (Fin (N + 1)) k)
          ((MvPolynomial.mem_homogeneousSubmodule 1 _).2 (MvPolynomial.isHomogeneous_X k i)) d F
          (by rwa [smul_eq_mul, mul_one])) ∈
        I.ideal ⟨AlgebraicGeometry.Proj.basicOpen
            (MvPolynomial.homogeneousSubmodule (Fin (N + 1)) k) (MvPolynomial.X i),
          AlgebraicGeometry.Proj.isAffineOpen_basicOpen _ _
            ((MvPolynomial.mem_homogeneousSubmodule 1 _).2 (MvPolynomial.isHomogeneous_X k i))
            Nat.one_pos⟩}

/-- The saturated homogeneous vanishing ideal `Γ_*(I)`: the ideal generated by `⋃_d I_*(d)`
(the generators are homogeneous, so it is a homogeneous ideal). -/

noncomputable def projectiveVanishingIdeal {k : Type u} [Field k] {N : ℕ}
    (I : (ProjectiveSpace N k).IdealSheafData) :
    HomogeneousIdeal (MvPolynomial.homogeneousSubmodule (Fin (N + 1)) k) :=
  ⟨Ideal.span (⋃ d, projectiveVanishingIdealDeg I d),
    Ideal.homogeneous_span _ _ (fun F hF => by
      obtain ⟨d, hd⟩ := Set.mem_iUnion.1 hF
      exact ⟨d, hd.1⟩)⟩

end
