import MiyaokaMori.AlgebraicGeometry.Proj.ProjectiveSpace.ProjectiveCoordinateRatio

/-!
# Homogeneous equations under the existing projective chart evaluation

For the chart evaluation `ProjectiveSpaceOverChart.chartEvaluation`, the image of the genuine
homogeneous fraction `F / Xⱼ^d` satisfies its denominator identity. An equation `e F = 0`
therefore vanishes in this chart, and the ideal generated by any family of these fractions
lies in the kernel. The degree may be zero and the target may be the zero ring.

Source: Theorem 4.2 of the paper (§4), especially the equations vanishing identically
before projectivization. This algebra step does not identify the generated ideal with the
ideal of the original closed target or construct the scheme factorization into that target.
-/

noncomputable section

namespace AlgebraicGeometry.Proj.ProjectiveChartEquationEvaluation

open ProjectiveSpaceOverChart

universe u v

variable {k R : Type u} [Field k] [CommRing R]

attribute [local instance] MvPolynomial.gradedAlgebra

/-- The coordinate variable `X j` **belongs to** the degree-one part of the standard grading. Use this rather
than `MvPolynomial.isHomogeneous_X k j : (X j).IsHomogeneous 1` where a proof of `X j ∈ projectiveGrading k n 1`
is expected: the two are defeq only at default transparency, and goals containing the latter spelling make
`rw`/`simp` fail to match. -/
theorem X_mem_projectiveGrading (n : ℕ) (j : Fin (n + 1)) :
    MvPolynomial.X j ∈ projectiveGrading k n 1 :=
  (MvPolynomial.mem_homogeneousSubmodule _ _).mpr (MvPolynomial.isHomogeneous_X k j)

/-- Evaluation of a homogeneous fraction satisfies its actual denominator identity. -/
theorem chartEvaluation_mk_mul (n : ℕ)
    (e : MvPolynomial (Fin (n + 1)) k →+* R) (j : Fin (n + 1))
    (hj : IsUnit (e (MvPolynomial.X j))) (F : MvPolynomial (Fin (n + 1)) k)
    (d : ℕ) (hF : F.IsHomogeneous d) :
    chartEvaluation n e j hj
        (HomogeneousLocalization.Away.mk (projectiveGrading k n)
          (X_mem_projectiveGrading n j) d F (by simpa using hF)) *
      e (MvPolynomial.X j) ^ d = e F := by
  let l := IsLocalization.Away.lift
    (S := Localization.Away (MvPolynomial.X (R := k) j))
    (g := e) (MvPolynomial.X (R := k) j) hj
  have h := congrArg l
    (IsLocalization.mk'_spec (Localization.Away (MvPolynomial.X (R := k) j))
      F (⟨MvPolynomial.X (R := k) j ^ d, ⟨d, rfl⟩⟩ :
        Submonoid.powers (MvPolynomial.X (R := k) j)))
  simpa only [chartEvaluation, RingHom.comp_apply, HomogeneousLocalization.algebraMap_apply,
    HomogeneousLocalization.Away.val_mk, Localization.mk_eq_mk', map_mul, map_pow, l,
    IsLocalization.Away.lift_eq] using h

/-- A homogeneous equation vanishing under polynomial evaluation also vanishes in the
same projective chart; cancellation uses only the invertibility of its denominator. -/
theorem chartEvaluation_mk_eq_zero (n : ℕ)
    (e : MvPolynomial (Fin (n + 1)) k →+* R) (j : Fin (n + 1))
    (hj : IsUnit (e (MvPolynomial.X j))) (F : MvPolynomial (Fin (n + 1)) k)
    (d : ℕ) (hF : F.IsHomogeneous d) (hzero : e F = 0) :
    chartEvaluation n e j hj
      (HomogeneousLocalization.Away.mk (projectiveGrading k n)
        (X_mem_projectiveGrading n j) d F (by simpa using hF)) = 0 := by
  exact (hj.pow d).mul_left_eq_zero.mp
    ((chartEvaluation_mk_mul n e j hj F d hF).trans hzero)

/-- Any indexed family of vanishing homogeneous equations generates an ideal in the
kernel of the existing chart evaluation. The family may be empty or infinite. -/
theorem span_range_mk_le_ker (n : ℕ)
    (e : MvPolynomial (Fin (n + 1)) k →+* R) (j : Fin (n + 1))
    (hj : IsUnit (e (MvPolynomial.X j))) {ι : Type v}
    (F : ι → MvPolynomial (Fin (n + 1)) k) (d : ι → ℕ)
    (hF : ∀ a, (F a).IsHomogeneous (d a)) (hzero : ∀ a, e (F a) = 0) :
    Ideal.span (Set.range (fun a ↦
      HomogeneousLocalization.Away.mk (projectiveGrading k n)
        (X_mem_projectiveGrading n j) (d a) (F a) (by simpa using hF a))) ≤
      RingHom.ker (chartEvaluation n e j hj) := by
  apply Ideal.span_le.mpr
  rintro _ ⟨a, rfl⟩
  exact RingHom.mem_ker.mpr (chartEvaluation_mk_eq_zero n e j hj (F a) (d a) (hF a) (hzero a))

end AlgebraicGeometry.Proj.ProjectiveChartEquationEvaluation
