import MiyaokaMori.Prelude
import MiyaokaMori.RingTheory.Dimension.Stacks00op
import MiyaokaMori.RingTheory.Dimension.FiniteTypeDomainDimension

/-! # Quotient of a finite type domain by a height-one prime

Let `k` be a field, `A` a finite type `k`-algebra which is a domain, and `P` a prime of height `1`
in `A`. Then `dim A/P + 1 = dim A`.

Proof:
1. Noether normalization (Mathlib `exists_integral_inj_algHom_of_fg`): there are `n` and an injective
   integral `k`-algebra map `R = k[x_1..x_n] → A`; injective integral extensions preserve dimension
   (`MiyaokaMori.RingTheory.ringKrullDim_eq_of_integral_injective`), so `dim A = dim R = n`
   (`MvPolynomial.ringKrullDim_of_isNoetherianRing`).
2. `R` is a UFD, hence integrally closed; `A` is a domain, integral over `R`, and `R → A` is
   injective, so `R → A` has going-down (Mathlib instance in `RingTheory/IntegralClosure/GoingDown`,
   Stacks 00H8). Let `q = P ∩ R`. By Stacks 00ON (Mathlib
   `Ideal.height_eq_height_add_of_liesOver_of_hasGoingDown`),
   `height P = height q + height(P/qA)`, so `height q ≤ 1`; since `P ≠ 0` and `A` is integral over
   `R`, `q ≠ 0` (`Ideal.under_ne_bot`), hence `height q = 1`.
3. `R` is a UFD, so height-one primes are principal: `q = (g)` with `g` a prime element
   (`Ideal.IsPrime.exists_mem_prime_of_ne_bot`, `Ideal.eq_span_singleton_of_height_eq_one`).
4. `dim R/(g) + 1 ≤ dim R = n` (`g` is a nonzerodivisor,
   `ringKrullDim_quotient_succ_le_of_nonZeroDivisor`). Conversely, choose a maximal ideal `𝔫`
   containing `g`; by Stacks 00OP (module `Stacks00op`) `height 𝔫 = n`, and by the corollary of
   Krull's principal ideal theorem (`Ideal.height_le_ringKrullDim_quotient_add_one`)
   `n = height 𝔫 ≤ dim R/(g) + 1`. Hence `dim R/q + 1 = n`.
5. `A/P` is integral over `R/q` and `R/q → A/P` is injective
   (`Ideal.Quotient.algebra_isIntegral_of_liesOver`, `Ideal.Quotient.instFaithfulSMul`), so
   `dim A/P = dim R/q`. Altogether `dim A/P + 1 = n = dim A`.

Reference: needed for the proof of Stacks 00OS; instead of the route through 00OQ/00OR using
Cohen–Macaulay rings, this uses Noether normalization + going-down, i.e. the argument of Matsumura,
*Commutative Algebra*, (14.H).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

noncomputable section

/-- The quotient of the polynomial ring `k[x_1..x_n]` by the principal ideal generated by a prime
element has dimension exactly one less. -/
private theorem MvPolynomial.ringKrullDim_quotient_span_prime_add_one {k : Type u} [Field k] (n : ℕ)
    (g : MvPolynomial (Fin n) k) (hg : Prime g) :
    ringKrullDim (MvPolynomial (Fin n) k ⧸ Ideal.span {g}) + 1 = (n : WithBot ℕ∞) := by
  have hdim : ringKrullDim (MvPolynomial (Fin n) k) = (n : WithBot ℕ∞) := by
    rw [MvPolynomial.ringKrullDim_of_isNoetherianRing]; simp
  refine le_antisymm ?_ ?_
  · rw [← hdim]
    exact ringKrullDim_quotient_succ_le_of_nonZeroDivisor
      (mem_nonZeroDivisors_of_ne_zero hg.ne_zero)
  · have hne : Ideal.span {g} ≠ ⊤ := by
      rw [Ne, Ideal.span_singleton_eq_top]; exact hg.not_isUnit
    obtain ⟨m, hm, hle⟩ := Ideal.exists_le_maximal _ hne
    have hgm : g ∈ m := hle (Ideal.mem_span_singleton_self g)
    have h := Ideal.height_le_ringKrullDim_quotient_add_one hgm
    rwa [MvPolynomial.height_eq_of_isMaximal n m] at h

theorem ringKrullDim_quotient_add_one_of_height_eq_one {k : Type u} [Field k] (A : Type u)
    [CommRing A] [IsDomain A] [Algebra k A] [Algebra.FiniteType k A] (P : Ideal A) [P.IsPrime]
    (hP : P.height = 1) : ringKrullDim (A ⧸ P) + 1 = ringKrullDim A := by
  obtain ⟨n, g, hg, hint⟩ := exists_integral_inj_algHom_of_fg k A
  let R := MvPolynomial (Fin n) k
  let _ : Algebra R A := g.toRingHom.toAlgebra
  have : Algebra.IsIntegral R A := ⟨hint⟩
  have : FaithfulSMul R A := (faithfulSMul_iff_algebraMap_injective R A).mpr hg
  have : IsNoetherianRing A := Algebra.FiniteType.isNoetherianRing k A
  have hdimA : ringKrullDim A = (n : WithBot ℕ∞) := by
    rw [MiyaokaMori.RingTheory.ringKrullDim_eq_of_integral_injective R A,
      MvPolynomial.ringKrullDim_of_isNoetherianRing]; simp
  -- `q = P ∩ R` has height `1`
  have hPne : P ≠ ⊥ := Ideal.ne_bot_of_height_eq_one hP
  have hqne : P.under R ≠ ⊥ := Ideal.under_ne_bot R hPne
  have hq1 : (P.under R).height = 1 := by
    have h := Ideal.height_eq_height_add_of_liesOver_of_hasGoingDown (P.under R) P
    rw [hP] at h
    have hle : (P.under R).height ≤ 1 := h ▸ le_self_add
    have hpos : (P.under R).height ≠ 0 := by
      rwa [Ne, Ideal.height_eq_zero_iff_eq_bot]
    exact le_antisymm hle (Order.one_le_iff_pos.mpr (pos_iff_ne_zero.mpr hpos))
  obtain ⟨x, hxmem, hxp⟩ := Ideal.IsPrime.exists_mem_prime_of_ne_bot inferInstance hqne
  have hqx : P.under R = Ideal.span {x} := Ideal.eq_span_singleton_of_height_eq_one hq1 hxmem hxp
  have h1 : ringKrullDim (A ⧸ P) = ringKrullDim (R ⧸ P.under R) :=
    MiyaokaMori.RingTheory.ringKrullDim_eq_of_integral_injective (R ⧸ P.under R) (A ⧸ P)
  rw [h1, hdimA, hqx]
  exact MvPolynomial.ringKrullDim_quotient_span_prime_add_one n x hxp

end
