import MiyaokaMori.Prelude
import MiyaokaMori.RingTheory.Dimension.FiberFiniteHeight

/-! # Finitely many primes over a height-one prime (Stacks 02MA)

Stacks 02MA: let `A ⊂ B` be an extension of domains, `A` Noetherian, `B` of finite type and
algebraic over `A`, and `𝔭` a height-one prime of `A`. Then there are only finitely many primes of
`B` lying over `𝔭`, and all of them have height `1`.

Proof:
1. Induction on the number `n` of generators of `B` (simultaneously for all `B`): `B = A[s]`,
   `|s| ≤ n`.
2. `n = 0`: `B = A[1]` (`adjoin ∅ = adjoin {1} = ⊥ = ⊤`), `1` is algebraic over `A`; handled by
   step 4 with `R = A`.
3. `n + 1`: `s = insert x t`, `R := A[t] ⊂ B` is a Noetherian domain, `A ⊂ R` is of finite type,
   algebraic, generated by `≤ n` elements; the induction hypothesis gives finitely many primes `𝔮`
   of `R` over `𝔭`, all of height `1`. `B = R[x]` (`Algebra.adjoin_union_eq_adjoin_adjoin`), `x`
   algebraic over `R`. Every prime `Q` of `B` over `𝔭` lies over some such `𝔮 = Q ∩ R`, so it
   suffices to show for each `𝔮`: finitely many `Q` over `𝔮`, all of height `1`.
4. Single-generator case (`R` Noetherian domain, `B = R[x]` a domain, `x` algebraic, `ht 𝔮 = 1`):
   `FiberFiniteHeight` (3) gives that the fibre ring is finite, (1) gives finiteness, (2) gives
   `ht Q ≤ ht 𝔮 = 1`; `Q ≠ 0` (`Q ∩ R = 𝔮 ≠ 0`) gives `ht Q ≥ 1`.

Reference: Stacks 02MA (the original uses the dimension inequality 02IJ; here 02IJ is avoided, using
only Mathlib's 00OM and the PID `κ(𝔮)[X]`).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000
set_option linter.unusedSectionVars false

universe u

noncomputable section

namespace Ideal

/-- The conclusion in the single-generator case. -/
theorem finite_primesOver_and_height_of_adjoin_singleton {R S : Type*} [CommRing R] [IsDomain R]
    [IsNoetherianRing R] [CommRing S] [IsDomain S] [IsNoetherianRing S] [Algebra R S]
    [FaithfulSMul R S] (x : S) (hx : Algebra.adjoin R {x} = ⊤) (halg : IsAlgebraic R x)
    (𝔮 : Ideal R) [𝔮.IsPrime] (h𝔮 : 𝔮.height = 1) :
    (𝔮.primesOver S).Finite ∧ ∀ Q ∈ 𝔮.primesOver S, Q.height = 1 := by
  have hfin := finite_fiber_of_adjoin_singleton x hx halg 𝔮 h𝔮
  refine ⟨finite_primesOver_of_finite_fiber 𝔮, fun Q ⟨hQ, hQ𝔮⟩ ↦ le_antisymm ?_ ?_⟩
  · exact h𝔮 ▸ height_le_of_liesOver_of_finite_fiber 𝔮 Q
  · rw [Order.one_le_iff_pos, pos_iff_ne_zero, Ne, Ideal.height_eq_zero_iff_eq_bot]
    rintro rfl
    have h1 : 𝔮 = (⊥ : Ideal S).under R := hQ𝔮.over
    rw [Ideal.under_def, Ideal.comap_bot_of_injective _ (FaithfulSMul.algebraMap_injective R S)]
      at h1
    exact Ideal.ne_bot_of_height_eq_one h𝔮 h1

private theorem aux (A : Type u) [CommRing A] [IsDomain A] [IsNoetherianRing A] (p : Ideal A)
    [p.IsPrime] (hp : p.height = 1) (n : ℕ) :
    ∀ (B : Type u) [CommRing B] [IsDomain B] [Algebra A B] [FaithfulSMul A B]
      [Algebra.IsAlgebraic A B] (s : Finset B), s.card ≤ n → Algebra.adjoin A (s : Set B) = ⊤ →
      (p.primesOver B).Finite ∧ ∀ q ∈ p.primesOver B, q.height = 1 := by
  induction n with
  | zero =>
    intro B _ _ _ _ _ s hs hadj
    have hs0 : s = ∅ := Finset.card_eq_zero.mp (Nat.le_zero.mp hs)
    have hB : IsNoetherianRing B :=
      Algebra.FiniteType.isNoetherianRing A B (h := ⟨⟨s, hadj⟩⟩)
    refine finite_primesOver_and_height_of_adjoin_singleton (1 : B) ?_
      (Algebra.IsAlgebraic.isAlgebraic _) p hp
    rw [← hadj, hs0]
    simp
  | succ n ih =>
    intro B _ _ _ _ _ s hs hadj
    have hB : IsNoetherianRing B :=
      Algebra.FiniteType.isNoetherianRing A B (h := ⟨⟨s, hadj⟩⟩)
    by_cases hs' : s.card ≤ n
    · exact ih B s hs' hadj
    obtain ⟨x, hxs⟩ : s.Nonempty := by
      rw [← Finset.card_pos]; omega
    classical
    set t := s.erase x with ht
    have hst : (s : Set B) = (t : Set B) ∪ {x} := by
      rw [ht, Finset.coe_erase]; simp [Set.insert_eq_of_mem (Finset.mem_coe.mpr hxs)]
    let R : Subalgebra A B := Algebra.adjoin A (t : Set B)
    let t' : Finset R := t.attach.image fun y ↦ ⟨y.1, Algebra.subset_adjoin (Finset.mem_coe.mpr y.2)⟩
    have ht' : (t' : Set R) = ((↑) : R → B) ⁻¹' (t : Set B) := by
      ext ⟨y, hy⟩
      simp [t']
    have hcard : t'.card ≤ n := by
      refine Finset.card_image_le.trans ?_
      rw [Finset.card_attach, ht, Finset.card_erase_of_mem hxs]; omega
    have hadjR : Algebra.adjoin A (t' : Set R) = ⊤ := by
      rw [ht']; exact Algebra.adjoin_adjoin_coe_preimage
    have hinjR : Function.Injective (algebraMap A R) := fun a b hab ↦
      FaithfulSMul.algebraMap_injective A B (congrArg Subtype.val hab)
    have : FaithfulSMul A R := (faithfulSMul_iff_algebraMap_injective A R).mpr hinjR
    have : Algebra.IsAlgebraic A R :=
      Algebra.IsAlgebraic.of_injective R.val Subtype.val_injective
    have hR : IsNoetherianRing R :=
      Algebra.FiniteType.isNoetherianRing A R (h := ⟨⟨t', hadjR⟩⟩)
    obtain ⟨hfinR, hhtR⟩ := ih R t' hcard hadjR
    have hxtop : Algebra.adjoin R {x} = ⊤ := by
      have h1 := Algebra.adjoin_union_eq_adjoin_adjoin A (t : Set B) {x}
      rw [← hst, hadj] at h1
      refine top_unique fun b _ ↦ ?_
      have : b ∈ (Algebra.adjoin R {x}).restrictScalars A := h1 ▸ Algebra.mem_top
      exact this
    have halgx : IsAlgebraic R x :=
      (Algebra.IsAlgebraic.isAlgebraic (R := A) x).extendScalars hinjR
    have key : ∀ 𝔮 ∈ p.primesOver R,
        (𝔮.primesOver B).Finite ∧ ∀ Q ∈ 𝔮.primesOver B, Q.height = 1 := by
      intro 𝔮 h𝔮
      have := h𝔮.1
      exact finite_primesOver_and_height_of_adjoin_singleton x hxtop halgx 𝔮 (hhtR 𝔮 h𝔮)
    have hcover : ∀ Q ∈ p.primesOver B, Q.under R ∈ p.primesOver R ∧
        Q ∈ (Q.under R).primesOver B := by
      rintro Q ⟨hQ, hQp⟩
      refine ⟨⟨inferInstance, ⟨?_⟩⟩, hQ, ⟨rfl⟩⟩
      rw [Ideal.under_under, ← hQp.over]
    refine ⟨?_, fun Q hQ ↦ (key _ (hcover Q hQ).1).2 Q (hcover Q hQ).2⟩
    refine (hfinR.biUnion fun 𝔮 h𝔮 ↦ (key 𝔮 h𝔮).1).subset fun Q hQ ↦ ?_
    exact Set.mem_biUnion (hcover Q hQ).1 (hcover Q hQ).2

/-- Stacks 02MA. -/
theorem finite_primesOver_and_height_eq_one {A B : Type u} [CommRing A] [CommRing B]
    [IsDomain A] [IsDomain B] [IsNoetherianRing A] [Algebra A B] [FaithfulSMul A B]
    [Algebra.FiniteType A B] [Algebra.IsAlgebraic A B] (p : Ideal A) [p.IsPrime]
    (hp : p.height = 1) :
    (p.primesOver B).Finite ∧ ∀ q ∈ p.primesOver B, q.height = 1 := by
  obtain ⟨s, hs⟩ := (‹Algebra.FiniteType A B›).out
  exact aux A p hp s.card B s le_rfl hs

end Ideal

end
