import MiyaokaMori.Prelude
import Mathlib.RingTheory.Etale.Basic
import Mathlib.RingTheory.Flat.TorsionFree
import Mathlib.RingTheory.Ideal.MinimalPrime.Localization
import Mathlib.RingTheory.Nakayama
import Mathlib.RingTheory.RegularLocalRing.Defs
import Mathlib.RingTheory.RingHom.StandardSmooth
import Mathlib.RingTheory.Unramified.LocalRing

/-! # Localizations of an étale algebra over a PID are domains

The localization of an étale algebra over a PID at every prime is a domain and a principal ideal ring (hence
regular and integrally closed). This is the algebraic core of "the local rings of a standard smooth algebra
of relative dimension `≤ 1` over a field are domains", **without assuming that `S` is a domain** (the argument
of `AlgebraicGeometry.Scheme.standardSmoothCurve_isRegularLocalRing_atPrime` requires `[IsDomain S]` and therefore cannot be
used to prove integrality of a curve without circularity; here that hypothesis is removed).

Proof: let `p = q ∩ A = (π)`. Unramified ⇒ the maximal ideal of `S_q` is `π S_q`. If `π = 0` then `S_q` is a
field; if `π ≠ 0` then `π` is a nonzerodivisor of `A`, `S_q` is flat over `A`, so the image of `π` is a
nonzerodivisor; a Noetherian local ring whose maximal ideal is generated by a nonzerodivisor is a domain
(a minimal prime `P ⊆ (x)` with `x ∉ P` gives `P = xP`, then Nakayama).

References: the one-dimensional case of Stacks 056S (smooth ⇒ regular); Stacks 00PD (characterization of DVRs).
-/

set_option autoImplicit false

universe u v

open IsLocalRing

/-- A Noetherian local ring whose maximal ideal is generated by a single nonzerodivisor is a domain. -/
theorem IsLocalRing.isDomain_of_maximalIdeal_eq_span_of_mem_nonZeroDivisors
    (R : Type u) [CommRing R] [IsLocalRing R] [IsNoetherianRing R] (x : R)
    (hx : x ∈ nonZeroDivisors R) (hm : maximalIdeal R = Ideal.span {x}) : IsDomain R := by
  obtain ⟨P, hP, -⟩ := Ideal.exists_minimalPrimes_le (I := (⊥ : Ideal R)) (J := maximalIdeal R) bot_le
  have hPprime : P.IsPrime := hP.1.1
  have hxP : x ∉ P := fun h =>
    Set.disjoint_left.mp (Ideal.disjoint_nonZeroDivisors_of_mem_minimalPrimes hP) h hx
  have hle : P ≤ maximalIdeal R • P := by
    intro a ha
    have ham : a ∈ Ideal.span {x} := hm ▸ IsLocalRing.le_maximalIdeal hPprime.ne_top ha
    obtain ⟨r, rfl⟩ := Ideal.mem_span_singleton'.mp ham
    have hr : r ∈ P := (hPprime.mem_or_mem ha).resolve_right hxP
    rw [mul_comm]
    exact Submodule.smul_mem_smul (hm ▸ Ideal.mem_span_singleton_self x) hr
  have hbot : P = ⊥ :=
    Submodule.eq_bot_of_le_smul_of_le_jacobson_bot (maximalIdeal R) P
      (IsNoetherian.noetherian P) hle (IsLocalRing.maximalIdeal_le_jacobson ⊥)
  rw [hbot] at hPprime
  have : NoZeroDivisors R :=
    ⟨fun {a b} h => by simpa using hPprime.mem_or_mem (show a * b ∈ (⊥ : Ideal R) by simpa using h)⟩
  exact NoZeroDivisors.to_isDomain R

/-- An étale algebra over a PID: the localization at every prime is a domain and a principal ideal ring. `S` is
not assumed to be a domain. -/
theorem Algebra.Etale.localization_isDomain_and_isPrincipalIdealRing
    (A : Type u) (S : Type v) [CommRing A] [CommRing S] [IsDomain A] [IsPrincipalIdealRing A]
    [Algebra A S] [Algebra.Etale A S] (q : Ideal S) [q.IsPrime] :
    IsDomain (Localization.AtPrime q) ∧ IsPrincipalIdealRing (Localization.AtPrime q) := by
  have : IsNoetherianRing S := Algebra.EssFiniteType.isNoetherianRing A S
  let p := q.under A
  have : p.IsPrime := Ideal.IsPrime.under A q
  have : q.LiesOver p := ⟨rfl⟩
  let _ := Localization.AtPrime.algebraOfLiesOver p q
  have hmap : p.map (algebraMap A (Localization.AtPrime q)) =
      maximalIdeal (Localization.AtPrime q) :=
    ((Algebra.isUnramifiedAt_iff_map_eq A p q).mp inferInstance).2
  obtain ⟨π, hπ⟩ := (IsPrincipalIdealRing.principal p).principal
  have hspan : maximalIdeal (Localization.AtPrime q) =
      Ideal.span {algebraMap A (Localization.AtPrime q) π} := by
    rw [← hmap, hπ, Ideal.submodule_span_eq, Ideal.map_span, Set.image_singleton]
  have hdom : IsDomain (Localization.AtPrime q) := by
    by_cases h0 : π = 0
    · have : maximalIdeal (Localization.AtPrime q) = ⊥ := by
        rw [hspan, h0, map_zero, Ideal.span_singleton_eq_bot]
      exact (IsLocalRing.isField_iff_maximalIdeal_eq.mpr this).isDomain
    · have : Module.Flat A S := Algebra.Smooth.flat A S
      have : Module.Flat A (Localization.AtPrime q) :=
        Module.Flat.trans A S (Localization.AtPrime q)
      have hreg : IsSMulRegular (Localization.AtPrime q) π :=
        Module.Flat.isSMulRegular_of_nonZeroDivisors (mem_nonZeroDivisors_of_ne_zero h0)
      refine IsLocalRing.isDomain_of_maximalIdeal_eq_span_of_mem_nonZeroDivisors _ _ ?_ hspan
      rw [mem_nonZeroDivisors_iff_right]
      intro z hz
      apply hreg
      simpa [Algebra.smul_def, mul_comm] using hz
  refine ⟨hdom, ?_⟩
  have hm : (maximalIdeal (Localization.AtPrime q)).IsPrincipal := by
    rw [← hmap]; infer_instance
  exact ((tfae_of_isNoetherianRing_of_isLocalRing_of_isDomain
    (Localization.AtPrime q)).out 4 0).mp hm

/-- A standard smooth algebra of relative dimension `n ≤ 1` over a field: the localization at every prime is a
domain and a principal ideal ring. `S` is not assumed to be a domain. -/
theorem RingHom.IsStandardSmoothOfRelativeDimension.localization_isDomain_and_isPrincipalIdealRing
    {K : Type u} {S : Type v} [Field K] [CommRing S] {n : ℕ} {f : K →+* S}
    (hf : f.IsStandardSmoothOfRelativeDimension n) (hn : n ≤ 1) (q : Ideal S) [q.IsPrime] :
    IsDomain (Localization.AtPrime q) ∧ IsPrincipalIdealRing (Localization.AtPrime q) := by
  obtain ⟨g, -, hg⟩ := hf.exists_etale_mvPolynomial
  let _ : Algebra (MvPolynomial (Fin n) K) S := g.toAlgebra
  have : Algebra.Etale (MvPolynomial (Fin n) K) S := hg.toAlgebra
  have : IsPrincipalIdealRing (MvPolynomial (Fin n) K) := by
    interval_cases n
    · exact IsPrincipalIdealRing.of_surjective
        (MvPolynomial.isEmptyAlgEquiv K (Fin 0)).symm.toRingHom
        (MvPolynomial.isEmptyAlgEquiv K (Fin 0)).symm.surjective
    · exact IsPrincipalIdealRing.of_surjective
        (MvPolynomial.uniqueAlgEquiv K (Fin 1)).symm.toRingHom
        (MvPolynomial.uniqueAlgEquiv K (Fin 1)).symm.surjective
  exact Algebra.Etale.localization_isDomain_and_isPrincipalIdealRing (MvPolynomial (Fin n) K) S q
