import MiyaokaMori.Prelude
import Mathlib.RingTheory.RegularLocalRing.Defs
import MiyaokaMori.RingTheory.RegularLocalRing.RegularLocalRingQuotientOfInfSqLe
import MiyaokaMori.RingTheory.RegularLocalRing.Stacks00np

/-! # Regularity of a quotient of a regular local ring by an ideal with `I ∩ 𝔪² ⊆ 𝔪I`

**Converse of `IsRegularLocalRing.quotient_of_inf_sq_le`.** Let `(P, m, κ)` be a regular local
ring and `K` an ideal with `P/K` again a regular local ring. Then `K ∩ m² ≤ m·K`, i.e. the natural
map `K/mK → m/m²` is injective (equivalently: `K` is generated by part of a regular system of
parameters — Stacks 00NU, Matsumura *Commutative Ring Theory* Thm. 14.2).

Source: Stacks 00NU (regular local ring, `R/I` regular ⇒ `I` is generated by a subset of a minimal
system of generators of `m`); Matsumura CRT Thm. 14.2. The proof below is self-contained.

## Proof

The Lean proof follows the outline below, except that steps 3–4 are organised as a **reduced
statement** `IsRegularLocalRing.eq_bot_of_le_sq_of_quotient` (`K ≤ m²` and `P/K` regular ⇒ `K = ⊥`,
via Nakayama and the dimension drop along a nonzerodivisor), applied to `P/J` and `K/J`.

Write `m = maximalIdeal P`, `κ = P/m`, `W := cotangentImage K ⊆ m/m²` (the image of `K` in the
cotangent space, `IsRegularLocalRing.cotangentImage` in
`MiyaokaMori.Stacks.Algebra.RegularLocalRingQuotientOfInfSqLe`), `r := dim_κ W`. `K ≠ ⊤` since `P/K`
is local (nontrivial), so `K ≤ m`.

1. **Lift a basis of `W`.** Choose `x₁, …, x_r ∈ K` whose classes `x̄ᵢ ∈ m/m²` form a basis of
   `W` (`exists_linearIndependent` + `mem_cotangentImage_iff`, exactly as in
   `spanFinrank_le_finrank_cotangentImage`). Put `J := (x₁, …, x_r) ≤ K`.
2. **`J ∩ m² ≤ mJ`** (linear algebra). If `b = Σ aᵢxᵢ ∈ m²`, then `Σ āᵢ x̄ᵢ = 0` in `m/m²`
   (`toCotangent` kills `m²`, and `toCotangent (aᵢ xᵢ) = āᵢ • x̄ᵢ`); linear independence gives
   `āᵢ = 0`, i.e. `aᵢ ∈ m`, hence `b ∈ mJ`.
3. **`P/J` is regular local** of the same dimension as `P/K`:
   `IsRegularLocalRing.quotient_of_inf_sq_le J` gives regularity. For the dimension: for a
   regular local ring the dimension equals the embedding dimension
   (`IsRegularLocalRing.spanFinrank_maximalIdeal`, `spanFinrank_maximalIdeal_eq_finrank_cotangentSpace`),
   and for both quotients the cotangent space is `(m/m²)/W'` with `W' = cotangentImage J =
   cotangentImage K = W` (the image of `J` in `m/m²` is spanned by the `x̄ᵢ`, i.e. is `W`;
   the cotangent space of `P/L`, `L ≤ m`, is `m/(L + m²) ≅ (m/m²)/cotangentImage L`
   — this identification is what `spanFinrank_maximalIdeal_quotient_le` proves in one direction;
   the equality `finrank (CotangentSpace (P/L)) = finrank ((m/m²)/cotangentImage L)` needs the
   reverse inequality, obtained by lifting a minimal generating set of `m_{P/L}` to `m` and
   observing that together with lifts of a basis of `W` it generates `m`). Hence
   `dim P/J = dim P − r = dim P/K`.
4. **`K = J`.** `P/J` is a domain (`IsRegularLocalRing.isDomain`, Stacks 00NP). Suppose
   `K ≠ J`; take `y ∈ K \ J`, `ȳ ≠ 0` in `P/J`, a nonzerodivisor. Then
   `dim (P/J)/(ȳ) + 1 ≤ dim P/J` (`ringKrullDim_quotient_succ_le_of_nonZeroDivisor`) and
   `dim P/K = dim (P/J)/(K/J) ≤ dim (P/J)/(ȳ)` (`ringKrullDim_quotient_le`, since `(ȳ) ≤ K/J`,
   through `DoubleQuot.quotQuotEquivQuotSup` / `Ideal.quotEquivOfEq` and
   `ringKrullDim_eq_of_ringEquiv`). So `dim P/K + 1 ≤ dim P/J = dim P/K`, impossible because
   `dim P/K < ⊤` (Noetherian local ring: `ringKrullDim_lt_top` via `FiniteRingKrullDim`; or simply
   `ringKrullDim (P/K) = spanFinrank m_{P/K} : ℕ` by regularity) and `≠ ⊥` (nontrivial ring).
5. Therefore `K ∩ m² = J ∩ m² ≤ mJ = mK`.

Edge cases: `K = ⊥` — trivial. `K = m` — `P/m` is a field, regular of dimension `0`;
`m ∩ m² = m² = m·m`. `P` a field — `m = ⊥`, `K = ⊥`. Everything is consistent with the statement.

Size: about 200 lines. Used by
`Algebra.FormallySmooth.of_isRegularLocalRing_of_surjective`
(`MiyaokaMori.Stacks.Algebra.SmoothOfRegularLocalizationsOverPerfectField`).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open IsLocalRing Submodule

noncomputable section

/-- **Reduced form.** `P` regular local, `K ≤ m²`, `P/K` regular local ⇒ `K = ⊥`.
Proof: lifting a minimal generating set of `m/K` to `m` generates `m` modulo `m²`, hence generates
`m` (Nakayama), so `dim P = μ(m) ≤ μ(m/K) = dim P/K`; but if `0 ≠ y ∈ K` then `y` is a
nonzerodivisor of the domain `P` and `dim P/K ≤ dim P/(y) ≤ dim P − 1`. -/
theorem IsRegularLocalRing.eq_bot_of_le_sq_of_quotient {P : Type u} [CommRing P]
    [IsRegularLocalRing P] (K : Ideal P) [IsRegularLocalRing (P ⧸ K)]
    (hK : K ≤ maximalIdeal P ^ 2) : K = ⊥ := by
  classical
  -- Step 1: `μ(m) ≤ μ(m_{P/K})`
  have hle : (maximalIdeal P).spanFinrank ≤ (maximalIdeal (P ⧸ K)).spanFinrank := by
    obtain ⟨s, hs, hspan⟩ :=
      (IsNoetherian.noetherian (maximalIdeal (P ⧸ K))).exists_span_finset_card_eq_spanFinrank
    have hsm : ∀ z ∈ s, z ∈ maximalIdeal (P ⧸ K) := fun z hz =>
      hspan ▸ Submodule.subset_span (Finset.mem_coe.mpr hz)
    have hlift : ∀ z ∈ s, ∃ y : P, Ideal.Quotient.mk K y = z := fun z _ =>
      Ideal.Quotient.mk_surjective z
    choose! g hg using hlift
    set t : Finset P := s.image g with ht
    have himage : (Ideal.Quotient.mk K) '' (t : Set P) = (s : Set (P ⧸ K)) := by
      ext z
      constructor
      · rintro ⟨w, hw, rfl⟩
        rw [ht, Finset.coe_image] at hw
        obtain ⟨z', hz', rfl⟩ := hw
        rw [hg z' hz']
        exact hz'
      · intro hz
        exact ⟨g z, by rw [ht, Finset.coe_image]; exact ⟨z, hz, rfl⟩, hg z hz⟩
    have hmapt : (Ideal.span (t : Set P)).map (Ideal.Quotient.mk K) = maximalIdeal (P ⧸ K) := by
      rw [Ideal.map_span, himage]
      exact hspan
    -- `m ≤ span t ⊔ m • m`
    have hm : maximalIdeal P ≤ Ideal.span (t : Set P) ⊔ maximalIdeal P • maximalIdeal P := by
      intro x hx
      have hx' : x ∈ Ideal.comap (Ideal.Quotient.mk K)
          ((Ideal.span (t : Set P)).map (Ideal.Quotient.mk K)) := by
        rw [hmapt, ← IsLocalRing.map_maximalIdeal_of_surjective (Ideal.Quotient.mk K)
          Ideal.Quotient.mk_surjective]
        exact Ideal.mem_map_of_mem _ hx
      rw [Ideal.comap_map_of_surjective _ Ideal.Quotient.mk_surjective,
        ← RingHom.ker_eq_comap_bot, Ideal.mk_ker] at hx'
      have hK' : K ≤ maximalIdeal P • maximalIdeal P := by
        rw [Ideal.smul_eq_mul, ← pow_two]; exact hK
      exact sup_le_sup_left hK' _ hx'
    have hNak : maximalIdeal P ≤ Ideal.span (t : Set P) :=
      Submodule.le_of_le_smul_of_le_jacobson_bot (IsNoetherian.noetherian _)
        (le_of_eq (IsLocalRing.jacobson_eq_maximalIdeal ⊥ bot_ne_top).symm) hm
    have htm : Ideal.span (t : Set P) ≤ maximalIdeal P := by
      refine Ideal.span_le.mpr fun y hy => ?_
      rw [ht, Finset.coe_image] at hy
      obtain ⟨z, hz, rfl⟩ := hy
      by_contra hcon
      have hu : IsUnit (g z) := IsLocalRing.notMem_maximalIdeal.mp hcon
      have hu' := hu.map (Ideal.Quotient.mk K)
      rw [hg z hz] at hu'
      exact (mem_nonunits_iff.mp ((mem_maximalIdeal z).mp (hsm z hz))) hu'
    have hspan_eq : Ideal.span (t : Set P) = maximalIdeal P := le_antisymm htm hNak
    calc (maximalIdeal P).spanFinrank = (Ideal.span (t : Set P)).spanFinrank := by rw [hspan_eq]
      _ ≤ (t : Set P).ncard := Submodule.spanFinrank_span_le_ncard_of_finite (Finset.finite_toSet t)
      _ = t.card := Set.ncard_coe_finset t
      _ ≤ s.card := Finset.card_image_le
      _ = (maximalIdeal (P ⧸ K)).spanFinrank := hs
  -- Step 2: dimension drop
  by_contra hne
  obtain ⟨y, hyK, hy0⟩ := (Submodule.ne_bot_iff K).mp hne
  have : IsDomain P := IsRegularLocalRing.isDomain P
  have h1 := ringKrullDim_quotient_succ_le_of_nonZeroDivisor (mem_nonZeroDivisors_of_ne_zero hy0)
  have hyK' : Ideal.span {y} ≤ K := (Ideal.span_singleton_le_iff_mem _).mpr hyK
  have h2 : ringKrullDim (P ⧸ K) ≤ ringKrullDim (P ⧸ Ideal.span {y}) := by
    let e : (P ⧸ Ideal.span {y}) ⧸ K.map (Ideal.Quotient.mk (Ideal.span {y})) ≃+* P ⧸ K :=
      (DoubleQuot.quotQuotEquivQuotSup (Ideal.span {y}) K).trans
        (Ideal.quotEquivOfEq (sup_eq_right.mpr hyK'))
    rw [← ringKrullDim_eq_of_ringEquiv e]
    exact ringKrullDim_quotient_le _
  have hdP : ((maximalIdeal P).spanFinrank : WithBot ℕ∞) = ringKrullDim P :=
    IsRegularLocalRing.spanFinrank_maximalIdeal
  have hdPK : ((maximalIdeal (P ⧸ K)).spanFinrank : WithBot ℕ∞) = ringKrullDim (P ⧸ K) :=
    IsRegularLocalRing.spanFinrank_maximalIdeal
  have h3 : (((maximalIdeal (P ⧸ K)).spanFinrank + 1 : ℕ) : WithBot ℕ∞) ≤
      ((maximalIdeal P).spanFinrank : WithBot ℕ∞) := by
    rw [hdP]
    push_cast
    rw [hdPK]
    exact le_trans (add_le_add h2 (le_refl (1 : WithBot ℕ∞))) h1
  have h4 : (maximalIdeal (P ⧸ K)).spanFinrank + 1 ≤ (maximalIdeal P).spanFinrank := by
    exact_mod_cast h3
  omega

/-- **Stacks 00NU, generator-free form.** `P` regular local, `P/K` regular local ⇒
`K ∩ m² ≤ m·K`. NL proof in the module docstring. -/
theorem IsRegularLocalRing.ker_inf_maximalIdeal_sq_le_of_quotient {P : Type u} [CommRing P]
    [IsRegularLocalRing P] (K : Ideal P) [IsRegularLocalRing (P ⧸ K)] :
    K ⊓ IsLocalRing.maximalIdeal P ^ 2 ≤ IsLocalRing.maximalIdeal P * K := by
  classical
  set m := maximalIdeal P with hm
  have hKtop : K ≠ ⊤ := fun h => by
    have : Subsingleton (P ⧸ K) := Ideal.Quotient.subsingleton_iff.mpr h
    exact false_of_nontrivial_of_subsingleton (P ⧸ K)
  have hKm : K ≤ m := le_maximalIdeal hKtop
  set W := IsRegularLocalRing.cotangentImage K with hW
  let bs := Module.finBasis (ResidueField P) W
  set r := Module.finrank (ResidueField P) W
  -- Step 1: lift a basis of `W` to elements of `K`
  have hlift : ∀ i : Fin r, ∃ x : m, (x : P) ∈ K ∧ m.toCotangent x = (bs i : CotangentSpace P) :=
    fun i => (IsRegularLocalRing.mem_cotangentImage_iff K).mp (bs i).2
  choose x hxK hxc using hlift
  set J : Ideal P := Ideal.span (Set.range fun i => (x i : P)) with hJ
  have hJK : J ≤ K := Ideal.span_le.mpr (by rintro _ ⟨i, rfl⟩; exact hxK i)
  have hJm : J ≤ m := hJK.trans hKm
  have hli : LinearIndependent (ResidueField P) fun i => (bs i : CotangentSpace P) :=
    bs.linearIndependent.map' W.subtype W.ker_subtype
  -- Step 2a: `J ∩ m² ≤ m J`
  have hJinf : J ⊓ m ^ 2 ≤ m * J := by
    rintro z ⟨hzJ, hzm2⟩
    obtain ⟨a, rfl⟩ := (Submodule.mem_span_range_iff_exists_fun P).mp hzJ
    have hz0 : m.toCotangent ⟨∑ i, a i • (x i : P), hJm hzJ⟩ = 0 := by
      rw [Ideal.toCotangent_eq_zero]; exact hzm2
    have hsum : m.toCotangent ⟨∑ i, a i • (x i : P), hJm hzJ⟩ =
        ∑ i, (residue P (a i)) • (bs i : CotangentSpace P) := by
      have : (⟨∑ i, a i • (x i : P), hJm hzJ⟩ : m) = ∑ i, a i • x i := by
        ext; simp
      rw [this, map_sum]
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [map_smul, hxc i, ← IsScalarTower.algebraMap_smul (ResidueField P) (a i),
        ResidueField.algebraMap_eq]
    have hzero : ∀ i, residue P (a i) = 0 :=
      Fintype.linearIndependent_iff.mp hli _ (hsum.symm.trans hz0)
    refine Ideal.sum_mem _ fun i _ => ?_
    rw [smul_eq_mul]
    exact Ideal.mul_mem_mul ((residue_eq_zero_iff _).mp (hzero i)) (Ideal.subset_span ⟨i, rfl⟩)
  -- Step 2b: `K ≤ J ⊔ m²`
  have hKJ : K ≤ J ⊔ m ^ 2 := by
    intro k hk
    have hkW : m.toCotangent ⟨k, hKm hk⟩ ∈ W :=
      (IsRegularLocalRing.mem_cotangentImage_iff K).mpr ⟨⟨k, hKm hk⟩, hk, rfl⟩
    set w : W := ⟨_, hkW⟩ with hw
    have hrepr := bs.sum_repr w
    have hc : ∀ i, ∃ c : P, residue P c = bs.repr w i := fun i => residue_surjective _
    choose c hc using hc
    have hmem : k - ∑ i, c i * (x i : P) ∈ m :=
      m.sub_mem (hKm hk) (Ideal.sum_mem _ fun i _ => Ideal.mul_mem_left _ _ (x i).2)
    have hdiff : k - ∑ i, c i * (x i : P) ∈ m ^ 2 := by
      rw [← Ideal.toCotangent_eq_zero m ⟨_, hmem⟩]
      have : (⟨k - ∑ i, c i * (x i : P), hmem⟩ : m) = ⟨k, hKm hk⟩ - ∑ i, c i • x i := by
        ext; simp
      rw [this, map_sub, map_sum]
      have h2 : ∑ i, m.toCotangent (c i • x i) =
          ∑ i, (bs.repr w i) • (bs i : CotangentSpace P) := by
        refine Finset.sum_congr rfl fun i _ => ?_
        rw [map_smul, hxc i, ← hc i, ← IsScalarTower.algebraMap_smul (ResidueField P) (c i),
          ResidueField.algebraMap_eq]
      rw [h2, sub_eq_zero]
      have h3 := congrArg Subtype.val hrepr
      rw [Submodule.coe_sum] at h3
      simp only [Submodule.coe_smul] at h3
      exact h3.symm
    have : k = (∑ i, c i * (x i : P)) + (k - ∑ i, c i * (x i : P)) := by ring
    rw [this]
    exact Submodule.add_mem_sup
      (Ideal.sum_mem _ fun i _ => Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨i, rfl⟩)) hdiff
  -- Step 3: pass to `P/J`
  have hJtop : J ≠ ⊤ := fun h => hKtop (top_le_iff.mp (h ▸ hJK))
  have hPJ : IsRegularLocalRing (P ⧸ J) := IsRegularLocalRing.quotient_of_inf_sq_le J hJtop hJinf
  set K' : Ideal (P ⧸ J) := K.map (Ideal.Quotient.mk J) with hK'
  have hK'sq : K' ≤ maximalIdeal (P ⧸ J) ^ 2 := by
    rw [← IsLocalRing.map_maximalIdeal_of_surjective (Ideal.Quotient.mk J)
      Ideal.Quotient.mk_surjective, ← Ideal.map_pow]
    calc K' ≤ (J ⊔ m ^ 2).map (Ideal.Quotient.mk J) := Ideal.map_mono hKJ
      _ = (m ^ 2).map (Ideal.Quotient.mk J) := by
        rw [Ideal.map_sup, Ideal.map_quotient_self, bot_sup_eq]
  let e : (P ⧸ J) ⧸ K' ≃+* P ⧸ K :=
    (DoubleQuot.quotQuotEquivQuotSup J K).trans (Ideal.quotEquivOfEq (sup_eq_right.mpr hJK))
  have : IsRegularLocalRing ((P ⧸ J) ⧸ K') := IsRegularLocalRing.of_ringEquiv e.symm
  have hK'bot : K' = ⊥ := IsRegularLocalRing.eq_bot_of_le_sq_of_quotient K' hK'sq
  have hKJ' : K ≤ J := by
    have := (Ideal.map_eq_bot_iff_le_ker (Ideal.Quotient.mk J)).mp hK'bot
    rwa [Ideal.mk_ker] at this
  rw [le_antisymm hKJ' hJK]
  exact hJinf

end
