import MiyaokaMori.Prelude
import MiyaokaMori.Paper.S2WeightedJets.Jets.BasedJetAlgebra
import MiyaokaMori.RingTheory.RegularLocalRing.Stacks00ln
import MiyaokaMori.RingTheory.RegularLocalRing.Stacks00nqRegularSequence
import MiyaokaMori.AlgebraicGeometry.Chow.Cycles.Stacks02qt

/-! # Stacks 00NO: the associated graded ring of a regular local ring

Stacks 00NO: for a regular local ring `(R, m, κ)` of dimension `d`, the associated graded ring
`⊕ m^n/m^{n+1}` is `≅ κ[X_1,…,X_d]`; in concrete form: every homogeneous polynomial relation among a minimal
system of generators `x_1..x_d` of `m` has all coefficients in `m`.

References: Stacks 00NO; the proof of 0AGQ.

Route (not via Hilbert–Samuel 00KQ/00K3): "a minimal system of generators of `m` is a regular sequence"
(Stacks 00NQ, `IsRegularLocalRing.isWeaklyRegular_of_span_eq_maximalIdeal`) + "a regular sequence is
quasi-regular" (Stacks 00LN(1), `RingTheory.Sequence.IsWeaklyRegular.isQuasiRegularFamily`), with `J = m`.
The same route in textbooks: Hartshorne II Thm 8.21A(e) + Matsumura Thm 16.2(i).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- In a Noetherian local ring, if `spanFinrank m = d` then `m` is generated by some `x : Fin d → R`. -/
theorem IsLocalRing.exists_fun_span_range_eq_maximalIdeal (R : Type*) [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] (d : ℕ) (hd : (IsLocalRing.maximalIdeal R).spanFinrank = d) :
    ∃ x : Fin d → R, Ideal.span (Set.range x) = IsLocalRing.maximalIdeal R := by
  obtain ⟨s, hs, hspan⟩ :=
    (IsNoetherian.noetherian (IsLocalRing.maximalIdeal R)).exists_span_finset_card_eq_spanFinrank
  refine ⟨fun i => ((s.equivFinOfCardEq (hs.trans hd)).symm i : R), ?_⟩
  have hr : Set.range (fun i => ((s.equivFinOfCardEq (hs.trans hd)).symm i : R)) = (s : Set R) := by
    ext y
    constructor
    · rintro ⟨i, rfl⟩
      exact ((s.equivFinOfCardEq (hs.trans hd)).symm i).2
    · intro hy
      exact ⟨s.equivFinOfCardEq (hs.trans hd) ⟨y, hy⟩, by simp⟩
  rw [hr]
  exact hspan

theorem IsRegularLocalRing.initialForms_algebraicallyIndependent (R : Type u) [CommRing R]
    [IsRegularLocalRing R] (d : ℕ) (hd : ringKrullDim R = d) :
    ∃ x : Fin d → R, (∀ i, x i ∈ IsLocalRing.maximalIdeal R) ∧
      Ideal.span (Set.range x) = IsLocalRing.maximalIdeal R ∧
      ∀ (n : ℕ) (F : MvPolynomial (Fin d) R), F.IsHomogeneous n →
        MvPolynomial.eval x F ∈ IsLocalRing.maximalIdeal R ^ (n + 1) →
        ∀ m, F.coeff m ∈ IsLocalRing.maximalIdeal R := by
  obtain ⟨x, hx⟩ := IsLocalRing.exists_fun_span_range_eq_maximalIdeal R d (by
    have := IsRegularLocalRing.spanFinrank_maximalIdeal (R := R)
    rw [hd] at this
    exact_mod_cast this)
  refine ⟨x, fun i => hx ▸ Ideal.subset_span ⟨i, rfl⟩, hx, fun n F hF hmem => ?_⟩
  have hQ : IsQuasiRegularFamily x :=
    (IsRegularLocalRing.isWeaklyRegular_of_span_eq_maximalIdeal hd x hx).isQuasiRegularFamily
  have := hQ n F hF (by rw [hx]; exact hmem)
  rwa [hx] at this

end
