import MiyaokaMori.Prelude
import MiyaokaMori.RingTheory.RegularLocalRing.Stacks00np
import MiyaokaMori.RingTheory.RegularLocalRing.Stacks00nq

/-! # Stacks 00NQ: a minimal system of generators is a regular sequence

The full form of Stacks 00NQ: in a regular local ring `R` of dimension `d`, any `d` generators `x_1..x_d` of the
maximal ideal `m` form an `R`-regular sequence (Mathlib's `RingTheory.Sequence.IsWeaklyRegular R (List.ofFn x)`;
the elements lie in `m`, so it is also `IsRegular`).

Reference: Stacks 00NQ (algebra-lemma-regular-ring-CM): induction on `d`; `x_1 ∉ m²` (otherwise `m` is generated
by `d−1` elements), `R` is a domain (00NP) so `x_1` is a nonzerodivisor, `R/(x_1)` is a regular local ring of
dimension `d−1` (the single step 00NQ) whose maximal ideal is generated by the images of `x_2..x_d`; induct.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry Pointwise

noncomputable section

/-- **No element of a minimal generating set lies in `m²`.**

Reference: the proof of Stacks 00NQ ("`x_1 ∉ m²`, otherwise `m/m²` is spanned by `d−1` elements"); Matsumura Thm
2.3.

Statement: `R` a Noetherian local ring, `x : Fin n → R`, `span (range x) = m`, `spanFinrank m = n`; then every
`x i ∉ m ^ 2`.

Proof: suppose `x i ∈ m²`. Let `N := span (x '' {j | j ≠ i})`.
1. `m = span (range x) ≤ N ⊔ span {x i} ≤ N ⊔ m²` (`range x = insert (x i) (x '' {j | j ≠ i})`, `Ideal.span_insert`).
2. `m² = m • m` (`pow_two`, `smul_eq_mul`), `N ≤ m`. Nakayama:
   `Submodule.le_of_le_smul_of_le_jacobson_bot (I := m) (N := N) (N' := m) m.fg_of_isNoetherianRing
   (IsLocalRing.maximalIdeal_le_jacobson ⊥) : m ≤ N ⊔ m • m → m ≤ N`, so `m = N`.
3. `N` is generated by `x '' {j | j ≠ i}`, a finite set of at most `n − 1` elements (`Set.ncard_image_le`; the
   `ncard` of `{j | j ≠ i}` is `n − 1`, and `n ≥ 1` since `i : Fin n`), so
   `Submodule.spanFinrank_span_le_ncard_of_finite` gives `spanFinrank m ≤ n − 1 < n`, contradicting `hn`.

Edge cases: for `n = 0`, `Fin 0` is empty and the conclusion is vacuous. `x` need not be injective (if `x i = x j`,
`N` still contains `x i` and step 2 goes through). -/
theorem IsLocalRing.notMem_sq_of_span_range_eq_maximalIdeal {R : Type*} [CommRing R]
    [IsLocalRing R] [IsNoetherianRing R] {n : ℕ} (x : Fin n → R)
    (hx : Ideal.span (Set.range x) = IsLocalRing.maximalIdeal R)
    (hn : (IsLocalRing.maximalIdeal R).spanFinrank = n) (i : Fin n) :
    x i ∉ IsLocalRing.maximalIdeal R ^ 2 := by
  classical
  intro hmem
  have hrange : Set.range x = insert (x i) (((Finset.univ.erase i).image x : Finset R) : Set R) := by
    ext y
    constructor
    · rintro ⟨j, rfl⟩
      by_cases h : j = i
      · exact Or.inl (h ▸ rfl)
      · exact Or.inr (by simpa using ⟨j, h, rfl⟩)
    · rintro (rfl | hy)
      · exact ⟨i, rfl⟩
      · obtain ⟨j, -, rfl⟩ := by simpa using hy
        exact ⟨j, rfl⟩
  have hle : IsLocalRing.maximalIdeal R ≤
      Ideal.span (((Finset.univ.erase i).image x : Finset R) : Set R) ⊔
        IsLocalRing.maximalIdeal R • IsLocalRing.maximalIdeal R := by
    conv_lhs => rw [← hx, hrange, Ideal.span_insert, sup_comm]
    refine sup_le_sup_left ?_ _
    rw [Ideal.span_singleton_le_iff_mem, smul_eq_mul, ← pow_two]
    exact hmem
  have hNm := Submodule.le_of_le_smul_of_le_jacobson_bot
    (IsNoetherian.noetherian (IsLocalRing.maximalIdeal R))
    (IsLocalRing.maximalIdeal_le_jacobson ⊥) hle
  have hNle : Ideal.span (((Finset.univ.erase i).image x : Finset R) : Set R) ≤
      IsLocalRing.maximalIdeal R := by
    rw [← hx]
    refine Ideal.span_mono ?_
    rw [hrange]
    exact Set.subset_insert _ _
  have heq := le_antisymm hNm hNle
  have hcard : (IsLocalRing.maximalIdeal R).spanFinrank ≤ n - 1 := by
    rw [heq]
    refine le_trans (Submodule.spanFinrank_span_le_ncard_of_finite (Finset.finite_toSet _)) ?_
    rw [Set.ncard_coe_finset]
    refine le_trans Finset.card_image_le ?_
    rw [Finset.card_erase_of_mem (Finset.mem_univ i), Finset.card_univ, Fintype.card_fin]
  have := i.pos
  omega

/-- The quotient-ring form of `cons`: `r` regular on `R` and the image of `rs` weakly regular on `R/(r)` ⇒ `r :: rs`
weakly regular on `R`. (Mathlib's `isWeaklyRegular_cons_iff` uses the module `QuotSMulTop r R`; here it is the
quotient ring `R ⧸ span {r}`.) -/
theorem RingTheory.Sequence.IsWeaklyRegular.cons_of_quotient_span_singleton {R : Type*}
    [CommRing R] {r : R} {rs : List R} (h1 : IsSMulRegular R r)
    (h2 : RingTheory.Sequence.IsWeaklyRegular (R ⧸ Ideal.span {r})
      (rs.map (Ideal.Quotient.mk (Ideal.span {r})))) :
    RingTheory.Sequence.IsWeaklyRegular R (r :: rs) := by
  rw [RingTheory.Sequence.isWeaklyRegular_cons_iff]
  refine ⟨h1, ?_⟩
  have h3 : RingTheory.Sequence.IsWeaklyRegular (R ⧸ Ideal.span {r}) rs :=
    (RingTheory.Sequence.isWeaklyRegular_map_algebraMap_iff (R ⧸ Ideal.span {r})
      (R ⧸ Ideal.span {r}) rs).mp h2
  have heq : (r • (⊤ : Submodule R R)) = (Ideal.span {r} : Ideal R) := by
    rw [← Submodule.ideal_span_singleton_smul]; simp
  exact ((Submodule.quotEquivOfEq _ _ heq).isWeaklyRegular_congr rs).mpr h3

/-- The inductive form of the full 00NQ (induction on `d`, quantified over all rings). -/
theorem IsRegularLocalRing.isWeaklyRegular_ofFn_aux (d : ℕ) :
    ∀ (R : Type u) [CommRing R] [IsRegularLocalRing R] (x : Fin d → R),
      Ideal.span (Set.range x) = IsLocalRing.maximalIdeal R →
      (IsLocalRing.maximalIdeal R).spanFinrank = d →
      RingTheory.Sequence.IsWeaklyRegular R (List.ofFn x) := by
  induction d with
  | zero =>
    intro R _ _ x _ _
    simp
  | succ d ih =>
    intro R _ _ x hx hd
    have hx0 : x 0 ∈ IsLocalRing.maximalIdeal R := hx ▸ Ideal.subset_span ⟨0, rfl⟩
    have hx2 : x 0 ∉ IsLocalRing.maximalIdeal R ^ 2 :=
      IsLocalRing.notMem_sq_of_span_range_eq_maximalIdeal x hx hd 0
    have hne : x 0 ≠ 0 := fun h => hx2 (h ▸ Ideal.zero_mem _)
    have hreg0 : IsSMulRegular R (x 0) := (IsRegular.of_ne_zero hne).left.isSMulRegular
    have hRbar : IsRegularLocalRing (R ⧸ Ideal.span {x 0}) :=
      IsRegularLocalRing.quotient_span_singleton hx0 hx2
    -- the images generate the maximal ideal of the quotient
    have hspan : Ideal.span (Set.range fun i : Fin d => Ideal.Quotient.mk (Ideal.span {x 0}) (x i.succ)) =
        IsLocalRing.maximalIdeal (R ⧸ Ideal.span {x 0}) := by
      rw [← IsLocalRing.map_maximalIdeal_of_surjective (Ideal.Quotient.mk (Ideal.span {x 0}))
        Ideal.Quotient.mk_surjective, ← hx, Ideal.map_span, Fin.range_fin_succ,
        Set.image_insert_eq, Ideal.span_insert, ← Set.range_comp]
      have : Ideal.Quotient.mk (Ideal.span {x 0}) (x 0) = 0 :=
        Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_span_singleton_self _)
      rw [this, Ideal.span_singleton_eq_bot.mpr rfl, bot_sup_eq]
      rfl
    -- the minimal number of generators of the maximal ideal of the quotient is exactly `d`
    have hle := IsLocalRing.spanFinrank_maximalIdeal_quotient_span_singleton_add_one_le hx0 hx2
    rw [hd] at hle
    have hge : d ≤ (IsLocalRing.maximalIdeal (R ⧸ Ideal.span {x 0})).spanFinrank := by
      have h2 := IsLocalRing.ringKrullDim_le_ringKrullDim_quotient_span_singleton_add_one hx0
      rw [← IsRegularLocalRing.spanFinrank_maximalIdeal (R := R),
        ← IsRegularLocalRing.spanFinrank_maximalIdeal (R := R ⧸ Ideal.span {x 0}), hd] at h2
      have h3 : ((d : ℕ) : WithBot ℕ∞) + 1 ≤
          (((IsLocalRing.maximalIdeal (R ⧸ Ideal.span {x 0})).spanFinrank : ℕ) : WithBot ℕ∞) + 1 := by
        push_cast at h2 ⊢; exact h2
      have h4 := WithBot.natCast_le_of_natCast_add_one_le_add_one h3
      exact_mod_cast h4
    have hdbar : (IsLocalRing.maximalIdeal (R ⧸ Ideal.span {x 0})).spanFinrank = d := by omega
    have hih := ih (R ⧸ Ideal.span {x 0})
      (fun i : Fin d => Ideal.Quotient.mk (Ideal.span {x 0}) (x i.succ)) hspan hdbar
    rw [List.ofFn_succ]
    refine RingTheory.Sequence.IsWeaklyRegular.cons_of_quotient_span_singleton hreg0 ?_
    rw [List.map_ofFn]
    exact hih

/-- **Stacks 00NQ (full form): a minimal system of generators of the maximal ideal of a regular local ring is a
regular sequence.** -/
theorem IsRegularLocalRing.isWeaklyRegular_of_span_eq_maximalIdeal {R : Type u} [CommRing R]
    [IsRegularLocalRing R] {d : ℕ} (hd : ringKrullDim R = d) (x : Fin d → R)
    (hx : Ideal.span (Set.range x) = IsLocalRing.maximalIdeal R) :
    RingTheory.Sequence.IsWeaklyRegular R (List.ofFn x) := by
  refine IsRegularLocalRing.isWeaklyRegular_ofFn_aux d R x hx ?_
  have := IsRegularLocalRing.spanFinrank_maximalIdeal (R := R)
  rw [hd] at this
  exact_mod_cast this

end
