import MiyaokaMori.Prelude

/-! # Stacks 00NQ: quotient of a regular local ring by an element of `m ∖ m²`

A consequence of Stacks 00NQ: for a regular local ring `R` and `x ∈ m ∖ m²`, `R/(x)` is again a regular local
ring (of dimension one less).

Reference: Stacks 00NQ (in the proof of 0AG0: `R/(x)` regular).

This file does not import `Stacks00np`: the single step 00NQ (`quotient_span_singleton`) does not need "regular
local rings are domains", while the prime-avoidance proof of 00NP uses this step, so the import direction is
`Stacks00np → Stacks00nq`. The full form of 00NQ ("a minimal system of generators is a regular sequence", which
needs 00NP) is in `Stacks00nqRegularSequence`.

`quotient_span_singleton` = `exists_finset_span_insert_eq_maximalIdeal` (extend `x` to a minimal generating set)
+ `spanFinrank_maximalIdeal_quotient_span_singleton_add_one_le` (the number of generators drops by `1`)
+ `ringKrullDim_le_ringKrullDim_quotient_span_singleton_add_one` (the dimension form of Krull's principal ideal
theorem).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- **Extend `x ∈ m ∖ m²` to a minimal system of generators of `m`** (first sentence of the proof of Stacks 00NQ).

Statement: `R` a Noetherian local ring, `x ∈ m`, `x ∉ m²`; then there is a finite set `s ⊆ R` with
`s.card + 1 ≤ spanFinrank m` and `span (insert x s) = m`.

Proof (exchange lemma, without the cotangent space): take a system `s₀` of `d = spanFinrank m` generators of `m`
and write `x = Σ_{y ∈ s₀} a_y y`. If all `a_y ∈ m` then `x ∈ m²`, a contradiction; so some `a_y` is a unit,
`y = a_y⁻¹ (x − Σ_{z ≠ y} a_z z) ∈ span (insert x (s₀ ∖ {y}))`, hence `insert x (s₀ ∖ {y})` generates `m`; take
`s = s₀ ∖ {y}` (`d − 1` elements). -/
theorem IsLocalRing.exists_finset_span_insert_eq_maximalIdeal {R : Type*} [CommRing R]
    [IsLocalRing R] [IsNoetherianRing R] {x : R} (hx : x ∈ IsLocalRing.maximalIdeal R)
    (hx2 : x ∉ IsLocalRing.maximalIdeal R ^ 2) :
    ∃ s : Finset R, s.card + 1 ≤ (IsLocalRing.maximalIdeal R).spanFinrank ∧
      Ideal.span (insert x (s : Set R)) = IsLocalRing.maximalIdeal R := by
  classical
  obtain ⟨s₀, hs₀, hspan⟩ :=
    (IsNoetherian.noetherian (IsLocalRing.maximalIdeal R)).exists_span_finset_card_eq_spanFinrank
  have hs₀m : ∀ z ∈ s₀, z ∈ IsLocalRing.maximalIdeal R := fun z hz =>
    hspan ▸ Submodule.subset_span (Finset.mem_coe.mpr hz)
  obtain ⟨a, -, hsum⟩ := Submodule.mem_span_finset.mp (hspan.symm ▸ hx : x ∈ Submodule.span R ↑s₀)
  -- some coefficient is a unit, otherwise `x ∈ m²`
  obtain ⟨y, hy, hay⟩ : ∃ y ∈ s₀, a y ∉ IsLocalRing.maximalIdeal R := by
    by_contra hcon
    push Not at hcon
    refine hx2 ?_
    rw [← hsum, pow_two]
    exact Ideal.sum_mem _ fun z hz => Ideal.mul_mem_mul (hcon z hz) (hs₀m z hz)
  obtain ⟨u, hu⟩ := IsLocalRing.notMem_maximalIdeal.mp hay
  refine ⟨s₀.erase y, ?_, ?_⟩
  · rw [Finset.card_erase_of_mem hy, ← hs₀]
    have := Finset.card_pos.mpr ⟨y, hy⟩
    omega
  · have hT : Ideal.span (insert x ((s₀.erase y : Finset R) : Set R)) ≤
        IsLocalRing.maximalIdeal R := by
      refine Ideal.span_le.mpr fun z hz => ?_
      rcases hz with rfl | hz
      · exact hx
      · exact hs₀m z (Finset.mem_of_mem_erase (Finset.mem_coe.mp hz))
    refine le_antisymm hT ?_
    have hyT : y ∈ Ideal.span (insert x ((s₀.erase y : Finset R) : Set R)) := by
      have h1 : a y * y = x - ∑ z ∈ s₀.erase y, a z • z := by
        rw [← hsum, ← Finset.add_sum_erase s₀ _ hy, smul_eq_mul, add_sub_cancel_right]
      have h2 : a y * y ∈ Ideal.span (insert x ((s₀.erase y : Finset R) : Set R)) := by
        rw [h1]
        refine Ideal.sub_mem _ (Ideal.subset_span (Set.mem_insert _ _))
          (Ideal.sum_mem _ fun z hz => ?_)
        exact Ideal.mul_mem_left _ _ (Ideal.subset_span (Set.mem_insert_of_mem _ (Finset.mem_coe.mpr hz)))
      have h3 : y = (↑u⁻¹ : R) * (a y * y) := by
        rw [← hu, ← mul_assoc, Units.inv_mul, one_mul]
      have h4 := Ideal.mul_mem_left _ (↑u⁻¹ : R) h2
      rwa [← h3] at h4
    rw [← hspan]
    refine Ideal.span_le.mpr fun z hz => ?_
    by_cases hzy : z = y
    · exact hzy ▸ hyT
    · exact Ideal.subset_span (Set.mem_insert_of_mem _
        (Finset.mem_coe.mpr (Finset.mem_erase.mpr ⟨hzy, Finset.mem_coe.mp hz⟩)))

/-- For `x ∈ m ∖ m²`, the minimal number of generators of the maximal ideal of `R/(x)` drops by at least `1`.
Assembled from the previous lemma: `m̄ = m·R̄` is generated by the image of `s`. -/
theorem IsLocalRing.spanFinrank_maximalIdeal_quotient_span_singleton_add_one_le {R : Type*}
    [CommRing R] [IsLocalRing R] [IsNoetherianRing R] {x : R}
    [IsLocalRing (R ⧸ Ideal.span {x})]
    (hx : x ∈ IsLocalRing.maximalIdeal R) (hx2 : x ∉ IsLocalRing.maximalIdeal R ^ 2) :
    (IsLocalRing.maximalIdeal (R ⧸ Ideal.span {x})).spanFinrank + 1 ≤
      (IsLocalRing.maximalIdeal R).spanFinrank := by
  classical
  obtain ⟨s, hs, hspan⟩ := IsLocalRing.exists_finset_span_insert_eq_maximalIdeal hx hx2
  refine le_trans (Nat.add_le_add_right ?_ 1) hs
  have hmap : IsLocalRing.maximalIdeal (R ⧸ Ideal.span {x}) =
      Ideal.span ((s.image (Ideal.Quotient.mk (Ideal.span {x})) : Finset _) : Set _) := by
    rw [← IsLocalRing.map_maximalIdeal_of_surjective (Ideal.Quotient.mk (Ideal.span {x}))
      Ideal.Quotient.mk_surjective, ← hspan, Ideal.map_span, Set.image_insert_eq,
      Ideal.span_insert, Finset.coe_image]
    have : Ideal.Quotient.mk (Ideal.span {x}) x = 0 :=
      Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_span_singleton_self x)
    rw [this, Ideal.span_singleton_eq_bot.mpr rfl, bot_sup_eq]
  rw [hmap]
  refine le_trans (Submodule.spanFinrank_span_le_ncard_of_finite (Finset.finite_toSet _)) ?_
  rw [Set.ncard_coe_finset]
  exact Finset.card_image_le

/-- Cancelling `+1` for natural numbers in `WithBot ℕ∞` (`ℕ∞` does not satisfy `AddRightReflectLE`, so Mathlib's
general cancellation lemma does not apply). -/
theorem WithBot.natCast_le_of_natCast_add_one_le_add_one {k : ℕ} {D : WithBot ℕ∞}
    (h : (k : WithBot ℕ∞) + 1 ≤ D + 1) : (k : WithBot ℕ∞) ≤ D := by
  induction D using WithBot.recBotCoe with
  | bot => simp at h
  | coe D =>
    induction D using ENat.recTopCoe with
    | top => exact le_top
    | coe n =>
      have h' : ((k + 1 : ℕ) : WithBot ℕ∞) ≤ ((n + 1 : ℕ) : WithBot ℕ∞) := by
        push_cast; exact h
      have h'' : k + 1 ≤ n + 1 := by exact_mod_cast h'
      exact_mod_cast (Nat.le_of_succ_le_succ h'')

/-- The dimension form of Krull's principal ideal theorem: in a Noetherian local ring, `x ∈ m` implies
`dim R ≤ dim R/(x) + 1`. Mathlib: `ringKrullDim_le_ringKrullDim_quotient_add_spanFinrank`. -/
theorem IsLocalRing.ringKrullDim_le_ringKrullDim_quotient_span_singleton_add_one {R : Type*}
    [CommRing R] [IsLocalRing R] [IsNoetherianRing R] {x : R}
    (hx : x ∈ IsLocalRing.maximalIdeal R) :
    ringKrullDim R ≤ ringKrullDim (R ⧸ Ideal.span {x}) + 1 := by
  have h1 : Ideal.span {x} ≤ Ring.jacobson R := by
    rw [IsLocalRing.ringJacobson_eq_maximalIdeal]
    exact (Ideal.span_singleton_le_iff_mem _).mpr hx
  refine le_trans (ringKrullDim_le_ringKrullDim_quotient_add_spanFinrank _ h1) ?_
  gcongr
  have : (Ideal.span {x}).spanFinrank ≤ 1 := by
    refine le_trans (Submodule.spanFinrank_span_le_ncard_of_finite (Set.finite_singleton x)) ?_
    simp
  exact_mod_cast this

theorem IsRegularLocalRing.quotient_span_singleton {R : Type*} [CommRing R] [IsRegularLocalRing R]
    {x : R} (hx : x ∈ IsLocalRing.maximalIdeal R) (hx2 : x ∉ IsLocalRing.maximalIdeal R ^ 2) :
    IsRegularLocalRing (R ⧸ Ideal.span {x}) := by
  have hne : Ideal.span {x} ≠ ⊤ := fun h =>
    (IsLocalRing.maximalIdeal.isMaximal R).ne_top
      (top_le_iff.mp (h ▸ (Ideal.span_singleton_le_iff_mem _).mpr hx))
  have : Nontrivial (R ⧸ Ideal.span {x}) := Ideal.Quotient.nontrivial_iff.mpr hne
  have : IsLocalRing (R ⧸ Ideal.span {x}) :=
    IsLocalRing.of_surjective' (Ideal.Quotient.mk (Ideal.span {x})) Ideal.Quotient.mk_surjective
  apply IsRegularLocalRing.of_spanFinrank_maximalIdeal_le
  have h1 := IsLocalRing.spanFinrank_maximalIdeal_quotient_span_singleton_add_one_le hx hx2
  have h2 := IsLocalRing.ringKrullDim_le_ringKrullDim_quotient_span_singleton_add_one hx
  have h3 : (((IsLocalRing.maximalIdeal (R ⧸ Ideal.span {x})).spanFinrank + 1 : ℕ) :
      WithBot ℕ∞) ≤ ringKrullDim (R ⧸ Ideal.span {x}) + 1 := by
    refine le_trans ?_ h2
    rw [← IsRegularLocalRing.spanFinrank_maximalIdeal (R := R)]
    exact_mod_cast h1
  push_cast at h3
  exact WithBot.natCast_le_of_natCast_add_one_le_add_one h3

end
