import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.Basic.EpiPullbackOpenOfLocallySurjective
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.HomOfTensorSectionDualFrame
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.QcFiniteTypeGeneratorsAffineOpen
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.NonvanishingLocusIsoInvariant
import MiyaokaMori.AlgebraicGeometry.Modules.Basic.ModulesPow
import MiyaokaMori.AlgebraicGeometry.Modules.Stacks0892_TensorPowSectionLocus
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.Stacks01pw
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.Stacks01pwUniformExponent

/-! # Stacks 01Q3 (1)⇒(5)⇒(7) localized on one affine nonvanishing locus

Stacks 01Q3 (1)⇒(5)⇒(7), localized on one affine open `X_s`: on a quasi-compact quasi-separated
scheme `X` with an invertible sheaf `L`, a homogeneous section `s ∈ Γ(X, L^{⊗m})` (`m > 0`) whose
nonvanishing locus `X_s` is affine, and a finite type quasi-coherent module `F`, there is `n₀` such
that for every `n ≥ n₀` divisible by `m` finitely many morphisms `L^{⊗-n} ⟶ F` are jointly
surjective on `X_s` (the pullback of `⨁_{j<r} L^{⊗-n} ⟶ F` to the open subscheme `X_s` is an
epimorphism).

This is the "local" half of Stacks 01Q3 (1)⇒(8); the global statement is assembled from finitely
many instances of this lemma (one per member of a finite affine cover `X = ⋃ X_{s_i}`) in
`AmpleFiniteTypeQuotient`.

Source: Stacks 01Q3 (`properties-proposition-characterize-ample`), proof, paragraphs (1)⇒(5) and
(7); Stacks 01PW (`properties-lemma-invert-s-sections`, extension of sections after multiplying by
a power of `s`); Stacks 01PB (a finite type quasi-coherent module on an affine scheme is generated
by finitely many global sections).

Route: step 1 is `Scheme.Modules.exists_finite_generators_of_isFiniteType`; step 2 is Stacks 01PW
(`exists_tensorPow_section_restrict_eq`); step 3 is `exists_tensorPow_section_restrict_eq_of_le`
followed by transport along `θ := tensorPowMulIso L m k : (L^{⊗m})^{⊗k} ≅ L^{⊗n}` — no
compatibility of `θ` with `tensorPowSection` is needed: we only use that `e := θ(s^{⊗k})` is
nonvanishing on `X_s` (`nonvanishingLocus_iso`, `nonvanishingLocus_tensorPowSection_succ`); step 4 is
`exists_zpow_neg_section_hom_of_tensor_section`; step 5 is `epi_pullback_ι_map_of_locally_surjective`
plus the biproduct bookkeeping done here.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- **Stacks 01Q3 (1)⇒(5)⇒(7) on one affine `X_s`.** `X` quasi-compact and quasi-separated, `L`
invertible, `m > 0`,
`s ∈ Γ(X, L^{⊗m})` with `X_s` affine, `F` quasi-coherent of finite type. Then there is `n₀` such
that for every `n ≥ n₀` with `m ∣ n` there are finitely many morphisms `φ_j : L^{⊗-n} ⟶ F`
(`j < r`) whose restriction to `X_s`, i.e. the pullback of `biproduct.desc φ` along the open
immersion `X_s.ι`, is an epimorphism. Here `L ^ (-(n : ℤ))` is the `ℤ`-power of the line bundle.

Proof sketch (Stacks 01Q3, proof of (1)⇒(5) and of (7), specialised to a single `X_s`):

1. *Finitely many generators on the affine `X_s`* (Stacks 01PB, direction "finite type ⇒ `Γ`
   finitely generated"). Put `U := X_s`, `A := Γ(U, O_X)`, `M := Γ(U, F)`. Since `F` is
   quasi-coherent and `U` is affine, `F|_U ≅ M^~` (Mathlib
   `Scheme.Modules.isIso_fromTildeΓ_of_isQuasicoherent` after restricting along `hs.fromSpec`). Since
   `F` is of finite type, `U` is covered by opens on which `F` is generated by finitely many
   sections; shrinking to standard opens `D(f_1), …, D(f_k)` of `U = Spec A` (finitely many by
   quasi-compactness of `U`) and clearing denominators, on each `D(f_i)` the module `M_{f_i}` is
   generated by the images of finitely many elements `t_{i1}, …, t_{ir_i} ∈ M`. If `t ∈ M`, then for
   each `i` there is `N` with `f_i^N t ∈ Σ_j A t_{ij}`; since `(f_1, …, f_k) = A` also
   `(f_1^N, …, f_k^N) = A`, so `t ∈ Σ_{i,j} A t_{ij}`. Hence `M` is generated by the finitely many
   `t_1, …, t_r` (renumbered), and these sections generate `F|_U`: for every open `V ≤ U`, every
   section of `F` over `V` is locally (on standard opens `D(g) ⊆ V` of `U`) of the form
   `Σ_j (a_j / g^N) t_j` (this is `F|_U ≅ M^~` again, or the library's
   `QuasicoherentAffineLocal` description of sections over basic opens as localizations).
2. *Extend the generators to global sections of twists* (Stacks 01PW (2),
   `Scheme.Modules.exists_tensorPow_section_restrict_eq`, applied to the
   invertible sheaf `L' := L^{⊗m}` with its section `s` and to `F`; it needs `CompactSpace X` and
   `QuasiSeparatedSpace X`). For each `j` there are `k_j ≥ 0` and
   `σ_j ∈ Γ(X, F ⊗ L'^{⊗k_j})` with `σ_j|_U = t_j ⊗ s^{k_j}|_U`. Put `k₀ := max_j k_j` and
   `n₀ := k₀ · m`.
3. *Uniformise the exponent.* Let `n ≥ n₀` with `m ∣ n`, say `n = k · m`, so `k ≥ k₀ ≥ k_j`.
   Replace `σ_j` by `σ_j ⊗ s^{k − k_j} ∈ Γ(X, F ⊗ L'^{⊗k})`; its restriction to `U` is
   `t_j ⊗ s^{k}|_U` (associativity of `⊗` on sections and `tensorPowSection` recursion). Identify
   `L'^{⊗k} = (L^{⊗m})^{⊗k} ≅ L^{⊗(km)} = L^{⊗n}` (`tensorPowMulIso`), so that
   `σ_j ∈ Γ(X, F ⊗ L^{⊗n})`.
4. *Sections of `F ⊗ L^{⊗n}` give morphisms `L^{⊗-n} ⟶ F`.* Since `L^{⊗n} ⊗ L^{⊗-n} ≅ O_X`
   (via the contraction `L ⊗ L^∨ ≅ O_X` of Stacks 01CT), a global section `σ` of `F ⊗ L^{⊗n}`
   defines `φ_σ : L^{⊗-n} ⟶ F` as the composite
   `L^{⊗-n} ≅ O_X ⊗ L^{⊗-n} →(σ ⊗ id) (F ⊗ L^{⊗n}) ⊗ L^{⊗-n} ≅ F ⊗ (L^{⊗n} ⊗ L^{⊗-n}) ≅ F ⊗ O_X ≅ F`
   (the first arrow is the morphism `O_X ⟶ F ⊗ L^{⊗n}` corresponding to `σ` under
   `Hom(O_X, −) ≃ Γ(X, −)`). On `U` the section `s^k` of
   `L^{⊗n}|_U` is a frame (it is nonvanishing at every point of `U = X_s = X_{s^k}`), with dual frame
   `(s^k)^∨ ∈ Γ(U, L^{⊗-n})` (`⟨s^k, (s^k)^∨⟩ = 1`); by construction
   `φ_{σ_j}((s^k)^∨|_V) = t_j|_V` for every open `V ≤ U`, because `σ_j|_U = t_j ⊗ s^k` and the
   contraction pairs `s^k` with `(s^k)^∨` to `1`.
5. *Epimorphism on `U`.* Let `p := biproduct.desc (φ_{σ_j})_j : ⨁_{j<r} L^{⊗-n} ⟶ F`. Its pullback to
   the open subscheme `U` is an epimorphism iff it is locally surjective on sections
   (`Scheme.Modules.epi_iff_locally_surjective_sections`, transported along
   `restrictFunctorIsoPullback`). Given an
   open `V ≤ U`, a section `t ∈ Γ(V, F)` and a point `x ∈ V`, step 1 gives an open `x ∈ W ≤ V` and
   `a_j ∈ Γ(W, O_X)` with `t|_W = Σ_j a_j • t_j|_W`; then the section `(a_j • (s^k)^∨|_W)_j` of
   `⨁_j L^{⊗-n}` over `W` is mapped by `p` to `Σ_j a_j • φ_{σ_j}((s^k)^∨|_W) = Σ_j a_j • t_j|_W = t|_W`
   (`biproduct.ι_desc`, linearity of the section maps). Hence the pullback of `p` to `U` is an
   epimorphism.

Edge cases: `X = ∅` (then `X_s = ∅`, every morphism to a module on the empty scheme is an
epimorphism, `r = 0` works); `F = 0` (`r = 0`, `n₀ = 0`); `X_s = ∅` (any `r`, the pullback to the
empty scheme is an epimorphism); the hypothesis `0 < m` is used only to make `m ∣ n` meaningful
(for `m = 0` the statement would force `n = 0` and would be false in general, e.g. a section over
a proper affine open `D(s)` of `X` that does not extend to `X`).

Formalization: step 1 is `exists_finite_generators_of_isFiniteType`; step 2 is
`exists_tensorPow_section_restrict_eq`; step 3 is `exists_tensorPow_section_restrict_eq_of_le`;
step 4 is `exists_zpow_neg_section_hom_of_tensor_section` (stated for an arbitrary frame section
`e` of `L^{⊗n}` with `U ≤ X_e`); step 5 is `epi_pullback_ι_map_of_locally_surjective`. With
`θ := tensorPowMulIso L m k` and `e := θ(s^{⊗k}) ∈ Γ(X, L^{⊗n})` one only needs
`X_e = X_{s^{⊗k}} ⊇ X_s` (`nonvanishingLocus_iso`), not a formula for `θ(s^{⊗k})`. -/
theorem AlgebraicGeometry.Scheme.Modules.exists_epi_pullback_nonvanishingLocus_biproduct_zpow_neg
    {X : AlgebraicGeometry.Scheme.{u}} [CompactSpace X] [QuasiSeparatedSpace X]
    (L : X.Modules) [L.IsLineBundle] {m : ℕ} (hm : 0 < m)
    (s : Γ(AlgebraicGeometry.Scheme.Modules.tensorPow L m, ⊤))
    (hs : AlgebraicGeometry.IsAffineOpen
      ((AlgebraicGeometry.Scheme.Modules.tensorPow L m).nonvanishingLocus s))
    (F : X.Modules) [F.IsQuasicoherent] [F.IsFiniteType] :
    ∃ n₀ : ℕ, ∀ n : ℕ, n₀ ≤ n → m ∣ n →
      ∃ (r : ℕ) (φ : Fin r → (L ^ (-(n : ℤ)) ⟶ F)),
        CategoryTheory.Epi
          ((AlgebraicGeometry.Scheme.Modules.pullback
            ((AlgebraicGeometry.Scheme.Modules.tensorPow L m).nonvanishingLocus s).ι).map
            (CategoryTheory.Limits.biproduct.desc φ)) := by
  classical
  -- step 1: finitely many generators `t j ∈ Γ(X_s, F)`
  obtain ⟨r, t, hgen⟩ := AlgebraicGeometry.Scheme.Modules.exists_finite_generators_of_isFiniteType F hs
  -- step 2: Stacks 01PW for `L' := L^{⊗m}` and each generator
  have h01pw : ∀ j : Fin r, ∃ (k : ℕ) (σ : Γ(AlgebraicGeometry.Scheme.Modules.tensor F
      (AlgebraicGeometry.Scheme.Modules.tensorPow (AlgebraicGeometry.Scheme.Modules.tensorPow L m) k), ⊤)),
      (AlgebraicGeometry.Scheme.Modules.tensor F
        (AlgebraicGeometry.Scheme.Modules.tensorPow (AlgebraicGeometry.Scheme.Modules.tensorPow L m) k)).presheaf.map
          (homOfLE (le_top : (AlgebraicGeometry.Scheme.Modules.tensorPow L m).nonvanishingLocus s ≤ ⊤)).op σ =
        AlgebraicGeometry.Scheme.Modules.moduleTensorSection (t j)
          ((AlgebraicGeometry.Scheme.Modules.tensorPow (AlgebraicGeometry.Scheme.Modules.tensorPow L m) k).presheaf.map
            (homOfLE (le_top : (AlgebraicGeometry.Scheme.Modules.tensorPow L m).nonvanishingLocus s ≤ ⊤)).op
            (AlgebraicGeometry.Scheme.Modules.tensorPowSection s k)) :=
    fun j => AlgebraicGeometry.Scheme.Modules.exists_tensorPow_section_restrict_eq
      (AlgebraicGeometry.Scheme.Modules.tensorPow L m) s F (t j)
  choose k σ hσ using h01pw
  refine ⟨m * ∑ j, k j, fun n hn hmn => ?_⟩
  obtain ⟨c, rfl⟩ := hmn
  have hc : ∀ j, k j ≤ c := fun j =>
    (Finset.single_le_sum (fun i _ => Nat.zero_le (k i)) (Finset.mem_univ j)).trans
      (Nat.le_of_mul_le_mul_left hn hm)
  -- step 3: uniformise the exponent to `c`, then transport along `(L^{⊗m})^{⊗c} ≅ L^{⊗(m c)}`
  choose σ' hσ' using fun j =>
    AlgebraicGeometry.Scheme.Modules.exists_tensorPow_section_restrict_eq_of_le
      (AlgebraicGeometry.Scheme.Modules.tensorPow L m) s F (t j) (σ j) (hσ j) (hc j)
  let θ : AlgebraicGeometry.Scheme.Modules.tensorPow (AlgebraicGeometry.Scheme.Modules.tensorPow L m) c ≅
      AlgebraicGeometry.Scheme.Modules.tensorPow L (m * c) :=
    AlgebraicGeometry.Scheme.Modules.tensorPowMulIso L m c
  let e : Γ(AlgebraicGeometry.Scheme.Modules.tensorPow L (m * c), ⊤) :=
    θ.hom.app ⊤ (AlgebraicGeometry.Scheme.Modules.tensorPowSection s c)
  have hUe : (AlgebraicGeometry.Scheme.Modules.tensorPow L m).nonvanishingLocus s ≤
      (AlgebraicGeometry.Scheme.Modules.tensorPow L (m * c)).nonvanishingLocus e := by
    have h1 : (AlgebraicGeometry.Scheme.Modules.tensorPow L (m * c)).nonvanishingLocus e =
        (AlgebraicGeometry.Scheme.Modules.tensorPow (AlgebraicGeometry.Scheme.Modules.tensorPow L m) c).nonvanishingLocus
          (AlgebraicGeometry.Scheme.Modules.tensorPowSection s c) :=
      AlgebraicGeometry.Scheme.Modules.nonvanishingLocus_iso θ
        (AlgebraicGeometry.Scheme.Modules.tensorPowSection s c)
    rw [h1]
    cases c with
    | zero =>
      rw [AlgebraicGeometry.Scheme.Modules.nonvanishingLocus_tensorPowSection_zero]
      exact le_top
    | succ b =>
      rw [AlgebraicGeometry.Scheme.Modules.nonvanishingLocus_tensorPowSection_succ]
  let σ'' : Fin r → Γ(AlgebraicGeometry.Scheme.Modules.tensor F
      (AlgebraicGeometry.Scheme.Modules.tensorPow L (m * c)), ⊤) :=
    fun j => (AlgebraicGeometry.Scheme.Modules.tensorCongrRightIso F θ).hom.app ⊤ (σ' j)
  have hσ'' : ∀ j, (AlgebraicGeometry.Scheme.Modules.tensor F
      (AlgebraicGeometry.Scheme.Modules.tensorPow L (m * c))).presheaf.map
        (homOfLE (le_top : (AlgebraicGeometry.Scheme.Modules.tensorPow L m).nonvanishingLocus s ≤ ⊤)).op (σ'' j) =
      AlgebraicGeometry.Scheme.Modules.moduleTensorSection (t j)
        ((AlgebraicGeometry.Scheme.Modules.tensorPow L (m * c)).presheaf.map
          (homOfLE (le_top : (AlgebraicGeometry.Scheme.Modules.tensorPow L m).nonvanishingLocus s ≤ ⊤)).op e) := by
    intro j
    show (AlgebraicGeometry.Scheme.Modules.tensor F
      (AlgebraicGeometry.Scheme.Modules.tensorPow L (m * c))).presheaf.map _
        ((AlgebraicGeometry.Scheme.Modules.tensorCongrRightIso F θ).hom.app ⊤ (σ' j)) = _
    rw [← AlgebraicGeometry.Scheme.Modules.Hom.app_map'
      (AlgebraicGeometry.Scheme.Modules.tensorCongrRightIso F θ).hom
      (le_top : (AlgebraicGeometry.Scheme.Modules.tensorPow L m).nonvanishingLocus s ≤ ⊤) (σ' j),
      hσ' j, AlgebraicGeometry.Scheme.Modules.tensorCongrRightIso_hom_app_moduleTensorSection]
    exact congrArg (fun z => AlgebraicGeometry.Scheme.Modules.moduleTensorSection (t j) z)
      (AlgebraicGeometry.Scheme.Modules.Hom.app_map' θ.hom
        (le_top : (AlgebraicGeometry.Scheme.Modules.tensorPow L m).nonvanishingLocus s ≤ ⊤)
        (AlgebraicGeometry.Scheme.Modules.tensorPowSection s c))
  -- step 4: the dual frame `ε` of `e` on `X_s` and the morphisms `φ j : L^{⊗-n} ⟶ F`
  obtain ⟨ε, hε⟩ := AlgebraicGeometry.Scheme.Modules.exists_zpow_neg_section_hom_of_tensor_section
    L F (m * c) e hUe
  choose φ hφ using fun j => hε (σ'' j) (t j) (hσ'' j)
  refine ⟨r, φ, ?_⟩
  -- step 5: local surjectivity on the opens of `X_s`
  apply AlgebraicGeometry.Scheme.Modules.epi_pullback_ι_map_of_locally_surjective
  intro V hVU f x hx
  obtain ⟨W, hWV, hxW, a, ha⟩ := hgen V hVU f x hx
  refine ⟨W, hWV, hxW, ∑ j, (CategoryTheory.Limits.biproduct.ι
    (fun _ : Fin r => L ^ (-((m * c : ℕ) : ℤ))) j).app W
      (a j • (L ^ (-((m * c : ℕ) : ℤ))).presheaf.map (homOfLE (hWV.trans hVU)).op ε), ?_⟩
  rw [map_sum, ha]
  refine Finset.sum_congr rfl fun j _ => ?_
  have hcomp : (CategoryTheory.Limits.biproduct.desc φ).app W
      ((CategoryTheory.Limits.biproduct.ι (fun _ : Fin r => L ^ (-((m * c : ℕ) : ℤ))) j).app W
        (a j • (L ^ (-((m * c : ℕ) : ℤ))).presheaf.map (homOfLE (hWV.trans hVU)).op ε)) =
      (CategoryTheory.Limits.biproduct.ι (fun _ : Fin r => L ^ (-((m * c : ℕ) : ℤ))) j ≫
        CategoryTheory.Limits.biproduct.desc φ).app W
        (a j • (L ^ (-((m * c : ℕ) : ℤ))).presheaf.map (homOfLE (hWV.trans hVU)).op ε) := rfl
  rw [hcomp, CategoryTheory.Limits.biproduct.ι_desc, AlgebraicGeometry.Scheme.Modules.Hom.app_smul,
    hφ j W (hWV.trans hVU)]

end
