import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Morphisms.QuasiProjectiveMorphism
import MiyaokaMori.AlgebraicGeometry.Modules.FrameLocusOn
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.ModuleSheafFrameIso
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.NonvanishingLocusIsoInvariant
import MiyaokaMori.AlgebraicGeometry.Modules.Stacks07rm_AmpleChartsAffineBase
import MiyaokaMori.AlgebraicGeometry.Modules.Stacks0892_TensorPowSectionLocus
import MiyaokaMori.AlgebraicGeometry.Modules.Stacks0892_TensorPowIsos
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.ModulesTensorPowCanonicalIso
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.ModuleSheafFrame
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.ModuleTensorPowers

/-! # Relative chart sections of a quasi-projective morphism

**Relative chart sections of a quasi-projective morphism** (Stacks 07RM, proof paragraphs 1–2): `S` quasi-compact,
`f : X ⟶ S` quasi-projective. There are a line bundle `M` on `X` (namely `L^{⊗d}` for the relatively ample `L`
and a common degree `d`), finitely many affine opens `V_j` covering `S`, and for each `j` finitely many sections
`s_{j,t} ∈ Γ(f⁻¹V_j, M)` with a set `I_j` of covering indices such that
(a) the frame loci `X_{s_{j,t}} := M.frameLocusOn (s_{j,t}) ⊆ f⁻¹V_j`, `t ∈ I_j`, are affine and cover `f⁻¹V_j`;
(b) for `t ∈ I_j`, `Γ(X_{s_{j,t}}, O_X)` is generated by the image of `Γ(V_j, O_S)` and the ratios
`s_{j,t'} / s_{j,t}`.

The proof is organised around the predicate `IsChartFamily f N P I`
("the conclusion of `IsAmple.exists_charts_generators_of_isAffine` for the line bundle `N` and the global
sections `P`, with covering indices `I`") and four transport lemmas:
1. `IsChartFamily.reindex` (reindexing along an equivalence) and `IsChartFamily.of_iso` (transport along an
   isomorphism of line bundles: `nonvanishingLocus_iso`, `Hom.app_res`, `Hom.app_smul`).
2. `IsChartFamily.tensorPow_succ` / `exists_tensorPow` (**common degree**): from a chart family for `N` one for
   `N^{⊗(c+1)}`, indexed by `ι ⊕ ι × ι`: the pure powers `P_ℓ^{⊗(c+1)}` (covering indices; same nonvanishing
   locus by `nonvanishingLocus_tensorPowSection`) and the mixed monomials `P_ℓ^{⊗c} ⊗ P_j`, whose ratio by
   `P_ℓ^{⊗(c+1)}` is `P_j / P_ℓ` (`moduleTensorSection_restrict`, `moduleTensorSection_smul`).
3. `frameLocusOn_restrictTopSection` (**transport along `W.ι`**): for a global section `e` of `N.restrict W.ι`
   and the corresponding section `restrictTopSection N W e ∈ Γ(N, W)`, the frame locus on `X` is the image
   `W.ι ''ᵁ X_e` of the nonvanishing locus. Both sides are characterised as the largest open on which the section
   is a frame (`frameLocusOn_eq_of_isFrame`, `isFrame_res_nonvanishingLocus`, `IsFrame.le_nonvanishingLocus`),
   and frames correspond along `W.ι` (`IsFrame.of_restrict_image`, `IsFrame.restrict_of_image`; local re-proofs of
   the two lemmas of `RelativeProjEvaluationEpi`, to keep the import closure small).
4. `IsChartFamily.restrict_transport`: a chart family for `(f ∣_ U, N.restrict (f⁻¹U).ι)` gives (a), (b) on `X`
   for the sections `restrictTopSection`: affineness by `IsAffineOpen.image_of_isOpenImmersion`, and the
   generation statement by `morphismRestrict_appLE` (`(f ∣_ U).appLE ⊤ _ = f.appLE (U.ι ''ᵁ ⊤) _`), the
   identification `U.ι ''ᵁ ⊤ = U` (`range_appLE_congr`, a `subst`), and the fact that the two module structures on
   `Γ(N.restrict W.ι, O) = Γ(N, W.ι ''ᵁ O)` agree (`eq_smul_restrict_iff`; `Opens.ι_appIso = Iso.refl`).
   The final rewriting of `M.frameLocusOn (s t)` to `W.ι ''ᵁ X_{P t}` is done by `closure_congr_of_eq` (a `subst`
   on an arbitrary open), because the proof term `M.frameLocusOn_le (s t)` blocks a direct `rw`.

**Assembly** (`exists_relative_chart_sections`): `L` from `exists_relativelyAmple`; a finite affine cover
`V_1, …, V_m` of `S` from `isCompact_iff_finite_and_eq_biUnion_affineOpens` (indexed by `Fin m` through
`Fintype.equivFin`); for each `j`, `IsAmple.exists_charts_generators_of_isAffine (f ∣_ V_j) (ι_j^*L)` (degree
`n_j`); `d := ∏_j n_j`, `b_j := d / n_j > 0`; the chain of isomorphisms
`(ι_j^*L^{⊗n_j})^{⊗b_j} ≅ ι_j^*L^{⊗(n_j b_j)} = ι_j^*L^{⊗d} ≅ ι_j^*(L^{⊗d}) ≅ (L^{⊗d}).restrict ι_j`
(`tensorPowMulIso`, `eqToIso`, `pullbackTensorPowIso`, `restrictFunctorIsoPullback`); then items 2, 1, 4.
`M := L^{⊗d}` is a line bundle by `IsLineBundle.tensorPow`. Edge cases: `S = ∅` gives `m = 0`, `d = 1`,
`M = L^{⊗1}`; `f⁻¹V_j = ∅` gives an empty chart family (all statements vacuous).

Used for the immersion of a quasi-projective scheme into a relative Proj (Stacks 07RM). -/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

namespace AlgebraicGeometry.Scheme.Modules

set_option backward.isDefEq.respectTransparency false

variable {X V : AlgebraicGeometry.Scheme.{u}}

/-- Chart family predicate: the conclusion of `IsAmple.exists_charts_generators_of_isAffine`. -/
def IsChartFamily (f : X ⟶ V) (N : X.Modules) [N.IsLineBundle] {ι : Type*} (P : ι → Γ(N, ⊤))
    (I : Set ι) : Prop :=
  (∀ x : X, ∃ ℓ ∈ I, x ∈ N.nonvanishingLocus (P ℓ)) ∧
  (∀ ℓ ∈ I, AlgebraicGeometry.IsAffineOpen (N.nonvanishingLocus (P ℓ))) ∧
  ∀ ℓ ∈ I, Subring.closure
    (Set.range (f.appLE ⊤ (N.nonvanishingLocus (P ℓ)) le_top) ∪
      {g | ∃ j, N.res (le_top : N.nonvanishingLocus (P ℓ) ≤ ⊤) (P j) =
        g • N.res (le_top : N.nonvanishingLocus (P ℓ) ≤ ⊤) (P ℓ)}) = ⊤

theorem isChartFamily_of_charts (f : X ⟶ V) [AlgebraicGeometry.IsAffine V]
    [AlgebraicGeometry.LocallyOfFiniteType f] (L : X.Modules) [L.IsLineBundle]
    (hL : AlgebraicGeometry.IsAmple L) :
    ∃ (n : ℕ) (_ : 0 < n) (ι : Type u) (_ : Fintype ι)
      (P : ι → Γ(AlgebraicGeometry.Scheme.Modules.tensorPow L n, ⊤)) (I : Set ι),
      IsChartFamily f (AlgebraicGeometry.Scheme.Modules.tensorPow L n) P I := by
  obtain ⟨n, hn, ι, hι, P, I, h1, h2, h3⟩ :=
    AlgebraicGeometry.IsAmple.exists_charts_generators_of_isAffine f L hL
  exact ⟨n, hn, ι, hι, P, I, h1, h2, h3⟩

/-- Reindexing a chart family along an equivalence. -/
theorem IsChartFamily.reindex {f : X ⟶ V} {N : X.Modules} [N.IsLineBundle] {ι κ : Type*}
    {P : ι → Γ(N, ⊤)} {I : Set ι} (h : IsChartFamily f N P I) (e : κ ≃ ι) :
    IsChartFamily f N (fun k => P (e k)) (e ⁻¹' I) := by
  obtain ⟨h1, h2, h3⟩ := h
  refine ⟨fun x => ?_, fun k hk => h2 (e k) hk, fun k hk => ?_⟩
  · obtain ⟨ℓ, hℓ, hx⟩ := h1 x
    refine ⟨e.symm ℓ, ?_, ?_⟩
    · show e (e.symm ℓ) ∈ I
      rw [e.apply_symm_apply]; exact hℓ
    · show x ∈ N.nonvanishingLocus (P (e (e.symm ℓ)))
      rw [e.apply_symm_apply]; exact hx
  · have hset : {g : Γ(X, N.nonvanishingLocus (P (e k))) | ∃ j, N.res (le_top : N.nonvanishingLocus (P (e k)) ≤ ⊤) (P (e j)) =
        g • N.res (le_top : N.nonvanishingLocus (P (e k)) ≤ ⊤) (P (e k))} =
        {g | ∃ j, N.res (le_top : N.nonvanishingLocus (P (e k)) ≤ ⊤) (P j) =
        g • N.res (le_top : N.nonvanishingLocus (P (e k)) ≤ ⊤) (P (e k))} := by
      ext g
      simp only [Set.mem_ofPred_eq]
      constructor
      · rintro ⟨j, hj⟩; exact ⟨e j, hj⟩
      · rintro ⟨j, hj⟩; exact ⟨e.symm j, by rw [e.apply_symm_apply]; exact hj⟩
    show Subring.closure (Set.range (f.appLE ⊤ (N.nonvanishingLocus (P (e k))) le_top) ∪
      {g | ∃ j, N.res (le_top : N.nonvanishingLocus (P (e k)) ≤ ⊤) (P (e j)) =
        g • N.res (le_top : N.nonvanishingLocus (P (e k)) ≤ ⊤) (P (e k))}) = ⊤
    rw [hset]
    exact h3 (e k) hk

/-- Transport of a chart family along an isomorphism of line bundles. -/
theorem IsChartFamily.of_iso {f : X ⟶ V} {N N' : X.Modules} [N.IsLineBundle] [N'.IsLineBundle]
    {ι : Type*} {P : ι → Γ(N, ⊤)} {I : Set ι} (h : IsChartFamily f N P I) (e : N ≅ N') :
    IsChartFamily f N' (fun ℓ => e.hom.app ⊤ (P ℓ)) I := by
  obtain ⟨h1, h2, h3⟩ := h
  have hnvl : ∀ ℓ, N'.nonvanishingLocus (e.hom.app ⊤ (P ℓ)) = N.nonvanishingLocus (P ℓ) :=
    fun ℓ => AlgebraicGeometry.Scheme.Modules.nonvanishingLocus_iso e (P ℓ)
  refine ⟨fun x => ?_, fun ℓ hℓ => ?_, fun ℓ hℓ => ?_⟩
  · obtain ⟨ℓ, hℓ, hx⟩ := h1 x
    exact ⟨ℓ, hℓ, by rw [hnvl]; exact hx⟩
  · show AlgebraicGeometry.IsAffineOpen (N'.nonvanishingLocus (e.hom.app ⊤ (P ℓ)))
    rw [hnvl]; exact h2 ℓ hℓ
  · show Subring.closure (Set.range (f.appLE ⊤ (N'.nonvanishingLocus (e.hom.app ⊤ (P ℓ))) le_top) ∪
      {g | ∃ j, N'.res (le_top : N'.nonvanishingLocus (e.hom.app ⊤ (P ℓ)) ≤ ⊤) (e.hom.app ⊤ (P j)) =
        g • N'.res (le_top : N'.nonvanishingLocus (e.hom.app ⊤ (P ℓ)) ≤ ⊤) (e.hom.app ⊤ (P ℓ))}) = ⊤
    rw [hnvl]
    have hset : {g : Γ(X, N.nonvanishingLocus (P ℓ)) | ∃ j, N'.res (le_top : N.nonvanishingLocus (P ℓ) ≤ ⊤) (e.hom.app ⊤ (P j)) =
        g • N'.res (le_top : N.nonvanishingLocus (P ℓ) ≤ ⊤) (e.hom.app ⊤ (P ℓ))} =
        {g | ∃ j, N.res (le_top : N.nonvanishingLocus (P ℓ) ≤ ⊤) (P j) =
        g • N.res (le_top : N.nonvanishingLocus (P ℓ) ≤ ⊤) (P ℓ)} := by
      ext g
      simp only [Set.mem_ofPred_eq]
      constructor
      · rintro ⟨j, hj⟩
        refine ⟨j, (Iso.app_bijective e _).injective ?_⟩
        rw [Hom.app_smul, Hom.app_res, Hom.app_res]
        exact hj
      · rintro ⟨j, hj⟩
        refine ⟨j, ?_⟩
        rw [← Hom.app_res, ← Hom.app_res, ← Hom.app_smul, hj]
    rw [hset]
    exact h3 ℓ hℓ

/-- **Raising a chart family to a power** `c + 1`: the pure powers `P_ℓ^{⊗(c+1)}` (covering indices) and the
mixed monomials `P_ℓ^{⊗c} ⊗ P_j`; the ratio `(P_ℓ^{⊗c} ⊗ P_j)/P_ℓ^{⊗(c+1)} = P_j/P_ℓ`. -/
theorem IsChartFamily.tensorPow_succ {f : X ⟶ V} {N : X.Modules} [N.IsLineBundle]
    {ι : Type*} {P : ι → Γ(N, ⊤)} {I : Set ι} (h : IsChartFamily f N P I) (c : ℕ) :
    IsChartFamily f (AlgebraicGeometry.Scheme.Modules.tensorPow N (c + 1))
      (Sum.elim (fun ℓ => AlgebraicGeometry.Scheme.Modules.tensorPowSection (P ℓ) (c + 1))
        (fun p : ι × ι => (sectionTensor (AlgebraicGeometry.Scheme.Modules.tensorPowSection (P p.2) c) (P p.1) :
          Γ(AlgebraicGeometry.Scheme.Modules.tensorPow N (c + 1), ⊤))))
      (Sum.inl '' I) := by
  obtain ⟨h1, h2, h3⟩ := h
  have hnvl : ∀ ℓ, (AlgebraicGeometry.Scheme.Modules.tensorPow N (c + 1)).nonvanishingLocus
      (AlgebraicGeometry.Scheme.Modules.tensorPowSection (P ℓ) (c + 1)) = N.nonvanishingLocus (P ℓ) :=
    fun ℓ => nonvanishingLocus_tensorPowSection N (P ℓ) (Nat.succ_pos c)
  refine ⟨fun x => ?_, ?_, ?_⟩
  · obtain ⟨ℓ, hℓ, hx⟩ := h1 x
    refine ⟨Sum.inl ℓ, ⟨ℓ, hℓ, rfl⟩, ?_⟩
    show x ∈ (AlgebraicGeometry.Scheme.Modules.tensorPow N (c + 1)).nonvanishingLocus
      (AlgebraicGeometry.Scheme.Modules.tensorPowSection (P ℓ) (c + 1))
    rw [hnvl]; exact hx
  · rintro _ ⟨ℓ, hℓ, rfl⟩
    show AlgebraicGeometry.IsAffineOpen ((AlgebraicGeometry.Scheme.Modules.tensorPow N (c + 1)).nonvanishingLocus
      (AlgebraicGeometry.Scheme.Modules.tensorPowSection (P ℓ) (c + 1)))
    rw [hnvl]; exact h2 ℓ hℓ
  · rintro _ ⟨ℓ, hℓ, rfl⟩
    set T := AlgebraicGeometry.Scheme.Modules.tensorPow N (c + 1) with hT
    set Q : ι ⊕ ι × ι → Γ(T, ⊤) := Sum.elim (fun ℓ => AlgebraicGeometry.Scheme.Modules.tensorPowSection (P ℓ) (c + 1))
        (fun p : ι × ι => (sectionTensor (AlgebraicGeometry.Scheme.Modules.tensorPowSection (P p.2) c) (P p.1) :
          Γ(T, ⊤))) with hQ
    show Subring.closure (Set.range (f.appLE ⊤ (T.nonvanishingLocus (Q (Sum.inl ℓ))) le_top) ∪
      {g | ∃ j, T.res (le_top : T.nonvanishingLocus (Q (Sum.inl ℓ)) ≤ ⊤) (Q j) =
        g • T.res (le_top : T.nonvanishingLocus (Q (Sum.inl ℓ)) ≤ ⊤) (Q (Sum.inl ℓ))}) = ⊤
    have hnvl' : T.nonvanishingLocus (Q (Sum.inl ℓ)) = N.nonvanishingLocus (P ℓ) := hnvl ℓ
    rw [hnvl']
    refine top_unique ?_
    rw [← h3 ℓ hℓ]
    refine Subring.closure_mono (Set.union_subset_union_right _ ?_)
    rintro g ⟨j, hj⟩
    refine ⟨Sum.inr (j, ℓ), ?_⟩
    -- the mixed monomial `P_ℓ^{⊗c} ⊗ P_j` restricted: `(P_ℓ^{⊗c}|) ⊗ (P_j|) = (P_ℓ^{⊗c}|) ⊗ (g • P_ℓ|) = g • (P_ℓ^{⊗(c+1)}|)`
    have hle : N.nonvanishingLocus (P ℓ) ≤ ⊤ := le_top
    show T.res hle (sectionTensor (AlgebraicGeometry.Scheme.Modules.tensorPowSection (P ℓ) c) (P j)) =
      g • T.res hle (sectionTensor (AlgebraicGeometry.Scheme.Modules.tensorPowSection (P ℓ) c) (P ℓ))
    have e1 : T.res hle (sectionTensor (AlgebraicGeometry.Scheme.Modules.tensorPowSection (P ℓ) c) (P j)) =
        AlgebraicGeometry.Scheme.Modules.moduleTensorSection
          ((AlgebraicGeometry.Scheme.Modules.tensorPow N c).res hle
            (AlgebraicGeometry.Scheme.Modules.tensorPowSection (P ℓ) c)) (N.res hle (P j)) :=
      AlgebraicGeometry.Scheme.Modules.moduleTensorSection_restrict (homOfLE hle) _ _
    have e2 : T.res hle (sectionTensor (AlgebraicGeometry.Scheme.Modules.tensorPowSection (P ℓ) c) (P ℓ)) =
        AlgebraicGeometry.Scheme.Modules.moduleTensorSection
          ((AlgebraicGeometry.Scheme.Modules.tensorPow N c).res hle
            (AlgebraicGeometry.Scheme.Modules.tensorPowSection (P ℓ) c)) (N.res hle (P ℓ)) :=
      AlgebraicGeometry.Scheme.Modules.moduleTensorSection_restrict (homOfLE hle) _ _
    rw [e1, e2, hj]
    have e3 := AlgebraicGeometry.Scheme.Modules.moduleTensorSection_smul (1 : Γ(X, N.nonvanishingLocus (P ℓ))) g
      ((AlgebraicGeometry.Scheme.Modules.tensorPow N c).res hle
        (AlgebraicGeometry.Scheme.Modules.tensorPowSection (P ℓ) c)) (N.res hle (P ℓ))
    rw [one_smul, one_mul] at e3
    exact e3

/-- Existence form: a chart family for `N` yields one for `N^{⊗b}` for every `b > 0`. -/
theorem IsChartFamily.exists_tensorPow {f : X ⟶ V} {N : X.Modules} [N.IsLineBundle]
    {ι : Type u} [Fintype ι] {P : ι → Γ(N, ⊤)} {I : Set ι} (h : IsChartFamily f N P I) {b : ℕ}
    (hb : 0 < b) :
    ∃ (κ : Type u) (_ : Fintype κ) (Q : κ → Γ(AlgebraicGeometry.Scheme.Modules.tensorPow N b, ⊤)) (J : Set κ),
      IsChartFamily f (AlgebraicGeometry.Scheme.Modules.tensorPow N b) Q J := by
  classical
  obtain ⟨c, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hb.ne'
  exact ⟨ι ⊕ ι × ι, inferInstance, _, _, h.tensorPow_succ c⟩

/-! ## Transport along the open immersion `W.ι` -/

/-- Frames along an equality of opens. -/
theorem IsFrame.congr_opens {N : X.Modules} {W W' : X.Opens} {e : Γ(N, W)} (hf : IsFrame N W e)
    (h : W = W') : IsFrame N W' (N.res (le_of_eq h.symm) e) := by
  subst h
  simpa using hf

/-- Bijectivity of `r ↦ r • e|` depends only on the open (transport along an equality of opens). -/
theorem bijective_smul_res_congr_opens' {N : X.Modules} {W V V' : X.Opens} (hV : V ≤ W) (hV' : V' ≤ W)
    (h : V = V') (e : Γ(N, W))
    (hb : Function.Bijective (fun r : Γ(X, V) => r • N.res hV e)) :
    Function.Bijective (fun r : Γ(X, V') => r • N.res hV' e) := by
  subst h
  exact hb

/-- `e` a frame of `N.restrict g` on `O` ⇒ a frame of `N` on `g ''ᵁ O` (local re-proof of
`IsFrame.restrictAppIso_hom_of_restrict`, to keep the import closure small). -/
theorem IsFrame.of_restrict_image {Y : AlgebraicGeometry.Scheme.{u}} (g : Y ⟶ X)
    [AlgebraicGeometry.IsOpenImmersion g] {N : X.Modules} {O : Y.Opens} {e : Γ(N.restrict g, O)}
    (hf : IsFrame (N.restrict g) O e) : IsFrame N (g ''ᵁ O) (e : Γ(N, g ''ᵁ O)) := by
  intro W' h
  have hO' : g ⁻¹ᵁ W' ≤ O := by
    have := g.preimage_mono h
    rwa [g.preimage_image_eq] at this
  have hW' : g ''ᵁ (g ⁻¹ᵁ W') = W' := by
    rw [g.image_preimage_eq_opensRange_inf]
    exact inf_eq_right.mpr (h.trans (g.image_le_opensRange O))
  refine bijective_smul_res_congr_opens' (g.image_mono hO') h hW' _ ?_
  have hb := hf (g ⁻¹ᵁ W') hO'
  have hfun : (fun r : Γ(Y, g ⁻¹ᵁ W') => r • (N.restrict g).res hO' e) =
      (fun r' : Γ(X, g ''ᵁ (g ⁻¹ᵁ W')) =>
        r' • N.res (g.image_mono hO') (e : Γ(N, g ''ᵁ O))) ∘
        (g.appIso (g ⁻¹ᵁ W')).inv := rfl
  rw [hfun] at hb
  exact (Function.Bijective.of_comp_iff _
    (ConcreteCategory.bijective_of_isIso (g.appIso (g ⁻¹ᵁ W')).inv)).mp hb

/-- `e` a frame of `N` on `g ''ᵁ O` ⇒ a frame of `N.restrict g` on `O` (local re-proof of
`IsFrame.restrictAppIso_inv_of_image`). -/
theorem IsFrame.restrict_of_image {Y : AlgebraicGeometry.Scheme.{u}} (g : Y ⟶ X)
    [AlgebraicGeometry.IsOpenImmersion g] {N : X.Modules} {O : Y.Opens} {e : Γ(N, g ''ᵁ O)}
    (hf : IsFrame N (g ''ᵁ O) e) : IsFrame (N.restrict g) O (e : Γ(N.restrict g, O)) := by
  intro O' h
  have hfun : (fun r : Γ(Y, O') => r • (N.restrict g).res h (e : Γ(N.restrict g, O))) =
      (fun r' : Γ(X, g ''ᵁ O') => r' • N.res (g.image_mono h) e) ∘ (g.appIso O').inv := rfl
  rw [hfun]
  exact (hf _ (g.image_mono h)).comp (ConcreteCategory.bijective_of_isIso (g.appIso O').inv)

/-- The section of `N` over `W` corresponding to a global section of `N.restrict W.ι`
(`Γ(N.restrict W.ι, ⊤) = Γ(N, W.ι ''ᵁ ⊤)`, then restrict along `W = W.ι ''ᵁ ⊤`). -/
def restrictTopSection (N : X.Modules) (W : X.Opens) (e : Γ(N.restrict W.ι, ⊤)) : Γ(N, W) :=
  N.res (le_of_eq (Opens.ι_image_top W).symm) (e : Γ(N, W.ι ''ᵁ ⊤))

theorem res_restrictTopSection (N : X.Modules) (W : X.Opens) (e : Γ(N.restrict W.ι, ⊤))
    {O : W.toScheme.Opens} (h : W.ι ''ᵁ O ≤ W) :
    N.res h (restrictTopSection N W e) =
      ((N.restrict W.ι).res (le_top : O ≤ ⊤) e : Γ(N, W.ι ''ᵁ O)) := by
  unfold restrictTopSection
  rw [res_res]
  rfl

/-- **Frame locus of the transported section = image of the nonvanishing locus.** -/
theorem frameLocusOn_restrictTopSection (N : X.Modules) [N.IsLineBundle] (W : X.Opens)
    (e : Γ(N.restrict W.ι, ⊤)) :
    N.frameLocusOn (restrictTopSection N W e) =
      W.ι ''ᵁ ((N.restrict W.ι).nonvanishingLocus e) := by
  refine frameLocusOn_eq_of_isFrame (W.ι_image_le _) ?_ ?_
  · rw [res_restrictTopSection]
    exact (isFrame_res_nonvanishingLocus (N.restrict W.ι) e).of_restrict_image W.ι
  · intro W' h' hf
    have hW' : W.ι ''ᵁ (W.ι ⁻¹ᵁ W') = W' := by
      rw [W.ι.image_preimage_eq_opensRange_inf, Opens.opensRange_ι]
      exact inf_eq_right.mpr h'
    have hf' := hf.congr_opens hW'.symm
    rw [res_res, res_restrictTopSection] at hf'
    have hf'' := hf'.restrict_of_image W.ι
    have hle := IsFrame.le_nonvanishingLocus hf''
    rw [← hW']
    exact W.ι.image_mono hle

/-- Scalar multiplication on `N.restrict g` is scalar multiplication on `N` through `(g.appIso O).inv`
(definitional). -/
theorem restrict_smul_eq_appIso_inv {Y : AlgebraicGeometry.Scheme.{u}} (g : Y ⟶ X) [AlgebraicGeometry.IsOpenImmersion g]
    (N : X.Modules) {O : Y.Opens} (r : Γ(Y, O)) (y : Γ(N.restrict g, O)) :
    r • y = @HSMul.hSMul Γ(X, g ''ᵁ O) Γ(N, g ''ᵁ O) Γ(N, g ''ᵁ O) instHSMul ((g.appIso O).inv r) y := rfl

theorem ι_appIso_inv_apply (W : X.Opens) {O : W.toScheme.Opens} (r : Γ(W.toScheme, O)) :
    (W.ι.appIso O).inv r = r := by
  rw [Opens.ι_appIso]
  rfl

/-- `x = g • y` in `Γ(N.restrict W.ι, O)` iff the same equation holds in `Γ(N, W.ι ''ᵁ O)`
(the two module structures agree because `W.ι.appIso O = Iso.refl`). -/
theorem eq_smul_restrict_iff (W : X.Opens) (N : X.Modules) {O : W.toScheme.Opens}
    (x y : Γ(N.restrict W.ι, O)) (g : Γ(W.toScheme, O)) :
    x = g • y ↔
      (x : Γ(N, W.ι ''ᵁ O)) = @HSMul.hSMul Γ(X, W.ι ''ᵁ O) Γ(N, W.ι ''ᵁ O) Γ(N, W.ι ''ᵁ O) instHSMul g y := by
  rw [restrict_smul_eq_appIso_inv, ι_appIso_inv_apply]

theorem range_appLE_congr {S : AlgebraicGeometry.Scheme.{u}} (f : X ⟶ S) {U U' : S.Opens} (h : U = U')
    {W : X.Opens} (e : W ≤ f ⁻¹ᵁ U) (e' : W ≤ f ⁻¹ᵁ U') :
    Set.range (f.appLE U W e) = Set.range (f.appLE U' W e') := by
  subst h
  rfl

theorem closure_congr_of_eq {S : AlgebraicGeometry.Scheme.{u}} (f : X ⟶ S) (U : S.Opens) (N : X.Modules)
    {ι : Type*} (s : ι → Γ(N, f ⁻¹ᵁ U)) (t : ι) {W W' : X.Opens} (hW : W ≤ f ⁻¹ᵁ U) (hW' : W' ≤ f ⁻¹ᵁ U)
    (h : W = W')
    (H : Subring.closure (Set.range (f.appLE U W hW) ∪
      {g | ∃ t', N.res hW (s t') = g • N.res hW (s t)}) = ⊤) :
    Subring.closure (Set.range (f.appLE U W' hW') ∪
      {g | ∃ t', N.res hW' (s t') = g • N.res hW' (s t)}) = ⊤ := by
  subst h
  exact H

/-- **Transport of a chart family from `f⁻¹U` to `X`.** -/
theorem IsChartFamily.restrict_transport {S : AlgebraicGeometry.Scheme.{u}} {f : X ⟶ S} (U : S.Opens)
    {N : X.Modules} [N.IsLineBundle] {ι : Type*} {P : ι → Γ(N.restrict (f ⁻¹ᵁ U).ι, ⊤)} {I : Set ι}
    (h : IsChartFamily (f ∣_ U) (N.restrict (f ⁻¹ᵁ U).ι) P I) :
    (∀ x : X, x ∈ f ⁻¹ᵁ U → ∃ t ∈ I, x ∈ N.frameLocusOn (restrictTopSection N (f ⁻¹ᵁ U) (P t))) ∧
    (∀ t ∈ I, AlgebraicGeometry.IsAffineOpen (N.frameLocusOn (restrictTopSection N (f ⁻¹ᵁ U) (P t)))) ∧
    ∀ t ∈ I, Subring.closure
      (Set.range (f.appLE U (N.frameLocusOn (restrictTopSection N (f ⁻¹ᵁ U) (P t)))
          (N.frameLocusOn_le (restrictTopSection N (f ⁻¹ᵁ U) (P t)))) ∪
        {g | ∃ t', N.res (N.frameLocusOn_le (restrictTopSection N (f ⁻¹ᵁ U) (P t)))
            (restrictTopSection N (f ⁻¹ᵁ U) (P t')) =
          g • N.res (N.frameLocusOn_le (restrictTopSection N (f ⁻¹ᵁ U) (P t)))
            (restrictTopSection N (f ⁻¹ᵁ U) (P t))}) = ⊤ := by
  obtain ⟨h1, h2, h3⟩ := h
  refine ⟨fun x hx => ?_, fun t ht => ?_, fun t ht => ?_⟩
  · obtain ⟨t, ht, hxt⟩ := h1 ⟨x, hx⟩
    refine ⟨t, ht, ?_⟩
    rw [frameLocusOn_restrictTopSection]
    exact ⟨⟨x, hx⟩, hxt, rfl⟩
  · rw [frameLocusOn_restrictTopSection]
    exact (h2 t ht).image_of_isOpenImmersion _
  · refine closure_congr_of_eq f U N (fun t' => restrictTopSection N (f ⁻¹ᵁ U) (P t')) t
      ((f ⁻¹ᵁ U).ι_image_le _) (N.frameLocusOn_le _) (frameLocusOn_restrictTopSection N _ (P t)).symm ?_
    have h3' := h3 t ht
    rw [morphismRestrict_appLE] at h3'
    have e1 : Set.range (f.appLE U ((f ⁻¹ᵁ U).ι ''ᵁ ((N.restrict (f ⁻¹ᵁ U).ι).nonvanishingLocus (P t)))
        ((f ⁻¹ᵁ U).ι_image_le _)) =
        Set.range (f.appLE (U.ι ''ᵁ ⊤) ((f ⁻¹ᵁ U).ι ''ᵁ ((N.restrict (f ⁻¹ᵁ U).ι).nonvanishingLocus (P t)))
          ((Set.image_mono le_top).trans (image_morphismRestrict_preimage f U ⊤).le)) :=
      range_appLE_congr f (Opens.ι_image_top U).symm _ _
    have e2 : {g : Γ(X, (f ⁻¹ᵁ U).ι ''ᵁ ((N.restrict (f ⁻¹ᵁ U).ι).nonvanishingLocus (P t))) |
          ∃ t', N.res ((f ⁻¹ᵁ U).ι_image_le ((N.restrict (f ⁻¹ᵁ U).ι).nonvanishingLocus (P t)))
          (restrictTopSection N (f ⁻¹ᵁ U) (P t')) =
        g • N.res ((f ⁻¹ᵁ U).ι_image_le ((N.restrict (f ⁻¹ᵁ U).ι).nonvanishingLocus (P t)))
          (restrictTopSection N (f ⁻¹ᵁ U) (P t))} =
        {g : Γ((f ⁻¹ᵁ U).toScheme, (N.restrict (f ⁻¹ᵁ U).ι).nonvanishingLocus (P t)) |
          ∃ t', (N.restrict (f ⁻¹ᵁ U).ι).res
            (le_top : (N.restrict (f ⁻¹ᵁ U).ι).nonvanishingLocus (P t) ≤ ⊤) (P t') =
          g • (N.restrict (f ⁻¹ᵁ U).ι).res
            (le_top : (N.restrict (f ⁻¹ᵁ U).ι).nonvanishingLocus (P t) ≤ ⊤) (P t)} := by
      ext g
      simp only [Set.mem_ofPred_eq, res_restrictTopSection]
      constructor
      · rintro ⟨t', ht'⟩
        exact ⟨t', (eq_smul_restrict_iff (f ⁻¹ᵁ U) N _ _ g).mpr ht'⟩
      · rintro ⟨t', ht'⟩
        exact ⟨t', (eq_smul_restrict_iff (f ⁻¹ᵁ U) N _ _ g).mp ht'⟩
    rw [e1, e2]
    exact h3'

end AlgebraicGeometry.Scheme.Modules

/-- **Relative chart sections** (Stacks 07RM, paragraphs 1–2): a line bundle `M` on `X`, a finite affine cover
`V_j` of `S` and finitely many sections `s_{j,t} ∈ Γ(f⁻¹V_j, M)` whose frame loci (`t ∈ I_j`) are affine, cover
`f⁻¹V_j`, and have coordinate rings generated over `Γ(V_j, O)` by the ratios `s_{j,t'}/s_{j,t}`. -/
theorem AlgebraicGeometry.IsQuasiProjectiveMorphism.exists_relative_chart_sections
    {X S : AlgebraicGeometry.Scheme.{u}} (f : X ⟶ S) [AlgebraicGeometry.IsQuasiProjectiveMorphism f]
    [CompactSpace S] :
    ∃ (M : X.Modules) (_ : M.IsLineBundle) (m : ℕ) (V : Fin m → S.affineOpens) (n : Fin m → ℕ)
      (s : ∀ j, Fin (n j) → Γ(M, f ⁻¹ᵁ (V j).1)) (I : ∀ j, Set (Fin (n j))),
      (∀ y : S, ∃ j, y ∈ (V j).1) ∧
      (∀ j (x : X), x ∈ f ⁻¹ᵁ (V j).1 → ∃ t ∈ I j, x ∈ M.frameLocusOn (s j t)) ∧
      (∀ j, ∀ t ∈ I j, AlgebraicGeometry.IsAffineOpen (M.frameLocusOn (s j t))) ∧
      ∀ j, ∀ t ∈ I j, Subring.closure
        (Set.range (f.appLE (V j).1 (M.frameLocusOn (s j t)) (M.frameLocusOn_le (s j t))) ∪
          {g | ∃ t', M.res (M.frameLocusOn_le (s j t)) (s j t') =
            g • M.res (M.frameLocusOn_le (s j t)) (s j t)}) = ⊤ := by
  classical
  open AlgebraicGeometry.Scheme.Modules in
  obtain ⟨L, hL, hample⟩ := AlgebraicGeometry.IsQuasiProjectiveMorphism.exists_relativelyAmple (f := f)
  have : AlgebraicGeometry.LocallyOfFiniteType f :=
    AlgebraicGeometry.IsQuasiProjectiveMorphism.locallyOfFiniteType (f := f)
  -- Step 1: finite affine cover of `S`
  have hcpt : IsCompact (X := S) ((⊤ : S.Opens) : Set S) := by
    rw [Opens.coe_top]; exact isCompact_univ
  obtain ⟨sV, hsfin, hsV⟩ := AlgebraicGeometry.isCompact_iff_finite_and_eq_biUnion_affineOpens.mp hcpt
  let _ : Fintype sV := hsfin.fintype
  let eV : sV ≃ Fin (Fintype.card sV) := Fintype.equivFin sV
  let V : Fin (Fintype.card sV) → S.affineOpens := fun j => (eV.symm j).1
  have hVcov : ∀ y : S, ∃ j, y ∈ (V j).1 := by
    intro y
    have hy : y ∈ (⊤ : S.Opens) := trivial
    rw [hsV, Opens.mem_iSup] at hy
    obtain ⟨i, hi⟩ := hy
    rw [Opens.mem_iSup] at hi
    obtain ⟨his, hyi⟩ := hi
    refine ⟨eV ⟨i, his⟩, ?_⟩
    show y ∈ ((eV.symm (eV ⟨i, his⟩)).1 : S.Opens)
    rw [eV.symm_apply_apply]
    exact hyi
  -- Step 2: charts over each `V j`
  have hcharts : ∀ j, ∃ (n : ℕ) (_ : 0 < n) (κ : Type u) (_ : Fintype κ)
      (P : κ → Γ(AlgebraicGeometry.Scheme.Modules.tensorPow
        ((AlgebraicGeometry.Scheme.Modules.pullback (f ⁻¹ᵁ (V j).1).ι).obj L) n, ⊤)) (I : Set κ),
      AlgebraicGeometry.Scheme.Modules.IsChartFamily (f ∣_ (V j).1) (AlgebraicGeometry.Scheme.Modules.tensorPow
        ((AlgebraicGeometry.Scheme.Modules.pullback (f ⁻¹ᵁ (V j).1).ι).obj L) n) P I :=
    fun j => AlgebraicGeometry.Scheme.Modules.isChartFamily_of_charts (f ∣_ (V j).1) _ (hample (V j))
  choose n hn κ hκ P I hP using hcharts
  -- Step 4: common degree
  let d : ℕ := ∏ j, n j
  have hd : 0 < d := Finset.prod_pos (fun j _ => hn j)
  have hdvd : ∀ j, n j ∣ d := fun j => Finset.dvd_prod_of_mem n (Finset.mem_univ j)
  have hdiv : ∀ j, n j * (d / n j) = d := fun j => Nat.mul_div_cancel' (hdvd j)
  have hb : ∀ j, 0 < d / n j := fun j => Nat.div_pos (Nat.le_of_dvd hd (hdvd j)) (hn j)
  -- Step 3: transport to `X`
  have hfinal : ∀ j, ∃ (n' : ℕ) (s : Fin n' → Γ(AlgebraicGeometry.Scheme.Modules.tensorPow L d, f ⁻¹ᵁ (V j).1))
      (I' : Set (Fin n')),
      (∀ x : X, x ∈ f ⁻¹ᵁ (V j).1 → ∃ t ∈ I', x ∈ (AlgebraicGeometry.Scheme.Modules.tensorPow L d).frameLocusOn (s t)) ∧
      (∀ t ∈ I', AlgebraicGeometry.IsAffineOpen ((AlgebraicGeometry.Scheme.Modules.tensorPow L d).frameLocusOn (s t))) ∧
      ∀ t ∈ I', Subring.closure
        (Set.range (f.appLE (V j).1 ((AlgebraicGeometry.Scheme.Modules.tensorPow L d).frameLocusOn (s t))
            ((AlgebraicGeometry.Scheme.Modules.tensorPow L d).frameLocusOn_le (s t))) ∪
          {g | ∃ t', (AlgebraicGeometry.Scheme.Modules.tensorPow L d).res
              ((AlgebraicGeometry.Scheme.Modules.tensorPow L d).frameLocusOn_le (s t)) (s t') =
            g • (AlgebraicGeometry.Scheme.Modules.tensorPow L d).res
              ((AlgebraicGeometry.Scheme.Modules.tensorPow L d).frameLocusOn_le (s t)) (s t)}) = ⊤ := by
    intro j
    obtain ⟨κ', hκ', Q, J, hQ⟩ := (hP j).exists_tensorPow (hb j)
    let e : AlgebraicGeometry.Scheme.Modules.tensorPow (AlgebraicGeometry.Scheme.Modules.tensorPow
        ((AlgebraicGeometry.Scheme.Modules.pullback (f ⁻¹ᵁ (V j).1).ι).obj L) (n j)) (d / n j) ≅
        (AlgebraicGeometry.Scheme.Modules.tensorPow L d).restrict (f ⁻¹ᵁ (V j).1).ι :=
      AlgebraicGeometry.Scheme.Modules.tensorPowMulIso _ (n j) (d / n j) ≪≫
        eqToIso (congrArg (AlgebraicGeometry.Scheme.Modules.tensorPow _) (hdiv j)) ≪≫
        (AlgebraicGeometry.Scheme.Modules.pullbackTensorPowIso (f ⁻¹ᵁ (V j).1).ι L d).symm ≪≫
        ((AlgebraicGeometry.Scheme.Modules.restrictFunctorIsoPullback (f ⁻¹ᵁ (V j).1).ι).app
          (AlgebraicGeometry.Scheme.Modules.tensorPow L d)).symm
    have hQ' := (hQ.of_iso e).reindex (Fintype.equivFin κ').symm
    obtain ⟨ha, hb', hc⟩ := hQ'.restrict_transport (V j).1
    exact ⟨_, _, _, ha, hb', hc⟩
  choose n' s I' hfinal using hfinal
  exact ⟨AlgebraicGeometry.Scheme.Modules.tensorPow L d, inferInstance, Fintype.card sV, V, n', s, I', hVcov,
    fun j => (hfinal j).1, fun j => (hfinal j).2.1, fun j => (hfinal j).2.2⟩

end
