import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Chow.DivisorOperator.RatDivisorOperator

/-! # Successive caps with pairwise commuting operators are independent of the order

For a list of pairwise commuting ℚ-divisor operators, the successive caps are independent of the order
(a purely combinatorial statement, proved by induction on `List.Perm`). -/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- `congr` along a proof of `p = p` is the identity (definitional, by K-like reduction of `Eq.rec`). -/
theorem AlgebraicGeometry.ChowGroupRat.congr_refl_eq_id (X : AlgebraicGeometry.Scheme.{u}) {p : ℕ}
    (e : p = p) : AlgebraicGeometry.ChowGroupRat.congr X e = LinearMap.id := rfl

/-- Two index casts compose to one (as linear maps). -/
theorem AlgebraicGeometry.ChowGroupRat.congr_comp_congr_of_eq (X : AlgebraicGeometry.Scheme.{u})
    {p q r : ℕ} (e : p = q) (e' : q = r) :
    (AlgebraicGeometry.ChowGroupRat.congr X e').comp (AlgebraicGeometry.ChowGroupRat.congr X e)
      = AlgebraicGeometry.ChowGroupRat.congr X (e.trans e') := by
  subst e e'; rfl

/-- A divisor operator commutes with the index cast (as linear maps): for `e : p = q`,
`congr e ∘ D p = D q ∘ congr (e + 1)`. -/
theorem AlgebraicGeometry.ChowGroupRat.congr_comp_ratDivisorOp (X : AlgebraicGeometry.Scheme.{u})
    (D : AlgebraicGeometry.RatDivisorOp X) {p q : ℕ} (e : p = q) (e1 : p + 1 = q + 1) :
    (AlgebraicGeometry.ChowGroupRat.congr X e).comp (D p)
      = (D q).comp (AlgebraicGeometry.ChowGroupRat.congr X e1) := by
  subst e; rfl

/-- `capList_perm` with an arbitrary proof of the index equality (so that it can be proved by
induction on the permutation; the proof of the equality is irrelevant). -/
theorem AlgebraicGeometry.RatDivisorOp.capList_perm_of_eq {X : AlgebraicGeometry.Scheme.{u}}
    {l l' : List (AlgebraicGeometry.RatDivisorOp X)} (h : l.Perm l')
    (hc : ∀ D ∈ l, ∀ E ∈ l, ∀ d : ℕ, (D d).comp (E (d + 1)) = (E d).comp (D (d + 1))) (d : ℕ)
    (e : d + l.length = d + l'.length) :
    AlgebraicGeometry.RatDivisorOp.capList l d
      = (AlgebraicGeometry.RatDivisorOp.capList l' d).comp
          (AlgebraicGeometry.ChowGroupRat.congr X e) := by
  induction h generalizing d with
  | nil =>
    rw [AlgebraicGeometry.ChowGroupRat.congr_refl_eq_id, LinearMap.comp_id]
  | cons x h ih =>
    rename_i l₁ l₂
    have hc' : ∀ D ∈ l₁, ∀ E ∈ l₁, ∀ d : ℕ, (D d).comp (E (d + 1)) = (E d).comp (D (d + 1)) :=
      fun D hD E hE => hc D (List.mem_cons_of_mem x hD) E (List.mem_cons_of_mem x hE)
    have e₁ : d + l₁.length = d + l₂.length := by rw [h.length_eq]
    simp only [AlgebraicGeometry.RatDivisorOp.capList]
    rw [ih hc' d e₁, LinearMap.comp_assoc, LinearMap.comp_assoc,
      AlgebraicGeometry.ChowGroupRat.congr_comp_ratDivisorOp X x e₁ e]
  | swap x y l =>
    simp only [AlgebraicGeometry.RatDivisorOp.capList, List.length_cons]
    rw [AlgebraicGeometry.ChowGroupRat.congr_refl_eq_id, LinearMap.comp_id, LinearMap.comp_assoc,
      LinearMap.comp_assoc]
    congr 1
    exact hc x (by simp) y (by simp) (d + l.length)
  | trans h₁ h₂ ih₁ ih₂ =>
    rename_i l₁ l₂ l₃
    have hc₂ : ∀ D ∈ l₂, ∀ E ∈ l₂, ∀ d : ℕ, (D d).comp (E (d + 1)) = (E d).comp (D (d + 1)) :=
      fun D hD E hE => hc D (h₁.mem_iff.mpr hD) E (h₁.mem_iff.mpr hE)
    have e₁ : d + l₁.length = d + l₂.length := by rw [h₁.length_eq]
    have e₂ : d + l₂.length = d + l₃.length := by rw [h₂.length_eq]
    rw [ih₁ hc d e₁, ih₂ hc₂ d e₂, LinearMap.comp_assoc,
      AlgebraicGeometry.ChowGroupRat.congr_comp_congr_of_eq]

/-- For a list of pairwise commuting operators, the successive caps are independent of the order (purely
combinatorial).

Proof sketch: permutations are generated by adjacent transpositions; induct on `h : l.Perm l'` with
`List.Perm.recOn` (cases nil / cons / swap / trans).
* nil: both sides are `LinearMap.id`, and `ChowGroupRat.congr X rfl = id`.
* cons `D`: `capList (D :: l) d = (capList l d).comp (D (d + l.length))`; use the induction hypothesis;
  `h.length_eq` makes `D (d + l.length)` and `D (d + l'.length)` differ by an index transport — for a
  general `e : p = q`, `D q ∘ congr (e+1) = congr e ∘ D p` (`subst e; rfl`).
* swap `D E`: `capList (E :: D :: l) d = capList l d ∘ D (d+n) ∘ E (d+n+1)` versus
  `capList l d ∘ E (d+n) ∘ D (d+n+1)`; use the commutativity `hc`.
* trans: compose the two transports (`congr_trans`); `hc` is transported along the permutation by
  `List.Perm.mem_iff`.
Index equalities are `subst`ed before `rfl`/`simp`; `congr` is never unfolded. The generalized form
`capList_perm_of_eq` (with an arbitrary index equality `e : d + l.length = d + l'.length`, convenient for
`induction … generalizing d`) is proved first, and this theorem is the special case
`e := by rw [h.length_eq]`. The auxiliary lemmas `ChowGroupRat.congr_refl_eq_id` /
`congr_comp_congr_of_eq` / `congr_comp_ratDivisorOp` are all `subst; rfl`. -/
theorem AlgebraicGeometry.RatDivisorOp.capList_perm {X : AlgebraicGeometry.Scheme.{u}}
    {l l' : List (AlgebraicGeometry.RatDivisorOp X)} (h : l.Perm l')
    (hc : ∀ D ∈ l, ∀ E ∈ l, ∀ d : ℕ, (D d).comp (E (d + 1)) = (E d).comp (D (d + 1))) (d : ℕ) :
    AlgebraicGeometry.RatDivisorOp.capList l d
      = (AlgebraicGeometry.RatDivisorOp.capList l' d).comp
          (AlgebraicGeometry.ChowGroupRat.congr X (by rw [h.length_eq])) :=
  AlgebraicGeometry.RatDivisorOp.capList_perm_of_eq h hc d _

end
