import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Varieties.Smooth.SmoothVarietyRegularInCodimOne
import MiyaokaMori.AlgebraicGeometry.Divisors.LineBundle.ClIsoPicPrincipal
import MiyaokaMori.AlgebraicGeometry.Divisors.LineBundle.DivisorLineBundleHom
import MiyaokaMori.AlgebraicGeometry.Divisors.LineBundle.LineBundleIsoLinearEquivalent
import MiyaokaMori.AlgebraicGeometry.Divisors.LineBundle.LineBundleIsDivisorial
import MiyaokaMori.AlgebraicGeometry.Divisors.Weil.DivisorClassGroup
import MiyaokaMori.AlgebraicGeometry.Divisors.LineBundle.PicardGroup
import MiyaokaMori.AlgebraicGeometry.Varieties.Basic.SmoothProjectiveVariety

/-! # `Cl(X) ≅ Pic(X)` on a smooth variety

On a smooth projective variety, `D ↦ O_X(D)` induces an isomorphism from the divisor class group to
the Picard group (Hartshorne II.6.16: `CDiv / principal ≅ Pic`, combined with Cartier = Weil).
Source: Hartshorne II.6.13–6.16.

Hypotheses (Hartshorne II.6.16): Cor. 6.16 requires `X` Noetherian, integral, separated and locally
factorial, and the proof is II.6.11 (`CDiv ≅ Div`, principal to principal) plus II.6.15 (`X` integral
gives `CaCl X ≅ Pic X`); `SmoothProjectiveVariety k` satisfies all of these. II.6.15 needs only `X`
integral, and 6.14 (injectivity) holds for any scheme.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- A Weil divisor `W` is sent to the isomorphism class of `O_X(D)`, where `D := cartierWeilEquiv⁻¹ W`
(Cartier = Weil on a smooth variety). -/
noncomputable def weilToPicardFun {k : Type u} [Field k] (X : SmoothProjectiveVariety k)
    (W : X.toScheme.WeilDivisor) : Additive (PicardGroup X.toVariety) :=
  Additive.ofMul
    (Quotient.mk (CategoryTheory.isIsomorphicSetoid (LineBundle X.toVariety))
      ((cartierWeilEquiv X).symm W).lineBundle : PicardGroup X.toVariety)

/-- Hartshorne II.6.13(b): `O(D₁ + D₂) ≅ O(D₁) ⊗ O(D₂)`, so `D ↦ [O(D)]` is a homomorphism.

Proof: if `D₁`, `D₂` are given by local equations `{(U_i, f_i)}`, `{(U_i, g_i)}` (on a common
refinement), then `D₁ + D₂` is given by `{(U_i, f_i g_i)}`; `O(D₁ + D₂)` is generated on `U_i` by
`(f_i g_i)⁻¹` and `O(D₁)|_{U_i} ⊗ O(D₂)|_{U_i}` by `f_i⁻¹ ⊗ g_i⁻¹`, and as sub-`O_X`-modules of `𝒦` they
agree. Formally, `CartierDivisor.lineBundle_add` gives `O(D+E).toModules ≅ tensor`,
`LineBundle.isoOfModules` packages it as an isomorphism of `LineBundle`s, and after `Quotient.sound`
this is the multiplication of `PicardGroup` (`Quotient.map₂ tensorPack`) by definition; additivity of
`cartierWeilEquiv.symm` is `map_add`. -/
theorem weilToPicardFun_add {k : Type u} [Field k] (X : SmoothProjectiveVariety k)
    (W W' : X.toScheme.WeilDivisor) :
    weilToPicardFun X (W + W') = weilToPicardFun X W + weilToPicardFun X W' := by
  unfold weilToPicardFun
  rw [map_add]
  obtain ⟨e⟩ := CartierDivisor.lineBundle_add ((cartierWeilEquiv X).symm W)
    ((cartierWeilEquiv X).symm W')
  have h : (Quotient.mk (CategoryTheory.isIsomorphicSetoid (LineBundle X.toVariety))
        ((cartierWeilEquiv X).symm W + (cartierWeilEquiv X).symm W').lineBundle :
        PicardGroup X.toVariety) =
      Quotient.mk (CategoryTheory.isIsomorphicSetoid (LineBundle X.toVariety))
        (LineBundle.tensorPack ((cartierWeilEquiv X).symm W).lineBundle
          ((cartierWeilEquiv X).symm W').lineBundle) :=
    Quotient.sound ⟨LineBundle.isoOfModules e⟩
  exact congrArg Additive.ofMul h

/-- `O(0) ≅ O_X` (the case `D = 0` of Hartshorne II.6.13): `cartierWeilEquiv.symm 0 = 0`, and
`CartierDivisor.lineBundle 0` is generated by `1`, i.e. it is the structure sheaf, the identity of
`PicardGroup` (`CartierDivisor.lineBundle_zero`, `LineBundle.isoOfModules`, `Quotient.sound`). -/
theorem weilToPicardFun_zero {k : Type u} [Field k] (X : SmoothProjectiveVariety k) :
    weilToPicardFun X 0 = 0 := by
  unfold weilToPicardFun
  rw [map_zero]
  obtain ⟨e⟩ := CartierDivisor.lineBundle_zero (X := X.toVariety)
  have h : (Quotient.mk (CategoryTheory.isIsomorphicSetoid (LineBundle X.toVariety))
        (CartierDivisor.lineBundle 0) : PicardGroup X.toVariety) =
      Quotient.mk (CategoryTheory.isIsomorphicSetoid (LineBundle X.toVariety))
        (LineBundle.ofModules (SheafOfModules.unit X.toScheme.ringCatSheaf)) :=
    Quotient.sound ⟨LineBundle.isoOfModules e⟩
  exact congrArg Additive.ofMul h

noncomputable def weilToPicardHom {k : Type u} [Field k] (X : SmoothProjectiveVariety k) :
    X.toScheme.WeilDivisor →+ Additive (PicardGroup X.toVariety) where
  toFun := weilToPicardFun X
  map_zero' := weilToPicardFun_zero X
  map_add' := weilToPicardFun_add X

/-- One half of Hartshorne II.6.13(c) ("`D` is principal iff `L(D) ≅ O_X`", direction `⇒`): principal
divisors are sent to the trivial class.

Proof: let `W = div(u)` with `u ∈ K(X)^×`. Then `cartierWeilEquiv (principal u) = W`
(`cartierWeilEquiv_principal`: both sides have coefficient `ord_Z u` at every prime divisor `Z`), so
`cartierWeilEquiv.symm W = principal u` by `symm_apply_apply`; and `O(div u) ≅ O_X` by
`CartierDivisor.lineBundle_principal` (the global local equation `t` with value `u`; `t⁻¹` is a global
frame). Here the principal Weil divisor is `AlgebraicGeometry.Scheme.principalDivisor`, the one used by
`principalDivisorHom`. -/
theorem weilToPicardHom_principal_mem_ker {k : Type u} [Field k] (X : SmoothProjectiveVariety k) :
    Subgroup.toAddSubgroup' X.toScheme.principalDivisorHom.range ≤ (weilToPicardHom X).ker := by
  intro W hW
  rw [Subgroup.mem_toAddSubgroup'] at hW
  obtain ⟨u, hu⟩ := MonoidHom.mem_range.mp hW
  have hW' : W = X.toScheme.principalDivisor (u : X.toScheme.functionField) :=
    (congrArg Multiplicative.toAdd hu).symm
  rw [AddMonoidHom.mem_ker]
  show weilToPicardFun X W = 0
  rw [hW', ← cartierWeilEquiv_principal X u]
  unfold weilToPicardFun
  rw [(cartierWeilEquiv X).symm_apply_apply]
  obtain ⟨e⟩ := CartierDivisor.lineBundle_principal u
  have h : (Quotient.mk (CategoryTheory.isIsomorphicSetoid (LineBundle X.toVariety))
        (CartierDivisor.lineBundle (CartierDivisor.principal u)) : PicardGroup X.toVariety) =
      Quotient.mk (CategoryTheory.isIsomorphicSetoid (LineBundle X.toVariety))
        (LineBundle.ofModules (SheafOfModules.unit X.toScheme.ringCatSheaf)) :=
    Quotient.sound ⟨LineBundle.isoOfModules e⟩
  exact congrArg Additive.ofMul h

/-- The homomorphism `Cl(X) → Pic(X)`: a Weil divisor `W` is sent to the isomorphism class of `O_X(D)`
with `D := cartierWeilEquiv⁻¹ W`; this is a homomorphism (`O(D + E) ≅ O(D) ⊗ O(E)`) sending principal
divisors to the trivial class (`O(div f) ≅ O_X`), so it descends to `Cl(X) = Div(X) / principal`
(`QuotientAddGroup.lift`), written multiplicatively (`toMultiplicativeLeft`). -/

noncomputable def classGroupToPicardGroup {k : Type u} [Field k]
    (X : SmoothProjectiveVariety k) :
    Multiplicative (X.toScheme.ClassGroup) →* PicardGroup X.toVariety :=
  AddMonoidHom.toMultiplicativeLeft
    (QuotientAddGroup.lift _ (weilToPicardHom X) (weilToPicardHom_principal_mem_ker X))

/-- Injectivity (Hartshorne II.6.14, with the "principal to principal" part of II.6.11).

Proof: suppose `[W] ↦ 1`, i.e. `O(D) ≅ O_X` with `D = cartierWeilEquiv⁻¹ W`. By `Quotient.exact` this
gives `O(D) ≅ O_X` as packaged line bundles, hence `O(D).toModules ≅ O(0).toModules` with
`lineBundle_zero`; `CartierDivisor.exists_principal_of_lineBundle_iso` (II.6.13(c), direction `⇐`) gives
`D − 0 = div f`; then `cartierWeilEquiv_principal` gives `W = div f ∈ principalDivisorHom.range`, and
`QuotientAddGroup.eq_zero_iff` finishes (`injective_iff_map_eq_one`). -/
theorem classGroupToPicardGroup_injective {k : Type u} [Field k]
    (X : SmoothProjectiveVariety k) : Function.Injective (classGroupToPicardGroup X) := by
  rw [injective_iff_map_eq_one]
  intro a ha
  obtain ⟨W, rfl⟩ : ∃ W : X.toScheme.WeilDivisor,
      a = Multiplicative.ofAdd (QuotientAddGroup.mk W : X.toScheme.ClassGroup) := by
    obtain ⟨W, hW⟩ := QuotientAddGroup.mk_surjective (Multiplicative.toAdd a)
    exact ⟨W, by rw [hW]; rfl⟩
  -- ha: [O(D)] = 1 with D := cartierWeilEquiv⁻¹ W
  have hiso : Nonempty (((cartierWeilEquiv X).symm W).lineBundle ≅
      LineBundle.ofModules (SheafOfModules.unit X.toScheme.ringCatSheaf)) :=
    Quotient.exact (show Additive.toMul (weilToPicardFun X W) = _ from ha)
  obtain ⟨e⟩ := hiso
  obtain ⟨e0⟩ := CartierDivisor.lineBundle_zero (X := X.toVariety)
  obtain ⟨f, hf⟩ := CartierDivisor.exists_principal_of_lineBundle_iso
    (LineBundle.toModulesIso e ≪≫ e0.symm)
  rw [sub_zero] at hf
  -- W = cartierWeilEquiv D = cartierWeilEquiv (div f) = div f is principal
  have hW : W = X.toScheme.principalDivisor (f : X.toScheme.functionField) := by
    rw [← cartierWeilEquiv_principal X f, ← hf, (cartierWeilEquiv X).apply_symm_apply]
  have hmem : W ∈ Subgroup.toAddSubgroup' X.toScheme.principalDivisorHom.range :=
    (Subgroup.mem_toAddSubgroup' _ W).mpr
      (MonoidHom.mem_range.mpr ⟨f, congrArg Multiplicative.ofAdd hW.symm⟩)
  have h0 : (QuotientAddGroup.mk W : X.toScheme.ClassGroup) = 0 :=
    (QuotientAddGroup.eq_zero_iff W).mpr hmem
  rw [h0]
  exact ofAdd_zero

/-- Surjectivity (Hartshorne II.6.15): every line bundle `L` on an integral scheme is `O(D)` for a Cartier
divisor `D` (`L ⊗ 𝒦 ≅ 𝒦` since `𝒦` is constant on an integral scheme, so `L` is an invertible subsheaf
of `𝒦`, which comes from a Cartier divisor by II.6.13(a)). Formally,
`LineBundle.exists_cartierDivisor_variety` gives `D` with `O(D) ≅ L`, and the preimage is
`ofAdd (mk (cartierWeilEquiv X D))` (the same computation as `classGroupEquivPicardGroup_mk`). -/
theorem classGroupToPicardGroup_surjective {k : Type u} [Field k]
    (X : SmoothProjectiveVariety k) : Function.Surjective (classGroupToPicardGroup X) := by
  intro p
  induction p using Quotient.inductionOn with
  | h L =>
    obtain ⟨D, ⟨e⟩⟩ := LineBundle.exists_cartierDivisor_variety X.toVariety L
    refine ⟨Multiplicative.ofAdd (QuotientAddGroup.mk (cartierWeilEquiv X D) : X.toScheme.ClassGroup), ?_⟩
    show Additive.toMul (weilToPicardFun X (cartierWeilEquiv X D)) = _
    rw [weilToPicardFun, (cartierWeilEquiv X).symm_apply_apply]
    exact Quotient.sound ⟨e⟩

/-- Hartshorne II.6.16: `Cl X → Pic X` is bijective for a Noetherian integral separated locally factorial
scheme. -/
theorem classGroupToPicardGroup_bijective {k : Type u} [Field k]
    (X : SmoothProjectiveVariety k) : Function.Bijective (classGroupToPicardGroup X) :=
  ⟨classGroupToPicardGroup_injective X, classGroupToPicardGroup_surjective X⟩

/-- The isomorphism `Cl(X) ≅ Pic(X)` of a smooth projective variety (Hartshorne II.6.16). -/
noncomputable def classGroupEquivPicardGroup {k : Type u} [Field k]
    (X : SmoothProjectiveVariety k) :
    Multiplicative (X.toScheme.ClassGroup) ≃* PicardGroup X.toVariety :=
  MulEquiv.ofBijective (classGroupToPicardGroup X) (classGroupToPicardGroup_bijective X)

/-- The class of the Weil divisor of `D` is sent to the class of `O_X(D)`. -/
theorem classGroupEquivPicardGroup_mk {k : Type u} [Field k] (X : SmoothProjectiveVariety k)
    (D : CartierDivisor X.toVariety) :
    classGroupEquivPicardGroup X
        (Multiplicative.ofAdd (QuotientAddGroup.mk (cartierWeilEquiv X D) : X.toScheme.ClassGroup)) =
      (Quotient.mk (CategoryTheory.isIsomorphicSetoid (LineBundle X.toVariety)) D.lineBundle :
        PicardGroup X.toVariety) := by
  show Additive.toMul (weilToPicardFun X (cartierWeilEquiv X D)) = _
  rw [weilToPicardFun, (cartierWeilEquiv X).symm_apply_apply]
  rfl

end
