import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Divisors.LineBundle.DivisorLineBundleFrame
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.ModuleTensorSheafificationComparison

/-! # Multiplication `O_X(D) ⊗ O_X(E) → O_X(D+E)`

For Cartier divisors `D`, `E`, the product of sections of the `𝒦_X`-subsheaves `O_X(D)`, `O_X(E)`
(`lineBundleSections`, the subsheaf form of Hartshorne II.6.13) lies in `O_X(D+E)`
(`mul_mem_lineBundleSections`), so multiplication in `𝒦_X` gives a `Γ(X,·)`-bilinear multiplication at
the **presheaf** level, `mulPresheafHom D E : O_X(D) ⊗ᵖʳᵉ O_X(E) ⟶ O_X(D+E)` (presheaf tensor product
`PresheafOfModules.Monoidal.tensorObj`). It is locally bijective (`mulPresheafHom_isLocallySurjective` /
`_isLocallyInjective`), hence an isomorphism after sheafification (`isIso_sheafification_map_mulPresheafHom`).
Also the group laws of local equations: `1` is a local equation of `0` (`isLocalEquation_one`), `t·s` is
one of `D+E` and `t⁻¹` one of `−D` (`IsLocalEquation.mul` / `.inv`).

Proof:
1. Group laws of local equations: `Additive.toMul` turns `0`, `+`, `−` into `1`, `·`, `⁻¹` (definitional),
   and the quotient and restriction maps are group homomorphisms.
2. For `h ∈ O(D)(W)`, `h' ∈ O(E)(W)`: near `x` take local equations `g₁`, `g₂` with `h·g₁`, `h'·g₂ ∈ O_X`;
   on the intersection `(hh')(g₁g₂) = (hg₁)(h'g₂) ∈ O_X`, and `g₁g₂` is a local equation of `D+E` (step 1).
3. The presheaf multiplication is `TensorProduct.lift` of the bilinear multiplication on each open; it is
   compatible with restriction because the restrictions of `𝒦_X` are ring homomorphisms (`map_mul`).
4. On an open `V` with local equations `t`, `s` of `D`, `E` (these exist near every point,
   `exists_isLocalEquation_pair`), `O(D)(V)`, `O(E)(V)`, `O(D+E)(V)` are freely generated by `t⁻¹`, `s⁻¹`,
   `(ts)⁻¹` (`bijective_smul_invSection`), the presheaf tensor product `O(D)(V) ⊗ O(E)(V)` is generated by
   `t⁻¹ ⊗ s⁻¹` (`exists_smul_tmul_invSection`, by `TensorProduct.induction_on`), and multiplication sends
   `r·(t⁻¹ ⊗ s⁻¹)` to `r·(ts)⁻¹` (`mulPresheafHom_app_smul_tmul`). Hence locally surjective and locally
   injective.
5. A locally bijective presheaf morphism becomes an isomorphism after sheafification
   (`AlgebraicGeometry.Scheme.Modules.moduleSheafification_map_isIso_of_locallyBijective`; Stacks 01CB).
Sources: Hartshorne II.6.13(b) (`O(D₁ − D₂) ≅ O(D₁) ⊗ O(D₂)^{-1}`, locally generated by `f_i^{-1} g_i`);
Stacks 01CB (sheafification and tensor products).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory Opposite TopologicalSpace
open scoped AlgebraicGeometry TensorProduct

noncomputable section

namespace CartierDivisor

variable {k : Type u} [Field k] {X : Variety k}

/-- `1` is a (global) local equation of the zero divisor. -/
theorem isLocalEquation_one : IsLocalEquation (0 : CartierDivisor X) ⊤ 1 := by
  unfold IsLocalEquation
  have h : Additive.toMul (0 : CartierDivisor X) = 1 := rfl
  rw [h, map_one, map_one]

/-- The product of local equations is a local equation of the sum. -/
theorem IsLocalEquation.mul {D E : CartierDivisor X} {U : X.toScheme.Opens}
    {t s : X.toScheme.rationalFunctionsUnitsSheaf.val.obj (op U)}
    (ht : IsLocalEquation D U t) (hs : IsLocalEquation E U s) :
    IsLocalEquation (D + E) U (t * s) := by
  unfold IsLocalEquation at *
  have h : Additive.toMul (D + E) = Additive.toMul D * Additive.toMul E := rfl
  rw [h, map_mul, ht, hs, map_mul]

/-- The inverse of a local equation is a local equation of the negative. -/
theorem IsLocalEquation.inv {D : CartierDivisor X} {U : X.toScheme.Opens}
    {t : X.toScheme.rationalFunctionsUnitsSheaf.val.obj (op U)}
    (ht : IsLocalEquation D U t) : IsLocalEquation (-D) U t⁻¹ := by
  unfold IsLocalEquation at *
  have h : Additive.toMul (-D) = (Additive.toMul D)⁻¹ := rfl
  rw [h, map_inv, ht, map_inv]

/-- `O_X(D)(W) · O_X(E)(W) ⊆ O_X(D+E)(W)`. -/
theorem mul_mem_lineBundleSections {D E : CartierDivisor X} {W : X.toScheme.Opens}
    {h h' : X.toScheme.rationalFunctionsSheaf.val.obj (op W)}
    (hh : h ∈ lineBundleSections D W) (hh' : h' ∈ lineBundleSections E W) :
    h * h' ∈ lineBundleSections (D + E) W := by
  intro x hx
  obtain ⟨U₁, hxU₁, hU₁W, g₁, hg₁, hm₁⟩ := hh x hx
  obtain ⟨U₂, hxU₂, hU₂W, g₂, hg₂, hm₂⟩ := hh' x hx
  have h1 : (U₁ ⊓ U₂ : X.toScheme.Opens) ≤ U₁ := inf_le_left
  have h2 : (U₁ ⊓ U₂ : X.toScheme.Opens) ≤ U₂ := inf_le_right
  refine ⟨U₁ ⊓ U₂, ⟨hxU₁, hxU₂⟩, h1.trans hU₁W,
    X.toScheme.rationalFunctionsUnitsSheaf.val.map (homOfLE h1).op g₁ *
      X.toScheme.rationalFunctionsUnitsSheaf.val.map (homOfLE h2).op g₂,
    IsLocalEquation.mul (IsLocalEquation.restrict (D := D) hg₁ h1)
      (IsLocalEquation.restrict (D := E) hg₂ h2), ?_⟩
  obtain ⟨a, ha⟩ := mem_range_restrict hU₁W h1 h g₁ hm₁
  obtain ⟨b, hb⟩ := mem_range_restrict hU₂W h2 h' g₂ hm₂
  refine ⟨a * b, ?_⟩
  rw [map_mul, ha, hb, map_mul]
  change _ = _ * (unitVal _ * unitVal _)
  ring

/-- The multiplication `O_X(D)(W) × O_X(E)(W) → O_X(D+E)(W)`, `Γ(X, W)`-bilinear. -/
def mulSections (D E : CartierDivisor X) (W : X.toScheme.Opens) :
    lineBundleSections D W →ₗ[Γ(X.toScheme, W)] lineBundleSections E W →ₗ[Γ(X.toScheme, W)]
      lineBundleSections (D + E) W :=
  LinearMap.mk₂ Γ(X.toScheme, W) (fun a b => ⟨a.1 * b.1, mul_mem_lineBundleSections a.2 b.2⟩)
    (fun a a' b => Subtype.ext (add_mul _ _ _))
    (fun r a b => Subtype.ext (mul_assoc _ _ _))
    (fun a b b' => Subtype.ext (mul_add _ _ _))
    (fun r a b => Subtype.ext (by
      change a.1 * ((X.toScheme.toRationalFunctionsSheaf.hom.app (op W)).hom r * b.1) =
        (X.toScheme.toRationalFunctionsSheaf.hom.app (op W)).hom r * (a.1 * b.1)
      ring))

set_option backward.isDefEq.respectTransparency false in
/-- The multiplication at the presheaf level, `O_X(D) ⊗ᵖʳᵉ O_X(E) ⟶ O_X(D+E)`. -/
def mulPresheafHom (D E : CartierDivisor X) :
    PresheafOfModules.Monoidal.tensorObj (R := X.toScheme.presheaf)
        (lineBundlePresheaf D) (lineBundlePresheaf E) ⟶ lineBundlePresheaf (D + E) where
  app W := ModuleCat.ofHom (TensorProduct.lift (mulSections D E W.unop))
  naturality {W W'} i := by
    apply ModuleCat.MonoidalCategory.tensor_ext
    intro a b
    apply Subtype.ext
    exact (map_mul (X.toScheme.rationalFunctionsSheaf.val.map i).hom a.1 b.1).symm

/-- Restriction of `𝒦_X` along the identity is the identity. -/
theorem rationalFunctionsSheaf_map_self {V : X.toScheme.Opens}
    (z : X.toScheme.rationalFunctionsSheaf.val.obj (op V)) :
    (X.toScheme.rationalFunctionsSheaf.val.map (homOfLE (le_refl V)).op).hom z = z := by
  have : (homOfLE (le_refl V)).op = 𝟙 (op V) := rfl
  rw [this, X.toScheme.rationalFunctionsSheaf.val.map_id]; rfl

/-- Product of frames: `t⁻¹ · s⁻¹ = (ts)⁻¹`. -/
theorem mulSections_invSection {D E : CartierDivisor X} {V : X.toScheme.Opens}
    {t s : X.toScheme.rationalFunctionsUnitsSheaf.val.obj (op V)}
    (ht : IsLocalEquation D V t) (hs : IsLocalEquation E V s) :
    mulSections D E V (ht.invSection le_rfl) (hs.invSection le_rfl) =
      (ht.mul hs).invSection le_rfl := by
  apply Subtype.ext
  change (X.toScheme.rationalFunctionsSheaf.val.map (homOfLE (le_refl V)).op).hom (unitVal t⁻¹) *
      (X.toScheme.rationalFunctionsSheaf.val.map (homOfLE (le_refl V)).op).hom (unitVal s⁻¹) =
    (X.toScheme.rationalFunctionsSheaf.val.map (homOfLE (le_refl V)).op).hom (unitVal (t * s)⁻¹)
  rw [rationalFunctionsSheaf_map_self, rationalFunctionsSheaf_map_self,
    rationalFunctionsSheaf_map_self, mul_inv]
  rfl

/-- On an open with local equations, the presheaf tensor product `O_X(D)(V) ⊗ O_X(E)(V)` is freely
generated by `t⁻¹ ⊗ s⁻¹`. -/
theorem exists_smul_tmul_invSection {D E : CartierDivisor X} {V : X.toScheme.Opens}
    {t s : X.toScheme.rationalFunctionsUnitsSheaf.val.obj (op V)}
    (ht : IsLocalEquation D V t) (hs : IsLocalEquation E V s)
    (z : lineBundleSections D V ⊗[Γ(X.toScheme, V)] lineBundleSections E V) :
    ∃ r : Γ(X.toScheme, V), z = r • (ht.invSection le_rfl ⊗ₜ[Γ(X.toScheme, V)] hs.invSection le_rfl) := by
  induction z using TensorProduct.induction_on with
  | zero => exact ⟨0, by rw [zero_smul]⟩
  | tmul a b =>
    obtain ⟨r₁, h₁⟩ := (ht.bijective_smul_invSection le_rfl).2 a
    obtain ⟨r₂, h₂⟩ := (hs.bijective_smul_invSection le_rfl).2 b
    exact ⟨r₁ * r₂, by rw [← h₁, ← h₂, TensorProduct.smul_tmul_smul]⟩
  | add z w hz hw =>
    obtain ⟨r, hr⟩ := hz
    obtain ⟨r', hr'⟩ := hw
    exact ⟨r + r', by rw [hr, hr', add_smul]⟩

/-- The presheaf multiplication sends `r·(t⁻¹ ⊗ s⁻¹)` to `r·(ts)⁻¹`. -/
theorem mulPresheafHom_app_smul_tmul {D E : CartierDivisor X} {V : X.toScheme.Opens}
    {t s : X.toScheme.rationalFunctionsUnitsSheaf.val.obj (op V)}
    (ht : IsLocalEquation D V t) (hs : IsLocalEquation E V s) (r : Γ(X.toScheme, V)) :
    (mulPresheafHom D E).app (op V) (r • (ht.invSection le_rfl ⊗ₜ[Γ(X.toScheme, V)] hs.invSection le_rfl)) =
      r • (ht.mul hs).invSection le_rfl := by
  change TensorProduct.lift (mulSections D E V) (r • (ht.invSection le_rfl ⊗ₜ[Γ(X.toScheme, V)] hs.invSection le_rfl)) = _
  rw [map_smul, TensorProduct.lift.tmul, mulSections_invSection]

/-- Near `x`, local equations of `D` and `E` on a common open inside `W`. -/
theorem exists_isLocalEquation_pair (D E : CartierDivisor X) (W : X.toScheme.Opens) (x : X.toScheme)
    (hx : x ∈ W) :
    ∃ (V : X.toScheme.Opens) (_ : x ∈ V) (_ : V ≤ W)
      (t s : X.toScheme.rationalFunctionsUnitsSheaf.val.obj (op V)),
      IsLocalEquation D V t ∧ IsLocalEquation E V s := by
  obtain ⟨U₁, hxU₁, t, ht⟩ := exists_isLocalEquation D x
  obtain ⟨U₂, hxU₂, s, hs⟩ := exists_isLocalEquation E x
  have hV1 : (U₁ ⊓ U₂ ⊓ W : X.toScheme.Opens) ≤ U₁ := inf_le_left.trans inf_le_left
  have hV2 : (U₁ ⊓ U₂ ⊓ W : X.toScheme.Opens) ≤ U₂ := inf_le_left.trans inf_le_right
  exact ⟨U₁ ⊓ U₂ ⊓ W, ⟨⟨hxU₁, hxU₂⟩, hx⟩, inf_le_right, _, _, ht.restrict hV1, hs.restrict hV2⟩

set_option backward.isDefEq.respectTransparency false in
/-- The presheaf multiplication is locally surjective: every section of `O_X(D+E)` is locally
`r·(ts)⁻¹ = (r·t⁻¹)·s⁻¹`. -/
theorem mulPresheafHom_isLocallySurjective (D E : CartierDivisor X) :
    PresheafOfModules.IsLocallySurjective (Opens.grothendieckTopology X.toScheme)
      (mulPresheafHom D E) := by
  refine ⟨fun {W} n ↦ ?_⟩
  rw [Opens.mem_grothendieckTopology]
  intro x hx
  obtain ⟨V, hxV, hVW, t, s, ht, hs⟩ := exists_isLocalEquation_pair D E W x hx
  refine ⟨V, homOfLE hVW, ?_, hxV⟩
  obtain ⟨r, hr⟩ := ((ht.mul hs).bijective_smul_invSection le_rfl).2
    (lineBundleRestrict (D + E) (homOfLE hVW) n)
  refine ⟨r • (ht.invSection le_rfl ⊗ₜ[Γ(X.toScheme, V)] hs.invSection le_rfl), ?_⟩
  change (mulPresheafHom D E).app (op V) (r • (ht.invSection le_rfl ⊗ₜ[Γ(X.toScheme, V)] hs.invSection le_rfl)) =
    lineBundleRestrict (D + E) (homOfLE hVW) n
  rw [mulPresheafHom_app_smul_tmul]
  exact hr

set_option backward.isDefEq.respectTransparency false in
/-- The presheaf multiplication is locally injective: on an open with local equations both sides are
freely generated by one generator. -/
theorem mulPresheafHom_isLocallyInjective (D E : CartierDivisor X) :
    PresheafOfModules.IsLocallyInjective (Opens.grothendieckTopology X.toScheme)
      (mulPresheafHom D E) := by
  refine ⟨fun {W} p q hpq ↦ ?_⟩
  change (mulPresheafHom D E).app W p = (mulPresheafHom D E).app W q at hpq
  rw [Opens.mem_grothendieckTopology]
  intro x hx
  obtain ⟨V, hxV, hVW, t, s, ht, hs⟩ := exists_isLocalEquation_pair D E W.unop x hx
  refine ⟨V, homOfLE hVW, ?_, hxV⟩
  let T := PresheafOfModules.Monoidal.tensorObj (R := X.toScheme.presheaf)
    (lineBundlePresheaf D) (lineBundlePresheaf E)
  change T.map (homOfLE hVW).op p = T.map (homOfLE hVW).op q
  obtain ⟨rp, hp⟩ := exists_smul_tmul_invSection ht hs (T.map (homOfLE hVW).op p)
  obtain ⟨rq, hq⟩ := exists_smul_tmul_invSection ht hs (T.map (homOfLE hVW).op q)
  have h1 : (mulPresheafHom D E).app (op V) (T.map (homOfLE hVW).op p) =
      (mulPresheafHom D E).app (op V) (T.map (homOfLE hVW).op q) := by
    rw [PresheafOfModules.naturality_apply, PresheafOfModules.naturality_apply, hpq]
  rw [hp, hq, mulPresheafHom_app_smul_tmul, mulPresheafHom_app_smul_tmul] at h1
  have hr := ((ht.mul hs).bijective_smul_invSection le_rfl).1 h1
  rw [hp, hq, hr]

/-- After sheafification the multiplication is an isomorphism `O_X(D) ⊗ O_X(E) ≅ O_X(D+E)` (locally
bijective implies an isomorphism after sheafification). -/
theorem isIso_sheafification_map_mulPresheafHom (D E : CartierDivisor X) :
    IsIso ((PresheafOfModules.sheafification (𝟙 X.toScheme.ringCatSheaf.obj)).map
      (mulPresheafHom D E)) :=
  @AlgebraicGeometry.Scheme.Modules.moduleSheafification_map_isIso_of_locallyBijective _ _ _ (mulPresheafHom D E)
    (mulPresheafHom_isLocallyInjective D E) (mulPresheafHom_isLocallySurjective D E)

end CartierDivisor

end
