import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Divisors.LineBundle.DivisorLineBundleMul
import MiyaokaMori.AlgebraicGeometry.Modules.Dual.DualSheaf

/-! # The dual pairing `O_X(−D) × O_X(D) → O_X`

For a Cartier divisor `D`, the multiplication pairing of the `𝒦_X`-subsheaves `O_X(−D)` and `O_X(D)`,
`O_X(−D) × O_X(D) → O_X(0) = O_X` (`zeroSectionsEquiv`: `O_X(0)(V)` is `ι(Γ(X, V))`), curried into a
morphism of **presheaves** `dualPairingPresheafHom D : O_X(−D) ⟶ 𝓗om(O_X(D), O_X)` (the target is the
dual presheaf `AlgebraicGeometry.Scheme.Modules.moduleDualPresheaf`, whose sections are compatible families of local
functionals), `h ↦ (V ↦ (y ↦ ι⁻¹(h|_V · y)))`. It is locally bijective, hence an isomorphism after
sheafification: `O_X(−D) ≅ O_X(D)^∨ = Modules.dual` (`isIso_sheafification_map_dualPairingPresheafHom`).

Proof:
1. For `h ∈ O(−D)(W)` and `y ∈ O(D)(V)` (`V ≤ W`), `h|_V·y ∈ O(−D + D)(V) = O(0)(V)`
   (`mul_mem_lineBundleSections`), and `O(0)(V) = ι(Γ(X, V))` (the frame of the local equation `1`,
   `zeroSectionsEquiv`); applying `ι⁻¹` gives the `Γ(X, V)`-linear functional `pairingFun`, compatible
   with restriction (`pairingFamily`; `ι` is injective and the restrictions of `𝒦_X` are ring maps),
   linear in `h` and compatible with restriction in `W` (`dualPairingPresheafHom`).
2. On an open `V` with a local equation `t`, `t` is a frame of `O(−D)` (`t⁻¹` is a local equation of
   `−D`, `IsLocalEquation.inv`) and `t⁻¹` a frame of `O(D)`; the pairing sends `t` to the dual frame
   `(t⁻¹)^∨ = coord_{t⁻¹}` (`pairingFamily_invSection`: `ι⁻¹(t·y)·t⁻¹ = y`, by `coord_unique`).
3. The dual frame is a frame of `𝓗om(O(D), O_X)` on `V` (`IsFrame.dualFrame_isFrame`; every dual section
   is `φ = φ(t⁻¹)·(t⁻¹)^∨`), so the pairing is bijective on `V`: locally surjective and locally injective.
4. A locally bijective map becomes an isomorphism after sheafification
   (`moduleSheafification_map_isIso_of_locallyBijective`); `Modules.dual (O_X(D))` is by definition the
   sheafification of the dual presheaf.
Sources: Hartshorne II.6.12–6.13 (`L^{-1} = L^∨`; `O(−D)` is locally generated by `f_i`); Stacks 01CM
(internal Hom).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory Opposite TopologicalSpace
open scoped AlgebraicGeometry TensorProduct

noncomputable section

namespace CartierDivisor

variable {k : Type u} [Field k] {X : Variety k}

/-- `O_X(0)(V) = ι(Γ(X, V))`: the bijection `r ↦ ι(r)` given by the frame of the local equation `1`. -/
def zeroSectionsEquiv (V : X.toScheme.Opens) :
    Γ(X.toScheme, V) ≃ₗ[Γ(X.toScheme, V)] lineBundleSections (0 : CartierDivisor X) V :=
  LinearEquiv.ofBijective
    (LinearMap.toSpanSingleton Γ(X.toScheme, V) (lineBundleSections (0 : CartierDivisor X) V)
      (((isLocalEquation_one (X := X)).restrict (le_top : V ≤ ⊤)).invSection le_rfl))
    (((isLocalEquation_one (X := X)).restrict (le_top : V ≤ ⊤)).bijective_smul_invSection le_rfl)

/-- As an element of `𝒦_X`, `zeroSectionsEquiv V r` is `ι(r)`. -/
theorem zeroSectionsEquiv_apply_val (V : X.toScheme.Opens) (r : Γ(X.toScheme, V)) :
    (zeroSectionsEquiv V r).1 = (X.toScheme.toRationalFunctionsSheaf.hom.app (op V)).hom r := by
  change (X.toScheme.toRationalFunctionsSheaf.hom.app (op V)).hom r *
    (X.toScheme.rationalFunctionsSheaf.val.map (homOfLE (le_refl V)).op).hom
      (unitVal (X.toScheme.rationalFunctionsUnitsSheaf.val.map (homOfLE (le_top : V ≤ ⊤)).op 1)⁻¹) = _
  rw [rationalFunctionsSheaf_map_self, map_one, inv_one]
  exact mul_one _

/-- `ι ∘ zeroSectionsEquiv⁻¹` is the inclusion `O_X(0)(V) ⊆ 𝒦_X(V)`. -/
theorem toRationalFunctionsSheaf_zeroSectionsEquiv_symm (V : X.toScheme.Opens)
    (z : lineBundleSections (0 : CartierDivisor X) V) :
    (X.toScheme.toRationalFunctionsSheaf.hom.app (op V)).hom ((zeroSectionsEquiv V).symm z) = z.1 := by
  rw [← zeroSectionsEquiv_apply_val, LinearEquiv.apply_symm_apply]

/-- `O_X(−D + D) = O_X(0)` as submodules. -/
theorem lineBundleSections_neg_add (D : CartierDivisor X) (V : X.toScheme.Opens) :
    lineBundleSections (-D + D) V = lineBundleSections (0 : CartierDivisor X) V := by
  rw [neg_add_cancel]

/-- The pairing functional: for `h ∈ O_X(−D)(W)` and `V ≤ W`, `y ∈ Γ(O_X(D), V) ↦ ι⁻¹(h|_V · y) ∈ Γ(X, V)`. -/
def pairingFun {D : CartierDivisor X} {W : X.toScheme.Opens} (h : lineBundleSections (-D) W)
    {V : X.toScheme.Opens} (hVW : V ≤ W) :
    Γ(lineBundleModules D, V) →ₗ[Γ(X.toScheme, V)] Γ(X.toScheme, V) :=
  (zeroSectionsEquiv V).symm.toLinearMap ∘ₗ
    (LinearEquiv.ofEq _ _ (lineBundleSections_neg_add D V)).toLinearMap ∘ₗ
    mulSections (-D) D V (lineBundleRestrict (-D) (homOfLE hVW) h) ∘ₗ
    (lineBundleSectionEquiv D V).symm.toLinearMap

/-- Evaluation formula: `ι(⟨h, y⟩) = h|_V · y`. -/
theorem toRationalFunctionsSheaf_pairingFun {D : CartierDivisor X} {W : X.toScheme.Opens}
    (h : lineBundleSections (-D) W) {V : X.toScheme.Opens} (hVW : V ≤ W)
    (y : Γ(lineBundleModules D, V)) :
    (X.toScheme.toRationalFunctionsSheaf.hom.app (op V)).hom (pairingFun h hVW y) =
      (X.toScheme.rationalFunctionsSheaf.val.map (homOfLE hVW).op).hom h.1 *
        ((lineBundleSectionEquiv D V).symm y).1 := by
  change (X.toScheme.toRationalFunctionsSheaf.hom.app (op V)).hom ((zeroSectionsEquiv V).symm _) = _
  rw [toRationalFunctionsSheaf_zeroSectionsEquiv_symm]
  rfl

/-- The inverse of the section isomorphism commutes with restriction. -/
theorem lineBundleSectionEquiv_symm_map (D : CartierDivisor X) {V V' : X.toScheme.Opens}
    (i : V' ⟶ V) (y : Γ(lineBundleModules D, V)) :
    (lineBundleSectionEquiv D V').symm ((lineBundleModules D).presheaf.map i.op y) =
      lineBundleRestrict D i ((lineBundleSectionEquiv D V).symm y) := by
  apply (lineBundleSectionEquiv D V').injective
  have hi : i = homOfLE (leOfHom i) := Subsingleton.elim _ _
  rw [LinearEquiv.apply_symm_apply, hi, ← lineBundleSectionEquiv_restrict,
    LinearEquiv.apply_symm_apply]

/-- The family of pairing functionals `V ↦ (y ↦ ι⁻¹(h|_V · y))`, compatible with restriction, i.e. an
element of `Γ(V, O_X(D)^∨)`. -/
def pairingFamily {D : CartierDivisor X} {W : X.toScheme.Opens} (h : lineBundleSections (-D) W) :
    AlgebraicGeometry.Scheme.Modules.LocalDualSections X.toScheme (lineBundleModules D) W :=
  ⟨fun V => pairingFun h (leOfHom V.hom), by
    intro V V' i y
    have hi : i.left = homOfLE (leOfHom i.left) := Subsingleton.elim _ _
    apply X.toScheme.toRationalFunctionsSheaf_app_injective
    beta_reduce
    rw [hi, toRationalFunctionsSheaf_pairingFun, X.toScheme.toRationalFunctionsSheaf_res,
      toRationalFunctionsSheaf_pairingFun, map_mul, lineBundleSectionEquiv_symm_map]
    congr 1
    exact (X.toScheme.rationalFunctionsSheaf_map_map (leOfHom V'.hom) (leOfHom i.left) h.1).symm⟩

/-- Composition of restriction maps of `𝒦_X` (for arbitrary morphisms of opens). -/
theorem rationalFunctionsSheaf_map_map' {A B C : X.toScheme.Opens} (f : A ⟶ B) (g : B ⟶ C)
    (q : X.toScheme.rationalFunctionsSheaf.val.obj (op C)) :
    (X.toScheme.rationalFunctionsSheaf.val.map f.op).hom
        ((X.toScheme.rationalFunctionsSheaf.val.map g.op).hom q) =
      (X.toScheme.rationalFunctionsSheaf.val.map (f ≫ g).op).hom q := by
  rw [← ConcreteCategory.comp_apply, ← Functor.map_comp]
  rfl

/-- Morphisms of opens are subsingletons, so the restriction maps of `𝒦_X` depend only on the opens. -/
theorem rationalFunctionsSheaf_map_congr {A B : X.toScheme.Opens} (f g : A ⟶ B)
    (q : X.toScheme.rationalFunctionsSheaf.val.obj (op B)) :
    (X.toScheme.rationalFunctionsSheaf.val.map f.op).hom q =
      (X.toScheme.rationalFunctionsSheaf.val.map g.op).hom q := by
  rw [Subsingleton.elim f g]

/-- `O_X → 𝒦_X` commutes with arbitrary restrictions. -/
theorem toRationalFunctionsSheaf_res' {A B : X.toScheme.Opens} (i : A ⟶ B) (a : Γ(X.toScheme, B)) :
    (X.toScheme.toRationalFunctionsSheaf.hom.app (op A)).hom ((X.toScheme.presheaf.map i.op).hom a) =
      (X.toScheme.rationalFunctionsSheaf.val.map i.op).hom
        ((X.toScheme.toRationalFunctionsSheaf.hom.app (op B)).hom a) :=
  congrArg (fun φ => φ.hom a) (X.toScheme.toRationalFunctionsSheaf.hom.naturality i.op)

set_option backward.isDefEq.respectTransparency false in
/-- The pairing at the presheaf level, `O_X(−D) ⟶ 𝓗om(O_X(D), O_X)`: `h ↦ (y ↦ ι⁻¹(h·y))`. -/
def dualPairingPresheafHom (D : CartierDivisor X) :
    lineBundlePresheaf (-D) ⟶ AlgebraicGeometry.Scheme.Modules.moduleDualPresheaf (lineBundleModules D) where
  app W := ModuleCat.ofHom
    { toFun := fun h => pairingFamily h
      map_add' := fun h h' => by
        apply Subtype.ext
        funext V
        apply LinearMap.ext
        intro y
        apply X.toScheme.toRationalFunctionsSheaf_app_injective
        change (X.toScheme.toRationalFunctionsSheaf.hom.app (op V.left)).hom
            (pairingFun (h + h') (leOfHom V.hom) y) =
          (X.toScheme.toRationalFunctionsSheaf.hom.app (op V.left)).hom
            (pairingFun h (leOfHom V.hom) y + pairingFun h' (leOfHom V.hom) y)
        rw [map_add, toRationalFunctionsSheaf_pairingFun, toRationalFunctionsSheaf_pairingFun,
          toRationalFunctionsSheaf_pairingFun]
        change (X.toScheme.rationalFunctionsSheaf.val.map (homOfLE (leOfHom V.hom)).op).hom
          (h.1 + h'.1) * _ = _
        rw [map_add, add_mul]
      map_smul' := fun r h => by
        apply Subtype.ext
        funext V
        apply LinearMap.ext
        intro y
        apply X.toScheme.toRationalFunctionsSheaf_app_injective
        change (X.toScheme.toRationalFunctionsSheaf.hom.app (op V.left)).hom
            (pairingFun (r • h) (leOfHom V.hom) y) =
          (X.toScheme.toRationalFunctionsSheaf.hom.app (op V.left)).hom
            ((X.toScheme.presheaf.map V.hom.op).hom r * pairingFun h (leOfHom V.hom) y)
        rw [map_mul, toRationalFunctionsSheaf_pairingFun, toRationalFunctionsSheaf_pairingFun,
          toRationalFunctionsSheaf_res']
        change (X.toScheme.rationalFunctionsSheaf.val.map (homOfLE (leOfHom V.hom)).op).hom
          ((X.toScheme.toRationalFunctionsSheaf.hom.app (op W.unop)).hom r * h.1) * _ = _
        rw [map_mul, mul_assoc]
        congr 2 }
  naturality {W W'} i := by
    apply ModuleCat.hom_ext
    apply LinearMap.ext
    intro h
    apply Subtype.ext
    funext V
    apply LinearMap.ext
    intro y
    apply X.toScheme.toRationalFunctionsSheaf_app_injective
    change (X.toScheme.toRationalFunctionsSheaf.hom.app (op V.left)).hom
        (pairingFun (lineBundleRestrict (-D) i.unop h) (leOfHom V.hom) y) =
      (X.toScheme.toRationalFunctionsSheaf.hom.app (op V.left)).hom
        (pairingFun h (leOfHom (V.hom ≫ i.unop)) y)
    rw [toRationalFunctionsSheaf_pairingFun, toRationalFunctionsSheaf_pairingFun]
    congr 1
    change (X.toScheme.rationalFunctionsSheaf.val.map (homOfLE (leOfHom V.hom)).op).hom
      ((X.toScheme.rationalFunctionsSheaf.val.map i.unop.op).hom h.1) = _
    rw [rationalFunctionsSheaf_map_map']
    exact rationalFunctionsSheaf_map_congr _ _ _

set_option backward.isDefEq.respectTransparency false in
/-- The frame `t` of `O_X(−D)` on `V` pairs to the dual frame of the frame `t⁻¹` of `O_X(D)`. -/
theorem pairingFamily_invSection {D : CartierDivisor X} {V : X.toScheme.Opens}
    {t : X.toScheme.rationalFunctionsUnitsSheaf.val.obj (op V)} (ht : IsLocalEquation D V t) :
    pairingFamily (ht.inv.invSection le_rfl) =
      (ht.isFrame.dualFrame : AlgebraicGeometry.Scheme.Modules.LocalDualSections X.toScheme (lineBundleModules D) V) := by
  apply Subtype.ext
  funext V'
  apply LinearMap.ext
  intro y
  change pairingFun (ht.inv.invSection le_rfl) (leOfHom V'.hom) y =
    ht.isFrame.coord (leOfHom V'.hom) y
  symm
  apply ht.isFrame.coord_unique
  rw [ht.res_frame, ← LinearEquiv.map_smul, ← LinearEquiv.eq_symm_apply]
  apply Subtype.ext
  change (X.toScheme.toRationalFunctionsSheaf.hom.app (op V'.left)).hom
      (pairingFun (ht.inv.invSection le_rfl) (leOfHom V'.hom) y) *
    (X.toScheme.rationalFunctionsSheaf.val.map (homOfLE (leOfHom V'.hom)).op).hom (unitVal t⁻¹) =
    ((lineBundleSectionEquiv D V'.left).symm y).1
  rw [toRationalFunctionsSheaf_pairingFun]
  change (X.toScheme.rationalFunctionsSheaf.val.map (homOfLE (leOfHom V'.hom)).op).hom
    ((X.toScheme.rationalFunctionsSheaf.val.map (homOfLE (le_refl V)).op).hom (unitVal t⁻¹⁻¹)) *
    _ * _ = _
  rw [rationalFunctionsSheaf_map_self, inv_inv]
  have hu := unitVal_inv_restrict_mul (leOfHom V'.hom) t
  rw [unitVal_restrict] at hu
  linear_combination ((lineBundleSectionEquiv D V'.left).symm y).1 * hu

set_option backward.isDefEq.respectTransparency false in
/-- The pairing is locally surjective: `φ|_V = φ(t⁻¹)·(t⁻¹)^∨` is the image of `φ(t⁻¹)·t`. -/
theorem dualPairingPresheafHom_isLocallySurjective (D : CartierDivisor X) :
    PresheafOfModules.IsLocallySurjective (Opens.grothendieckTopology X.toScheme)
      (dualPairingPresheafHom D) := by
  refine ⟨fun {W} φ ↦ ?_⟩
  rw [Opens.mem_grothendieckTopology]
  intro x hx
  obtain ⟨U, hxU, t, ht⟩ := exists_isLocalEquation D x
  have hVU : (U ⊓ W : X.toScheme.Opens) ≤ U := inf_le_left
  have hVW : (U ⊓ W : X.toScheme.Opens) ≤ W := inf_le_right
  have ht' := ht.restrict hVU
  refine ⟨U ⊓ W, homOfLE hVW, ?_, ⟨hxU, hx⟩⟩
  let φ' : Γ(AlgebraicGeometry.Scheme.Modules.dualSheaf (lineBundleModules D), U ⊓ W) :=
    (AlgebraicGeometry.Scheme.Modules.moduleDualPresheaf (lineBundleModules D)).map (homOfLE hVW).op φ
  have key := ht'.isFrame.eq_smul_dualFrame le_rfl φ'
  simp only [AlgebraicGeometry.Scheme.Modules.res_self] at key
  refine ⟨AlgebraicGeometry.Scheme.Modules.dualPair φ' le_rfl ht'.frame • ht'.inv.invSection le_rfl, ?_⟩
  change (dualPairingPresheafHom D).app (op (U ⊓ W))
    (AlgebraicGeometry.Scheme.Modules.dualPair φ' le_rfl ht'.frame • ht'.inv.invSection le_rfl) = φ'
  rw [map_smul]
  change AlgebraicGeometry.Scheme.Modules.dualPair φ' le_rfl ht'.frame •
    pairingFamily (ht'.inv.invSection le_rfl) = φ'
  rw [pairingFamily_invSection]
  exact key

set_option backward.isDefEq.respectTransparency false in
/-- The pairing is locally injective: `O_X(−D)` is generated on `V` by `t`, and the target is freely
generated on `V` by the dual frame `(t⁻¹)^∨`. -/
theorem dualPairingPresheafHom_isLocallyInjective (D : CartierDivisor X) :
    PresheafOfModules.IsLocallyInjective (Opens.grothendieckTopology X.toScheme)
      (dualPairingPresheafHom D) := by
  refine ⟨fun {W} h₁ h₂ heq ↦ ?_⟩
  change (dualPairingPresheafHom D).app W h₁ = (dualPairingPresheafHom D).app W h₂ at heq
  rw [Opens.mem_grothendieckTopology]
  intro x hx
  obtain ⟨U, hxU, t, ht⟩ := exists_isLocalEquation D x
  have hVU : (U ⊓ W.unop : X.toScheme.Opens) ≤ U := inf_le_left
  have hVW : (U ⊓ W.unop : X.toScheme.Opens) ≤ W.unop := inf_le_right
  have ht' := ht.restrict hVU
  refine ⟨U ⊓ W.unop, homOfLE hVW, ?_, ⟨hxU, hx⟩⟩
  change (lineBundlePresheaf (-D)).map (homOfLE hVW).op h₁ =
    (lineBundlePresheaf (-D)).map (homOfLE hVW).op h₂
  obtain ⟨r₁, hr₁⟩ := (ht'.inv.bijective_smul_invSection le_rfl).2
    ((lineBundlePresheaf (-D)).map (homOfLE hVW).op h₁)
  obtain ⟨r₂, hr₂⟩ := (ht'.inv.bijective_smul_invSection le_rfl).2
    ((lineBundlePresheaf (-D)).map (homOfLE hVW).op h₂)
  have hr₁' : r₁ • ht'.inv.invSection le_rfl = (lineBundlePresheaf (-D)).map (homOfLE hVW).op h₁ := hr₁
  have hr₂' : r₂ • ht'.inv.invSection le_rfl = (lineBundlePresheaf (-D)).map (homOfLE hVW).op h₂ := hr₂
  have key : (dualPairingPresheafHom D).app (op (U ⊓ W.unop))
      ((lineBundlePresheaf (-D)).map (homOfLE hVW).op h₁) =
    (dualPairingPresheafHom D).app (op (U ⊓ W.unop))
      ((lineBundlePresheaf (-D)).map (homOfLE hVW).op h₂) := by
    rw [PresheafOfModules.naturality_apply, PresheafOfModules.naturality_apply, heq]
  rw [← hr₁', ← hr₂', map_smul, map_smul] at key
  change r₁ • pairingFamily (ht'.inv.invSection le_rfl) =
    r₂ • pairingFamily (ht'.inv.invSection le_rfl) at key
  rw [pairingFamily_invSection] at key
  have hinj := (ht'.isFrame.dualFrame_isFrame (U ⊓ W.unop) le_rfl).1
  have hr : r₁ = r₂ := hinj (by simpa only [AlgebraicGeometry.Scheme.Modules.res_self] using key)
  rw [← hr₁', ← hr₂', hr]

/-- After sheafification the pairing is an isomorphism `O_X(−D) ≅ 𝓗om(O_X(D), O_X)` (locally bijective
implies an isomorphism after sheafification). -/
theorem isIso_sheafification_map_dualPairingPresheafHom (D : CartierDivisor X) :
    IsIso ((PresheafOfModules.sheafification (𝟙 X.toScheme.ringCatSheaf.obj)).map
      (dualPairingPresheafHom D)) :=
  @AlgebraicGeometry.Scheme.Modules.moduleSheafification_map_isIso_of_locallyBijective _ _ _ (dualPairingPresheafHom D)
    (dualPairingPresheafHom_isLocallyInjective D) (dualPairingPresheafHom_isLocallySurjective D)

end CartierDivisor

end
