import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Divisors.LineBundle.DivisorLineBundleMul
import MiyaokaMori.AlgebraicGeometry.Divisors.LineBundle.DivisorLineBundleDualPairing
import MiyaokaMori.AlgebraicGeometry.Modules.ExteriorPower.ExteriorPowerSheafMul
import MiyaokaMori.AlgebraicGeometry.Divisors.LineBundle.DivisorLineBundle
import MiyaokaMori.AlgebraicGeometry.Modules.Dual.ModulesDual
import MiyaokaMori.AlgebraicGeometry.Modules.Tensor.ModulesTensor

/-! # `D ↦ O_X(D)` is a homomorphism

`D ↦ O_X(D)` is a homomorphism from the group of Cartier divisors to `Pic`: `O_X(0) ≅ O_X`,
`O_X(D+E) ≅ O_X(D) ⊗ O_X(E)`, `O_X(−D) ≅ O_X(D)^∨`. Source: Hartshorne II.6.12–6.13 (`O(D) ⊆ 𝒦` is locally
generated by `f_i^{-1}`; `D ↦ O(D)` is a group homomorphism; `L^{-1} = L^∨`).

Proof (entirely on the subsheaves `lineBundleSections` of `𝒦_X`, without stalks):
* zero: `1` is a local equation of `0` (`isLocalEquation_one`), so `1` is a global frame of `O_X(0)`
  (`IsLocalEquation.isFrame`), and a global frame gives `O_X ≅ O_X(0)` (`IsFrame.topTrivialization`).
* add: multiplication in `𝒦_X` gives a presheaf morphism `O_X(D) ⊗ᵖʳᵉ O_X(E) ⟶ O_X(D+E)` sending the
  generator `t⁻¹ ⊗ s⁻¹` to the generator `(ts)⁻¹` on opens with local equations `t`, `s`; it is locally
  bijective, hence an isomorphism after sheafification (`DivisorLineBundleMul`); the isomorphism
  `sheafify(P ⊗ᵖʳᵉ Q) ≅ sheafify P ⊗ sheafify Q` (`tensorSheafifyIso`) turns the target into `Modules.tensor`.
* neg: the pairing `O_X(−D) × O_X(D) → O_X(0) = O_X`, curried into a presheaf morphism
  `O_X(−D) ⟶ 𝓗om(O_X(D), O_X)`, sends the frame `t` to the dual frame `(t⁻¹)^∨` on opens with a local
  equation `t`; it is locally bijective, hence after sheafification `O_X(−D) ≅ Modules.dual O_X(D)`
  (`DivisorLineBundleDualPairing`).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- `O_X(0) ≅ O_X`. -/
theorem CartierDivisor.lineBundle_zero {k : Type*} [Field k] {X : Variety k} :
    Nonempty ((0 : CartierDivisor X).lineBundle.toModules
      ≅ SheafOfModules.unit X.toScheme.ringCatSheaf) :=
  ⟨(CartierDivisor.isLocalEquation_one (X := X)).isFrame.topTrivialization.symm⟩

/-- `O_X(D + E) ≅ O_X(D) ⊗ O_X(E)`. -/
theorem CartierDivisor.lineBundle_add {k : Type*} [Field k] {X : Variety k} (D E : CartierDivisor X) :
    Nonempty ((D + E).lineBundle.toModules
      ≅ AlgebraicGeometry.Scheme.Modules.tensor D.lineBundle.toModules E.lineBundle.toModules) :=
  haveI := CartierDivisor.isIso_sheafification_map_mulPresheafHom D E
  ⟨(asIso ((PresheafOfModules.sheafification (𝟙 X.toScheme.ringCatSheaf.obj)).map
      (CartierDivisor.mulPresheafHom D E))).symm ≪≫
    MiyaokaMori.ExteriorPowerSheafMul.tensorSheafifyIso
      (CartierDivisor.lineBundlePresheaf D) (CartierDivisor.lineBundlePresheaf E)⟩

/-- `O_X(−D) ≅ O_X(D)^∨`. -/
theorem CartierDivisor.lineBundle_neg {k : Type*} [Field k] {X : Variety k} (D : CartierDivisor X) :
    Nonempty ((-D).lineBundle.toModules
      ≅ AlgebraicGeometry.Scheme.Modules.dual D.lineBundle.toModules) :=
  haveI := CartierDivisor.isIso_sheafification_map_dualPairingPresheafHom D
  letI e := asIso ((PresheafOfModules.sheafification (𝟙 X.toScheme.ringCatSheaf.obj)).map
    (CartierDivisor.dualPairingPresheafHom D))
  ⟨e⟩

end
