import MiyaokaMori.Prelude
import MiyaokaMori.RingTheory.KeyLemma.Defs

/-! # A uniformizer of `B_𝔭` inside `B`

For `B` a domain, `𝔭` a prime with `B_𝔭` a DVR, there is `π ∈ 𝔭 = 𝔭^(1)` with `π ∉ 𝔭^(2)` (`π` is a
uniformizer of `B_𝔭` chosen in `B`).

Reference: first sentence of the fourth paragraph of the proof of Stacks 0EAW ("choose c with cπ_i ∈ A …
we may assume π_i ∈ A"); 00PD (the maximal ideal of a DVR is generated by a uniformizer).
-/

set_option autoImplicit false

universe u

open PeriodicComplex

noncomputable section

namespace KeyLemma

variable {B : Type u} [CommRing B] [IsDomain B]
  (𝔭 : Ideal B) [𝔭.IsPrime] [IsDiscreteValuationRing (Localization.AtPrime 𝔭)]

/-- Proof: the DVR `R = B_𝔭` is not a field; take a uniformizer `ϖ` (`IsDiscreteValuationRing.exists_irreducible`).
`IsLocalization.surj 𝔭.primeCompl ϖ` gives `b ∈ B`, `s ∉ 𝔭` with `ϖ * s = b` (`s` is a unit in `R`), so `b`
is associated to `ϖ`: `b ∈ 𝔪_R` (`Irreducible.maximalIdeal_eq`) but `b ∉ 𝔪_R²` (otherwise `ϖ ∈ (ϖ²)`,
contradicting `IsDiscreteValuationRing.addVal_uniformizer` / `addVal`). Membership unfolds via
`Ideal.mem_comap`. Edge case: `B_𝔭` a DVR already excludes `𝔭 = ⊥`. -/
theorem exists_uniformizer : ∃ π : B, π ∈ symbPow 𝔭 1 ∧ π ∉ symbPow 𝔭 2 := by
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible (Localization.AtPrime 𝔭)
  obtain ⟨⟨b, s⟩, hbs⟩ := IsLocalization.surj 𝔭.primeCompl ϖ
  simp only at hbs
  obtain ⟨u, hu⟩ := IsLocalization.map_units (Localization.AtPrime 𝔭) s
  have hm : IsLocalRing.maximalIdeal (Localization.AtPrime 𝔭) = Ideal.span {ϖ} := hϖ.maximalIdeal_eq
  refine ⟨b, ?_, ?_⟩
  · simp only [symbPow, Ideal.mem_comap, pow_one, hm, Ideal.mem_span_singleton, ← hbs]
    exact dvd_mul_right ϖ _
  · simp only [symbPow, Ideal.mem_comap, hm, Ideal.span_singleton_pow, Ideal.mem_span_singleton, ← hbs,
      ← hu]
    intro hdvd
    have h1 : ϖ * ϖ ∣ ϖ * 1 := by rw [mul_one, ← pow_two]; exact Units.dvd_mul_right.mp hdvd
    exact hϖ.not_isUnit (isUnit_of_dvd_one ((mul_dvd_mul_iff_left hϖ.ne_zero).mp h1))

end KeyLemma

end
