import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.RingTheory.Ideal.Maps

/-!
# The ideal-fraction subalgebra inside a localization

For an ideal `I` and an element `a` of a commutative ring `R`, `chart I a` is the
actual subalgebra of `R[1/a]` generated by the fractions `b/a` with `b ∈ I`.
Multiplication by the image of `a` is injective, and localizing this subalgebra
at that image gives the same ambient `R[1/a]`. When `a ∈ I`, the extended centre
ideal is generated by the image of `a`.

These are the elementary chart properties in Stacks Tag 07Z3, following the
affine blowup algebra of Tag 052Q. The comparison of this explicit subalgebra
model with the homogeneous localization of the Rees algebra is still a separate
construction. No Proj chart identification or blowup existence is asserted here.
The geometric consumers are Tag 0804 and the point blowups in the ruled-surface realization
(Corollary 4.3) and the prescribed-point specialization (Lemma 5.1) of the paper.

All rings, including the zero ring, and all `a`, including zero divisors, are
allowed. The ambient algebra and scalar tower are the canonical ones induced
by the actual subalgebra inclusion.
-/

namespace MiyaokaMori.RingTheory.IdealFractionChart

universe u

variable {R : Type u} [CommRing R]

/-- The subalgebra of `R[1/a]` generated by the actual fractions `b/a` for `b ∈ I`. -/
noncomputable def chart (I : Ideal R) (a : R) : Subalgebra R (Localization.Away a) :=
  Algebra.adjoin R
    ((fun b : R ↦ algebraMap R (Localization.Away a) b *
      IsLocalization.Away.invSelf (S := Localization.Away a) a) '' (I : Set R))

/-- The actual fraction `b/a`, with its membership in the generated subalgebra. -/
noncomputable def fraction (I : Ideal R) (a : R) (b : I) : chart I a :=
  ⟨algebraMap R (Localization.Away a) (b : R) *
      IsLocalization.Away.invSelf (S := Localization.Away a) a,
    Algebra.subset_adjoin ⟨(b : R), b.2, rfl⟩⟩

/-- Multiplication by the chosen denominator recovers the actual numerator in the chart. -/
theorem generator_mul_fraction (I : Ideal R) (a : R) (b : I) :
    algebraMap R (chart I a) a * fraction I a b = algebraMap R (chart I a) (b : R) := by
  apply Subtype.ext
  change algebraMap R (Localization.Away a) a *
      (algebraMap R (Localization.Away a) (b : R) *
        IsLocalization.Away.invSelf (S := Localization.Away a) a) =
    algebraMap R (Localization.Away a) (b : R)
  rw [mul_left_comm, IsLocalization.Away.mul_invSelf, mul_one]

/-- If the denominator lies in the centre, the extended centre ideal is generated by it. -/
theorem centerExtension_eq_span (I : Ideal R) (a : R) (ha : a ∈ I) :
    I.map (algebraMap R (chart I a)) =
      Ideal.span ({algebraMap R (chart I a) a} : Set (chart I a)) := by
  apply le_antisymm
  · apply Ideal.map_le_iff_le_comap.mpr
    intro b hb
    change algebraMap R (chart I a) b ∈
      Ideal.span ({algebraMap R (chart I a) a} : Set (chart I a))
    apply Ideal.mem_span_singleton.mpr
    exact ⟨fraction I a ⟨b, hb⟩, (generator_mul_fraction I a ⟨b, hb⟩).symm⟩
  · apply Ideal.span_le.mpr
    rintro b rfl
    exact Ideal.mem_map_of_mem _ ha

/-- The image of the denominator is a nonzerodivisor in the actual subalgebra. -/
theorem generator_mul_eq_zero (I : Ideal R) (a : R) (r : chart I a) :
    algebraMap R (chart I a) a * r = 0 → r = 0 := by
  intro h
  apply Subtype.ext
  have h' : algebraMap R (Localization.Away a) a * (r : Localization.Away a) = 0 :=
    congrArg Subtype.val h
  exact (IsLocalization.Away.algebraMap_isUnit (S := Localization.Away a) a).mul_right_eq_zero.mp h'

/-- Inverting the denominator in the chart gives its original ambient localization. -/
theorem isLocalization_away (I : Ideal R) (a : R) :
    IsLocalization.Away (algebraMap R (chart I a) a) (Localization.Away a) := by
  apply IsLocalization.Away.mk
  · change IsUnit (algebraMap R (Localization.Away a) a)
    exact IsLocalization.Away.algebraMap_isUnit a
  · intro z
    obtain ⟨n, b, hb⟩ := IsLocalization.Away.surj a z
    refine ⟨n, algebraMap R (chart I a) b, ?_⟩
    change z * algebraMap R (Localization.Away a) a ^ n =
      algebraMap R (Localization.Away a) b
    exact hb
  · intro r s h
    have hrs : r = s := Subtype.ext h
    exact ⟨0, by simpa using hrs⟩

end MiyaokaMori.RingTheory.IdealFractionChart
