import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Blowup.ReesAlgebraSheaf

/-! # The charts of the Rees algebra are affine blowup algebras

Ring theory behind Stacks 0804 / 052Q: for an ideal `J ⊆ A` and `a ∈ J`, the degree-zero
homogeneous localization `(⊕ₙ Jⁿ)_{(aX)}` of the Rees algebra at the degree-one element `aX` is the
affine blowup algebra `A[J/a] ⊆ A_a` (`Ideal.affineBlowup J a = MiyaokaMori.RingTheory.IdealFractionChart.chart J a`),
compatibly with the structure maps from `A`; and the basic opens `D₊(aX)`, `a ∈ J`, cover
`Proj (⊕ₙ Jⁿ)` (the irrelevant ideal `⊕_{n≥1} Jⁿ Xⁿ` is generated by `J·X`).

Source: Stacks 0804 (Lemma "lemma-blowing-up-affine") and Stacks 052Q (affine blowup algebra);
used for Stacks 0804 (`blowup_preimage_affine_cover`).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open Polynomial

noncomputable section

namespace Ideal

variable {A : Type u} [CommRing A] (J : Ideal A)

/-- Membership in the `n`-th piece of the Rees grading: `f = r·Xⁿ` with `r ∈ Jⁿ`. -/
theorem mem_reesGrading_iff (n : ℕ) (f : reesAlgebra J) :
    f ∈ J.reesGrading n ↔ ∃ r ∈ J ^ n, Polynomial.monomial n r = (f : A[X]) := by
  constructor
  · rintro ⟨r, hr⟩
    refine ⟨r, ?_, hr⟩
    have hf : (f : A[X]) ∈ reesAlgebra J := f.2
    have hr' : Polynomial.monomial n r = (f : A[X]) := hr
    rw [← hr'] at hf
    exact reesAlgebra.monomial_mem.mp hf
  · rintro ⟨r, -, hr⟩
    exact ⟨r, hr⟩

/-- `a·X` as an element of the Rees algebra, for `a ∈ J`. -/
def reesX (a : A) (ha : a ∈ J) : reesAlgebra J :=
  ⟨Polynomial.monomial 1 a, reesAlgebra.monomial_mem.mpr (by simpa using ha)⟩

@[simp] theorem coe_reesX (a : A) (ha : a ∈ J) :
    ((J.reesX a ha : reesAlgebra J) : A[X]) = Polynomial.monomial 1 a := rfl

theorem reesX_mem (a : A) (ha : a ∈ J) : J.reesX a ha ∈ J.reesGrading 1 :=
  ⟨a, rfl⟩

theorem algebraMap_mem_reesGrading_zero (r : A) :
    algebraMap A (reesAlgebra J) r ∈ J.reesGrading 0 :=
  ⟨r, by simp [Polynomial.monomial_zero_left]⟩

/-- Evaluation at `X = 1`: the Rees algebra maps to `A`, `∑ rₙ Xⁿ ↦ ∑ rₙ`. -/
def reesEvalOne : reesAlgebra J →+* A :=
  (Polynomial.evalRingHom (1 : A)).comp (Subalgebra.val (reesAlgebra J)).toRingHom

theorem reesEvalOne_apply (f : reesAlgebra J) :
    J.reesEvalOne f = Polynomial.eval (1 : A) (f : A[X]) := rfl

@[simp] theorem reesEvalOne_reesX (a : A) (ha : a ∈ J) : J.reesEvalOne (J.reesX a ha) = a := by
  simp [reesEvalOne_apply, Polynomial.eval_monomial]

@[simp] theorem reesEvalOne_algebraMap (r : A) : J.reesEvalOne (algebraMap A (reesAlgebra J) r) = r := by
  simp [reesEvalOne_apply]

theorem reesEvalOne_of_mem {n : ℕ} {f : reesAlgebra J} (hf : f ∈ J.reesGrading n) :
    Polynomial.monomial n (J.reesEvalOne f) = (f : A[X]) := by
  obtain ⟨r, -, hr⟩ := (J.mem_reesGrading_iff n f).mp hf
  rw [reesEvalOne_apply, ← hr, Polynomial.eval_monomial, one_pow, mul_one]

theorem reesEvalOne_mem_pow {n : ℕ} {f : reesAlgebra J} (hf : f ∈ J.reesGrading n) :
    J.reesEvalOne f ∈ J ^ n := by
  obtain ⟨r, hr, hr'⟩ := (J.mem_reesGrading_iff n f).mp hf
  rw [reesEvalOne_apply, ← hr', Polynomial.eval_monomial, one_pow, mul_one]
  exact hr

section Away

variable (a : A) (ha : a ∈ J)

/-- `aⁿ` as an element of `Submonoid.powers a`. -/
def powersPow (a : A) (n : ℕ) : Submonoid.powers a :=
  ⟨a ^ n, Submonoid.pow_mem _ (Submonoid.mem_powers a) n⟩

@[simp] theorem coe_powersPow (a : A) (n : ℕ) : ((powersPow a n : Submonoid.powers a) : A) = a ^ n :=
  rfl

theorem powersPow_zero (a : A) : powersPow a 0 = 1 := Subtype.ext (pow_zero a)

theorem powersPow_succ (a : A) (n : ℕ) :
    powersPow a (n + 1) = ⟨a, Submonoid.mem_powers a⟩ * powersPow a n :=
  Subtype.ext (by simp [pow_succ'])

theorem powers_reesX_le_comap :
    Submonoid.powers (J.reesX a ha) ≤ (Submonoid.powers a).comap J.reesEvalOne := by
  rintro _ ⟨n, rfl⟩
  exact ⟨n, by simp [map_pow]⟩

/-- The ring map `(Rees J)_{(aX)} → A_a`, `f/(aX)ⁿ ↦ f(1)/aⁿ`. -/
def reesAwayToLocalization :
    HomogeneousLocalization.Away J.reesGrading (J.reesX a ha) →+* Localization.Away a :=
  (IsLocalization.map (M := Submonoid.powers (J.reesX a ha)) (T := Submonoid.powers a)
      (S := Localization.Away (J.reesX a ha)) (Localization.Away a) J.reesEvalOne
      (J.powers_reesX_le_comap a ha)).comp
    (algebraMap (HomogeneousLocalization.Away J.reesGrading (J.reesX a ha))
      (Localization.Away (J.reesX a ha)))

theorem reesAwayToLocalization_mk (n : ℕ) (x : reesAlgebra J) (hx : x ∈ J.reesGrading (n • 1)) :
    J.reesAwayToLocalization a ha
        (HomogeneousLocalization.Away.mk J.reesGrading (J.reesX_mem a ha) n x hx) =
      IsLocalization.mk' (Localization.Away a) (J.reesEvalOne x) (powersPow a n) := by
  rw [reesAwayToLocalization, RingHom.comp_apply, HomogeneousLocalization.algebraMap_apply,
    HomogeneousLocalization.Away.val_mk, Localization.mk_eq_mk', IsLocalization.map_mk']
  exact congrArg _ (Subtype.ext (by simp [map_pow]))

theorem reesAwayToLocalization_fromZeroRingHom (x : J.reesGrading 0) :
    J.reesAwayToLocalization a ha (HomogeneousLocalization.fromZeroRingHom _ _ x) =
      algebraMap A (Localization.Away a) (J.reesEvalOne x) := by
  rw [reesAwayToLocalization, RingHom.comp_apply, HomogeneousLocalization.algebraMap_apply]
  change (IsLocalization.map (M := Submonoid.powers (J.reesX a ha)) (T := Submonoid.powers a)
      (S := Localization.Away (J.reesX a ha)) (Localization.Away a) J.reesEvalOne
      (J.powers_reesX_le_comap a ha)) (Localization.mk (x : reesAlgebra J) 1) = _
  rw [Localization.mk_eq_mk', IsLocalization.map_mk', IsLocalization.mk'_eq_iff_eq_mul]
  simp

/-- `b/a ∈ A[J/a]` for `b ∈ J`. -/
theorem mk'_mem_affineBlowup_of_mem (b : A) (hb : b ∈ J) :
    IsLocalization.mk' (Localization.Away a) b ⟨a, Submonoid.mem_powers a⟩ ∈ J.affineBlowup a := by
  refine Algebra.subset_adjoin ⟨b, hb, ?_⟩
  rw [IsLocalization.mk'_eq_mul_mk'_one]
  rfl

/-- `b/aⁿ ∈ A[J/a]` for `b ∈ Jⁿ`. -/
theorem mk'_mem_affineBlowup (n : ℕ) (b : A) (hb : b ∈ J ^ n) :
    IsLocalization.mk' (Localization.Away a) b (powersPow a n) ∈ J.affineBlowup a := by
  induction n generalizing b with
  | zero =>
    rw [powersPow_zero, IsLocalization.mk'_one]
    exact Subalgebra.algebraMap_mem _ b
  | succ n ih =>
    rw [pow_succ'] at hb
    refine Submodule.mul_induction_on hb ?_ ?_
    · intro c hc d hd
      rw [powersPow_succ, IsLocalization.mk'_mul]
      exact Subalgebra.mul_mem _ (Ideal.mk'_mem_affineBlowup_of_mem J a c hc) (ih d hd)
    · intro x y hx hy
      rw [IsLocalization.mk'_eq_mul_mk'_one, map_add, add_mul, ← IsLocalization.mk'_eq_mul_mk'_one,
        ← IsLocalization.mk'_eq_mul_mk'_one]
      exact Subalgebra.add_mem _ hx hy

theorem reesAwayToLocalization_mem (y : HomogeneousLocalization.Away J.reesGrading (J.reesX a ha)) :
    J.reesAwayToLocalization a ha y ∈ J.affineBlowup a := by
  obtain ⟨n, x, hx, rfl⟩ := HomogeneousLocalization.Away.mk_surjective _ (J.reesX_mem a ha) y
  rw [reesAwayToLocalization_mk]
  have hb := J.reesEvalOne_mem_pow hx
  rw [smul_eq_mul, mul_one] at hb
  exact Ideal.mk'_mem_affineBlowup J a n _ hb

theorem reesAwayToLocalization_injective :
    Function.Injective (J.reesAwayToLocalization a ha) := by
  rw [injective_iff_map_eq_zero]
  intro y hy
  obtain ⟨n, x, hx, rfl⟩ := HomogeneousLocalization.Away.mk_surjective _ (J.reesX_mem a ha) y
  rw [reesAwayToLocalization_mk, IsLocalization.mk'_eq_zero_iff] at hy
  obtain ⟨⟨_, k, rfl⟩, hk⟩ := hy
  change a ^ k * J.reesEvalOne x = 0 at hk
  apply HomogeneousLocalization.val_injective
  rw [HomogeneousLocalization.Away.val_mk, HomogeneousLocalization.val_zero, Localization.mk_eq_mk',
    IsLocalization.mk'_eq_zero_iff]
  refine ⟨⟨(J.reesX a ha) ^ k, ⟨k, rfl⟩⟩, ?_⟩
  change (J.reesX a ha) ^ k * x = 0
  apply Subtype.ext
  rw [Subalgebra.coe_mul, Subalgebra.coe_pow, coe_reesX, ← J.reesEvalOne_of_mem hx,
    Polynomial.monomial_pow, Polynomial.monomial_mul_monomial, hk, Polynomial.monomial_zero_right,
    ZeroMemClass.coe_zero]

theorem reesAwayToLocalization_surjective (z : Localization.Away a) (hz : z ∈ J.affineBlowup a) :
    ∃ y, J.reesAwayToLocalization a ha y = z := by
  refine Algebra.adjoin_induction (p := fun z _ => ∃ y, J.reesAwayToLocalization a ha y = z)
    ?_ ?_ ?_ ?_ hz
  · rintro _ ⟨b, hb, rfl⟩
    refine ⟨HomogeneousLocalization.Away.mk J.reesGrading (J.reesX_mem a ha) 1 (J.reesX b hb)
      (by simpa using J.reesX_mem b hb), ?_⟩
    rw [reesAwayToLocalization_mk, reesEvalOne_reesX, IsLocalization.mk'_eq_mul_mk'_one]
    congr 1
    exact congrArg _ (Subtype.ext (pow_one a))
  · intro r
    refine ⟨HomogeneousLocalization.Away.mk J.reesGrading (J.reesX_mem a ha) 0
      (algebraMap A (reesAlgebra J) r) (by simpa using J.algebraMap_mem_reesGrading_zero r), ?_⟩
    rw [reesAwayToLocalization_mk, reesEvalOne_algebraMap, powersPow_zero, IsLocalization.mk'_one]
  · rintro x y - - ⟨x', rfl⟩ ⟨y', rfl⟩
    exact ⟨x' + y', map_add _ _ _⟩
  · rintro x y - - ⟨x', rfl⟩ ⟨y', rfl⟩
    exact ⟨x' * y', map_mul _ _ _⟩

/-- The ring map `(Rees J)_{(aX)} → A[J/a]`. -/
def reesAwayToAffineBlowup :
    HomogeneousLocalization.Away J.reesGrading (J.reesX a ha) →+* J.affineBlowup a :=
  (J.reesAwayToLocalization a ha).codRestrict (J.affineBlowup a) (J.reesAwayToLocalization_mem a ha)

@[simp] theorem coe_reesAwayToAffineBlowup (y : HomogeneousLocalization.Away J.reesGrading (J.reesX a ha)) :
    ((J.reesAwayToAffineBlowup a ha y : J.affineBlowup a) : Localization.Away a) =
      J.reesAwayToLocalization a ha y := rfl

theorem reesAwayToAffineBlowup_bijective : Function.Bijective (J.reesAwayToAffineBlowup a ha) := by
  refine ⟨fun x y h => J.reesAwayToLocalization_injective a ha (congrArg Subtype.val h), ?_⟩
  rintro ⟨z, hz⟩
  obtain ⟨y, hy⟩ := J.reesAwayToLocalization_surjective a ha z hz
  exact ⟨y, Subtype.ext hy⟩

/-- **Stacks 052Q / 0804**: `(⊕ₙ Jⁿ)_{(aX)} ≃ A[J/a]` as rings. -/
def reesAwayEquivAffineBlowup :
    HomogeneousLocalization.Away J.reesGrading (J.reesX a ha) ≃+* J.affineBlowup a :=
  RingEquiv.ofBijective _ (J.reesAwayToAffineBlowup_bijective a ha)

@[simp] theorem reesAwayEquivAffineBlowup_apply
    (y : HomogeneousLocalization.Away J.reesGrading (J.reesX a ha)) :
    J.reesAwayEquivAffineBlowup a ha y = J.reesAwayToAffineBlowup a ha y := rfl

/-- Compatibility with the structure maps from `A`: `r/1 ↦ r/1`. -/
theorem reesAwayEquivAffineBlowup_fromZeroRingHom (r : A) :
    J.reesAwayEquivAffineBlowup a ha
        (HomogeneousLocalization.fromZeroRingHom _ _
          (⟨algebraMap A (reesAlgebra J) r, J.algebraMap_mem_reesGrading_zero r⟩ : J.reesGrading 0)) =
      algebraMap A (J.affineBlowup a) r := by
  apply Subtype.ext
  rw [reesAwayEquivAffineBlowup_apply, coe_reesAwayToAffineBlowup,
    reesAwayToLocalization_fromZeroRingHom]
  simp only [reesEvalOne_algebraMap]
  rfl

end Away

/-! ### The basic opens `D₊(aX)`, `a ∈ J`, cover `Proj (⊕ₙ Jⁿ)` -/

/-- The irrelevant ideal `⊕_{n ≥ 1} Jⁿ Xⁿ` of the Rees algebra is generated by `J·X`. -/
theorem reesGrading_irrelevant_le_span :
    (HomogeneousIdeal.irrelevant J.reesGrading).toIdeal ≤
      Ideal.span (Set.range fun b : J => J.reesX b b.2) := by
  rw [HomogeneousIdeal.toIdeal_irrelevant_le]
  intro i hi x hx
  change x ∈ J.reesGrading i at hx
  change x ∈ Ideal.span _
  obtain ⟨k, rfl⟩ : ∃ k, i = k + 1 := ⟨i - 1, by omega⟩
  obtain ⟨r, hr, hrx⟩ := (J.mem_reesGrading_iff (k + 1) x).mp hx
  rw [pow_succ'] at hr
  -- `r ↦ (the Rees element r·X^{k+1}) ∈ span`, by induction over `r ∈ J * J ^ k`
  have key : ∀ r ∈ J * J ^ k, ∃ hy : Polynomial.monomial (k + 1) r ∈ reesAlgebra J,
      (⟨Polynomial.monomial (k + 1) r, hy⟩ : reesAlgebra J) ∈
        Ideal.span (Set.range fun b : J => J.reesX b b.2) := by
    intro r hr
    refine Submodule.mul_induction_on hr ?_ ?_
    · intro c hc d hd
      have hmem : Polynomial.monomial (k + 1) (c * d) ∈ reesAlgebra J := by
        rw [add_comm, ← Polynomial.monomial_mul_monomial]
        exact Subalgebra.mul_mem _ (reesAlgebra.monomial_mem.mpr (by simpa using hc))
          (reesAlgebra.monomial_mem.mpr hd)
      refine ⟨hmem, ?_⟩
      have : (⟨_, hmem⟩ : reesAlgebra J) =
          J.reesX c hc * ⟨Polynomial.monomial k d, reesAlgebra.monomial_mem.mpr hd⟩ :=
        Subtype.ext (by
          rw [Subalgebra.coe_mul, coe_reesX, Polynomial.monomial_mul_monomial]
          show Polynomial.monomial (k + 1) (c * d) = Polynomial.monomial (1 + k) (c * d)
          rw [add_comm])
      rw [this]
      exact Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨⟨c, hc⟩, rfl⟩)
    · rintro r₁ r₂ ⟨h₁, m₁⟩ ⟨h₂, m₂⟩
      have hmem : Polynomial.monomial (k + 1) (r₁ + r₂) ∈ reesAlgebra J := by
        rw [map_add]; exact Subalgebra.add_mem _ h₁ h₂
      refine ⟨hmem, ?_⟩
      have : (⟨_, hmem⟩ : reesAlgebra J) = ⟨_, h₁⟩ + ⟨_, h₂⟩ :=
        Subtype.ext (by rw [Subalgebra.coe_add]; exact map_add _ _ _)
      rw [this]
      exact Ideal.add_mem _ m₁ m₂
  obtain ⟨hy, hmem⟩ := key r hr
  have hx' : x = ⟨_, hy⟩ := Subtype.ext hrx.symm
  rw [hx']
  exact hmem

/-- **Stacks 0804 (cover)**: `Proj (⊕ₙ Jⁿ) = ⋃_{a ∈ J} D₊(aX)`. -/
theorem reesGrading_iSup_basicOpen_eq_top :
    ⨆ b : J, AlgebraicGeometry.Proj.basicOpen J.reesGrading (J.reesX b b.2) = ⊤ :=
  AlgebraicGeometry.Proj.iSup_basicOpen_eq_top J.reesGrading _ J.reesGrading_irrelevant_le_span

end Ideal

end
