import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.Glue.ModulesGlueIsoOfFrames

/-! # Line bundles with the same transition units are isomorphic

**Line bundles with the same transition units are isomorphic** (Stacks 01CR + 04TN, gluing of
morphisms of sheaves of modules; Hartshorne II.6.13-style cocycle comparison).

Given an open cover `U i` of `X`, two `O_X`-modules `M`, `N`, local frames `b i ∈ Γ(M, U i)` of `M`
and `c i ∈ Γ(N, U i)` of `N` (`IsFrame`), such that for all `i, j` there is a single section
`u ∈ Γ(X, U i ⊓ U j)` with `b i = u • b j` **and** `c i = u • c j` on `U i ⊓ U j`, there is a global
isomorphism `e : M ≅ N` with `e (b i) = c i` for all `i`.

Difference from `exists_iso_of_local_frames` (`ModulesGlueIsoOfFrames.lean`):
the frames there are restrictions of *global* sections; here they are genuinely local, and the
compatibility is expressed through the transition units. This is the form needed for
`O_X(f^*D) ≅ f^*O_Y(D)`, where the frames `(f^♯ g_i)^{-1}` and
`f^*(g_i^{-1})` only live on `f^{-1} U_i`.

Proof (self-contained; the gluing lemma is `AlgebraicGeometry.Scheme.Modules.glueIso`):
1. `φ i := (hb i).restrictIso ≪≫ (hc i).restrictIso.symm : M|_{U i} ≅ N|_{U i}` sends `b i|` to `c i|`
   (`restrictIso_hom_app_frame`: the frame goes to `1`; `restrictIso_inv_app`: `1` goes to the frame).
2. For `V ≤ U i` the section map of `φ i` on `V` sends `b i|_V` to `c i|_V`
   (`sectionMapOfRestrictHom_res`, the local version of `sectionMapOfRestrictHom_res_top`).
3. Compatibility on `V ≤ U i ⊓ U j`: both section maps are `Γ(X, V)`-linear and `b i|_V` is a frame on
   `V`, so it suffices to compare them on `b i|_V`: `φ i` gives `c i|_V`; `φ j` gives
   `u|_V • φ j (b j|_V) = u|_V • c j|_V = c i|_V`.
4. `glueIso` produces `e` with `e.app V = ` section map of `φ i` for `V ≤ U i`; with `V = U i` this is
   `e (b i) = c i`.

Source: Stacks 01CR (invertible modules are locally generated by one section), Stacks 04TN (gluing
morphisms of sheaves); Hartshorne II.6.13.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

namespace AlgebraicGeometry.Scheme.Modules

set_option backward.isDefEq.respectTransparency false

variable {X : Scheme.{u}}

/-- The section map on `V ≤ W` of `ψ : M|_W ⟶ N|_W`, applied to the restriction of a section
`x ∈ Γ(M, W)`: first apply `ψ` on `⊤`, then restrict (local version of
`sectionMapOfRestrictHom_res_top`). -/
theorem sectionMapOfRestrictHom_res {M N : X.Modules} {W : X.Opens}
    (ψ : M.restrict W.ι ⟶ N.restrict W.ι) (V : X.Opens) (hV : V ≤ W) (x : Γ(M, W)) :
    sectionMapOfRestrictHom ψ V hV (M.res hV x) =
      N.res (hV.trans_eq W.ι_image_top.symm)
        (show Γ(N, W.ι ''ᵁ ⊤) from ψ.val.app (op ⊤)
          (show Γ(M.restrict W.ι, ⊤) from M.res (image_ι_le W ⊤) x)) := by
  have h2 : V ≤ W.ι ''ᵁ W.ι ⁻¹ᵁ V := by
    rw [AlgebraicGeometry.Scheme.Hom.image_preimage_eq_opensRange_inf,
      AlgebraicGeometry.Scheme.Opens.opensRange_ι]
    exact le_inf hV le_rfl
  have hle : W.ι ''ᵁ W.ι ⁻¹ᵁ V ≤ W.ι ''ᵁ ⊤ :=
    leOfHom (W.ι.opensFunctor.map (homOfLE (le_top : W.ι ⁻¹ᵁ V ≤ ⊤)))
  have h := PresheafOfModules.naturality_apply ψ.val
    (homOfLE (le_top : W.ι ⁻¹ᵁ V ≤ ⊤)).op
    (show Γ(M.restrict W.ι, ⊤) from M.res (image_ι_le W ⊤) x)
  have hM : ((M.restrict W.ι).val.map (homOfLE (le_top : W.ι ⁻¹ᵁ V ≤ ⊤)).op
        (show Γ(M.restrict W.ι, ⊤) from M.res (image_ι_le W ⊤) x) :
          Γ(M, W.ι ''ᵁ W.ι ⁻¹ᵁ V)) =
      M.res (W.ι.image_preimage_le V) (M.res hV x) := by
    change M.res hle (M.res (image_ι_le W ⊤) x) = _
    rw [res_res, res_res]
  have hN : ((N.restrict W.ι).val.map (homOfLE (le_top : W.ι ⁻¹ᵁ V ≤ ⊤)).op
        (ψ.val.app (op ⊤) (show Γ(M.restrict W.ι, ⊤) from M.res (image_ι_le W ⊤) x)) :
          Γ(N, W.ι ''ᵁ W.ι ⁻¹ᵁ V)) =
      N.res hle (show Γ(N, W.ι ''ᵁ ⊤) from ψ.val.app (op ⊤)
        (show Γ(M.restrict W.ι, ⊤) from M.res (image_ι_le W ⊤) x)) := rfl
  have hnat : (ψ.val.app (op (W.ι ⁻¹ᵁ V))
        (show Γ(M.restrict W.ι, W.ι ⁻¹ᵁ V) from
          M.res (W.ι.image_preimage_le V) (M.res hV x)) : Γ(N, W.ι ''ᵁ W.ι ⁻¹ᵁ V)) =
      N.res hle (show Γ(N, W.ι ''ᵁ ⊤) from ψ.val.app (op ⊤)
        (show Γ(M.restrict W.ι, ⊤) from M.res (image_ι_le W ⊤) x)) :=
    (congrArg (fun y : Γ(M.restrict W.ι, W.ι ⁻¹ᵁ V) => ψ.val.app (op (W.ι ⁻¹ᵁ V)) y) hM).symm.trans
      (h.trans hN)
  change N.res h2 (ψ.val.app (op (W.ι ⁻¹ᵁ V))
    (show Γ(M.restrict W.ι, W.ι ⁻¹ᵁ V) from
      M.res (W.ι.image_preimage_le V) (M.res hV x))) = _
  rw [hnat, res_res]

/-- The trivialization `(hb).restrictIso ≪≫ (hc).restrictIso.symm : M|_W ≅ N|_W` built from two frames
sends the frame `b|` to the frame `c|` (on `⊤` of `W`). -/
theorem restrictIso_trans_symm_app_frame {M N : X.Modules} {W : X.Opens}
    {b : Γ(M, W)} {c : Γ(N, W)} (hb : IsFrame M W b) (hc : IsFrame N W c) :
    (hb.restrictIso ≪≫ hc.restrictIso.symm).hom.val.app (op ⊤)
      (show Γ(M.restrict W.ι, ⊤) from M.res (image_ι_le W ⊤) b) =
      (show Γ(N.restrict W.ι, ⊤) from N.res (image_ι_le W ⊤) c) := by
  change hc.restrictIso.inv.val.app (op ⊤) (hb.restrictIso.hom.val.app (op ⊤) _) = _
  rw [hb.restrictIso_hom_app_frame, hc.restrictIso_inv_app]
  rw [map_one, one_smul]
  rfl

/-- Sections of a sheaf of modules over an empty open are all equal (sheaf condition for the empty
cover). -/
theorem sections_eq_of_not_nonempty (M : X.Modules) {V : X.Opens} (hV : ¬ Nonempty V)
    (s t : Γ(M, V)) : s = t := by
  refine TopCat.Sheaf.eq_of_locally_eq' ⟨M.presheaf, M.isSheaf⟩ (fun i : PEmpty.{u + 1} => i.elim)
    V (fun i => i.elim) ?_ s t (fun i => i.elim)
  intro x hx
  exact (hV ⟨⟨x, hx⟩⟩).elim

/-- **Gluing an isomorphism of modules from local frames with equal transition units.**
The transition unit is only required on nonempty overlaps. -/
theorem exists_iso_of_local_frames_transition {ι : Type u} (U : ι → X.Opens)
    (hU : ⨆ i, U i = ⊤) {M N : X.Modules} (b : ∀ i, Γ(M, U i)) (c : ∀ i, Γ(N, U i))
    (hb : ∀ i, IsFrame M (U i) (b i)) (hc : ∀ i, IsFrame N (U i) (c i))
    (h : ∀ i j, Nonempty (U i ⊓ U j : X.Opens) → ∃ u : Γ(X, U i ⊓ U j),
      M.res inf_le_left (b i) = u • M.res inf_le_right (b j) ∧
      N.res inf_le_left (c i) = u • N.res inf_le_right (c j)) :
    ∃ e : M ≅ N, ∀ i, e.hom.app (U i) (b i) = c i := by
  let φ : ∀ i, M.restrict (U i).ι ≅ N.restrict (U i).ι := fun i =>
    (hb i).restrictIso ≪≫ (hc i).restrictIso.symm
  have step1 : ∀ i (V : X.Opens) (hV : V ≤ U i),
      sectionMapOfRestrictHom (φ i).hom V hV (M.res hV (b i)) = N.res hV (c i) := by
    intro i V hV
    rw [sectionMapOfRestrictHom_res, restrictIso_trans_symm_app_frame (hb i) (hc i), res_res]
  have hcompat : ∀ i j (V : X.Opens) (hi : V ≤ U i) (hj : V ≤ U j),
      restrictSectionMap (φ i).hom V hi = restrictSectionMap (φ j).hom V hj := by
    intro i j V hi hj
    ext x
    have hV' : V ≤ U i ⊓ U j := le_inf hi hj
    by_cases hne : Nonempty (U i ⊓ U j : X.Opens)
    swap
    · exact sections_eq_of_not_nonempty N (fun ⟨⟨x, hx⟩⟩ => hne ⟨⟨x, hV' hx⟩⟩) _ _
    have hfr : IsFrame M V (M.res hi (b i)) := (hb i).restrict hi
    have hx : x = hfr.coord le_rfl x • M.res hi (b i) := by
      have := hfr.coord_smul_frame le_rfl x
      rw [res_self] at this
      exact this.symm
    change sectionMapOfRestrictHom (φ i).hom V hi x = sectionMapOfRestrictHom (φ j).hom V hj x
    rw [hx, sectionMapOfRestrictHom_smul, sectionMapOfRestrictHom_smul, step1]
    congr 1
    obtain ⟨u, hbu, hcu⟩ := h i j hne
    have hb' : M.res hi (b i) = X.presheaf.map (homOfLE hV').op u • M.res hj (b j) := by
      have := congrArg (M.res hV') hbu
      rw [res_res, res_smul, res_res] at this
      exact this
    have hc' : N.res hi (c i) = X.presheaf.map (homOfLE hV').op u • N.res hj (c j) := by
      have := congrArg (N.res hV') hcu
      rw [res_res, res_smul, res_res] at this
      exact this
    rw [hb', sectionMapOfRestrictHom_smul, step1, ← hc']
  obtain ⟨e, he⟩ := glueIso U hU M N φ hcompat
  refine ⟨e, fun i => ?_⟩
  have h1 := he i (U i) le_rfl
  have h2 := step1 i (U i) le_rfl
  rw [res_self, res_self] at h2
  rw [h1]
  exact h2

end AlgebraicGeometry.Scheme.Modules

end
