import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.ExteriorPower.ExteriorPowerSheafMul
import MiyaokaMori.AlgebraicGeometry.Modules.ExteriorPower.ExteriorPowerStalk
import MiyaokaMori.AlgebraicGeometry.Modules.Stalk.TensorPresheafStalk
import MiyaokaMori.AlgebraicGeometry.Modules.Stalk.ModuleSheafificationStalk

/-! # Stalks of exterior powers, tensor products and the maps between them

Description on **stalks** of the exterior power sheaf, the tensor sheaf and the three morphisms
`exteriorMap`, `tensorMap`, `exteriorPowerMul` on them.

Sources: Stacks 01CB (stalks of tensor products), Stacks `modules.tex`, `lemma-stalk-tensor-algebra`
(stalks of exterior powers). The stalk isomorphisms `moduleExteriorPowerStalkEquiv : (Λ^n E)_x ≅ Λ^n(E_x)`
(termwise germs on wedge germs), `tensorPresheafStalkEquiv` and `moduleSheafificationStalkEquiv` are
available; this file only shows that the morphisms are conjugate to their stalk counterparts:

* `tensorStalkEquiv' : (A ⊗ B)_x ≃ A_x ⊗ B_x`, sending the germ of `moduleTensorSection s t` to
  `s_x ⊗ t_x`;
* `stalkMap_exteriorMap`: `(Λ^n φ)_x` is conjugate to `⋀^n (φ_x)`;
* `stalkMap_tensorMap`: `(φ ⊗ ψ)_x` is conjugate to `φ_x ⊗ ψ_x`;
* `stalkMap_exteriorPowerMul`: the stalk of the wedge multiplication is conjugate to the module-level
  wedge multiplication `Module.exteriorPowerMul`.

All proofs check the identities on generators: stalks are generated by germs of sections, and the
images of wedge/tensor germs are given by `moduleExteriorMap_wedge`, `tensorMap_app_tensorSection`,
`exteriorSheafMul_wedge`.
-/

set_option autoImplicit false
set_option maxHeartbeats 800000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry TensorProduct

noncomputable section

namespace MiyaokaMori.ExteriorTensorStalk

open AlgebraicGeometry AlgebraicGeometry.Scheme.Modules

set_option backward.isDefEq.respectTransparency false

variable {X : AlgebraicGeometry.Scheme.{u}}

local instance instCommRingSectionsForStalk (U : X.Opensᵒᵖ) :
    CommRing (X.ringCatSheaf.obj.obj U) :=
  inferInstanceAs (CommRing Γ(X, U.unop))

/-! ### Functoriality of stalk maps -/

theorem moduleStalkMap_comp_apply (x : X) {M N P : X.Modules} (φ : M ⟶ N) (ψ : N ⟶ P)
    (z : M.presheaf.stalk x) :
    moduleStalkMap X x (φ ≫ ψ) z = moduleStalkMap X x ψ (moduleStalkMap X x φ z) := by
  obtain ⟨U, hxU, s, rfl⟩ := M.presheaf.exists_germ_eq z
  rw [moduleStalkMap_germ, moduleStalkMap_germ, moduleStalkMap_germ, Scheme.Modules.Hom.comp_app]
  rfl

theorem moduleStalkMap_id_apply (x : X) {M : X.Modules} (z : M.presheaf.stalk x) :
    moduleStalkMap X x (𝟙 M) z = z := by
  obtain ⟨U, hxU, s, rfl⟩ := M.presheaf.exists_germ_eq z
  rw [moduleStalkMap_germ, Scheme.Modules.Hom.id_app]
  rfl

theorem moduleStalkMap_zero_apply (x : X) {M N : X.Modules} (z : M.presheaf.stalk x) :
    moduleStalkMap X x (0 : M ⟶ N) z = 0 := by
  obtain ⟨U, hxU, s, rfl⟩ := M.presheaf.exists_germ_eq z
  rw [moduleStalkMap_germ, Scheme.Modules.Hom.zero_app]
  exact map_zero _

/-! ### Stalks of the tensor sheaf -/

/-- `(A ⊗ B)_x ≃ A_x ⊗ B_x` (`Modules.tensor A B` is the sheafification of `A ⊗ᵖʳᵉ B`; sheafification does
not change stalks, and the stalk of the presheaf tensor product is the tensor product of stalks). -/
def tensorStalkEquiv' (A B : X.Modules) (x : X) :
    (AlgebraicGeometry.Scheme.Modules.tensor A B).presheaf.stalk x ≃ₗ[X.presheaf.stalk x]
      (A.presheaf.stalk x ⊗[X.presheaf.stalk x] B.presheaf.stalk x) :=
  (moduleSheafificationStalkEquiv X (moduleTensorPresheaf A B) x).symm ≪≫ₗ
    tensorPresheafStalkEquiv X A.val B.val x

theorem tensorStalkEquiv'_germ (A B : X.Modules) (x : X) (U : X.Opens) (hx : x ∈ U)
    (s : Γ(A, U)) (t : Γ(B, U)) :
    tensorStalkEquiv' A B x
        ((AlgebraicGeometry.Scheme.Modules.tensor A B).presheaf.germ U x hx
          (moduleTensorSection s t)) =
      A.presheaf.germ U x hx s ⊗ₜ[X.presheaf.stalk x] B.presheaf.germ U x hx t := by
  change tensorPresheafStalkEquiv X A.val B.val x
    ((moduleSheafificationStalkEquiv X (moduleTensorPresheaf A B) x).symm
      ((moduleSheafification X (moduleTensorPresheaf A B)).presheaf.germ U x hx
        (moduleSheafificationUnit X (moduleTensorPresheaf A B) U (s ⊗ₜ[Γ(X, U)] t)))) = _
  rw [moduleSheafificationStalkEquiv_symm_germ]
  exact tensorPresheafStalkEquiv_germ_tmul X A.val B.val x U hx s t

theorem tensorStalkEquiv'_symm_tmul (A B : X.Modules) (x : X) (U : X.Opens) (hx : x ∈ U)
    (s : Γ(A, U)) (t : Γ(B, U)) :
    (tensorStalkEquiv' A B x).symm
        (A.presheaf.germ U x hx s ⊗ₜ[X.presheaf.stalk x] B.presheaf.germ U x hx t) =
      (AlgebraicGeometry.Scheme.Modules.tensor A B).presheaf.germ U x hx
        (moduleTensorSection s t) := by
  rw [← tensorStalkEquiv'_germ, LinearEquiv.symm_apply_apply]

/-- The value of `tensorMap φ ψ` on pure tensor sections. -/
theorem tensorMap_app_tensorSection {A A' B B' : X.Modules} (φ : A ⟶ A') (ψ : B ⟶ B')
    (U : X.Opens) (s : Γ(A, U)) (t : Γ(B, U)) :
    (AlgebraicGeometry.Scheme.Modules.tensorMap φ ψ).app U (moduleTensorSection s t) =
      moduleTensorSection (φ.app U s) (ψ.app U t) := by
  change ((PresheafOfModules.sheafification (𝟙 X.ringCatSheaf.obj)).map
      (PresheafOfModules.Monoidal.tensorHom (R := X.presheaf) φ.val ψ.val)).val.app (op U)
      (moduleSheafificationUnit X (moduleTensorPresheaf A B) U (s ⊗ₜ[Γ(X, U)] t)) =
    moduleSheafificationUnit X (moduleTensorPresheaf A' B') U
      (φ.app U s ⊗ₜ[Γ(X, U)] ψ.app U t)
  refine (moduleSheafificationUnit_naturality X _ U _).trans ?_
  rfl

/-- **Stalk of a tensor map**: `(φ ⊗ ψ)_x` is conjugate to `φ_x ⊗ ψ_x`. -/
theorem stalkMap_tensorMap {A A' B B' : X.Modules} (φ : A ⟶ A') (ψ : B ⟶ B') (x : X)
    (z : (AlgebraicGeometry.Scheme.Modules.tensor A B).presheaf.stalk x) :
    tensorStalkEquiv' A' B' x
        (moduleStalkMap X x (AlgebraicGeometry.Scheme.Modules.tensorMap φ ψ) z) =
      TensorProduct.map (moduleStalkMap X x φ) (moduleStalkMap X x ψ)
        (tensorStalkEquiv' A B x z) := by
  have key : (tensorStalkEquiv' A' B' x).toLinearMap ∘ₗ
      moduleStalkMap X x (AlgebraicGeometry.Scheme.Modules.tensorMap φ ψ) ∘ₗ
        (tensorStalkEquiv' A B x).symm.toLinearMap =
      TensorProduct.map (moduleStalkMap X x φ) (moduleStalkMap X x ψ) := by
    apply TensorProduct.ext'
    intro m n
    obtain ⟨U, hx, s, t, rfl, rfl⟩ := modulePresheafStalk_exists_pair X A.val B.val x m n
    simp only [LinearMap.comp_apply, LinearEquiv.coe_coe, TensorProduct.map_tmul]
    erw [tensorStalkEquiv'_symm_tmul, moduleStalkMap_germ, tensorMap_app_tensorSection,
      tensorStalkEquiv'_germ, moduleStalkMap_germ, moduleStalkMap_germ]
  have h := LinearMap.congr_fun key (tensorStalkEquiv' A B x z)
  simp only [LinearMap.comp_apply, LinearEquiv.coe_coe, LinearEquiv.symm_apply_apply] at h
  exact h

/-! ### Stalks of the exterior power sheaf -/

/-- **Stalk of an exterior power map**: `(Λ^n φ)_x` is conjugate to `⋀^n (φ_x)`. -/
theorem stalkMap_exteriorMap {E E' : X.Modules} (φ : E ⟶ E') (n : ℕ) (x : X)
    (z : (AlgebraicGeometry.Scheme.Modules.exteriorPower E n).presheaf.stalk x) :
    moduleExteriorPowerStalkEquiv X E' x n
        (moduleStalkMap X x (AlgebraicGeometry.Scheme.Modules.exteriorMap φ n) z) =
      exteriorPower.map n (moduleStalkMap X x φ) (moduleExteriorPowerStalkEquiv X E x n z) := by
  have key : (moduleExteriorPowerStalkEquiv X E' x n).toLinearMap ∘ₗ
      moduleStalkMap X x (AlgebraicGeometry.Scheme.Modules.exteriorMap φ n) ∘ₗ
        (moduleExteriorPowerStalkEquiv X E x n).symm.toLinearMap =
      exteriorPower.map n (moduleStalkMap X x φ) := by
    apply LinearMap.ext_on (exteriorPower.ιMulti_span (X.presheaf.stalk x) n (E.presheaf.stalk x))
    rintro _ ⟨v, rfl⟩
    obtain ⟨U, hxU, c, hc⟩ := modulePresheafStalk_exists_fin X E.val x n v
    have hv : v = fun i => E.presheaf.germ U x hxU (c i) := funext fun i => (hc i).symm
    subst hv
    have hsymm : (moduleExteriorPowerStalkEquiv X E x n).symm
        (exteriorPower.ιMulti (X.presheaf.stalk x) n (fun i => E.presheaf.germ U x hxU (c i))) =
        (moduleExteriorPower X E n).presheaf.germ U x hxU (moduleExteriorWedge X E n U c) := by
      rw [← moduleExteriorPowerStalkEquiv_wedge_germ, LinearEquiv.symm_apply_apply]
    simp only [LinearMap.comp_apply, LinearEquiv.coe_coe]
    erw [hsymm, moduleStalkMap_germ]
    change moduleExteriorPowerStalkEquiv X E' x n
      ((moduleExteriorPower X E' n).presheaf.germ U x hxU
        ((moduleExteriorMap X n φ).app U (moduleExteriorWedge X E n U c))) = _
    rw [moduleExteriorMap_wedge, moduleExteriorPowerStalkEquiv_wedge_germ,
      exteriorPower.map_apply_ιMulti]
    congr 1
    funext i
    exact (moduleStalkMap_germ X x φ U hxU (c i)).symm
  have h := LinearMap.congr_fun key (moduleExteriorPowerStalkEquiv X E x n z)
  simp only [LinearMap.comp_apply, LinearEquiv.coe_coe] at h
  erw [LinearEquiv.symm_apply_apply] at h
  exact h

/-- Stalk of a tensor product of exterior powers: `(Λ^a E ⊗ Λ^b E')_x ≃ ⋀^a E_x ⊗ ⋀^b E'_x`. -/
def exteriorTensorStalkEquiv (E E' : X.Modules) (a b : ℕ) (x : X) :
    (AlgebraicGeometry.Scheme.Modules.tensor
        (AlgebraicGeometry.Scheme.Modules.exteriorPower E a)
        (AlgebraicGeometry.Scheme.Modules.exteriorPower E' b)).presheaf.stalk x
      ≃ₗ[X.presheaf.stalk x]
      ((⋀[X.presheaf.stalk x]^a (E.presheaf.stalk x)) ⊗[X.presheaf.stalk x]
        (⋀[X.presheaf.stalk x]^b (E'.presheaf.stalk x))) :=
  tensorStalkEquiv' _ _ x ≪≫ₗ
    TensorProduct.congr (moduleExteriorPowerStalkEquiv X E x a)
      (moduleExteriorPowerStalkEquiv X E' x b)

theorem exteriorTensorStalkEquiv_symm_tmul (E E' : X.Modules) (a b : ℕ) (x : X)
    (U : X.Opens) (hx : x ∈ U) (v : Fin a → Γ(E, U)) (w : Fin b → Γ(E', U)) :
    (exteriorTensorStalkEquiv E E' a b x).symm
        (exteriorPower.ιMulti (X.presheaf.stalk x) a (fun i => E.presheaf.germ U x hx (v i)) ⊗ₜ
          exteriorPower.ιMulti (X.presheaf.stalk x) b (fun i => E'.presheaf.germ U x hx (w i))) =
      (AlgebraicGeometry.Scheme.Modules.tensor
        (AlgebraicGeometry.Scheme.Modules.exteriorPower E a)
        (AlgebraicGeometry.Scheme.Modules.exteriorPower E' b)).presheaf.germ U x hx
        (moduleTensorSection (moduleExteriorWedge X E a U v) (moduleExteriorWedge X E' b U w)) := by
  apply (exteriorTensorStalkEquiv E E' a b x).injective
  rw [LinearEquiv.apply_symm_apply]
  symm
  change TensorProduct.congr (moduleExteriorPowerStalkEquiv X E x a)
      (moduleExteriorPowerStalkEquiv X E' x b) (tensorStalkEquiv' _ _ x _) = _
  erw [tensorStalkEquiv'_germ]
  rw [TensorProduct.congr_tmul, moduleExteriorPowerStalkEquiv_wedge_germ,
    moduleExteriorPowerStalkEquiv_wedge_germ]

/-- **Stalk of the wedge multiplication**: `(Λ^a E ⊗ Λ^b E ⟶ Λ^{a+b} E)_x` is conjugate to
`Module.exteriorPowerMul`. -/
theorem stalkMap_exteriorPowerMul (E : X.Modules) (a b : ℕ) (x : X)
    (z : (AlgebraicGeometry.Scheme.Modules.tensor
        (AlgebraicGeometry.Scheme.Modules.exteriorPower E a)
        (AlgebraicGeometry.Scheme.Modules.exteriorPower E b)).presheaf.stalk x) :
    moduleExteriorPowerStalkEquiv X E x (a + b)
        (moduleStalkMap X x (AlgebraicGeometry.Scheme.Modules.exteriorPowerMul E a b) z) =
      Module.exteriorPowerMul (X.presheaf.stalk x) (E.presheaf.stalk x) a b
        (exteriorTensorStalkEquiv E E a b x z) := by
  have key : (moduleExteriorPowerStalkEquiv X E x (a + b)).toLinearMap ∘ₗ
      moduleStalkMap X x (AlgebraicGeometry.Scheme.Modules.exteriorPowerMul E a b) ∘ₗ
        (exteriorTensorStalkEquiv E E a b x).symm.toLinearMap =
      Module.exteriorPowerMul (X.presheaf.stalk x) (E.presheaf.stalk x) a b := by
    refine Module.exteriorPowerMul_hom_ext fun v w => ?_
    obtain ⟨U, hxU, c, hc⟩ := modulePresheafStalk_exists_fin X E.val x (a + b) (Fin.append v w)
    have hv : v = fun i => E.presheaf.germ U x hxU (c (Fin.castAdd b i)) := by
      funext i; rw [← Fin.append_left v w i]; exact (hc _).symm
    have hw : w = fun i => E.presheaf.germ U x hxU (c (Fin.natAdd a i)) := by
      funext i; rw [← Fin.append_right v w i]; exact (hc _).symm
    subst hv hw
    simp only [LinearMap.comp_apply, LinearEquiv.coe_coe]
    erw [exteriorTensorStalkEquiv_symm_tmul, moduleStalkMap_germ]
    change moduleExteriorPowerStalkEquiv X E x (a + b)
      ((moduleExteriorPower X E (a + b)).presheaf.germ U x hxU
        ((MiyaokaMori.ExteriorPowerSheafMul.exteriorSheafMul X E a b).app U
          (moduleTensorSection (moduleExteriorWedge X E a U (fun i => c (Fin.castAdd b i)))
            (moduleExteriorWedge X E b U (fun i => c (Fin.natAdd a i)))))) = _
    rw [MiyaokaMori.ExteriorPowerSheafMul.exteriorSheafMul_wedge,
      moduleExteriorPowerStalkEquiv_wedge_germ, Module.exteriorPowerMul_ιMulti]
    congr 1
    funext i
    refine Fin.addCases (fun j => ?_) (fun j => ?_) i <;> simp only [Fin.append_left, Fin.append_right]
  have h := LinearMap.congr_fun key (exteriorTensorStalkEquiv E E a b x z)
  simp only [LinearMap.comp_apply, LinearEquiv.coe_coe, LinearEquiv.symm_apply_apply] at h
  exact h

end MiyaokaMori.ExteriorTensorStalk

end
