import MiyaokaMori.Prelude
import MiyaokaMori.Paper.S2WeightedJets.Jets.JetBaseClosedPoint
import MiyaokaMori.Paper.S2WeightedJets.Jets.JetConstantTerm

/-! # The constant-term section is surjective

The constant-term section `ι₀ = jetConstantTerm r W : W → W ×_k D_r` is surjective on underlying spaces.

Proof: `ι₀` is the base change of the closed point `jetBaseZero : Spec k → D_r = Spec k[t]/(t^{r+1})` along
`pr₂ : W ×_k D_r → D_r` (`jetConstantTerm_isPullback`, assembled by `IsPullback.of_right` from `ι₀ ≫ pr₁ = 𝟙`,
`z ≫ (D_r → Spec k) = 𝟙` and the pullback square of `W ×_k D_r`), and `jetBaseZero` is surjective: the image of
`Spec.map ε` is `V(ker ε)` (`range_comap_of_surjective`), and `ker ε = (t)` is generated by a nilpotent, so
`V(ker ε) = Spec` (`zeroLocus_eq_univ_iff`). Surjectivity is stable under base change (Mathlib's
`IsStableUnderBaseChange` instance for `AlgebraicGeometry.Surjective`).

This is what the restriction of based jets to open sets (`BasedJetOpenRestriction`) needs: every point of
`W ×_k D_r` lies in the image of `ι₀`.

Source: the proof of Ein–Mustață Lemma 2.3 (factoring through an open set is a set-theoretic condition); §2 of the
paper (a nilpotent thickening does not change the underlying space).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- `ε : k[t]/(t^{r+1}) → k` (`t ↦ 0`) is surjective: `ε ∘ η = id`. -/
theorem jetBaseZero_epsilon_surjective (k : Type u) [Field k] (r : ℕ) :
    Function.Surjective (MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.epsilon (R := k) r) := fun a =>
  ⟨MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.eta r a,
    DFunLike.congr_fun (MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.epsilon_eta (R := k) r) a⟩

/-- `ker ε ≤ nilradical`: `ε(mk p) = p(0) = 0` means `X ∣ p`, and `mk X` is nilpotent (`X^{r+1} = 0`). -/
theorem jetBaseZero_ker_epsilon_le_nilradical (k : Type u) [Field k] (r : ℕ) :
    RingHom.ker (MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.epsilon (R := k) r) ≤
      nilradical (MiyaokaMori.RingTheory.GlobalTruncatedParameter k r) := by
  intro q hq
  obtain ⟨p, rfl⟩ := MiyaokaMori.Jet.jetProjection_surjective _ _ q
  rw [RingHom.mem_ker] at hq
  have hp : p.coeff 0 = 0 := by
    rw [Polynomial.coeff_zero_eq_eval_zero]
    exact hq
  obtain ⟨p', rfl⟩ := Polynomial.X_dvd_iff.mpr hp
  rw [mem_nilradical, map_mul]
  refine Commute.isNilpotent_mul_right (Commute.all _ _) ⟨r + 1, ?_⟩
  -- `TruncatedJetRing` is `AdjoinRoot (X^(r+1))`; the generic quotient
  -- lemma no longer rewrites its equalities, so close by the term (`exact` works up to definitional unfolding).
  rw [← map_pow]
  exact Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span (Set.mem_singleton _))

/-- The closed point `jetBaseZero : Spec k → D_r` is surjective on underlying spaces (`D_r` has a single point).
Not registered as a global instance; use `haveI` where needed. -/
theorem jetBaseZero_surjective (k : Type u) [Field k] (r : ℕ) :
    AlgebraicGeometry.Surjective (jetBaseZero k r) := by
  constructor
  intro x
  have hrange : Set.range (PrimeSpectrum.comap
      (MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.epsilon (R := k) r)) = Set.univ := by
    rw [range_comap_of_surjective _ _ (jetBaseZero_epsilon_surjective k r),
      PrimeSpectrum.zeroLocus_eq_univ_iff]
    exact jetBaseZero_ker_epsilon_le_nilradical k r
  have hx : x ∈ Set.range (PrimeSpectrum.comap
      (MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.epsilon (R := k) r)) := hrange ▸ Set.mem_univ x
  obtain ⟨y, hy⟩ := hx
  exact ⟨y, hy⟩

/-- The constant-term section is the base change of the closed point along `pr₂`: the square `W → Spec k`,
`W → W ×_k D_r`, `Spec k → D_r`, `W ×_k D_r → D_r` is a pullback. -/
theorem jetConstantTerm_isPullback {k : Type u} [Field k] (r : ℕ) (W : AlgebraicGeometry.Scheme.{u})
    [W.Over (AlgebraicGeometry.Spec (CommRingCat.of k))] :
    IsPullback (W ↘ AlgebraicGeometry.Spec (CommRingCat.of k)) (jetConstantTerm (k := k) r W)
      (jetBaseZero k r)
      (pullback.snd (W ↘ AlgebraicGeometry.Spec (CommRingCat.of k))
        (jetBase k r ↘ AlgebraicGeometry.Spec (CommRingCat.of k))) := by
  refine (IsPullback.of_right (h₁₁ := jetConstantTerm (k := k) r W) (h₁₂ := pullback.fst _ _)
    (v₁₁ := W ↘ AlgebraicGeometry.Spec (CommRingCat.of k)) (v₁₂ := pullback.snd _ _)
    (v₁₃ := W ↘ AlgebraicGeometry.Spec (CommRingCat.of k)) (h₂₁ := jetBaseZero k r)
    (h₂₂ := jetBase k r ↘ AlgebraicGeometry.Spec (CommRingCat.of k)) ?_ ?_
    (IsPullback.of_hasPullback _ _)).flip
  · rw [show jetConstantTerm (k := k) r W ≫ pullback.fst _ _ = 𝟙 W from pullback.lift_fst _ _ _,
      jetBaseZero_comp_structure]
    exact IsPullback.of_horiz_isIso ⟨by simp⟩
  · exact pullback.lift_snd _ _ _

/-- The constant-term section `W → W ×_k D_r` is surjective on underlying spaces. -/
theorem jetConstantTerm_surjective {k : Type u} [Field k] (r : ℕ) (W : AlgebraicGeometry.Scheme.{u})
    [W.Over (AlgebraicGeometry.Spec (CommRingCat.of k))] :
    Function.Surjective (jetConstantTerm (k := k) r W) := by
  have : AlgebraicGeometry.Surjective (jetBaseZero k r) := jetBaseZero_surjective k r
  have : AlgebraicGeometry.Surjective (jetConstantTerm (k := k) r W) :=
    MorphismProperty.of_isPullback (P := @AlgebraicGeometry.Surjective)
      (jetConstantTerm_isPullback (k := k) r W) inferInstance
  exact (jetConstantTerm (k := k) r W).surjective

end
