import MiyaokaMori.Prelude
import MiyaokaMori.Paper.S2WeightedJets.Jets.JetBaseClosedPoint
import MiyaokaMori.Paper.S2WeightedJets.Jets.JetConstantTerm
import MiyaokaMori.Paper.S2WeightedJets.Jets.JetThickening
import MiyaokaMori.Paper.S2WeightedJets.Jets.BasedJetOpenRestriction_ConstantTermSurjective

/-! # The constant-term closed immersion is a nilpotent thickening

The closed immersion `ι₀ : T → T ×_k Spec k[t]/(t^{r+1})` taking the constant term is defined by a nilpotent
ideal (`t^{r+1} = 0`), hence is a nilpotent thickening (see §2 of the paper, the local coordinates on the based
jet space: a nilpotent thickening does not change the underlying topological space).

## Proof outline

Write `Y := jetThickening r T = T ×_k D_r`, `pr₂ : Y → D_r`, `ι₀ := jetConstantTerm r T` and
`z := jetBaseZero k r : Spec k → D_r` (`t ↦ 0`).

1. `ι₀` is the base change of the closed immersion `z` along `pr₂` (`jetConstantTerm_isPullback`), and closed
   immersions are stable under base change.
2. Let `τ := pr₂^*(t) ∈ Γ(Y, ⊤)` (`jetThickeningParam`); then `τ^{r+1} = pr₂^*(t^{r+1}) = 0`.
3. Let `J` be the ideal sheaf generated by `τ` (`jetThickeningParamIdealSheaf`: on every affine open `U` take
   `(τ|_U)`; quasi-coherence comes from `Ideal.map_span`), `Z := J.subscheme`, `j := J.subschemeι : Z → Y`, so
   `j.ker = J`.
4. `j^*τ = 0` (`jetThickeningParamIdealSheaf_subschemeι_appTop_param`): on every affine open `U`,
   `j.app U (τ|_U) = 0` since `τ|_U ∈ J(U) = ker (j.app U)`; by locality of sheaves (`Scheme.zero_of_zero_cover`)
   the global section vanishes.
5. Hence the ring homomorphism `φ : k[t]/(t^{r+1}) → Γ(Z, ⊤)` corresponding to `j ≫ pr₂` satisfies `φ(t) = 0`,
   so `φ = (φ ∘ η) ∘ ε` (`Ideal.Quotient.ringHom_ext`, `Polynomial.ringHom_ext`), i.e. `j ≫ pr₂` factors
   through `z` (`factor_through_jetBaseZero`).
6. By the universal property of the pullback square, `j` factors through `ι₀`: `j = ψ ≫ ι₀`, hence
   `ι₀.ker ≤ j.ker = J` (`Scheme.Hom.le_ker_comp`; `jetConstantTerm_ker_le_paramIdealSheaf`).
7. On every affine open `U`: `(ι₀.ker.ideal U)^{r+1} ≤ (τ|_U)^{r+1} = ((τ^{r+1})|_U) = (0) = ⊥`.

This route needs neither the computation `R ⊗_k k[t]/(t^{r+1}) ≅ R[t]/(t^{r+1})` on affine charts nor a
quasi-compact covering argument.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- Sheaf locality for pullbacks of global sections: `f^* s = 0` as soon as `f.app U` kills
`s|_U` for every affine open `U` of the target (the opens `f⁻¹U` cover the source). -/
theorem AlgebraicGeometry.Scheme.Hom.appTop_eq_zero_of_forall_affineOpens
    {X Y : AlgebraicGeometry.Scheme.{u}} (f : X ⟶ Y) (s : Γ(Y, ⊤))
    (h : ∀ U : Y.affineOpens, f.app U (Y.presheaf.map (homOfLE le_top).op s) = 0) :
    f.appTop s = 0 := by
  have hcov : TopologicalSpace.IsOpenCover (fun U : Y.affineOpens => f ⁻¹ᵁ U.1) := by
    show (⨆ U : Y.affineOpens, f ⁻¹ᵁ U.1) = ⊤
    rw [← AlgebraicGeometry.Scheme.Hom.preimage_iSup, AlgebraicGeometry.iSup_affineOpens_eq_top,
      AlgebraicGeometry.Scheme.Hom.preimage_top]
  apply AlgebraicGeometry.Scheme.zero_of_zero_cover _ (X.openCoverOfIsOpenCover _ hcov)
  intro U
  change (f ⁻¹ᵁ U.1).ι.appTop (f.appTop s) = 0
  rw [AlgebraicGeometry.Scheme.Opens.ι_appTop]
  have hle : (f ⁻¹ᵁ U.1).ι ''ᵁ ⊤ ≤ f ⁻¹ᵁ U.1 := (AlgebraicGeometry.Scheme.Opens.ι_image_top _).le
  have hle' : (f ⁻¹ᵁ U.1).ι ''ᵁ ⊤ ≤ f ⁻¹ᵁ ⊤ :=
    le_top.trans (AlgebraicGeometry.Scheme.Hom.preimage_top f).ge
  have h1 : f.appLE ⊤ ((f ⁻¹ᵁ U.1).ι ''ᵁ ⊤) hle' =
      Y.presheaf.map (homOfLE le_top).op ≫ f.app U.1 ≫ X.presheaf.map (homOfLE hle).op := by
    rw [AlgebraicGeometry.Scheme.Hom.app_eq_appLE, AlgebraicGeometry.Scheme.Hom.appLE_map,
      AlgebraicGeometry.Scheme.Hom.map_appLE]
  change f.appLE ⊤ ((f ⁻¹ᵁ U.1).ι ''ᵁ ⊤) hle' s = 0
  rw [h1, CategoryTheory.ConcreteCategory.comp_apply, CategoryTheory.ConcreteCategory.comp_apply,
    h U, map_zero]

/-- The class of `t` in `k[t]/(t^{r+1})`, viewed as a global section of `D_r = Spec k[t]/(t^{r+1})`. -/
noncomputable def jetBaseParam (k : Type u) [Field k] (r : ℕ) : Γ(jetBase k r, ⊤) :=
  (AlgebraicGeometry.Scheme.ΓSpecIso (CommRingCat.of (MiyaokaMori.RingTheory.GlobalTruncatedParameter k r))).inv
    (MiyaokaMori.Jet.jetProjection k r Polynomial.X)

/-- `t^{r+1} = 0` in `Γ(D_r, ⊤)`. -/
theorem jetBaseParam_pow (k : Type u) [Field k] (r : ℕ) :
    jetBaseParam k r ^ (r + 1) = 0 := by
  -- the computation on the `Spec` side; `jetBase k r` unfolds to it
  -- (`TruncatedJetRing` is `AdjoinRoot (X^(r+1))`; use the restated
  -- `jetProjection_X_pow_succ` instead of `rw [jetProjection, Ideal.Quotient.eq_zero_iff_mem.mpr _]`)
  have h : ((AlgebraicGeometry.Scheme.ΓSpecIso
      (CommRingCat.of (MiyaokaMori.RingTheory.GlobalTruncatedParameter k r))).inv
        (MiyaokaMori.Jet.jetProjection k r Polynomial.X) :
      Γ(AlgebraicGeometry.Spec (CommRingCat.of (MiyaokaMori.RingTheory.GlobalTruncatedParameter k r)), ⊤))
        ^ (r + 1) = 0 := by
    rw [← map_pow, ← map_pow, MiyaokaMori.Jet.jetProjection_X_pow_succ, map_zero]
  exact h

/-- A morphism `f : Z → D_r = Spec k[t]/(t^{r+1})` with `f^*(t) = 0` factors through the closed
point `t ↦ 0 : Spec k → D_r`: the ring map `φ : k[t]/(t^{r+1}) → Γ(Z, ⊤)` of `f` kills `t`, hence
`φ = (φ ∘ η) ∘ ε` (check on constants and on `t`), and `f = Z.toSpecΓ ≫ Spec.map φ`. -/
theorem factor_through_jetBaseZero {k : Type u} [Field k] (r : ℕ) {Z : AlgebraicGeometry.Scheme.{u}}
    (f : Z ⟶ jetBase k r) (hf : f.appTop (jetBaseParam k r) = 0) :
    ∃ g : Z ⟶ AlgebraicGeometry.Spec (CommRingCat.of k), f = g ≫ jetBaseZero k r := by
  -- everything is proved on the `Spec` side and transported by `exact` (`jetBase`, `jetBaseZero`
  -- and `jetBaseParam` unfold to the `Spec` forms)
  have key : ∀ (f' : Z ⟶ AlgebraicGeometry.Spec
      (CommRingCat.of (MiyaokaMori.RingTheory.GlobalTruncatedParameter k r))),
      f'.appTop ((AlgebraicGeometry.Scheme.ΓSpecIso
        (CommRingCat.of (MiyaokaMori.RingTheory.GlobalTruncatedParameter k r))).inv
          (MiyaokaMori.Jet.jetProjection k r Polynomial.X)) = 0 →
      ∃ g : Z ⟶ AlgebraicGeometry.Spec (CommRingCat.of k),
        f' = g ≫ AlgebraicGeometry.Spec.map
          (CommRingCat.ofHom (MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.epsilon (R := k) r)) := by
    intro f hf
    have hψt : ((AlgebraicGeometry.Scheme.ΓSpecIso
        (CommRingCat.of (MiyaokaMori.RingTheory.GlobalTruncatedParameter k r))).inv ≫ f.appTop).hom
          (MiyaokaMori.Jet.jetProjection k r Polynomial.X) = 0 := hf
    have hψ : ((AlgebraicGeometry.Scheme.ΓSpecIso
        (CommRingCat.of (MiyaokaMori.RingTheory.GlobalTruncatedParameter k r))).inv ≫ f.appTop).hom =
        ((((AlgebraicGeometry.Scheme.ΓSpecIso
          (CommRingCat.of (MiyaokaMori.RingTheory.GlobalTruncatedParameter k r))).inv ≫ f.appTop).hom.comp
            (MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.eta r)).comp
              (MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.epsilon (R := k) r)) := by
      apply Ideal.Quotient.ringHom_ext
      apply Polynomial.ringHom_ext
      · intro a
        change _ = ((AlgebraicGeometry.Scheme.ΓSpecIso
          (CommRingCat.of (MiyaokaMori.RingTheory.GlobalTruncatedParameter k r))).inv ≫ f.appTop).hom
            (MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.eta r
              (MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.epsilon (R := k) r
                (MiyaokaMori.Jet.jetProjection k r (Polynomial.C a))))
        rw [MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.epsilon_projection,
          MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.eta_apply, Polynomial.eval_C]
        rfl
      · change ((AlgebraicGeometry.Scheme.ΓSpecIso
          (CommRingCat.of (MiyaokaMori.RingTheory.GlobalTruncatedParameter k r))).inv ≫ f.appTop).hom
            (MiyaokaMori.Jet.jetProjection k r Polynomial.X) =
          ((AlgebraicGeometry.Scheme.ΓSpecIso
          (CommRingCat.of (MiyaokaMori.RingTheory.GlobalTruncatedParameter k r))).inv ≫ f.appTop).hom
            (MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.eta r
              (MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.epsilon (R := k) r
                (MiyaokaMori.Jet.jetProjection k r Polynomial.X)))
        rw [hψt, MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.epsilon_projection, Polynomial.eval_X,
          map_zero, map_zero]
    refine ⟨Z.toSpecΓ ≫ AlgebraicGeometry.Spec.map (CommRingCat.ofHom
      (((AlgebraicGeometry.Scheme.ΓSpecIso
          (CommRingCat.of (MiyaokaMori.RingTheory.GlobalTruncatedParameter k r))).inv ≫ f.appTop).hom.comp
            (MiyaokaMori.RingTheory.GlobalTruncatedParameterAPI.eta r))), ?_⟩
    have h1 : f = Z.toSpecΓ ≫ AlgebraicGeometry.Spec.map ((AlgebraicGeometry.Scheme.ΓSpecIso
        (CommRingCat.of (MiyaokaMori.RingTheory.GlobalTruncatedParameter k r))).inv ≫ f.appTop) := by
      rw [AlgebraicGeometry.Spec.map_comp, ← Category.assoc,
        ← AlgebraicGeometry.Scheme.toSpecΓ_naturality, Category.assoc,
        AlgebraicGeometry.toSpecΓ_SpecMap_ΓSpecIso_inv, Category.comp_id]
    rw [Category.assoc, ← AlgebraicGeometry.Spec.map_comp, ← CommRingCat.ofHom_comp,
      ← hψ, CommRingCat.ofHom_hom]
    exact h1
  exact key f hf

/-- The second projection `pr₂ : T ×_k D_r → D_r` of the jet thickening. -/
noncomputable abbrev jetThickeningSnd {k : Type u} [Field k] (r : ℕ) (T : AlgebraicGeometry.Scheme.{u})
    [T.Over (AlgebraicGeometry.Spec (CommRingCat.of k))] : jetThickening (k := k) r T ⟶ jetBase k r :=
  CategoryTheory.Limits.pullback.snd (T ↘ AlgebraicGeometry.Spec (CommRingCat.of k))
    (jetBase k r ↘ AlgebraicGeometry.Spec (CommRingCat.of k))

/-- The global section `τ = pr₂^*(t)` of `T ×_k D_r`; the ideal it generates cuts out `ι₀(T)`. -/
noncomputable def jetThickeningParam {k : Type u} [Field k] (r : ℕ) (T : AlgebraicGeometry.Scheme.{u})
    [T.Over (AlgebraicGeometry.Spec (CommRingCat.of k))] : Γ(jetThickening (k := k) r T, ⊤) :=
  (jetThickeningSnd (k := k) r T).appTop (jetBaseParam k r)

theorem jetThickeningParam_pow {k : Type u} [Field k] (r : ℕ) (T : AlgebraicGeometry.Scheme.{u})
    [T.Over (AlgebraicGeometry.Spec (CommRingCat.of k))] :
    jetThickeningParam (k := k) r T ^ (r + 1) = 0 := by
  unfold jetThickeningParam
  rw [← map_pow, jetBaseParam_pow, map_zero]

/-- The (quasi-coherent) ideal sheaf `(τ) ⊆ 𝒪_{T ×_k D_r}` generated by `τ = pr₂^*(t)`:
on an affine open `U` it is the principal ideal `(τ|_U)`. -/
noncomputable def jetThickeningParamIdealSheaf {k : Type u} [Field k] (r : ℕ)
    (T : AlgebraicGeometry.Scheme.{u}) [T.Over (AlgebraicGeometry.Spec (CommRingCat.of k))] :
    (jetThickening (k := k) r T).IdealSheafData where
  ideal U := Ideal.span {(jetThickening (k := k) r T).presheaf.map (homOfLE le_top).op
    (jetThickeningParam (k := k) r T)}
  map_ideal_basicOpen U f := by
    rw [Ideal.map_span, Set.image_singleton, ← CategoryTheory.ConcreteCategory.comp_apply,
      ← Functor.map_comp]
    rfl

theorem jetThickeningParamIdealSheaf_ideal {k : Type u} [Field k] (r : ℕ)
    (T : AlgebraicGeometry.Scheme.{u}) [T.Over (AlgebraicGeometry.Spec (CommRingCat.of k))]
    (U : (jetThickening (k := k) r T).affineOpens) :
    (jetThickeningParamIdealSheaf (k := k) r T).ideal U =
      Ideal.span {(jetThickening (k := k) r T).presheaf.map (homOfLE le_top).op
        (jetThickeningParam (k := k) r T)} := rfl

/-- `τ` restricts to zero on the closed subscheme `V(τ)` (sheaf locality + `ker_subschemeι_app`). -/
theorem jetThickeningParamIdealSheaf_subschemeι_appTop_param {k : Type u} [Field k] (r : ℕ)
    (T : AlgebraicGeometry.Scheme.{u}) [T.Over (AlgebraicGeometry.Spec (CommRingCat.of k))] :
    (jetThickeningParamIdealSheaf (k := k) r T).subschemeι.appTop (jetThickeningParam (k := k) r T)
      = 0 := by
  apply AlgebraicGeometry.Scheme.Hom.appTop_eq_zero_of_forall_affineOpens
  intro U
  have hmem : (jetThickening (k := k) r T).presheaf.map (homOfLE le_top).op
      (jetThickeningParam (k := k) r T) ∈
      RingHom.ker ((jetThickeningParamIdealSheaf (k := k) r T).subschemeι.app U).hom := by
    rw [AlgebraicGeometry.Scheme.IdealSheafData.ker_subschemeι_app,
      jetThickeningParamIdealSheaf_ideal]
    exact Ideal.subset_span (Set.mem_singleton _)
  exact hmem

/-- `ι₀.ker ≤ (τ)`: the closed subscheme `V(τ)` factors through the constant-term section. -/
theorem jetConstantTerm_ker_le_paramIdealSheaf {k : Type u} [Field k] (r : ℕ)
    (T : AlgebraicGeometry.Scheme.{u}) [T.Over (AlgebraicGeometry.Spec (CommRingCat.of k))] :
    (jetConstantTerm (k := k) r T).ker ≤ jetThickeningParamIdealSheaf (k := k) r T := by
  obtain ⟨g, hg⟩ := factor_through_jetBaseZero (k := k) r
    ((jetThickeningParamIdealSheaf (k := k) r T).subschemeι ≫ jetThickeningSnd (k := k) r T)
    (by
      rw [AlgebraicGeometry.Scheme.Hom.comp_appTop, CategoryTheory.ConcreteCategory.comp_apply]
      exact jetThickeningParamIdealSheaf_subschemeι_appTop_param (k := k) r T)
  have hpb := jetConstantTerm_isPullback (k := k) r T
  have hψ : hpb.lift g (jetThickeningParamIdealSheaf (k := k) r T).subschemeι hg.symm ≫
      jetConstantTerm (k := k) r T = (jetThickeningParamIdealSheaf (k := k) r T).subschemeι :=
    hpb.lift_snd _ _ _
  have := AlgebraicGeometry.Scheme.Hom.le_ker_comp
    (hpb.lift g (jetThickeningParamIdealSheaf (k := k) r T).subschemeι hg.symm)
    (jetConstantTerm (k := k) r T)
  rwa [hψ, AlgebraicGeometry.Scheme.IdealSheafData.ker_subschemeι] at this

theorem jetConstantTerm_isClosedImmersion_nilpotent {k : Type u} [Field k] (r : ℕ)
    (T : AlgebraicGeometry.Scheme.{u}) [T.Over (AlgebraicGeometry.Spec (CommRingCat.of k))] :
    AlgebraicGeometry.IsClosedImmersion (jetConstantTerm (k := k) r T) ∧
      ∀ U : (jetThickening (k := k) r T).affineOpens, ((jetConstantTerm (k := k) r T).ker.ideal U) ^ (r + 1) = ⊥ := by
  refine ⟨MorphismProperty.of_isPullback (P := @AlgebraicGeometry.IsClosedImmersion)
    (jetConstantTerm_isPullback (k := k) r T) inferInstance, ?_⟩
  intro U
  have hle := jetConstantTerm_ker_le_paramIdealSheaf (k := k) r T U
  rw [jetThickeningParamIdealSheaf_ideal] at hle
  refine le_bot_iff.mp ((Ideal.pow_right_mono hle (r + 1)).trans ?_)
  rw [Ideal.span_singleton_pow, ← map_pow, jetThickeningParam_pow, map_zero,
    Ideal.span_singleton_zero]

end
