import MiyaokaMori.Prelude
import MiyaokaMori.Paper.S2WeightedJets.Jets.JetLinearPiece_Defs
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.QuasicoherentAffineLocal
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.Stacks01ic

/-! # The linear piece of the jet algebra: `Γ(U, L_{q+1})` is generated by the classes `[d_q b]`

For every affine `U ⊆ C` and every coefficient morphism `θ : sec^*Ω_{Z/C} ⟶ L_{q+1} = S_{q+1}/I^{(2)}_{q+1}`
(`jetLinearPiece.IsCoefficientHom`), the sections map `θ.app U` is **surjective** (the first half of the bijectivity
of the coefficient morphism, `DeformedJetAlgebraFiberAtZero_LinearPieceDual`). Notation as in `JetLinearPiece_Defs`.

Proof:
* `AlgebraicGeometry.Scheme.Modules.cokernel_π_app_surjective` (generic, Stacks 01XB): for quasi-coherent `M, N` and
  `f : M ⟶ N`, `Γ(U, cokernel.π f)` is surjective on every affine `U` — `N → coker f → 0` is exact (`ShortComplex.exact_iff_epi`)
  and `Γ(U, -)` is exact on quasi-coherent modules over affine `U` (`gammaAffine_exact_iff`; `coker f` is quasi-coherent by 01IC).
* Every `ℓ ∈ Γ(U, L)` is `π_L(y)` with `y ∈ Γ(U, S_{q+1})`; its chart reading `js y ∈ grading ε r (q+1)` is the class of a
  weighted-homogeneous polynomial `p = Σ_α monomial α c_α` of weight `q+1` in the symbols `X_{(q', b)}` (weight `q'+1`)
  (`BasedJetAlgebra.mem_grading_iff`, `MvPolynomial.as_sum`). Choosing `y_α ∈ Γ(U, S_{q+1})` with `js y_α = [monomial α c_α]`
  (`exists_jetSection_eq`), `y = Σ_α y_α` (`js` is injective and additive), so `ℓ = Σ_α π_L(y_α)`, and:
  - if `α` has degree `≥ 2`, `monomial α c_α ∈ span (reesMonomials w 2 (q+1)) = (P_+)² ∩ P_{q+1}`
    (`irrPow_weightedHomogeneousSubmodule_eq_span`), so `[monomial α c_α] ∈ (J_+)² ∩ J_{q+1}` (`ReesAlgebra.map_mem_irrPow` for the
    graded quotient map), hence `y_α` comes from `Γ(U, I^{(2)}_{q+1})` (`exists_irrelevantPow_app_eq_of_jetSection_mem_irrPow`) and
    `π_L(y_α) = 0` (`cokernel.condition`);
  - otherwise `α` has degree `1` (degree `0` would give weight `0 ≠ q+1`), so `α = single (q', b) 1` with `q'+1 = q+1`, i.e.
    `monomial α c_α = C c_α · X_{(q,b)}` and `[monomial α c_α] = algebraMap c_α · d_q b` (`coeffClass_succ`); then
    `y_α = c_α • x_b` for `x_b` with `js x_b = d_q b`, and `π_L(y_α) = c_α • θ.app U ((db)|_sec)` by the characterisation `hθ`.
  So `ℓ ∈ range (θ.app U)`.

Source: §2 of the paper, eq. (2.7) (the linear part of the `(q+1)`-st jet coefficient); Stacks 01XB.
Edge cases: `U = ⊥` (zero modules); `q = 0` (`I^{(2)}_1 = 0`, every monomial of weight 1 has degree 1); `r = 0` (no `q`).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000
set_option linter.style.haveILetI false

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-! ## Generic: `Γ(U, cokernel.π f)` is surjective over an affine `U` -/

/-- **Sections of a cokernel over an affine open** (Stacks 01XB): for quasi-coherent `M, N` on a scheme and `f : M ⟶ N`, the
sections map `Γ(U, N) → Γ(U, cokernel f)` of `cokernel.π f` is surjective for every affine open `U`. Proof: the complex
`N → coker f → 0` is exact because `cokernel.π f` is an epimorphism (`ShortComplex.exact_iff_epi`), `coker f` is quasi-coherent
(01IC, `isQuasicoherent_kernel`), and `Γ(U, -)` is exact on quasi-coherent modules over affine `U` (`gammaAffine_exact_iff`).
Edge cases: `U = ⊥` (zero modules); `f = 0` (`coker f ≅ N`). -/
theorem AlgebraicGeometry.Scheme.Modules.cokernel_π_app_surjective {X : AlgebraicGeometry.Scheme.{u}}
    {M N : X.Modules} [M.IsQuasicoherent] [N.IsQuasicoherent] (f : M ⟶ N) (U : X.affineOpens) :
    Function.Surjective ((CategoryTheory.Limits.cokernel.π f).app U.1).hom := by
  haveI : (CategoryTheory.Limits.cokernel f).IsQuasicoherent :=
    (AlgebraicGeometry.Scheme.Modules.isQuasicoherent_kernel f).2
  let S : CategoryTheory.ShortComplex X.Modules :=
    CategoryTheory.ShortComplex.mk (CategoryTheory.Limits.cokernel.π f)
      (0 : CategoryTheory.Limits.cokernel f ⟶ CategoryTheory.Limits.cokernel f) (CategoryTheory.Limits.comp_zero)
  have hS : S.Exact := (CategoryTheory.ShortComplex.exact_iff_epi S rfl).mpr inferInstance
  have hex := (AlgebraicGeometry.Scheme.Modules.gammaAffine_exact_iff S).mp hS U
  intro y
  exact (hex y).mp rfl

/-! ## Monomials in the chart ring: decomposables and the linear symbols -/

namespace BasedJetAlgebra

variable {R B : Type u} [CommRing R] [CommRing B] [Algebra R B] (ε : B →ₐ[R] R) (r : ℕ)

attribute [local instance] MvPolynomial.weightedGradedAlgebra

/-- The quotient map `R[X_{(q,b)}] → J_r(B, ε)` is graded for the weights `weight r B`. -/
theorem mk_mem_grading_of_mem_weightedHomogeneousSubmodule (m : ℕ) (p : MvPolynomial (Fin r × B) R)
    (hp : p ∈ MvPolynomial.weightedHomogeneousSubmodule R (weight r B) m) :
    Ideal.Quotient.mk (relations ε r) p ∈ grading ε r m :=
  mk_mem_grading ε r ((MvPolynomial.mem_weightedHomogeneousSubmodule R (weight r B) m p).mp hp)

/-- A monomial of weight `j` and (ordinary) degree `≥ 2` in the symbols has its class in `(J_+)² ∩ J_j`. -/
theorem mk_monomial_mem_irrPow_two (j : ℕ) (α : Fin r × B →₀ ℕ) (c : R)
    (hα : Finsupp.weight (weight r B) α = j) (hdeg : 2 ≤ α.degree) :
    Ideal.Quotient.mk (relations ε r) (MvPolynomial.monomial α c) ∈
      ReesAlgebra.irrPow (grading ε r) 2 j := by
  classical
  have hw : ∀ s : Fin r × B, 0 < weight r B s := fun s => Nat.succ_pos _
  have hmem : MvPolynomial.monomial α c ∈
      ReesAlgebra.irrPow (MvPolynomial.weightedHomogeneousSubmodule R (weight r B)) 2 j := by
    rw [MvPolynomial.irrPow_weightedHomogeneousSubmodule_eq_span (weight r B) hw 2 j]
    have h1 : (MvPolynomial.monomial α (1 : R) : MvPolynomial (Fin r × B) R) ∈
        MvPolynomial.reesMonomials (B := R) (weight r B) 2 j := ⟨α, hα, hdeg, rfl⟩
    have h2 : MvPolynomial.monomial α c = c • MvPolynomial.monomial α (1 : R) := by
      rw [MvPolynomial.smul_monomial, smul_eq_mul, mul_one]
    rw [h2]
    exact Submodule.smul_mem _ c (Submodule.subset_span h1)
  exact ReesAlgebra.map_mem_irrPow (MvPolynomial.weightedHomogeneousSubmodule R (weight r B)) (grading ε r)
    (Ideal.Quotient.mk (relations ε r)) (mk_mem_grading_of_mem_weightedHomogeneousSubmodule ε r) hmem

/-- A monomial of weight `q+1` and degree `≤ 1` in the symbols is `C c · X_{(q, b)}` for some `b`, so its class is
`algebraMap c · d_q b`. -/
theorem mk_monomial_eq_of_degree_le_one (q : ℕ) (hq : q < r) (α : Fin r × B →₀ ℕ) (c : R)
    (hα : Finsupp.weight (weight r B) α = q + 1) (hdeg : α.degree ≤ 1) :
    ∃ b : B, Ideal.Quotient.mk (relations ε r) (MvPolynomial.monomial α c) =
      algebraMap R (BasedJetAlgebra ε r) c * coeffClass ε r (q + 1) b := by
  classical
  have hdeg1 : α.degree = 1 := by
    rcases Nat.le_one_iff_eq_zero_or_eq_one.mp hdeg with h0 | h1
    · exfalso
      rw [Finsupp.degree_eq_zero_iff] at h0
      rw [h0, map_zero] at hα
      exact Nat.succ_ne_zero q hα.symm
    · exact h1
  obtain ⟨s, rfl⟩ := (Finsupp.sum_eq_one_iff α).mp hdeg1
  obtain ⟨q', b⟩ := s
  have hq' : q'.1 + 1 = q + 1 := by
    rw [Finsupp.weight_single, one_smul] at hα
    exact hα
  have hqq : q' = ⟨q, hq⟩ := Fin.ext (Nat.succ_injective hq')
  subst hqq
  refine ⟨b, ?_⟩
  rw [coeffClass_succ ε r q hq b]
  have h1 : (MvPolynomial.monomial (Finsupp.single ((⟨q, hq⟩ : Fin r), b) 1) c : MvPolynomial (Fin r × B) R) =
      MvPolynomial.C c * MvPolynomial.X ((⟨q, hq⟩ : Fin r), b) := by
    rw [MvPolynomial.X, MvPolynomial.C_mul_monomial, mul_one]
  rw [h1, map_mul]
  rfl

end BasedJetAlgebra

/-! ## Surjectivity of the coefficient morphism on affine opens -/

section CoefficientHom

variable {k : Type u} [Field k] {C : SmoothProjectiveCurve k}
    (Z : CategoryTheory.Over C.toScheme) [AlgebraicGeometry.IsAffineHom Z.hom] (sec : C.toScheme ⟶ Z.left)
    (hs : sec ≫ Z.hom = CategoryTheory.CategoryStruct.id _) (r : ℕ)

namespace jetLinearPiece

/-- A section of `S_{q+1}` whose chart reading lies in `(J_+)² ∩ J_{q+1}` dies in `L_{q+1}` (`cokernel.condition`). -/
theorem cokernel_π_app_eq_zero_of_jetSection_mem_irrPow (q : Fin r) (U : C.toScheme.affineOpens)
    (x : Γ((jetGradedAlgebra (k := k) Z sec hs r).1.part (q.1 + 1), U.1))
    (hx : letI := relativeJetScheme.sectionsAlgebra Z U.1
      jetSection Z sec hs r U (q.1 + 1) x ∈
        ReesAlgebra.irrPow (BasedJetAlgebra.grading (relativeJetScheme.augmentation Z sec hs U.1) r) 2 (q.1 + 1)) :
    ((CategoryTheory.Limits.cokernel.π
      ((jetGradedAlgebra (k := k) Z sec hs r).1.irrelevantPow 2 (q.1 + 1)).2).app U.1).hom x = 0 := by
  obtain ⟨y, rfl⟩ := exists_irrelevantPow_app_eq_of_jetSection_mem_irrPow Z sec hs r U 2 (q.1 + 1) x hx
  have h := congrArg (fun φ => (AlgebraicGeometry.Scheme.Modules.Hom.app φ U.1).hom y)
    (CategoryTheory.Limits.cokernel.condition ((jetGradedAlgebra (k := k) Z sec hs r).1.irrelevantPow 2 (q.1 + 1)).2)
  exact h

/-- **Surjectivity of a coefficient morphism on the sections over an affine `U`** (see the module docstring). -/
theorem coefficientHom_app_surjective (q : Fin r) (U : C.toScheme.affineOpens)
    (θ : (AlgebraicGeometry.Scheme.Modules.pullback sec).obj (AlgebraicGeometry.Omega Z.hom) ⟶
      CategoryTheory.Limits.cokernel ((jetGradedAlgebra (k := k) Z sec hs r).1.irrelevantPow 2 (q.1 + 1)).2)
    (hθ : IsCoefficientHom Z sec hs r q θ) :
    Function.Surjective (θ.app U.1).hom := by
  classical
  letI := relativeJetScheme.sectionsAlgebra Z U.1
  haveI : ((jetGradedAlgebra (k := k) Z sec hs r).1.irrelevantPow 2 (q.1 + 1)).1.IsQuasicoherent :=
    (jetGradedAlgebra (k := k) Z sec hs r).1.irrelevantPow_isQuasicoherent 2 (q.1 + 1)
  haveI : ((jetGradedAlgebra (k := k) Z sec hs r).1.part (q.1 + 1)).IsQuasicoherent :=
    (jetGradedAlgebra (k := k) Z sec hs r).1.quasicoherent (q.1 + 1)
  set πL := (CategoryTheory.Limits.cokernel.π
    ((jetGradedAlgebra (k := k) Z sec hs r).1.irrelevantPow 2 (q.1 + 1)).2).app U.1 with hπL
  set N := LinearMap.range (θ.val.app (Opposite.op U.1)).hom with hN
  -- it suffices to show that every `π_L(y)` lies in the range
  suffices key : ∀ y : Γ((jetGradedAlgebra (k := k) Z sec hs r).1.part (q.1 + 1), U.1), πL.hom y ∈ N by
    intro ℓ
    obtain ⟨y, rfl⟩ := AlgebraicGeometry.Scheme.Modules.cokernel_π_app_surjective
      ((jetGradedAlgebra (k := k) Z sec hs r).1.irrelevantPow 2 (q.1 + 1)).2 U ℓ
    exact key y
  intro y
  -- the chart reading of `y` is the class of a weighted-homogeneous polynomial `p` of weight `q+1`
  obtain ⟨p, hp, hpy⟩ := (BasedJetAlgebra.mem_grading_iff _ r (q.1 + 1) _).mp
    (jetSection_mem_grading Z sec hs r U (q.1 + 1) y)
  -- one section `f α` for each monomial of `p`
  have hchoice : ∀ α ∈ p.support, ∃ yα : Γ((jetGradedAlgebra (k := k) Z sec hs r).1.part (q.1 + 1), U.1),
      jetSection Z sec hs r U (q.1 + 1) yα =
        Ideal.Quotient.mk _ (MvPolynomial.monomial α (MvPolynomial.coeff α p)) := by
    intro α hα
    refine exists_jetSection_eq Z sec hs r U (q.1 + 1) _ (BasedJetAlgebra.mk_mem_grading _ r ?_)
    exact MvPolynomial.isWeightedHomogeneous_monomial _ _ _ (hp (MvPolynomial.mem_support_iff.mp hα))
  choose! f hf using hchoice
  -- `y = Σ_α f α`
  have hy : y = ∑ α ∈ p.support, f α := by
    apply jetSection_injective Z sec hs r U (q.1 + 1)
    rw [← jetSectionLin_apply, ← jetSectionLin_apply, map_sum]
    simp only [jetSectionLin_apply]
    rw [Finset.sum_congr rfl (fun α hα => hf α hα), ← map_sum, ← MvPolynomial.as_sum]
    exact hpy.symm
  rw [hy, map_sum]
  refine Submodule.sum_mem N fun α hα => ?_
  have hαw : Finsupp.weight (BasedJetAlgebra.weight r Γ(Z.left, Z.hom ⁻¹ᵁ U.1)) α = q.1 + 1 :=
    hp (MvPolynomial.mem_support_iff.mp hα)
  by_cases hdeg : 2 ≤ α.degree
  · -- decomposable monomial: dies in `L`
    have h0 : πL.hom (f α) = 0 := by
      refine cokernel_π_app_eq_zero_of_jetSection_mem_irrPow Z sec hs r q U (f α) ?_
      rw [hf α hα]
      exact BasedJetAlgebra.mk_monomial_mem_irrPow_two _ r (q.1 + 1) α _ hαw hdeg
    rw [h0]
    exact Submodule.zero_mem N
  · -- linear monomial: `c • d_q b`
    obtain ⟨b, hb⟩ := BasedJetAlgebra.mk_monomial_eq_of_degree_le_one _ r q.1 q.2 α (MvPolynomial.coeff α p) hαw
      (Nat.lt_succ_iff.mp (Nat.lt_of_not_le hdeg))
    obtain ⟨xb, hxb⟩ := exists_jetSection_eq Z sec hs r U (q.1 + 1) _
      (BasedJetAlgebra.coeffClass_mem_grading _ r (q.1 + 1) b)
    have hfα : f α = MvPolynomial.coeff α p • xb := by
      apply jetSection_injective Z sec hs r U (q.1 + 1)
      rw [hf α hα, hb, jetSection_smul, hxb]
    rw [hfα]
    have hsm : πL.hom (MvPolynomial.coeff α p • xb) = MvPolynomial.coeff α p • πL.hom xb :=
      AlgebraicGeometry.Scheme.Modules.Hom.app_smul _ _ _
    rw [hsm]
    refine Submodule.smul_mem N _ ?_
    refine ⟨omegaSection Z sec hs U.1 b, ?_⟩
    exact hθ U b xb hxb

end jetLinearPiece

end CoefficientHom

end
