import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.SectionsRingGeneratedInDegreeOne
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.RelativeProjEvaluation
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.ModuleSheafFrameIso

/-! # The universal quotient `π^*𝒜_1 → O(1)` is an epimorphism (Stacks 01O4)

Second half of Stacks 01O4 (the universal quotient): when `𝒜` is generated by `𝒜_1`, the
canonical evaluation `ψ := relativeProj.evaluation 𝒜 1 : π^*𝒜_1 → O(1)` is an epimorphism.
It combines two lemmas:
* `evaluation_app_unit`: the value of `ψ` on the image `η(a)` of the adjunction unit
  (`a ∈ Γ(U, 𝒜_m)`, `U` affine) is `evaluationLocal 𝒜 m U a`;
* `isFrame_evaluationLocal`: for `a ∈ Γ(U, 𝒜_1)`, `evaluationLocal a` is a frame of `O(1)` on
  the chart principal open `V_a := ι(φ_U⁻¹ D₊(a))`;
together with `irrelevant_le_span_degOne_of_generatedInDegreeOne`, which shows that the `V_a`
cover `π⁻¹U`.

Sources: Stacks 01O4, 01MW(5); the paper uses this for the two projections from the
tautological line of the ruled surface (proof of Proposition 6.1).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- The value of the canonical evaluation on the image of the adjunction unit: for `U` affine,
`a ∈ Γ(U, 𝒜_m)` and `η : 𝒜_m → π_*π^*𝒜_m` the unit of `pullback ⊣ pushforward`,
`ψ_m(η_U(a)) = evaluationLocal 𝒜 m U a ∈ Γ(π⁻¹U, O(m))`
(`Γ(π_*π^*𝒜_m, U)` and `Γ(π^*𝒜_m, π⁻¹U)` are definitionally equal).

This unfolds the definition of `evaluation` in `RelativeProjEvaluation` (`homEquiv.symm` applied
to the morphism `𝒜_m → π_*O(m)` extended from `evaluationBase` on the affine basis by Mathlib's
`TopCat.Sheaf.restrictHomEquivHom`).

Proof: let `g` be the transpose of `evaluation`; `Adjunction.homEquiv_unit` and
`Equiv.apply_symm_apply` give `η ≫ π_*ψ = g`, and taking sections over `U` gives
`ψ.app (π⁻¹U) (η_U a) = g.app U a`; by Mathlib's `TopCat.Sheaf.extend_hom_app`
(`restrictHomEquivHom` recovers the original transformation on a basic open `U`),
`g.app U = evaluationBaseApp 𝒜 m (op U) = evaluationLocal 𝒜 m U`. -/
theorem AlgebraicGeometry.Scheme.relativeProj.evaluation_app_unit
    {X : AlgebraicGeometry.Scheme.{u}} (𝒜 : X.GradedQCAlgebra) (m : ℕ) (U : X.affineOpens)
    (a : Γ(𝒜.part m, U.1)) :
    (AlgebraicGeometry.Scheme.relativeProj.evaluation 𝒜 m).app
        ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ U.1)
        ((((AlgebraicGeometry.Scheme.Modules.pullbackPushforwardAdjunction
          (AlgebraicGeometry.Scheme.relativeProj 𝒜).hom).unit.app (𝒜.part m)).app U.1) a) =
      AlgebraicGeometry.Scheme.relativeProj.evaluationLocal 𝒜 m U a := by
  let π := (AlgebraicGeometry.Scheme.relativeProj 𝒜).hom
  let adj := AlgebraicGeometry.Scheme.Modules.pullbackPushforwardAdjunction π
  let g : 𝒜.part m ⟶ (AlgebraicGeometry.Scheme.Modules.pushforward π).obj
      (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 (m : ℤ)) :=
    SheafOfModules.Hom.mk (PresheafOfModules.homMk
      (AlgebraicGeometry.Scheme.relativeProj.evaluationPresheafHom 𝒜 m)
      (fun V r s =>
        AlgebraicGeometry.Scheme.relativeProj.evaluationPresheafHom_smul 𝒜 m V.unop r s))
  have h1 : adj.unit.app (𝒜.part m) ≫ (AlgebraicGeometry.Scheme.Modules.pushforward π).map
      (AlgebraicGeometry.Scheme.relativeProj.evaluation 𝒜 m) = g := by
    have h0 := (adj.homEquiv _ _).apply_symm_apply g
    rw [Adjunction.homEquiv_unit] at h0
    exact h0
  have h2 := congrArg (fun φ => φ.app U.1 a) h1
  simp only [AlgebraicGeometry.Scheme.Modules.Hom.comp_app, ConcreteCategory.comp_apply] at h2
  refine Eq.trans ?_ (h2.trans ?_)
  · rfl
  · have h3 := TopCat.Sheaf.extend_hom_app (𝒜.part m).presheaf
      ⟨((AlgebraicGeometry.Scheme.Modules.pushforward π).obj
          (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 (m : ℤ))).presheaf,
        ((AlgebraicGeometry.Scheme.Modules.pushforward π).obj
          (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 (m : ℤ))).isSheaf⟩
      AlgebraicGeometry.Scheme.relativeProj.isBasis_affineOpens_val
      (AlgebraicGeometry.Scheme.relativeProj.evaluationBase 𝒜 m) U
    exact congrArg (fun f => f a) h3

/-- The chart principal open `V_a := ι(φ_U⁻¹ D₊(a))`: for `U` affine and `a ∈ Γ(U, 𝒜_m)`, with
`φ_U : π⁻¹U ≅ Proj A(U)` (Stacks 01NQ), `D₊(a)` is the basic open of `a` viewed as an element
of `A(U)_m` (`sectionsOf`). -/
noncomputable def AlgebraicGeometry.Scheme.relativeProj.chartBasicOpen
    {X : AlgebraicGeometry.Scheme.{u}} (𝒜 : X.GradedQCAlgebra) (m : ℕ) (U : X.affineOpens)
    (a : Γ(𝒜.part m, U.1)) : (AlgebraicGeometry.Scheme.relativeProj 𝒜).left.Opens :=
  ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ U.1).ι ''ᵁ
    ((AlgebraicGeometry.Scheme.relativeProj.affineIso 𝒜 U).hom ⁻¹ᵁ
      AlgebraicGeometry.Proj.basicOpen (𝒜.sectionsGrading U.1) (𝒜.sectionsOf U.1 m a).1)

/-- `V_a ⊆ π⁻¹U`. -/
theorem AlgebraicGeometry.Scheme.relativeProj.chartBasicOpen_le
    {X : AlgebraicGeometry.Scheme.{u}} (𝒜 : X.GradedQCAlgebra) (m : ℕ) (U : X.affineOpens)
    (a : Γ(𝒜.part m, U.1)) :
    AlgebraicGeometry.Scheme.relativeProj.chartBasicOpen 𝒜 m U a ≤
      (AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ U.1 :=
  AlgebraicGeometry.Scheme.Modules.image_ι_le _ _

/-- `p ∈ V_a` if `p ∈ π⁻¹U` and `φ_U(p) ∈ D₊(a)`. -/
theorem AlgebraicGeometry.Scheme.relativeProj.mem_chartBasicOpen
    {X : AlgebraicGeometry.Scheme.{u}} (𝒜 : X.GradedQCAlgebra) (m : ℕ) (U : X.affineOpens)
    (a : Γ(𝒜.part m, U.1)) (p : (AlgebraicGeometry.Scheme.relativeProj 𝒜).left)
    (hp : p ∈ (AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ U.1)
    (hq : (AlgebraicGeometry.Scheme.relativeProj.affineIso 𝒜 U).hom.base ⟨p, hp⟩ ∈
      AlgebraicGeometry.Proj.basicOpen (𝒜.sectionsGrading U.1) (𝒜.sectionsOf U.1 m a).1) :
    p ∈ AlgebraicGeometry.Scheme.relativeProj.chartBasicOpen 𝒜 m U a :=
  ⟨⟨p, hp⟩, hq, rfl⟩


/-! ## Frames along the `restrict` of an open immersion versus the image open

`Γ(M.restrict f, O) = Γ(M, f ''ᵁ O)` is `Iso.refl` (Mathlib's `restrictAppIso`), scalars are
transported through `f.appIso O` (`smul_restrictAppIso_hom` is `rfl`), and the restriction maps
are `M.presheaf.map (f.opensFunctor.map _)` (`opensFunctor_map_homOfLE` is `rfl`). Hence the maps
`r ↦ r • e|` on the two sides differ only by composition with the bijection `(f.appIso O').inv`.
(The lemmas `restrict_top` / `restrict_smul_res` of `ModuleSheafFrame` handle only `W.ι`; here `f`
is an arbitrary open immersion, and the converse direction is included.) -/

namespace AlgebraicGeometry.Scheme.Modules

set_option backward.isDefEq.respectTransparency false

/-- Bijectivity of `r ↦ r • e|` depends only on the open set: transport along an equality of
opens (after `subst`, the inclusion proofs are irrelevant). -/
private theorem bijective_smul_res_congr_opens {X : AlgebraicGeometry.Scheme.{u}} (M : X.Modules)
    {W V V' : X.Opens} (hV : V ≤ W) (hV' : V' ≤ W) (h : V = V') (e : Γ(M, W))
    (hb : Function.Bijective (fun r : Γ(X, V) => r • M.res hV e)) :
    Function.Bijective (fun r : Γ(X, V') => r • M.res hV' e) := by
  subst h
  exact hb

/-- Frames along the `restrict` of an open immersion `f`: if `e` is a frame of `M` on the image
open `f ''ᵁ O`, then (through `restrictAppIso.inv`, which is `Iso.refl`) it is a frame of
`M.restrict f` on `O`. -/
theorem IsFrame.restrictAppIso_inv_of_image {X Y : AlgebraicGeometry.Scheme.{u}} (f : X ⟶ Y)
    [AlgebraicGeometry.IsOpenImmersion f]
    {M : Y.Modules} {O : X.Opens} {e : Γ(M, f ''ᵁ O)} (hf : IsFrame M (f ''ᵁ O) e) :
    IsFrame (M.restrict f) O ((M.restrictAppIso f O).inv e) := by
  intro O' h
  have hfun : (fun r : Γ(X, O') => r • (M.restrict f).res h ((M.restrictAppIso f O).inv e)) =
      (fun r' : Γ(Y, f ''ᵁ O') => r' • M.res (f.image_mono h) e) ∘ (f.appIso O').inv := rfl
  rw [hfun]
  exact (hf _ (f.image_mono h)).comp (ConcreteCategory.bijective_of_isIso (f.appIso O').inv)

/-- Conversely, if `e` is a frame of `M.restrict f` on `O`, then (through `restrictAppIso.hom`) it
is a frame of `M` on `f ''ᵁ O`. Every open `W'` inside `f ''ᵁ O` is an image:
`W' = f ''ᵁ (f ⁻¹ᵁ W')` (`image_preimage_eq_opensRange_inf`). -/
theorem IsFrame.restrictAppIso_hom_of_restrict {X Y : AlgebraicGeometry.Scheme.{u}} (f : X ⟶ Y)
    [AlgebraicGeometry.IsOpenImmersion f]
    {M : Y.Modules} {O : X.Opens} {e : Γ(M.restrict f, O)} (hf : IsFrame (M.restrict f) O e) :
    IsFrame M (f ''ᵁ O) ((M.restrictAppIso f O).hom e) := by
  intro W' h
  have hO' : f ⁻¹ᵁ W' ≤ O := by
    have := f.preimage_mono h
    rwa [f.preimage_image_eq] at this
  have hW' : f ''ᵁ (f ⁻¹ᵁ W') = W' := by
    rw [f.image_preimage_eq_opensRange_inf]
    exact inf_eq_right.mpr (h.trans (f.image_le_opensRange O))
  refine bijective_smul_res_congr_opens M (f.image_mono hO') h hW' _ ?_
  have hb := hf (f ⁻¹ᵁ W') hO'
  have hfun : (fun r : Γ(X, f ⁻¹ᵁ W') => r • (M.restrict f).res hO' e) =
      (fun r' : Γ(Y, f ''ᵁ (f ⁻¹ᵁ W')) =>
        r' • M.res (f.image_mono hO') ((M.restrictAppIso f O).hom e)) ∘
        (f.appIso (f ⁻¹ᵁ W')).inv := rfl
  rw [hfun] at hb
  exact (Function.Bijective.of_comp_iff _
    (ConcreteCategory.bijective_of_isIso (f.appIso (f ⁻¹ᵁ W')).inv)).mp hb

end AlgebraicGeometry.Scheme.Modules

/-- For `a ∈ Γ(U, 𝒜_1)`, `evaluationLocal 𝒜 1 U a` (restricted to `V_a`) is a frame of `O(1)` on
`V_a`.

Sources: Stacks 01MW(5) (`x_a` generates `O(1)` on `D₊(a)`), 01NQ, 01NR.

Proof sketch: `evaluationLocal a` is `x_a := Proj.twistSection (sectionsOf a) ∈ Γ(Proj A(U), O(1))`
pulled back along `φ_U` (adjunction unit), transported to `O(1)|_{π⁻¹U}` by `twistAffineIso`⁻¹,
and finally viewed in `Γ(π⁻¹U, O(1))` via "sections of the restricted sheaf = sections on the
image open". By `isFrame_homogeneousSection`, `x_a` is a frame of `O_{Proj A(U)}(1)` on `D₊(a)`
(`a` vanishes nowhere on `D₊(a)`). Being a frame is preserved by: (i) pullback along the
isomorphism of schemes `φ_U`; (ii) the isomorphism of module sheaves `twistAffineIso`⁻¹
(isomorphisms commute with scalar multiplication); (iii) the identification of sections of
`O(1)|_{π⁻¹U}` on `φ_U⁻¹D₊(a)` with sections of `O(1)` on `ι(φ_U⁻¹D₊(a)) = V_a`
(`restrictAppIso`, an `Iso.refl`).

Formal steps:
(i) `MiyaokaMori.WeightedJets.ProjTwisting.isFrame_homogeneousSection`: `x_a|_{D₊(a)}` is a frame of
`G := O_{Proj A(U)}(1)` on `D₊(a)` (`twistSection` is `homogeneousSection … ⊤`; the restriction
is `rfl`).
(ii) `IsFrame.restrict` to `φ ''ᵁ φ⁻¹D₊(a)`, then `IsFrame.restrictAppIso_inv_of_image` makes it
a frame of `G.restrict φ` on `φ⁻¹D₊(a)`, and `IsFrame.map_iso` along
`(restrictFunctorIsoPullback φ).app G` moves it to `φ^*G`; Mathlib's
`Adjunction.unit_leftAdjointUniq_hom_app` and `restrictAdjunction_unit_app_app` show that the
image `η(x_a)` of the pullback adjunction unit is this isomorphism applied to the image of the
restrict adjunction unit (`Hom.app_res` commutes restrictions).
(iii) `IsFrame.map_iso` along `twistAffineIso.symm` to `O(1)|_{π⁻¹U}` (then `Hom.app_res`).
(iv) `IsFrame.restrictAppIso_hom_of_restrict`: a frame of the restricted sheaf on `φ⁻¹D₊(a)` is a
frame of `O(1)` on `ι ''ᵁ φ⁻¹D₊(a) = V_a`.
(v) The target section equals this one by `evaluationLocal_eq` and `res_res` (the rest is `rfl`). -/
theorem AlgebraicGeometry.Scheme.relativeProj.isFrame_evaluationLocal
    {X : AlgebraicGeometry.Scheme.{u}} (𝒜 : X.GradedQCAlgebra) (U : X.affineOpens)
    (a : Γ(𝒜.part 1, U.1)) :
    AlgebraicGeometry.Scheme.Modules.IsFrame (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1)
      (AlgebraicGeometry.Scheme.relativeProj.chartBasicOpen 𝒜 1 U a)
      ((AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1).res
        (AlgebraicGeometry.Scheme.relativeProj.chartBasicOpen_le 𝒜 1 U a)
        (AlgebraicGeometry.Scheme.relativeProj.evaluationLocal 𝒜 1 U a)) := by
  -- notation
  let φ := (AlgebraicGeometry.Scheme.relativeProj.affineIso 𝒜 U).hom
  let ι := ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ U.1).ι
  let G := AlgebraicGeometry.Proj.twist (𝒜.sectionsGrading U.1) ((1 : ℕ) : ℤ)
  let T := AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 ((1 : ℕ) : ℤ)
  let a' := 𝒜.sectionsOf U.1 1 a
  let D := AlgebraicGeometry.Proj.basicOpen (𝒜.sectionsGrading U.1) a'.1
  let s : Γ(G, ⊤) := AlgebraicGeometry.Proj.twistSection (𝒜.sectionsGrading U.1) a'.1 a'.2
  have hDtop : φ ⁻¹ᵁ D ≤ φ ⁻¹ᵁ ⊤ := φ.preimage_mono le_top
  -- (i) x_a is a frame of O_{Proj A(U)}(1) on D₊(a) (a vanishes nowhere on D₊(a))
  have hD : AlgebraicGeometry.Scheme.Modules.IsFrame G D (G.res le_top s) :=
    MiyaokaMori.WeightedJets.ProjTwisting.isFrame_homogeneousSection (𝒜.sectionsGrading U.1) 1
      a'.1 a'.2 D (fun x => x.2)
  -- (ii) transport along restrict φ to φ⁻¹D, then along restrictFunctorIsoPullback to φ^*G
  have hR : AlgebraicGeometry.Scheme.Modules.IsFrame (G.restrict φ) (φ ⁻¹ᵁ D)
      ((G.restrictAppIso φ (φ ⁻¹ᵁ D)).inv (G.res (φ.image_preimage_le D) (G.res le_top s))) :=
    (hD.restrict (φ.image_preimage_le D)).restrictAppIso_inv_of_image φ
  let e₁ := (AlgebraicGeometry.Scheme.Modules.restrictFunctorIsoPullback φ).app G
  have hP := hR.map_iso e₁
  -- image of the adjunction unit = image of the restrict adjunction unit through e₁ (Mathlib unit_leftAdjointUniq_hom_app)
  let u : Γ((AlgebraicGeometry.Scheme.Modules.pullback φ).obj G, φ ⁻¹ᵁ ⊤) :=
    (((AlgebraicGeometry.Scheme.Modules.pullbackPushforwardAdjunction φ).unit.app G).app ⊤).hom s
  have hu : u = e₁.hom.app (φ ⁻¹ᵁ ⊤)
      ((G.restrictAppIso φ (φ ⁻¹ᵁ ⊤)).inv (G.res (φ.image_preimage_le ⊤) s)) := by
    have h1 := CategoryTheory.Adjunction.unit_leftAdjointUniq_hom_app
      (AlgebraicGeometry.Scheme.Modules.restrictAdjunction φ)
      (AlgebraicGeometry.Scheme.Modules.pullbackPushforwardAdjunction φ) G
    have h2 := congrArg (fun ψ => ψ.app ⊤ s) h1
    simp only [AlgebraicGeometry.Scheme.Modules.Hom.comp_app,
      AlgebraicGeometry.Scheme.Modules.pushforward_map_app,
      AlgebraicGeometry.Scheme.Modules.restrictAdjunction_unit_app_app] at h2
    exact h2.symm
  have hu' : ((AlgebraicGeometry.Scheme.Modules.pullback φ).obj G).res hDtop u =
      e₁.hom.app (φ ⁻¹ᵁ D)
        ((G.restrictAppIso φ (φ ⁻¹ᵁ D)).inv (G.res (φ.image_preimage_le D) (G.res le_top s))) := by
    rw [hu, ← AlgebraicGeometry.Scheme.Modules.Hom.app_res]
    rfl
  rw [← hu'] at hP
  -- (iii) transport along twistAffineIso⁻¹ to O(1)|_{π⁻¹U}
  let e₂ := AlgebraicGeometry.Scheme.relativeProj.twistAffineIso 𝒜 U ((1 : ℕ) : ℤ)
  have hQ := hP.map_iso e₂.symm
  rw [CategoryTheory.Iso.symm_hom, AlgebraicGeometry.Scheme.Modules.Hom.app_res] at hQ
  -- (iv) sections of the restricted sheaf = sections on the image open
  have hT := hQ.restrictAppIso_hom_of_restrict ι
  -- (v) match the target section: two restrictions = one restriction (res_res), the rest is rfl
  have heq : (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1).res
      (AlgebraicGeometry.Scheme.relativeProj.chartBasicOpen_le 𝒜 1 U a)
      (AlgebraicGeometry.Scheme.relativeProj.evaluationLocal 𝒜 1 U a) =
      (T.restrictAppIso ι (φ ⁻¹ᵁ D)).hom
        ((T.restrict ι).res hDtop (e₂.inv.app (φ ⁻¹ᵁ ⊤) u)) := by
    rw [AlgebraicGeometry.Scheme.relativeProj.evaluationLocal_eq]
    exact AlgebraicGeometry.Scheme.Modules.res_res T _ _ _
  rw [heq]
  exact hT

/-- The universal quotient: when the algebra is generated in degree one, the canonical evaluation
`ψ = relativeProj.evaluation 𝒜 1 : π^*𝒜_1 → O(1)` is an epimorphism (second half of Stacks
01O4, the universal quotient `π^*E ↠ O(1)` of a projective bundle).

Proof: epimorphisms are checked locally on sections (`epi_iff_locally_surjective_sections`).
Given `s ∈ Γ(O(1), W)` and `p ∈ W`, take an affine `U ∋ π(p)`;
`irrelevant_le_span_degOne_of_generatedInDegreeOne` and Mathlib's `Proj.iSup_basicOpen_eq_top`
give `f ∈ A(U)_1` with `φ_U(p) ∈ D₊(f)`, `f = sectionsOf a` for some `a ∈ Γ(U, 𝒜_1)`; so `p ∈ V_a`.
On `W ⊓ V_a`, `s = r • evaluationLocal a|` (frame coordinate `r`, `isFrame_evaluationLocal`),
and `evaluationLocal a = ψ(η(a))` (`evaluation_app_unit`); since `ψ` is `O`-linear and compatible
with restriction, `ψ(r • η(a)|_{W ⊓ V_a}) = s|_{W ⊓ V_a}`. -/
theorem AlgebraicGeometry.Scheme.relativeProj.epi_evaluation_one
    {X : AlgebraicGeometry.Scheme.{u}} (𝒜 : X.GradedQCAlgebra) (h𝒜 : 𝒜.GeneratedInDegreeOne) :
    CategoryTheory.Epi (AlgebraicGeometry.Scheme.relativeProj.evaluation 𝒜 1) := by
  rw [AlgebraicGeometry.Scheme.Modules.epi_iff_locally_surjective_sections]
  intro W s p hp
  obtain ⟨U, hU, hpU, -⟩ := TopologicalSpace.Opens.isBasis_iff_nbhd.mp X.isBasis_affineOpens
    (TopologicalSpace.Opens.mem_top ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom.base p))
  let Ua : X.affineOpens := ⟨U, hU⟩
  let q : AlgebraicGeometry.Proj (𝒜.sectionsGrading U) :=
    (AlgebraicGeometry.Scheme.relativeProj.affineIso 𝒜 Ua).hom.base ⟨p, hpU⟩
  have hcov : ⨆ f : 𝒜.sectionsGrading U 1,
      AlgebraicGeometry.Proj.basicOpen (𝒜.sectionsGrading U) (f : 𝒜.sectionsRing U) = ⊤ :=
    AlgebraicGeometry.Proj.iSup_basicOpen_eq_top (𝒜.sectionsGrading U)
      (fun f : 𝒜.sectionsGrading U 1 => (f : 𝒜.sectionsRing U))
      ((AlgebraicGeometry.Scheme.GradedQCAlgebra.irrelevant_le_span_degOne_of_generatedInDegreeOne
        𝒜 h𝒜 Ua).trans (Ideal.span_mono fun b hb => ⟨⟨b, hb⟩, rfl⟩))
  have hq : q ∈ ⨆ f : 𝒜.sectionsGrading U 1,
      AlgebraicGeometry.Proj.basicOpen (𝒜.sectionsGrading U) (f : 𝒜.sectionsRing U) := by
    rw [hcov]; exact trivial
  obtain ⟨f, hqf⟩ := TopologicalSpace.Opens.mem_iSup.mp hq
  obtain ⟨a, ha⟩ := f.2
  have hqa : q ∈ AlgebraicGeometry.Proj.basicOpen (𝒜.sectionsGrading U) (𝒜.sectionsOf U 1 a).1 := by
    have : (𝒜.sectionsOf U 1 a).1 = (f : 𝒜.sectionsRing U) := ha
    rw [this]; exact hqf
  let V := AlgebraicGeometry.Scheme.relativeProj.chartBasicOpen 𝒜 1 Ua a
  have hpV : p ∈ V := AlgebraicGeometry.Scheme.relativeProj.mem_chartBasicOpen 𝒜 1 Ua a p hpU hqa
  have hVU := AlgebraicGeometry.Scheme.relativeProj.chartBasicOpen_le 𝒜 1 Ua a
  have hfr := AlgebraicGeometry.Scheme.relativeProj.isFrame_evaluationLocal 𝒜 Ua a
  let T := AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1
  let W' : (AlgebraicGeometry.Scheme.relativeProj 𝒜).left.Opens := W ⊓ V
  have hW'W : W' ≤ W := inf_le_left
  have hW'V : W' ≤ V := inf_le_right
  let s' : Γ(T, W') := T.presheaf.map (homOfLE hW'W).op s
  let r := hfr.coord hW'V s'
  let ya := (((AlgebraicGeometry.Scheme.Modules.pullbackPushforwardAdjunction
    (AlgebraicGeometry.Scheme.relativeProj 𝒜).hom).unit.app (𝒜.part 1)).app U) a
  let P := (AlgebraicGeometry.Scheme.Modules.pullback
    (AlgebraicGeometry.Scheme.relativeProj 𝒜).hom).obj (𝒜.part 1)
  refine ⟨W', hW'W, ⟨hp, hpV⟩, r • P.presheaf.map (homOfLE (hW'V.trans hVU)).op ya, ?_⟩
  have hnat : (AlgebraicGeometry.Scheme.relativeProj.evaluation 𝒜 1).app W'
      (P.presheaf.map (homOfLE (hW'V.trans hVU)).op ya) =
      T.presheaf.map (homOfLE (hW'V.trans hVU)).op
        ((AlgebraicGeometry.Scheme.relativeProj.evaluation 𝒜 1).app
          ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ U) ya) :=
    PresheafOfModules.naturality_apply (AlgebraicGeometry.Scheme.relativeProj.evaluation 𝒜 1).val
      (homOfLE (hW'V.trans hVU)).op ya
  have key := hfr.coord_smul_frame hW'V s'
  rw [AlgebraicGeometry.Scheme.Modules.res_res] at key
  rw [AlgebraicGeometry.Scheme.Modules.Hom.app_smul, hnat,
    AlgebraicGeometry.Scheme.relativeProj.evaluation_app_unit 𝒜 1 Ua a]
  exact key

end
