import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Proj.RelativeProj.GeneratedInDegreeOne
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.SheafOfModulesIsLineBundle
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.ProjTwistingSheaf
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.RelativeProjTwistQC
import MiyaokaMori.AlgebraicGeometry.Modules.Algebra.SectionsRingGeneratedInDegreeOne
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.RelativeProjEvaluationEpi
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.Stacks01ms
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.Stacks01nr
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.WeightedProjCoordinateFormula

/-! # Invertibility of `O(n)` and the universal quotient (Stacks 01O4)

Stacks 01O4: if `A` is generated by `A_1` over `A_0`, then every `O(n)` on `Proj_S(A)` is
invertible and the canonical map `π^*A_1 → O(1)` is surjective (the universal quotient
`π^*E ↠ O(1)` of a projective bundle `P(E)`). The paper uses this for the two projections from
the tautological line of the ruled surface (proof of Proposition 6.1).

The proof combines:
* `Modules.IsLineBundle.of_restrict_nhds`: being a line bundle is a local property.
* `Proj.twist_isLineBundle_of_irrelevant_le_span_degOne`: the absolute case, `O(n)` is
  invertible when `A_+ ⊆ (A_1)`. For `n ≥ 0` the frame `homogeneousCoordinateFrameIso`
  (`f^n` is a frame of `O(n)` on `D₊(f)`) is used; for `n < 0` Stacks 01MS
  (`Proj.twist_mul_isIso_on_basicOpen` with `d = 1`).
* `GradedQCAlgebra.irrelevant_le_span_degOne_of_generatedInDegreeOne`: generation in degree
  one at the sheaf level implies `A(U)_+ ⊆ (A(U)_1)` for the sections ring `A(U)` of an affine
  open `U`.
* `relativeProj.twist_restrict_isLineBundle_of_affine`: transport along
  `π⁻¹U ≅ Proj A(U)` and `O(n)|_{π⁻¹U} ≅ φ^*O_{Proj A(U)}(n)` (Stacks 01NQ, 01NR).
* `relativeProj.epi_evaluation_one` (module `RelativeProjEvaluationEpi`): the universal
  quotient `ψ := relativeProj.evaluation 𝒜 1` is an epimorphism.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- Being a line bundle is local: if every point has an open neighbourhood `V` such that `M|_V`
is a line bundle, then `M` is a line bundle (Stacks 01CR: invertibility is a local condition).
Proof: take a neighbourhood `V` of `x` and a trivialization `e` of `M|_V` on an open `W ∋ x` of
`V`; `U := V.ι ''ᵁ W` is an open of `X`, and the isomorphism of schemes `φ : U ≅ W`
(`IsOpenImmersion.isoOfRangeEq`, both have the same image in `X`) satisfies
`φ ≫ W.ι ≫ V.ι = U.ι`, so `M|_U ≅ (M|_V|_W)|_φ ≅ O_W|_φ ≅ O_U`
(Mathlib `restrictFunctorComp` / `restrictFunctorCongr` / `restrictUnitIso`). -/
theorem AlgebraicGeometry.Scheme.Modules.IsLineBundle.of_restrict_nhds
    {X : AlgebraicGeometry.Scheme.{u}} (M : X.Modules)
    (h : ∀ x : X, ∃ V : X.Opens, x ∈ V ∧ (M.restrict V.ι).IsLineBundle) : M.IsLineBundle := by
  refine ⟨fun x => ?_⟩
  obtain ⟨V, hxV, hV⟩ := h x
  obtain ⟨W, hxW, ⟨e⟩⟩ := hV.locally_trivial ⟨x, hxV⟩
  refine ⟨V.ι ''ᵁ W, ⟨⟨x, hxV⟩, hxW, rfl⟩, ⟨?_⟩⟩
  let j : W.toScheme ⟶ X := W.ι ≫ V.ι
  have hrange : Set.range (V.ι ''ᵁ W).ι = Set.range j := by
    rw [AlgebraicGeometry.Scheme.Opens.range_ι]
    change ((V.ι ''ᵁ W : X.Opens) : Set X) = Set.range (V.ι.base ∘ W.ι.base)
    rw [Set.range_comp, AlgebraicGeometry.Scheme.Hom.coe_image]
    congr 1
    exact (AlgebraicGeometry.Scheme.Opens.range_ι W).symm
  let φ : (V.ι ''ᵁ W).toScheme ≅ W.toScheme :=
    AlgebraicGeometry.IsOpenImmersion.isoOfRangeEq (V.ι ''ᵁ W).ι j hrange
  have hfac : φ.hom ≫ j = (V.ι ''ᵁ W).ι :=
    AlgebraicGeometry.IsOpenImmersion.isoOfRangeEq_hom_fac _ _ hrange
  exact (AlgebraicGeometry.Scheme.Modules.restrictFunctorCongr hfac.symm).app M ≪≫
    (AlgebraicGeometry.Scheme.Modules.restrictFunctorComp φ.hom j).app M ≪≫
    (AlgebraicGeometry.Scheme.Modules.restrictFunctor φ.hom).mapIso
      ((AlgebraicGeometry.Scheme.Modules.restrictFunctorComp W.ι V.ι).app M ≪≫ e) ≪≫
    AlgebraicGeometry.Scheme.Modules.restrictUnitIso φ.hom

/-- The absolute case (Stacks 01MS / first half of 01O4): if the graded ring `A` satisfies
`A_+ ⊆ (A_1)` (the irrelevant ideal is contained in the ideal generated by `A_1`, i.e. `A` is
generated by `A_1` over `A_0`), then every `O(n)` (`n ∈ ℤ`) on `Proj A` is a line bundle.
Proof: Mathlib's `Proj.iSup_basicOpen_eq_top` shows that the `D₊(f)`, `f ∈ A_1`, cover `Proj A`;
being a line bundle is local (`IsLineBundle.of_restrict_nhds`), and on `D₊(f)`: for `n ≥ 0`,
`f^n ∈ A_n` vanishes nowhere and is a frame of `O(n)` (`homogeneousCoordinateFrameIso`); for
`n < 0` use Stacks 01MS (`twist_mul_isIso_on_basicOpen` with `d = 1`). -/
theorem AlgebraicGeometry.Proj.twist_isLineBundle_of_irrelevant_le_span_degOne {σ A : Type u}
    [CommRing A] [SetLike σ A] [AddSubgroupClass σ A] (𝒜 : ℕ → σ) [GradedRing 𝒜]
    (h : (HomogeneousIdeal.irrelevant 𝒜).toIdeal ≤ Ideal.span (𝒜 1 : Set A)) (n : ℤ) :
    (AlgebraicGeometry.Proj.twist 𝒜 n).IsLineBundle := by
  apply AlgebraicGeometry.Scheme.Modules.IsLineBundle.of_restrict_nhds
  intro x
  have hcov : ⨆ f : 𝒜 1, AlgebraicGeometry.Proj.basicOpen 𝒜 (f : A) = ⊤ :=
    AlgebraicGeometry.Proj.iSup_basicOpen_eq_top 𝒜 (fun f : 𝒜 1 => (f : A))
      (h.trans (Ideal.span_mono fun a ha => ⟨⟨a, ha⟩, rfl⟩))
  have hx : x ∈ ⨆ f : 𝒜 1, AlgebraicGeometry.Proj.basicOpen 𝒜 (f : A) := by
    rw [hcov]; exact trivial
  obtain ⟨f, hxf⟩ := TopologicalSpace.Opens.mem_iSup.mp hx
  refine ⟨AlgebraicGeometry.Proj.basicOpen 𝒜 (f : A), hxf, ?_⟩
  rcases n with k | k
  · -- n = k ≥ 0: f^k is a frame of O(k) on D₊(f) (homogeneousCoordinateFrameIso)
    have hfk : (f : A) ^ k ∈ 𝒜 k := by
      simpa using SetLike.pow_mem_graded k f.2
    have hU : ∀ y : (AlgebraicGeometry.Proj.basicOpen 𝒜 (f : A)),
        (f : A) ^ k ∉ y.1.asHomogeneousIdeal := by
      intro y hy
      have hy' : (f : A) ^ k ∈ y.1.asHomogeneousIdeal.toIdeal := hy
      exact y.2 (y.1.isPrime.mem_of_pow_mem k hy')
    have e := MiyaokaMori.WeightedJets.ProjTwisting.homogeneousCoordinateFrameIso 𝒜 k ((f : A) ^ k) hfk
      (AlgebraicGeometry.Proj.basicOpen 𝒜 (f : A)) hU
    exact AlgebraicGeometry.Scheme.Modules.IsLineBundle.of_iso e.symm
  · -- n < 0: Stacks 01MS (d = 1)
    obtain ⟨e⟩ := (AlgebraicGeometry.Proj.twist_mul_isIso_on_basicOpen 𝒜 (f : A) f.2 Nat.one_pos
      (Int.negSucc k) 0).1
    have hm : Int.negSucc k * ((1 : ℕ) : ℤ) = Int.negSucc k := by simp
    rw [hm] at e
    exact AlgebraicGeometry.Scheme.Modules.IsLineBundle.of_iso e.symm

/-- On an affine open `U`: if `O(n)` on `Proj A(U)` is a line bundle, then so is
`O_{Proj_X 𝒜}(n)|_{π⁻¹U}` (transport along `φ_U : π⁻¹U ≅ Proj A(U)` of Stacks 01NQ and
`O(n)|_{π⁻¹U} ≅ φ_U^* O(n)` of Stacks 01NR; the pullback of a line bundle is a line bundle). -/
theorem AlgebraicGeometry.Scheme.relativeProj.twist_restrict_isLineBundle_of_affine
    {X : AlgebraicGeometry.Scheme.{u}} (𝒜 : X.GradedQCAlgebra) (n : ℤ) (U : X.affineOpens)
    (h : (AlgebraicGeometry.Proj.twist (𝒜.sectionsGrading U.1) n).IsLineBundle) :
    ((AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 n).restrict
      ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ U.1).ι).IsLineBundle := by
  have := h
  exact AlgebraicGeometry.Scheme.Modules.IsLineBundle.of_iso
    (AlgebraicGeometry.Scheme.relativeProj.twistAffineIso 𝒜 U n).symm

/-- When the algebra is generated in degree one, every `O(n)` on the relative Proj is a line
bundle (first half of Stacks 01O4). -/
theorem AlgebraicGeometry.Scheme.relativeProj.twist_isLineBundle_of_generatedInDegreeOne
    {X : AlgebraicGeometry.Scheme.{u}} (𝒜 : X.GradedQCAlgebra) (h𝒜 : 𝒜.GeneratedInDegreeOne)
    (n : ℤ) : (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 n).IsLineBundle := by
  apply AlgebraicGeometry.Scheme.Modules.IsLineBundle.of_restrict_nhds
  intro p
  obtain ⟨U, hU, hpU, -⟩ := TopologicalSpace.Opens.isBasis_iff_nbhd.mp X.isBasis_affineOpens
    (TopologicalSpace.Opens.mem_top ((AlgebraicGeometry.Scheme.relativeProj 𝒜).hom.base p))
  refine ⟨(AlgebraicGeometry.Scheme.relativeProj 𝒜).hom ⁻¹ᵁ U, hpU, ?_⟩
  exact AlgebraicGeometry.Scheme.relativeProj.twist_restrict_isLineBundle_of_affine 𝒜 n ⟨U, hU⟩
    (AlgebraicGeometry.Proj.twist_isLineBundle_of_irrelevant_le_span_degOne _
      (AlgebraicGeometry.Scheme.GradedQCAlgebra.irrelevant_le_span_degOne_of_generatedInDegreeOne
        𝒜 h𝒜 ⟨U, hU⟩) n)

/-- Stacks 01O4: for an algebra generated in degree one, every `O(n)` is a line bundle and the
universal quotient `π^*𝒜_1 → O(1)` is an epimorphism. -/
theorem AlgebraicGeometry.Scheme.relativeProj.twist_one_universalQuotient {S : AlgebraicGeometry.Scheme.{u}}
    (𝒜 : S.GradedQCAlgebra) (h𝒜 : 𝒜.GeneratedInDegreeOne) :
    (∀ n : ℤ, (AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 n).IsLineBundle) ∧
    ∃ ψ : (AlgebraicGeometry.Scheme.Modules.pullback (AlgebraicGeometry.Scheme.relativeProj 𝒜).hom).obj
            (𝒜.part 1) ⟶ AlgebraicGeometry.Scheme.relativeProj.twist 𝒜 1,
      CategoryTheory.Epi ψ :=
  ⟨AlgebraicGeometry.Scheme.relativeProj.twist_isLineBundle_of_generatedInDegreeOne 𝒜 h𝒜,
    ⟨AlgebraicGeometry.Scheme.relativeProj.evaluation 𝒜 1,
      AlgebraicGeometry.Scheme.relativeProj.epi_evaluation_one 𝒜 h𝒜⟩⟩

end
