import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.ProjTwistingSheaf
import MiyaokaMori.AlgebraicGeometry.Modules.Pullback.ModulesRestrictMonoidal
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.WeightedProjNegativeFrame

/-! # Stacks 01MS: local triviality of `O(nd)` on `D₊(f)` and the multiplication isomorphism

Stacks 01MS: for `f ∈ S` homogeneous of degree `d > 0`, the sheaf `O_{Proj S}(nd)` is trivial on `D₊(f)` (generated by
`f^n`), and the multiplication map `O(nd) ⊗ O(m) → O(nd + m)` is an isomorphism on `D₊(f)`.

Source: Stacks 01MS; Lemma 2.2 of the paper (`O(m)` is invertible for sufficiently divisible
`m`).

* **Trivialization**: `g ∈ 𝒜 j` is a frame of `O(j)` on `D₊(g)` (`isFrame_homogeneousSection`) and `1/g` is a frame of
  `O(-j)` (`isFrame_inverseSection`). Take `g = f^|n|` (of degree `|n|·d`, nowhere vanishing on `D₊(f)`); use the former
  for `n ≥ 0` and the latter for `n < 0`, and then the general `Scheme.Modules.IsFrame.restrictIso` gives
  `O(nd)|_{D₊(f)} ≅ O_{D₊(f)}`.
* **Multiplication isomorphism**: without stalks and without the monoidal structure. `twistMul = L(twistMulPresheaf) ≫ ε`
  (transpose along the sheafification adjunction), and sheafification commutes with restriction along an open immersion
  (`sheafifyRestrictHom_naturality`), so it suffices to show that the presheaf morphism `twistMulPresheaf`, restricted
  to `D₊(f)`, is an isomorphism on every open set, i.e. that for every `W ⊆ D₊(f)` the map
  `O(a)(W) ⊗_{O(W)} O(b)(W) → O(a+b)(W)`, `s ⊗ t ↦ st`, is bijective. This follows from the purely linear-algebraic
  lemma `TensorProduct.lift_bijective_of_frame`: `O(a)(W)` has the frame `e = f^n` (`r ↦ r • e` is bijective), and
  `t ↦ e·t : O(b)(W) → O(a+b)(W)` has the inverse `u ↦ e⁻¹·u` (`e⁻¹ = f^{-n}` is a section of `O(-a)(W)`).

The hypothesis `hd : 0 < d` is not used in either half (`f^|n|` is nowhere vanishing on `D₊(f)` regardless of `d`); it is
kept to match the statement of Stacks 01MS.
-/
set_option autoImplicit false
set_option maxHeartbeats 400000
-- As in `ProjTwistingSheaf` / `WeightedProjCoordinateFormula`: definitional-equality checks on homogeneous localizations.
set_option backward.isDefEq.respectTransparency false

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry TensorProduct

noncomputable section

/-- **Pure linear algebra**: let `μ : M₁ × M₂ → M₃` be bilinear; if `e ∈ M₁` is a "frame" (`r ↦ r • e` is bijective)
and `μ(e, ·) : M₂ → M₃` is bijective, then `TensorProduct.lift μ : M₁ ⊗ M₂ → M₃` is bijective.
Proof: the composite of `M₂ ≃ R ⊗ M₂ ≃ M₁ ⊗ M₂` (`lid⁻¹`, then `rTensor` of the frame isomorphism) with `lift μ` is
`μ(e, ·)`. -/
theorem TensorProduct.lift_bijective_of_frame {R : Type*} [CommRing R]
    {M₁ M₂ M₃ : Type*} [AddCommGroup M₁] [AddCommGroup M₂] [AddCommGroup M₃]
    [Module R M₁] [Module R M₂] [Module R M₃]
    (μ : M₁ →ₗ[R] M₂ →ₗ[R] M₃) (e : M₁)
    (he : Function.Bijective (fun r : R => r • e))
    (hμ : Function.Bijective (μ e)) :
    Function.Bijective (TensorProduct.lift μ) := by
  let φ : R ≃ₗ[R] M₁ := LinearEquiv.ofBijective (LinearMap.toSpanSingleton R M₁ e) he
  let ψ : M₂ ≃ₗ[R] M₁ ⊗[R] M₂ :=
    (TensorProduct.lid R M₂).symm ≪≫ₗ LinearEquiv.rTensor M₂ φ
  have hcomp : ∀ t : M₂, TensorProduct.lift μ (ψ t) = μ e t := by
    intro t
    simp only [ψ, φ, LinearEquiv.trans_apply, TensorProduct.lid_symm_apply,
      LinearEquiv.rTensor_tmul, TensorProduct.lift.tmul, LinearEquiv.ofBijective_apply,
      LinearMap.toSpanSingleton_apply, one_smul]
  have hfun : (TensorProduct.lift μ : M₁ ⊗[R] M₂ → M₃) =
      (μ e : M₂ → M₃) ∘ ψ.symm := by
    funext z
    rw [Function.comp_apply, ← hcomp, LinearEquiv.apply_symm_apply]
  rw [hfun]
  exact hμ.comp ψ.symm.bijective

namespace AlgebraicGeometry.Scheme.Modules

variable {X Y : AlgebraicGeometry.Scheme.{u}} (f : X ⟶ Y) [AlgebraicGeometry.IsOpenImmersion f]

/-- General form: `R.map (L_Y φ) = h_P⁻¹ ≫ L_X (R_pre φ) ≫ h_Q` (`sheafifyRestrictHom_naturality` rearranged). -/
theorem restrictFunctor_map_sheafify_map_eq
    {P Q : _root_.PresheafOfModules.{u} Y.ringCatSheaf.obj} (φ : P ⟶ Q) :
    (restrictFunctor f).map ((sheafifyZ Y).map φ) =
      inv (sheafifyRestrictHom f P) ≫
        (sheafifyZ X).map ((restrictPre f).map φ) ≫ sheafifyRestrictHom f Q := by
  rw [sheafifyRestrictHom_naturality f φ, IsIso.inv_hom_id_assoc]

/-- General form: if `R_pre φ` is an isomorphism, then so is `R.map (L_Y φ)`. -/
theorem isIso_restrictFunctor_map_sheafify_map
    {P Q : _root_.PresheafOfModules.{u} Y.ringCatSheaf.obj} (φ : P ⟶ Q)
    (hφ : IsIso ((restrictPre f).map φ)) :
    IsIso ((restrictFunctor f).map ((sheafifyZ Y).map φ)) := by
  rw [restrictFunctor_map_sheafify_map_eq f φ]
  have h2 : IsIso ((sheafifyZ X).map ((restrictPre f).map φ)) := inferInstance
  infer_instance

/-- General form: the counit of the sheafification adjunction is an isomorphism on sheaves, and remains one after
restriction. -/
theorem isIso_restrictFunctor_map_counit_app (M : Y.Modules) :
    IsIso ((restrictFunctor f).map ((adjZ Y).counit.app M)) := by
  have hciso : IsIso (_root_.PresheafOfModules.sheafificationAdjunction
      (𝟙 Y.ringCatSheaf.obj)).counit := inferInstance
  have hc : IsIso ((adjZ Y).counit.app M) := @NatIso.isIso_app_of_isIso _ _ _ _ _ _ _ hciso _
  infer_instance

/-- General form: `L_Y φ ≫ ε_M` is an isomorphism after restriction (when the restriction of `φ` is an isomorphism). -/
theorem isIso_restrictFunctor_map_sheafify_map_comp_counit
    {P : _root_.PresheafOfModules.{u} Y.ringCatSheaf.obj} {M : Y.Modules}
    (φ : P ⟶ (forgetZ Y).obj M) (hφ : IsIso ((restrictPre f).map φ)) :
    IsIso ((restrictFunctor f).map ((sheafifyZ Y).map φ ≫ (adjZ Y).counit.app M)) := by
  rw [Functor.map_comp]
  have h1 := isIso_restrictFunctor_map_sheafify_map f φ hφ
  have h2 := isIso_restrictFunctor_map_counit_app f M
  infer_instance

/-- General form: if a morphism of presheaves of modules `φ` is bijective on every `f ''ᵁ V`, then `R_pre φ` is an
isomorphism (the underlying function of `(R_pre φ).app V` is that of `φ.app (f ''ᵁ V)`, Mathlib's
`pushforward_map_app_apply`). -/
theorem isIso_restrictPre_map_of_bijective
    {P Q : _root_.PresheafOfModules.{u} Y.ringCatSheaf.obj} (φ : P ⟶ Q)
    (h : ∀ V : X.Opens, Function.Bijective (φ.app (op (f ''ᵁ V))).hom) :
    IsIso ((restrictPre f).map φ) := by
  refine _root_.PresheafOfModules.isIso_of_isIso_app _ (fun V => ?_)
  refine (ConcreteCategory.isIso_iff_bijective _).mpr ?_
  exact h V.unop

end AlgebraicGeometry.Scheme.Modules

namespace AlgebraicGeometry.Proj

open MiyaokaMori.WeightedJets.ProjTwisting

variable {σ A : Type u} [CommRing A] [SetLike σ A] [AddSubgroupClass σ A] (𝒜 : ℕ → σ) [GradedRing 𝒜]

/-- Change of index (`sectionsSubmodule 𝒜 c W` is a subtype of the same function type for every `c`). -/
def castSection {c c' : ℤ} (h : c = c') {W : Opens (ProjectiveSpectrum.top 𝒜)}
    (s : sectionsSubmodule 𝒜 c W) : sectionsSubmodule 𝒜 c' W :=
  ⟨s.1, h ▸ s.2⟩

/-- **Bijectivity of the multiplication on sections**: if `e ∈ O(a)(W)` and `e' ∈ O(c)(W)` are pointwise inverse
(`e·e' = 1`) and `r ↦ r • e` is bijective, then `O(a)(W) ⊗_{O(W)} O(b)(W) → O(a+b)(W)`, `s ⊗ t ↦ st` (the component of
`twistMulPresheaf` on `W`) is bijective. -/
theorem twistMulPresheaf_app_bijective (a b c : ℤ) (hc : c + (a + b) = b)
    (W : Opens (ProjectiveSpectrum.top 𝒜))
    (e : sectionsSubmodule 𝒜 a W) (e' : sectionsSubmodule 𝒜 c W)
    (hee' : ∀ x : W, e.1 x * e'.1 x = 1)
    (he : Function.Bijective
      (fun r : (ProjectiveSpectrum.Proj.structureSheaf 𝒜).obj.obj (op W) => r • e)) :
    Function.Bijective ((twistMulPresheaf 𝒜 a b).app (op W)).hom := by
  show Function.Bijective (TensorProduct.lift _)
  refine TensorProduct.lift_bijective_of_frame _ e he ?_
  show Function.Bijective (fun t : sectionsSubmodule 𝒜 b W => twistSectionMul 𝒜 a b W e t)
  refine Function.bijective_iff_has_inverse.mpr
    ⟨fun u => castSection 𝒜 hc (twistSectionMul 𝒜 c (a + b) W e' u), ?_, ?_⟩
  · intro t
    apply Subtype.ext
    funext x
    change e'.1 x * (e.1 x * t.1 x) = t.1 x
    rw [← mul_assoc, mul_comm (e'.1 x), hee', one_mul]
  · intro u
    apply Subtype.ext
    funext x
    change e.1 x * (e'.1 x * u.1 x) = u.1 x
    rw [← mul_assoc, hee', one_mul]

/-- For `f ∈ 𝒜 d`, `a = n·d` and `W ⊆ D₊(f)`, the component of `twistMulPresheaf 𝒜 a b` on `W` is bijective.
For `n ≥ 0` the frame is `e = f^n` with inverse `e' = 1/f^n`; for `n < 0` the roles are exchanged. -/
theorem twistMulPresheaf_app_bijective_of_le_basicOpen (f : A) {d : ℕ} (hf : f ∈ 𝒜 d)
    (a : ℤ) (n : ℤ) (ha : a = n * d) (b : ℤ)
    (W : Opens (ProjectiveSpectrum.top 𝒜)) (hW : W ≤ basicOpen 𝒜 f) :
    Function.Bijective ((twistMulPresheaf 𝒜 a b).app (op W)).hom := by
  have hpow : ∀ k : ℕ, f ^ k ∈ 𝒜 (k * d) := fun k ↦ by
    simpa only [smul_eq_mul] using SetLike.pow_mem_graded k hf
  have hnv : ∀ k : ℕ, ∀ x : W, f ^ k ∉ x.1.asHomogeneousIdeal := fun k x ↦
    x.1.asHomogeneousIdeal.toIdeal.primeCompl.pow_mem (hW x.2) k
  rcases le_or_gt 0 n with hn | hn
  · obtain ⟨k, rfl⟩ : ∃ k : ℕ, n = k := ⟨n.toNat, by omega⟩
    have : a = ((k * d : ℕ) : ℤ) := by rw [ha]; push_cast; ring
    subst this
    refine twistMulPresheaf_app_bijective 𝒜 _ b (-((k * d : ℕ) : ℤ)) (by ring) W
      (homogeneousSection 𝒜 (k * d) (f ^ k) (hpow k) W)
      (inverseSection 𝒜 (k * d) (f ^ k) (hpow k) (hnv k)) ?_ ?_
    · intro x
      exact fiber_coordinate_mul_inverse 𝒜 (f ^ k) x.1 (hnv k x)
    · exact (homogeneousFrameSectionEquiv 𝒜 (k * d) (f ^ k) (hpow k) (hnv k)).bijective
  · obtain ⟨k, rfl⟩ : ∃ k : ℕ, n = -(k : ℤ) := ⟨n.natAbs, by omega⟩
    have : a = -((k * d : ℕ) : ℤ) := by rw [ha]; push_cast; ring
    subst this
    refine twistMulPresheaf_app_bijective 𝒜 _ b ((k * d : ℕ) : ℤ) (by ring) W
      (inverseSection 𝒜 (k * d) (f ^ k) (hpow k) (hnv k))
      (homogeneousSection 𝒜 (k * d) (f ^ k) (hpow k) W) ?_ ?_
    · intro x
      exact fiber_inverse_mul_coordinate 𝒜 (f ^ k) x.1 (hnv k x)
    · exact (inverseFrameSectionEquiv 𝒜 (k * d) (f ^ k) (hpow k) (hnv k)).bijective

/-- `O(nd)` has a frame on `D₊(f)`: `f^n` for `n ≥ 0` (`isFrame_homogeneousSection`), `1/f^{-n}` for `n < 0`
(`isFrame_inverseSection`). -/
theorem exists_isFrame_twist_basicOpen (f : A) {d : ℕ} (hf : f ∈ 𝒜 d) (a : ℤ) (n : ℤ)
    (ha : a = n * d) :
    ∃ e : Γ(twist 𝒜 a, basicOpen 𝒜 f),
      Scheme.Modules.IsFrame (twist 𝒜 a) (basicOpen 𝒜 f) e := by
  have hpow : ∀ k : ℕ, f ^ k ∈ 𝒜 (k * d) := fun k ↦ by
    simpa only [smul_eq_mul] using SetLike.pow_mem_graded k hf
  have hnv : ∀ k : ℕ, ∀ x : (basicOpen 𝒜 f : Opens (ProjectiveSpectrum.top 𝒜)),
      f ^ k ∉ x.1.asHomogeneousIdeal := fun k x ↦
    x.1.asHomogeneousIdeal.toIdeal.primeCompl.pow_mem x.2 k
  rcases le_or_gt 0 n with hn | hn
  · obtain ⟨k, rfl⟩ : ∃ k : ℕ, n = k := ⟨n.toNat, by omega⟩
    have : a = ((k * d : ℕ) : ℤ) := by rw [ha]; push_cast; ring
    subst this
    exact ⟨_, isFrame_homogeneousSection 𝒜 (k * d) (f ^ k) (hpow k) (basicOpen 𝒜 f) (hnv k)⟩
  · obtain ⟨k, rfl⟩ : ∃ k : ℕ, n = -(k : ℤ) := ⟨n.natAbs, by omega⟩
    have : a = -((k * d : ℕ) : ℤ) := by rw [ha]; push_cast; ring
    subst this
    exact ⟨_, isFrame_inverseSection 𝒜 (k * d) (f ^ k) (hpow k) (basicOpen 𝒜 f) (hnv k)⟩

/-- The presheaf morphism `twistMulPresheaf 𝒜 a b` restricted along `D₊(f) ↪ Proj` is an isomorphism (bijective on every
open set). -/
theorem isIso_restrictPre_map_twistMulPresheaf (f : A) {d : ℕ} (hf : f ∈ 𝒜 d)
    (a : ℤ) (n : ℤ) (ha : a = n * d) (b : ℤ) :
    IsIso ((Scheme.Modules.restrictPre (basicOpen 𝒜 f).ι).map (twistMulPresheaf 𝒜 a b)) :=
  Scheme.Modules.isIso_restrictPre_map_of_bijective (basicOpen 𝒜 f).ι (twistMulPresheaf 𝒜 a b)
    (fun V => twistMulPresheaf_app_bijective_of_le_basicOpen 𝒜 f hf a n ha b
      ((basicOpen 𝒜 f).ι ''ᵁ V) (Scheme.Opens.ι_image_le _ _))

/-- `twistMul` is the transpose of `twistMulPresheaf` along the sheafification adjunction: `L(φ) ≫ ε`. -/
theorem twistMul_eq_sheafify_map_comp_counit (a b : ℤ) :
    twistMul 𝒜 a b =
      (Scheme.Modules.sheafifyZ (Proj 𝒜)).map (twistMulPresheaf 𝒜 a b) ≫
        (Scheme.Modules.adjZ (Proj 𝒜)).counit.app (twist 𝒜 (a + b)) :=
  (Scheme.Modules.adjZ (Proj 𝒜)).homEquiv_counit _ _ _

/-- The multiplication `O(a) ⊗ O(b) → O(a+b)` restricted along `D₊(f) ↪ Proj` is an isomorphism. -/
theorem isIso_restrictFunctor_map_twistMul (f : A) {d : ℕ} (hf : f ∈ 𝒜 d)
    (a : ℤ) (n : ℤ) (ha : a = n * d) (b : ℤ) :
    IsIso ((Scheme.Modules.restrictFunctor (basicOpen 𝒜 f).ι).map (twistMul 𝒜 a b)) := by
  rw [twistMul_eq_sheafify_map_comp_counit]
  exact Scheme.Modules.isIso_restrictFunctor_map_sheafify_map_comp_counit (basicOpen 𝒜 f).ι
    (twistMulPresheaf 𝒜 a b) (isIso_restrictPre_map_twistMulPresheaf 𝒜 f hf a n ha b)

end AlgebraicGeometry.Proj

set_option linter.unusedVariables false in
/-- **Stacks 01MS**: for `f ∈ 𝒜 d`, `O(nd)|_{D₊(f)} ≅ O_{D₊(f)}` (generated by `f^n`), and the multiplication
`O(nd) ⊗ O(m) → O(nd + m)` is an isomorphism on `D₊(f)`. -/
theorem AlgebraicGeometry.Proj.twist_mul_isIso_on_basicOpen {σ A : Type u} [CommRing A] [SetLike σ A]
    [AddSubgroupClass σ A] (𝒜 : ℕ → σ) [GradedRing 𝒜] (f : A) {d : ℕ} (hf : f ∈ 𝒜 d) (hd : 0 < d)
    (n m : ℤ) :
    Nonempty ((AlgebraicGeometry.Proj.twist 𝒜 (n * d)).restrict (AlgebraicGeometry.Proj.basicOpen 𝒜 f).ι ≅
      SheafOfModules.unit _) ∧
    CategoryTheory.IsIso ((AlgebraicGeometry.Scheme.Modules.restrictFunctor (AlgebraicGeometry.Proj.basicOpen 𝒜 f).ι).map
      (AlgebraicGeometry.Proj.twistMul 𝒜 (n * d) m)) := by
  refine ⟨?_, AlgebraicGeometry.Proj.isIso_restrictFunctor_map_twistMul 𝒜 f hf (n * d) n rfl m⟩
  obtain ⟨e, he⟩ := AlgebraicGeometry.Proj.exists_isFrame_twist_basicOpen 𝒜 f hf (n * d) n rfl
  exact ⟨he.restrictIso⟩

-- `Proj.twistMul 𝒜 a b : O(a) ⊗ O(b) ⟶ O(a + b)` (the multiplication map of the absolute Proj, Stacks 01MO) is defined in `ProjTwistingSheaf`.

end
