import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.LineBundleNonvanishingLocus
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.ProjTwistingSheaf
import MiyaokaMori.AlgebraicGeometry.Modules.SectionIsZeroAt
import MiyaokaMori.AlgebraicGeometry.Proj.Twist.WeightedProjCoordinateFormula

/-! # Stacks 01MW(5): the non-vanishing locus of a homogeneous section of `O(d)`

Stacks 01MW(5): on the Proj of a graded ring `A`, a homogeneous element `f ∈ A_1` gives a global section `x_f` of `O(1)`
whose non-vanishing locus is exactly the basic open `D₊(f)` (which is affine); hence, when `A` is generated by `A_1`,
`O(1)` is ample in the sense of the definition (with `m = 1`).

Sources: Stacks 01MW(5), 01MN (sections of `O(1)` on Proj).

**The hypothesis that the `D₊(h)`, `h ∈ 𝒜 d`, cover `Proj 𝒜` is necessary.** Without it the equivalence
"`x_f` does not vanish at `x` ⟺ `x ∈ D₊(f)`" fails, for any `d > 0`. Counterexample: the weighted projective line
`A = k[u, v]` with `deg u = 1`, `deg v = 2`, `d = 1`, `f = u`, `x = (u)` (a homogeneous prime ideal, relevant since
`v ∉ x`). On `D₊(v) = Spec k[u²/v] ≅ 𝔸¹` the sections of `O(1)` are `c/v^k` (`deg c = 1 + 2k`), and every homogeneous
element of odd degree of `k[u,v]` is divisible by `u`, so `O(1)|_{D₊(v)}` is freely generated by `u/1` (`u/1` is a
frame); hence `x_u = u/1` does not vanish at `x ∈ D₊(v)` (`IsFrame.germ_notMem_maximalIdeal_smul`), although `u ∈ 𝔭_x`,
i.e. `x ∉ D₊(u)`. Stacks 01MW itself carries the hypothesis "`A` is generated by `A_1`". The hypothesis `hd : 0 < d` is
not needed for either direction.

Statements and proofs:

* `not_isZeroAt_twistSection_of_mem_basicOpen` (unconditional: `x ∈ D₊(f) ⟹ x_f` does not vanish at `x`):
  `f/1` is a frame of `O(d)` on `D₊(f)` (`isFrame_homogeneousSection`), the germ of a frame does not lie in
  `𝔪_x·O(d)_x` (`IsFrame.germ_notMem_maximalIdeal_smul`), and `x_f|_{D₊(f)}` is this frame
  (`homogeneousSection_restrict`, `rfl`).
* `isZeroAt_twistSection_of_notMem_basicOpen` (`x ∉ D₊(f)` and some `h ∈ 𝒜 d` with `x ∈ D₊(h)` ⟹ `x_f` vanishes at
  `x`): on `D₊(h)`, `h/1` is a frame of `O(d)`, `x_f|_{D₊(h)} = c • (h/1)` with coordinate `c = f/h`
  (`coord_homogeneousSection` = `divideSection`). The value of `c` at `x`, via `Proj.stalkIso'`, is
  `mk f ⟨h, _⟩ ∈ A_{(𝔭)}`, which is not a unit since `f ∈ 𝔭` (`IsLocalization.AtPrime.isUnit_mk'_iff`), i.e.
  `c_x ∈ 𝔪_x`; hence `(x_f)_x = c_x • (h/1)_x ∈ 𝔪_x • O(d)_x`.
* `not_isZeroAt_twistSection_iff_of_exists_mem_basicOpen` (pointwise hypothesis `∃ h ∈ 𝒜 d, x ∈ D₊(h)`),
  `not_isZeroAt_twistSection_iff_of_iSup_basicOpen_eq_top` (global hypothesis `⨆ h : 𝒜 d, D₊(h) = ⊤`) and
  `not_isZeroAt_twistSection_iff_of_iSup_eq_top` (the cover given by a family `g i ∈ 𝒜 d`; when `𝒜` is generated by
  `𝒜 1` over `𝒜 0` and `d = 1` this is Mathlib's `Proj.iSup_basicOpen_eq_top'`): both directions combined.
* `not_isZeroAt_twistSection_iff_of_adjoin_eq_top`: the original hypothesis of Stacks 01MW, "`A` is generated over
  `𝒜 0` by a family of homogeneous elements of degree `d`" (`Algebra.adjoin (𝒜 0) (Set.range g) = ⊤`); the cover is
  given by Mathlib's `Proj.iSup_basicOpen_eq_top'`.
* `projectiveGrading_iSup_basicOpen_X`, `not_isZeroAt_twistSection_X_iff`: the instance for the coordinates `x_i` on
  `P^N`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000
-- As in `Stacks01ms` / `WeightedProjCoordinateFormula`: definitional-equality checks on homogeneous localizations.
set_option backward.isDefEq.respectTransparency false

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

-- The graded-ring instance of `P^N` (Mathlib's `MvPolynomial.gradedAlgebra` is a `def`; it is enabled only inside this file).
attribute [local instance] MvPolynomial.gradedAlgebra

/-- The global section of `O(d)` given by `f ∈ A_d` (the map `S_d → Γ(Proj S, O(d))` of Stacks 01MN):
    `ProjTwisting.homogeneousSection` (`x ↦ f/1 ∈ A_x`, locally the homogeneous fraction `f/1` of degree `d`). -/
noncomputable def AlgebraicGeometry.Proj.twistSection {σ A : Type u} [CommRing A] [SetLike σ A]
    [AddSubgroupClass σ A] (𝒜 : ℕ → σ) [GradedRing 𝒜] {d : ℕ} (f : A) (hf : f ∈ 𝒜 d) :
    ((AlgebraicGeometry.Proj.twist 𝒜 (d : ℤ)).val.obj (Opposite.op ⊤) : Type u) :=
  MiyaokaMori.WeightedJets.ProjTwisting.homogeneousSection 𝒜 d f hf ⊤

namespace AlgebraicGeometry.Proj

open MiyaokaMori.WeightedJets.ProjTwisting AlgebraicGeometry.Scheme.Modules

variable {σ A : Type u} [CommRing A] [SetLike σ A] [AddSubgroupClass σ A] (𝒜 : ℕ → σ) [GradedRing 𝒜]

/-- The restriction of `x_f` to any open `U` is `f/1` on `U` (`homogeneousSection_restrict`). -/
theorem res_twistSection {d : ℕ} (f : A) (hf : f ∈ 𝒜 d) (U : (Proj 𝒜).Opens) :
    (twist 𝒜 (d : ℤ)).res le_top (twistSection 𝒜 f hf) = homogeneousSection 𝒜 d f hf U := rfl

/-- The germ of `x_f` at `x` equals the germ of `x_f|_U` at `x` (`germ_res_apply`). -/
theorem germ_twistSection {d : ℕ} (f : A) (hf : f ∈ 𝒜 d) {U : (Proj 𝒜).Opens} {x : Proj 𝒜}
    (hx : x ∈ U) :
    (twist 𝒜 (d : ℤ)).presheaf.germ ⊤ x trivial (twistSection 𝒜 f hf) =
      (twist 𝒜 (d : ℤ)).presheaf.germ U x hx (homogeneousSection 𝒜 d f hf U) := by
  rw [← res_twistSection 𝒜 f hf U]
  exact (TopCat.Presheaf.germ_res_apply _ _ _ _ _).symm

/-- **`x ∈ D₊(f) ⟹ x_f` does not vanish at `x`** (unconditional): `f/1` is a frame of `O(d)` on `D₊(f)`
(`isFrame_homogeneousSection`), and the germ of a frame does not lie in `𝔪_x • O(d)_x`
(`IsFrame.germ_notMem_maximalIdeal_smul`). -/
theorem not_isZeroAt_twistSection_of_mem_basicOpen {d : ℕ} (f : A) (hf : f ∈ 𝒜 d) (x : Proj 𝒜)
    (hx : x ∈ basicOpen 𝒜 f) : ¬ IsZeroAt (twistSection 𝒜 f hf) x := by
  intro hz
  have hU : ∀ y : (basicOpen 𝒜 f : (Proj 𝒜).Opens), f ∉ y.1.asHomogeneousIdeal := fun y => y.2
  have hfr := isFrame_homogeneousSection 𝒜 d f hf (basicOpen 𝒜 f) hU
  refine hfr.germ_notMem_maximalIdeal_smul hx ?_
  have hz' : (twist 𝒜 (d : ℤ)).presheaf.germ ⊤ x trivial (twistSection 𝒜 f hf) ∈
      (IsLocalRing.maximalIdeal ((Proj 𝒜).presheaf.stalk x)) •
        (⊤ : Submodule ((Proj 𝒜).presheaf.stalk x) ((twist 𝒜 (d : ℤ)).stalk x)) := hz
  rw [germ_twistSection 𝒜 f hf hx] at hz'
  exact hz'

/-- **If `x ∉ D₊(f)` and some `h ∈ 𝒜 d` does not vanish at `x`, then `x_f` vanishes at `x`.**
On `D₊(h)`, `h/1` is a frame of `O(d)` and `x_f|_{D₊(h)} = (f/h) • (h/1)`; the value of `f/h` at `x` is
`mk f ⟨h, _⟩ ∈ A_{(𝔭_x)}`, which is not a unit since `f ∈ 𝔭_x`, so it lies in `𝔪_x`; hence `(x_f)_x ∈ 𝔪_x • O(d)_x`.
(Without such an `h` the conclusion can fail: see the weighted projective line in the module docstring.) -/
theorem isZeroAt_twistSection_of_notMem_basicOpen {d : ℕ} (f : A) (hf : f ∈ 𝒜 d) (x : Proj 𝒜)
    (hx : x ∉ basicOpen 𝒜 f) (h : A) (hh : h ∈ 𝒜 d) (hxh : x ∈ basicOpen 𝒜 h) :
    IsZeroAt (twistSection 𝒜 f hf) x := by
  set U : (Proj 𝒜).Opens := basicOpen 𝒜 h with hUdef
  have hU : ∀ y : U, h ∉ y.1.asHomogeneousIdeal := fun y => y.2
  have hfr := isFrame_homogeneousSection 𝒜 d h hh U hU
  set s := homogeneousSection 𝒜 d f hf U with hsdef
  set c : Γ(Proj 𝒜, U) := hfr.coord le_rfl s with hcdef
  have hs : s = c • homogeneousSection 𝒜 d h hh U := by
    have := hfr.coord_smul_frame le_rfl s
    rw [res_self] at this
    exact this.symm
  have hc : c = divideSection 𝒜 d h hh hU s := coord_homogeneousSection 𝒜 d h hh U hU le_rfl s
  -- the germ of `c` at `x` lies in the maximal ideal
  have hcx : (Proj 𝒜).presheaf.germ U x hxh c ∈ IsLocalRing.maximalIdeal ((Proj 𝒜).presheaf.stalk x) := by
    rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff]
    intro hu
    have key : (Proj.stalkIso' 𝒜 x) ((Proj 𝒜).presheaf.germ U x hxh c) = c.1 ⟨x, hxh⟩ :=
      Proj.stalkIso'_germ 𝒜 U x hxh c
    have hu' : IsUnit (c.1 ⟨x, hxh⟩) := by
      convert hu.map (Proj.stalkIso' 𝒜 x) using 1
      exact key.symm
    rw [← HomogeneousLocalization.isUnit_iff_isUnit_val, hc, divideSection_val] at hu'
    change IsUnit ((Localization.mk f 1 : Fiber 𝒜 x) * Localization.mk 1 ⟨h, hU ⟨x, hxh⟩⟩) at hu'
    rw [Localization.mk_mul, one_mul, mul_one, Localization.mk_eq_mk',
      IsLocalization.AtPrime.isUnit_mk'_iff] at hu'
    exact hx hu'
  show (twist 𝒜 (d : ℤ)).presheaf.germ ⊤ x trivial (twistSection 𝒜 f hf) ∈ _
  rw [germ_twistSection 𝒜 f hf hxh, ← hsdef, hs, germ_smul']
  exact Submodule.smul_mem_smul hcx Submodule.mem_top

/-- **Stacks 01MW(5), pointwise form**: if some `h ∈ 𝒜 d` does not vanish at `x`, then
`x_f` does not vanish at `x` ⟺ `x ∈ D₊(f)`. -/
theorem not_isZeroAt_twistSection_iff_of_exists_mem_basicOpen {d : ℕ} (f : A) (hf : f ∈ 𝒜 d)
    (x : Proj 𝒜) (hx : ∃ h ∈ 𝒜 d, x ∈ basicOpen 𝒜 h) :
    ¬ IsZeroAt (twistSection 𝒜 f hf) x ↔ x ∈ basicOpen 𝒜 f := by
  refine ⟨fun hnz => ?_, not_isZeroAt_twistSection_of_mem_basicOpen 𝒜 f hf x⟩
  by_contra hx'
  obtain ⟨h, hh, hxh⟩ := hx
  exact hnz (isZeroAt_twistSection_of_notMem_basicOpen 𝒜 f hf x hx' h hh hxh)

/-- **Stacks 01MW(5)**: if the basic opens of the homogeneous elements of degree `d` cover `Proj 𝒜` (when `𝒜` is
generated by `𝒜 1` over `𝒜 0` and `d = 1` this is Mathlib's `Proj.iSup_basicOpen_eq_top'`), then the non-vanishing
locus of `x_f` (`f ∈ 𝒜 d`) is exactly `D₊(f)`. -/
theorem not_isZeroAt_twistSection_iff_of_iSup_basicOpen_eq_top {d : ℕ} (f : A) (hf : f ∈ 𝒜 d)
    (hcover : ⨆ h : 𝒜 d, basicOpen 𝒜 (h : A) = ⊤) (x : Proj 𝒜) :
    ¬ IsZeroAt (twistSection 𝒜 f hf) x ↔ x ∈ basicOpen 𝒜 f := by
  refine not_isZeroAt_twistSection_iff_of_exists_mem_basicOpen 𝒜 f hf x ?_
  obtain ⟨h, hxh⟩ := Opens.mem_iSup.mp (hcover.ge (Set.mem_univ x))
  exact ⟨h, h.2, hxh⟩

/-- As above, with the cover given by a family of homogeneous elements `g i` of degree `d` (the output shape of
`ProjectiveSpaceOver.iSup_chart`, `projectiveSpace_iSup_basicOpen_X` and Mathlib's `Proj.iSup_basicOpen_eq_top'`). -/
theorem not_isZeroAt_twistSection_iff_of_iSup_eq_top {ι : Type*} (g : ι → A) {d : ℕ}
    (hg : ∀ i, g i ∈ 𝒜 d) (hcover : ⨆ i, basicOpen 𝒜 (g i) = ⊤) (f : A) (hf : f ∈ 𝒜 d)
    (x : Proj 𝒜) :
    ¬ IsZeroAt (twistSection 𝒜 f hf) x ↔ x ∈ basicOpen 𝒜 f := by
  refine not_isZeroAt_twistSection_iff_of_exists_mem_basicOpen 𝒜 f hf x ?_
  obtain ⟨i, hxi⟩ := Opens.mem_iSup.mp (hcover.ge (Set.mem_univ x))
  exact ⟨g i, hg i, hxi⟩

/-- **Stacks 01MW(5) with its original hypothesis**: if a family of homogeneous elements `g i` of degree `d` generates
`A` over `𝒜 0` (`Algebra.adjoin (𝒜 0) (Set.range g) = ⊤`; Stacks' "`A` is generated by `A_1`" is the case `d = 1`),
then for every `f ∈ 𝒜 d` the non-vanishing locus of `x_f` is exactly `D₊(f)`. The cover `⨆ i, D₊(g i) = ⊤` is given by
Mathlib's `Proj.iSup_basicOpen_eq_top'`. -/
theorem not_isZeroAt_twistSection_iff_of_adjoin_eq_top {ι : Type*} (g : ι → A) {d : ℕ}
    (hg : ∀ i, g i ∈ 𝒜 d) (hgen : Algebra.adjoin (𝒜 0) (Set.range g) = ⊤) (f : A) (hf : f ∈ 𝒜 d)
    (x : Proj 𝒜) :
    ¬ IsZeroAt (twistSection 𝒜 f hf) x ↔ x ∈ basicOpen 𝒜 f :=
  not_isZeroAt_twistSection_iff_of_iSup_eq_top 𝒜 g hg
    (iSup_basicOpen_eq_top' 𝒜 g (fun i => ⟨d, hg i⟩) hgen) f hf x

/-- The standard opens `D₊(x_i)` cover `P^N = Proj (projectiveGrading k N)`: the `x_i` are homogeneous and generate the
polynomial ring over `k = 𝒜 0` (Mathlib's `Proj.iSup_basicOpen_eq_top'`). This is the same statement as
`SerreTwistIsLineBundle.projectiveSpace_iSup_basicOpen_X`; it is repeated here so that users of 01MW need not import
that module. -/
theorem projectiveGrading_iSup_basicOpen_X (k : Type u) [Field k] (N : ℕ) :
    ⨆ i : Fin (N + 1), basicOpen (AlgebraicGeometry.Proj.projectiveGrading k N) (MvPolynomial.X i) = ⊤ := by
  apply iSup_basicOpen_eq_top'
  · exact fun i => ⟨1, MvPolynomial.isHomogeneous_X k i⟩
  · apply top_unique
    intro p hp
    clear hp
    induction p using MvPolynomial.induction_on with
    | C r =>
      exact (Algebra.adjoin (AlgebraicGeometry.Proj.projectiveGrading k N 0)
        (Set.range (MvPolynomial.X : Fin (N + 1) → MvPolynomial (Fin (N + 1)) k))).algebraMap_mem
          ⟨MvPolynomial.C r, MvPolynomial.isHomogeneous_C (Fin (N + 1)) r⟩
    | add p q hp hq => exact Subalgebra.add_mem _ hp hq
    | mul_X p i hp =>
      exact Subalgebra.mul_mem _ hp (Algebra.subset_adjoin (Set.mem_range_self i))

/-- The coordinates `x_i ∈ Γ(P^N, O(1))` on `P^N`: the non-vanishing locus is exactly `D₊(x_i)` (the instance of
Stacks 01MW(5) on `P^N`, in the shape needed by `Stacks01ne` / `MmsetupExists` / `ProjectiveSpaceTwistAmple`). -/
theorem not_isZeroAt_twistSection_X_iff (k : Type u) [Field k] (N : ℕ) (i : Fin (N + 1))
    (hi : MvPolynomial.X i ∈ AlgebraicGeometry.Proj.projectiveGrading k N 1) (x : Proj (AlgebraicGeometry.Proj.projectiveGrading k N)) :
    ¬ IsZeroAt (twistSection (AlgebraicGeometry.Proj.projectiveGrading k N) (MvPolynomial.X i) hi) x ↔
      x ∈ basicOpen (AlgebraicGeometry.Proj.projectiveGrading k N) (MvPolynomial.X i) :=
  not_isZeroAt_twistSection_iff_of_iSup_eq_top (AlgebraicGeometry.Proj.projectiveGrading k N) MvPolynomial.X
    (fun j => (MvPolynomial.mem_homogeneousSubmodule 1 _).2 (MvPolynomial.isHomogeneous_X k j))
    (projectiveGrading_iSup_basicOpen_X k N) (MvPolynomial.X i) hi x

end AlgebraicGeometry.Proj

end
