import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.Basic.OverSiteSections

/-! # Local presentation data of a finitely presented sheaf of modules

**Concrete** presentation data of a finitely presented sheaf of modules near a point (the definition of
Stacks 01B8 / 01BM unfolded on opens): if `F` is of finite presentation, then `x` has an open
neighbourhood `U` with `s^1, …, s^n ∈ F(U)` (generators) and `r^1, …, r^m ∈ Γ(X,U)^n` (relations) such
that `⊕_{j} O_U → ⊕_{i} O_U → F|_U → 0` is exact, i.e.
1. `s` locally generates `F|_U` (`IsLocalGenerators`: every section over any `W ≤ U` is, near every
   point of `W`, a linear combination of the `s_i`);
2. `Σ_i r^j_i s^i = 0`;
3. for every `W ≤ U`, the coefficients `c` with `Σ_i c_i s^i|_W = 0` are, near every point of `W`, linear
   combinations of the `r^j|`.

Source: Mathlib `SheafOfModules.IsFinitePresentation` (`Algebra/Category/ModuleCat/Sheaf/Quasicoherent.lean`)
unfolded; Stacks 01BM (`modules-definition-finite-presentation`). This module does not involve the
internal Hom and can be reused wherever "finite presentation ⇒ local generators and relations" is needed.

The proof unfolds Mathlib's definition: `IsFinitePresentation` gives a family of opens covering `⊤` and
finite presentations `p` of `F.over (σ.X i)` (`SheafOfModules.Presentation`, living on the site
`Over U`). The general site-level tools (epimorphisms are locally surjective, sections of a finite free
sheaf are combinations of the standard sections, sections of kernels) are in `OverSiteSections`; this file
only reads off `s_i`, `ρ_j`, `r^j_i` from `p` (`presGen` / `presRelSec` / `presRel`), proves the three
properties (`presGen_generates` / `presRel_relation` / `presRel_generate`) and reindexes to `Fin n`,
`Fin m` (`isLocalPresentation_reindex`). Key fact: the sections of `F.over U` at `ov hW : Over U`
(`hW : W ≤ U`) are **by definition** `Γ(F, W)` and the restriction maps are `F.presheaf.map`, so
identities on the site can be used directly as identities on `X`. For finite `I` every section of
`(free I)(U)` is a **global** combination of the standard sections (`free_section_eq_sum`), so the relation
vectors `r^j` are defined directly on `U` without shrinking.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

namespace AlgebraicGeometry.Scheme.Modules

variable {X : AlgebraicGeometry.Scheme.{u}}

/-- `s : Fin n → Γ(F, U)` **locally generates** `F|_U`: for every open `W ≤ U`, section `t ∈ F(W)` and point
`y ∈ W` there are an open neighbourhood `W' ≤ W` of `y` and coefficients `c : Fin n → Γ(X, W')` with
`t|_{W'} = Σ_i c_i • s_i|_{W'}` (i.e. `⊕_{i} O_U → F|_U`, `e_i ↦ s_i`, is locally surjective, equivalently an
epimorphism of sheaves). -/
def IsLocalGenerators (F : X.Modules) (U : X.Opens) {n : ℕ} (s : Fin n → Γ(F, U)) : Prop :=
  ∀ (W : X.Opens) (hW : W ≤ U) (t : Γ(F, W)) (y : X), y ∈ W →
    ∃ (W' : X.Opens) (hW' : W' ≤ W), y ∈ W' ∧ ∃ c : Fin n → Γ(X, W'),
      F.presheaf.map (homOfLE hW').op t =
        ∑ i, c i • F.presheaf.map (homOfLE (hW'.trans hW)).op (s i)

/-- `(s, r)` is a **local presentation** of `F|_U`: `s` locally generates, the `r^j` are relations, and the
relations are locally generated by the `r^j` (i.e. `⊕_j O_U → ⊕_i O_U → F|_U → 0` is an exact sequence of
sheaves). -/
structure IsLocalPresentation (F : X.Modules) (U : X.Opens) {n m : ℕ}
    (s : Fin n → Γ(F, U)) (r : Fin m → Fin n → Γ(X, U)) : Prop where
  generates : AlgebraicGeometry.Scheme.Modules.IsLocalGenerators F U s
  relation : ∀ j, ∑ i, r j i • s i = 0
  relations_generate : ∀ (W : X.Opens) (hW : W ≤ U) (c : Fin n → Γ(X, W)),
    ∑ i, c i • F.presheaf.map (homOfLE hW).op (s i) = 0 → ∀ y ∈ W,
      ∃ (W' : X.Opens) (hW' : W' ≤ W), y ∈ W' ∧ ∃ d : Fin m → Γ(X, W'),
        ∀ i, X.presheaf.map (homOfLE hW').op (c i) =
          ∑ j, d j • X.presheaf.map (homOfLE (hW'.trans hW)).op (r j i)


/-! ### Data read off a presentation of `F.over U`

`p : (F.over U).Presentation` (Mathlib) consists of `p.generators : (F.over U).GeneratingSections`
(`π = p.generators.π : free I ⟶ F.over U`, an epimorphism) and `p.relations : (kernel π).GeneratingSections`.
We read off `s_i := (p.generators.s i)(U) ∈ F(U)`, `ρ_j := kernel.ι ((p.relations.s j)(U)) ∈ (free I)(U)` and
its coordinates `r^j_i ∈ Γ(X, U)`, and prove the three clauses of `IsLocalPresentation` for them
(with the finite index types `I`, `I'` of `p`; the reindexing to `Fin n`, `Fin m` is done afterwards). -/

/-- Shortcut instances for the site `(Opens X).over U` (they are found by Mathlib's instance search from
`Sites/Over.lean`, but each search costs ~50–90 ms and is repeated hundreds of times in this file). Local to
this file; nothing downstream sees them. -/
local instance instHasSheafifyOver (U : X.Opens) :
    HasSheafify ((Opens.grothendieckTopology X).over U) AddCommGrpCat.{u} := inferInstance

local instance instHasWeakSheafifyOver (U : X.Opens) :
    HasWeakSheafify ((Opens.grothendieckTopology X).over U) AddCommGrpCat.{u} := inferInstance

local instance instWEqualsLocallyBijectiveOver (U : X.Opens) :
    ((Opens.grothendieckTopology X).over U).WEqualsLocallyBijective AddCommGrpCat.{u} := inferInstance

section presentation

variable (F : X.Modules) {U : X.Opens} (p : (F.over U).Presentation)

/-- The generators `s_i ∈ F(U)` of a presentation of `F.over U`. -/
def presGen (i : p.generators.I) : Γ(F, U) :=
  PresheafOfModules.sections.eval (p.generators.s i) (op (ov (le_refl U)))

/-- The relation `ρ_j ∈ (free I)(U)`: the image under `kernel.ι` of the `j`-th generating section of
`kernel π`. -/
def presRelSec (j : p.relations.I) :
    (SheafOfModules.free (R := X.ringCatSheaf.over U) p.generators.I).val.obj (op (ov (le_refl U))) :=
  (kernel.ι p.generators.π).val.app (op (ov (le_refl U)))
    (PresheafOfModules.sections.eval (p.relations.s j) (op (ov (le_refl U))))

/-- The coefficients `r^j_i ∈ Γ(X, U)` of the relation `ρ_j = Σ_i r^j_i e_i`. -/
def presRel (j : p.relations.I) (i : p.generators.I) : Γ(X, U) :=
  fromOv (le_refl U) (SheafOfModules.ofUSec _
    ((SheafOfModules.freeCoord (R := X.ringCatSheaf.over U) p.generators.I i).val.app
      (op (ov (le_refl U))) (presRelSec F p j)))

variable [Fintype p.generators.I]

/-- `π` on a combination of standard sections over `U` itself, in terms of `presGen`. -/
lemma presGen_π_app_sum (c : p.generators.I → (X.ringCatSheaf.over U).obj.obj (op (ov (le_refl U)))) :
    p.generators.π.val.app (op (ov (le_refl U)))
        (∑ i, c i • SheafOfModules.freeE (R := X.ringCatSheaf.over U) p.generators.I i (ov (le_refl U))) =
      ∑ i, fromOv (le_refl U) (c i) • presGen F p i := by
  rw [over_π_app_sum]
  exact Finset.sum_congr rfl fun i _ => congrArg _ (presheaf_map_le_refl F U _)

lemma presRelSec_eq_sum (j : p.relations.I) :
    presRelSec F p j = ∑ i, toOv (le_refl U) (presRel F p j i) •
      SheafOfModules.freeE (R := X.ringCatSheaf.over U) p.generators.I i (ov (le_refl U)) :=
  SheafOfModules.free_section_eq_sum _ _ (presRelSec F p j)

/-- **The generators generate locally**: `Epi π` is locally surjective on sections
(`over_epi_locally_surjective`); a preimage `u ∈ (free I)(W')` of `t|_{W'}` is `Σ_i c_i e_i`
(`free_section_eq_sum`), and `π u = Σ_i c_i s_i|_{W'}` (`over_π_app_sum`). -/
theorem presGen_generates (W : X.Opens) (hW : W ≤ U) (t : Γ(F, W)) (y : X) (hy : y ∈ W) :
    ∃ (W' : X.Opens) (hW' : W' ≤ W), y ∈ W' ∧ ∃ c : p.generators.I → Γ(X, W'),
      F.presheaf.map (homOfLE hW').op t =
        ∑ i, c i • F.presheaf.map (homOfLE (hW'.trans hW)).op (presGen F p i) := by
  obtain ⟨W', hW', hyW', u, hu⟩ := over_epi_locally_surjective p.generators.π hW t y hy
  refine ⟨W', hW', hyW', fun i => fromOv _ (SheafOfModules.ofUSec _
    ((SheafOfModules.freeCoord (R := X.ringCatSheaf.over U) p.generators.I i).val.app
      (op (ov (hW'.trans hW))) u)), ?_⟩
  have h1 := SheafOfModules.free_section_eq_sum p.generators.I (ov (hW'.trans hW)) u
  rw [h1, over_π_app_sum] at hu
  exact hu.symm

/-- **The relations hold**: `Σ_i r^j_i s_i = π(ρ_j) = π(kernel.ι (…)) = 0`. -/
theorem presRel_relation (j : p.relations.I) : ∑ i, presRel F p j i • presGen F p i = 0 := by
  have h0 := SheafOfModules.kernel_ι_val_app_apply_eq_zero p.generators.π (ov (le_refl U))
    (PresheafOfModules.sections.eval (p.relations.s j) (op (ov (le_refl U))))
  rw [show (kernel.ι p.generators.π).val.app (op (ov (le_refl U)))
      (PresheafOfModules.sections.eval (p.relations.s j) (op (ov (le_refl U)))) = presRelSec F p j from rfl,
    presRelSec_eq_sum, presGen_π_app_sum] at h0
  exact h0

variable [Fintype p.relations.I]

/-- `kernel.ι` applied to `p.relations.π v` for `v ∈ (free I')(W')`, expanded in the standard basis:
`v = Σ_j d_j e'_j`, `p.relations.π e'_j = (p.relations.s j)|_{W'}`, and `kernel.ι` of that is
`ρ_j|_{W'} = Σ_i r^j_i|_{W'} e_i`. -/
lemma kernel_ι_relπ_app {W' : X.Opens} (hW' : W' ≤ U)
    (v : (SheafOfModules.free (R := X.ringCatSheaf.over U) p.relations.I).val.obj (op (ov hW'))) :
    (kernel.ι p.generators.π).val.app (op (ov hW')) (p.relations.π.val.app (op (ov hW')) v) =
      ∑ j, SheafOfModules.ofUSec _
        ((SheafOfModules.freeCoord (R := X.ringCatSheaf.over U) p.relations.I j).val.app (op (ov hW')) v) •
        ∑ i, toOv hW' (X.presheaf.map (homOfLE hW').op (presRel F p j i)) •
          SheafOfModules.freeE (R := X.ringCatSheaf.over U) p.generators.I i (ov hW') := by
  have h1 := SheafOfModules.free_section_eq_sum p.relations.I (ov hW') v
  refine (congrArg (fun z => (kernel.ι p.generators.π).val.app (op (ov hW'))
    (p.relations.π.val.app (op (ov hW')) z)) h1).trans ?_
  simp only []
  rw [SheafOfModules.GeneratingSections.π_app_sum, map_sum]
  refine Finset.sum_congr rfl fun j _ => ?_
  rw [_root_.map_smul ((kernel.ι p.generators.π).val.app (op (ov hW'))).hom]
  refine congrArg _ ?_
  rw [← SheafOfModules.sections_eval_map (p.relations.s j) (ovHomTop hW').op,
    PresheafOfModules.naturality_apply (kernel.ι p.generators.π).val (ovHomTop hW').op,
    show (kernel.ι p.generators.π).val.app (op (ov (le_refl U)))
      (PresheafOfModules.sections.eval (p.relations.s j) (op (ov (le_refl U)))) = presRelSec F p j from rfl,
    presRelSec_eq_sum, SheafOfModules.free_map_sum]
  rfl

/-- **The relations generate all relations locally**: if `Σ_i c_i s_i|_W = 0` then `u := Σ_i c_i e_i` lies
in `(kernel π)(W)` (`exists_kernel_ι_val_app_eq`); `Epi p.relations.π` gives `y ∈ W' ≤ W` and
`v ∈ (free I')(W')` with `p.relations.π v = k|_{W'}`; applying `kernel.ι` and comparing the `i`-th
coordinates (`freeCoord_app_sum`, `freeCoord_app_sum_smul_sum`) gives `c_i|_{W'} = Σ_j d_j r^j_i|_{W'}`. -/
theorem presRel_generate (W : X.Opens) (hW : W ≤ U) (c : p.generators.I → Γ(X, W))
    (hc : ∑ i, c i • F.presheaf.map (homOfLE hW).op (presGen F p i) = 0) (y : X) (hy : y ∈ W) :
    ∃ (W' : X.Opens) (hW' : W' ≤ W), y ∈ W' ∧ ∃ d : p.relations.I → Γ(X, W'),
      ∀ i, X.presheaf.map (homOfLE hW').op (c i) =
        ∑ j, d j • X.presheaf.map (homOfLE (hW'.trans hW)).op (presRel F p j i) := by
  have h0 : p.generators.π.val.app (op (ov hW))
      (∑ i, toOv hW (c i) • SheafOfModules.freeE (R := X.ringCatSheaf.over U) p.generators.I i (ov hW)) = 0 := by
    rw [over_π_app_sum]
    exact hc
  obtain ⟨k, hk⟩ := SheafOfModules.exists_kernel_ι_val_app_eq p.generators.π (ov hW) _ h0
  obtain ⟨W', hW', hyW', v, hv⟩ := over_epi_locally_surjective p.relations.π hW k y hy
  refine ⟨W', hW', hyW', fun j => fromOv _ (SheafOfModules.ofUSec _
    ((SheafOfModules.freeCoord (R := X.ringCatSheaf.over U) p.relations.I j).val.app
      (op (ov (hW'.trans hW))) v)), fun i => ?_⟩
  have hv' := congrArg (fun z => (kernel.ι p.generators.π).val.app (op (ov (hW'.trans hW))) z) hv
  simp only [] at hv'
  rw [kernel_ι_relπ_app F p (hW'.trans hW) v,
    PresheafOfModules.naturality_apply (kernel.ι p.generators.π).val (ovHom hW hW').op k] at hv'
  change _ = (SheafOfModules.free (R := X.ringCatSheaf.over U) p.generators.I).val.map
    (ovHom hW hW').op ((kernel.ι p.generators.π).val.app (op (ov hW)) k) at hv'
  rw [hk, SheafOfModules.free_map_sum] at hv'
  simp only [over_ring_map_apply] at hv'
  have h1 := SheafOfModules.freeCoord_app_sum_smul_sum (R := X.ringCatSheaf.over U) p.generators.I
    (ov (hW'.trans hW))
    (fun j => SheafOfModules.ofUSec _
      ((SheafOfModules.freeCoord (R := X.ringCatSheaf.over U) p.relations.I j).val.app
        (op (ov (hW'.trans hW))) v))
    (fun j i => toOv (hW'.trans hW) (X.presheaf.map (homOfLE (hW'.trans hW)).op (presRel F p j i))) i
  have h2 := SheafOfModules.freeCoord_app_sum (R := X.ringCatSheaf.over U) p.generators.I
    (ov (hW'.trans hW)) (fun i => toOv (hW'.trans hW) (X.presheaf.map (homOfLE hW').op (c i))) i
  have hcoef := congrArg (fun z => (SheafOfModules.freeCoord (R := X.ringCatSheaf.over U) p.generators.I i).val.app
    (op (ov (hW'.trans hW))) z) hv'
  exact (congrArg (SheafOfModules.ofUSec _) ((h1.symm.trans hcoef).trans h2)).symm

end presentation

/-- Reindexing a local presentation with finite index types `I`, `I'` to `Fin n`, `Fin m`
(`Fintype.equivFin`, `Equiv.sum_comp`). -/
theorem isLocalPresentation_reindex (F : X.Modules) (U : X.Opens) {I I' : Type u} [Fintype I] [Fintype I']
    (s : I → Γ(F, U)) (r : I' → I → Γ(X, U))
    (hgen : ∀ (W : X.Opens) (hW : W ≤ U) (t : Γ(F, W)) (y : X), y ∈ W →
      ∃ (W' : X.Opens) (hW' : W' ≤ W), y ∈ W' ∧ ∃ c : I → Γ(X, W'),
        F.presheaf.map (homOfLE hW').op t = ∑ i, c i • F.presheaf.map (homOfLE (hW'.trans hW)).op (s i))
    (hrel : ∀ j, ∑ i, r j i • s i = 0)
    (hrg : ∀ (W : X.Opens) (hW : W ≤ U) (c : I → Γ(X, W)),
      ∑ i, c i • F.presheaf.map (homOfLE hW).op (s i) = 0 → ∀ y ∈ W,
        ∃ (W' : X.Opens) (hW' : W' ≤ W), y ∈ W' ∧ ∃ d : I' → Γ(X, W'),
          ∀ i, X.presheaf.map (homOfLE hW').op (c i) =
            ∑ j, d j • X.presheaf.map (homOfLE (hW'.trans hW)).op (r j i)) :
    ∃ (n m : ℕ) (s' : Fin n → Γ(F, U)) (r' : Fin m → Fin n → Γ(X, U)),
      AlgebraicGeometry.Scheme.Modules.IsLocalPresentation F U s' r' := by
  let e : Fin (Fintype.card I) ≃ I := (Fintype.equivFin I).symm
  let e' : Fin (Fintype.card I') ≃ I' := (Fintype.equivFin I').symm
  refine ⟨_, _, fun i => s (e i), fun j i => r (e' j) (e i), ?_, ?_, ?_⟩
  · intro W hW t y hy
    obtain ⟨W', hW', hyW', c, hc⟩ := hgen W hW t y hy
    refine ⟨W', hW', hyW', fun i => c (e i), ?_⟩
    rw [hc]
    exact (Equiv.sum_comp e (fun i => c i • F.presheaf.map (homOfLE (hW'.trans hW)).op (s i))).symm
  · intro j
    rw [← hrel (e' j)]
    exact Equiv.sum_comp e (fun i => r (e' j) i • s i)
  · intro W hW c hc y hy
    have hc' : ∑ i, c (e.symm i) • F.presheaf.map (homOfLE hW).op (s i) = 0 := by
      rw [← hc, ← Equiv.sum_comp e (fun i => c (e.symm i) • F.presheaf.map (homOfLE hW).op (s i))]
      simp only [Equiv.symm_apply_apply]
    obtain ⟨W', hW', hyW', d, hd⟩ := hrg W hW (fun i => c (e.symm i)) hc' y hy
    refine ⟨W', hW', hyW', fun j => d (e' j), fun i => ?_⟩
    have h1 := hd (e i)
    simp only [Equiv.symm_apply_apply] at h1
    rw [h1]
    exact (Equiv.sum_comp e' (fun j => d j • X.presheaf.map (homOfLE (hW'.trans hW)).op (r j (e i)))).symm

/-- **Finite presentation ⇒ a concrete finite local presentation near every point.**

Source: the definition of Mathlib's `SheafOfModules.IsFinitePresentation` (`Quasicoherent.lean`); Stacks 01BM.

Proof sketch:
1. `IsFinitePresentation.exists_quasicoherentData F` gives `σ : F.QuasicoherentData` with
   `σ.IsFinitePresentation`. `σ.coversTop : J.CoversTop σ.X` (`J = Opens.grothendieckTopology X`) says that
   the sieve generated by the `σ.X i` covers `⊤`; by definition of `Opens.grothendieckTopology`
   (`S ∈ J U ↔ ∀ y ∈ U, ∃ V (f : V ⟶ U), S f ∧ y ∈ V`), taking `y = x` gives some `i` and `V ≤ σ.X i` with
   `x ∈ V`. Put `U := σ.X i`, so `x ∈ U`.
2. `p := σ.presentation i : (F.over U).Presentation` with `p.IsFinite`: `p.generators.I` and
   `p.relations.I` are finite; choose `Fin n ≃ p.generators.I` and `Fin m ≃ p.relations.I`
   (`Fintype.equivFin`). `F.over U = pushforward (𝟙 _) F` (`SheafOfModules.over`), whose sections at an object
   `W → U` of `Over U` are **by definition** `F(W)`.
3. Generators: `p.generators.s : I → (F.over U).sections`, where `sections = (presheaf ⋙ forget).sections`
   are the restriction-compatible families of sections; its value at `𝟙 U : Over U` gives `s_i ∈ F(U)`, and
   compatibility says that its value at `W → U` is `s_i|_W`.
4. "`s` locally generates": `p.generators.epi : Epi p.generators.π` with `π = freeHomEquiv.symm s`.
   Epimorphisms of sheaves of modules are locally surjective on sections
   (`SheafOfModules.imageSieve_mem_of_epi`, `over_epi_locally_surjective`): for every `W → U`, `t ∈ F(W)`,
   `y ∈ W` there are `W' ≤ W ∋ y` and `u ∈ (free I)(W')` with `π_{W'}(u) = t|_{W'}`. For finite `I`,
   `(free I)(W') = ⊕_{i ∈ I} Γ(X, W')` and `π_{W'}(Σ_i c_i e_i) = Σ_i c_i s_i|_{W'}` (`free_section_eq_sum`,
   `over_π_app_sum`; `e_i = (ιFree i)_{W'}` via `unitHomEquiv`).
5. Relations: `p.relations.s : I' → (kernel π).sections`; kernels are computed openwise
   (`kernel_ι_val_app_*`), so `(kernel π)(U) = {c ∈ Γ(X,U)^n : Σ c_i s_i = 0}`, and the value at `𝟙 U` gives
   `r^j ∈ Γ(X,U)^n` with `Σ_i r^j_i s^i = 0` (`relation`).
6. "The relations are locally generated by the `r^j`": `p.relations.epi : Epi (free I' ⟶ kernel π)`, as in
   step 4: for every `W ≤ U`, `c ∈ (kernel π)(W)` (i.e. `Σ c_i s_i|_W = 0`) and `y ∈ W` there are `W' ∋ y` and
   `d ∈ Γ(X,W')^m` with `c|_{W'} = Σ_j d_j r^j|_{W'}` (compare coordinates with `freeCoord_app_sum`).

Edge cases: `n = 0` (`F|_U = 0`) and `m = 0` (no relations) are allowed; `U` contains `x`, hence is
nonempty. -/
theorem exists_isLocalPresentation (F : X.Modules) [F.IsFinitePresentation] (x : X) :
    ∃ (U : X.Opens) (_ : x ∈ U) (n m : ℕ) (s : Fin n → Γ(F, U)) (r : Fin m → Fin n → Γ(X, U)),
      AlgebraicGeometry.Scheme.Modules.IsLocalPresentation F U s r := by
  obtain ⟨σ, hσ⟩ := SheafOfModules.IsFinitePresentation.exists_quasicoherentData F
  obtain ⟨i₀, hx⟩ := exists_mem_of_coversTop σ.X σ.coversTop x
  obtain ⟨U, hxU, p, hp⟩ : ∃ (U : X.Opens) (_ : x ∈ U) (p : (F.over U).Presentation), p.IsFinite :=
    ⟨σ.X i₀, hx, σ.presentation i₀, hσ.isFinite_presentation i₀⟩
  have : Finite p.generators.I := SheafOfModules.GeneratingSections.IsFiniteType.finite
  have : Finite p.relations.I := SheafOfModules.GeneratingSections.IsFiniteType.finite
  let _ : Fintype p.generators.I := Fintype.ofFinite _
  let _ : Fintype p.relations.I := Fintype.ofFinite _
  obtain ⟨n, m, s', r', h⟩ := isLocalPresentation_reindex F U (presGen F p) (presRel F p)
    (presGen_generates F p) (presRel_relation F p) (presRel_generate F p)
  exact ⟨U, hxU, n, m, s', r', h⟩

end AlgebraicGeometry.Scheme.Modules

end
