import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.QcSectionsBasicOpenLocalization
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.QcApproxGoodOn
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.QcApproxSpanAffine
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.QcApproxSpanSubpresheaf

/-! # Extending a good sub-presheaf across an affine open (Stacks 01PC)

Support module for `QcFiniteTypeApproxFiniteSections`.

Let `F` be quasi-coherent on the quasi-separated scheme `S`, `G ⊆ F` good on the quasi-compact open `U`
(`QcApprox.GoodOn`), and `W` an affine open. Then there are finitely many sections `e i ∈ Γ(F, W)` such
that the sub-presheaf `spanSub F W e` generated by them (good on `W` by `goodOn_spanSub`) **agrees with `G`
on every open `V ≤ U ⊓ W`** (`GoodOn.exists_spanSub_agree`). This is Stacks 01PC ("extend a finite type
quasi-coherent submodule from a quasi-compact open of an affine to the affine"), in the form needed by the
gluing step (`QcFiniteTypeApproxFiniteSections_Glue`).

Proof.
1. (`exists_basicOpen_cover_fg`) `U ⊓ W` is quasi-compact. For `x ∈ U ⊓ W` take an affine `U₁ ≤ U`
   containing `x` with `G(U₁)` finitely generated (`exists_affine_fg`) and a basic open
   `D(f) = D(g)`, `f ∈ Γ(U₁, O)`, `g ∈ Γ(W, O)`, containing `x` (`exists_basicOpen_le_affine_inter`); then
   `D(g) ≤ U` and `G(D(g))` is spanned by finitely many sections (`exists_span_basicOpen`). Finitely many
   such `g` cover `U ⊓ W`.
2. (`exists_global_of_basicOpen_mem`) For a generator `a ∈ G(D(g))`: `a = t|_{D(g)} / g ^ n` with
   `t ∈ Γ(F, W)` (`exists_pow_smul_eq_map_basicOpen`), and `t|_{D(g)} ∈ G`; saturation over the quasi-compact
   `W ⊓ U` (`exists_pow_smul_map_inf_mem`) gives `m` with `h := g ^ m • t` satisfying `h|_{U ⊓ W} ∈ G` and
   `h|_{D(g)} = g ^ (m + n) • a`.
3. Let `e` be the family of all these `h`. On `V ≤ U ⊓ W`: `spanSub(V) ⊆ G(V)` because each `e i` restricts
   into `G` on `U ⊓ W` and membership in `G` is local; `G(V) ⊆ spanSub(V)` because every `x ∈ V` lies in some
   `D(g)`, and on a basic open `D(b)` of `D(g)` inside `V` the module `G(D(b))` is spanned by the restricted
   generators `a|_{D(b)} = g ^ {-(m+n)} • h|_{D(b)}` (`obj_basicOpen_eq_span`), which lie in the span of the
   `e i|_{D(b)}`.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

namespace AlgebraicGeometry.Scheme.Modules.QcApprox

variable {S : AlgebraicGeometry.Scheme.{u}} (F : S.Modules)

/-- If `e i = u ^ N • a` with `u` a unit, then `a` lies in the span of the `e j`. -/
theorem mem_span_of_unit_pow_smul_eq {U : S.Opens} {ι : Type u} (e : ι → Γ(F, U)) (i : ι)
    {u : Γ(S, U)} (hu : IsUnit u) (N : ℕ) (a : Γ(F, U)) (h : e i = u ^ N • a) :
    a ∈ Submodule.span Γ(S, U) (Set.range e) := by
  obtain ⟨w, rfl⟩ := hu
  have hone : ((↑(w⁻¹ ^ N) : Γ(S, U)) * (↑w : Γ(S, U)) ^ N) = 1 := by
    rw [← Units.val_pow_eq_pow_val, ← Units.val_mul, inv_pow, inv_mul_cancel, Units.val_one]
  have ha : a = (↑(w⁻¹ ^ N) : Γ(S, U)) • e i :=
    calc a = (1 : Γ(S, U)) • a := (one_smul _ _).symm
      _ = ((↑(w⁻¹ ^ N) : Γ(S, U)) * (↑w : Γ(S, U)) ^ N) • a := by rw [hone]
      _ = (↑(w⁻¹ ^ N) : Γ(S, U)) • ((↑w : Γ(S, U)) ^ N • a) := mul_smul _ _ _
      _ = _ := by rw [h]
  rw [ha]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

variable {F} [F.IsQuasicoherent]

/-- **Step 1.** Finitely many basic opens `D(g)` of the affine `W`, contained in `U`, covering `U ⊓ W`, on
each of which `G` is spanned by finitely many sections. -/
theorem GoodOn.exists_basicOpen_cover_fg [QuasiSeparatedSpace S] {G : F.val.Submodule} {U : S.Opens}
    (hG : GoodOn F G U) (hU : IsCompact (U : Set S)) {W : S.Opens}
    (hW : AlgebraicGeometry.IsAffineOpen W) :
    ∃ T : Finset Γ(S, W), (∀ g ∈ T, S.basicOpen g ≤ U) ∧ (∀ x ∈ U ⊓ W, ∃ g ∈ T, x ∈ S.basicOpen g) ∧
      ∀ g ∈ T, ∃ (p : ℕ) (a : Fin p → Γ(F, S.basicOpen g)),
        objΓ G (S.basicOpen g) = Submodule.span Γ(S, S.basicOpen g) (Set.range a) := by
  classical
  have hcomp : IsCompact ((U ⊓ W : S.Opens) : Set S) := hU.inter_of_isOpen hW.isCompact U.2 W.2
  have hpt : ∀ x : S, x ∈ U ⊓ W → ∃ g : Γ(S, W), x ∈ S.basicOpen g ∧ S.basicOpen g ≤ U ∧
      ∃ (p : ℕ) (a : Fin p → Γ(F, S.basicOpen g)),
        objΓ G (S.basicOpen g) = Submodule.span Γ(S, S.basicOpen g) (Set.range a) := by
    intro x hx
    obtain ⟨U₁, hU₁, hxU₁, hle, hfg⟩ := hG.exists_affine_fg x hx.1
    obtain ⟨f, g, hfg', hxf⟩ := AlgebraicGeometry.exists_basicOpen_le_affine_inter hU₁ hW x ⟨hxU₁, hx.2⟩
    have hspan := hG.exists_span_basicOpen hle hU₁ hfg f
    rw [hfg'] at hspan hxf
    exact ⟨g, hxf, hfg' ▸ (S.basicOpen_le f).trans hle, hspan⟩
  choose! g hg using hpt
  obtain ⟨T₀, hT₀⟩ := hcomp.elim_finite_subcover
    (fun x : (U ⊓ W : S.Opens) => (S.basicOpen (g x) : Set S))
    (fun x => (S.basicOpen (g x)).2)
    (fun x hx => Set.mem_iUnion.mpr ⟨⟨x, hx⟩, (hg x hx).1⟩)
  refine ⟨T₀.image fun x : (U ⊓ W : S.Opens) => g x.1, ?_, ?_, ?_⟩
  · intro g' hg'
    obtain ⟨x, -, rfl⟩ := Finset.mem_image.mp hg'
    exact (hg x.1 x.2).2.1
  · intro y hy
    obtain ⟨x, hxT, hyx⟩ := Set.mem_iUnion₂.mp (hT₀ hy)
    exact ⟨g x.1, Finset.mem_image.mpr ⟨x, hxT, rfl⟩, hyx⟩
  · intro g' hg'
    obtain ⟨x, -, rfl⟩ := Finset.mem_image.mp hg'
    exact (hg x.1 x.2).2.2

/-- **Step 2.** A section `a ∈ G(D(g))` (`g ∈ Γ(W, O)`, `D(g) ≤ U`) is, up to a power of `g`, the
restriction of a section `h ∈ Γ(F, W)` whose restriction to `U ⊓ W` lies in `G`. -/
theorem GoodOn.exists_global_of_basicOpen_mem [QuasiSeparatedSpace S] {G : F.val.Submodule}
    {U : S.Opens} (hG : GoodOn F G U) (hU : IsCompact (U : Set S)) {W : S.Opens}
    (hW : AlgebraicGeometry.IsAffineOpen W) (g : Γ(S, W)) (hg : S.basicOpen g ≤ U)
    (a : Γ(F, S.basicOpen g)) (ha : a ∈ objΓ G (S.basicOpen g)) :
    ∃ (h : Γ(F, W)) (N : ℕ),
      F.presheaf.map (homOfLE (inf_le_right : U ⊓ W ≤ W)).op h ∈ objΓ G (U ⊓ W) ∧
      F.presheaf.map (homOfLE (S.basicOpen_le g)).op h =
        (S.presheaf.map (homOfLE (S.basicOpen_le g)).op g) ^ N • a := by
  obtain ⟨n, t, ht⟩ := F.exists_pow_smul_eq_map_basicOpen hW g a
  have htG : F.presheaf.map (homOfLE (S.basicOpen_le g)).op t ∈ objΓ G (S.basicOpen g) := by
    rw [ht]
    exact Submodule.smul_mem _ _ ha
  have h1 : F.presheaf.map (homOfLE (inf_le_left.trans (S.basicOpen_le g) :
      S.basicOpen g ⊓ U ≤ W)).op t ∈ objΓ G (S.basicOpen g ⊓ U) := by
    rw [← map_map (S.basicOpen_le g) inf_le_left]
    exact (mem_iff_map_mem_of_le_of_le G inf_le_left (le_inf le_rfl hg) _).mp htG
  obtain ⟨m, hm⟩ := hG.exists_pow_smul_map_inf_mem hU hW g t h1
  refine ⟨g ^ m • t, m + n, ?_, ?_⟩
  · exact (mem_iff_map_mem_of_le_of_le G (le_inf inf_le_right inf_le_left)
      (le_inf inf_le_right inf_le_left) _).mpr (by rw [map_map]; exact hm)
  · rw [AlgebraicGeometry.Scheme.Modules.map_smul, ht, map_pow, smul_smul, ← pow_add]

/-- **Stacks 01PC in sub-presheaf form.** `G` good on the quasi-compact `U`, `W` affine: there are finitely
many `e i ∈ Γ(F, W)` such that `spanSub F W e` agrees with `G` on every open `V ≤ U ⊓ W`. -/
theorem GoodOn.exists_spanSub_agree [QuasiSeparatedSpace S] {G : F.val.Submodule} {U : S.Opens}
    (hG : GoodOn F G U) (hU : IsCompact (U : Set S)) {W : S.Opens}
    (hW : AlgebraicGeometry.IsAffineOpen W) :
    ∃ (ι : Type u) (_ : Fintype ι) (e : ι → Γ(F, W)),
      ∀ V ≤ U ⊓ W, objΓ G V = objΓ (spanSub F W e) V := by
  classical
  obtain ⟨T, hTU, hTcov, hTfg⟩ := hG.exists_basicOpen_cover_fg hU hW
  choose p a ha using hTfg
  have hgen : ∀ (g : Γ(S, W)) (hg : g ∈ T) (l : Fin (p g hg)),
      ∃ (h : Γ(F, W)) (N : ℕ),
        F.presheaf.map (homOfLE (inf_le_right : U ⊓ W ≤ W)).op h ∈ objΓ G (U ⊓ W) ∧
        F.presheaf.map (homOfLE (S.basicOpen_le g)).op h =
          (S.presheaf.map (homOfLE (S.basicOpen_le g)).op g) ^ N • a g hg l := by
    intro g hg l
    exact hG.exists_global_of_basicOpen_mem hU hW g (hTU g hg) (a g hg l)
      ((ha g hg) ▸ Submodule.subset_span ⟨l, rfl⟩)
  choose h N hhG hhN using hgen
  let ι : Type u := Σ g : {g // g ∈ T}, Fin (p g.1 g.2)
  let e : ι → Γ(F, W) := fun i => h i.1.1 i.1.2 i.2
  refine ⟨ι, inferInstance, e, fun V hV => ?_⟩
  apply le_antisymm
  · -- `G(V) ⊆ spanSub(V)`
    intro t ht
    rw [mem_spanSub_iff]
    intro x hx
    obtain ⟨g, hg, hxg⟩ := hTcov x (hV hx.1)
    have hDg : AlgebraicGeometry.IsAffineOpen (S.basicOpen g) := hW.basicOpen g
    obtain ⟨b, hb, hxb⟩ := hDg.exists_basicOpen_le (V := V ⊓ S.basicOpen g) ⟨x, ⟨hx.1, hxg⟩⟩ hxg
    have hbV : S.basicOpen b ≤ V := hb.trans inf_le_left
    have hbg : S.basicOpen b ≤ S.basicOpen g := hb.trans inf_le_right
    have hbW : S.basicOpen b ≤ V ⊓ W := le_inf hbV (hbg.trans (S.basicOpen_le g))
    refine ⟨S.basicOpen b, hbW, hxb, ?_⟩
    have htb : F.presheaf.map (homOfLE (hbW.trans inf_le_left)).op t ∈ objΓ G (S.basicOpen b) :=
      mem_map_of_mem G _ ht
    rw [hG.obj_basicOpen_eq_span (hTU g hg) hDg b (a g hg) (ha g hg)] at htb
    refine (Submodule.span_le.mpr ?_) htb
    rintro _ ⟨l, rfl⟩
    -- `a g hg l |_{D(b)} = g^{-N} • h|_{D(b)}`
    have hcomp : S.presheaf.map (homOfLE hbg).op (S.presheaf.map (homOfLE (S.basicOpen_le g)).op g) =
        S.presheaf.map (homOfLE (hbg.trans (S.basicOpen_le g))).op g := by
      rw [← S.presheaf.map_comp_apply, ← op_comp, homOfLE_comp]
    have hunit : IsUnit (S.presheaf.map (homOfLE (hbg.trans (S.basicOpen_le g))).op g) := by
      rw [← hcomp]
      exact (S.toRingedSpace.isUnit_res_basicOpen g).map (S.presheaf.map (homOfLE hbg).op).hom
    refine mem_span_of_unit_pow_smul_eq F _ ⟨⟨g, hg⟩, l⟩ hunit (N g hg l) _ ?_
    show F.presheaf.map (homOfLE (hbW.trans inf_le_right)).op (h g hg l) = _
    rw [← map_map (S.basicOpen_le g) hbg, hhN g hg l, AlgebraicGeometry.Scheme.Modules.map_smul, map_pow,
      hcomp]
  · -- `spanSub(V) ⊆ G(V)`
    intro t ht
    rw [mem_spanSub_iff] at ht
    apply hG.mem_of_locally V (hV.trans inf_le_left)
    intro x hx
    obtain ⟨U₀, h₀, hx₀, ht₀⟩ := ht x ⟨hx, (hV hx).2⟩
    refine ⟨U₀, h₀.trans inf_le_left, hx₀, ?_⟩
    refine (Submodule.span_le.mpr ?_) ht₀
    rintro _ ⟨i, rfl⟩
    have := mem_map_of_mem G (h₀.trans (inf_le_inf_right W (hV.trans inf_le_left))) (hhG i.1.1 i.1.2 i.2)
    rw [map_map] at this
    exact this

end AlgebraicGeometry.Scheme.Modules.QcApprox

end
