import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.Stacks01pbAffineOpen
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.QcSectionsBasicOpenLocalization
import Mathlib.LinearAlgebra.Finsupp.LinearCombination

/-! # Generators of a finite type quasi-coherent module on an affine open

**Stacks 01PB "⇒", in the form used to build epimorphisms**: a quasi-coherent module `F` of finite
type on `X` is, over an affine open `U`, generated by finitely many sections `t_1, …, t_r ∈ Γ(F, U)`:
every section `f` of `F` over an open `V ≤ U` is, locally around each point of `V`, an
`O_X`-linear combination `Σ_j a_j • t_j|_W` of the restrictions of the `t_j`.

Proof (self-contained; everything used is proved in the library).
1. `Γ(F, U)` is a finite `Γ(X, U)`-module (`Scheme.Modules.finite_sections_of_isFiniteType`,
   `Stacks01pbAffineOpen`), so there are `r` and `t : Fin r → Γ(F, U)` spanning it
   (`Module.Finite.exists_fin`).
2. Given `V ≤ U`, `f ∈ Γ(F, V)` and `x ∈ V`, choose `g ∈ Γ(X, U)` with `x ∈ D(g) ≤ V`
   (`IsAffineOpen.exists_basicOpen_le`). Since `F` is quasi-coherent and `U` is affine, sections of
   `F` over the basic open `D(g)` are a localization of `Γ(F, U)`: there are `N` and `u ∈ Γ(F, U)` with
   `u|_{D(g)} = (g|_{D(g)})^N • f|_{D(g)}` (`Scheme.Modules.exists_pow_smul_eq_map_basicOpen`,
   `QcSectionsBasicOpenLocalization`).
3. Write `u = Σ_j c_j • t_j` (`Submodule.mem_span_range_iff_exists_fun`). The restriction `g|_{D(g)}`
   is a unit `w` (`RingedSpace.isUnit_res_basicOpen`), so
   `f|_{D(g)} = w^{-N} • u|_{D(g)} = Σ_j (w^{-N} · c_j|_{D(g)}) • t_j|_{D(g)}`; take `W := D(g)` and
   `a_j := w^{-N} · c_j|_{D(g)}`.

Edge cases: `U = ∅` (zero ring, `r = 0` works vacuously), `F = 0` (`r = 0`), `V = ∅` (nothing to
check). The statement quantifies over all `V ≤ U` and all points, so it is exactly the "locally
surjective on sections" input of `Scheme.Modules.epi_pullback_ι_map_of_locally_surjective`.

Source: Stacks 01PB (`properties-lemma-finite-type-module`), direction finite type ⇒ finitely
generated global sections on an affine; Stacks 01I8 (sections over basic opens are localizations). -/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- **Finitely many sections over an affine open generate a finite type quasi-coherent module
there** (Stacks 01PB "⇒"). There are `r` and `t : Fin r → Γ(F, U)` such that for every open `V ≤ U`,
every `f ∈ Γ(F, V)` and every `x ∈ V` there are an open `x ∈ W ≤ V` and coefficients
`a : Fin r → Γ(X, W)` with `f|_W = Σ_j a_j • t_j|_W`. -/
theorem AlgebraicGeometry.Scheme.Modules.exists_finite_generators_of_isFiniteType
    {X : AlgebraicGeometry.Scheme.{u}} (F : X.Modules) [F.IsQuasicoherent] [F.IsFiniteType]
    {U : X.Opens} (hU : AlgebraicGeometry.IsAffineOpen U) :
    ∃ (r : ℕ) (t : Fin r → Γ(F, U)), ∀ (V : X.Opens) (hVU : V ≤ U) (f : Γ(F, V)) (x : X), x ∈ V →
      ∃ (W : X.Opens) (hWV : W ≤ V), x ∈ W ∧ ∃ a : Fin r → Γ(X, W),
        F.presheaf.map (homOfLE hWV).op f =
          ∑ j, a j • F.presheaf.map (homOfLE (hWV.trans hVU)).op (t j) := by
  classical
  have hfin : Module.Finite Γ(X, U) Γ(F, U) :=
    AlgebraicGeometry.Scheme.Modules.finite_sections_of_isFiniteType F hU
  obtain ⟨r, t, ht⟩ := Module.Finite.exists_fin (R := Γ(X, U)) (M := Γ(F, U))
  refine ⟨r, t, fun V hVU f x hx => ?_⟩
  obtain ⟨g, hgV, hxg⟩ := hU.exists_basicOpen_le (V := V) ⟨x, hx⟩ (hVU hx)
  have hDU : X.basicOpen g ≤ U := X.basicOpen_le g
  set fD : Γ(F, X.basicOpen g) := F.presheaf.map (homOfLE hgV).op f with hfD
  obtain ⟨N, u, hu⟩ :=
    AlgebraicGeometry.Scheme.Modules.exists_pow_smul_eq_map_basicOpen F hU g fD
  have hu_mem : u ∈ Submodule.span Γ(X, U) (Set.range t) := by rw [ht]; trivial
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun Γ(X, U)).mp hu_mem
  have hunit : IsUnit (X.presheaf.map (homOfLE (X.basicOpen_le g)).op g) :=
    X.toRingedSpace.isUnit_res_basicOpen g
  obtain ⟨w, hw⟩ := hunit
  refine ⟨X.basicOpen g, hgV, hxg,
    fun j => (↑(w⁻¹ ^ N) : Γ(X, X.basicOpen g)) * X.presheaf.map (homOfLE hDU).op (c j), ?_⟩
  have hres : F.presheaf.map (homOfLE hDU).op u =
      ∑ j, X.presheaf.map (homOfLE hDU).op (c j) • F.presheaf.map (homOfLE hDU).op (t j) := by
    rw [← hc, map_sum]
    refine Finset.sum_congr rfl fun j _ => ?_
    exact AlgebraicGeometry.Scheme.Modules.map_smul F (homOfLE hDU) (c j) (t j)
  have hone : (↑(w⁻¹ ^ N) : Γ(X, X.basicOpen g)) *
      (X.presheaf.map (homOfLE (X.basicOpen_le g)).op g) ^ N = 1 := by
    rw [← hw, ← Units.val_pow_eq_pow_val, ← Units.val_mul, inv_pow, inv_mul_cancel, Units.val_one]
  have key : fD = (↑(w⁻¹ ^ N) : Γ(X, X.basicOpen g)) • F.presheaf.map (homOfLE hDU).op u := by
    rw [hu, smul_smul, hone, one_smul]
  change fD = _
  rw [key, hres, Finset.smul_sum]
  refine Finset.sum_congr rfl fun j _ => ?_
  rw [smul_smul]

end
