import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.QuasiCoherent.QcLocalizedModule

/-! # Finite type sheaves have finitely generated sections on affine opens (Stacks 01PB)

Stacks 01PB on an affine open: if `M` is a quasi-coherent sheaf of finite type on a scheme `X`
and `U ⊆ X` is an affine open, then `Γ(M, U)` is a finitely generated `Γ(X, U)`-module.

Source: Stacks 01PB (properties-lemma-finite-type-module, "(1) ⇔ (2)"), together with
Stacks 01I8 (a quasi-coherent sheaf on an affine scheme is the tilde of its module of sections).
The `⊤`-version for an affine scheme is the forward direction of
`AlgebraicGeometry.Scheme.Modules.isFiniteType_iff_finite_sections` (`Stacks01pb`), which
follows from this lemma applied to `U = ⊤` (`isAffineOpen_top X`);
this lemma is the version on an arbitrary affine open, which is what the relative Proj needs
(charts `Proj S(U) → U`, `U` affine open of the base). The converse direction is
`AlgebraicGeometry.Scheme.Modules.isFiniteType_of_finite_affine_sections`
(`FiniteTypeOfFiniteAffineSections`).

Auxiliary lemmas live in `Stacks01pbAffineOpenAux`:
`finite_of_generatingSections` (Spec: finitely many generating sections ⇒ finite global sections,
via full faithfulness of `tilde`), `exists_generatingSections_restrict` (generators of `M.over V`
⇒ generators of `M.restrict f` for an open immersion `f` with image in `V`),
`finite_of_finite_restrict` (transport along `restrictAppIso`), `finite_basicOpen` (the local step).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

open AlgebraicGeometry

namespace Stacks01pbAffineOpenAux

set_option backward.isDefEq.respectTransparency false in
/-- On `Spec R`, a quasi-coherent module generated by finitely many global sections has
finitely generated global sections. -/
theorem finite_of_generatingSections {R : CommRingCat.{u}} (N : (Spec R).Modules)
    [N.IsQuasicoherent] (σ : N.GeneratingSections) [σ.IsFiniteType] :
    Module.Finite R Γ(N, ⊤) := by
  let P : ModuleCat.{u} R := (modulesSpecToSheaf.obj N).presheaf.obj (.op ⊤)
  have : IsIso N.fromTildeΓ := Scheme.Modules.isIso_fromTildeΓ_of_isQuasicoherent N
  have : Epi (C := (Spec R).Modules) σ.π := σ.epi
  let φ : SheafOfModules.free.{u} σ.I ⟶ tilde P := σ.π ≫ inv N.fromTildeΓ
  have : Epi φ := epi_comp _ _
  let ψ : (tilde.functor R).obj (ModuleCat.of R (σ.I →₀ R)) ⟶ (tilde.functor R).obj P :=
    (tildeFinsupp σ.I).hom ≫ φ
  have : Epi ψ := epi_comp _ _
  let g : ModuleCat.of R (σ.I →₀ R) ⟶ P := (tilde.functor R).preimage ψ
  have : Epi ((tilde.functor R).map g) := by
    rw [Functor.map_preimage]; infer_instance
  have : Epi g := (tilde.functor R).epi_of_epi_map this
  have hg := (ModuleCat.epi_iff_surjective g).mp this
  have : Finite σ.I := SheafOfModules.GeneratingSections.IsFiniteType.finite
  have : Module.Finite R (σ.I →₀ R) := inferInstance
  have : Module.Finite R P := Module.Finite.of_surjective g.hom hg
  exact this

set_option backward.isDefEq.respectTransparency false in
/-- Generators of `M.over V` give generators of `M.restrict f` for any open immersion `f`
with image inside `V`. -/
theorem exists_generatingSections_restrict {X Y : Scheme.{u}} (f : Y ⟶ X) [IsOpenImmersion f]
    (M : X.Modules) {V : X.Opens} (hf : f.opensRange ≤ V)
    (σ : (M.over V).GeneratingSections) [σ.IsFiniteType] :
    ∃ τ : (M.restrict f).GeneratingSections, τ.IsFiniteType := by
  have hrange : Set.range f.base ⊆ Set.range V.ι.base := by
    rw [Scheme.Opens.range_ι]
    exact fun x hx => hf (show x ∈ f.opensRange from hx)
  let f' : Y ⟶ V.toScheme := IsOpenImmersion.lift V.ι f hrange
  have hf' : f' ≫ V.ι = f := IsOpenImmersion.lift_fac _ _ _
  have : IsOpenImmersion f' := inferInstance
  have h1 : PreservesColimitsOfSize.{u, u} (Scheme.Modules.overEquiv V).functor := inferInstance
  have h2 : PreservesColimitsOfSize.{u, u} (Scheme.Modules.restrictFunctor f') := inferInstance
  let F := (Scheme.Modules.overEquiv V).functor ⋙ Scheme.Modules.restrictFunctor f'
  have : PreservesColimitsOfSize.{u, u} F := @comp_preservesColimits _ _ _ _ _ _ _ _ h1 h2
  let η : SheafOfModules.unit Y.ringCatSheaf ≅ F.obj (SheafOfModules.unit _) :=
    (Scheme.Modules.restrictUnitIso f').symm
  let iso : F.obj (M.over V) ≅ M.restrict f :=
    (Scheme.Modules.restrictFunctor f').mapIso ((Scheme.Modules.overFunctorEquiv V).app M) ≪≫
      ((Scheme.Modules.restrictFunctorComp f' V.ι).app M).symm ≪≫
      (Scheme.Modules.restrictFunctorCongr hf').app M
  exact ⟨(σ.map F η).ofEpi iso.hom, inferInstance⟩

/-- Transfer finiteness of the global sections of `M.restrict hU.fromSpec` back to `Γ(M, U)`
(a semilinear bijection with respect to a ring automorphism of `Γ(X, U)`). -/
theorem finite_of_finite_restrict {X : Scheme.{u}} (M : X.Modules) {U : X.Opens}
    (hU : IsAffineOpen U) [h : Module.Finite Γ(X, U) Γ(M.restrict hU.fromSpec, ⊤)] :
    Module.Finite Γ(X, U) Γ(M, U) := by
  have hV : hU.fromSpec ''ᵁ ⊤ = U := by
    rw [Scheme.Hom.image_top_eq_opensRange, hU.opensRange_fromSpec]
  let e : Γ(X, U) ≃+* Γ(X, U) :=
    ((X.presheaf.mapIso (eqToIso hV).op) ≪≫ (hU.fromSpec.appIso ⊤) ≪≫
      Scheme.ΓSpecIso Γ(X, U)).commRingCatIsoToRingEquiv
  have : RingHomSurjective (e : Γ(X, U) →+* Γ(X, U)) := ⟨e.surjective⟩
  have : RingHomSurjective (e.symm : Γ(X, U) →+* Γ(X, U)) := ⟨e.symm.surjective⟩
  have key : ∀ (r : Γ(X, hU.fromSpec ''ᵁ ⊤)) (y : Γ(M, hU.fromSpec ''ᵁ ⊤)),
      (M.restrictAppIso hU.fromSpec ⊤).inv (r • y) =
        ((hU.fromSpec.appIso ⊤).hom r) • (M.restrictAppIso hU.fromSpec ⊤).inv y := fun r y => by
    have := Scheme.Modules.smul_restrictAppIso_inv_apply hU.fromSpec M ⊤ r y
    exact this
  let g : Γ(M, U) →ₛₗ[(e : Γ(X, U) →+* Γ(X, U))] Γ(M.restrict hU.fromSpec, ⊤) :=
    { toFun := fun m => (M.restrictAppIso hU.fromSpec ⊤).inv (M.presheaf.map (eqToHom hV).op m)
      map_add' := fun a b => by simp
      map_smul' := fun a m => by
        rw [Scheme.Modules.map_smul, key, Scheme.Modules.smul_Spec_def]
        congr 1
        simp only [e]
        have h1 : (Opens.leTop (⊤ : (Spec Γ(X, U)).Opens)).op = 𝟙 _ := Subsingleton.elim _ _
        rw [h1, CategoryTheory.Functor.map_id]
        simp [Iso.commRingCatIsoToRingEquiv] }
  have hg : Function.Bijective g :=
    ((ConcreteCategory.bijective_of_isIso (M.restrictAppIso hU.fromSpec ⊤).inv)).comp
      (ConcreteCategory.bijective_of_isIso (M.presheaf.map (eqToHom hV).op))
  have : RingHomInvPair (e : Γ(X, U) →+* Γ(X, U)) (e.symm : Γ(X, U) →+* Γ(X, U)) :=
    RingHomInvPair.of_ringEquiv e
  have : RingHomInvPair (e.symm : Γ(X, U) →+* Γ(X, U)) (e : Γ(X, U) →+* Γ(X, U)) :=
    RingHomInvPair.of_ringEquiv_symm e
  let ge : Γ(M, U) ≃ₛₗ[(e : Γ(X, U) →+* Γ(X, U))] Γ(M.restrict hU.fromSpec, ⊤) :=
    LinearEquiv.ofBijective g hg
  exact Module.Finite.of_surjective
    (ge.symm : Γ(M.restrict hU.fromSpec, ⊤) →ₛₗ[(e.symm : Γ(X, U) →+* Γ(X, U))] Γ(M, U))
    ge.symm.surjective

set_option backward.isDefEq.respectTransparency false in
/-- Local step: if `M.over V` is generated by finitely many sections and `X.basicOpen g ≤ V`
(`g ∈ Γ(X, U)`, `U` affine), then `Γ(M, X.basicOpen g)` is a finite `Γ(X, X.basicOpen g)`-module.
Proof: `D := X.basicOpen g` is affine; transfer the generators to `M.restrict hD.fromSpec` on
`Spec Γ(X, D)` (`exists_generatingSections_restrict`), apply `finite_of_generatingSections`,
and transport back along the semilinear bijection (`finite_of_finite_restrict`). -/
theorem finite_basicOpen {X : Scheme.{u}} (M : X.Modules) [M.IsQuasicoherent] {U : X.Opens}
    (hU : IsAffineOpen U) {V : X.Opens} (σ : (M.over V).GeneratingSections) [σ.IsFiniteType]
    (g : Γ(X, U)) (hg : X.basicOpen g ≤ V) :
    Module.Finite Γ(X, X.basicOpen g) Γ(M, X.basicOpen g) := by
  have hD : IsAffineOpen (X.basicOpen g) := hU.basicOpen g
  have hrange : hD.fromSpec.opensRange ≤ V := by
    rw [hD.opensRange_fromSpec]; exact hg
  obtain ⟨τ, hτ⟩ := exists_generatingSections_restrict hD.fromSpec M hrange σ
  have := hτ
  have : Module.Finite Γ(X, X.basicOpen g) Γ(M.restrict hD.fromSpec, ⊤) :=
    finite_of_generatingSections (M.restrict hD.fromSpec) τ
  exact finite_of_finite_restrict M hD

end Stacks01pbAffineOpenAux

/-- **Stacks 01PB on an affine open.** Let `A = Γ(X, U)` and `N = Γ(M, U)`.

Proof. The route avoids the
"epi ⇒ surjective on affine sections" step (Stacks 01IC + 01XB) of the first plan and instead uses
the full faithfulness of `tilde` on `Spec` (Stacks 01I8):
1. `M.IsFiniteType` (Mathlib `SheafOfModules.IsFiniteType`) gives an open cover `V_i` of `X` and,
   for each `i`, finitely many sections generating `M.over V_i` (an epi `free I_i → M.over V_i`).
   For `x ∈ U` pick `i` with `x ∈ V_i` and `g ∈ A` with `x ∈ D(g) := X.basicOpen g ≤ V_i`
   (`IsAffineOpen.exists_basicOpen_le`).
2. `D(g)` is affine (`IsAffineOpen.basicOpen`). Along the open immersion
   `j = hD.fromSpec : Spec Γ(X, D(g)) → X`, whose image lies in `V_i`, the generators of
   `M.over V_i` transfer to finitely many generating sections of `M.restrict j`
   (`Stacks01pbAffineOpenAux.exists_generatingSections_restrict`: the functor
   `(overEquiv V_i).functor ⋙ restrictFunctor j'` preserves colimits and the unit, and
   `SheafOfModules.GeneratingSections.map`; `j = j' ≫ V_i.ι` by `IsOpenImmersion.lift`).
3. On `Spec R` (`R = Γ(X, D(g))`) a quasi-coherent module `N'` with an epi `free I → N'`,
   `I` finite, has `Γ(N', ⊤)` finite over `R`
   (`Stacks01pbAffineOpenAux.finite_of_generatingSections`): `N' ≅ tilde Γ(N', ⊤)`
   (`isIso_fromTildeΓ_of_isQuasicoherent`), `free I ≅ tilde (I →₀ R)` (`tildeFinsupp`),
   `tilde` is fully faithful (`tilde.fullyFaithfulFunctor`) hence reflects epimorphisms, so the
   epi comes from a surjection `(I →₀ R) → Γ(N', ⊤)` (`ModuleCat.epi_iff_surjective`).
4. Transport `Module.Finite R Γ(M.restrict j, ⊤)` to `Module.Finite Γ(X, D(g)) Γ(M, D(g))` along the
   semilinear bijection `Γ(M, D(g)) ≃ Γ(M.restrict j, ⊤)` (`restrictAppIso`, with the ring
   automorphism `Γ(X, D(g)) ≅ Γ(Spec R, ⊤) ≅ R`; `Stacks01pbAffineOpenAux.finite_of_finite_restrict`).
5. The `g`'s obtained in step 1 satisfy `U ≤ ⨆ D(g)`, so they generate the unit ideal of `A`
   (`IsAffineOpen.self_le_iSup_basicOpen_iff`); take a finite subset `t` (`Ideal.span_eq_top_iff_finite`).
   Since `M` is quasi-coherent, `N → Γ(M, D(g))` is the localization of `N` at `g`
   (`Scheme.Modules.isLocalizedModule_basicOpen`, Stacks 01I8 on `X`), and
   `Γ(X, D(g)) = A_g` (`IsAffineOpen.isLocalization_basicOpen`). Mathlib's
   `Module.Finite.of_localizationSpan_finite'` concludes `Module.Finite A N`.

Edge cases: `U = ∅` (zero ring, zero module — fine); zero scheme — fine. -/
theorem AlgebraicGeometry.Scheme.Modules.finite_sections_of_isFiniteType
    {X : AlgebraicGeometry.Scheme.{u}} (M : X.Modules) [M.IsQuasicoherent] [M.IsFiniteType]
    {U : X.Opens} (hU : AlgebraicGeometry.IsAffineOpen U) :
    Module.Finite Γ(X, U) Γ(M, U) := by
  classical
  obtain ⟨d, hd⟩ := SheafOfModules.IsFiniteType.exists_localGeneratorsData M
  have hcov : ∀ x : X, ∃ i, x ∈ d.X i := by
    have h := d.coversTop
    rw [Opens.coversTop_iff] at h
    intro x
    have hx : x ∈ ⨆ i, d.X i := by rw [h]; trivial
    exact Opens.mem_iSup.mp hx
  have hloc : ∀ x : U, ∃ g : Γ(X, U), x.1 ∈ X.basicOpen g ∧
      Module.Finite Γ(X, X.basicOpen g) Γ(M, X.basicOpen g) := by
    intro x
    obtain ⟨i, hi⟩ := hcov x.1
    obtain ⟨g, hg1, hg2⟩ := hU.exists_basicOpen_le (V := d.X i) ⟨x.1, hi⟩ x.2
    have := hd.isFiniteType i
    exact ⟨g, hg2, Stacks01pbAffineOpenAux.finite_basicOpen M hU (d.generators i) g hg1⟩
  choose gof hg1 hg2 using hloc
  have hspan : Ideal.span (Set.range gof) = ⊤ := by
    rw [← hU.self_le_iSup_basicOpen_iff]
    intro x hx
    exact Opens.mem_iSup.mpr ⟨⟨gof ⟨x, hx⟩, ⟨x, hx⟩, rfl⟩, hg1 ⟨x, hx⟩⟩
  obtain ⟨t, hts, ht⟩ := (Ideal.span_eq_top_iff_finite _).mp hspan
  have hfin : ∀ g : t, Module.Finite Γ(X, X.basicOpen g.1) Γ(M, X.basicOpen g.1) := by
    intro g
    obtain ⟨x, hx⟩ := hts g.2
    have := hg2 x
    rw [hx] at this
    exact this
  let modD : ∀ g : t, Module Γ(X, U) Γ(M, X.basicOpen g.1) := fun g =>
    Module.compHom Γ(M, X.basicOpen g.1) (X.presheaf.map (homOfLE (X.basicOpen_le g.1)).op).hom
  have : ∀ g : t, IsScalarTower Γ(X, U) Γ(X, X.basicOpen g.1) Γ(M, X.basicOpen g.1) := fun g =>
    ⟨fun r a m => by
      change ((X.presheaf.map (homOfLE (X.basicOpen_le g.1)).op).hom r * a) • m =
        (X.presheaf.map (homOfLE (X.basicOpen_le g.1)).op).hom r • (a • m)
      rw [mul_smul]⟩
  let f : ∀ g : t, Γ(M, U) →ₗ[Γ(X, U)] Γ(M, X.basicOpen g.1) := fun g =>
    { toFun := M.presheaf.map (homOfLE (X.basicOpen_le g.1)).op
      map_add' := fun a b => by simp
      map_smul' := fun r m => by
        rw [Scheme.Modules.map_smul]; rfl }
  have : ∀ g : t, IsLocalization.Away g.1 Γ(X, X.basicOpen g.1) := fun g =>
    hU.isLocalization_basicOpen g.1
  have : ∀ g : t, IsLocalizedModule.Away g.1 (f g) := fun g =>
    Scheme.Modules.isLocalizedModule_basicOpen M hU g.1 (fun _ _ => rfl) (f g) (fun _ => rfl)
  exact Module.Finite.of_localizationSpan_finite' t ht f hfin

end
