import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Divisors.Cartier.CartierDivisor
import MiyaokaMori.AlgebraicGeometry.Divisors.Degree.CurveDivisorDegree
import MiyaokaMori.AlgebraicGeometry.Divisors.LineBundle.DivisorLineBundle
import MiyaokaMori.AlgebraicGeometry.Divisors.Degree.LineBundleDegree
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.LineBundleIsoOfModulesIso
import MiyaokaMori.AlgebraicGeometry.Varieties.Curves.SmoothProjectiveCurve
import MiyaokaMori.AlgebraicGeometry.Divisors.Weil.CartierToWeil
import MiyaokaMori.AlgebraicGeometry.Divisors.LineBundle.DivisorLineBundleGenericSection
import MiyaokaMori.AlgebraicGeometry.Divisors.RationalSections.LineCartierPresentationOfFrames
import MiyaokaMori.AlgebraicGeometry.Morphisms.IsProjectiveOverIsProper

/-! # The degree of `O_C(D)` is the degree of `D`

Comparison of the two degrees: `L ≅ O_C(D)` implies `deg L = deg D`. On the left, `LineBundle.degree`
is the difference of Euler characteristics, equal to the top self-intersection `deg(c₁(L) ∩ [C])`
(`LineBundle.degree_eq_topSelfIntersection`); on the right, `CartierDivisor.degree` is the degree of
the Weil cycle of `D`.

Sources: Hartshorne II.6.13 (`O(D)` is generated by `f_i^{-1}` on `U_i`); Stacks 02SG, 0AYQ.

All the mathematical content lies in the core lemma
`CartierDivisor.exists_lineCartierPresentation_coefficient_variety` (for an arbitrary variety) and its
curve case `CartierDivisor.exists_lineCartierPresentation_coefficient`; the remaining statements follow
from it. The bridge does not go through "a principal divisor has degree zero": `HasCurveModuleDegree` is
existential, so one presentation of `O(D)` suffices.
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory

noncomputable section

/-- Core lemma (Hartshorne II.6.13): `O_X(D)` has a Cartier presentation (a rational section `s`, local
frames, and local equations given by the coordinates of `s` in the frames) whose coefficient function
is exactly that of `[D]`. Valid on any variety.

Route:
1. Take local equations `(U_i, f_i)` of `D` (`cartierDivisor_exists_localData`); `weilCycle_ofLocalData`
   gives that the coefficient of `[D]` inside `U_i` is `ord(f_i)`.
2. Cartier data: `authorLocalData U f` with the empty opens removed (`nonemptyPart`; this does not
   change the coefficients).
3. On each `U_i` take a local equation `t_i` in the quotient sheaf (with value `f_i` at the generic
   point, `local_section_ofLocalData`). Then `t_i^{-1}` is a frame of `O_X(D)` on `U_i`
   (`IsLocalEquation.isFrame`): sections are characterized by `h ∈ O_X(D)(W) ⟺ h·t|_W ∈ O_X(W)`, and
   sheafification does not change sections because the subpresheaf is already a sheaf.
4. The rational section `s := f_{i₀} • (t_{i₀}^{-1})_η` is independent of `i₀`:
   `f_i • (t_i^{-1})_η = f_j • (t_j^{-1})_η` (`IsLocalEquation.smul_germ_frame_eq`).
5. Assembly (`LineCartierPresentationOfFrames`): a frame gives a trivialization (`IsFrame.restrictIso`),
   the generic coordinate of the frame element is `1`, so the coordinate of `s` is `f_i`
   (`equation_eq`); `section_ne_zero` follows from the coordinate being nonzero. -/
theorem CartierDivisor.exists_lineCartierPresentation_coefficient_variety {k : Type u} [Field k]
    (X : Variety k) (D : CartierDivisor X)
    [AlgebraicGeometry.IsIntegral X.toScheme] [AlgebraicGeometry.IsLocallyNoetherian X.toScheme] :
    ∃ (s : (CartierDivisor.lineBundle D).toModules.presheaf.stalk (genericPoint X.toScheme))
      (P : AlgebraicGeometry.Divisors.LineCartierPresentation
        (⟨X.toScheme, X.toScheme ↘ AlgebraicGeometry.Spec (CommRingCat.of k)⟩ : AlgebraicGeometry.Proj.SchemeOver k)
        (CartierDivisor.lineBundle D).toModules s),
      ∀ x : X.toScheme, P.cartier.coefficient x =
        (CartierDivisor.weilCycle X D :
          AlgebraicGeometry.AlgebraicCycle X.toScheme ℤ) x := by
  classical
  obtain ⟨ι, U, f, hUf, hD⟩ := cartierDivisor_exists_localData X D
  subst hD
  let A := MiyaokaMori.LineCartierPresentationOfFrames.nonemptyPart
    (CartierDivisor.authorLocalData U f hUf)
  let η := genericPoint X.toScheme
  have key : ∀ i : A.index, ∃ t : X.toScheme.rationalFunctionsUnitsSheaf.val.obj (Opposite.op (A.opens i)),
      CartierDivisor.IsLocalEquation (CartierDivisor.ofLocalData U f) (A.opens i) t ∧
      ((@AlgebraicGeometry.Scheme.rationalUnitsSectionToFunctionField X.toScheme _ (A.opens i) i.2 t :
          (X.toScheme.functionField)ˣ) : X.toScheme.functionField) = A.equation i := by
    intro i
    obtain ⟨⟨x, hx⟩⟩ := i.2
    obtain ⟨t, htv, htq⟩ := CartierToWeilLocalSection.local_section_ofLocalData U f hUf x i.1.1 hx
    exact ⟨t, htq, congrArg Units.val htv⟩
  choose t ht hval using key
  have hηmem : ∀ i : A.index, η ∈ A.opens i := fun i =>
    AlgebraicGeometry.Divisors.LineGenericCoordinates.genericPoint_mem_of_nonempty X.toScheme (A.opens i) i.2
  let i₀ : A.index := A.indexAt η
  let s : (CartierDivisor.lineBundle (CartierDivisor.ofLocalData U f)).toModules.presheaf.stalk η :=
    (A.equation i₀ : X.toScheme.presheaf.stalk η) •
      (CartierDivisor.lineBundleModules (CartierDivisor.ofLocalData U f)).presheaf.germ
        (A.opens i₀) η (hηmem i₀) (ht i₀).frame
  have hs : ∀ (i : A.index) (hU : Nonempty (A.opens i)), s =
      (A.equation i : X.toScheme.presheaf.stalk η) •
        (CartierDivisor.lineBundleModules (CartierDivisor.ofLocalData U f)).presheaf.germ
          (A.opens i) η
          (AlgebraicGeometry.Divisors.LineGenericCoordinates.genericPoint_mem_of_nonempty X.toScheme (A.opens i) hU)
          (ht i).frame := by
    intro i hU
    have : Nonempty (A.opens i₀) := i₀.2
    have : Nonempty (A.opens i) := i.2
    have h := (ht i₀).smul_germ_frame_eq (ht i) (hηmem i₀) (hηmem i)
    rw [hval i₀, hval i] at h
    exact h
  obtain ⟨P, hP⟩ := MiyaokaMori.LineCartierPresentationOfFrames.exists_presentation_of_frames
    (⟨X.toScheme, X.toScheme ↘ AlgebraicGeometry.Spec (CommRingCat.of k)⟩ : AlgebraicGeometry.Proj.SchemeOver k)
    (CartierDivisor.lineBundleModules (CartierDivisor.ofLocalData U f)) A
    (fun i => (ht i).frame) (fun i => (ht i).isFrame) s hs
  refine ⟨s, P, fun x => ?_⟩
  rw [hP, A.coefficient_eq_ord_of_mem x (A.indexAt x) (A.indexAt_mem x)]
  exact (CartierDivisor.weilCycle_ofLocalData X U f hUf (A.indexAt x).1.1 x
    (A.indexAt_mem x)).symm

/-- The curve case of the core lemma: `X := C.toVariety`. -/
theorem CartierDivisor.exists_lineCartierPresentation_coefficient {k : Type u} [Field k]
    (C : SmoothProjectiveCurve k) (D : CartierDivisor C.toVariety)
    [AlgebraicGeometry.IsIntegral C.toScheme] [AlgebraicGeometry.IsLocallyNoetherian C.toScheme] :
    ∃ (s : (CartierDivisor.lineBundle D).toModules.presheaf.stalk (genericPoint C.toScheme))
      (P : AlgebraicGeometry.Divisors.LineCartierPresentation
        (⟨C.toScheme, C.toScheme ↘ AlgebraicGeometry.Spec (CommRingCat.of k)⟩ : AlgebraicGeometry.Proj.SchemeOver k)
        (CartierDivisor.lineBundle D).toModules s),
      ∀ x : C.toScheme, P.cartier.coefficient x =
        (CartierDivisor.weilCycle C.toVariety D :
          AlgebraicGeometry.AlgebraicCycle C.toScheme ℤ) x :=
  CartierDivisor.exists_lineCartierPresentation_coefficient_variety C.toVariety D

/-- The bridge in relational form: the degree relation of `O(D)` holds at `d = deg D`. -/
private theorem CartierDivisor.hasCurveModuleDegree_lineBundle {k : Type u} [Field k]
    (C : SmoothProjectiveCurve k) (D : CartierDivisor C.toVariety) :
    AlgebraicGeometry.Intersection.HasCurveModuleDegree
      (⟨C.toScheme, C.toScheme ↘ AlgebraicGeometry.Spec (CommRingCat.of k)⟩ : AlgebraicGeometry.Proj.SchemeOver k)
      (CartierDivisor.lineBundle D).toModules (CartierDivisor.degree C D) := by
  letI : AlgebraicGeometry.IsIntegral C.toScheme := SmoothProjectiveCurve.isIntegral C
  letI : AlgebraicGeometry.IsProper
      (C.toScheme ↘ AlgebraicGeometry.Spec (CommRingCat.of k)) :=
    IsProjectiveOver.isProper C.projective
  letI : AlgebraicGeometry.IsNoetherian C.toScheme :=
    AlgebraicGeometry.Intersection.properFieldScheme_isNoetherian
      (C.toScheme ↘ AlgebraicGeometry.Spec (CommRingCat.of k))
  have hdim : topologicalKrullDim C.toScheme ≤ 1 := by rw [C.dim_one]
  obtain ⟨s, P, hP⟩ := CartierDivisor.exists_lineCartierPresentation_coefficient C D
  refine ⟨inferInstance, inferInstance, inferInstance, hdim, s, P, ?_⟩
  -- `CartierDivisor.degree C D = AlgebraicCycle.degree (weilCycle D)`, and `rawZeroCycleDegree` is an
  -- abbreviation of the same primitive
  rw [CartierDivisor.degree_weilCycle]
  change AlgebraicGeometry.AlgebraicCycle.degree (k := k)
    ((P.cartier.zeroCycle hdim : AlgebraicGeometry.Intersection.DimensionCycle C.toScheme 0) :
      AlgebraicGeometry.AlgebraicCycle C.toScheme ℤ) = _
  congr 1
  apply Function.locallyFinsuppWithin.ext
  intro x
  exact hP x

/-- `L ≅ O_C(D)` implies `deg L = deg D`. -/
theorem LineBundle.degree_eq_cartierDivisor_degree {k : Type u} [Field k]
    (C : SmoothProjectiveCurve k) {D : CartierDivisor C.toVariety} {L : LineBundle C.toVariety}
    (e : (CartierDivisor.lineBundle D).toModules ≅ L.toModules) :
    LineBundle.degree L = CartierDivisor.degree C D :=
  LineBundle.degree_eq_of_hasCurveModuleDegree L
    ((AlgebraicGeometry.Intersection.curveModuleDegree_iso_iff _ _ _ e _).mp
      (CartierDivisor.hasCurveModuleDegree_lineBundle C D))

/-- The degree of the line bundle `O_C(D)` is the degree of `D`. -/
theorem CartierDivisor.lineBundle_degree {k : Type u} [Field k]
    (C : SmoothProjectiveCurve k) (D : CartierDivisor C.toVariety) :
    LineBundle.degree (CartierDivisor.lineBundle D) = CartierDivisor.degree C D :=
  LineBundle.degree_eq_cartierDivisor_degree C (Iso.refl _)

end
