import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Cohomology.ConstantSheaf.Stacks0a38ConstantInclusion
import MiyaokaMori.AlgebraicGeometry.Cohomology.ConstantSheaf.Stacks0a38GenSub
import MiyaokaMori.AlgebraicGeometry.Cohomology.ConstantSheaf.Stacks0a38GradedPieceOpens

/-! # The graded pieces of the filtration are short exact (Stacks 0A38)

Stacks 0A38, third paragraph of the proof: for a gcd-closed list of constant positive generators
`(V_i, n_i, ψ_i)` of `K ⊆ ℤ_X`, with `K_k := ⟨ψ_i : n_i ≤ k⟩` (`genSub ψ n k`), each graded piece `K_{k+1}/K_k`
sits in a short exact sequence `0 → j_!ℤ_W → j_!ℤ_V → K_{k+1}/K_k → 0` with `V`, `W` quasi-compact opens.

Source: Stacks 0A38 (cohomology-lemma-subsheaf-of-constant-sheaf), proof, paragraph 3.

**Route.** Everything reduces to
the exactness of the stalk functor on abelian sheaves (Mathlib `Mathlib.Topology.Sheaves.Abelian`) and to a few
stalk computations (`Stacks0a38GradedPieceStalk.lean`, `Stacks0a38GradedPieceRestrict.lean`,
`Stacks0a38GradedPieceOpens.lean`). With `V = ⋃_{n_i = k+1} V_i`, `W = V ∩ ⋃_{n_i ≤ k} V_i`,
`q : j_!ℤ_V ⟶ K_{k+1}` the constant section `k+1` over `V` (`exists_gradedSection`), `p := q ≫ cokernel.π t_k`
and `ρ : j_!ℤ_W ⟶ j_!ℤ_V` the restriction map:
* `p` is an epimorphism (`epi_gradedQuotientMap`): `K_{k+1}` is generated by `K_k` and `q`, purely categorically;
* `ρ ≫ p = 0` (`restrict_comp_gradedQuotientMap`): the section `k+1` over `W` lies in `K_k`
  (`exists_gradedSectionLow`, the gcd argument), purely categorically;
* `kernel.lift p ρ : j_!ℤ_W ⟶ ker p` is an isomorphism (`isIso_kernelLift_gradedQuotientMap`), checked on stalks:
  at `x ∈ W` the stalk of `ρ` is an isomorphism; at `x ∉ V` the stalk of `j_!ℤ_V` is zero; at `x ∈ V ∖ W` the stalk
  of `K_k` is zero, so the stalk of `q ≫ cokernel.π t_k` is injective up to `(k+1) • c_V`, which is a monomorphism
  since `ℤ_X` has no torsion;
* the short exact sequence is `0 → ker p → j_!ℤ_V → coker t_k → 0`. -/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace TopCat.Presheaf

noncomputable section

namespace TopCat.Sheaf

variable {X : TopCat.{u}}

section Aux

variable {K : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}}
  {t : ℕ} {V : Fin t → Opens X} (ψ : ∀ i, extendByZeroConstant (V i) ⟶ K) (n : Fin t → ℕ) (k : ℕ)
  (m : K ⟶ (CategoryTheory.constantSheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}).obj
    (AddCommGrpCat.of (ULift ℤ)))

/-- `p := q ≫ cokernel.π t_k : j_!ℤ_V ⟶ K_{k+1}/K_k`, for `q : j_!ℤ_V ⟶ K_{k+1}` (the constant section `k+1`
over `V`, `exists_gradedSection`). -/
def gradedQuotientMap (q : extendByZeroConstant (gradedOpen V n k) ⟶ genSub ψ n (k + 1)) :
    extendByZeroConstant (gradedOpen V n k) ⟶ cokernel (genSubT ψ n k) :=
  q ≫ cokernel.π (genSubT ψ n k)

section Biproduct

-- Mathlib states `Abelian.hasFiniteBiproducts` as a theorem, not an instance; we use it section-locally
-- (no global instance is registered), exactly as in `Stacks0a38GenSub.lean`.
attribute [local instance] CategoryTheory.Abelian.hasFiniteBiproducts

/-- **`p` is an epimorphism.** `K_{k+1}` is the image of `⨁_{n_i ≤ k+1} j_!ℤ_{V_i} ⟶ K`; the summand `ψ_i`
with `n_i ≤ k` factors through `t_k : K_k ⟶ K_{k+1}` (so it dies in the cokernel), and the summand `ψ_i` with
`n_i = k+1` is `ρ_{V_i,V} ≫ q` (both are `(k+1) • c_{V_i}` after `ι_{k+1} ≫ m`). Hence two maps out of
`coker t_k` agreeing after `p` agree after `cokernel.π t_k`, which is an epimorphism. -/
theorem epi_gradedQuotientMap [Mono m] (hψ : ∀ i, ψ i ≫ m = ((n i : ℤ) • constantInclusion (V i)))
    (q : extendByZeroConstant (gradedOpen V n k) ⟶ genSub ψ n (k + 1))
    (hq : q ≫ genSubι ψ n (k + 1) ≫ m = (((k + 1 : ℕ) : ℤ) • constantInclusion (gradedOpen V n k))) :
    Epi (gradedQuotientMap ψ n k q) := by
  have hmι := genSubι_mono ψ n (k + 1)
  have hmιm := mono_genSubι_comp ψ n (k + 1) m
  have he : Epi (factorThruImage (genSubDesc ψ n (k + 1))) := inferInstance
  constructor
  intro T g h hgh
  have hπ : cokernel.π (genSubT ψ n k) ≫ g = cokernel.π (genSubT ψ n k) ≫ h := by
    rw [← cancel_epi (factorThruImage (genSubDesc ψ n (k + 1)))]
    apply biproduct.hom_ext'
    intro j
    by_cases hj : n j.1 ≤ k
    · have hfac : biproduct.ι (fun i : {i : Fin t // n i ≤ k + 1} => extendByZeroConstant (V i.1)) j ≫
          factorThruImage (genSubDesc ψ n (k + 1)) = genSubIn ψ n k j.1 hj ≫ genSubT ψ n k := by
        rw [← cancel_mono (genSubι ψ n (k + 1)), Category.assoc, Category.assoc, genSubT_ι, genSubIn_comp_genSubι]
        exact (Category.assoc _ _ _).symm.trans (genSubIn_comp_genSubι ψ n (k + 1) j.1 j.2)
      have hz : ∀ f : cokernel (genSubT ψ n k) ⟶ T,
          biproduct.ι (fun i : {i : Fin t // n i ≤ k + 1} => extendByZeroConstant (V i.1)) j ≫
            factorThruImage (genSubDesc ψ n (k + 1)) ≫ cokernel.π (genSubT ψ n k) ≫ f = 0 := by
        intro f
        rw [← Category.assoc, hfac, Category.assoc, ← Category.assoc (genSubT ψ n k), cokernel.condition,
          zero_comp, comp_zero]
      rw [hz g, hz h]
    · have hj' : n j.1 = k + 1 := le_antisymm j.2 (Nat.succ_le_of_lt (lt_of_not_ge hj))
      have hfac : biproduct.ι (fun i : {i : Fin t // n i ≤ k + 1} => extendByZeroConstant (V i.1)) j ≫
          factorThruImage (genSubDesc ψ n (k + 1)) = extendByZeroConstantRestrict (le_gradedOpen V n k hj') ≫ q := by
        rw [← cancel_mono (genSubι ψ n (k + 1) ≫ m), Category.assoc, Category.assoc, hq, Preadditive.comp_zsmul,
          extendByZeroConstantRestrict_comp_constantInclusion]
        have h1 : biproduct.ι (fun i : {i : Fin t // n i ≤ k + 1} => extendByZeroConstant (V i.1)) j ≫
            factorThruImage (genSubDesc ψ n (k + 1)) ≫ genSubι ψ n (k + 1) ≫ m = ψ j.1 ≫ m := by
          rw [← Category.assoc]
          exact genSubIn_comp_genSubι_comp ψ n (k + 1) j.1 j.2 m
        rw [h1, hψ, hj']
      have hz : ∀ f : cokernel (genSubT ψ n k) ⟶ T,
          biproduct.ι (fun i : {i : Fin t // n i ≤ k + 1} => extendByZeroConstant (V i.1)) j ≫
            factorThruImage (genSubDesc ψ n (k + 1)) ≫ cokernel.π (genSubT ψ n k) ≫ f =
          extendByZeroConstantRestrict (le_gradedOpen V n k hj') ≫ q ≫ cokernel.π (genSubT ψ n k) ≫ f := by
        intro f
        rw [← Category.assoc, hfac, Category.assoc]
      rw [hz g, hz h]
      have := congrArg (fun f => extendByZeroConstantRestrict (le_gradedOpen V n k hj') ≫ f) hgh
      simp only [gradedQuotientMap, Category.assoc] at this
      exact this
  exact (cancel_epi (cokernel.π (genSubT ψ n k))).mp hπ

end Biproduct

/-- **`ρ ≫ p = 0`**: the restriction `ρ_{W,V} ≫ q` of the section `k+1` to `W` lies in `K_k`
(`exists_gradedSectionLow`: `ρ ≫ q = r ≫ t_k` after cancelling the monomorphism `ι_{k+1} ≫ m`), and
`t_k ≫ cokernel.π t_k = 0`. -/
theorem restrict_comp_gradedQuotientMap [Mono m] (hn : ∀ i, 0 < n i)
    (hψ : ∀ i, ψ i ≫ m = ((n i : ℤ) • constantInclusion (V i)))
    (hgcd : ∀ (x : X) (J : Finset (Fin t)), J.Nonempty → (∀ j ∈ J, x ∈ V j) → ∃ i, x ∈ V i ∧ n i = J.gcd n)
    (q : extendByZeroConstant (gradedOpen V n k) ⟶ genSub ψ n (k + 1))
    (hq : q ≫ genSubι ψ n (k + 1) ≫ m = (((k + 1 : ℕ) : ℤ) • constantInclusion (gradedOpen V n k))) :
    extendByZeroConstantRestrict (gradedOpenInter_le V n k) ≫ gradedQuotientMap ψ n k q = 0 := by
  have hmιm := mono_genSubι_comp ψ n (k + 1) m
  obtain ⟨r, hr⟩ := exists_gradedSectionLow ψ n k m hn hψ hgcd
  have hfac : extendByZeroConstantRestrict (gradedOpenInter_le V n k) ≫ q = r ≫ genSubT ψ n k := by
    rw [← cancel_mono (genSubι ψ n (k + 1) ≫ m), Category.assoc, hq, Preadditive.comp_zsmul,
      extendByZeroConstantRestrict_comp_constantInclusion, Category.assoc r, ← Category.assoc (genSubT ψ n k),
      genSubT_ι, hr]
  unfold gradedQuotientMap
  rw [← Category.assoc, hfac, Category.assoc, cokernel.condition, comp_zero]

/-- `(k+1) • c_V : j_!ℤ_V ⟶ ℤ_X` is a monomorphism (`c_V` is one and `ℤ_X` has no torsion). -/
theorem mono_nsmul_constantInclusion (U : Opens X) (a : ℕ) (ha : a ≠ 0) :
    Mono (((a : ℕ) : ℤ) • constantInclusion U) := by
  have h : ((a : ℕ) : ℤ) • constantInclusion U = constantInclusion U ≫ (((a : ℕ) : ℤ) • 𝟙 _) := by
    rw [Preadditive.comp_zsmul, Category.comp_id]
  rw [h]
  have := constantInclusion_mono U
  have := mono_zsmul_id_constantSheaf (X := X) ((a : ℕ) : ℤ) (Nat.cast_ne_zero.mpr ha)
  exact mono_comp _ _

/-- **`ker p ≅ j_!ℤ_W`**: `kernel.lift p ρ` is an isomorphism, checked on stalks. Injective since
`kernel.lift p ρ ≫ kernel.ι p = ρ` is a monomorphism. Surjective: let `b` be in the stalk of `ker p` at `x`
and `a` its image in the stalk of `j_!ℤ_V` (so `p_x a = 0`). At `x ∈ W` the stalk of `ρ` is an isomorphism, so
`a = ρ_x a'` and `b = (kernel.lift p ρ)_x a'` by injectivity of `(kernel.ι p)_x`. At `x ∉ V` the stalk of `j_!ℤ_V`
is zero, so `a = 0`, so `b = 0`. At `x ∈ V ∖ W` no `V_i` with `n_i ≤ k` contains `x`, so the stalk of `K_k` is zero
(`isZero_stalk_genSub_of_forall_notMem`); exactness of `K_k → K_{k+1} → coker t_k` on stalks gives `q_x a = 0`,
hence `((k+1) • c_V)_x a = 0`, hence `a = 0` since `(k+1) • c_V` is a monomorphism (`ℤ_X` has no torsion). -/
theorem isIso_kernelLift_gradedQuotientMap [Mono m]
    (q : extendByZeroConstant (gradedOpen V n k) ⟶ genSub ψ n (k + 1))
    (hq : q ≫ genSubι ψ n (k + 1) ≫ m = (((k + 1 : ℕ) : ℤ) • constantInclusion (gradedOpen V n k)))
    (hρ : extendByZeroConstantRestrict (gradedOpenInter_le V n k) ≫ gradedQuotientMap ψ n k q = 0) :
    IsIso (kernel.lift (gradedQuotientMap ψ n k q) (extendByZeroConstantRestrict (gradedOpenInter_le V n k)) hρ) := by
  have hmρ := extendByZeroConstantRestrict_mono (gradedOpenInter_le V n k)
  have hmlift : Mono (kernel.lift (gradedQuotientMap ψ n k q) (extendByZeroConstantRestrict (gradedOpenInter_le V n k))
      hρ) := mono_of_mono_fac (kernel.lift_ι _ _ hρ)
  have key : ∀ x : X, IsIso ((stalkFunctor AddCommGrpCat.{u} x).map
      (kernel.lift (gradedQuotientMap ψ n k q) (extendByZeroConstantRestrict (gradedOpenInter_le V n k)) hρ).hom) := by
    intro x
    rw [ConcreteCategory.isIso_iff_bijective]
    have hmκ : Mono (kernel.ι (gradedQuotientMap ψ n k q)) := inferInstance
    have hκ : Function.Injective ((stalkFunctor AddCommGrpCat.{u} x).map (kernel.ι (gradedQuotientMap ψ n k q)).hom) :=
      (AddCommGrpCat.mono_iff_injective _).mp ((mono_iff_stalk_mono _).mp hmκ x)
    have hlifκ : (stalkFunctor AddCommGrpCat.{u} x).map (kernel.lift (gradedQuotientMap ψ n k q)
        (extendByZeroConstantRestrict (gradedOpenInter_le V n k)) hρ).hom ≫
        (stalkFunctor AddCommGrpCat.{u} x).map (kernel.ι (gradedQuotientMap ψ n k q)).hom =
        (stalkFunctor AddCommGrpCat.{u} x).map (extendByZeroConstantRestrict (gradedOpenInter_le V n k)).hom := by
      rw [← CategoryTheory.Functor.map_comp]
      exact congrArg (fun f => (stalkFunctor AddCommGrpCat.{u} x).map f.hom) (kernel.lift_ι _ _ hρ)
    refine ⟨(AddCommGrpCat.mono_iff_injective _).mp ((mono_iff_stalk_mono _).mp hmlift x), fun b => ?_⟩
    by_cases hx : x ∈ gradedOpenInter V n k
    · have hiso := isIso_stalkFunctor_map_extendByZeroConstantRestrict_hom_of_mem (gradedOpenInter_le V n k) x hx
      obtain ⟨a', ha'⟩ := (ConcreteCategory.bijective_of_isIso
        ((stalkFunctor AddCommGrpCat.{u} x).map (extendByZeroConstantRestrict (gradedOpenInter_le V n k)).hom)).2
        ((stalkFunctor AddCommGrpCat.{u} x).map (kernel.ι (gradedQuotientMap ψ n k q)).hom b)
      refine ⟨a', hκ ?_⟩
      rw [← ConcreteCategory.comp_apply, hlifκ]
      exact ha'
    · refine ⟨0, ?_⟩
      rw [map_zero]
      apply hκ
      rw [map_zero]
      -- `a := (kernel.ι p)_x b` satisfies `p_x a = 0`
      have hpa : (stalkFunctor AddCommGrpCat.{u} x).map (gradedQuotientMap ψ n k q).hom
          ((stalkFunctor AddCommGrpCat.{u} x).map (kernel.ι (gradedQuotientMap ψ n k q)).hom b) = 0 := by
        rw [← ConcreteCategory.comp_apply, ← CategoryTheory.Functor.map_comp]
        have h0 : (kernel.ι (gradedQuotientMap ψ n k q)).hom ≫ (gradedQuotientMap ψ n k q).hom = 0 := by
          have := congrArg (fun f => (sheafToPresheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}).map f)
            (kernel.condition (gradedQuotientMap ψ n k q))
          rw [CategoryTheory.Functor.map_zero] at this
          exact this
        rw [h0, CategoryTheory.Functor.map_zero]
        rfl
      by_cases hxV : x ∈ gradedOpen V n k
      · have hnot : ∀ j, n j ≤ k → x ∉ V j := fun j hj hxj =>
          hx ⟨hxV, (mem_gradedOpenLow V n k).mpr ⟨j, hj, hxj⟩⟩
        have hK := isZero_stalk_genSub_of_forall_notMem ψ n k x hnot
        -- exactness of `K_k → K_{k+1} → coker t_k` on stalks
        let S₀ : ShortComplex (TopCat.Sheaf AddCommGrpCat.{u} X) :=
          ShortComplex.mk (genSubT ψ n k) (cokernel.π (genSubT ψ n k)) (cokernel.condition _)
        have hS₀ : S₀.Exact := ShortComplex.exact_of_g_is_cokernel S₀ (cokernelIsCokernel _)
        have hS₀x := (ShortComplex.ab_exact_iff _).mp ((exact_iff_stalkFunctor_map_exact S₀).mp hS₀ x)
        have hqa : (stalkFunctor AddCommGrpCat.{u} x).map q.hom
            ((stalkFunctor AddCommGrpCat.{u} x).map (kernel.ι (gradedQuotientMap ψ n k q)).hom b) = 0 := by
          obtain ⟨z, hz⟩ := hS₀x ((stalkFunctor AddCommGrpCat.{u} x).map q.hom
            ((stalkFunctor AddCommGrpCat.{u} x).map (kernel.ι (gradedQuotientMap ψ n k q)).hom b)) (by
              change (stalkFunctor AddCommGrpCat.{u} x).map (cokernel.π (genSubT ψ n k)).hom
                ((stalkFunctor AddCommGrpCat.{u} x).map q.hom _) = 0
              rw [← ConcreteCategory.comp_apply, ← CategoryTheory.Functor.map_comp]
              exact hpa)
          have hz0 : z = 0 := (AddCommGrpCat.isZero_iff_subsingleton.mp hK).elim z 0
          rw [← hz, hz0]
          exact map_zero _
        have hc : (stalkFunctor AddCommGrpCat.{u} x).map ((((k + 1 : ℕ) : ℤ) • constantInclusion (gradedOpen V n k)).hom)
            ((stalkFunctor AddCommGrpCat.{u} x).map (kernel.ι (gradedQuotientMap ψ n k q)).hom b) = 0 := by
          rw [← hq]
          change (stalkFunctor AddCommGrpCat.{u} x).map (q.hom ≫ (genSubι ψ n (k + 1) ≫ m).hom) _ = 0
          rw [CategoryTheory.Functor.map_comp, ConcreteCategory.comp_apply, hqa, map_zero]
        have hmono := mono_nsmul_constantInclusion (gradedOpen V n k) (k + 1) (Nat.succ_ne_zero k)
        apply (AddCommGrpCat.mono_iff_injective _).mp ((mono_iff_stalk_mono _).mp hmono x)
        rw [map_zero]
        exact hc.symm
      · exact (AddCommGrpCat.isZero_iff_subsingleton.mp
          (isZero_stalk_extendByZeroConstant_of_notMem (gradedOpen V n k) x hxV)).elim _ _
  exact isIso_of_stalkFunctor_map_iso _

end Aux

/-- **Short exactness of the graded pieces** (Stacks 0A38, proof, paragraph 3). Let `X` be
quasi-separated, `m : K ⟶ ℤ_X` a monomorphism, and `(V_i, n_i, ψ_i)_{i : Fin t}` a list of constant positive
generators of `K`: `V_i` quasi-compact, `n_i > 0`, `ψ_i : j_!ℤ_{V_i} ⟶ K` with `ψ_i ≫ m = n_i • c_i` where
`c_i := constantInclusion (V i) : j_!ℤ_{V_i} ⟶ ℤ_X` is the canonical inclusion, and gcd-closed (`hgcd`).
Let `K_k := genSub ψ n k` be the subsheaf generated by the `ψ_i` with `n_i ≤ k`, and `t_k : K_k ⟶ K_{k+1}` the
inclusion (`genSubT`). Then for every `k` there are quasi-compact opens `V`, `W` and a short exact sequence
`0 → j_!ℤ_W → j_!ℤ_V → coker t_k → 0`.

**Natural-language proof (self-contained, following Stacks 0A38; stalkwise).** Everything is a subsheaf of
`ℤ_X` via `m`, and the stalk of `ℤ_X` at `x` is `ℤ`. For `x ∈ X` write `I_x := {i : x ∈ V_i}` and
`d_k(x) := gcd(n_i : i ∈ I_x, n_i ≤ k)` (`0` if there is no such `i`).

*Step 1 (stalks of `K_k`).* `(K_k)_x = d_k(x) ℤ ⊆ ℤ`: `K_k` is the image of `⨁_{n_i ≤ k} j_!ℤ_{V_i} ⟶ K ⊆ ℤ_X`;
the stalk functor is exact on abelian sheaves and commutes with finite direct sums, `(j_!ℤ_{V_i})_x = ℤ` if
`x ∈ V_i` and `0` otherwise (`extendByZero_stalk_of_mem`, `isZero_extendByZero_stalk_of_notMem`), and the
stalk of `ψ_i ≫ m = n_i • c_i` at `x ∈ V_i` is multiplication by `n_i` (the stalk of `c_i` at `x ∈ V_i` is the
identity of `ℤ` under the canonical identifications, from `constantInclusion_comp_restrictUnit`: `c_i ≫ η = ε`
and the stalk of `ε` at `x ∈ V_i` is the canonical isomorphism). So `(K_k)_x` is the subgroup generated by the `n_i`, `i ∈ I_x`,
`n_i ≤ k`, i.e. `d_k(x) ℤ`.

*Step 2 (the gcd property).* By `hgcd` applied to `J := {i ∈ I_x : n_i ≤ k}` (when nonempty), `d_k(x) = n_i`
for some `i ∈ I_x`; in particular `d_k(x) ≤ k` when `d_k(x) ≠ 0`. Consequence: if `x ∈ V_j` for some `n_j ≤ k`
(so `d_k(x) ≠ 0`) then `d_k(x) ∣ k + 1` whenever also `x ∈ V_i` for some `n_i = k + 1`: indeed
`d_{k+1}(x) = gcd(d_k(x), k+1)` is attained by some `n_l`, `l ∈ I_x`; if `d_{k+1}(x) < d_k(x)` then
`n_l = d_{k+1}(x) < d_k(x) ≤ k`, so `l` is among the indices defining `d_k(x)` and `d_k(x) ∣ n_l`, impossible for
`0 < n_l < d_k(x)`. Hence `d_{k+1}(x) = d_k(x)` and `d_k(x) ∣ k + 1`.

*Step 3 (the opens).* `V := ⋃_{n_i = k+1} V_i` and `W := V ∩ ⋃_{n_i ≤ k} V_i`; both are quasi-compact (finite
unions of quasi-compact opens; `W` by quasi-separatedness, `QuasiSeparatedSpace.inter_isCompact`).

*Step 4 (the map `p : j_!ℤ_V ⟶ coker t_k`).* The constant section `k+1` over `V` lies in `K_{k+1}(V)`: for
`x ∈ V`, `d_{k+1}(x) ∣ k+1` (`d_{k+1}(x)` divides `n_i = k+1` for the `i` with `x ∈ V_i`), and a section of `ℤ_X`
lies in a subsheaf iff its germs do. Concretely, `(k+1) • c_V : j_!ℤ_V ⟶ ℤ_X` factors through
`m ∘ genSubι ψ n (k+1)` (both monomorphisms; the factorisation exists because `K_{k+1}` is the image of the
biproduct map and, locally on `V`, the section `k+1` is a ℤ-combination of the generators `n_i` over
`V_i ∋ x`, by Bézout with `d_{k+1}(x) ∣ k+1`). Let `q : j_!ℤ_V ⟶ K_{k+1}` be the factorisation and
`p := q ≫ cokernel.π t_k`.

*Step 5 (stalks of `coker t_k` and of `p`).* Stalks are exact, so `(coker t_k)_x = d_{k+1}(x)ℤ / d_k(x)ℤ`.
For `x ∉ V`: `d_{k+1}(x) = d_k(x)` (no `n_i = k+1` with `x ∈ V_i`), so the stalk is `0`. For `x ∈ W`:
`d_{k+1}(x) = d_k(x)` by Step 2, stalk `0`. For `x ∈ V \ W`: `d_k(x) = 0` and `d_{k+1}(x) = k+1`, stalk
`(k+1)ℤ ≅ ℤ`, and `p_x : ℤ → (k+1)ℤ/0` is `1 ↦ k+1`, an isomorphism. Hence `p` is an epimorphism (surjective on
all stalks) and its kernel has stalk `ℤ` at `x ∈ W` (all of `(j_!ℤ_V)_x`) and `0` elsewhere.

*Step 6 (the kernel is `j_!ℤ_W`).* The canonical map `ρ : j_!ℤ_W ⟶ j_!ℤ_V` (`ρ ≫ c_V = c_W`) satisfies
`ρ ≫ p = 0`: `ρ ≫ q` lands in `K_k` since the constant section `k+1` over `W` lies in `K_k(W)` (for `x ∈ W`,
`d_k(x) ∣ k+1` by Step 2), so `ρ ≫ q ≫ cokernel.π t_k = 0`. The induced map `j_!ℤ_W ⟶ ker p` is an isomorphism
on every stalk (`ℤ → ℤ` the identity for `x ∈ W`, `0 → 0` otherwise), hence an isomorphism
(`TopCat.Presheaf.isIso_of_stalkFunctor_map_iso`). Therefore `S := (j_!ℤ_W ⟶ j_!ℤ_V ⟶ coker t_k)` with
`ρ` and `p` is short exact (`ρ` mono, `p` epi, exactness at the middle since `ρ` is the kernel of `p`), and
`S.X₁ = j_!ℤ_W`, `S.X₂ = j_!ℤ_V`, `S.X₃ = coker t_k`.

*Edge cases.* If no `n_i = k+1` then `V = W = ∅`, `j_!ℤ_∅ = 0`, `t_k` is an isomorphism (`K_{k+1} = K_k`), the
cokernel is `0`, and `0 → 0 → 0` is short exact. `t = 0`: all `K_k = 0`, same. `X = ∅`: all sheaves are zero.

**Library facts used**: stalks of `extendByZero` (`ExtendByZeroStalk.lean`), exactness of the stalk functor
on `Sheaf (Opens.grothendieckTopology X) AddCommGrpCat` (kernels, cokernels, images, finite biproducts),
the stalk of the constant sheaf `ℤ_X` (`ℤ`), the canonical maps `ρ : j_!ℤ_W ⟶ j_!ℤ_V`, and "a section of
`ℤ_X` lies in a subsheaf iff all its germs do". -/
theorem exists_shortExact_genSub_quotient [QuasiSeparatedSpace X]
    (K : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u})
    (m : K ⟶ (CategoryTheory.constantSheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}).obj
      (AddCommGrpCat.of (ULift ℤ))) [CategoryTheory.Mono m]
    {t : ℕ} (V : Fin t → Opens X) (hV : ∀ i, IsCompact ((V i : Opens X) : Set X))
    (n : Fin t → ℕ) (hn : ∀ i, 0 < n i) (ψ : ∀ i, extendByZeroConstant (V i) ⟶ K)
    (hψ : ∀ i, ψ i ≫ m = ((n i : ℤ) • constantInclusion (V i)))
    (hgcd : ∀ (x : X) (J : Finset (Fin t)), J.Nonempty → (∀ j ∈ J, x ∈ V j) →
      ∃ i, x ∈ V i ∧ n i = J.gcd n)
    (k : ℕ) :
    ∃ (V' W' : Opens X), IsCompact (V' : Set X) ∧ IsCompact (W' : Set X) ∧
      ∃ S : CategoryTheory.ShortComplex
          (CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}),
        S.ShortExact ∧
        Nonempty (S.X₁ ≅ extendByZeroConstant W') ∧
        Nonempty (S.X₂ ≅ extendByZeroConstant V') ∧
        Nonempty (S.X₃ ≅ CategoryTheory.Limits.cokernel (genSubT ψ n k)) := by
  obtain ⟨q, hq⟩ := exists_gradedSection ψ n k m hψ
  have hρ := restrict_comp_gradedQuotientMap ψ n k m hn hψ hgcd q hq
  have hepi := epi_gradedQuotientMap ψ n k m hψ q hq
  have hiso := isIso_kernelLift_gradedQuotientMap ψ n k m q hq hρ
  refine ⟨gradedOpen V n k, gradedOpenInter V n k, isCompact_gradedOpen V n k hV,
    isCompact_gradedOpenInter V n k hV,
    ShortComplex.mk (kernel.ι (gradedQuotientMap ψ n k q)) (gradedQuotientMap ψ n k q) (kernel.condition _),
    ?_, ⟨(asIso (kernel.lift (gradedQuotientMap ψ n k q) _ hρ)).symm⟩, ⟨Iso.refl _⟩, ⟨Iso.refl _⟩⟩
  exact { exact := ShortComplex.exact_of_f_is_kernel _ (kernelIsKernel (gradedQuotientMap ψ n k q))
          mono_f := inferInstance
          epi_g := hepi }

end TopCat.Sheaf

end
