import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Cohomology.ConstantSheaf.Stacks0a38ConstantInclusion
import MiyaokaMori.AlgebraicGeometry.Cohomology.ConstantSheaf.ConstantSheafSectionLevelSets
import MiyaokaMori.Algebra.Stacks0a38ConstantGenerators_Bezout

/-! # Gcd-closed constant generators of a subsheaf of `ℤ_X` (Stacks 0A38)

Stacks 0A38, first two paragraphs of the proof: a subsheaf `K ⊆ ℤ_X` generated by finitely many sections over
quasi-compact opens (on a space where two quasi-compact opens meet in a quasi-compact open) is generated by
finitely many **constant positive** sections `n_i ∈ ℤ_{>0}` over quasi-compact opens `V_i`, and the list can be
taken **gcd-closed**: for every `x ∈ X` and every nonempty set `J` of indices with `x ∈ V_j` for all `j ∈ J`,
`gcd(n_j, j ∈ J)` is one of the `n_i` with `x ∈ V_i`.

Ingredients:
* `ConstantSheafSections.lean`: sections of `ℤ_T` (`constSec`, local constancy, injectivity);
* `ExtendByZeroConstantUnitSection.lean`: constant sections of `j_!ℤ_U`, hom-extensionality on the unit
  section, the canonical maps `ρ_{W,U} : j_!ℤ_W ⟶ j_!ℤ_U` (`restrictExtend`), joint epimorphicity of a cover;
* `ConstantInclusionUnitSection.lean`: `constantInclusion_unitSection` (`c_U` sends the unit section to
  `1 ∈ ℤ_X(U)`) and its consequences (`ρ_{W,U} ≫ c_U = c_W`, `(n • c_V)_V(e_V) = n`);
* `ConstantSheafSectionLevelSets.lean`: paragraph 1 (level sets of a section over a quasi-compact open);
* `Finset.gcd` bookkeeping for paragraph 2.
Here: `exists_constant_generators` (paragraph 1 for all generators at once: drop the value `0`, make the values
positive), `exists_gcdClosed_of_constant_generators` (paragraph 2: add `(⋂_{j ∈ J} V_j, gcd_J n, Σ a_j ρ_j ψ_j)` for
every nonempty `J`), and the target `exists_gcdClosed_constant_generators` (reindex by `Fin t`).

Source: Stacks 0A38 (cohomology-lemma-subsheaf-of-constant-sheaf), proof, paragraphs 1–2. -/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace

noncomputable section

namespace TopCat.Sheaf

variable {X : TopCat.{u}}

/-- **Paragraph 1 of Stacks 0A38** for a jointly epimorphic family `φ_a : j_!ℤ_{U_a} ⟶ K`, `U_a` quasi-compact:
`K` is generated by constant *positive* sections over quasi-compact opens. Apply `exists_levelSets` to each
`φ_a ≫ m`, drop the level sets with value `0` (they give the zero morphism since `m` is a monomorphism), and
replace `(L, z, ρ ≫ φ_a)` by `(L, |z|, sign z • (ρ ≫ φ_a))`. -/
theorem exists_constant_generators
    (K : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u})
    (m : K ⟶ (CategoryTheory.constantSheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}).obj
      (AddCommGrpCat.of (ULift ℤ))) [CategoryTheory.Mono m]
    {r : ℕ} (U : Fin r → Opens X) (hU : ∀ a, IsCompact ((U a : Opens X) : Set X))
    (φ : ∀ a, extendByZeroConstant (U a) ⟶ K) (hgen : IsJointlyEpi φ) :
    ∃ (κ : Type u) (_ : Fintype κ) (V : κ → Opens X) (n : κ → ℕ) (ψ : ∀ i, extendByZeroConstant (V i) ⟶ K),
      (∀ i, IsCompact ((V i : Opens X) : Set X)) ∧ (∀ i, 0 < n i) ∧ IsJointlyEpi ψ ∧
      (∀ i, ψ i ≫ m = ((n i : ℤ) • constantInclusion (V i))) := by
  classical
  have hlev := fun a : Fin r => exists_levelSets (U a) (hU a) (φ a ≫ m)
  choose ι hι L hL z hLc hLcov hLf using hlev
  let _ : ∀ a, Fintype (ι a) := hι
  -- sign bookkeeping
  have hsign : ∀ w : ℤ, w ≠ 0 → Int.sign w * Int.sign w = 1 := by
    intro w hw
    rcases lt_trichotomy w 0 with h | h | h
    · rw [Int.sign_eq_neg_one_of_neg h]; norm_num
    · exact absurd h hw
    · rw [Int.sign_eq_one_of_pos h]; norm_num
  refine ⟨{p : Σ a, ι a // z p.1 p.2 ≠ 0}, inferInstance, fun p => L p.1.1 p.1.2, fun p => (z p.1.1 p.1.2).natAbs,
    fun p => Int.sign (z p.1.1 p.1.2) • (restrictExtend (U p.1.1) (hL p.1.1 p.1.2) ≫ φ p.1.1),
    fun p => hLc _ _, fun p => Int.natAbs_pos.2 p.2, ?_, fun p => ?_⟩
  · -- jointly epimorphic
    intro T g h hgh
    apply hgen
    intro a
    apply isJointlyEpi_restrictExtend (U a) (L a) (hL a) (hLcov a)
    intro i
    by_cases hz : z a i = 0
    · have h0 : restrictExtend (U a) (hL a i) ≫ φ a = 0 := by
        rw [← cancel_mono m, Category.assoc, hLf a i, hz, zero_smul, zero_comp]
      show restrictExtend (U a) (hL a i) ≫ (φ a ≫ g) = restrictExtend (U a) (hL a i) ≫ (φ a ≫ h)
      rw [← Category.assoc, ← Category.assoc, h0, zero_comp, zero_comp]
    · have h1 := hgh ⟨⟨a, i⟩, hz⟩
      simp only [Preadditive.zsmul_comp] at h1
      have h2 := congrArg (fun x => Int.sign (z a i) • x) h1
      simp only [smul_smul, hsign _ hz, one_smul] at h2
      simpa only [Category.assoc] using h2
  · -- `ψ ≫ m = |z| • c`
    rw [Preadditive.zsmul_comp, Category.assoc, hLf, smul_smul, Int.sign_mul_self_eq_natAbs]

/-- **Paragraph 2 of Stacks 0A38 (gcd-closure)**. Given constant positive generators `(V_i, n_i, ψ_i)`, `i : κ`,
the family indexed by `κ ⊕ {J : Finset κ // J.Nonempty}` — the old generators together with, for every nonempty
`J`, `(⋂_{j ∈ J} V_j, gcd_{j ∈ J} n_j, ∑_{j ∈ J} a_j • (ρ_{V_J, V_j} ≫ ψ_j))` with `∑ a_j n_j = gcd_J n`
(Bézout) — is again a family of constant positive generators over quasi-compact opens (quasi-separatedness for
the intersections), and it is gcd-closed: for `x ∈ X` and a nonempty set `J'` of new indices with `x ∈ V'_p` for
all `p ∈ J'`, the union `K` of the underlying index sets has `x ∈ V_K` and `n_K = gcd_{p ∈ J'} n'_p`
(`Finset.gcd_biUnion_eq_gcd_gcd`). -/
theorem exists_gcdClosed_of_constant_generators [QuasiSeparatedSpace X]
    (K : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u})
    (m : K ⟶ (CategoryTheory.constantSheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}).obj
      (AddCommGrpCat.of (ULift ℤ)))
    {κ : Type u} [Fintype κ] (V : κ → Opens X) (n : κ → ℕ) (ψ : ∀ i, extendByZeroConstant (V i) ⟶ K)
    (hV : ∀ i, IsCompact ((V i : Opens X) : Set X)) (hn : ∀ i, 0 < n i) (hgen : IsJointlyEpi ψ)
    (hψ : ∀ i, ψ i ≫ m = ((n i : ℤ) • constantInclusion (V i))) :
    ∃ (κ' : Type u) (_ : Fintype κ') (V' : κ' → Opens X) (n' : κ' → ℕ)
      (ψ' : ∀ i, extendByZeroConstant (V' i) ⟶ K),
      (∀ i, IsCompact ((V' i : Opens X) : Set X)) ∧ (∀ i, 0 < n' i) ∧ IsJointlyEpi ψ' ∧
      (∀ i, ψ' i ≫ m = ((n' i : ℤ) • constantInclusion (V' i))) ∧
      (∀ (x : X) (J : Finset κ'), J.Nonempty → (∀ j ∈ J, x ∈ V' j) → ∃ i, x ∈ V' i ∧ n' i = J.gcd n') := by
  classical
  -- finite intersections of quasi-compact opens are quasi-compact (quasi-separatedness)
  have hinf : ∀ J : Finset κ, J.Nonempty → IsCompact ((J.inf V : Opens X) : Set X) := by
    intro J
    induction J using Finset.induction_on with
    | empty => intro h; exact absurd h Finset.not_nonempty_empty
    | insert i J hi ih =>
      intro _
      rw [Finset.inf_insert]
      by_cases hJ : J.Nonempty
      · rw [Opens.coe_inf]
        exact QuasiSeparatedSpace.inter_isCompact _ _ (V i).isOpen (hV i) (J.inf V).isOpen (ih hJ)
      · rw [Finset.not_nonempty_iff_eq_empty] at hJ
        subst hJ
        rw [Finset.inf_empty, inf_top_eq]
        exact hV i
  -- Bézout coefficients
  choose a ha using fun J : Finset κ => Finset.exists_int_sum_mul_eq_gcd J n
  -- the new family
  let V' : κ ⊕ {J : Finset κ // J.Nonempty} → Opens X := Sum.elim V (fun J => J.1.inf V)
  let n' : κ ⊕ {J : Finset κ // J.Nonempty} → ℕ := Sum.elim n (fun J => J.1.gcd n)
  let ψ' : ∀ p, extendByZeroConstant (V' p) ⟶ K := fun p =>
    match p with
    | Sum.inl i => ψ i
    | Sum.inr J => ∑ j ∈ J.1.attach, a J.1 j.1 • (restrictExtend (V j.1) (Finset.inf_le j.2) ≫ ψ j.1)
  -- the index set underlying a new index
  let under : κ ⊕ {J : Finset κ // J.Nonempty} → Finset κ := Sum.elim (fun i => {i}) (fun J => J.1)
  have hunder_ne : ∀ p, (under p).Nonempty := by
    rintro (i | J)
    · exact Finset.singleton_nonempty i
    · exact J.2
  have hV'_le : ∀ p, ∀ k ∈ under p, V' p ≤ V k := by
    rintro (i | J) k hk
    · rw [Finset.mem_singleton.1 hk]
      exact le_rfl
    · exact Finset.inf_le hk
  have hn'_gcd : ∀ p, (under p).gcd n = n' p := by
    rintro (i | J)
    · exact (Finset.gcd_singleton).trans (normalize_eq _)
    · rfl
  refine ⟨κ ⊕ {J : Finset κ // J.Nonempty}, inferInstance, V', n', ψ', ?_, ?_, ?_, ?_, ?_⟩
  · rintro (i | J)
    · exact hV i
    · exact hinf J.1 J.2
  · rintro (i | J)
    · exact hn i
    · exact Finset.gcd_pos_of_forall_pos J.2 fun j _ => hn j
  · intro T g h hgh
    apply hgen
    intro i
    exact hgh (Sum.inl i)
  · rintro (i | J)
    · exact hψ i
    · show (∑ j ∈ J.1.attach, a J.1 j.1 • (restrictExtend (V j.1) (Finset.inf_le j.2) ≫ ψ j.1)) ≫ m =
        ((J.1.gcd n : ℕ) : ℤ) • constantInclusion (J.1.inf V)
      rw [Preadditive.sum_comp, ← ha J.1, ← Finset.sum_attach J.1 (fun j => a J.1 j * (n j : ℤ)), Finset.sum_smul]
      refine Finset.sum_congr rfl fun j _ => ?_
      rw [Preadditive.zsmul_comp, Category.assoc, hψ, Preadditive.comp_zsmul, restrictExtend_comp_constantInclusion,
        smul_smul]
  · intro x J' hJ' hxJ'
    have hKne : (J'.biUnion under).Nonempty := by
      obtain ⟨p, hp⟩ := hJ'
      exact Finset.biUnion_nonempty.2 ⟨p, hp, hunder_ne p⟩
    refine ⟨Sum.inr ⟨J'.biUnion under, hKne⟩, ?_, ?_⟩
    · show x ∈ (J'.biUnion under).inf V
      rw [mem_finset_inf_iff]
      intro k hk
      obtain ⟨p, hp, hkp⟩ := Finset.mem_biUnion.1 hk
      exact hV'_le p k hkp (hxJ' p hp)
    · show (J'.biUnion under).gcd n = J'.gcd n'
      rw [Finset.gcd_biUnion_eq_gcd_gcd]
      exact Finset.gcd_congr rfl fun p _ => hn'_gcd p

/-- **Gcd-closed constant generators** (Stacks 0A38, proof, paragraphs 1–2). Let `X` be
quasi-separated, `m : K ⟶ ℤ_X` a monomorphism, and `φ_a : j_!ℤ_{U_a} ⟶ K` (`a : Fin r`) a jointly epimorphic
family with `U_a` quasi-compact ("`K` is generated by the sections `φ_a` over `U_a`"). Write
`c V := constantInclusion V : j_!ℤ_V ⟶ ℤ_X` for the canonical inclusions. Then there are `t`,
quasi-compact opens `V_i`, positive integers `n_i` and morphisms `ψ_i : j_!ℤ_{V_i} ⟶ K` (`i : Fin t`) such that
* the `ψ_i` are jointly epimorphic (they generate `K`);
* `ψ_i ≫ m = n_i • c (V_i)` (`ψ_i` is the constant section `n_i` over `V_i`, viewed in `K ⊆ ℤ_X`);
* gcd-closure: for every `x : X` and nonempty `J : Finset (Fin t)` with `x ∈ V_j` for all `j ∈ J`, there is `i`
  with `x ∈ V_i` and `n_i = gcd_{j ∈ J} n_j`.

**Proof.** `exists_constant_generators` (paragraph 1) followed by
`exists_gcdClosed_of_constant_generators` (paragraph 2), then reindexing along `Fintype.equivFin`
(`Finset.gcd_image` for the gcd-closure).

*Edge cases.* `r = 0` (`K = 0`): the family produced is empty (`t = 0`); all conditions are vacuous (a nonempty
`J : Finset (Fin 0)` does not exist). `U_a = ∅`: `j_!ℤ_∅ = 0`, the level set has value `0` and is dropped.
`X = ∅`: everything is zero. -/
theorem exists_gcdClosed_constant_generators [QuasiSeparatedSpace X]
    (K : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u})
    (m : K ⟶ (CategoryTheory.constantSheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}).obj
      (AddCommGrpCat.of (ULift ℤ))) [CategoryTheory.Mono m]
    {r : ℕ} (U : Fin r → Opens X) (hU : ∀ a, IsCompact ((U a : Opens X) : Set X))
    (φ : ∀ a, extendByZeroConstant (U a) ⟶ K) (hgen : IsJointlyEpi φ) :
    ∃ (t : ℕ) (V : Fin t → Opens X) (n : Fin t → ℕ) (ψ : ∀ i, extendByZeroConstant (V i) ⟶ K),
      (∀ i, IsCompact ((V i : Opens X) : Set X)) ∧ (∀ i, 0 < n i) ∧ IsJointlyEpi ψ ∧
      (∀ i, ψ i ≫ m = ((n i : ℤ) • constantInclusion (V i))) ∧
      (∀ (x : X) (J : Finset (Fin t)), J.Nonempty → (∀ j ∈ J, x ∈ V j) →
        ∃ i, x ∈ V i ∧ n i = J.gcd n) := by
  classical
  obtain ⟨κ, _, V, n, ψ, hV, hn, hgen', hψ⟩ := exists_constant_generators K m U hU φ hgen
  obtain ⟨κ', _, V', n', ψ', hV', hn', hgen'', hψ', hgcd⟩ :=
    exists_gcdClosed_of_constant_generators K m V n ψ hV hn hgen' hψ
  let e := Fintype.equivFin κ'
  refine ⟨Fintype.card κ', fun i => V' (e.symm i), fun i => n' (e.symm i), fun i => ψ' (e.symm i),
    fun i => hV' _, fun i => hn' _, ?_, fun i => hψ' _, ?_⟩
  · intro T g h hgh
    apply hgen''
    intro i
    obtain ⟨j, rfl⟩ := e.symm.surjective i
    exact hgh j
  · intro x J hJ hxJ
    obtain ⟨i', hxi', hni'⟩ := hgcd x (J.image e.symm) (hJ.image _) (by
      intro p hp
      obtain ⟨j, hj, rfl⟩ := Finset.mem_image.1 hp
      exact hxJ j hj)
    refine ⟨e i', ?_, ?_⟩
    · show x ∈ V' (e.symm (e i'))
      rw [Equiv.symm_apply_apply]
      exact hxi'
    · show n' (e.symm (e i')) = J.gcd (fun i => n' (e.symm i))
      rw [Equiv.symm_apply_apply, hni', Finset.gcd_image]
      rfl

end TopCat.Sheaf

end
