import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Cohomology.ConstantSheaf.Stacks0a38GenSub
import MiyaokaMori.AlgebraicGeometry.Cohomology.ConstantSheaf.Stacks0a38ConstantGenerators
import MiyaokaMori.AlgebraicGeometry.Cohomology.ConstantSheaf.Stacks0a38GradedPiece

/-! # Filtration of a finitely generated subsheaf of the constant sheaf (Stacks 0A38)

Stacks 0A38: on a space in which the intersection of two quasi-compact opens is quasi-compact, a subsheaf
`K ⊆ ℤ_X` generated by finitely many sections over quasi-compact opens has a finite filtration whose
successive quotients sit in short exact sequences `0 → j′_!ℤ_W → j_!ℤ_V → quotient → 0` (`V`, `W`
quasi-compact opens).

Source: Stacks 0A38 (cohomology-lemma-subsheaf-of-constant-sheaf); Tohoku p. 168.

The proof of `TopCat.Sheaf.exists_filtration_subsheaf_constant` is the Stacks 0A38 argument split as
follows.
1. `exists_gcdClosed_constant_generators` (`Stacks0a38ConstantGenerators.lean`): paragraphs 1–2 of the
   Stacks proof — the generators can be taken to be constant positive sections `n_i • c_{V_i}` over
   quasi-compact opens `V_i` (`c_V = constantInclusion V : j_!ℤ_V ⟶ ℤ_X` the canonical inclusion,
   `Stacks0a38ConstantInclusion.lean`), and the list can be taken gcd-closed. This is where
   quasi-separatedness and quasi-compactness of the `U_a` are used.
2. `Stacks0a38GenSub.lean`: `K_k := genSub ψ n k`, the subsheaf generated by the `ψ_i` with `n_i ≤ k`
   (image of `⨁_{n_i ≤ k} j_!ℤ_{V_i} ⟶ K`), with `genSubι : K_k ↪ K`, `genSubT : K_k ⟶ K_{k+1}`,
   `K_0 = 0` (all `n_i > 0`) and `K_N = K` for `N = max n_i` (the `ψ_i` generate `K`).
3. `exists_shortExact_genSub_quotient` (`Stacks0a38GradedPiece.lean`): paragraph 3 of the Stacks proof —
   `0 → j_!ℤ_W → j_!ℤ_V → K_{k+1}/K_k → 0` with `V = ⋃_{n_i = k+1} V_i`, `W = V ∩ ⋃_{n_i ≤ k} V_i`
   (stalkwise, using the gcd property).
The filtration of the statement is `Fil k := K_k`, `ι k := genSubι`, `t k := genSubT`, `n := N`. -/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u v w u' v'

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open scoped AlgebraicGeometry

noncomputable section

/-- Stacks 0A38: `X` quasi-separated (the intersection of two quasi-compact opens is quasi-compact),
`K ⊆ ℤ_X` (`m` a monomorphism) generated by finitely many sections over quasi-compact opens `U_a`
(a section `s_a ∈ K(U_a)` is a morphism `φ_a : j_{a!}ℤ_{U_a} ⟶ K`; generation means the `φ_a` are jointly
epimorphic, `hgen`, written without coproducts). Then `K` has a finite filtration: subsheaves
`ι_i : K_i ↪ K` with inclusions `t_i : K_i ⟶ K_{i+1}` (`t_i ≫ ι_{i+1} = ι_i`), `K_0 = 0`, `K_n ≅ K` (`ι_n` an
isomorphism), and every successive quotient `K_{i+1}/K_i = coker t_i` sits in a short exact sequence
`0 → j′_!ℤ_W → j_!ℤ_V → K_{i+1}/K_i → 0` (`V`, `W` quasi-compact opens). -/

theorem TopCat.Sheaf.exists_filtration_subsheaf_constant {X : TopCat.{u}} [QuasiSeparatedSpace X]
    (K : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u})
    (m : K ⟶ (CategoryTheory.constantSheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}).obj
      (AddCommGrpCat.of (ULift ℤ))) [CategoryTheory.Mono m]
    {r : ℕ} (U : Fin r → TopologicalSpace.Opens X) (hU : ∀ a, IsCompact ((U a : TopologicalSpace.Opens X) : Set X))
    (φ : ∀ a, TopCat.Sheaf.extendByZero (U a)
      ((CategoryTheory.constantSheaf (Opens.grothendieckTopology (U a)) AddCommGrpCat.{u}).obj
        (AddCommGrpCat.of (ULift ℤ))) ⟶ K)
    (hgen : ∀ {T : CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}} (g h : K ⟶ T),
      (∀ a, φ a ≫ g = φ a ≫ h) → g = h) :
    ∃ (n : ℕ) (Fil : ℕ → CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u})
      (ι : ∀ i, Fil i ⟶ K) (t : ∀ i, Fil i ⟶ Fil (i + 1)),
      (∀ i, CategoryTheory.Mono (ι i)) ∧ (∀ i, t i ≫ ι (i + 1) = ι i) ∧
      CategoryTheory.Limits.IsZero (Fil 0) ∧ CategoryTheory.IsIso (ι n) ∧
      ∀ i, i < n →
        ∃ (V W : TopologicalSpace.Opens X), IsCompact (V : Set X) ∧ IsCompact (W : Set X) ∧
          ∃ S : CategoryTheory.ShortComplex
              (CategoryTheory.Sheaf (Opens.grothendieckTopology X) AddCommGrpCat.{u}),
            S.ShortExact ∧
            Nonempty (S.X₁ ≅ TopCat.Sheaf.extendByZero W
              ((CategoryTheory.constantSheaf (Opens.grothendieckTopology W) AddCommGrpCat.{u}).obj
                (AddCommGrpCat.of (ULift ℤ)))) ∧
            Nonempty (S.X₂ ≅ TopCat.Sheaf.extendByZero V
              ((CategoryTheory.constantSheaf (Opens.grothendieckTopology V) AddCommGrpCat.{u}).obj
                (AddCommGrpCat.of (ULift ℤ)))) ∧
            Nonempty (S.X₃ ≅ CategoryTheory.Limits.cokernel (t i)) := by
  -- Step 1: gcd-closed constant positive generators (Stacks 0A38, paragraphs 1–2)
  obtain ⟨t, V, n, ψ, hV, hn, hψgen, hψ, hgcd⟩ :=
    TopCat.Sheaf.exists_gcdClosed_constant_generators K m U hU φ hgen
  -- Step 2: the filtration `K_k = ⟨ψ_i : n_i ≤ k⟩`, `N = max n_i`
  let N : ℕ := Finset.univ.sup n
  have hN : ∀ i, n i ≤ N := fun i => Finset.le_sup (f := n) (Finset.mem_univ i)
  refine ⟨N, TopCat.Sheaf.genSub ψ n, TopCat.Sheaf.genSubι ψ n, TopCat.Sheaf.genSubT ψ n,
    TopCat.Sheaf.genSubι_mono ψ n, TopCat.Sheaf.genSubT_ι ψ n, TopCat.Sheaf.isZero_genSub_zero ψ n hn,
    TopCat.Sheaf.isIso_genSubι_of_le ψ hψgen n N hN, fun k _ => ?_⟩
  -- Step 3: the graded pieces (Stacks 0A38, paragraph 3)
  exact TopCat.Sheaf.exists_shortExact_genSub_quotient K m V hV n hn ψ hψ hgcd k

end
