import MiyaokaMori.Prelude
import MiyaokaMori.AlgebraicGeometry.Modules.LineBundle.IsLineBundle
import MiyaokaMori.AlgebraicGeometry.Modules.LocallyFree.ModuleSheafFrame

/-! # Local frames of line bundles

A **frame** of a sheaf of modules `M` on an open `W` is a section `e ∈ Γ(M, W)` such that for every
open `W' ⊆ W` the map `r ↦ r • e|_{W'}` is a bijection `Γ(X, W') → Γ(M, W')` (`IsFrame`). A line
bundle has a frame near every point (`exists_frame`, `exists_frame_le`). A frame gives
**coordinates**: `hf.coordEquiv h : Γ(M, W') ≃ₗ[Γ(X, W')] Γ(X, W')` with `coord x • e|_{W'} = x`,
uniqueness, and compatibility with restriction (`coord_map`). Two frames differ by a unit
(`IsFrame.exists_unit`).

Design: Cartier divisors, regular sections, ideals of zeros and orders of rational sections are all
ring-theoretic statements after taking coordinates in a frame. A frame is a `Prop` (a condition on a
section) carrying no categorical isomorphism, restriction to a smaller open is `rfl`-level, and
coordinates are elements of `Γ(X, W')` on which ring computations can be done directly. The parts not
depending on `IsLineBundle` (`res`, `IsFrame`, `coordEquiv`/`coord` and their lemmas) live in
`ModuleSheafFrame`, which depends only on Mathlib; this file contains the existence theorems that need
`IsLineBundle`.

Reference: Stacks 01CR (an invertible sheaf is locally generated by one section).
-/

set_option autoImplicit false
set_option maxHeartbeats 400000

universe u

open CategoryTheory Opposite TopologicalSpace

noncomputable section

namespace AlgebraicGeometry.Scheme.Modules

set_option backward.isDefEq.respectTransparency false

variable {X : Scheme.{u}}

/-- A trivialization gives a frame: `e := φ⁻¹(1)`. -/
theorem Trivialization.exists_isFrame {M : X.Modules} (t : Trivialization M) :
    ∃ e : Γ(M, t.carrier.ι ''ᵁ ⊤), IsFrame M (t.carrier.ι ''ᵁ ⊤) e := by
  obtain ⟨V, φ⟩ := t
  refine ⟨(φ.inv.val.app (op ⊤) (1 : Γ(V.toScheme, ⊤)) : Γ(M, V.ι ''ᵁ ⊤)), ?_⟩
  intro W' h
  obtain ⟨O, rfl⟩ : ∃ O : V.toScheme.Opens, W' = V.ι ''ᵁ O :=
    ⟨V.ι ⁻¹ᵁ W', by
      rw [Scheme.Hom.image_preimage_eq_opensRange_inf]
      exact (inf_eq_right.mpr (h.trans (by simp))).symm⟩
  have hnat : (M.presheaf.map (homOfLE h).op
        (φ.inv.val.app (op ⊤) (1 : Γ(V.toScheme, ⊤)) : Γ(M, V.ι ''ᵁ ⊤)) : Γ(M, V.ι ''ᵁ O)) =
      φ.inv.val.app (op O) (1 : Γ(V.toScheme, O)) := by
    have := PresheafOfModules.naturality_apply φ.inv.val (homOfLE (le_top : O ≤ ⊤)).op
      (1 : Γ(V.toScheme, ⊤))
    have h1 : (ConcreteCategory.hom ((SheafOfModules.unit V.toScheme.ringCatSheaf).val.map
        (homOfLE (le_top : O ≤ ⊤)).op)) (1 : Γ(V.toScheme, ⊤)) = (1 : Γ(V.toScheme, O)) :=
      map_one (V.toScheme.presheaf.map (homOfLE (le_top : O ≤ ⊤)).op).hom
    exact this.symm.trans (congrArg _ h1)
  have key : ∀ r : Γ(X, V.ι ''ᵁ O),
      r • (M.presheaf.map (homOfLE h).op
        (φ.inv.val.app (op ⊤) (1 : Γ(V.toScheme, ⊤)) : Γ(M, V.ι ''ᵁ ⊤)) : Γ(M, V.ι ''ᵁ O)) =
      φ.inv.val.app (op O) (show Γ(V.toScheme, O) from r) := by
    intro r
    rw [hnat]
    have := (φ.inv.val.app (op O)).hom.map_smul (show Γ(V.toScheme, O) from r) (1 : Γ(V.toScheme, O))
    have h2 : (show Γ(V.toScheme, O) from r) • (1 : Γ(V.toScheme, O)) = (show Γ(V.toScheme, O) from r) :=
      mul_one _
    refine Eq.trans ?_ (this.symm.trans (congrArg _ h2))
    have hs : ∀ y : Γ(M.restrict V.ι, O), (show Γ(V.toScheme, O) from r) • y =
        (((V.ι.appIso O).inv (show Γ(V.toScheme, O) from r) : Γ(X, V.ι ''ᵁ O)) •
          (show Γ(M, V.ι ''ᵁ O) from y) : Γ(M, V.ι ''ᵁ O)) := fun _ => rfl
    have hr : ((V.ι.appIso O).inv (show Γ(V.toScheme, O) from r) : Γ(X, V.ι ''ᵁ O)) = r := by
      rw [Scheme.Opens.ι_appIso]; rfl
    refine Eq.trans ?_ (hs _).symm
    rw [hr]
  have hbij : Function.Bijective (φ.inv.val.app (op O)) := by
    refine Function.bijective_iff_has_inverse.mpr ⟨φ.hom.val.app (op O), fun x => ?_, fun x => ?_⟩
    · exact ConcreteCategory.congr_hom
        (congrArg (fun k : SheafOfModules.unit V.toScheme.ringCatSheaf ⟶ _ => k.val.app (op O))
          φ.inv_hom_id) x
    · exact ConcreteCategory.congr_hom
        (congrArg (fun k : M.restrict V.ι ⟶ _ => k.val.app (op O)) φ.hom_inv_id) x
  show Function.Bijective (fun r : Γ(X, V.ι ''ᵁ O) => r • (M.presheaf.map (homOfLE h).op _ : Γ(M, V.ι ''ᵁ O)))
  rw [funext key]
  exact hbij

/-- Local frames of a line bundle: every point has an open neighbourhood `W` and a frame on `W`. -/
theorem exists_frame (M : X.Modules) [M.IsLineBundle] (p : X) :
    ∃ (W : X.Opens) (_ : p ∈ W) (e : Γ(M, W)), IsFrame M W e := by
  obtain ⟨t, hp⟩ := IsLineBundle.exists_trivialization M p
  obtain ⟨e, he⟩ := t.exists_isFrame
  exact ⟨t.carrier.ι ''ᵁ ⊤, by simpa using hp, e, he⟩

/-- The frame can be chosen inside any given open neighbourhood. -/
theorem exists_frame_le (M : X.Modules) [M.IsLineBundle] {U : X.Opens} {p : X} (hp : p ∈ U) :
    ∃ (W : X.Opens) (_ : W ≤ U) (_ : p ∈ W) (e : Γ(M, W)), IsFrame M W e := by
  obtain ⟨W, hpW, e, he⟩ := exists_frame M p
  exact ⟨W ⊓ U, inf_le_right, ⟨hpW, hp⟩, _, he.restrict inf_le_left⟩

/-- The frame can be chosen on an affine open (affine opens form a basis of the topology). -/
theorem exists_affine_frame_le (M : X.Modules) [M.IsLineBundle] {U : X.Opens} {p : X} (hp : p ∈ U) :
    ∃ (W : X.Opens) (_ : IsAffineOpen W) (_ : W ≤ U) (_ : p ∈ W) (e : Γ(M, W)), IsFrame M W e := by
  obtain ⟨W, hWU, hpW, e, he⟩ := exists_frame_le M hp
  obtain ⟨_, ⟨W₁, hW₁, rfl⟩, hpW₁, hW₁W⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open hpW W.isOpen
  exact ⟨W₁, hW₁, le_trans hW₁W hWU, hpW₁, _, he.restrict hW₁W⟩

end AlgebraicGeometry.Scheme.Modules

end
